### ISSUE TITLE
Mengennotierung und Preisnotierung: Einstellungen->Darstellung Beispiele sind falsch

### ISSUE THREAD

**Issue by sponiro** [buchen/portfolio#1000]
Unter Einstellungen->Darstellung gibt es eine kurze Erklärung zu Mengennotierung und Preisnotierung. Darunter sind einige Beispiele. Diese sind jedoch teilweise falsch. Es müssen in beiden Beispielen die Einheiten invertiert werden damit es passt. 

Es müsste dort stehen:
Mengennotierung: USD/EUR 1,1232

und

Preisnotierung: EUR/USD 0,89

Nebenbei, wieso ist der Titel des Fensters "Benutzervorgaben" aber im Menü klickt man auf "Einstellungen..." um dahin zu gelangen?

**Comment by sponiro** [comment]
Die Notation verwendet den Bruchstrich nicht im mathematischen Sinn. Gemeint ist "von einer Einheit der Währung" / "zu x Einheiten der anderen Währung". Ist wohl so üblich und daher richtig.

**Comment by buchen** [comment]
> Nebenbei, wieso ist der Titel des Fensters "Benutzervorgaben" aber im Menü klickt man auf "Einstellungen..." um dahin zu gelangen?

Ist mir noch nie aufgefallen... Der Dialog kommt aus dem Eclipse Framework (ich muss nur die Seiten programmieren) und anscheinend ist das so übersetzt worden. Das kann ich leicht ändern.

> Die Notation verwendet den Bruchstrich nicht im mathematischen Sinn.

Ich habe das zunächst auch "mathematisch" programmiert... und habe dann im Forum Feedback von den Forex Usern erhalten 😄
