### ISSUE TITLE
GTK+3: Starkes Flackern in der App

### ISSUE THREAD

**Issue by Necoro** [buchen/portfolio#1004]
Nachdem nun die neue Webkitversion unterstützt wurde (s. #769), habe ich bei mir testhalber auf die Verwendung von GTK+3 umgestellt. Dabei ist (bei mir) PP momentan nicht nutzbar, das ganze Fenster flackert bei Mausbewegungen.

Screen-Capture-Video folgt.

**Comment by Necoro** [comment]
Da gibt es auch schon einen Eclipse-Bug, der das ganze aber nicht eingrenzt: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517671

**Comment by mherweg** [comment]
I suffer from the same bug. it did get worse recently: scrollbars flicker in red color

**Comment by buchen** [comment]
Did you try ```GTK_IM_MODULE=ibus``` mentioned in the bug linked above?

**Comment by robert-franz** [comment]
I do have the same problem. But using the  `SWT_GTK3=0 ./PortfolioPerformance` solves the problem.

**Comment by rodrigograca31** [comment]
The app was flickering really bad for me (unusable) on Linux Mint 19.2 Cinnamon (everything updated)

`SWT_GTK3=0 ./PortfolioPerformance` solved it for me. 

seems `GTK_IM_MODULE=ibus` also solves it.

**Comment by Necoro** [comment]
After setting up a new system w/o any usable gtk2 webkit-gtk, unsetting my ooold `GTK_IM_MODULE=xim` did indeed work.

Not a Portfolio Bug, hence.

**Comment by emilrueh** [comment]
Hi, just installed on Arch Linux and the flickering makes it unusable. Setting either of the two env vars mentioned in my bashrc does not seem to do anything.

Anyone having the issue and a fix?
