### ISSUE TITLE
Release ohne JDK-Bundle

### ISSUE THREAD

**Issue by SebRut** [buchen/portfolio#1006]
Ich hab Portfolio Performance mal als [Chocolatey Package](https://chocolatey.org/packages/portfolio) gepackt. Leider erstellt der dortige Installer automatisch Symlinks zu allen .exe-Dateien im Zielpfad, also auch zu der javaw.exe etc. im JDK-Bundle. Auschließen lassen sich diese leider nur explizit, was eine manuelle Änderung bei jedem JDK-Update nötig macht. Wäre es möglich wieder eine Variante ohne JDK anzubieten?

**Comment by buchen** [comment]
> Wäre es möglich wieder eine Variante ohne JDK anzubieten?

Auch auf Windows baue ich das auch ohne JRE. Die kann ich auch auf bintray hochladen. Mache ich heute Abend.

Ich habe das JRE eingepackt, weil es viele Probleme auf Windows gibt das richtig JRE in der richtigen Bit Version zu installieren, etc. Und weil Benutzer teilweise sehr alte JRE verwendet haben, die dann z.B. keine Let's Encrypt Zertifikate unterstützen etc. Kann man bei den Chocolatey Abhängigkeiten definieren?

Das JRE werde ich wohl eher selten ändern. Allerdings musste ich es jetzt ein paar Mal patchen bis es auf alle Plattformen richtig tut.

**Comment by SebRut** [comment]
> Kann man bei den Chocolatey Abhängigkeiten definieren?

Kann man, hab im Moment die JDK 8 drin, wenn alles richtig hinhaut wird automatisch die 64bit-Version von PP und JDK8 installiert.

**Comment by buchen** [comment]
Ich habe die ZIP Dateien ohne JRE hier hochgeladen:
https://bintray.com/buchen/downloads/portfolio-performance/0.33.1?sort=&order=#files/0.33.1

**Comment by SebRut** [comment]
> Ich habe die ZIP Dateien ohne JRE hier hochgeladen:
https://bintray.com/buchen/downloads/portfolio-performance/0.33.1?sort=&order=#files/0.33.1

Danke, hab vorher noch nicht mit Bintray gearbeitet, kann ich davon ausgehen, dass neuere Releases ein ähnliches URL-Schema haben? (normaler DL-Link ohne "-distro" in der Mitte)?

**Comment by buchen** [comment]
> kann ich davon ausgehen, dass neuere Releases ein ähnliches URL-Schema haben?

Erstmal ja. Ich habe es gescripted, es sollte das gleiche Schema bleiben.

Allerdings bin ich erst vor kurzem zu Bintray gewechselt. Ich will nicht ausschliessen, dass ich die Binaries irgendwann noch mal wieder umziehe.

**Comment by buchen** [comment]
>  (normaler DL-Link ohne "-distro" in der Mitte)?

Das mit und ohne "-distro" bleibt auch.
