### ISSUE TITLE
Gesamterträge lassen sich nicht im Diagramm darstellen

### ISSUE THREAD

**Issue by Anth0rx** [buchen/portfolio#1024]
### Problem:
Man kann sich zwar unter **Berichte >> Vermögensaufstellung >> Diagramm** die Dividenden und Zinsen einzeln anzeigen lassen, allerdings fehlt die Möglichkeit sich die Erträge als Summe aus Zinsen und Dividenden anzeigen lassen zu können.

### Lösung:
Eine neue Datenreihe hinzufügen, welche die Erträge abbildet.

**Comment by Anth0rx** [comment]
@buchen Wo könnte man solch eine Datenreihe erstellen?

**Comment by Anth0rx** [comment]
Alles klar, keine Eile. Gibt es eine Dokumentation für Entwickler? Ich tue mir momentan noch ein bisschen schwer damit einen Überblick zu bekommen.

**Comment by buchen** [comment]
Done. Kommt mit der nächsten Version.

> Gibt es eine Dokumentation für Entwickler? 

Leider nein. Das README vom Repository erklärt wie man Eclipse aufsetzt. Darüber hinaus gibt es nicht viel. Einiges erklärt sich, wenn man Eclipse RCP kennt. Ansonsten versuche ich die Rechnungen von dem GUI durch die zwei Projekte "name.abuchen.portfolio" und "n.a.portfolio.ui" zu trennen.
