### ISSUE TITLE
Eclipse und die babel Addons

### ISSUE THREAD

**Issue by Ragas13** [buchen/portfolio#1029]
Ich kämpfe seit Wochen damit Eclipse mit PP wieder zum laufen zu bekommen. Alles wie im Manual beschrieben kompiliert und die Platform in Eclipse zugewiesen aber die Babel Plugin's fehlen, selbst wenn ich "fehlende Plugins" nachinstallieren möchte. 

Auch habe ich bereits versucht diese als zusätzliche Software nachzuinstallieren oder direkt die Language Pakete in das Plugin Verzeichnis zu kopieren.

Wenn ich über MAVEN das Projekt kompiliere, klappt alles ohne Probleme und das generierte Programm lässt sich ausführen. Nur Eclipse beschwert sich wegen den fehlenden Plugins.

An Java Versionen habe ich bereits die 8er bis 10er getestet sowie Eclipse Neon, Oxygen und Photon. Nur MAVEN muss ich noch ausprobieren da unter 3.5.2 hat es mE noch funktioniert, seit ich 3.5.4 verwende tritt evtl. dieses Problem auf.

**Comment by buchen** [comment]
> die Babel Plugin's fehlen

Wo fehlen die? In der Target Platform?

(Die Babel Archive ziehen ab und an mal um. Wenn das dann nicht gecacht ist, könnte es schief gehen).

Poste mal einen Screenshot wo und wie Du den Fehler siehst.

**Comment by Ragas13** [comment]
OK, Fehler gefunden und darauf hat mich dieser Beitrag gebracht:
https://www.eclipse.org/forums/index.php?t=msg&th=488516&goto=1147222&#msg_1147222

Ich bin also in die Run Configuration rein, unter "PP > Plug-Ins" und die notwendigen Addons über "Add Required Plug-Ins" erneut ausgewählt. Da jetzt die "Portfolio Performance.launch" von deiner geringfügig abweicht habe ich diese auf ignore für den GIT upload gesetzt^^

1000 Dank und VG
Marco
