### ISSUE TITLE
Fehler beim Anlegen eines Wertpapiersparplan

### ISSUE THREAD

**Issue by davitfaenglae** [buchen/portfolio#1032]
Wenn man einen neuen Wertpapaiersparplan anlegt, ist das DropDown Feld Wertpapier zu klein um etwas auszuwählen. Auch wenn man das Fenster größer zieht oder Vollbild macht wird es nicht größer
<img width="526" alt="bildschirmfoto 2018-09-21 um 23 36 02" src="https://user-images.githubusercontent.com/38737065/45907148-216a8180-bdf7-11e8-90b9-9bbcac895b28.png">

Version 0.34.1 (macosx, x86_64)

**Comment by cmaoling** [comment]
Ich kann das nur (mit linux_x86) reproduzieren, wenn ich keine Wertpapiere angelegt habe. Die Breite der Auswahlbox richtet sich nach der Länge des längsten Namens...
Ein Screenshot der Wertpapierliste würde zum weiteren Debug helfen.

**Comment by davitfaenglae** [comment]
Ah alles klar das war der Fehler. Ich hatte noch kein Wertpapier angelegt, deswegen konnte ich nichts auswählen. Habe jetzt mal ein Wertpapier angelegt und es funktioniert jetzt.

Danke.
