### ISSUE TITLE
PDF-Import VIAC Schweiz

### ISSUE THREAD

**Issue by bretzel15** [buchen/portfolio#1036]
Hallo zusammen,

ich nutze schon länger mit grosser Freude PP, und bin mit der “deutschen Seite” sehr zufrieden. Seit einigen Monaten bin ich nun aber Kunde bei VIAC (www.viac.ch), einem Schweizer Säule 3a Anbieter, und würde dort gerne die monatlichen Buchungen in PP importieren. Mit 8 Buchungen pro Monat, Fremdwährung inklusive, wäre die Automatisierung schon super! Hat irgendjemand den Import schon erledigt? Ansonsten würde ich mich, vielleicht mit Hilfe von erfahrenen Leute, daran machen.

Link zum Forum: [https://forum.portfolio-performance.info/t/pdf-import-viac-schweiz/3708](https://forum.portfolio-performance.info/t/pdf-import-viac-schweiz/3708)

Hier noch ein Beispieldokumente mit Fremdwährung, Gebühren und Steuern:

PDF Author: 'motth' 
PDFBox Version: 1.8.13
-----------------------------------------
Terzo Vorsorgestiftung der WIR Bank
Auberg 1
4002 Basel
Internet www.viac.ch
E-Mail info@viac.ch
Telefon 0800 80 40 40
Kunde 1.234.567.890 Herr
Portfolio 1.234.567.890.01 Max Mustermann
Musterweg 12
1234 Schweiz
Basel, 05.07.2018
Börsenabrechnung - Kauf
Wir haben für Sie folgenden Auftrag ausgeführt:
Order: Kauf
1.369 Ant iShares Core S&P500
ISIN: IE00B5BMR087
Kurs: USD 262.51
Betrag USD 359.27
Umrechnungskurs CHF/USD 1.00195 CHF 359.98
Stempelsteuer CHF 0.46
Verrechneter Betrag: Valuta 05.07.2018 CHF 360.43
S. E. & O.
Freundliche Grüsse
Terzo Vorsorgestiftung
Anzeige ohne Unterschrift

**Comment by buchen** [comment]
@bretzel15 Ich habe einen ersten Wurf implementiert.

Kannst Du mal ausprobieren:
[win 64bit](https://www.dropbox.com/s/q4ye8l5b91xqv9f/PortfolioPerformance-distro-0.39.1-SNAPSHOT-win32.win32.x86_64.zip?dl=0)
[win 32bit](https://www.dropbox.com/s/t5ubvbyels6n85w/PortfolioPerformance-distro-0.39.1-SNAPSHOT-win32.win32.x86.zip?dl=0)
[macOS](https://www.dropbox.com/s/wnewwq055d7qowt/PortfolioPerformance-distro-0.39.1-SNAPSHOT-macosx.cocoa.x86_64.tar.gz?dl=0)

(Das sind Dropbox Links - im UI oben rechts "Herunterladen" wählen)

**Comment by bretzel15** [comment]
Vielen Dank. Funktioniert in den meisten Fällen, nur bei einigen Abrechnungen mit zwei Währungen hatte ich in meiner Testdatei Probleme. Liegt aber eher an meiner Testdatei (EUR als Basiswaehrung, Konto in CHF und Kauf in USD) als am Importer...

**Comment by nikorosberg** [comment]
Thanks for the work on this - was also looking for currency conversion help which seems to still be an issue. Looking at this [viac review](https://investinghero.ch/viac-review) there isn't much in the way of support, I will try contacting them directly.
