### ISSUE TITLE
Sortierung "Betrag" bei Auslandswährungen falsch

### ISSUE THREAD

**Issue by Moosbueffel** [buchen/portfolio#1037]
Sortiert man die Spalte Betrag in einer Auslandswährung z.B. USD, so wird nach absolutem Betrag sortiert [Funktion ABS()] und nicht nach dem Betrag d.h. positive und negative Werte werden nicht unterschieden.

Bei Konten in EUR ist die Sortierung richtig.

**Comment by buchen** [comment]
Um welche Ansicht geht es genau? Die Liste der Konten? Oder die Liste der Buchungen in einem Portfolio?

**Comment by Moosbueffel** [comment]
In der Kontenansicht
![grafik](https://user-images.githubusercontent.com/7726457/46300951-41dbce00-c5a5-11e8-882d-896f2ab7ae65.png)

**Comment by tomcastro89** [comment]
Hi Andreas,
ich habe das Problem behoben.
Dadurch das intern ein Amount nur positiv ist, reicht es nicht diesem zum Vergelcih herzuziehen.
Ich musste vorher den Amount anpassen indem ich die nach dem Type der Transaktion frage (isDebit()?

Ich habe leider keinen Test dafür geschrieben, in diesem Fall war die Änderung trivial.
Theoretisch könnte man diese Logik zur Transaction auslagern, aber ich vermute das es so gewollt ist das ein Amount so ist. Die Banken machen das ja so mit Haben/Soll etc.

Das Ganze habe ich im Rahmen von einem Hacktoberfest gemacht https://hacktoberfest.digitalocean.com/
https://www.meetup.com/de-DE/Coding-Dojo-Rhein-Main/events/254752507/

Schöne Grüße !!

Pull-Request:
https://github.com/buchen/portfolio/pull/1039

**Comment by buchen** [comment]
Vielen Dank! Ist drin.
