### ISSUE TITLE
PDF Import Consors

### ISSUE THREAD

**Issue by dr2okevin** [buchen/portfolio#1044]
Ich kann einige Ausführungen der Aktien Sparpläne bei Consors nicht importieren. Scheint nur solche zu betreffen bei denen die WKN nur aus Zahlen besteht.

Fehlermeldung:
Nur 2 von 3 Pattern erkannt: [^(Wertpapier|Bezeichnung) WKN ISIN$, ^(?<name>.*)(?<wkn>[^ ]*)$, (Kurs|Preis pro Anteil) (\d+,\d+) (?<currency>\w{3}+).*] (KAUF_8388******_ord133*****_001_wkn906866_dat20181015_id73024******.pdf)

**Comment by buchen** [comment]
Ohne Beispiel ist das schwer zu beurteilen.

Das dritte nicht erkannte Pattern ist ```(Kurs|Preis pro Anteil) (\d+,\d+) (?\w{3}+)``, also eine Text, dann ein Betrag, dann eine Währung.

Es kann aber auch sein, dass der Matcher verrutscht. Um das sagen zu können, brauchen wir ein Beispiel. Am einfachst über PP -> Datei -> Importieren -> Debug: Text aus PDF generieren. Dann Deine persönlichen Daten überschreiben und hier posten.

> denen die WKN nur aus Zahlen besteht.

Das sieht mir nicht danach aus. Die WKN darf aus beliebigen Zeichen bestehen.

**Comment by dr2okevin** [comment]
```
PDF Author: 'Consorsbank' 
PDFBox Version: 1.8.13
-----------------------------------------
Consorsbank • 90318 Nürnberg
Depotnummer 0000000000
0000000000/00
Kevin ABCDEFGHI
Straße 12
12345 Ort Vermerk der Bank 1000
02
ORDERABRECHNUNG
KAUF AM 15.10.2018  UM 08:05:51 SPARPLAN NR. 000000000.001
Bezeichnung WKN ISIN
AMAZON.COM INC.    DL-,01 906866 US0231351067
Einheit Umsatz
ST 0,19084
Kurs 1.548,790000 EUR P.ST.  
Kurswert EUR 295,57
Provision EUR 4,43
Wert 17.10.2018 EUR 300,00
zulasten Konto-Nr. 0000000000
Bestand zugunsten Girosammelverwahrung 
CBF 2126
Die Order wurde an folgender Börse gehandelt: MUENCHEN
Sparplanname: Aazon                    
Beratungsfreies Geschäft
Hinweis für Orderabrechnungen und Depotbuchungsanzeigen:
Einwendungen wegen Unrichtigkeit oder Unvollständigkeit dieser Mitteilung müssen unverzüglich erhoben werden, vgl. Nummer B. Ziffer I. 11 (4) und (5) der
Allgemeinen Geschäftsbedingungen (AGB Banken).
Machen Sie Ihre Einwendungen in Textform geltend, genügt die Absendung innerhalb der Sechs-Wochen-Frist an die Consorsbank oder per Fax oder Mail an die
unten angegebenen Adressen. Das Unterlassen rechtzeitiger Einwendungen gilt als Genehmigung.
Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).
Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929
Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de
Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449
Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé
```

**Comment by cmaoling** [comment]
Ha! Der Tausenderpunkt war meine erste Idee. Hätte aber dann die WKN geprüft und die Wärme unter 1000€...
Das Problem hatte ich auch und auch gefixt aber scheinbar keinen Pullrequest gemacht. Muss Mal in meinem Repo nachschauen...

**Comment by cmaoling** [comment]
Das war die Änderung von mir im PDFExtractor: @buchen kann man das eine File vielleicht cherrypicken? 😁https://github.com/cmaoling/portfolio/commit/268a2b2bfbf0c1e05b548cedfa0eda2463cb5765#diff-9c1b30062fb791acaf9514a5d9af0e7a

**Comment by buchen** [comment]
> kann man das eine File vielleicht cherrypicken?

Gute Idee! Das war super einfach. Ist drin.

Wegen den falsch gerundeten Zahlen in der Heatmap baue ich vermutlich morgen eine neue Version.
