### ISSUE TITLE
Fehler beim Aufsetzen der eclipse-Projekte

### ISSUE THREAD

**Issue by rryi** [buchen/portfolio#1054]
Hallo!

Würde gern in/mit portfolio entwickeln und habe dazu
 - eclipse frisch installiert (neueste Release also SimRel 2018‑09, Paket mit DSL, das enthält auch PDE) 
 - https://github.com/buchen/portfolio.git geclont (nur den branch "master") und Projekte importiert: via eclipse "import projects from git"
 - "mvn clean install -Dgenerate-target-platform=true -Dtycho.disableP2Mirrors" ausgeführt
 - in eclipse refresh via F5 ausgeführt.

der mvn Lauf läuft im Test auf genau einen Fehler, und sagt dann dass diverses geskippt wurde.  Siehe anhang mvn init fehler.txt.
[mvn init fehler.txt](https://github.com/buchen/portfolio/files/2522603/mvn.init.fehler.txt)

In Eclipse sind danach diverse Projekte fehlerhaft, Im Source habe ich einige angeschaut. Sehr häufig fand ich fehlerhafte Imports des Typs "import org.eclipse.nebula...".  In der Projektkonfiguration werden keine Fehler angezeigt - Jar-s scheinen also nicht zu fehlen, aber eclipse kann die .class files im Import nicht finden. 

In Datei "eclipse fehler.txt"  habe ich die Fehlerliste angehängt.
[eclipse fehler.txt](https://github.com/buchen/portfolio/files/2522613/eclipse.fehler.txt)

JDK/JRE sind java version "1.8.0_121", System Windows 1803, alles 64 bit.

Meine erste Idee ist, dass die vielen Fehler Folge der übersprungenen mvn Befehle sind, weil die Initialisierung unvollständig ist. Dann reicht es ggf. den gescheiterten Test "InvestmentPlanTest.testNoGenerationWithStartInFuture" zu korrigieren.

Würde mich dazu über Unterstützung sehr freuen - Ihr Projekt finde ich sehr spannend, da würde ich gern tiefer einsteigen.

MfG
R. Rudolph

**Comment by buchen** [comment]
Hi @rryi,

meine These: weil der Test fehlgeschlagen ist, ist die Target Platform nicht generiert worden. Weil die Target Platform nicht generiert worden ist, fehlen die abhängigen Bibliotheken.

Ich habe keine Ahnung warum der Test fehlschlägt. Bei mir tut er 😄 - wie Programmierer immer gerne sagen. Und auch [Travis](https://travis-ci.org/buchen/portfolio/branches) meckert gerade nicht.

Lass doch Maven mal mit ```-DskipTests``` laufen damit die Tests übersprungen werden.

> in eclipse refresh via F5 ausgeführt.

Nur Refresh reicht nicht. Du musst, wie im README beschrieben, die Target Platform auch konfigurieren: https://github.com/buchen/portfolio#set-target-platform

**Comment by buchen** [comment]
(Und ich muss mal rausfinden warum der Test fehlschlägt. @cmaoling  hat das in #1049 ebenfalls schon bemerkt. And der Systemsprache liegt es nicht: sowohl Deutsch als auch English funktioniert 🤔 ).

**Comment by buchen** [comment]
(Test gefixt. Das Problem war wohl eine Abhängigkeit zu dem Wochentag an dem der Test lief...)

**Comment by rryi** [comment]
Danke für die schnelle Abhilfe!

Nach git fetch, erneutem Holzhammer "mvn clean install -Dgenerate-target-platform=true -Dtycho.disableP2Mirrors" und target platform config haben die eclipse Projekte jetzt keine Fehler mehr.
