### ISSUE TITLE
Beim Löschen von Wertpapier wird Placeholder nicht ersetzt

### ISSUE THREAD

**Issue by PatrickLerner** [buchen/portfolio#1055]
Löscht man ein Wertpapier, so gibt es den Placeholder `{0}`, welcher vermutlich den Namen des Wertpapiers enthalten sollte:

<img width="531" alt="screenshot 2018-10-29 at 23 31 53" src="https://user-images.githubusercontent.com/1738261/47684397-0e578800-dbd3-11e8-8272-db03a1077cb0.png">

Dieser wird, wie hier zu sehen nicht ersetzt.

**Comment by buchen** [comment]
fixed
