### ISSUE TITLE
JavaDoc für Portfolio Performance?

### ISSUE THREAD

**Issue by Ragas13** [buchen/portfolio#1064]
Hallo Andreas, 

besteht evtl. die Möglichkeit für PP JavaDoc zur Verfügung zu stellen?

Sicher, PP wird regelmäßig erweitert so das der manuelle Arbeitsaufwand too much sein dürfte. Bei meiner Suche nach einer Lösung dieses Problems bin ich auf https://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/ gestoßen.

In diesem Beitrag wird beschrieben wie mittels Travis CI i. V. m. GitHub automatisch auf der aktuellen Master Branch das JavaDoc aufgebaut und bei GitHub automatisch veröffentlicht wird.

Vielleicht hilft dies ja dem ein oder anderen dich beim programmieren zu unterstützen?!

Gruß 
Marco

**Comment by buchen** [comment]
Ich selber nutze Javadoc - auch von anderen Projekten - so gut wie nie. In der IDE werden mir die Kommentare ja dynamisch angezeigt - entweder über F2 oder bei der Code Completion. Darum habe ich selber nie den Bedarf auf eine separate Javadoc Seite zu gehen. Und der erste Schritt ist ja seine Eclipse IDE aufzusetzen.

Dann habe ich die Javadoc gerade mal lokal generiert. Ganz ehrlich - die sind quasi leer. Es sind so wenige Kommentare, dass ich nicht sicher bin ob jemanden das hilft. Ich versuche bei neuen Klassen besser zu werden und füge Kommentare hinzu...

Der Trick die über Travis und GitHub Pages ist nicht schlecht. Ich nutze für die Homepage/Hilfe https://netlify.com (super einfach) und mit sowas wie Orchid kann man wohl auch einfach Javadoc publizieren: https://orchid.netlify.com/plugins/OrchidJavadoc

**Comment by Ragas13** [comment]
Ah ok, dass macht Sinn.Ich kam eigentlich nur auf diese Idee da ich es bei anderen Projekten gesehen habe, aber nicht hinterfragt ob es wirklich genutzt wird. Bei API`s macht dies sicherlich sinnig sein, für komplexe Programme eher nicht. CLOSED
