### ISSUE TITLE
Release 0.36.0: Fehlerhafte Anzeige im Reiter "Statement of Assets" in den Spalten mit absoluter Performance, vermutlich durch Währungskonversion

### ISSUE THREAD

**Issue by FabianSchuessler** [buchen/portfolio#1070]
Nach dem Update auf 0.36.0 wird bei mir im Reiter "Statement of Assets (Standard)" in den Spalten mit absoluter Performance fehlerhafte Informationen angezeigt, komischerweise nur bei einem Wertpapier. Gefühlte zwei Dezimalstellen zuviel. Eventuell könnte es daran liegen, dass das Wertpapier in USD fixiert ist. Nach Prüfung der historischen Daten des Wertpapier und meiner Transaktionen komme ich zu dem Schluss, dass ein Bug eingeführt worden sein muss mit dem neusten Release. Vorher hat es ja auch funktioniert. Selbst ein Neuladen der historischen Daten war nicht zielführend.

**Comment by buchen** [comment]
Ist das unter *Performance -> Berechnung*? Und ist das die Prozentzahl oder der absolute Wert? Was ist mit dem Berichtszeitraum? Ein Jahr?

Bei mir schaut das erst mal okay aus...

**Comment by hintz** [comment]
Kann diesen Bug bestätigen.
Öffnen des selben portfolio XML files mit 0.35.1 und 0.36 zeigt komplett verschiedene Werte in absolute Performance Spalten, z.b. einer Spalte "Capital Gains (FIFO) 1 day".
Die Werte in 0.36 sind falsch.

**Comment by buchen** [comment]
Ich stehe noch etwas auf dem Schlauch... sorry... ich versuche das gerade an der *kommer* Beispieldatei nachzuvollziehen.

Siehe die beiden Screenshots unten - immer auf *2018* bezogen.

Für alle Wertpapiere ohne irgendwelche Dividenden oder Steuern sind die Werte identisch. Bei den anderen Werten muss man ein bisschen rechnen weil Kursgewinne, Erträge und Steuern separat ausgewiesen werden.

Zum Beispiel für den *iShares FTSE EPRA/NAREIT Global Property*:
Kursgewinn -3,92 + Erträge 242,15 - Steuern 27,57 = 210,66 absolute Performance

Kannst Du den Fehler bei Dir in der *kommer* Datei nachstellen?

<img width="937" alt="bildschirmfoto 2018-12-18 um 09 00 20" src="https://user-images.githubusercontent.com/587976/50140409-e916fa00-02a4-11e9-9d81-918b634429cf.png">

<img width="461" alt="bildschirmfoto 2018-12-18 um 09 00 24" src="https://user-images.githubusercontent.com/587976/50140411-eb795400-02a4-11e9-83e6-0913fb6f4ab0.png">

**Comment by hintz** [comment]
Der Fehler tritt nur in "absolute Performance" Spalten auf mit kürzerem Zeitfenster auf, etwa 1 day / 30 days.
Allerdings kann ich den Bug in kommer.xml nicht reproduzieren. Vielleicht kann ich ein minimales Beispiel konstruieren.

**Comment by buchen** [comment]
> Allerdings kann ich den Bug in kommer.xml nicht reproduzieren. Vielleicht kann ich ein minimales Beispiel konstruieren.

Das wäre super. Oder aus Deiner Datei alle anderen Wertpapiere / Buchungen löschen und mir per Email an *portfolio dot performance dot help at gmail dot com* schicken.

**Comment by hintz** [comment]
Das Problem scheint bei mir aufzutreten wenn die selbe Security in verschiedenen Accounts gehalten wird. Habe per mail in minimal example geschickt.

**Comment by buchen** [comment]
@FabianSchuessler trifft diese Situation auch auf Dich zu? Das Problem betrifft Wertpapiere die in mehreren Depots gehalten werden.

**Comment by buchen** [comment]
Ja, mit diesem Fix ist auch Dein @FabianSchuessler Problem gelöst. Ich baue einen Fix.
