### ISSUE TITLE
Have there been any attempts to at a web version?

### ISSUE THREAD

**Issue by lenucksi** [buchen/portfolio#1072]
Hi,

thanks for Portfolio Performance!

Given that PP is an Eclipse RCP application, has anyone considered using the Eclipse RAP [1] to provide a web platform on the base of the existing PP codebase?
Having a constantly running version that could in the end maybe even do automatic imports of data in the background at some point and would present everything using a web client could be pretty nice. 

It looks like RAP would support larger parts of the e4 platform. [2]

[1] https://www.eclipse.org/rap/ 
[2] https://www.eclipse.org/rap/incubator/
https://www.eclipse.org/efxclipse/index.html

**Comment by buchen** [comment]
I have not attempted to create a web version and, to be honest, I have no plans to do so.

Thomas from the forum is in the process of building a mobile version:
https://forum.portfolio-performance.info/t/alpha-tester-fuer-mobile-portfolio-app-gesucht/3826
