### ISSUE TITLE
Kann PP nicht bauen/starten

### ISSUE THREAD

**Issue by keszocze** [buchen/portfolio#1075]
Moin und frohes Neues!
Ich wollte mich gerade daran machen, ein wenig weiter an PP herumzubasteln und habe Probleme, es unter Linux auf der Konsole zu bauen. Ich habe frisch geklont, `export MAVEN_OPTS="-Xmx1g"` ausgeführt und versuche mittels `mvn install -Dtycho.disableP2Mirrors` PP zu bauen. Das schlägt nun leider fehl, da keine Tests ausgeführt werden können:

```[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Portfolio Performance 0.36.2-SNAPSHOT .............. SUCCESS [  0.296 s]
[INFO] name.abuchen.portfolio ............................. SUCCESS [  3.458 s]
[INFO] name.abuchen.portfolio.tests ....................... FAILURE [ 26.518 s]
[INFO] name.abuchen.portfolio.ui .......................... SKIPPED
[INFO] name.abuchen.portfolio.ui.tests .................... SKIPPED
[INFO] name.abuchen.portfolio.bootstrap ................... SKIPPED
[INFO] name.abuchen.portfolio.feature ..................... SKIPPED
[INFO] portfolio.product 0.36.2-SNAPSHOT .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:38 min
[INFO] Finished at: 2019-01-05T16:11:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:1.3.0:test (default-test) on project name.abuchen.portfolio.tests: No tests found. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:1.3.0:test (default-test) on project name.abuchen.portfolio.tests: No tests found.
```
Ich habe deshalb versucht, kein `install`, sondern nur ein `package` durchzuführen. Damit kannst ich zwar ein binary erzeugen, dieses aber nicht starten. Im zugehörigen Logfile finden Zeilen der Art

```
!SESSION 2019-01-05 16:25:49.085 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2019-01-05 16:25:50.668
!MESSAGE Application error
!STACK 1
java.lang.Error: Unresolved compilation problems: 
	The import javax.inject cannot be resolved
	The import org.eclipse cannot be resolved
	The import org.eclipse cannot be resolved
 [...]
```

Falls das hilft, kann ich den `install` build log und den vollständigen Fehlerlog anhängen.

Meine Fragen nun:
* was mache ich falsch?
*  ist es irgendwie einfach möglich, die Tests aus dem `install` target zu entfernen?

**Comment by buchen** [comment]
Ebenfalls frohes Neues Jahr!! 😄 

Der Build an sich sollte tun - auf [Travis](https://travis-ci.org/buchen/portfolio) läuft er durch.

Ich vermute auch, dass ```name.abuchen.portfolio.tests: No tests found.``` eher ein Folgefehler ist. Konnten alle Dependencies korrekt aufgelöst werden? Gibt es Meldungen wenn die Target Platform aufgelöst wird?

Poste mal das komplette Log (ich glaube Du kannst das als TXT Datei an diesen Issue anhängen).

**Comment by keszocze** [comment]
Ich habe mit einem frischen `git clone` gestartet, und da funktioniert alles. Sobald ich jedoch in Eclipse im `portfolio-app` Projekt in der `portfolio-ide.target` Datei "set as target platform" auswähle, funktioniert das Bauen auf der Konsole nicht mehr (log hängt an). Manuelles Starten der Tests über "Run as" im `portfolio-app/eclipse` Order sagt auch, dass keine Tests gefunden werden. Außerdem habe ich 3766 Fehler (und 8 Warnings), die mir Eclipse anzeigt.

Mein workaround wäre, also Eclipse komplett zu ignorieren und anderweitig zu entwickeln und  dann auf der Konsole zu bauen, auch wenn das eher unbefriedigend ist.


[mvn_install.txt](https://github.com/buchen/portfolio/files/2735891/mvn_install.txt)

**Comment by buchen** [comment]
@keszocze - Der Build in Eclipse und der Build mit Maven sind mehr oder weniger unabhängig voneinander (leider).

Der Build in Eclipse braucht die *generierte* Target Platform.
Maven baut die sich aus den POM Dependencies selbständig zusammen.

> Mein workaround wäre, also Eclipse komplett zu ignorieren und anderweitig zu entwickeln und dann auf der Konsole zu bauen, auch wenn das eher unbefriedigend ist.

Das ist unpraktisch. Ich nutze ja das selbe Framework wie Eclipse IDE selbst. Und da lässt sich innerhalb der IDE viel einfacher entwicklen.

Also lass uns erst mal nach dem Maven Build schauen... und wenn die Target Platform generiert ist, nach dem Build in der IDE.

Aus dem Log werde ich noch nicht schlau. 😬 
Steht was in der Datei ```Expected eclipse log file: /home/keszocze/proggs/pp_git/name.abuchen.portfolio.tests/target/work/data/.metadata/.log```

Meine Vermutung wäre: vor ein paar Tagen hatten wir einen Dependency Issue bei dem die Tests und Java11 nicht ausgeführt werden könnten (da gab es einen Fehler in der Resolution). Bist Du mit Deinem Clone auf dem letzten Master? Mit welcher Java Version baust Du auf der Kommandozeile?

**Comment by keszocze** [comment]
Sry, dass ich das hier habe schleifen lassen. Ich bin jetzt wieder auf Bauen auf der Konsole mit Java 8 gewechselt. Das dauert zwar immer so um die fünf MInuten, ist dafür aber verlässlich.

Da ich keine Ahnung von Maven habe: Ist es irgendwie möglich, die targets (oder wie das bei Maven auch immer heißen mag) `name.abuchen.portfolio.tests`' und `name.abuchen.portfolio.ui.tests` auszuschalten? Die benötigen viel Zeit und ich verwende sie überhaupt nicht.
