### ISSUE TITLE
bug - Kursdiagramme zeigen nur noch fortlaufende Linien

### ISSUE THREAD

**Issue by Marfir** [buchen/portfolio#1086]
Ich habe einen Fehler entdeckt, der offenbar seit Weihnachten in PP schlummert. Die Kursdiagramme aller Aktien werden nicht mehr richtig gezeichnet. Es liegen zwar historische Kurse vor, aber trotzdem wird nur von einem Tag vor Weihnachten bis heute eine Linie gezogen. Zwischenzeitliche Kurs-Höhen und Tiefen sind nicht mehr sichtbar.

Bisher gefundener workaround:
Wenn ich auf Wertpapier editieren gehe und ohne etwas zu ändern den Dialog mit ok verlasse, wird das Kursdiagramm korrekt gezeichnet. Das ist aber absolut unpraktikabel das für alle Wertpapiere jedes mal manuell zu machen.

Ich nutze PP v0.36.1 unter Linux. Im Fehlerprotokoll steht nur
"Fri Jan 18 23:32:04 CET 2019
Kein Wechselkurs für Umrechnung von EUR nach  gefunden"
(keine Ahnung ob das damit zu tun hat)

und so sieht es aus:
![vorher](https://user-images.githubusercontent.com/1114182/51427797-09b3d600-1bfc-11e9-9f1f-ce7ecc9ed5f4.png)
nach dem klick auf ok:
![nachher](https://user-images.githubusercontent.com/1114182/51427795-07517c00-1bfc-11e9-8a9f-f61c26268cc2.png)

**Comment by Marfir** [comment]
Ich habe mir gerade die 0.37.1 herunter geladen und der bug ist auch dort genau so vorhanden.

**Comment by Ragas13** [comment]
Strange, da sich dieses Verhalten nicht nachvollziehen lässt. Wenn du im Fehlerprotokoll doppelt auf die Meldung klickst, werden weitere Informationen angegeben?

By the way, unter welcher Währung führst du dieses Wertpapier?

**Comment by Marfir** [comment]
Die Fehlermeldung kam nicht wieder. Vermutlich ein irrläufer. Ich führe alle Wertpapiere in €. Da ich früher nicht solche Probleme hatte und jetzt mit allen Wertpapieren, wird es wohl nicht an einem einzelnen Wertpapier oder einer Währung liegen. Zumindest sehe ich nicht dass PP an irgend einer Stelle beim Kurse holen abbricht. Er zieht die wirklich alle.

Spannend gerade entdeckt:
unter "Alle Wertpapiere" steht in der Spalte "letzter (datum)" das heutige drin. Aber in der Spalte "letzter historischer" steht mal der 17.12. und mal der 18.01. drin. Klicke ich auf Wertpapier editieren dann werden mir im Reiter "Historische Kurse" auch Kurse von heute und gestern angezeigt. Klick auf ok aktualisiert die Spalte "letzter historischer" auf heute.

Kann es sein, dass ihr noch irgend eine Automatik an die Kursaktualisierung gekoppelt habt? Ich aktualisiere die Kurse manuell über das Menü. Nicht das dadurch nur ein Teil eurer Kurs-Update-Logik aufgerufen wird?

**Comment by Marfir** [comment]
So langsam kommen wir der Lösung näher. Ich hatte immer auf "Online" - "Kurse aktualisieren" geklickt und nahm an, dass damit der heutige Kurs in der xml abgespeichert und überall verwendet werden würde. Dem widersprechen aber die vielen komischen bugs die ich beobachten durfte.

Offenbar speichert Ihr die Kurse doppelt. Einmal den aktuellen Kurs und einmal die historischen Kurse und beide scheinen in PP nichts mit einander zu tun zu haben. Das würde erklären wieso die Kursdiagramme nicht richtig gemalt werden und in #1093 wird offenbar auf einen historischen Kurs zurück gesprungen, weil der aktuelle ignoriert wird. Offenbar speichert nur die Funktion "historische Kurse aktualisieren" die Daten richtig in der xml. Und nur "Kurse aktualisieren" macht irgend eine dummy Aktion.

Liege ich richtig? Führt Ihr die Daten doppelt oder verwerft aktuelle Kursdownloads?

**Comment by Marfir** [comment]
Ja habe es soeben an meinem 2. Portfolio ausprobiert. Nur "historische Kurse aktualisieren" schreibt wirklich Kurse in die xml und aktualisiert alle Anzeigen. Sogar der heutige Kurs wird gezogen und überall aktualisiert.

Das Menü "Kurse aktualisieren" ist dagegen Schrott.

Wieso behandelt Ihr "heute" und "historisch" so unterschiedlich?

**Comment by buchen** [comment]
> Das Menü "Kurse aktualisieren" ist dagegen Schrott.
> Wieso behandelt Ihr "heute" und "historisch" so unterschiedlich?

In der Tat ist das irritierend. Technisch sind die historischen und der "letzte" Kurs etwas anderes und werden auch separat gespeichert. Deswegen dachte ich, es wäre auch sinnvoll *zwei* Menüpunkte zu haben: einen für den aktuellen Kurs, einen für die historischen Kurse.

Aber ich gebe zu das ist nicht optimal. Zum einen sind die blöd benannt, zum anderen wird aus dem Kontextmenü auf dem Wertpapier auch immer *beides* aktualisiert. Und schließlich interessiert den Benutzer eigentlich gar nicht, dass das zwei verschiedenen Dinge sind.

Ich werde die Menüpunkte ändern und zu einem Menüpunkt zusammenfassen.

**Comment by buchen** [comment]
Ich habe jetzt folgendes gemacht:

* Die beiden Menüpunkte sind zu *einem* verschmolzen: "Kurse aktualisieren". Das ruft sowohl die Seite mit den Historischen Kurse auf als auch die Seite mit den aktuellen Kurse (bei Yahoo und AlphaVantage sind das zwei verschiedene APIs).
* alle 30 Minuten sollten die aktuellen Kurse aktualisiert werden; alle 6 Stunden die historischen Kurse

@Marfir erklärt das das Verhalten was Du beobachtet hast?

**Comment by Marfir** [comment]
Ja das klingt so als würde es das Problem erschlagen. Danke für den bugfix!

**Comment by buchen** [comment]
Okay, kommt mit der nächsten Version.
