### ISSUE TITLE
Absturz bei Eingabe von Zinsen, Einlagen, Entnahmen, ...

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#1089]
Version 0.37.0 (linux, x86_64)
$java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-2~14.04-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

Reproduktionsschritte:
1. Ein Konto öffnen.
2. Rechtsklick --> "Zinsen"
3. Zinsen von 0.49 Euro eingeben:
3.a) Eingabe von "0"
3.b) Eingabe von "."
3.c) Eingabe von "4"

Erwartetes Verhalten:
Die Zinsen lassen sich erfassen.

Beobachtetes Verhalten:
PortfolioPerformance stürzt ab und wird beendet.

Auf der Konsole sieht das so aus:
`LANG=en_GB ./PortfolioPerformance 

(process:8188): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.

(process:8205): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.

(Portfolio Performance:8205): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

** (Portfolio Performance:8205): CRITICAL **: JNI class pointer is NULL for class org/eclipse/swt/accessibility/AccessibleObject

** (Portfolio Performance:8205): CRITICAL **: JNI class pointer is NULL for class org/eclipse/swt/accessibility/AccessibleObject

(Portfolio Performance:8205): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

(Portfolio Performance:8205): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
java: /build/buildd/oxygen-gtk3-1.3.5/src/animations/oxygencomboboxdata.cpp:81: void Oxygen::ComboBoxData::setButton(GtkWidget*): Assertion `!_button._widget' failed.`

**Comment by buchen** [comment]
Mit diesem Update habe ich auch auf die Eclipse Version 2018-09 aktualisiert.
Da scheint es wohl Probleme unter Linux zu geben. 😬 

Erste Frage: verwendest du GTK3 oder hast Du PortfolioPerformance.ini dahingehend editiert GTK2 zu verwenden?

**Comment by yetipenguin** [comment]
Nein, das müsste GTK3 sein, so wies standardmäßig eingestellt ist.

Die PortfolioPerformance.ini sieht so aus:
`-startup
plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.800.v20180827-1352
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--illegal-access=permit
-XX:+UseG1GC
-XX:+UseStringDeduplication
-Xms256m
-Xmx768m
-Djdk.gtk.version=3`

**Comment by masterzuso** [comment]
Mit openJDK 10.0.2 tritt das Problem bei mir unter Linux nicht auf

**Comment by yetipenguin** [comment]
Habs mit dem OpenJDK von AdoptOpenJDK ausprobiert, das Problem tritt weiterhin auf.
` java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)`

Dann sieht das auf der Konsole so aus:
`./PortfolioPerformance 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/skyman/src/packages/SOURCES/portfolio/plugins/org.apache.servicemix.bundles.xstream_1.4.8.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

(Portfolio Performance:31690): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

** (Portfolio Performance:31690): CRITICAL **: JNI class pointer is NULL for class org/eclipse/swt/accessibility/AccessibleObject


** (Portfolio Performance:31690): CRITICAL **: JNI class pointer is NULL for class org/eclipse/swt/accessibility/AccessibleObject


(Portfolio Performance:31690): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

(Portfolio Performance:31690): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
java: /build/buildd/oxygen-gtk3-1.3.5/src/animations/oxygencomboboxdata.cpp:81: void Oxygen::ComboBoxData::setButton(GtkWidget*): Zusicherung »!_button._widget« nicht erfüllt.`

**Comment by yetipenguin** [comment]
Wie ich nun gesehen habe, betrifft es nicht nur Zinsen, sondern auch Entnahmen und Einlagen, also im Prinzip die ganzen Dialoge mit den Zahlen.
Könnte man hier kurzfristig was tun? :-) Für mich stellt das gerade einen Blocker dar ...

**Comment by buchen** [comment]
Ich habe gerade mal meine Ubuntu 18.04 LTS Installation ausprobiert (VMWare) und habe keine Probleme. Vorher habe ich die Aktualisierung laufen lassen.

Von den Fehlern hier: das ist alles in Native C Code auf den ich keinen Einfluß habe (das kommt aus dem SWT Framework das wiederum Teil von Eclipse ist). Es scheint mir darum auch eher nicht an Java8 oder Java11 zu liegen.

Die Frage ist ob es was bringt PP auf GTK2 zu zwingen.
Also mal mit
```
SWT_GTK3=0 ./PortfolioPerformance
```
starten.

**Comment by yetipenguin** [comment]
Leider hat sowohl `SWT_GTK3=0 ./PortfolioPerformance`als auch `-Djdk.gtk.version=2` in der PortfolioPerformance.ini nicht geholfen. :-(

**Comment by buchen** [comment]
Wird vielleicht noch ein Log Datei irgendwo anders geschrieben? Vielleicht in dem *configuration* Verzeichnis?

Mein Problem ist: mit diesen Fehlermeldungen ist es schwer in dem Bug Tracker bei Eclipse selber zu suchen. Der Crash ist vermutlich nicht wegen ```Gdk-WARNING *: gdk_window_set_icon_list: icons too large``` sondern tritt später auf (wenn Du im Eingabefeld Werte eingibst). Diese Meldung/Crash brauchen wir um sinnvoll googlen zu können.

Und vermutlich hängt es mit Deiner Distribution (ist das Ubuntu?) zusammen. Und mit dem Theme. Etc. Alles schon gesehen - allerdings steige ich bei Linux nicht wirklich durch.

**Comment by yetipenguin** [comment]
Leider liegt da auch keine Logdatei. Ich habs im Eclipse-Bugzilla auch schon versucht und werde die Spur  mal weiterverfolgen. Trotzdem schon mal vielen Dank für deine Hilfe! :-) Andere Themes und Distributionsversionen werde ich auch noch ausprobieren. Ich hab da ja was relativ altes in Verwendung.

**Comment by buchen** [comment]
Ich habe meine VMWare Ubuntu 18.04 Installation ausprobiert: da tritt das Problem nicht auf.

**Comment by yetipenguin** [comment]
Es liegt, wie von dir vermutet, am GTK3-Theme. In meinem Fall ist es "oxygen-gtk". Ändere ich das GTK3-Theme mittels "systemsettings" in KDE, so treten keine Abstürze mehr auf.
Ich schau mal, ob das ein generelles Problem mit Eclipse-2018-09 ist und mache dann gegebenenfalls einen Bug-Report bei Eclipse auf.

**Comment by yetipenguin** [comment]
In Eclipse konnte ich es auf Anhieb nicht nachvollziehen.

Wer Themes für GTK3 auf Kubuntu 14 sucht:
apt-get install gtk3-engines-xfce
oder Adwaita https://www.gnome-look.org/p/1013073/
sehen einigermaßen vernünftig aus.
