### ISSUE TITLE
PortfolioPerformance ist bei Sichtenwechsel sehr langsam

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#1090]
Seit ein paar Versionen ist PortfolioPerfomance sehr langsam, wenn man in bestimmte Ansichten wechselt. Beispielsweise von "Perfomance" nach "Vermögensaufstellung".
Im gleichen Moment geht eine CPU auf 100% hoch und der Seitenwechsel dauert zwischen 3 und 10 Sekunden.
Fehlermeldungen gibt es leider keine, aber es wirkt auf mich, als ob im Hintergrund eine Berechnung zu lange dauert, da in dem Moment die komplette GUI hängt und beim Verschieben des Fensters auch nicht neu gerendet wird.

Ist leider ein etwas unspezifisches Problem ...
Ich verwende Kubuntu 14.04.5 LTS.

**Comment by buchen** [comment]
Ist das mit der aktuellen Version 0.36.0 besser geworden? Oder tritt das immer noch auf?

Ich hatte ein Problem dass mit jeder Spaltenänderung die Datei als "dirty" markiert wurde und darum alle Berechnungen noch mal ausgeführt wurden.

**Comment by yetipenguin** [comment]
Bei mir ist 0.37.0 aktuell und ja, da tritt es leider noch auf.

**Comment by yetipenguin** [comment]
Tritt auch schon mit 0.35.1 auf. Weiter zurück kann ich nicht so einfach, da es da nur Source-Pakete und keine Binärpakete gibt.

**Comment by buchen** [comment]
Okay, dann muss ich selber mal unter Ubuntu/Kubuntu ausprobieren.

**Comment by buchen** [comment]
@yetipenguin in der Vermögensaufstellung werden noch viele Berechnungen im UI Thread gemacht (ja, ich weiß... das muss ich angehen). Wieviele Spalten hast Du denn in der Vermögensaufstellung konfiguriert? Und mit welchen Zeiträumen? Wenn Du magst, dann wäre es super wenn Du mir Deine Datei zu Testzwecken an *portfolio dot performance dot help at gmail dot com* schicken könntest.

**Comment by yetipenguin** [comment]
Das Problem habe ich auch mit der Kommer-Beispieldatei mit den Standardspalten, die bei einer frischen Installation vorhanden sind. Das sind: Bestand, Name, ISIN, Kurs, Einstandspreise, Marktwert, Anteil in %, Notiz.
Sobald ich mit Eclipse 2018-09 kompilieren und starten kann, schaue ich mir das mal im Debugger an. Kann aber bei mir noch bis Anfang März dauern, bis ich wieder mehr Zeit dafür finde ...

**Comment by yetipenguin** [comment]
Problem tritt mit dieser Version nicht mehr auf:
Version: 0.52.0 (Apr. 2021)
Platform: linux, x86_64
Java: 11.0.11+9-Ubuntu-0ubuntu2.18.04, Ubuntu
