### ISSUE TITLE
bug: Kursanzeige in Vermögensaufstellung springt auf 14. Dezember zurück

### ISSUE THREAD

**Issue by Marfir** [buchen/portfolio#1093]
Ich habe in der v0.37.1 und auch schon zuvor das Problem, dass nach der Kursaktualisierung (manuell ausgelöst) die Anzeige "Kursdatum" in der Vermögensaufstellung auf den 14.12.2018 zurück springt. Die Kurse wurden aber herunter geladen. Denn wenn ich z. B. danach auf Diagramm gehe und wieder zurück, dann steht dort das heutige Kursdatum mit den richtigen Wertpapierkursen.
Ich nehme daher an dass es sich um einen Anzeige-bug handelt.

Ich habe den bug schon in der v0.36.1 gehabt und ein erneutes herunter laden der Version hilft nicht.

![kursanzeige buggy](https://user-images.githubusercontent.com/1114182/51492053-bd5dc700-1db0-11e9-9630-b1e784a35fc9.png)

**Comment by Ragas13** [comment]
@Marfir
Tritt dieser Fehler bei allen deinen Wertpapieren auf oder nur bei einem?

Kannst du bitte testweise ein komplett neues, leeres Portfolio erstellen und dann dieses Wertpapier nur mit Kursen anlegen? Tritt der Fehler dann immer noch auf?

**Comment by Marfir** [comment]
Heute ist er auf den "18.01.19" zurück gesprungen. Ich glaube der Effekt tritt nur auf, wenn ich PP länger geöffnet lasse.

Ja alle Wertpapiere sind betroffen.

Allerdings scheint dieser bug mit #1086 zusammen zu hängen. Denn der 14. Dezember könnte es auch sein seit dem ich diese durchgängigen Linien in den Kursdiagrammen sehe.

Ok ich habe jetzt ein neues Portfolio angelegt. Dort sieht erst mal alles gut aus. Ich beobachte es mal die Tage und gebe dann feedback.

**Comment by Marfir** [comment]
siehe Kommentar an #1086

**Comment by buchen** [comment]
> dass nach der Kursaktualisierung (manuell ausgelöst) die Anzeige "Kursdatum" in der Vermögensaufstellung auf den 14.12.2018 zurück springt. 

Wie ist denn für dieses Wertpapier der Kursdownload konfiguriert?

Je nachdem welchen Kursdownload man hat, werden die Kurse technisch wieder überschrieben. Zum Beispiel wenn man Kurse aus einer Tabelle von einer Webseite extrahiert, dann werden diese Kurse zu dem Wertpapier eingefügt.

Bei Yahoo dagegen lädt PP immer nur die historischen Kurse *ab* dem letzten historischen Kurs.

**Comment by Marfir** [comment]
Alle Wertpapiere habe ich nach der Standardvorgabe konfiguriert. Also "historische Kurse" -> "Yahoo Finance" und "aktueller Kurs" -> "Liferant wie historische Kurse".

**Comment by buchen** [comment]
> die Anzeige "Kursdatum" in der Vermögensaufstellung auf den 14.12.2018 zurück springt

In der Vermögensaufstellung wird das Datum angezeigt, von dem der Kurs stammt der zu der Bewertung der Position herangezogen wurde. Zumindest sollte das so sein. :smile:

Vereinfacht ist das der aktuelle Kurs (wenn es ihn gibt) und wenn es keinen historischen Kurs zu diesem Datum gibt (historische Kurse werden präferiert). Es sei denn der aktuelle Kurs ist später als das Datum zu dem die Vermögensaufstellung angezeigt werden soll.

Meine Theorie: Wenn man die Vermögensaufstellung öffnet, wird automatisch das aktuelle Datum gesetzt. Wenn Du die einen ganzen Tag offen hälst, dann ist das plötzlich das Datum von gestern. Wenn die aktuellen Kurse dann aktualisiert werden, liegen die in der Zukunft. Und das Datum "springt" zurück auf den letzten historischen Kurs. Da Du "nur" die aktuellen Kurse aktualisiert hast, liegt das plötzlich viel weiter in der Vergangenheit.

🤔 Da muss ich mir was überlegen...
