### ISSUE TITLE
Tortendiagramm Vermögensaufstellung - Bestände wird bei Umlauten im Pfad nicht angezeigt

### ISSUE THREAD

**Issue by Daresch** [buchen/portfolio#1094]
**Fehlerbeschreibung**
Das folgende tritt bei mir unter Linux Mint 19.1 (und auch davor bei Ubuntu 18.04) auf:
Enthält der Pfad, in dem PP liegt, ein Umlaut, so kann das Tortendiagramm unter _Vermögensaufstellung - Bestände_ nicht angezeigt werden.

**Fehlermeldung** im Terminal:
`Error loading module '/home/arne/Dokumente/10_Privat/Finanzen/Wertpapier%C3%BCbersicht/Portfolio_Performance/configuration/org.eclipse.osgi/482/0/.cp/webkitextensions4919/libswt-webkit2extension-gtk-4919.so': /home/arne/Dokumente/10_Privat/Finanzen/Wertpapier%C3%BCbersicht/Portfolio_Performance/configuration/org.eclipse.osgi/482/0/.cp/webkitextensions4919/libswt-webkit2extension-gtk-4919.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden`

Der Umlaut befindet sich hier in _Wertpapierübersicht_, welches als _Wertpapier%C3%BCbersicht_ verarbeitet wird.

**Workaround**
Ersetzen von Umlauten im Pfad durch Nicht-Umlaute.

**Comment by Ragas13** [comment]
So wie ich bspw https://bugs.eclipse.org/bugs/show_bug.cgi?id=312832 verstehe, handelt es sich um ein Linux spezifisches Problem da Sonderzeichen und Umlaute per UTF-8 kodiert werden. 

Da kannst du mE nur darauf hoffen das Eclipse dies irgendwann behebt.

Gruß 
Marco

**Comment by buchen** [comment]
@Daresch Ich habe keine Kontrolle darüber wie und woher die nativen Module geladen werden. Das liegt beim Eclipse Framework. Ich befürchte hier bleibt nur der Workaround -> keine Umlaute verwenden. Sorry.
