### ISSUE TITLE
CSV-Import-Vorlage: Formatierung bei Wert wird nicht gespeichert

### ISSUE THREAD

**Issue by skyfmmf** [buchen/portfolio#1097]
Ich habe eine Konfiguration beim CSV-Import als Vorlage gespeichert. In der Spalte für 'Wert' sind die Zahlen mit `.` als Dezimaltrennzeichen dargestellt, daher stelle ich das Format auf `0,000.00` um, um die Werte korrekt importieren zu können. 

Wenn ich die Vorlage erneut verwenden will, wird die Dezimaltrennung wieder auf die Standardeinstellung `0.000,00` zurückgesetzt, wodurch die Werte falsch importiert würden.

Version 0.37.1 (macosx, x86_64)

**Comment by buchen** [comment]
Danke. Ich habe nur das Pattern gespeichert - das ist aber bei verschiedenen 'Locale' Objekten gleich.
