### ISSUE TITLE
Bug beim Löschen von Watchlists

### ISSUE THREAD

**Issue by anroth** [buchen/portfolio#1098]
Hallo,

ich habe Probleme beim Löschen von Watchlists festgestellt.
Ich habe ca. 30 Watchlists angelegt, mit teilweise langen Namen (138 Zeichen).
In den Namen sind auch Zeichen wie Umlaute ";" und "-".

Wenn ich eine Liste löschen möchte kann es zufällig passieren, dass die korrekte Liste verschwindet.
Viel öfter passiert es aber, dass eine andere Liste verschwindet.
Lösche ich mehrere nacheinander kann es passieren, dass beim erneuten versuch eine weitere Liste zu löschen keine Liste gelöscht wird.

Viele Grüße,
Anroth

**Comment by buchen** [comment]
Interessanter Bug. Das Problem war: ich habe zwar die Watchlist gelöscht, aber das UI Element nicht. Und dann haben sich zwei UI Elemente übereinander geschoben. Und es konnte schon passieren, dass das alte Element weiterhin oben steht.
