### ISSUE TITLE
Startfehler und Bau via mvn ebenso

### ISSUE THREAD

**Issue by Richie94** [buchen/portfolio#1099]
Heyho,

bei mir unter Manjaro/arch Linux lief Version 0.36.1 noch fehlerfrei, ab dem Upgrade zu 0.37.1 bekomme ich nur noch Fehlermeldungen bzgl unresolvter Modules 
```
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.common [350]
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.core.contenttype [274]
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.core.jobs [288]
```

Mir gab darauf jmd den Tipp, meinen .eclipse-Folder umzubennenen, dann lief mein System wieder mit version 0.36.1, aber nach Update wieder der gleiche Fehler.

Dann wollte ich das Projekt einfach selber mit Maven bauen, aber da failt es bei mir mit
```
Could not find artifact org.apache.maven.plugins:maven-jarsigner-plugin:jar:1.5-SNAPSHOT
```
im central Maven https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jarsigner-plugin gibts es auch keine Version 1.5, nur 1.4 oder 3.0.0

**Comment by Marfir** [comment]
Man bindet in ein Release auch keine SNAPSHOT dependencies ein. Da hat jemand beim letzten PP Release geschlafen. ;-)
Das enforcer Plugin kann helfen solche Fehler in Zukunft zu vermeiden.

**Comment by buchen** [comment]
> Man bindet in ein Release auch keine SNAPSHOT dependencies ein.

Richtig. Habe ich trotzdem gemacht, weil das jarsigner Plugin nur im snapshot das "certchain" Property unterstützte. Aber ich sehe nach 3 Jahren gibt es mal wieder eine neue Release - dann kann ich auf 3.0.0 gehen. Commit kommt.

Das hat auch funktioniert weil ich die SNAPSHOT Version in einem eigenen Maven Repository gehostet habe. Und dieses Repository habe ich vor ein paar Tagen aus Versehen entfernt. Das funktioniert dann lokal noch (Cache), aber nicht für neue Builds.

> ab dem Upgrade zu 0.37.1 bekomme ich nur noch Fehlermeldungen bzgl unresolvter Modules

Der Update Prozess ist nicht so stabil. Vor allem wenn sich das Update Framework selber aktualisiert. Das war mit 0.37.x der Fall. Einfach noch mal neu runterladen?

Wenn der Fehler in der IDE auftritt, dann vermute ich, dass Deine Target Platform noch aktualisiert werden muss.

**Comment by Marfir** [comment]
Kann man PP nicht so umbauen, dass es ohne den ganzen Eclipse Kram auskommt? Der Update Prozess ist unzuverlässig. Wenn man das herunter laden und entpacken selbst implementieren würde, würde es vermutlich in 99,9% der Zeit funktionieren. ;-)

Ich habe das für [Planetensuche](http://marfir.de/de/planetensuche.html) schon vor längerer Zeit implementiert und kann da Anregungen geben, falls gewünscht.

**Comment by Marfir** [comment]
Ich habe unter Ubuntu z.B. immer das Problem das der automatische Neustart nach dem Update nicht klappt.

Für das kleine Programm wurde OSGI verwendet? Klingt ziemlich over engineered.
Aber gut. Da das Kind nun schon in den Brunnen gefallen ist, müssen wir wohl damit leben.
