### ISSUE TITLE
Failure during Update

### ISSUE THREAD

**Issue by Dude1994** [buchen/portfolio#1100]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/47081297/51801570-ef9f7680-223f-11e9-98ed-1c840cd83847.png">

Fehler beim Installieren der Elemente
  session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]name.abuchen.zulu.jre.macosx.x86_64 8.30.0.1-patch1, action=org.eclipse.equinox.internal.p2.touchpoint.natives.actions.LinkAction).
  Kann Verknüpfung libjli.dylib nicht erzeugen.
  File that was copied to backup could not be deleted: /private/var/folders/rs/s40m7nlj1371bkdvpk1skf3w0000gn/T/AppTranslocation/E30E75EE-3F3F-4A7B-B174-CD9526969B90/d/PortfolioPerformance.app/Contents/Eclipse/plugins/name.abuchen.zulu.jre.macosx.x86_64_8.30.0.1-patch1/Contents/MacOS/libjli.dylib

**Comment by buchen** [comment]
Ich befürchte da bleibt leider nur ein erneuter Download.

Ich nutze das p2 Framework zur Aktualisierung. Das ist nicht immer ganz stabil - vor allem wenn es sich selber aktualisieren muss. Meistens betrifft sowas eher Windows - auf meinem mac habe ich es noch nicht gesehen.

Wie auch immer - ich will lieber Zeit in PP features verwenden als diese Bibliothek zu Debugge, darum lieber noch mal neu runterladen. Trotzdem vielen Dank für Rückmeldung.
