### ISSUE TITLE
Umlaute Encoding in Regionen

### ISSUE THREAD

**Issue by codeofsumit** [buchen/portfolio#1102]
Stimmt ne Kleinigkeit nicht :-)
![image](https://user-images.githubusercontent.com/2399810/52015843-38c32500-24e3-11e9-9b86-6417485deedc.png)

**Comment by buchen** [comment]
Danke! Mit der nächsten Version wird die Klassifizierung richtig angelegt. Allerdings werden *existierende* Klassifikationen nicht modifiziert (es ist eher eine Vorlage die der Nutzer anpassen kann). D.h. in Du müsstest dann entweder eine neue Klassifikation erstellen oder in Deiner Version die Bezeichnet korrigieren.
