### ISSUE TITLE
Problem: Relative Berichtszeiträume immer relative zu *heute*

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#1103]
In der Vermögensaufstellung kann man sich zusätzliche Spalten einblenden, z.B. "Absolute Performance 1 Jahr" - also mit relativen Zeitraum des letzten Jahres.

Diese Zeiträume werden immer relativ zum heutigen Datum aufgelöst.

Aber: in der Vermögensaufstellung kann man ein anderes Datum anwählen. Erwartet man dann nicht eher das die "Letztes 1 Jahre" Kennzahl sich auf das Jahr bis zu diesem Datum bezieht?

Und: In der Performance-Berechnung gibt es *zwei* Vermögensaufstellungen - eine für den Beginn und eine für das Ende des betrachteten Zeitraums. Sollte die Kennzahl "Letztes 1 Jahr" nicht relativ zu diesen beiden Vermögensaufstellungen sein?

Siehe auch hier: https://forum.portfolio-performance.info/t/zahlenueberlauf-in-vermoegensaufstellung-abs-perf-1-jahr/4474

Man müsste das "startDate" und "endDate" aus der ReportingPeriod rauswerfen und sowas wie ein ```ReportingPeriod#getInterval(LocalDate relativeTo)``` einfügen.

**Comment by sebasbaumh** [comment]
> Aber: in der Vermögensaufstellung kann man ein anderes Datum anwählen. Erwartet man dann nicht eher das die "Letztes 1 Jahre" Kennzahl sich auf das Jahr bis zu diesem Datum bezieht?

Ja, ich würde denken, das sollte sich dann auch auf den Zeitraum ein Jahr davor beziehen.

Einige Nutzer haben Probleme mit den Zeiträumen, wie ich immer wieder im Forum mitbekomme und manchmal auch bei mir selber merke.
Hilfreich wäre es vielleicht, wenn man den Zeitraum explizit anzeigt - zum Beispiel in einer Statuszeile unter der Ansicht oder einfach oben hinter der Überschrift "Performance-Berechnung".
Dann ist schon mal klar, was die Basis ist.

Bei der Performance-Ansicht sehe ich die Zeiträume so:
"1 Jahr" würde ich auch immer relativ zum aktuellen Datum sehen, also quasi "seit einem Jahr".
Ich habe mir selber Zeiträume für die einzelnen Jahre hinzugefügt, also "2018","2019" und so weiter.
Das ist ja quasi das "Year-To-Date", obwohl dieses als dynamische Option noch fehlt. Und das würde heute z.B. nur die 31 Tage im Januar 2019 enthalten.

**Comment by imperatom** [comment]
> In der Vermögensaufstellung kann man sich zusätzliche Spalten einblenden, z.B. "Absolute Performance 1 Jahr" - also mit relativen Zeitraum des letzten Jahres.
> Diese Zeiträume werden immer relativ zum heutigen Datum aufgelöst.
> Aber: in der Vermögensaufstellung kann man ein anderes Datum anwählen. Erwartet man dann nicht eher das die "Letztes 1 Jahre" Kennzahl sich auf das Jahr bis zu diesem Datum bezieht?

Stimmt, das sollte man eigentlich erwarten. Ähnlich wie Sebastian glaube ich aber auch, dass es am einfachsten wäre, den Zeitraum direkt und explizit anzuzeigen und auszuwählen. Dass es aktuell zwei verschiedene Orte gibt, an denen man den Zeitraum auswählt, ist eher irritierend (auch wenn es funktionieren würde wie erwartet). Ich nutze die Time-Machine überhaupt nie, daher ist mir der Fehler auch nie aufgefallen. Man kann sich doch alle Zeiträume individuell auswählen, in denen die Performance betrachtet wird. Dass man zusätzlich an anderer Stelle über die Time Machine nochmal Zeiträume auswählt, **kann** ja eigentlich nur zu Irritationen führen. Ich würde die Time Machine einfach ganz abschaffen, da sie nichts kann, das die anderen Schalter nicht bereits können, wenn ich das richtig sehe.
 
> Und: In der Performance-Berechnung gibt es _zwei_ Vermögensaufstellungen - eine für den Beginn und eine für das Ende des betrachteten Zeitraums. Sollte die Kennzahl "Letztes 1 Jahr" nicht relativ zu diesen beiden Vermögensaufstellungen sein?

Auch diese Irritation gäbe es nicht, wenn man die Parallelstruktur der Zeitauswahl abschaffen würde. Ich bin überzeugt, dass die Zeit nur an einer Stelle ausgewählt werden sollte. Dabei klingt zwar auch Sebastians Idee interessant, sie schließt aber aus, dass man zwei ganz verschiedene Zeiträume gleichzeitig in verschiedenen Spalten betrachten kann. Umso mehr denke ich, dass die Zeitraumauswahl am Zahnradsymbol gut funktioniert und die Tiem Machine einfach rausfliegen sollte, um die Irritationen zu verhindern.

**Comment by Ragas13** [comment]
Mir selbst ist dies bewusst auch noch nicht aufgefallen, da ich nur hier und da auf die Kennzahlen achte. Aber wenn ich so an das Berichtswesen bei uns in der Firma denke (Stichwort "vs Last Year") würde ich dies relativ zum gewählten Zeitraums erwarten.

**Comment by buchen** [comment]
> Ich nutze die Time-Machine überhaupt nie, daher ist mir der Fehler auch nie aufgefallen.

Für mich ist das auch eher ein "Debug" Tool - wenn ich verstehen möchte warum PP das Depot zu einem bestimmten Zeitpunkt bewertet hat. Und ich habe es "Time-Machine" benannt, weil WISO Mein Geld (ich glaube es war WISO) so groß Werbung gemacht hat, dass man sich sein Depot auch mit der Time Machine zu einem früheren Zeitpunkt anschauen kann :grins
