### ISSUE TITLE
Bug: Filter für Depots und Konten in der Vermögensübersicht verschwunden

### ISSUE THREAD

**Issue by oduudo** [buchen/portfolio#1104]
Seit dem Commit “Refactored AbstractFinanceView to use ToolBarManager” vom 15.1.2019 @ 08:33 ist der Button für die Filtereinstellung für Depots und KOnten in der Finanzübersicht nicht mehr zu sehen.
Vor diesem Commit war er noch da.
Ich denke mal, das der Button nicht absichtlich weggemacht wurde, es gibt zwar einen Forums-Thread dazu, aber ich hab hier nichts dazu gefunden, deshalb mache ich hier mal nen Issue auf!
Danke fürs Kümmern,
Udo

**Comment by buchen** [comment]
Oooops. Das ist mir durch die Lappen gegangen. Ist wieder da. Kommt mit der nächsten Version (in den nächsten Tagen).
