### ISSUE TITLE
Inflationsrate für europäische Länder / Eurostat

### ISSUE THREAD

**Issue by Ragas13** [buchen/portfolio#1108]
PP wird ja nicht nur v. Anwendern in Deutschland verwendet. Da ich jedoch zur Vergesslichkeit neige und bevor es unter geht, Eurostat bietet einen Web Services d. die Preissteigerungen seit 1996 f. die europäischen Länder an.

Der Vorteil wäre das A) das HTML parsen entfallen könnte und B) die Länder selektiv abgefragt werden können.

Unsicher bin ich noch was das Basisjahr in der Abfrage betrifft, da der Stream sowohl alle als auch nur bestimmte Basisjahre anbietet.

Im allgemeinen Denke ich da an die Anfragen aus #32 und https://forum.portfolio-performance.info/t/historische-daten-verbraucherpreisindex-importieren/3676/9

**REST API Beispiel f. Deutschland**
http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/de/prc_hicp_midx?filterNonGeo=1&precision=1&geo=DE&unitLabel=code&coicop=CP00

**Tabelle der HVPI Daten**
https://ec.europa.eu/eurostat/tgm/table.do?tab=table&init=1&language=de&pcode=teicp000&plugin=1

**Dokumentation d. Web Services**
https://ec.europa.eu/eurostat/web/json-and-unicode-web-services/getting-started/query-builder

**Eurostat Datensatz prc_hicp_midx**
https://ec.europa.eu/eurostat/web/hicp/data/database?p_p_id=NavTreeportletprod_WAR_NavTreeportletprod_INSTANCE_BO6Fgp25CkI9&p_p_lifecycle=0&p_p_state=pop_up&p_p_mode=view&p_p_col_id=column-2&p_p_col_count=3&_NavTreeportletprod_WAR_NavTreeportletprod_INSTANCE_BO6Fgp25CkI9_nodeInfoService=true&nodeId=252712

**DESTATIS CPI vs Eurostat, HVPI**
Es wird eine geringe Änderung der Werte gebe, da lt https://www.destatis.de/DE/ZahlenFakten/GesamtwirtschaftUmwelt/Preise/FAQ/Verbraucherpreise/VPI_HVPI.html der deutsche VPI und dessen europäisches Gegenstück geringfügig anders berechnet wird. Bspw Glücksspiel, selbsgenutztes Eigentum oder unterschiedliche Warenkörbe.

> **Worin unterscheiden sich der Verbraucher­preis­index und der Harmonisierte Verbraucher­preisindex?**
> Das Statistische Bundesamt berechnet für europäische Zwecke neben dem nationalen Verbraucher­preisindex für Deutschland (VPI) auch einen Harmonisierten Verbraucher­preisindex (HVPI) für Deutschland.
> 
> Der VPI für Deutschland misst die durch­schnittliche Preisentwicklung aller Waren und Dienst­leistungen, die private Haushalte für Konsum­zwecke kaufen. Er dient einerseits der Inflations­messung, außerdem der Deflationierung gesamt­wirtschaftlicher Größen, d.h. der Umrechnung nominaler in reale Veränderungen sowie den Empfängern regelmäßig wieder­kehrender Zahlungen als Kompensations­maßstab.
> 
> Der HVPI wurde in der Europäischen Union (EU) entwickelt, um Preisänderungen international vergleichen und zu einer Gesamt­inflationsrate für Europa und der Europäischen Währungsunion zusammenfassen zu können.
> 
> Diese unterschiedlichen Zielsetzungen bedingen eine zum Teil unterschiedliche Methodik und auch kleine Differenzen beim Erfassungsbereich.

[Statistisches Bundesamt
Verbraucherpreisindex für Deutschland.pdf](https://github.com/buchen/portfolio/files/2825524/MerkblattPunkte.pdf)

**Comment by buchen** [comment]
Die Frage nach weiteren Inflationsraten ist ur-ur-alt. 😄  Und das auf ein sauberes API zu stellen halte ich auch für eine gute Idee. 👍 

Für mich ist die Frage ob wir weiterhin eine "Extra-Implementierung" für die Inflationsrate haben, oder ob die Inflationsrate nicht einfach als ein Wertpapier abgebildet wird. Wertpapiere können ja schon jetzt "währungslos" sein (eben ein Index) und dann als "Benchmark" den Diagrammen hinzugefügt werden.

Wenn man also einen entsprechenden ```QuoteFeed``` gegen das obige API implementieren würde, könnte man die einfach hinzufügen. Und vielleicht ist das "Ticker Symbol" dann das Land (so könnte man einfach Deutschland, EU, und was auch immer auswählen).

Das einzige "Problem" dabei ist, dass man bei der Inflationsrate nur einen Wert pro Monat bekommt. Aber bei dem Wertpapier die Kurse natürlich für einen Tag hinterlegt werden müssen. Aber auch das sollte nicht so problematisch sein - man könnte den letzten Tag im Monat nehmen.

Was meinst du?

> Es wird eine geringe Änderung der Werte geben

Ehrlich gesagt kann ich nicht beurteilen ob das ein Problem ist. Ich persönlich würde es als nicht so problematisch ansehen. Und wir könnten in einem ersten Wurf ja die alte Implementierung erst mal stehen lassen.

**Comment by Ragas13** [comment]
@buchen
Das mit dem QuoteFeed hört sich nach einer coolen Idee an. Und wenn mein verkalktes Gehirn sich nicht täuscht hatte glaube ich das im Forum über Wertpapier und Inflationsrate diskutiert wurde. Hätte dann den Vorteil das man ihn als Benchmark definieren kann.

Ich habe gestern schon mal ein wenig mit der Eurostat API gespielt und auch  mittlerweile die korrekte Zuordnung zwischen Monat/Jahr und dem Indexwert hingekommen. 

Ok, ich würde mich jetzt erst einmal am YahooSearchProvider orientieren da ich hier mE über Dropdown das Land equivalent zum Handelsplatz als DropDown vielleicht lösen kann.

Was dann die einzelnen Tage je Monat betrifft, ich meine es sollte gehen wenn man den ersten und letzten Tag des Monats definiert. Auf der anderen Seite sollten vielleicht doch alle Tage zugewiesen werden wenn dich jemand die Kursgrafik ansieht und nicht exakt den Tag wg. Tooltip trifft.

VG
Marco

**Comment by buchen** [comment]
> Und seit fehlende Tage in der Grafik sichtbar sind, schaut das Chart wie ein Zebra aus.

Aber das würde sich ja lösen wenn man als Kalendar "Empty" wählt (oder vorgibt)? Oder einen speziellen Kalender definiert, der immer nur nach dem letzten Tag im Monat schaut.

Vielleicht braucht man auch eine Konfiguration für die "erwartete Frequenz der Kurse" - also täglich, oder monatlich. Und dann können die Charts das entsprechend zeichnen. Aber auch da würde ich erst mal abwarten an wie vielen Stellen man das benötigen würde.

> Auf der anderen Seite sollten vielleicht doch alle Tage zugewiesen werden wenn jemand die Kursgrafik ansieht und nicht exakt den Tag wg. Tooltip trifft.

Wobei man das auch im Tooltip lösen könnte - in dem man nach rechts und links nach weiteren Daten sucht. So machen wir das ja schon bei den "Kauf/Verkaufereignissen". Abgesehen davon gibt es das Problem schon heute. Auch das würde ich in einen separaten Change packen.

**Comment by Ragas13** [comment]
Ich mach dann hier mal dicht da PR #1110 jetzt das implementiert

Gruß
Marco
