### ISSUE TITLE
Ampersand wird nicht überall angezeigt

### ISSUE THREAD

**Issue by keszocze** [buchen/portfolio#1109]
Hallo zusammen,
in der aktuellen Version 85fe95b0 werden in Überschriften und im Text der Heatmap Ampersand-Zeichen (`&`) nicht angezeigt, da sie vom GUI Framework genutzt werden, um Hotkeys zu bezeichnen. 

Unter keszocze/portfolio@d1ddcf15 habe ich dem Dashboard die Methode `String getAmpersandLabel` hinzugefügt, die die Ampersands verdoppelt, bevor sie zurückgegeben werden. Damit ist es möglich, an den richtigen Stellen, diesen String zu verwenden. 

Vorteile:
* Der Nutzer kann seine Namen wie gewohnt eingeben
* Man überschreibt nicht den vom Nutzer eingegebenen Namen und hat somit überraschend zwei Ampersands 

Nachteil:
* Man muss bei jedem Aufruf von `getText` überlegen/wissen, welchen String man benötigt.

Falls das Problem und der zugehörige Workaround Zustimmung finden, würde ich einen Merge-Request eröffnen.

Viele Grüße
Oliver

**Comment by buchen** [comment]
Das ist ganz klar ein Bug. Ich habe auch schon so eine Hilfsklasse ```TextUtil#tooltip``` die das kaufmännische & entsprechend behandelt (es ist mir zunächst bei den Tooltips aufgefallen). Ich habe die beiden Stellen gefixt.

Ich habe mich gegen eine Methode in ```Dashboard.Widget``` entschieden, weil man wohl in vielen Klassen ähnliche Methoden einfügen müsste. Aber die View Klasse, die den String in ein SWT Objekt schiebt, kann wissen ob der String zu diesem Zeitpunkt escaped werden muss.

BTW, Du kannst ruhig schon zur Diskussion einen Pull Request aufmachen.
