### ISSUE TITLE
Bessere Sichtbarkeit des Changelogs

### ISSUE THREAD

**Issue by christian-schauer** [buchen/portfolio#1114]
Zunächst mal Danke dafür, dass du den [Changelog ](https://www.portfolio-performance.info/portfolio/versions.html) so vorbildlich pflegst. Ich finde es super, dass er automatisch angezeigt wird, wenn eine neue Version verfügbar ist. Wenn nur alle Programme das bieten würden! 

Manchmal möchte ich den Changelog aber selbst aufrufen, und da suche ich mir jedes mal einen Ast. Hier wären zwei Orte, an dem du den Changelog verlinken könntest:
1. Auf der Startseite 
![image](https://user-images.githubusercontent.com/47474538/52519834-d21bd500-2c61-11e9-98c2-a5b8cf189b68.png)
2. Im Hilfe-Menü des Programms
![image](https://user-images.githubusercontent.com/47474538/52519855-1d35e800-2c62-11e9-8ddc-ee716c4304ca.png)

**Comment by buchen** [comment]
Danke für den Hinweis. Habe ich gemacht!

**Comment by christian-schauer** [comment]
Cool. Danke!
