### ISSUE TITLE
Liste der nennenswerten Änderungen besser verlinken

### ISSUE THREAD

**Issue by christian-schauer** [buchen/portfolio#1123]
Noch ein Verbesserungsvorschlag für die Änderungshistorie:
Von der Seite der Änderungshistorie verlinkst du auf die "nennenswerten Änderungen" mit diesem Link:
https://forum.portfolio-performance.info/t/neues-nennenswertes/23/7
Durch diesen Link landet man immer bei folgendem Eintrag (was natürlich eher verwirrend ist):
Version 0.25.0 vom 11. September 2016

Besser wäre es natürlich, wenn du zum stets aktuellen Eintrag verlinken würdest. (Am einfachsten wäre es natürlich, wenn man den Forums-Thread einfach nach Datum absteigend sortieren könnte, aber diese Option scheint nicht zu existieren.) 
Um den korrekten Eintrag zu verlinken, müsstest du also theoretisch den Link bei jeder Aktualisierung mit dem neuen Deeplink aktualisieren. Das hast du anscheinend auch damals für Release 0.25.0 gemacht, dann aber vergessen zu aktualisieren. Ich habe allerdings etwas rumprobiert und festgestellt, dass du auch einfach eine sehr hohe Zahl in die URL einfügen kannst und dadurch stets auf den neuesten Eintrag verlinkst; z.B. "999":
https://forum.portfolio-performance.info/t/neues-nennenswertes/23/999

**Comment by buchen** [comment]
.../last scheint der korrekte Weg zu sein: https://meta.discourse.org/t/link-to-last-post-in-topic-no-longer-works-after-recent-updates/32415/8
