### ISSUE TITLE
Renditediagramm zeigt Werte für 2019 mit HVPI Deutschland nur für den 01.01.2019 an

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#1126]
Version 39.0

Reproduktionsschritte:
1. HVPI Deutschland als Wertpapier hinzufügen (siehe #1108 )
2. Im Renditediagramm den HVPI als Benchmark hinzufügen.
3. Diagramm auf ein Jahr einstellen
4. Klick und halten auf dem Diagramm.
5. Bewegen von 2018 nach 2019.

Erwartetes Ergebnis:
Das Mouseover zeigt für jeden Tag im Jahr 2019 die einzelnen Renditewerte an.

Beobachtetes Ergebnis:
Für 2019 werden nur die Renditewerte zum 01.01.2019 für alle angezeigten Kurven angezeigt.
Wenn ich HVPI entfernen, funktioniert es.
Nach meinem Verständnis liegt es daran, dass heute am 23.02.2019 keine Werte für HVPI nach dem 01.01.2019 vorliegen.

**Comment by Ragas13** [comment]
Der "aktuell" Eurostat veröffentlichte HVPI ist der Januar, neuere Daten wurden noch nicht veröffentlicht. 

Wenn ich den Veröffentlichungskalender @ https://ec.europa.eu/eurostat/documents/272892/272971/HICP+release+schedule+2019/ mir ansehe dauert es etwa 6 Wochen bis Daten zeitversetzt veröffentlicht werden.

However, die Datenreihen endet am 1. Januar da keine weiteren Daten vorliegen. Aber da lässt sich vielleicht was finden.

**Comment by yetipenguin** [comment]
Mir ist es heute erst einmal egal, wann die Daten für HVPI vorliegen. Trotzdem würde ich gerne die tagesaktuellen Daten meiner anderen Wertpapiere und Kredite sehen können. Das Mouseover nimmt immer das letzte Datum, an dem für alle angezeigten Werte Daten vorhanden sind.

**Comment by sebasbaumh** [comment]
Argh, darüber habe ich auch schon gerätselt, aber bei mir mit dem normalen Verbraucherpreisindex, den es schon immer gab. Da sehe ich auch nur den Stand bis 31.01.2019 - aber wenn ich ihn rausnehme, werden die restlichen Werte auch für den letzten Handelstag angezeigt.
Ich habe auch immer gerne den aktuellsten Vergleich, egal ob bei einzelnen Benchmarks Werte fehlen.

@buchen kann man nicht einfach den letzten Preis für Kurven mit fehlenden Daten anzeigen, damit man trotzdem den aktuellsten Vergleich der restlichen Kurven hat? Eventuell kannst Du das Ticket von @yetipenguin einfach umbenennen.

**Comment by yetipenguin** [comment]
Der Verbraucherpreisindex hat bei mir das Problem nicht, denn er wird im Mouseover nicht angezeigt. Vermutlich liegt es daran, dass dieser nicht als Wertpapier verwaltet wird ...

**Comment by sebasbaumh** [comment]
> Der Verbraucherpreisindex hat bei mir das Problem nicht, denn er wird im Mouseover nicht angezeigt. Vermutlich liegt es daran, dass dieser nicht als Wertpapier verwaltet wird ...

Ja, ich habe ihn extra hinzugefügt als Benchmark.
Das Problem ist aber dasselbe wie bei Dir - deswegen denke ich, macht es Sinn, dass für alle Fälle zu lösen.

**Comment by buchen** [comment]
> Für 2019 werden nur die Renditewerte zum 01.01.2019 für alle angezeigten Kurven angezeigt.
Wenn ich HVPI entfernen, funktioniert es.

Ich erinnert mich dunkel das der Tooltip irgendwie eine "Referenzdatenserie" brauchte. Und wenn die nicht vollständig ist, dann werden auch andere Werte nicht angezeigt. Siehe hier in  [TimelineChartToolTip](https://github.com/buchen/portfolio/blob/0.39.0/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/chart/TimelineChartToolTip.java#L106). Da ich die nächsten Wochen "offline" bin wird es noch was dauern...

**Comment by Ragas13** [comment]
Ich glaube ich habe einen möglichen Ansatzpunkt gefunden, siehe https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dataseries/DataSeriesSet.java#L158-L174 . Wenn hier bei der Abfrage des Feeds je Security besagter HVPI Feed gesetzt ist, könnte ```DataSeries.Type.CONSUMER_PRICE_INDEX``` anstelle ```DataSeries.Type.SECURITY_BENCHMARK``` evtl die Lösung sein. Ich probiere es am Wochenende einmal aus.

```
// consumer price index
        series = new DataSeries(DataSeries.Type.CONSUMER_PRICE_INDEX, ConsumerPriceIndex.class,
                        Messages.LabelConsumerPriceIndex, Colors.CPI.getRGB());
        series.setBenchmark(true);
        series.setLineStyle(LineStyle.DASHDOTDOT);
        availableSeries.add(series);

        // securities as benchmark
        for (Security security : client.getSecurities())
        {
            series = new DataSeries(DataSeries.Type.SECURITY_BENCHMARK, security, security.getName(), //
                            wheel.next());
            series.setBenchmark(true);
            availableSeries.add(series);
        }
```

Schönes Wochenende

**Comment by yetipenguin** [comment]
Problem tritt mit dieser Version nicht mehr auf:
Version: 0.52.0 (Apr. 2021)
Platform: linux, x86_64
Java: 11.0.11+9-Ubuntu-0ubuntu2.18.04, Ubuntu
