### ISSUE TITLE
In "Wertpapiere" schaltet Reiter "Trades" nicht um bei WP-Wechsel

### ISSUE THREAD

**Issue by YannCebron** [buchen/portfolio#1133]
Wenn in der oberen Tabelle zwischen Wertpapieren gewechselt wird, sollte die darunterliegende Ansicht umgeschaltet werden. Dies funktioniert für die Reiter "Kursdiagramm" und "Umsätze", jedoch  nicht für "Trades" wenn das WP eine andere Währung (USD) hat, teilweise aber auch ohne Währungswechsel. Keine Einträge im Fehlerprotokoll.

Version: 0.39.0 (Feb. 2019)
Platform: macosx, x86_64

**Comment by buchen** [comment]
Das kann ich so nicht nachvollziehen. Allerdings ist die "Trade" Funktion noch ziemlich abhängig von der Datenqualität. Sobald der was nicht passt, wird gar nichts mehr angezeigt (oder die alten Werte bleiben stehen). Ich werde auf jeden Fall mal die Fehlermeldung verbessern.
