### ISSUE TITLE
PDF Import Union Investment

### ISSUE THREAD

**Issue by FlorianAlexander** [buchen/portfolio#1137]
PDF Author: ''
PDFBox Version: 1.8.16
-----------------------------------------
Gern berät Sie:
Sparda-Bank eG
Union Investment - Kundenservice
Telefon: 069 58998-6000
Telefax: 069 58998-9000
Herrn E-Mail: service@union-investment.de
Florian Alexander
Musterstr. 31 UnionDepot: 12345678
12345 Musterstadt Depotinhaber:
Florian Alexander
16. November 2018
Abrechnung Nr. 59
Unterdepot-Nr.: 1234567816
Fonds: UniGlobal ISIN: DE0008491051 Verwaltungsvergütung: 1,20 % p. a.
Hinweis: UniProfiRente Altersvorsorgevertrag
- gefördert -
Buchungs-/ Umsatzart Betrag/EUR Ausgabe- Preis/EUR Anteile
Preisdatum aufschlag %
Vortrag vom 18.09.2018 52,963
18.10.2018
17.10.2018 Kauf 160,00
Anlage 160,00 5,00 227,01 0,705
Gesamtausschüttung *1 139,54
16.11.2018
 15.11.2018 Wiederanlage 139,54 0,00 210,62 0,663
Kauf ohne Ausgabeaufschlag
Bestand am 16.11.2018 54,331
*1 Während der Ansparphase erfolgt beim Altersvorsorgevertrag UniProfiRente keine Besteuerung von Erträgen und Wertsteigerungen. Dies
geschieht erst zum Zeitpunkt der Auszahlung oder bei zulagenschädlicher Auflösung des UniProfiRente-Depots im Rahmen der nachgela-
gerten Besteuerung. Diese Abrechnung stellt keine Steuerbescheinigung dar.
Unterdepot-Nr.: 1234567820
Fonds: UniGlobal ISIN: DE0008491051 Verwaltungsvergütung: 1,20 % p. a.
Buchungs-/ Umsatzart Betrag/EUR Ausgabe- Preis/EUR Anteile
Preisdatum aufschlag %
Vortrag vom 12.01.2018 20,746
Gesamtausschüttung *1 53,94
abgeführte Kapitalertragsteuer 0,00
inklusive Solidaritätszuschlag
16.11.2018
1 5.11.2018 Wiederanlage 53,94 0,00 210,62 0,256
Kauf ohne Ausgabeaufschlag
Bestand am 16.11.2018 21,002
*1 Diese Abrechnung stellt keine Steuerbescheinigung dar. Nach Ablauf des Kalenderjahres erhalten Sie automatisch eine für Ihr UnionDepot
geltende Steuerbescheinigung. Bitte berücksichtigen Sie, dass Kapitalerträge steuerpflichtig sind.
Die steuerpflichtigen Erträge betragen 37,76 Euro.
Fortsetzung auf Seite 2
Union Investment Service Bank AG · 60621 Frankfurt am Main
Tel.: 069 58998-0, Fax: 069 58998-9000 · E-Mail: service@union-investment.de · Internet: www.union-investment.de · Registergericht: Amtsgericht Frankfurt am Main HRB 54979
Vorstand: Horst Dietzel, Rainer Kobusch, Barbara Resch · Aufsichtsratsvorsitzender: Hans Joachim Reinke · Gläubiger-ID: DE81USB00000002100  
Einzahlungen: DZ BANK AG Deutsche Zentral-Genossenschaftsbank, Frankfurt am Main, IBAN: DE34 5006 0400 0000 0006 86 (BIC: GENODEFFXXX)
Seite 2 von 2 Datenschutzfeld
zum Schreiben vom 16. November 2018 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
UnionDepot: 12345678 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Depotinhaber: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Florian Alexander XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Steuerübersicht per 16.11.2018
Freistellungsauftrag gültig bis auf Widerruf
erteilter Freistellungsauftrag in EUR: 75,00
verbleibender Freistellungsauftrag in EUR: 37,24
Depotübersicht zum 16.11.2018
Unterdepot- Fondsname/Produktname Anteil- Rücknahme- Depotwert/
Nr. ISIN/Ertragsverwendung bestand preis/Währung Währung
Verwahrart/Lagerland
1234567816 UniProfiRente
UniGlobal 5 210,62 EUR 1.000,00 EUR
DE0008491051/ausschüttend
Girosammelverwahrung/Bundesrepublik Deutschland
1234567820 UniGlobal 10 210,62 EUR 1.000,00 EUR
DE0008491051/ausschüttend
Girosammelverwahrung/Bundesrepublik Deutschland
Im Anteilbestand sind 10,011 Anteile enthalten, die steuerlich als "Altbestand" gelten.*
Gesamt-Depotwert 10.000,00 EUR
* Seit 1. Januar 2018 sind Veräußerungsgewinne aus dem Verkauf der als "Altbestand" gekennzeichneten Anteile steuerpflichtig, wenn sie auf
Wertveränderungen ab dem 1. Januar 2018 zurückzuführen sind. Im Rahmen Ihrer Steuererklärung können Sie für diese Veräußerungsge-
winne einen persönlichen Freibetrag von 100.000 EUR geltend machen. Bitte wenden Sie sich hierzu an Ihr Finanzamt oder Ihren Steuerbe-
rater. Der Verkauf von Fondsanteilen erfolgt nach einer gesetzlich vorgegebenen Reihenfolge. Dabei gelten die zuerst erworbenen Anteile
als zuerst veräußert (FIFO-Methode = First in - first out). Der Gegenwert eines Anteils verändert sich bewertungstäglich. Alle Fondspreise fin-
den Sie im Internet unter www.union-investment.de.
Die Bewertung des Fonds erfolgt zum jeweils letzten verfügbaren Rücknahmepreis.
Bitte überprüfen Sie, ob wir Ihre Aufträge weisungsgemäß ausgeführt haben. Bei Differenzen informieren Sie uns bitte schriftlich unverzüglich 
unter Angabe Ihrer jeweiligen 10-stelligen Unterdepot-Nummer und der Abrechnungsnummer, die Sie auf der ersten Seite der Abrechnung 
finden. Die Verkaufsunterlagen nach § 297 Abs. 5  KAGB und aktuelle Fondsinformationen erhalten Sie kostenlos bei Ihrer Bank oder im 
Internet unter www.union-investment.de.
B ei Fragen sind wir gern für Sie da. Rufen Sie uns einfach an! Sie erreichen uns montags bis freitags zwischen 08:00 und 18:00 Uhr.

**Comment by yannik995** [comment]
Ich habe ein JSON Regex erstellt mit dem man es theoretisch importieren können müsste und dies auch der PDFImportAssistant Klasse hinzugefügt:
`extractors.add(new JSONPDFExtractor(client, "union-investment-purchase.json"));`

Allerdings bekomme ich immer die folgende Meldung:
![image](https://user-images.githubusercontent.com/1337304/98279905-ddb54080-1f9a-11eb-9f28-533a00502d32.png)

@buchen Hast du oder jemand anders eine Idee, woran es liegen könnte?
Ich habe es durch debuggt und dort wird jeder Wert per Regex erkannt.

Ich hatte mit diesem Text getestet:
[unionInv.txt](https://github.com/buchen/portfolio/files/5496154/unionInv.txt)

Und das ist die erstellte Regex JSON Datei:
`
{
	"version": 1,
	"name": "UnionInvestment - Sparplan",
	"locale": "de",
	"pattern": [
		"Union Investment",
		"Abrechnung",
		"Anlage"
	],
	"transactions": [
		{
			"type": "PURCHASE",
			"startsWith": "Unterdepot-Nr.*$",
			"sections": [
				{
					"context": "SECURITY",
					"pattern": [
						"^Fonds. (?<name>.*) ISIN. (?<isin>.+?) .+$"
					]
				},
				{
					"pattern": [
						"^Anlage (?<amount>[\\d.,]+) ([\\d+,.]*) ([\\d+,.]*) (?<shares>[\\d+,.]*)"
					]
				},
				{
					"pattern": [
						"^Bestand am (?<date>\\d+.\\d+.\\d{4}+) .*"
					]
				}
			]
		}
	]
}
`

**Comment by Nirus2000** [comment]
Hallo @FlorianAlexander

ich würde gern den Importer bauen, dazu benötige ich aber noch mehr Dokumente wie
Kauf, Verkauf, Dividenden etc.

Könntest du mir diese hier noch zur Verfügung stellen?

Tutorial:
[Buchungen aus PDF Dateien importieren](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

Grüße
Alex

**Comment by FlorianAlexander** [comment]
@Nirus2000 Bei Union gibt es keine einzelnen Dokumente zu Kauf, Verkauf, Dividenden. Man bekommt nur jedes Quartal eine Abrechnung wie sie schon oben aufgeführt ist.
In dieser Abrechnung hast du dann pro Fonds die Käufe, Verkäufe, Gebühren, Ausschüttungen in dem Zeitraum gelistet.

Sieht ungefähr so aus: Statt Gesamtausschüttung steht dann halt da Verkauf oder Kauf 
<img width="930" alt="Screenshot 2021-02-03 at 03 16 36" src="https://user-images.githubusercontent.com/43973961/106688541-986ed200-65ce-11eb-9ca8-d3c2814d98f6.png">

**Comment by Nirus2000** [comment]
Hallo @FlorianAlexander
ich benötige einen neuen korrekten Extrakt vom Dokument.
So wie dieser hier ist, sind alle Formatierungen nicht vorhanden und kann deswegen nicht verwendet werden also wie im Link
oben beschrieben vorgehen und im Forum unter dem korrekten Beitrag posten.

Grüße
Alex

**Comment by Nirus2000** [comment]
Hallo @FlorianAlexander
leider habe ich von dir noch keinen Post im PP-Forum gesehen.

Loggen Sie sich dazu im Forum unter https://forum.portfolio-performance.info/ ein und erstelle einen Beitrag im PDF-Importer von PDF-Import von UnionInvest/Volksbank/DZ Bank

Wie es funktioniert, können Sie im Video-Tutorial sehen.

Video-Tutorial:
PDF-Dokumente für die Fehlersuche extrahieren

Gruß
Alex
