### ISSUE TITLE
Frage Aktualisierung XML File

### ISSUE THREAD

**Issue by tauchersven1** [buchen/portfolio#1139]
Hallo zusammen,

ich versuche mich ein bischen in das Tool ein zuarbeiten und habe versuchsweise einen Boolschen Wert bei den Stammdaten eines Wertpapiers hinzugefügt. Sozusagen Copy Paste der Funktion für inaktive Wertpapiere. Beim Testen wird mir dieses Feld auch im Formular angezeigt und ich kann es anklicken. Wenn ich auf OK klicke, bekomme ich keine Fehlermeldung, und in der XML Datei wird das zusätzliche Attribut im Schema angezeigt.  Ich sehe dass hier der Defaultwert false hinterlegt ist.  

Wenn ich in der Testumgebung den Wert auf false setze und speichere, wird der wert jedoch nicht überschrieben. Wenn ich den Wert im Test.xml file auf true setze, wird dieser jedoch nicht ausgelesen. (Es wird immer der Defaultwert angezeigt).

Kann mir jemand verraten, wo möglicherweise mein Fehler liegt?

Danke und VG

Sven

**Comment by Ragas13** [comment]
Hallo @tauchersven,

das Feld im Formular muss auch an das richtige Feld gebunden werden, die Erfahrung hatte ich auch als der Kalender implementiert wurde. Daher lohnt sich bspw ein Blick in den Commit https://github.com/buchen/portfolio/commit/4095063037cc7ffc1fdff96ccc3133afbfd46bd3

Ansonsten, wenn du dich mit Anleihen/ Bondage beschäftigst, es wäre evtl übersichtlich wenn du nicht an das Security Model anknüpfst sondern ein eigenes Datenmodell für Bonds ansteuerst.

VG
Marco

**Comment by tauchersven1** [comment]
Vielen Dank das sehe ich mir an. Ich habe auch vor über ein eigenes Modell zu arbeiten, aber soweit bin ich noch nicht. Erstmal will ich die Grundlagen verstehen.

VG

Sven
