### ISSUE TITLE
Degiro import csv

### ISSUE THREAD

**Issue by ehmkah** [buchen/portfolio#1140]
Hallo 

Es gibt ja https://github.com/buchen/portfolio/issues/816 der von pdf import von degiro Daten handelt. Für mich wäre eher der CSV Import interessant.

Wenn ich so einen Config bauen würde, was muss ich machen, damit Ihr testen könnt, dass der Import funktioniert? Vermutlich würde ich es https://github.com/buchen/portfolio/blob/bad7ae8794c1a8237dea74f37de68abae0765f8d/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/csv/csv-config.json eintragen müssen. Wie testet Ihr dann, dass meine COnfig funktioniert?

**Comment by Ragas13** [comment]
Hallo @ehmkah

die richtige Stelle für die Konfiguration hast du gefunden. Aber was den Test betrifft, so  kann es nicht überprüft werden. Die Folgen wären aber unkritisch da dann bestenfalls keine Felder zugeordnet werden. 

Gruß 
Marco

**Comment by tobi-tobsen** [comment]
Moin, 
ich habe ebenfalls Probleme den csv degiro export zu importieren.
Zunächst, weil das Format des Datums nicht auswählbar ist und ggf. zu viele Informationen im degiro export sind. Die Datei .csv sieht so aus: 

`
Datum,Uhrzeit,Produkt,ISIN,Börse,Anzahl,,Kurs ,,Wert in Lokalwährun,,Wert,Wechselkurs,,Gebühr,,Gesamt
12-03-2018,13:37,ISH.S.EU.SEL.DIV.30 U.ETF,DE0002635299,XET,5,EUR,16.5340,EUR,-82.67,EUR,-82.67,,,,EUR,-82.67
`
Sollte dieses so parsbar sein?

**Comment by buchen** [comment]
> Wenn ich so einen Config bauen würde, was muss ich machen, damit Ihr testen könnt, dass der Import funktioniert?

Gar nicht. Als "convenience" würde ich die einfach mit ausliefern.

Aber im Prinzip kannst Du Dir lokal auch eine Konfiguration bauen und auch speichern.


@tobi-tobsen Ist das CSV "Original" - ich frage weil es da leere Spaltenüberschriften gibt

Ich habe die Datei mit folgender Konfiguration einlesen können:
[degiro.zip](https://github.com/buchen/portfolio/files/3439186/degiro.zip)

<img width="598" alt="Bildschirmfoto 2019-07-28 um 14 54 14" src="https://user-images.githubusercontent.com/587976/62006943-dd978580-b147-11e9-8191-46afdb54f0c5.png">

Aber ich vermute das wird so nicht gehen wenn da Wechselkurse drin sind, Gebühren, etc. Um das auszuprobieren, braucht es mehr Beispiele.

**Comment by tobi-tobsen** [comment]
@buchen ja, es ist "original". Ich kann verstehen, dass du weitere Beispiele brauchst. Ich werde mal was "anonymisieren" und hier anhängen, bzw. selber rumprobieren und das ergebnis hier ablegen. Dein Import hat prinzipiell fast geklappt - leider habe ich dinge mit Fremdwährung drin und tue mich schwer die richtigen Mappings zu finden.

**Comment by SamSambuka** [comment]
Hier noch ein paar Beispiele, auch Fremdwährungen dabei.
[transactions_ano.zip](https://github.com/buchen/portfolio/files/4109344/transactions_ano.zip)
