### ISSUE TITLE
ETF Pdf Import comdirect

### ISSUE THREAD

**Issue by CPacki** [buchen/portfolio#1141]
Hallo zusammen,

ich hab einen fehlgeschlagenen ETF Pdf Import von comdirect.

[Kosteninformation_Kauf_1_St._WKN_A0X8ZS.txt](https://github.com/buchen/portfolio/files/2989328/Kosteninformation_Kauf_1_St._WKN_A0X8ZS.txt)

**Comment by masterzuso** [comment]
Hierbei handelt es sich um eine Kosteninformation nach MIFID 2 (https://www.bafin.de/SharedDocs/Veroeffentlichungen/DE/Fachartikel/2018/fa_bj_1807_Kostentransparenz.html)
Hier wird dir nur angezeigt, welche Kosten auf dich durch den Kauf zukommen.
Importieren tust du danach die Wertpapierabrechnung. Diese wird dir etwas später in die Postbox gestellt

**Comment by CPacki** [comment]
Danke!
