### ISSUE TITLE
PDF Import DKB Ertragsgutschrift § 27 KSTG

### ISSUE THREAD

**Issue by FlorianAlexander** [buchen/portfolio#1143]
PDF Author: ''
PDFBox Version: 1.8.16
-----------------------------------------
10919 Berlin
Depotnummer 500123456
Kundennummer 191111111
Florian Mustermann
Abrechnungsnr. 63310000000
Herrn Datum 13.05.2014
Florian Mustermann
Musterstr. 11
12345 Musterstadt
Ertragsgutschrift nach § 27 KStG
Nominale Wertpapierbezeichnung ISIN (WKN)
Stück 200 FREENET AG DE000A0Z2ZZ5 (A0Z2ZZ)
NAMENS-AKTIEN O.N.
Zahlbarkeitstag 14.05.2014 Ertrag pro Stück 1,45 EUR
Bestandsstichtag 13.05.2014
Ex-Tag 14.05.2014
Geschäftsjahr 01.01.2013 - 31.12.2013
Dividendengutschrift nach § 27 KStG 290,00+ EUR
Ausmachender Betrag 290,00+ EUR
Lagerstelle Clearstream Banking FFM (849000 / 4003)
Den Betrag buchen wir mit Wertstellung 14.05.2014 zu Gunsten des Kontos 1234567890 (IBAN DE64 1203 0000 1234
5678 90), BLZ 120 300 00 (BIC BYLADEM1001).
Keine Steuerbescheinigung.
Es handelt sich bei der Ausschüttung um Leistungen aus dem steuerlichen Einlagekonto der Kapitalgesellschaft (§27 Abs.
1-7 KStG). Dieser Ertrag unterliegt laut Gesetz zum Zeitpunkt des Zuflusses keinem Steuerabzug und ist
einkommensteuerfrei. Er mindert jedoch im Nachhinein den Kaufkurs der bezogenen Aktie, so dass bei deren Verkauf
möglicherweise ein entsprechend höherer Kursgewinn zu versteuern ist.
Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.
Bitte ggf. Rückseite beachten.
0883.05140101.0001313ER01

**Comment by FlorianAlexander** [comment]
Ich probiere mich mal dran.

**Comment by FlorianAlexander** [comment]
@buchen ich hätte ne Lösung, aber ich kriege den Pull request nicht hin. Musst du mich dafür erst freischalten?

**Comment by florianletsch** [comment]
@FlorianAlexander Um einen Pull Request zu erstellen, muss nichts freigeschaltet werden. Woran genau hapert's denn?

**Comment by FlorianAlexander** [comment]
@florianletsch danke für deine Antwort. ich hatte sie nicht gesehen.
ich habe erst lernen müssen, dass man zuerst einen Fork machen muss, bevor man einen Pull request erstellen kann.

hier ist der PR: https://github.com/buchen/portfolio/pull/1162
