### ISSUE TITLE
Historische Kurse korrigieren

### ISSUE THREAD

**Issue by ghost** [buchen/portfolio#1167]
Seit ein paar Tagen gibt es beim Wertpapier mit der ISIN IE00BTJRMP35 ein Problem mit den historischen Kursen. Es sind falsche Werte hinterlegt, was sich negativ auf alle Statistiken innerhalb von Portfolio Performance auswirkt:

![image](https://user-images.githubusercontent.com/50886396/58124123-bf744d00-7c0d-11e9-818a-ef81514f0dcb.png)

**Comment by Ragas13** [comment]
Die Frage ist wohl, warum (hier Yahoo Finance) falsche Kursdaten meldet. However, was wäre dein Anliegen wie PP hier damit umgehen sollte?

**Comment by buchen** [comment]
@ghost Wie gesagt, die Kurse kommen von Yahoo. Mittlerweile scheint das bei Yahoo wieder korrigiert zu sein - ich konnte die Kurse problemlos abrufen.
