### ISSUE TITLE
[Maven 3.6.1 does not build PP] Build Fehler: javax.annotation Dependency nicht gefunden

### ISSUE THREAD

**Issue by julianbreiteneicher** [buchen/portfolio#1168]
Hi,

auf meinem System bekomme ich leider folgenden Fehler beim Bauen:

```
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: name.abuchen.portfolio:name.abuchen.portfolio:0.39.2-SNAPSHOT @ /home/jb/git/portfolio/name.abuchen.portfolio/pom.xml
[INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio:0.39.2-SNAPSHOT @ /home/jb/git/portfolio/name.abuchen.portfolio/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   You requested to install 'osgi.bundle; javax.annotation 0.0.0' but it could not be found
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio:0.39.2-SNAPSHOT @ /home/jb/git/portfolio/name.abuchen.portfolio/pom.xml: See log for details -> [Help 1]
```

Wie im Readme beschrieben, habe ich versucht das Projekt mit
```
export MAVEN_OPTS="-Xmx1g"
mvn clean verify -Dtycho.disableP2Mirrors
```
zu bauen.

Ein paar Detail zu meinem System:
```
OS: Arch Linux
Java: OpenJDK 8
Maven: 3.6.1
```

**Comment by buchen** [comment]
Was sagt denn ```mvn -version```?

javax.annotation sollte Teil der Target Platform sein.

Ich habe gerade bei mir lokal den Maven Cache komplett gelöscht und noch mal gebaut. Ich laufe ich nicht in diesen Fehler rein.

```
$ mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /Users/.../Tools/apache-maven-3.6.0
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"
```

(Sorry, sehe den Issue erst jetzt)

**Comment by michaellass** [comment]
Hier das selbe Problem, ebenfalls unter Arch Linux. `mvn -version`:

```
Apache Maven 3.6.1 (NON-CANONICAL_2019-05-22T16:10:23+02:00_root; 2019-05-22T16:10:23+02:00)
Maven home: /opt/maven
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.1.7-arch1-1-arch", arch: "amd64", family: "unix"
```

**Comment by buchen** [comment]
Mir ist unklar wo das schief geht. Der Travis build auf Linux läuft durch.

BTW, ich habe mit Commit 474e5c73b1c0f891687c9539674d7e2e58b5082d die Dependency Resolution umgestellt. Man braucht keinen Maven Build mehr um die Target Platform einmal zu generieren. Die ist jetzt so eingecheckt, dass sie in Eclipse verwendbar ist. @michaellass - tut das bei Dir?

@Ragas13 @sebasbaumh Evtl. macht es auch für Euch Sinn Euren lokalen Setup zu ändern

**Comment by michaellass** [comment]
Ich habe jetzt erst einmal nur maven getestet. Da ändert sich das Verhalten insofern, dass maven deutlich mehr Dependencies heruntergeladen hat. Dafür klemmt es jetzt an folgender Stelle:

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: name.abuchen.portfolio.distro.product 0.39.2.qualifier
[ERROR]   Missing requirement: name.abuchen.portfolio.distro.product 0.39.2.qualifier requires 'org.eclipse.equinox.p2.iu; name.abuchen.zulu.jre.feature.feature.group 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: name.abuchen.portfolio:portfolio.product:0.39.2-SNAPSHOT @ /scratch/bevan/git/portfolio/portfolio-product/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by michaellass** [comment]
Ich habe es noch einmal direkt in Eclipse versucht. Dort bekomme ich die folgenden Fehlermeldungen:

![Bildschirmfoto von 2019-06-08 20-21-46](https://user-images.githubusercontent.com/11042539/59150975-0fd01500-8a2c-11e9-837e-4bf5a118ccc2.png)

Wenn man die Fehler löscht, tauchen sie zwar nicht wieder auf, aber trotzdem lässt sich die Anwendung nicht starten. Stattdessen kommt folgender Fehler:
```
java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Display
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:147)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Display cannot be found by org.eclipse.e4.ui.workbench.swt_0.14.300.v20180906-1121
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by Ragas13** [comment]
@buchen @julianbreiteneicher @michaellass @@sebasbaumh 

Ich habe GIT heute um 22:30 synchronisiert und den offline Cache von Maven geleert und den Eclipse Workspace zurück gesetzt. Nach erstellen der Target Plattform (neues System) +1 und anpassen der Run Configuration funktioniert es bei mir unter Win 10 einwandfrei.

> Apache Maven 3.6.0
> Eclipse SDK Version: 2018-12 (4.10)
> Java version: 11.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.2
> Default locale: de_DE, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by buchen** [comment]
@michaellass 

```
requires 'org.eclipse.equinox.p2.iu; name.abuchen.zulu.jre.feature.feature.group 0.0.0' but it could not be found
```

sollte in diesem Repository zur Verfügung stehen

```
	<repositories>
		<repository>
			<id>portfolio-jre</id>
			<layout>p2</layout>
			<url>http://buchen.github.io/bundled-jre/8.30.0.1-patch1</url>
		</repository>
	</repositories>
```

Da scheint mir vorher noch ein Problem vorzuliegen.
Am Anfang des Logs werden die Dependencies aufgelöst - gibt es da Fehlermeldungen? Poste doch mal das ganze Log (als Attachment).

**Comment by michaellass** [comment]
Fehlermeldungen gibt es keine. Hier der komplette output von
* [mvn clean verify -Dtycho.disableP2Mirrors](https://github.com/buchen/portfolio/files/3269307/mvn.log)
* [mvn -X clean verify -Dtycho.disableP2Mirrors](https://github.com/buchen/portfolio/files/3269308/mvn-debug.log)

**Comment by buchen** [comment]
Mein Output sieht wie folgt aus:

```
INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: name.abuchen.portfolio:name.abuchen.portfolio:0.39.2-SNAPSHOT @ /Users/asbn/Code/portfolio-currencies/name.abuchen.portfolio/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745/
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745/
[INFO] Adding repository http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20180606145124/repository/
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20180606145124/repository/
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20180606145124/repository
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops2/R20180606145124/repository/
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops2/R20180606145124/repository/
[INFO] Adding repository http://download.eclipse.org/technology/babel/update-site/R0.16.0/photon
[INFO] Fetching p2.index from http://download.eclipse.org/nebula/releases/2.0.1/
[INFO] Fetching p2.index from http://download.eclipse.org/nebula/releases/2.0.1/
[INFO] Adding repository http://download.eclipse.org/nebula/releases/2.0.1
[INFO] Fetching p2.index from https://buchen.github.io/portfolio-deps/1.0.0/ (173B)
[INFO] Fetching p2.index from https://buchen.github.io/portfolio-deps/1.0.0/ (173B)
[INFO] Adding repository https://buchen.github.io/portfolio-deps/1.0.0
**[INFO] Fetching p2.index from http://buchen.github.io/bundled-jre/8.30.0.1-patch1/ (173B)
**[INFO] Fetching p2.index from http://buchen.github.io/bundled-jre/8.30.0.1-patch1/ (173B)
**[INFO] Adding repository http://buchen.github.io/bundled-jre/8.30.0.1-patch1
[INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio:0.39.2-SNAPSHOT @ /Users/asbn/Code/portfolio-currencies/name.abuchen.portfolio/pom.xml
```

Ich habe den relevanten Unterschied mit ** markiert.

Mir ist nicht klar, warum das bei Dir nicht gezogen wird.

Im pom.xml steht das Repository drin:

```xml
	<repositories>
		<repository>
			<id>portfolio-jre</id>
			<layout>p2</layout>
			<url>http://buchen.github.io/bundled-jre/8.30.0.1-patch1</url>
		</repository>
	</repositories>
```

Und auch pomDependencies=consider ist gesetzt:

```xml
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<resolver>p2</resolver>
					<pomDependencies>consider</pomDependencies>
```

**Comment by michaellass** [comment]
> Mir ist nicht klar, warum das bei Dir nicht gezogen wird.

Ich habe mal Maven 3.6.0 statt 3.6.1 installiert. Und :tada: es funktioniert wieder! Das erklärt wohl auch, warum plötzlich alle Arch-Nutzer betroffen sind, denn da wurde das Paket [am 22.05. aktualisiert](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/maven&id=d42378d281042e6c3081babd78c184faa61e885a).

Bevor wir zu schnell Schlüsse ziehen, werde ich noch einmal testen, dass es nichts mit der Änderung an `MAVEN_OPTS` zu tun hat.

**Comment by michaellass** [comment]
Probably this one: https://issues.apache.org/jira/browse/MNG-6669

**Comment by Ragas13** [comment]
Jup, das scheint wirklich ein Bug v. 3.6.1 zu sein...

https://bugs.eclipse.org/bugs/show_bug.cgi?id=546463
https://bugs.eclipse.org/bugs/show_bug.cgi?id=545872

**Comment by sebasbaumh** [comment]
> Mir ist unklar wo das schief geht. Der Travis build auf Linux läuft durch.
> 
> BTW, ich habe mit Commit [474e5c7](https://github.com/buchen/portfolio/commit/474e5c73b1c0f891687c9539674d7e2e58b5082d) die Dependency Resolution umgestellt. Man braucht keinen Maven Build mehr um die Target Platform einmal zu generieren. Die ist jetzt so eingecheckt, dass sie in Eclipse verwendbar ist. @michaellass - tut das bei Dir?
> 
> @Ragas13 @sebasbaumh Evtl. macht es auch für Euch Sinn Euren lokalen Setup zu ändern

Ja, habe es mal komplett neu aufgesetzt und funktioniert jetzt ohne die Target-Platform nochmal zu erstellen. Nur die "Add required plugins" muss man noch ausführen.

**Comment by buchen** [comment]
Über das *enforcer plugin* könnte man eine Rule definieren die Version 3.6.1 ausschliesst und eine entsprechende Fehlermeldung ausgibt. Leider läuft das enforcer plugin erst **nach** der Dependency Resolution, d.h. das hilft hier nicht.

Maven Tycho kann man ebenfalls nicht beibringen eine product configuration (es geht nur um die Bistro) per default *nicht* zu verwenden. Es werden immer alle Dateien eingelesen die dem Muster "*.product" entsprechen.

Bleibt Dokumentation. Mal sehen wie schnell Maven eine neue Version released.

**Comment by buchen** [comment]
BTW, Apache Maven 3.6.2 ist veröffentlicht. Damit wird PP wieder ohne Probleme genaut.
