### ISSUE TITLE
Tooltip wird bei Hover auch bei leerem Notizfeld gezeigt

### ISSUE THREAD

**Issue by PatrickLerner** [buchen/portfolio#1170]
Wie hier zu sehen, wenn man 'Notiz' als Spalte hat, so wird für jede Zeile bei Hover im Tooltip der gesammte Inhalt nochmal angezeigt, was bei langen Notizen sinnvoll ist. Bei leeren Notizen wird dann jedoch ein leerer Tooltip angezeigt was etwas komisch wirkt.

![Screenshot 2019-06-08 at 09 02 13](https://user-images.githubusercontent.com/1738261/59143539-b389d880-89cc-11e9-861d-1cd2a416986b.png)

Zu erwarten wäre, dass bei leeren Notizen kein Tooltip angezeigt wird. ggF könnte man auch argumentieren dass wenn die komplette Notiz bereits sichtbar ist, dass dann auch kein Tooltip angezeigt werden müsste, aber zumindest wirkt es hier nicht so komisch.

- Version: 0.39.1 (Apr 2019)
- Platform: macosx, x86_64

**Comment by buchen** [comment]
Fixed. Vielen Dank für die Fehlermeldung!

> ggF könnte man auch argumentieren dass wenn die komplette Notiz bereits sichtbar ist, dass dann auch kein Tooltip angezeigt werden müsste, aber zumindest wirkt es hier nicht so komisch.

Das Verhalten kann ich nicht ohne grösseren Aufwand beeinflussen. Und sehe ich auch nicht so problematisch. Aber dieser leere Tooltip sieht blöd aus.
