### ISSUE TITLE
Zwei Fenster auf Mac?

### ISSUE THREAD

**Issue by codeofsumit** [buchen/portfolio#1176]
![image](https://user-images.githubusercontent.com/2399810/59908393-9530cd80-940d-11e9-8b1a-3dd1093d1433.png)

Gestern habe ich irgendwie ausgelöst, das Portfolio Performance auf zwei Fenstern verteilt ist. Die Hauptapp und die Datei die geöffnet ist.

Jedes mal wenn ich die XML öffne, öffnet sie sich in einem neuen Fenster. Schließe ich das hintere, leere Fenster, beendet Portfolio Performance.

Bekomme ich das irgendwie wieder in ein Fenster?

Danke für jede Hilfe!

**Comment by buchen** [comment]
Versuch mal über das Menü *Hilfe -> Debug: GUI zurücksetzen...*

**Comment by codeofsumit** [comment]
das hat geklappt 👍 , vielen dank!
