### ISSUE TITLE
Missing requirement: name.abuchen.zulu.jre.feature.feature.group

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#1178]
Ich habe Probleme beim Bauen von Portfolio Performance:

    [INFO] Scanning for projects...
    [INFO] Computing target platform for MavenProject: name.abuchen.portfolio:name.abuchen.portfolio:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio\pom.xml
    [INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745/
    [INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745/
    [INFO] Adding repository http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745
    [INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20180606145124/repository/
    [INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20180606145124/repository/
    [INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20180606145124/repository
    [INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops2/R20180606145124/repository/
    [INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops2/R20180606145124/repository/
    [INFO] Adding repository http://download.eclipse.org/technology/babel/update-site/R0.16.0/photon
    [INFO] Fetching p2.index from http://download.eclipse.org/nebula/releases/2.0.1/
    [INFO] Fetching p2.index from http://download.eclipse.org/nebula/releases/2.0.1/
    [INFO] Adding repository http://download.eclipse.org/nebula/releases/2.0.1
    [INFO] Fetching p2.index from https://buchen.github.io/portfolio-deps/1.0.0/ (173B)
    [INFO] Fetching p2.index from https://buchen.github.io/portfolio-deps/1.0.0/ (173B)
    [INFO] Adding repository https://buchen.github.io/portfolio-deps/1.0.0
    [INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio\pom.xml
    [INFO] Resolving class path of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio\pom.xml
    [INFO] Computing target platform for MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.tests:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.tests\pom.xml
    [INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.tests:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.tests\pom.xml
    [INFO] Resolving class path of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.tests:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.tests\pom.xml
    [INFO] Computing target platform for MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.ui:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.ui\pom.xml
    [INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.ui:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.ui\pom.xml
    [INFO] Resolving class path of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.ui:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.ui\pom.xml
    [INFO] Computing target platform for MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.ui.tests:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.ui.tests\pom.xml
    [INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.ui.tests:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.ui.tests\pom.xml
    [INFO] Resolving class path of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.ui.tests:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.ui.tests\pom.xml
    [INFO] Computing target platform for MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.feature:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.feature\pom.xml
    [INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.feature:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.feature\pom.xml
    [INFO] Resolving class path of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.feature:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.feature\pom.xml
    [INFO] Computing target platform for MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.bootstrap:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.bootstrap\pom.xml
    [INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.bootstrap:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.bootstrap\pom.xml
    [INFO] Resolving class path of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.bootstrap:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\name.abuchen.portfolio.bootstrap\pom.xml
    [INFO] Computing target platform for MavenProject: name.abuchen.portfolio:portfolio.product:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\portfolio-product\pom.xml
    [INFO] Resolving dependencies of MavenProject: name.abuchen.portfolio:portfolio.product:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\portfolio-product\pom.xml
    [INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
    [ERROR] Cannot resolve project dependencies:
    [ERROR]   Software being installed: name.abuchen.portfolio.distro.product 0.39.3.qualifier
    [ERROR]   Missing requirement: name.abuchen.portfolio.distro.product 0.39.3.qualifier requires 'org.eclipse.equinox.p2.iu; name.abuchen.zulu.jre.feature.feature.group 0.0.0' but it could not be found
    [ERROR] 
    [ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
    [ERROR] Cannot resolve dependencies of MavenProject: name.abuchen.portfolio:portfolio.product:0.39.3-SNAPSHOT @ C:\eclipseWorkspace\portfolio\portfolio-product\pom.xml: See log for details -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

@buchen Konkret scheint hier `name.abuchen.zulu.jre.feature.feature.group` zu fehlen - hast Du da etwas geändert?

**Comment by sebasbaumh** [comment]
Meine eclipse-Version ist 2019-06 (4.12.0), vielleicht liegt es auch daran?

**Comment by sebasbaumh** [comment]
Das Entfernen des Features ([hier](https://github.com/buchen/portfolio/blob/master/portfolio-product/name.abuchen.portfolio.distro.product#L54)) hilft und lässt es wieder kompilieren.
Bei mir lässt es sich dann auch starten, aber ich habe eh ein separates JDK 11 installiert.

**Comment by buchen** [comment]
> Meine eclipse-Version ist 2019-06 (4.12.0), vielleicht liegt es auch daran?

Nein, ich nutze auch 2019-06.

Aber: welche Maven Version nutzt Du?

Version 3.6.1 zieht die pom Dependencies nicht richtig (und das JRE ist eine POM dependency) - siehe hier: #1168

**Comment by sebasbaumh** [comment]
Ich nutze das embedded Maven im eclipse: Version 3.6.1.
Ist natürlich blöd, wenn das gerade Probleme bereitet.

**Comment by buchen** [comment]
> Ist natürlich blöd, wenn das gerade Probleme bereitet.

Da bleibt nur solange das JRE feature rauszunehmen.
Es hat aus irgendwelchen Gründen nicht funktioniert, das Feature ebenfalls über die Target Platform zu ziehen.

**Comment by sebasbaumh** [comment]
Seltsam, dass es erst jetzt aufgetaucht ist.
Das war auch das einzige Feature, was Probleme bereitet hat.
Ich hoffe, dass sich da noch etwas tut bei Tycho/Maven.

**Comment by buchen** [comment]
> Ich hoffe, dass sich da noch etwas tut bei Tycho/Maven.

Wenn ich das richtig verstanden habe ist der Commit bei Maven schon wieder reverted. Mir ist aber unklar wann eine Maven Version 3.6.2 veröffentlicht wird.

Ich selber baue nur ab und an mit Maven auf der Kommandozeile (ansonsten überlasse ich das Travis) und da habe ich kein Problem mit der Maven Version.

**Comment by sebasbaumh** [comment]
Ok, dann warten wir einfach ab. Solange ich es noch so bauen kann, ist es ok für mich.
