### ISSUE TITLE
Import DKB Kontoauszug / Kreditkartenabrechnung PDF schlägt fehl

### ISSUE THREAD

**Issue by StegSchreck** [buchen/portfolio#1182]
![image](https://user-images.githubusercontent.com/9078002/60826803-01058b00-a1af-11e9-8615-afd374072241.png)

Sowohl Kontoauszüge als auch Kreditkartenabrechnungen mit dem gleichen Fehler (siehe Screenshot)
Import von Wertpapierabrechnungen funktioniert soweit einwandfrei

**Systeminformationen:**
Version: 0.40.0 (Jul 2019)
Platform: linux, x86_64

**Comment by ZfT2** [comment]
Das ist nicht weiter verwunderlich, denn bislang ist auch nur der Import von Wertpapierabrechnungen implementiert. 
Ich habe mich vor einiger Zeit mal am Import der VISA / Tagesgeld Abrechnungen versucht, das gestaltete sich aber etwas schwierig... Wenn ich mal Zeit habe, würde ich mich da noch mal dran machen, oder es findet sich jemand anderes dafür.

**Comment by StegSchreck** [comment]
Ah alles klar. Danke für die Antwort! 
Würde mich freuen, sobald das Feature da ist.
