### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by PatrickvL** [buchen/portfolio#1214]
Publishing a version ported to Android, for use on tablets and mobile phones, would open up a much larger user-base and bring high exposure.

Since there's no good tool for portfolio management on Android yet, so this would be a great contender for filling that void!!!

**Comment by buchen** [comment]
Yes, an Android version (or any mobile version) would be very cool. If somebody has the time and skills do so, I would be very happy to help. Personally, I do not have the time at the moment to start something like this.

**Comment by metal450** [comment]
I'd love to see this too...might be good to consider leaving the issue open, so anyone else who stumbles upon it or wants to chime in or contribute would see it? I'd imagine this would be a popular idea ;)

**Comment by zgjavi** [comment]
I would love this too.
