### ISSUE TITLE
Berichtszeitraum: Merfachauswahl bei Radiobuttons möglich

### ISSUE THREAD

**Issue by DmRodionov** [buchen/portfolio#1221]
Hallo zusammen,

im Dialog "Neuer Berichtzeitraum" funktioniert die RadioButton-Gruppe falsch wenn man die Buttons nicht direkt anklickt, sondern nur den dazugehörigen Wert ändert.

Startzustand:
![grafik](https://user-images.githubusercontent.com/1448926/64105626-e139b000-cd76-11e9-8666-a9b7a80b712e.png)

Hier klicke ich auf das Textbox mit "430" und ändere den Wert auf "431" (manuell oder mit den input spinners). Der Radiobutton neben "Letzte 1 Jahre 2 Monate" bleibt ausgewählt und dazu kommt noch der neben "Letzte 431 Tage"
![grafik](https://user-images.githubusercontent.com/1448926/64105700-05958c80-cd77-11e9-93ab-c112cfe0670f.png)

und so weiter, und so fort...
![grafik](https://user-images.githubusercontent.com/1448926/64105712-09c1aa00-cd77-11e9-82e4-b2bbc39bc4ae.png)

Ist scheinbar nur ein GUI-Fehler, da beim Klick auf "OK" die letzte Eingabe korrekt übernommen wird.

Gruß
Dmitrij

**Comment by buchen** [comment]
Danke für die Rückmeldung. Schaue ich mir an.

**Comment by sennahLessert** [comment]
der Bug existiert nach wie vor. Ich werde mich um einen Bugfix bemühen.

**Comment by DmRodionov** [comment]
Behoben in https://github.com/buchen/portfolio/pull/1248
Thank you, @sennahLessert !
