### ISSUE TITLE
Very slow startup time since latest update

### ISSUE THREAD

**Issue by th23x** [buchen/portfolio#1225]
Hey there,

since the latest update PP on my PC (Win 10) as well as the one of a friend is taking very much longer than before. Not opening an individual portfolio file, but the startup of the program itself now takes easily 30-40 seconds while before it was maybe 3-5 seconds.

Any information that might help to investigate, please let me know...

Thanks and kind regards
Thorsten

**Comment by Ragas13** [comment]
Dear Thorsten,


this is strange as I use Win10 as well, but it's still ~5 seconds at my side.

I guess there are some local conflicts at your local PP software. Maybe you should delete your local version and download the latest version from the website. Before you delete any files, please make a backup of your portfolio files!!!! Otherwise you will start from the scratch.

**Comment by buchen** [comment]
I am not aware of any change that should have an impact on what PP does during startup.

About two months ago, I changed the way PP restores the window layout. Do you have a complicated window layout (multiple files open; multiple views on the same file)?

Besides the suggestion by @Ragas13, maybe it helps to move the "workspace" directory. When starting PP, a new workspace directory is created. If it is faster then, I would be interested to what is "in" the workspace directory. See https://help.portfolio-performance.info/installation/#workspace-verzeichnis

**Comment by th23x** [comment]
Thanks to both of you @buchen and @Ragas13 for the quick reply and some suggestions...I tried both ideas and it did change anything. Neither (re)moving the workspace dir nor a complete new copy, and also not doing both together.

Did some further "analysis" what happens: It's the first start after booting, that is so slow. Closing PP and opening again is still 3-5 secs as always.

When looking at the Task Manager during the PP startup I see the following (see attached images before and during start).

Not sure what changed over the past weeks (?) that triggers now the **Anti Malware Protection of Windows Defender** to kick in so heavily. Never had this before...

![before_start_pp](https://user-images.githubusercontent.com/13735303/64281414-5feb4480-cf53-11e9-9a03-741e1e312bf9.jpg)

![during_start_pp](https://user-images.githubusercontent.com/13735303/64281434-6aa5d980-cf53-11e9-9524-447c5917cea2.jpg)

I can live with it, no big issue... Just in case you have any idea, please let me know!?

**Comment by Ragas13** [comment]
> I can live with it, no big issue... Just in case you have any idea, please let me know!?

Ich habe den Windows Defender in Verdacht, hast du testweise diesen schon mal deaktiviert und dann die Ladezeiten geprüft?

**Comment by th23x** [comment]
Ja, ist definitiv die Anti Malware Protection des Windows Defender.

Nur ohne die möchte ich den PC eigentlich nicht laufen lassen. Und noch dazu scheint kein anderes Program (so stark) betroffen zu sein. Und auch bei PP war dies bis vor kurzem nicht der Fall.

**Comment by Ragas13** [comment]
Windows Defender ist bekannt dafür Phasenweise mit Java Applikationen wie PP nicht zurecht zukommen, sprich auch die enthaltenen JAR-Datein zu lösen.

Möglicherweise kannst du hier den Defender via Kommandozeile einstellen, oder du wechselst den Virenscanner :wink:

**Comment by th23x** [comment]
Okay, für mich erstmal "close" - es liegt am Windows Defender, die Auswirkung ist (warum auch immer) sehr signifikant. Ich nehme es in Kauf bzw steige doch wieder auf Kaspersky um...
