### ISSUE TITLE
Uhrzeit für alle Trasaktionen

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#1226]
besteht die Möglichkeit die Uhrzeit für alle Transaktionen einzubauen? Aktuell stimmt mein Saldo aufgrund der vielen täglichen Buchungen oft nicht, und ich muss ständig nachrechnen, ob mein Broker  versteckte Gebühren eingebaut hat. Erst durch Angabe der Uhrzeit wird die korrekte Reihenfolge der Buchungen sowie Saldo sichergestellt.

**Comment by buchen** [comment]
Nehme ich bei Gelegenheit mit auf.

**Comment by megabugman** [comment]
Danke!
