### ISSUE TITLE
Manually set currencies which are not found in the ECB reference data

### ISSUE THREAD

**Issue by schopenhauer** [buchen/portfolio#1228]
Is there an option to manually set an exchange rate (e.g. Kazakhstani tenge - _KZT_) which is not currently available in the ECB reference data feed? If not, it would be worthwhile checking, whether this could be added as a feature.

**Comment by Ragas13** [comment]
This feature is already present in PP, just add a custom currency instead of a new security.

A German how to is available at https://help.portfolio-performance.info/waehrungen/
