### ISSUE TITLE
Israelischer Shekel als ILS statt ILa

### ISSUE THREAD

**Issue by Chikitaman** [buchen/portfolio#1229]
Die Kurse an der Tel Aviv Stock Exchange (TASE) werden in Shekel Agorot `ILa` und nicht Shekel `ILS` angegeben:
```
1 ILS = 100 ILa
```
Der Wechselkurs zu `EUR` wird aber für `ILS` angegeben. Dadurch erscheinen entweder Einstandskurse oder Kursgewinne/-verluste stark verzerrt.

Es sollte eine weitere Währung ähnlich zu `GBP` und `GBX` bei britischen Wertpapieren eingeführt werden.

**Comment by buchen** [comment]
👍

**Comment by buchen** [comment]
Ist drin #1232
