### ISSUE TITLE
Trade Republic: PDF Dividends 

### ISSUE THREAD

**Issue by rbu** [buchen/portfolio#1234]
Here's two types of PDFs from Trade Republic that Portfolio cannot handle.

1. Dividends statement
```
PDF Author: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
My Name SEITE 1 von 1
My Str. 2 DATUM 12.09.2019
D 12345 Berlin DEPOT XXXXXXXXX
DIVIDENDE
ÜBERSICHT
Dividende mit dem Ex-Tag 14.08.2019.
POSITION ANZAHL ERTRÄGNIS BETRAG
Microsoft Corp. 10 Stk. 0,460 USD 4,60 USD
Registered Shares DL-,00000625
US5949181045
GESAMT 4,60 USD
ABRECHNUNG
POSITION BETRAG
Quellensteuer DE für US-Emittent -0,690 USD
Zwischensumme 3,91 USD
Zwischensumme 1,106 EUR/USD 3,54 EUR
Kapitalertragssteuer -0,420 EUR
Solidaritätszuschlag -0,020 EUR
GESAMT 3,10 EUR
BUCHUNG
VERRECHNUNGSKONTO VALUTA BETRAG
DE63110XXXXXXXXXXXXXXX 12.09.2019 3,10 EUR
Microsoft Corp. Registered Shares DL-,00000625 in Girosammelverwahrung.
Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.
Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie 
Leistung.
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
ABRE / 12.09.2019 / 363XXXXX / XXXX-XXXX
```

2. Knock out certificate is removed ("Tilgung")
This happens when a knock-out certificate reaches its strike price and is removed from the market. It sits in your portfolio for a few more days and then gets removed/"sold for 1ct" by the broker. You receive this statement:

```
PDF Author: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
My Name SEITE 1 von 1
My Str. 2 DATUM 20.09.2019
D 12345 Berlin DEPOT XXXXXXXXX
TILGUNG
ÜBERSICHT
NR. BUCHUNG WERTPAPIER ANZAHL
1 Tilgung HSBC Trinkaus & Burkhardt AG 500 Stk.
TurboC O.End SAP
DE000TR81Z50
ABRECHNUNG
NR. POSITION SUMME
1 Kurswert 0,500 EUR
SUMME 0,500 EUR
2 Kapitalertragssteuer Optimierung 10,98 EUR
Solidaritätszuschlag Optimierung 0,600 EUR
SUMME 11,58 EUR
GELDBUCHUNG
VERRECHNUNGSKONTO VALUTA BETRAG
DE63110XXXXXXXXXXXXXXX 23.09.2019 12,08 EUR
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
ABRE / 20.09.2019 / 363XXXXX / XXXX-XXXX
```

**Comment by lhein** [comment]
Das Importieren von Dividendenerträgen scheint immer noch ein Problem zu haben. Er steigt grundsätzlich bei https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/actions/CheckCurrenciesAction.java#L151-L152 aus. Selbst wenn ich diese Prüfung deaktiviere, dann funktioniert zwar der Import, aber die Quellensteuer taucht in der Buchung nicht auf.

**Comment by Loader23** [comment]
Gibt es dazu schon etwas neues? Gibt immer die Meldung:
"Steuern und Gebühren dürfen keine Währung haben: USD x,xx"

**Comment by bobtothem** [comment]
Ich habe auch das Problem bei Dividenden aus dem Ausland, z.B. den USA. Da sind einige Zahlen in USD und andere in EUR. Deshalb steht da immer eine Währung mit dabei. Kann man dazu eine Lösung finden?

**Comment by masterzuso** [comment]
Es scheint ein Problem mit dem Update von Portfolio Performance zu sein.
Den Fehler habe ich in meiner alten Version mit etlichen Updates auch. 
Wenn ich Portfolio Performance aus Eclipse starte oder die aktuelle Version frisch runterlade ist der Fehler weg.

**Comment by Loader23** [comment]
Habe es mal getestet, neue Depot.xml funktioniert doch sobald ich meine Depot.xml lade funktioniert es nicht mehr.

**Comment by andre68723** [comment]
neues Depot angelegt mit 0.43.1 - Dividendenimport einer ETF-Ausschüttung
"Unbekannter oder nicht unterstützter Buchungstyp"

keine Änderung bei 0.43.2-SNAPSHOT


```
PDF Author: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
My Name SEITE 1 von 1
My Street 1 DATUM 26.09.2019
D 69190 Walldorf DEPOT xxxxxx
AUSSCHÜTTUNG
ÜBERSICHT
Ausschüttung mit dem Ex-Tag 12.09.2019.
POSITION ANZAHL ERTRÄGNIS BETRAG
iShsV-EM Dividend UCITS ETF 10 Stk. 0,563 USD 5,63 USD
Registered Shares USD o.N.
IE00B652H904
GESAMT 5,63 USD
ABRECHNUNG
POSITION BETRAG
Zwischensumme 5,63 USD
Zwischensumme 1,102 EUR/USD 5,11 EUR
Kapitalertragssteuer -0,890 EUR
Solidaritätszuschlag -0,040 EUR
GESAMT 4,18 EUR
BUCHUNG
VERRECHNUNGSKONTO VALUTA BETRAG
DExxxxxx 25.09.2019 4,18 EUR
iShsV-EM Dividend UCITS ETF Registered Shares USD o.N. in Wertpapierrechnung.
Lagerland: Republik Irland
Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.
Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie 
Leistung.
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
ABRE / 26.09.2019 / 91006300 / 5a5c-a8c2

```

**Comment by ChrisKolan** [comment]
In Version 0.44.1 (Feb 2020) tritt [dieses Problem](https://github.com/buchen/portfolio/issues/1234#issuecomment-565385686) immer noch auf.

![image](https://user-images.githubusercontent.com/9021862/74597621-aa283400-5062-11ea-9410-881282ee7be0.png)

**Comment by Loader23** [comment]
Bei meinen Tests habe ich herausgefunden, dass es davon abhängt was zuerst importiert wird.

Auf dem Kauf Dokument steht keine Währung sondern nur der Euro Preis. Die Dividende hat aber eine Währungsumrechnung drin und dann kommt es zu dieser Fehlermeldung.

Wenn man zuerst die Dividende importiert kann man zwar immer die Dividende importieren aber das Kauf dokument nicht mehr. Zusätzlich wird die Aktie auch noch mit Dollar angelegt. Das alles habe ich allerdings erst festgestellt, nachdem ich https://github.com/buchen/portfolio/issues/1365 aufgemacht habe xD

Es müsste wahrscheinlich so sein, dass Portfolio die Währung einfach ignoriert und immer selbst den Euro berechnet mit den Angaben auf dem PDF.

**Comment by ChrisKolan** [comment]
@Loader23 Ich kann all dies bestätigen. Es scheint, dass es derzeit nicht möglich ist, Dokumente aus Trade Republic mit zwei Währungen zu behandeln.

**Comment by networxnet** [comment]
@ChrisKolan kannst du erklären wieso? Ich kann die Problematik dahinter nicht nachvollziehen.

Depot läuft in EUR, Papier wir din EUR geführt, Dividendensumme wird in EUR angegeben und verrechnet.
Lediglich die Quellensteuer wird in der Abrechnung nur in USD angegeben, allerdings dann mit dem ebenfalls angegebenen Umrechnungskurs umgerechnet. Mit diesem sollte sich die Quellensteuer im Zuge des Imports doch problemlos in EUR umrechnen lassen oder als Differenz Dividende x Stück - Auszahlungsbetrag berechnen lassen.
