### ISSUE TITLE
Eigene Top-Level-Kategorien tauchen nicht in Tortendiagramm auf

### ISSUE THREAD

**Issue by verybadsoldier** [buchen/portfolio#1244]
Wenn man unter `Klassifizierungen` eine neue Top-Level-Kategorie anlegt, dann taucht diese u.U. nicht z.B. unter `Tortendiagramm` auf. Dies passiert offebar nur, wenn gleichzeitig *kein* Element der Kategorie `Ohne Klassifizierung` zugeordnet ist. Sobald mindestens ein Element in `Ohne Klassifierzung` ist, dann werden auch die Elemente in meiner neuen Top-Level-Kategorie angezeigt.

Reproduzieren:
![image](https://user-images.githubusercontent.com/364469/66240796-fef38f80-e6fd-11e9-92df-221b352629dc.png)

sieht dann so aus. Also `Anderes` fehlt:
![image](https://user-images.githubusercontent.com/364469/66240893-1c285e00-e6fe-11e9-8d23-abcfd31248fd.png)

Verschiebe ich nun `w2` nach `Ohne Klassifizierung`, dann sieht es korrekterweise so aus:
![image](https://user-images.githubusercontent.com/364469/66240981-3e21e080-e6fe-11e9-9483-b4ca22d98f2b.png)

Hintergrund:
Ich möchte mir eine Top-Level-Kategorie `Anderes` anlegen, um dort Konten/Wertpapiere hin verschieben zu können, die z.B. nicht einer bestimmten Region zugeordnet sind (z.B. ein Girokonto). Ich möchte diese Element von denen trennen, denen ich tatsächlich noch keine Kategorie zugeordnet habe (im Idealfall ist bei mir dann `Ohne Kategorie` immer leer wenn ich alles brav zugeordnet habe).

Reproduziert mit Version:
```
Version: 0.42.1 (Okt. 2019)
Platform: win32, x86_64
Java: 11.0.4+11-LTS, Azul Systems, Inc.
```

**Comment by verybadsoldier** [comment]
Also ich hab das Gefühl, dass eigene Top-Level-Kategorien eigentlich gar nicht vorgesehen sind, kann das sein?
Ich konnte eine erstellen, in dem ich sie innerhalb der Kategorie `Wertpapierart` erstellt habe und dann aber auf die oberste Ebene verschoben habe. War das ein Hack? ^^

**Comment by verybadsoldier** [comment]
...beim Speichern werden die neuen Top-Level-Kategorien rausgeschmissen und die Children landen wieder in `Ohne Klassifizerung`. Alles keine gute Vorzeichen Oo

**Comment by Ragas13** [comment]
Soweit ich es mitbekommen habe, als oberster Knoten geht nur ein Punkt. Es ist wie eine Pyramide.

Aber eventuell hilft dir folgende Alternative? 

```
Klassifizierung
》 Sonstiges 
》》 Girokonto 
》》 Tagegeld
》 Wertpapierarten
》》 Aktien
》》》 w1
》》》 w2
》》 Aktienfonds
》》 Exchange Traded Funds
```

**Comment by verybadsoldier** [comment]
Also generell glaube ich, geht es schon, mehrere Top-Level-Knoten zu haben. Wenn ich den Code richtig verstehe, dann wird das momentan auch gemacht, wenn man irgendwas in `Ohne Klassifizierung` drin hat. Dann sind `Ohne Klassifizierung` und `Wertpapiere` jeweils oberste Knoten. Es wird dann ein virtueller Root-Knoten genutzt:
https://github.com/buchen/portfolio/blob/7c77d9c04594bfc5b7c1532daf122968fd022ccd/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/taxonomy/TaxonomyModel.java#L326

---
Deine Methode verstehe ich so, dass die Top-Level Kategorie `Wertpapierarten` in `Klassifizierung` umbenannt wird und dann da drin wieder `Wertpapierarten` angelegt wird und parallel dazu dann eben `Sonstiges`?
Finde ich auf jeden Fall gut und damit kann ich prinzipiell gut leben, danke!

Wenn eigene Top-Level-Knoten generell nicht vorgesehen sind, dann würde ich das Ticket schließen?

**Comment by Ragas13** [comment]
> Wenn eigene Top-Level-Knoten generell nicht vorgesehen sind, dann würde ich das Ticket schließen?

Ob eigene Top-Level-Knoten angedacht sind, kann wenn nur @buchen beurteilen. Aber unterm Strich ob jetzt mehrere top-level-Knoten und einen darüber liegenden virtuellen Knoten (wg. Pie-Chart) oder einen sichtbaren der alles andere unterordnet...

Entscheidend für das schließen ist mE, ob du das "Problem" als geklärt /behoben ansiehst.

**Comment by verybadsoldier** [comment]
Technisch besteht das Problem mMn weiterhin, nur dass es mich persönlich jetzt nicht mehr stört :)

Wenn eigene Top-Level-Knoten nicht vorgesehen sind, dann könnte man auch einfach das Verschieben von Knoten auf die oberste Ebene technisch verhindern. Das ist zumindest der einzige Weg, den ich bisher finden konnte, wie man Top-Level-Knoten erzeugen kann. In diesem Fall wäre dieses Ticket hier natürlich auch hinfällig.

**Comment by buchen** [comment]
> Wenn eigene Top-Level-Knoten nicht vorgesehen sind, dann könnte man auch einfach das Verschieben von Knoten auf die oberste Ebene technisch verhindern.

Das habe ich jetzt mal gemacht.
