### ISSUE TITLE
Deployment doesn't work

### ISSUE THREAD

**Issue by sennahLessert** [buchen/portfolio#1245]
**Bug Reproduktion**

- lösche dein ~/.m2 Verzeichnis
- Klone das Projekt
`cd portfolio-app`
`mvn install`

**Erwartet**
- Maven Build läuft erfolgreich durch

**Tatsächlich**
- das Auflösen einiger Abhängigkeiten schlägt fehl aufgrund aufgrund falscher URI's

ps.: ich habe bereits einen Pull-Request mit dem Fix gemacht. #1247

**Comment by Ragas13** [comment]
Etwas irritiert mich dein pull #1247 i.V.m. deinem Hinweis auf ```mvn install```.

Dein pull ändert nur die Target-Plattform von Eclipse, hat aber keine Auswirkungen auf MAVEN :thinking:

**Comment by sennahLessert** [comment]
die Abhängigkeiten aus der "portfolio-target-definition" Datei werden definitiv heruntergeladen. Wenn dort auf eine Ressource verwiesen wird, die nicht existiert, dann stoppt das Deployment. Soweit so gut. Vor dieser Änderung konnte ich die Anwendung nicht starten bzw. deployen

**Comment by buchen** [comment]
Danke @sennahLessert - Leider passiert mir das mit der Babel Abhängigkeit immer mal wieder. Die URLs bleiben nicht stabil, aber durch das Caching der Abhängigkeiten merke ich das nicht sofort.
