### ISSUE TITLE
CSV Import übernimmt teilweise Wertpapier nicht

### ISSUE THREAD

**Issue by marco-5** [buchen/portfolio#1251]
How to reproduce:
1. Leeres PP Projekt anlegen
2. CSV Import des folgenden Files in PP als Kontoumsätze:
[konto.txt](https://github.com/buchen/portfolio/files/3718047/konto.txt)
(Dieses File wurde übrigens durch ein "Exportieren" in PP erzeugt)
3. Die erste Seite des CSV Import Wizard sieht dann so aus (Wertpapiere sind noch alle vorhanden):
![csv_import_wizard_1](https://user-images.githubusercontent.com/56444184/66659239-63a17380-ec43-11e9-97a8-e100479bdd2a.PNG)
4. Nach einem Klick auf weiter sieht das ganze dann aber so aus:
![csv_import_wizard_2](https://user-images.githubusercontent.com/56444184/66659240-63a17380-ec43-11e9-9646-699be21d222e.PNG)
Wie man sehen kann, wurde hier bei den Kontoumsatz Typen Gebühren, Gebührenerstattung und Steuern das Wertpapier nicht mehr übernommen.

**Comment by msschl** [comment]
Selbe Problem

**Comment by buchen** [comment]
Merged. Danke! Kommt mit der nächsten Version.
