### ISSUE TITLE
investment plans - view next execution date

### ISSUE THREAD

**Issue by cqst** [buchen/portfolio#1259]
Hello and thx for this awesome app 

First, sorry if this is a duplicate as I don't speak German :)

Would be nice in "investments plans" view to add column in order to see the "next execution date". 

Thx again
Cheers

**Comment by Ragas13** [comment]
No worry regarding language skills, english is supported as well 😉 

Proposed to the owner as follows:
![InvestmentPlan](https://user-images.githubusercontent.com/29358155/67151215-ea4cf500-f2c2-11e9-897c-7118d124bfdc.JPG)
