### ISSUE TITLE
[Testing] Neuer Zeitraum "Halteperiode" im SecurityChart

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#1261]
@Ragas13 

Mit f5f9c8f5458901007e4cea4b6376d00fac3ba705 kann man jetzt die "Halteperiode" als Zeitraum in SecurityChart auswählen. Ich musste dafür ein paar Dinge umbauen - siehe auch Kommentar in dem Commit. **Es wäre cool wenn Du die SecurityCharts bei Gelegenheit testen könntest.**

Es gibt da leider so gut wie keine Tests (wie es für den ganzen UI Code fast keine Tests gibt was vielleicht langsam ein Problem wird weil die Nebenwirkungen einer Änderung nicht mehr gut abzuschätzen sind). Ich habe geschaut ob alles weiterhin tut: mit oder ohne Bollinger Bänder und anderen Indikatoren, mit relativen Charts, mit logarithmischen Charts, mit oder ohne Halteperiode, etc. Aber ein zweiter Blick kann nicht schaden.

**Comment by Ragas13** [comment]
@buchen

Gute Idee :+1:

Ich habe es einmal gegen mein Portfolio laufen lassen. Interessant was man Rückwirkend jetzt besser sieht,  bspw. Haltdauer von 6 Monaten von vor 3 Jahren und Kursverfolgung bis heute...

Zwei kleine Fehler haben sich bei den Marken für den Durchschnittspreis versteckt. Wenn der letzte Trade die Position geschlossen hat, zeichnet er den letzten Datenpunkt nicht.

 Alles andere schaut gut aus.
