### ISSUE TITLE
[Frage] mehrfarbigen Erträge bar chart ?

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#1272]
Erträge bestehen aus Zins und Dividenden. Könnte es Sinn machen Erträge (OPTIONAL) mehrfarbig darzustellen z.B. so ?
![mehrfarbig](https://user-images.githubusercontent.com/17204819/68078714-67f12480-fddc-11e9-8bbf-21282bde080a.png)
So wäre der jeweilige Anteil von Div/Zinsen besser ersichtlich. Nur so ne Idee.

**Comment by buchen** [comment]
Eine gut Idee. Leider unterstützt das die Grafikbibliothek nicht: entweder "stacked" oder nebeneinander. Und in diesem Diagramm kann man ja mehrere Jahre auswählen.
