### ISSUE TITLE
add YTD in Report Interval

### ISSUE THREAD

**Issue by cqst** [buchen/portfolio#1274]
Hi pp !

In Performance view, when we select a report interval (current month, 1 year, 2 years...) could be useful to have YTD.
It is actually possible by adding "last xxx trading days" or selecting "from 01/01/xxxx" but will have to be updated daily in first case, annually in 2cd, anyway it will never be permanent.
A quick YTD shortcut would be simple and helpful I guess :)

What do you think ?
Thx for reading
Cheers

**Comment by buchen** [comment]
Merged. Will be published with the next version (I think roughly mid of November).
