### ISSUE TITLE
Konto/Depot per Kontextmenü im Import Wizard wählen

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#1277]
### User Story

Als Benutzer möchte ich ein Kontextmenü haben, mit dem ich das Konto/Depot/Gegenkonto/Gegendepot für ein importierte Buchung ändern kann
um das Konto/Depot zu übersteuern in den die Buchungen importiert werden.

In dem Kontextmenü sollte ich die Möglichkeit haben,
* entweder ein existierendes Konto
* oder Depot auszuwählen oder das Konto/Depot abzuwählen (damit wird das weiter oben im Dialog globale Konto verwendet).

Das Kontextmenü sollte für mehrere Buchungen möglich sein, d.h. als Benutzer kann ich mehrere Buchungen wählen und das Konto/Depot auf einmal wählen.

### Links

Siehe auch #1267

**Comment by buchen** [comment]
Ich sehe gerade der Feature Request ist schon was älter: #638

**Comment by verybadsoldier** [comment]
> Ich habe dazu #1277 angelegt - hast Du Lust und Zeit das Feature zu bauen?

Ich kann nichts versprechend, da ich keine Erfahrungen mit Eclipse-Applikationen habe. Aber ich werde es mir ansehen und gucken, ob ich in anderen Dialog ähnlichen Code finden kann, an dem mich entlang hangeln kann. Der Dialog selber hat ja bisher wohl noch kein Context-Menü.

**Comment by buchen** [comment]
Es gibt schon ein Kontextmenü - mit "Importieren/Nicht importieren" und ggf. einer Erklärung warum die Buchung einen Fehler hat. Das könnte man erweitern: https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/wizards/datatransfer/ReviewExtractedItemsPage.java#L480

**Comment by verybadsoldier** [comment]
Ahh ok danke. Ich war jetzt gedanklich beim Dialog davor. Wobei Review-Dialog viel passender ist, da es dort ja wirklich um die Umsätze (bzw. um die Zeilen) geht und im Dialog davor ja eher um die Spalten.

**Comment by verybadsoldier** [comment]
Oje, da musstest du ja noch ganz schön nachfeilen :(
