### ISSUE TITLE
dezimal ungenauigkeit

### ISSUE THREAD

**Issue by julian-klode** [buchen/portfolio#1281]
Angehängte CSV, extrahiert aus Mintos report ergibt 2,97, sollte aber 3,03 sein (z.B. SUM in LibreOffice) - also ca. 1,98% Abweichung.

[mintos.zip](https://github.com/buchen/portfolio/files/3854171/mintos.zip)

Vermutlich ist der Datentyp nicht präzise genug.

**Comment by julian-klode** [comment]
Bei Bruchstücken von ETF hatte ich glaube ich auch Ungenauigkeit gesehen, da war es aber am Ende nicht relevant.

**Comment by Ragas13** [comment]
Das Programm ist auf 4 bzw 5 Kommastellen reglementiert  und auch nicht für P2P Kredite ausgerichtet. 

https://forum.portfolio-performance.info/t/zu-wenig-kommastellen-fuer-zinseinkuenfte-bei-p2p-krediten/4660

**Comment by buchen** [comment]
Aktuell werden alle Beträge - also auch der Betrag einer Zinsbuchung - in Cent gespeichert. Weil die Zahl keine Nachkommastellen hat (die man für Cent Bruchteile bräuchte) sind mehr Nachkommastellen eine massive Änderung. Vermutlich würde man alle Rechnungen von ```long``` auf ```BigDecimal``` umstellen und - pro Konto (?) - die Genauigkeit (=Nachkommastellen) festlegen. Dann ist die Frage welche Auswirkungen das auf Speicherverbrauch/Performance hat. Die Zeit habe ich aktuell nicht.

Ansonsten gilt:
* Kurse mit 4 Nachkommastellen
* Stücke mit 6 Nachkommastellen
