### ISSUE TITLE
Add Cash Account /Offset account coloumn 

### ISSUE THREAD

**Issue by vipuldamani** [buchen/portfolio#1285]
Dear Sir.
Can you add 1 more coloumn in below image report? then we easily find which client have open position.
![image](https://user-images.githubusercontent.com/57120750/69213070-10e3a180-0b89-11ea-8e42-aff369b70017.png)
in this report also seen quote, so we consider that is open position then also which account that open position is not seen.
![image](https://user-images.githubusercontent.com/57120750/69902620-eb8b3a80-13b5-11ea-8ec5-20d99654c1cf.png)

if possible add common data series for all calculation.
![image](https://user-images.githubusercontent.com/57120750/69213160-5011f280-0b89-11ea-94c8-ff4ec4394795.png)

 Thanks in advance.

**Comment by buchen** [comment]
Added securities account to list of trades. Available with the next version I publish.

**Comment by vipuldamani** [comment]
Thanks sir.
Have a nice time.
