### ISSUE TITLE
Hilfe bei gson package import

### ISSUE THREAD

**Issue by Galgemaennle** [buchen/portfolio#1286]
Hi,

ich schaffe es nicht mehr PP seit snapshot 0.40 in eclipse zu compilieren. Im wesentlichen seitdem mit json gearbeitet wird. Fehlermeldungen besagen, dass entsprechende Typen nicht aufgelöst werden. Ein validate plugin motzt daher immer gson und bouncycastle an:

> Missing Constraint: Import-Package: com.google.gson; version="0.0.0"
> Missing Constraint: Import-Package: org.bouncycastle; version="0.0.0"

Add required plug-ins schafft keine Abhilfe. Der maven build läuft jedoch einwandfrei durch. Entsprechende Pakete wurden auch von maven über fetch gedownloaded. Leider kommt eclipse damit trotzdem nicht klar. Ich habe darüber hinaus die entsprechenden Pakete vom maven repo heruntergeladen und manuell zu eclipse hinzugefügt.

Jetzt bin ich mit meinen beschränkten java/eclipse Kenntnissen am ende und weiß nicht mehr weiter.

Vlt hilft euch folgender Errorlog beim forcierten Start trotz fehlender Abhängigkeiten weiter:

> !SESSION 2019-11-22 23:21:32.411 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.8.0_151
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
> Framework arguments:  -product name.abuchen.portfolio.bootstrap.product
> Command-line arguments:  -product name.abuchen.portfolio.bootstrap.product -data C:\Users\mail\git\portfolio/../runtime-name.abuchen.portfolio.product -dev file:C:/Users/mail/git/portfolio/.metadata/.plugins/org.eclipse.pde.core/Portfolio Performance Java11/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog
> 
> !ENTRY name.abuchen.portfolio.ui 4 0 2019-11-22 23:21:34.247
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.osgi.framework.BundleException: Could not resolve module: name.abuchen.portfolio.ui [134]
>   Unresolved requirement: Require-Bundle: name.abuchen.portfolio; bundle-version="0.42.2"
>     -> Bundle-SymbolicName: name.abuchen.portfolio; bundle-version="0.42.2.qualifier"
>        name.abuchen.portfolio [132]
>          Unresolved requirement: Import-Package: com.google.gson
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:447)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)
> 
> !ENTRY org.eclipse.osgi 4 0 2019-11-22 23:21:35.393
> !MESSAGE Application error
> !STACK 1
> java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Display
> 	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:147)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
> Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Display cannot be found by org.eclipse.e4.ui.workbench.swt_0.14.300.v20180906-1121
> 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
> 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
> 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
> 	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 14 more

BTW habe es auch mit der anderen launch config ausprobiert.

**Comment by buchen** [comment]
> Leider kommt eclipse damit trotzdem nicht klar.

Es sieht für mich so aus als sei Deine "Target Platform" nicht okay. *Alle* Dependencies müssen in der Target Platform vorhanden sein, sonst kann Eclipse die OSGi Abhängigkeiten nicht auflösen.

Seit ein paar Commits sollte es eigentlich reichen die ```portfolio-target-definition/portfolio-target-definiton.target``` im Target Editor zu öffnen, etwas warten bis die aufgelöst ist, und oben rechts als Target Platform setzen (oder "Reload" sagen).

**Was für eine Fehlermeldung bekommst Du denn wenn die Target Platform öffnest?**

Bei mir sieht das so aus:

<img width="1440" alt="Bildschirmfoto 2019-11-23 um 07 27 58" src="https://user-images.githubusercontent.com/587976/69474548-c9485a00-0dc2-11ea-8fe6-bc37314710ec.png">

**Comment by buchen** [comment]
Hat es geklappt? Wenn nicht, dann Issue noch mal öffnen. Alles andere als die Target Platform macht keinen Sinn.

**Comment by Galgemaennle** [comment]
Ja hat geklappt. Problem: portfolio-target-definition project war nicht im workspace...
