### ISSUE TITLE
Layout-Problem unter Linux

### ISSUE THREAD

**Issue by FrankdeRouw** [buchen/portfolio#1288]
Unter Linux scheint die rechte Spalte nicht skalierbar und rechts ausgerichtet zu sein. Es ist auch möglich, die linke Spalte so weit nach links zu verschieben, dass sie nicht mehr abgerufen werden kann.

Siehe Beispiele und Diskussion im Forum: 

https://forum.portfolio-performance.info/t/move-position-of-quote-column-in-historical-quotes-window/6366

**Comment by buchen** [comment]
> Unter Linux scheint die rechte Spalte nicht skalierbar und rechts ausgerichtet zu sein.

Unter Linux verwendet das SWT Framework die native Tabellen Widgets. Darum ist die ganz rechte Spalte immer mindestens so breit wie der restliche der Tabellen zur Verfügung stehende Platz.

**Meines Wissens kann ich das nicht ändern.** Aber es könnte sein, dass das an einem GTK3 Theme hängt. Allerdings hat eine Google Suche mich nicht wirklich weitergebracht. Wenn Du da bessere Informationen/Links/WIKIs hast, dann schaue ich mir das gerne an.


Die Ausrichtung des Texts in der Spalte ist natürlich frei wählbar - also hier rechts ausgerichtet weil es sich um Zahlenwerte handelt.
