### ISSUE TITLE
Traderepublic Sparplan nicht importierbar

### ISSUE THREAD

**Issue by ackount** [buchen/portfolio#1291]
Der pdf-Import von Traderepublic-Sparplan-Abrechnungen funktioniert nicht.
Anbei der anonyme Export.

PDF Author: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
Vorname Nachname SEITE 1 von 1
Adresse DATUM 18.11.2019
D PLZ Stadt AUSFÜHRUNG ff2f-1254
SPARPLAN NR
DEPOT NR
WERTPAPIERABRECHNUNG SPARPLAN
ÜBERSICHT
Sparplanausführung am 18.11.2019 an der Lang & Schwarz Exchange.
Der Kontrahent der Transaktion ist Lang & Schwarz TradeCenter AG & Co. KG.
POSITION ANZAHL KURS BETRAG
iShsIII-Core MSCI World U.ETF 0,4534 Stk. 55,13 EUR 25,00 EUR
Registered Shs USD (Acc) o.N.
ISIN: IE00B4L5Y983
GESAMT 25,00 EUR
BUCHUNG
VERRECHNUNGSKONTO VALUTA BETRAG
DE88110101008889505855 20.11.2019 -25,00 EUR
iShsIII-Core MSCI World U.ETF Registered Shs USD (Acc) o.N. in Wertpapierrechnung.
Lagerland: Republik Irland
Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.
Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie 
Leistung.
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
ABRE / 2019-11-18 / 18423478 / 0079-d6c3

**Comment by buchen** [comment]
Danke für das Beispiel. Kommt mit der nächsten Version.
