### ISSUE TITLE
ING - Uhrzeit für Kauf aus PDF nicht verfügbar

### ISSUE THREAD

**Issue by gaertnermarkus** [buchen/portfolio#1298]
Bei einem Kauf Dividenten etc wird die Zeit des Kaufes nicht mit erfasst. Das Datum wird gesetzt.

PDF Author: 'ING-DiBa'
PDFBox Version: 1.8.16
-----------------------------------------
ING-DiBa AG · 60628 Frankfurt am Main
Depotinhaber: xxxxx xxxxx
xxxxx Direkt-Depot Nr.: xxxxx
xxxxx xxxxx Datum: 10.12.2019
xxxxx xxxxx Seite: 1 von 1
xxxxx xxxxx
Wertpapierabrechnung Kauf
Ordernummer xxxxx.001
ISIN (WKN) DE000A0TGJ55 (A0TGJ5)
Wertpapierbezeichnung VARTA AG Inhaber-Aktien o.N.
Nominale Stück 5,00
Kurs EUR 114,40
Handelsplatz Direkthandel
Ausführungstag / -zeit 10.12.2019 um 09:51:46 Uhr
Kurswert EUR 572,00
Provision EUR 6,33
Endbetrag zu Ihren Lasten EUR 578,33
Abrechnungs-IBAN xxxxx xxxxx xxxxx xxxxx
Valuta 12.12.2019
Wertpapiere zugunsten Girosammelverwahrung.
Diese Order wurde mit folgendem Limit / -typ erteilt: 115,00 EUR
Bei Fragen besuchen Sie uns einfach unter www.ing.de/wertpapierwissen - da gibt es viele schnelle
Antworten. Oder senden Sie uns eine E-Mail an info@ing.de .
ING-DiBa AG · Theodor-Heuss-Allee 2 · 60486 Frankfurt am Main · Vorsitzender des Aufsichtsrates: Dr. Claus Dieter Hoffmann · Vorstand: Nick Jue (Vorsitzender),
Bernd Geilen (stellv. Vorsitzender), Zeljko Kaurin, Dr. Joachim von Schorlemer, Norman Tambach · Sitz: Frankfurt am Main · AG Frankfurt am Main HRB 7727,
Steuernummer: 047 220 2800 4 · USt-IdNr.: DE 114 103 475 · Internet: www.ing.de · E-Mail: info@ing.de · BIC: INGDDEFFXXX · Mitglied im Einlagensicherungsfonds
34WAAD8011768194_T

**Comment by masterzuso** [comment]
> Bei einem Kauf Dividenten etc wird die Zeit des Kaufes nicht mit erfasst. Das Datum wird gesetzt.
Für Kauf und Verkauf habe ich es angepasst (siehe commit). 
Bei Dividenden gibt es der ING keine Uhrzeit im PDF (habe ich allerdings auch bei anderen Banken bisher noch nie gesehen bei einer Dividendenabrechnung)

**Comment by buchen** [comment]
Super. Vielen Dank @masterzuso
