### ISSUE TITLE
Watchlist Attribut Datum Auswahl zwischen "Datum" und "Tage bis"

### ISSUE THREAD

**Issue by debegr92** [buchen/portfolio#1303]
Es wäre toll, wenn man in der Watchlist eine Spalte anzeigen könnte, wie viele Tage es bis zu einem Datum im Attribut noch sind.
So habe ich das Datum der Quartalszahlen einiger Aktien drin und könnte aber auch noch direkt sehen, wie viele Tage es noch sind. Gezählt werden alle Tage und nicht nur Handelstage (also auch Samstag, Sonntag und Feiertage).
Ich stelle mir das so vor, dass in der Auswahl bei Attributen ein kleiner Pfeil die zwei Möglichkeiten "Datum" und "Tage bis" anzeigt und ich daraus wählen kann.
Ist das Datum bereits vorbei, so steht eine negative Zahl im Feld. Außerdem ist das Feld gelb markiert (nice to have).

**Comment by Ragas13** [comment]
Ich sehe vermutlich den Wald vor lauter Bäumen nicht, aber wozu sollte dies gut sein?

**Comment by buchen** [comment]
Das "Datum" gibt es als konfigurierbares Attribut, was allerdings in der aktuelle Code Basis nicht ganz einfach ist, sind mehrere Spalten (also "Datum" und "Tage bis") auf ein Attribut zu Mappen.

Wenn man ein neues Attribut anlegen würde, dann könnte man vielleicht in der Zelle beides anzeigen: "(1 Tag)  18.12.2019". Allerdings ist es ein neues Attribut. Und zwei Werte in einer Zelle überlädt vielleicht.

Ich schaue mir das mal an - dauert aber ein paar Tage.

**Comment by debegr92** [comment]
Ich würde es praktisch finden, diese Ansicht zu haben, gerne auch als neues Attribut "Datum als Tage" meinetwegen.
In der Watchlist für den Optionshandel könnte man direkt Kandidaten erkennen wo es sich noch lohnt, vor den Earnings einen Trade zu machen.
Hat keine Eile, einfach ein nice to have.

**Comment by buchen** [comment]
> gerne auch als neues Attribut "Datum als Tage" meinetwegen.

Ich habe jetzt mal eine weitere Spalte auf das selbe Attribute gelegt: "Tage dazwischen". Es werden alle Tage gezählt. Negative Zahlen heißt "noch so viele Tage bis zu dem Datum", positive Zahlen heißt "so viele Tage seit diesem Datum".
