### ISSUE TITLE
Git Push failed wegen GitHub Action

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#1310]
[Dieser Commit](https://github.com/buchen/portfolio/commit/5dd1d3954202356c8ad1b2c1b33616b97c540038) scheint Schwierigkeiten zu machen, wenn man lokal einen Git-Branch erstellt hat und diesen in seinen GitHub-Fork von portfolio pushen will.

Diese Fehlermeldung erscheint dann:

     ! [remote rejected]   master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope)
    error: failed to push some refs to 'https://github.com/sebasbaumh/portfolio'

Anscheinend versucht er da etwas mit den GitHub Actions zu machen, obwohl ich da nichts aktiviert habe - trotzdem reagiert er auf die `main.yml`...
Hast Du da eventuell eine Idee dazu?

**Comment by sebasbaumh** [comment]
Löschen der Datei scheint zumindest beim Push zu helfen - aber ich vermute Schwierigkeiten dann bei Pull Requests auf dem Zweig.

**Comment by Ragas13** [comment]
Unter Win zickt bei mir auch der GitHub Desktop, aber über die Kommandozeile via ```GIT PUSH``` scheint es zu gehen 🤔

**Comment by sebasbaumh** [comment]
Komischerweise hat bei mir SourceTree gesponnen, die da eigentlich keine tiefere Integration haben sollten.
In der GitHub UI sieht man es leider überhaupt nicht, da ist der Ordner `.github` versteckt.

**Comment by buchen** [comment]
😒 

Ich habe - versuchsweise - Github Actions aufgesetzt um PP bei jedem Push zu bauen.

Anscheinend braucht man Extra-Berechtigungen um ein Github "workflow file" in sein Repository zu pushen. Und weil Euer OAuth client - also die Credentials die Ihr auf der Github Seite geholt habt - diesen Scope ("workflow") nicht enthalten. (Über Settings -> Developer Settings -> Personal Access Token).

Ich finde nicht viel dazu auf Google - aber eine Change zum [Github Desktop](refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope) die den Benutzer dazu informiert und auffordert neue Credentials zu holen.


Die Build direkt im Repository zu definieren ist ja ganz attraktiv, aber ob das wegen der Berechtigungen zu praktisch ist? Wieder rauswerfen?

**Comment by sebasbaumh** [comment]
Die Idee mit dem automatischen Build ist schon gut - es ist nur komisch, dass es dann bei den Forks quer schiesst.
Zu mal ich mir noch nicht erklären kann, warum das bei mir in [SourceTree](https://www.sourcetreeapp.com/) kommt, aber bei @Ragas13 mit git auf der Kommandozeile nicht. Wobei ich bei ner kurzen Recherche auch das als Tipp gefunden habe, git direkt auf der Kommandozeile zu verwenden.
Der Workflow sollte ja eigentlich immer laufen und direkt von GitHub aus, egal welchen Client man benutzt.

Nur muss das ja quasi immer bei Forks quer schiessen, da dort kaum jemand die Actions aufsetzen wird (macht ja auch eher wenig Sinn). Ich habe zwar einen eigenen Branch, wo sich das einfach anpassen lässt (direkt auf GitHub geht es nicht so einfach, da der Ordner `.github` ausgeblendet wird). Aber im Hauptbranch für Pull Requests wollte ich Deinem Branch so nah wie möglich folgen @buchen .

**Comment by buchen** [comment]
> Zu mal ich mir noch nicht erklären kann, warum das bei mir in SourceTree kommt, aber bei @Ragas13 mit git auf der Kommandozeile nicht.

Ich vermute die Benutzer haben unterschiedliche Rechte. Man braucht den "workflow" scope um einen Workflow in "sein" Repository zu pushen (und ein fork ist ein eigenes Repository). Ich konnte übrigens mein "SourceTree" token aktualisieren und den "workflow" scope hinzufügen.

> Nur muss das ja quasi immer bei Forks quer schiessen, da dort kaum jemand die Actions aufsetzen wird (macht ja auch eher wenig Sinn).

Bei PR #1311 ist der Workflow in dem "remote" Repository drin, aber ist anscheinend nicht gelaufen. Zumindest in seinem Repository ist keine Github Action zu sehen. So ganz verstehe ich das noch nicht.

**Comment by Ragas13** [comment]
Nur der Vollständigkeit halber, dass war die Fehlermeldung die ich via **GitHub Desktop** erhalten habe;

```
 ! [remote rejected]   master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/Ragas13/portfolio.git'
```

Warum es über die Apps nicht funktioniert, I don't know. Über die Kommandozeile bzw. das neu aufsetzen des Repos hat die Fehlermeldung verschwinden lassen.

**Comment by masterzuso** [comment]
> Bei PR #1311 ist der Workflow in dem "remote" Repository drin, aber ist anscheinend nicht gelaufen. Zumindest in seinem Repository ist keine Github Action zu sehen. So ganz verstehe ich das noch nicht.

Ich habe es bei mir jetzt einmal ausprobiert. Die Actions müssen im Fork nochmal extra aktiviert werden. Wenn das der Fall ist, läuft der Build beim Push auch durch.

**Comment by sebasbaumh** [comment]
> > Zu mal ich mir noch nicht erklären kann, warum das bei mir in SourceTree kommt, aber bei @Ragas13 mit git auf der Kommandozeile nicht.
> 
> Ich vermute die Benutzer haben unterschiedliche Rechte. Man braucht den "workflow" scope um einen Workflow in "sein" Repository zu pushen (und ein fork ist ein eigenes Repository). Ich konnte übrigens mein "SourceTree" token aktualisieren und den "workflow" scope hinzufügen.

Wie genau hast Du denn das gemacht @buchen ?
Ich bin bei https://github.com/settings/applications unter "Authorized OAuth Apps", kann dort aber für "SourcetreeForWindows" nur "Revoke access" ausführen und die Permissions nicht ändern.

**Comment by sebasbaumh** [comment]
Wenn man bei SourceTree "Push all tags" beim Push deaktiviert, klappt es auch - sehr seltsam.
Anscheinend entspricht das `git push --tags` auf der Kommandozeile.

**Comment by buchen** [comment]
> Wie genau hast Du denn das gemacht @buchen ?
> Ich bin bei https://github.com/settings/applications unter "Authorized OAuth Apps", kann dort aber für "SourcetreeForWindows" nur "Revoke access" ausführen und die Permissions nicht ändern.

Ich habe für SourceTree ein **Personal Access Token** angelegt. Und da ist der Name des Tokens (bei mir "Source Tree") ein Link. Wenn ich den anklicke, dann kann ich die Access Permissions von dem Token editieren.

**Comment by sebasbaumh** [comment]
Das wäre dann auch die Lösung @buchen :
* Man erstellt sich unter https://github.com/settings/tokens ein Personal Access Token für SourceTree
* Dabei aktiviert man das Recht `workflow`
* In SourceTree fügt man unter `Authentication`  -> `Add` einen Eintrag für SourceTree hinzu
    * Host: GitHub
    * Preferred Protocol: HTTPS
    * Authentication: Basic
    * Username: GitHub-Username
* Dann `Refresh Password` und dort das generierte Personal Access Token einfügen
 
@Ragas13 wenn das für Dich auch funktioniert, könnten wir dieses Ticket hier schließen.
Bei mir hat das funktioniert.

**Comment by Ragas13** [comment]
@sebasbaumh 
Ich glaube du kannst das Ticket schließen, es scheint auch bei mir zu funktionieren.

Euch beiden einen guten Rutsch und Gruß
