### ISSUE TITLE
Optionsscheine kein Automatischer kurs Download

### ISSUE THREAD

**Issue by kingfraenky** [buchen/portfolio#1315]
Hallo nochmal

Man kann bei Optionsscheinen kein Automatischen Kursdownload einstellen da anscheinend hier nur auf das Symbol zurückgegriffen wird. Aber wenn ich über Kurse -> HTML-Tabelle importieren gehe zeigt er den richtigen Link zu z.B. Onvista korrekt an und er importiert den auch alles korekt. 
Es währe schön wenn du das beim Automatischen Kursdownload mit einbinden könntest.

Danke Schön

**Comment by debegr92** [comment]
Kannst du dazu bitte ein Beispiel machen? Vielleicht sogar ein Portfolio mit anhängen?

**Comment by kingfraenky** [comment]
![Unbenannt](https://user-images.githubusercontent.com/57058425/71479125-76175c00-27f3-11ea-8fdc-28ecca6842b0.PNG)
![Anmerkung 2019-12-26 151721 PNG](https://user-images.githubusercontent.com/57058425/71479131-7adc1000-27f3-11ea-900c-b5973619812a.jpg)
![Anmerkung 2019-12-26 151806](https://user-images.githubusercontent.com/57058425/71479134-7d3e6a00-27f3-11ea-8c46-424cbc0b37b2.jpg)
![Anmerkung 2019-12-26 151912](https://user-images.githubusercontent.com/57058425/71479137-7f082d80-27f3-11ea-8506-60d460612453.jpg)
so geht es halt

**Comment by kingfraenky** [comment]
Und bei Online Aktualisierung konfigurieren gehts nicht, da er hier meckert das der Börsenplatz fehlt aber man auch keinen auswählen kann.

**Comment by Ragas13** [comment]
Und die URL als Kurslieferant funktioniert nicht weil...

Das die HTML Abfrage nicht automatisiert werden kann sollte nachvollziehbar sein, es ist statischer Content.

**Comment by oduudo** [comment]
Hallo @kingfraenky!
Ich nutze Ariva als Kurslieferant für historische Kurse:
historische Kurse: Tabelle auf einer Website: URL:
`https://www.ariva.de/{ISIN}/historische_kurse?boerse_id=1&month={DATE:yyyy-MM-32}&currency=EUR&clean_split=1&clean_payout=0&clean_bezug=1`
Wenn die ISIN gepflegt ist sollte das historische Kurse liefern.
Hab das mal im PP-Forum gefunden.
Vielleicht hilft Dir das weiter??

**Comment by buchen** [comment]
Der automatische Download "Tabelle auf einer Webseite" und der Dialog mit "copy & paste" verwenden genau die gleiche Logik. Ich vermute Du hast als Kurslieferant noch "Yahoo" ausgewählt.
