### ISSUE TITLE
Sutorbank / Fairriester Gebuehrentilgung in PDF Import beachten

### ISSUE THREAD

**Issue by tenjaa** [buchen/portfolio#1324]
Hallo,
der Importer der Sutorbank fuegt aktuell nur Kaeufe hinzu. Die Gebuehrentilgung fehlt leider komplett.
Spricht was dagegen, die Verkaeufe zur Gebuehrentilgung als Pull Request hinzuzufuegen?
Dann wuerde ich das gerne machen :)

**Comment by Ragas13** [comment]
@tenjaa 
Der PDF Import ist leider immer nur so gut wie er mittels vorliegenden Beispielen programmiert werden kann. Wenn du Beispiele vorliegen hast ist das bereits hilfreich, Spitze wenn du bei der Programmierung mithelfen kannst :+1:

**Comment by tenjaa** [comment]
@Ragas13 Cool ich bin schon dabei :)
Meine Idee war, dass der Verkauf dann direkt in der Hoehe Gebuehren hat zu welchem Preis er auch verkauft wird.
Setze ich jetzt aber den Amount auf z.B. 4 EUR in der Transaction und fuege noch eine Unit vom Typ FEE hinzu in Hoehe von 4 EUR, sieht das im Test gut aus, aber wenn ich dann testweise das Dokument importiere, habe ich durch den Verkauf ingesamt 8 EUR erloest. 4 EUR Gewinn, 4 EUR Fee.
Setzte ich den Amount aber auf 0 EUR, gibt es einen Fehler dass die FEE hoeher ist als der Amount.

Gibt es irgendwo eine Uebersicht wie das am Ende zusammengerechnet wird oder sowas?

**Comment by Ragas13** [comment]
@tenjaa 
Das Problem ist das du eine reine Gebühr als Verkauf buchen möchtest, sprich du würdest x Stück für 0 Euro verkaufen und zahlst zusätzlich 4 Euro als Gebühr. 

Bei Onvista @ https://github.com/buchen/portfolio/blob/f866c0a3658aaea7b4d6f4fe9824f8bd02858b1d/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/OnvistaPDFExtractor.java#L934-L973 findest du eine reine Buchung von Gebühren.

VG
Marco

**Comment by tenjaa** [comment]
Bei fairriester sieht das ganze etwa so aus:
```
08.07.2019 05.07.2019 0,98 Gebührentilgung iShares Core MSCI Emerging Markets 1,1260 28,48 US$ -0,0387
08.07.2019 05.07.2019 0,98 Verwaltungsgebühr/Vertriebskosten 1. Hj.2019
```
Also in diesem Beispiel jetzt 98ct Gebuehren.

Ich fuehre das bisher ohne Verrechnungskonto, deshalb war meine Idee Verkauf und Gebuehr in eine Transaction zu packen.
Aber dann mache ich daraus zwei Buchungen.
Einmal ganz normal den Verkauf und dann separat die Gebuehren.
