### ISSUE TITLE
IntelliJ Support

### ISSUE THREAD

**Issue by tenjaa** [buchen/portfolio#1326]
Hey,
hat jemand schonmal erfolgreich das Projekt in IntelliJ importiert um daran zu arbeiten?

**Comment by Ragas13** [comment]
Vermutlich wird es auch nicht möglich sein, PP verwendet das Framework von Eclipse damit es ausführbar wird.

**Comment by tenjaa** [comment]
Mir würde es schon viel helfen, wenn alleine die unit Tests und Code completion funktionieren. 
Zum richtigen starten kann ich gerne kurz auf Eclipse wechseln. 
Also falls jemand noch Ideen hat bin ich dankbar für jeden Hinweis :)

**Comment by lenucksi** [comment]
PP besteht wie @Ragas13 schon sagte aus OSGi Plugins/Bundles für die Equinox OSGi Runtime, in bekanntester Darreichung als Eclipse bekannt. 
Grundsätzlich scheint IntelliJ auch mit OSGi umgehen zu können. Wie weit das dann Spaß macht sei dahin gestellt.

Das Internet sagte dieses hier dazu:
- https://stackoverflow.com/questions/50406413/how-to-setup-equinox-osgi-framework-in-intellij-idea-2018-1-on-mac-os
- https://de.slideshare.net/marcusharringer/develop-and-build-osgi-bundles-without-pain-using-intellij-and-gradle
- JetBrains hat noch einiges an Dokumentationsseiten zu ihren OSGi Features, da gabs aber keine abschließend tolle Einsprungseite für. 

Viel Spaß beim Ausprobieren und lass uns Deine Ergebnisse wissen.

**Comment by tenjaa** [comment]
Danke fuer die Links aber auch damit habe ich wenig Erfolg..
Ein [Intellij Keymapping](https://marketplace.eclipse.org/content/intellij-idea-keymap-eclipse) sollte fuer den Anfang helfen.

Habt ihr mal ueberlegt das ohne OSGi zu machen?
Es waere vermutlich unglaublich viel Arbeit und das Frontend funktioniert ohne gar nicht, korrekt?

**Comment by Ragas13** [comment]
@tenjaa 
Unterstützt IntelliJ nicht OSGI?
https://www.jetbrains.com/help/idea/osgi.html

**Comment by SimonScholz** [comment]
IntelliJ kennt, soweit ich weiß, auch nicht die Auflösung der Target Platform, die genutzt wird um die Abhängigkeiten des Projektes aufzulösen. 
Es gibt in der Eclipse Community aber bereits Bestrebungen einen build rein via maven dependencies zu ermöglichen. 
Neben diesem Problem fehlt auch das ganze Tooling, welches Eclipse PDE (Plugin Development Environment) mitliefert. D.h. die ganzen Editoren und Wizards für die Rich Client Entwicklung fehlen.
Und einige Dinge, wie das application model, will man einfach nicht via plain XML Editor anpassen.
@tenjaa Was lässt dich so an IntelliJ festhalten?

**Comment by tenjaa** [comment]
Dass ich jeden Tag damit arbeite und einfach dran gewoehnt bin ist der Hauptgrund.
An Features vermisse ich bisher hauptsaechlich das search everywhere, einen Shortcut um direkt zur Testdatei zu springen und die Code Analyse markiert zum Beispiel nichtmal Stellen wo man den Diamand Operator fuer Generics nutzen kann.
Sonst ist es ok, man kann schon mit was machen :)

Ein reiner Maven Build waere natuerlich top!

**Comment by buchen** [comment]
> Ein reiner Maven Build waere natuerlich top!

Na ja, ```mvn clean verify``` baut das schon von der Kommandozeile. Ich weiß nicht ob das auch in IntelliJ funktioniert, weil *Tycho* eine Build Extension zu Maven ist. Und ich vermute das geht nicht wirklich inkrementel.

Ich bin auch Fan von IntelliJ. Und vor ein paar Jahren habe ich es auch mal probiert ob ich PP aus IntelliJ raus entwickeln kann. Das macht aber für die ganzen UI Teile leider keinen Sinn. Ich mach das Ticket mal wieder zu 😭
