### ISSUE TITLE
Breite der Spalten in der Performanceansicht anpassen

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#1335]
Die Breite der Spalten auf dem Dashboard in der Performanceansicht wird momentan automatisch eingestellt.
Dabei wird sie gleich verteilt (bei 3 Spalten bekommt jede ein Drittel des zur Verfügung stehenden Platzes).
Ich würde die Breite gerne anpassen können, damit ich zum Beispiel die Kennzahlen/Risikokennzahlen in zwei schmalen Spalten anordnen kann und dann mehr Platz für die Jahresrenditen/Monatsrenditen und weitere Diagramme.
Eventuell gänge das auch automatisch, zumindest für die Textspalten.

**Comment by buchen** [comment]
Die Idee finde ich gut. Ich überlege schon länger wie ich das mache so dass trotzdem das Dashboard auf verschiedenen Bildschirmgrössen funktioniert. Ich frage mich ob man z.B. eine Spalte "verdoppeln" kann (dann speichere ich mir Gewichte von z.B. 1-1-2). Mit der Maus jede Spaltenbreite individuell anpassen erscheint mir a) kompliziert zu programmieren und b) dann schwer auf verschieden Bildschirmgrössen anzupassen.

**Comment by sebasbaumh** [comment]
Da hast Du recht - per Maus ziehen wird zu kompliziert.
Ich denke, es reicht, wenn sich einfach ein Control über mehrere Spalten erstrecken kann.
Bei mir sind die Textcontrols recht schmal und die Charts/Ertragsmatrix eher breit.
Da würde es helfen, wenn man die Charts über zwei Spalten laufen lassen kann.
Ansonsten finde ich die automatische Anpassung an den Bildschirm gut so wie sie ist 👍
