### ISSUE TITLE
Erträge / Dividienden je Konto für Steuerfreibetrag

### ISSUE THREAD

**Issue by Ang3er** [buchen/portfolio#1336]
Hallo Zusammen,

ich versuche aktuell für die Steueroptimierung die Erträge / Dividenden je Konto als Analyse aufzubauen. Leider kann ich die Dividenden nur auf die Aktie und die Zinsen auf das Konto mappen. Bei mir ist es so dass zum Beispiel eine Aktie in zwei Depots, ergo zwei Referenzkonten gekauft wurde. Bei Dividenden werden diese auf zwei Konten Ausgeschüttet.
Ist es aktuell möglich die Dividenden + Zinsen = Erträge gesammelt je Konto zu analysieren?

Danke vorab

Benutze die aktuelle Version

**Comment by markokocic** [comment]
Was du machen kannst ist:

- du merkst Kurserfolge
- du buchst ein Verkauf mit heutigem Datum und heutigen Kurs
- du merkst den neuen Kurserfolg und rechnest den Unterschied
- der Unterschied ist dein realisierter Ertrag

Aber, wenn du Depotüberträge getätigt hast, besser warte bis #1292 gefixt wird, da die Ertragsberechnung in diesem Fall falsch berechnet wird.

**Comment by Ang3er** [comment]
Found it!
![image](https://user-images.githubusercontent.com/12126245/71905059-ac47ca80-3167-11ea-8f4b-517d79b0a130.png)
 Und dann den Filter auf ein Jahr selektieren
