### ISSUE TITLE
PDF Import erkennt keine schon importierten Buchungen die vom Typ "Einliferung" sind

### ISSUE THREAD

**Issue by fmms** [buchen/portfolio#1340]
Hi,

da ich mein Verrechnungskonto nicht mit Portfolio Performance manage, habe ich von Kauf auf Einlieferung umgestellt. 

Jetzt habe ich allerdings das Problem, dass der PDF Import nicht mehr erkennt, dass Belege bereits importiert sind und damit Duplikate erstellt und damit die Wertpapierbestände falsch sind.

![grafik](https://user-images.githubusercontent.com/908734/71939767-0d958b00-31b4-11ea-91e0-25e51b7568d7.png)

Danke

**Comment by buchen** [comment]
Das ist natürlich nervig. Du kannst manuell natürlich per Kontextmenü sagen "nicht importieren", dass ist aber Arbeit.

Ich erweitere die Logik, so dass "Einlieferung" und "Kauf" als identisch erkannt werden (wenn die anderen Parameter stimmen).
