### ISSUE TITLE
0.43.1: Reports -> Securities shows 2 different IRRs

### ISSUE THREAD

**Issue by ronnykrijt** [buchen/portfolio#1342]
When looking at a security in the Reports -> Securities, 2 different IRR values are showing. The IRR on the top-tab is different then the value in the bottom view (on the trades overview)

**Comment by buchen** [comment]
Fair point.

The IRR in the upper table is *always* in relation to the reporting period selected in the upper right corner. If you select *2 years* then the IRR is calculated for those two years. If bought the security before the start of the reporting period, then the valuation at the start of the reporting period is taken as the investment. (And, of course, IRR is an annualized indicator).

The IRR in the lower table, in particular the "trades" tables, is calculated for the full trade. It starts with the purchase, it ends either with the closing transaction (sale) or the current valuation. Transactions are split if needed (e.g. if you buy 100, but then sell only 50, you have 2 trades: one closed, and one open). Dividends are not (yet) included (I hope to add this in the future).

If you make the reporting period long enough to include the purchase, and if you have no dividend payments on the security, then the IRR numbers should be the same.
