### ISSUE TITLE
PDF import for Scalable / Baaderbank does not work

### ISSUE THREAD

**Issue by xemwebe** [buchen/portfolio#1343]
Probably due to a format change of the pdf documents, import of Scalable / Baaderbank transactions does not work anymore. I have fixed the code already and added a new test file for the new format, which you can find [here](https://github.com/xemwebe/portfolio).

Unfortunately, the fix breaks the another test case, therefore, I need some advice before I can send a pull request. Let me explain the issue:
Previously, the block identifier for document type "Buy" was "Scalable Capital Vermögensverw. GmbH". This does not work with the new PDF format, where "Scalable Capital" and "Vermögensverwaltung GmbH" comes now on two lines, intermixed with the name and address of the client. Therefore, I changed the block identifier to "Werpapierabrechnung: Kauf" which makes also more sense anyway and is in line withe the document type identifier. With this change 3 of the now 4 test cases pass the test. The test case that fails supports a two page format, where the string "Wertpapierabrechnung: Kauf" is repeated on page two. Currently, reading the second block will fail, since it does not contain any relevant information regarding a buy transaction.

What's the best way to deal with this problem? Is there any way to suppress parsing the second page? 

A simple solution would be to just to add another PDF extractor, but since it differs by only one string from the original one this seems not to be the best way to solve this issue.

**Comment by buchen** [comment]
Hi @xemwebe,

> What's the best way to deal with this problem? Is there any way to suppress parsing the second page?

Whenever I ran into this problem in the past, I actually found another string that I could use as block identifier... maybe this time we ran out of luck. 😄 

If I am not mistaken, the blocks are identified and then parsed in this code block:

https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/PDFParser.java#L135-L141

One solution could be to catch IlegalArgumentExceptions from transaction.parse and ignore the exception if it is *not* the first block. That would mean that at least one transaction was successfully found (e.g. one block was parsed) which makes it unlikely that another parse would find more (other) transactions.

If that does not work, feel free to push the change as PR (even if the build will fail) as it is easier for me to look at it as PR.

Sorry for not replying earlier.

Andreas.

**Comment by xemwebe** [comment]
Seems that luck is still with us: After understanding the the matter a bit better, I found at least one string that serves as an appropriate identifier. All test four test cases pass the test now (including the new one) and I was able to read the new pdf format correctly. I commited and pushed my changes and made a pull request.

**Comment by buchen** [comment]
Danke!
