### ISSUE TITLE
Manche Dividendenzahlungen von Flatex führen zu einer ungültigen Buchungskomponente

### ISSUE THREAD

**Issue by AlphaCentauri1983** [buchen/portfolio#1348]
Wie in den Forumsbeitrag von Erdoes (https://forum.portfolio-performance.info/t/dividenden-import-wechselkurs-des-nettowertes-fehlt-flatex/1366/22) unter Punkt 2 aufgezeigt, kommt es bei Import von Dividenden PDFs von ausländischen Aktien zum folgendem Fehler:

image
![image](https://user-images.githubusercontent.com/59516954/72210548-826f0a80-34bd-11ea-8033-defb7c5f5323.png)

Dies liegt an folgender Codestelle:

![image](https://user-images.githubusercontent.com/59516954/72210560-9581da80-34bd-11ea-8fe4-781715164ffa.png)

Passt man die Grenzen von 0.001 und -0.001 etwas an (auf 0.005 und -0.005) liefen die Dividendenbuchungen ohne Probleme durch.

**Comment by buchen** [comment]
Ja, kleine Beträge können Rundungsfehler enthalten die dann über die Grenze hinweggehen. Im Prinzip kann man die Grenze natürlich weiter aufweichen.

Ich frage mich aber: kommen beide Werte - sowohl EUR als auch USD aus dem Flatex Dokument selber? Oder berechnet der Importer einen der Werte (und rundet dann nicht gut genug)?

Denn
> 3,29 * 0,887 = 2,91823  --> grundet 2,92
Vielleicht rundet der Importer hier nicht sondern schneidet auf 2,91 ab?

Oder
> 2,91 / 0,887 = 3,2807215333 --> gerundet 3,28

**Comment by AlphaCentauri1983** [comment]
@buchen 
Soweit ich das verstehe, wird bei Flatex die Quellensteuer von Bruttodividende erst in USD subtrahiert und dann in EUR konvertiert. Es wird alles gerundet und nicht abgeschnitten.

Der Importer scheint tatsächlich die Werte abzuschneiden und nicht zu runden. Hier ein Beispiel aus meinen Daten:

![image](https://user-images.githubusercontent.com/59516954/72280500-c20e3180-3638-11ea-92f6-656a5e3fc682.png)

Gerundet auf Euro sollte die Steuer folgenden Wert ergeben:
`3,04/1,3767=2,208179 also gerundet 2,21`

Der tatsächliche Wert in PP ist jedoch 2,20:

![image](https://user-images.githubusercontent.com/59516954/72280750-57112a80-3639-11ea-853e-334cbd2ae533.png)

Das eigentlich Problem ist die Methode `longValue()`. Sie rundet nicht sondern schneidet ab.

![image](https://user-images.githubusercontent.com/59516954/72283962-2680bf00-3640-11ea-9a55-d9c207bc8695.png)

Man könnte den Scale von 10 auf 0 setzen. Auf jeden Fall muss man zuerst runden und dann in long konvertieren.

**Comment by buchen** [comment]
> Das eigentlich Problem ist die Methode longValue(). Sie rundet nicht sondern schneidet ab.

ja, sehe ich auch so. Ein #setScale sollte besser sein.

Ich habe gerade den Code entsprechend mal angepasst, aber kein Testfall ist angeschlagen. Könntest Du mir die obige Datei über *Datei -> Importieren -> Debug: PDF in Text umwandeln...* als Testfall zur Verfügung stellen? Oder noch besser: einen PR mit der Change machen?
```java
BigDecimal taxesFxInEUR = BigDecimal.valueOf(mTaxesFx.getAmount()).divide(exchangeRate,
                                                10, RoundingMode.HALF_DOWN).setScale(0, RoundingMode.HALF_DOWN);
```

**Comment by AlphaCentauri1983** [comment]
Ist drin. War tatsächlich auch schon so bei anderen Importern implementiert.
