### ISSUE TITLE
Fehler beim importieren von ING DIBA Ertragsabrechnungen

### ISSUE THREAD

**Issue by k1l1** [buchen/portfolio#1352]
Leider kommt es seit diesem Jahr bei importen von ING DIBA Ertragsabrechnungen zu einem Fehler:

`Nur 0 von 1 Pattern erkannt:`

Ich würde mich sehr über eine anpassung freuen, habe dieses feature sehr zu schätzen gelernt.

Die ertragsabrechnungen sehen ca. so aus 

> 
> ING-DiBa AG · 60628 Frankfurt am Main
> Depotinhaber: Vorname Name
> Direkt-Depot Nr.: 1234567890
> Datum: 11.01.2020
> Seite: 1 von 2
> Ertragsgutschrift
> ISIN (WKN)
> Wertpapierbezeichnung LU0292106167 (DBX1LC)
> Xtr.DBLCI Commod.Opt.Yld Swap
> Inhaber-Anteile 1C EUR Hgd oN
> Nominale 1.447,00 Stück
> Vorabpauschale per Stück 0,05848533 EUR
> Ex-Tag 02.01.2020
> Zahltag 02.01.2020
> 02.01.2020 Kapitalertragsteuer 24,51% EUR 20,74
> Kirchensteuer 8,00 % EUR 1,65
> Solidaritätszuschlag 5,50% EUR 1,14
> Gesamtbetrag zu Ihren Lasten EUR - 23,53
> Abrechnungs-IBAN DEXXXXXXXXXXXXXXXXXXX
> Valuta 02.01.2020
> 
> Jahressteuerbescheinigung folgt.
> Weitere steuerliche Informationen entnehmen Sie bitte der Rückseite.
> Depotinhaber: Vorname Name
> Direkt-Depot Nr.: 1234567890
> Datum: 11.01.2020
> Seite: Seite: 2 von 2
> 
> ISIN (WKN) LU0292106167 (DBX1LC)
> Vorabpauschale gem. § 18 InvStG 84,63 EUR
> Vorabpauschale nach Teilfreistellung 84,63 EUR
> 
> KapSt-pflichtiger Kapitalertrag 84,63 EUR
> 
> Bemessungsgrundlage für KapSt vor QuSt 84,63 EUR
> Bemessungsgrundlage für KapSt 84,63 EUR
> 
> Sparer-Pauschbetrag vor Ertrag 0,00 EUR
> Sparer-Pauschbetrag nach Ertrag 0,00 EUR
> 
> Wenn Sie Anteile unter dem Jahr erworben haben, fällt die Vorabpauschale nur für die seit
> Kauf angefangenen Monate an. Jeder vorherige Monate mindert die Vorabpauschale damit
> um ein Zwölftel.

**Comment by masterzuso** [comment]
Könntest du das PDF nochmal bitte in der Debug-Version hier posten.
Datei -> Importieren -> Debug: Text aus PDF extrahieren
Das Format entspricht dann dem, was wirklich eingelesen wird. 
Copy & Paste vom PDF weicht davon leider ab.

Problem bei dir ist, dass die Vorabpauschale noch nicht erkannt wird.

**Comment by k1l1** [comment]
```
PDF Author: 'ING-DiBa'
PDFBox Version: 1.8.16
-----------------------------------------
ING-DiBa AG · 60628 Frankfurt am Main
Depotinhaber: Vorname Nachname
Herrn Direkt-Depot Nr.: XXXXXXXX
Vorname Nachname Datum: 14.01.2020
XXX-Strasse 1 Seite: 1 von 2
1111 Stadt
Ertragsgutschrift
ISIN (WKN) IE00B53QG562 (A0YEDX)
Wertpapierbezeichnung iShs VII-Core MSCI EMU UCI.ETF
Reg. Shares EUR (Acc) o.N.
Nominale 304,00 Stück
Vorabpauschale per Stück 0,35979288 EUR
Vorabpauschale mit Teilfreist. per St. 0,25185501 EUR
Ex-Tag 02.01.2020
Zahltag 02.01.2020
Kapitalertragsteuer 24,51% EUR 17,65
Kirchensteuer 8,00 % EUR 1,41
Solidaritätszuschlag 5,50% EUR 0,97
Gesamtbetrag zu Ihren Lasten EUR - 20,03
Abrechnungs-IBAN DEXXXXXXXXXXXXXXXX
Valuta 02.01.2020
Jahressteuerbescheinigung folgt.
Weitere steuerliche Informationen entnehmen Sie bitte der Rückseite.
ING-DiBa AG · Theodor-Heuss-Allee 2 · 60486 Frankfurt am Main · Vorsitzender des Aufsichtsrates: Dr. Claus Dieter Hoffmann · Vorstand: Nick Jue (Vorsitzender),
Bernd Geilen (stellv. Vorsitzender), Zeljko Kaurin, Dr. Joachim von Schorlemer, Norman Tambach · Sitz: Frankfurt am Main · AG Frankfurt am Main HRB 7727,
Steuernummer: 047 220 2800 4 · USt-IdNr.: DE 114 103 475 · Internet: www.ing.de · E-Mail: info@ing.de · BIC: INGDDEFFXXX · Mitglied im Einlagensicherungsfonds
Depotinhaber: Vorname Nachname
Direkt-Depot Nr.: XXXXXXXX
Datum: 14.01.2020
Seite: 2 von 2
ISIN (WKN) IE00B53QG562 (A0YEDX)
Vorabpauschale gem. § 18 InvStG 102,90 EUR
abzgl. Teilfreistellungsbetrag 30,00 % 30,87 EUR
Vorabpauschale nach Teilfreistellung 72,03 EUR
KapSt-pflichtiger Kapitalertrag 72,03 EUR
Bemessungsgrundlage für KapSt vor QuSt 72,03 EUR
Bemessungsgrundlage für KapSt 72,03 EUR
Sparer-Pauschbetrag vor Ertrag 0,00 EUR
Sparer-Pauschbetrag nach Ertrag 0,00 EUR
Wenn Sie Anteile unter dem Jahr erworben haben, fällt die Vorabpauschale nur für die seit
Kauf angefangenen Monate an. Jeder vorherige Monate mindert die Vorabpauschale damit
um ein Zwölftel.
Bei Fragen besuchen Sie uns einfach unter www.ing.de/wertpapierwissen - da gibt es viele schnelle
Antworten. Oder senden Sie uns eine E-Mail an info@ing.de .

```

**Comment by buchen** [comment]
Fixed mit 0eb12c28bb7e73d6750e4823dc8eb4ad151caa6a
