### ISSUE TITLE
Missing exception hendeling (Illegal transaction unit)

### ISSUE THREAD

**Issue by PhKP** [buchen/portfolio#1366]
Hey

Thanks for making this program! I think it's the best of it's kind that i have found so far.

In file mentioned below there should be a better exception handling:
 name.abuchen.portfolio/src/name/abuchen/portfolio/model/Transaction.jav

I am getting this error and i am not able to find out how to fix the issue in the data:

<img width="895" alt="Skærmbillede 2020-01-23 kl  17 49 17" src="https://user-images.githubusercontent.com/11960377/73005119-b07f1380-3e08-11ea-922d-e8c083c0d339.png">

I will not attach detailed error log since it could contain data about my portfolio.

I hope you will make a better error handling and release a new version so i kan get a propper error message and thereby fix the issue it that input data.

Version: 0.44.0 (jan. 2020)
Platform: macosx, x86_64
Java: 11.0.4+11-LTS, Azul Systems, Inc.

Best regards PhKP

**Comment by buchen** [comment]
Hi @PhKP,

thanks for the stack trace. Helps me to find the problem.

In your case, it looks like:
* you have assigned a security to multiple categories
* you have picked that taxonomy as the top-level grouping in the statement of assets view
* when splitting the position, the rounding errors become too big (which can easily happen on small amounts) and I am aborting the calculation

I'll have to look at it again.

If you happen to know which security you might have assigned to multiple categories, you could try to undo that assignment.

**Comment by buchen** [comment]
Fixed with the next version

**Comment by PhKP** [comment]
Thanks for fixing it.

I also played around with the taxonomies and i managed to get the exception to go away. Thanks.

Looking forward to try the new release.
