### ISSUE TITLE
PDF-Import für gratisbroker

### ISSUE THREAD

**Issue by gsw17** [buchen/portfolio#1367]
[gratisbroker-kauf.txt](https://github.com/buchen/portfolio/files/4107128/gratisbroker-kauf.txt)

**Comment by 5TDg9** [comment]
Bitte auch den Verkauf. Ist ein toller Broker ohne Transaktionskosten, dementsprechend auch häufige Trades ;)

![2020-01-14_Wertpapierabrechnung_Verkauf_DE000A0TGJ55_01](https://user-images.githubusercontent.com/1994787/74093737-74b99e80-4ad6-11ea-93c6-e610cf71d0eb.png)
![2020-01-14_Wertpapierabrechnung_Verkauf_DE000A0TGJ55_02](https://user-images.githubusercontent.com/1994787/74093738-75523500-4ad6-11ea-896f-951304a178c9.png)
[2020-01-14_Wertpapierabrechnung_Verkauf_DE000A0TGJ55.pdf.txt](https://github.com/buchen/portfolio/files/4175736/2020-01-14_Wertpapierabrechnung_Verkauf_DE000A0TGJ55.pdf.txt)

**Comment by buchen** [comment]
Der Name der Originaldatei ist egal.

Die Verkaufsbuchung sollte damit auch tun.

**Comment by gsw17** [comment]
Dividendenabrechnung
[gratis-div.txt](https://github.com/buchen/portfolio/files/4230333/gratis-div.txt)

**Comment by gsw17** [comment]
Dividendenabrechnung wurde geändert

[div.txt](https://github.com/buchen/portfolio/files/4374179/div.txt)
