### ISSUE TITLE
Onvista Kurse API import

### ISSUE THREAD

**Issue by phiresky** [buchen/portfolio#1371]
Hey,

I just started using portfolio (so please let me know if I'm missing something), and I'm really happy with the PDF import feature. But i noticed that importing historical quotes is kind of a pain.

I wrote my own tool a while ago that fetches historical prices from Onvistas API (which is undocumented but outputs nice JSON). The endpoint is `POST https://www.onvista.de/etf/ajax/snapshotHistory`

The only problem is that it needs onvista's internal id for each stock so there's one api call to convert ISIN to onvistaid, then another to get the historical prices.

Here's my pretty simple (typescript) code for fetching the data: https://github.com/phiresky/portfolio-bot/blob/master/get-price-history.ts

I might also be able to send a PR to add this myself, but haven't really looked at any of the code here.

**Comment by phiresky** [comment]
Ah one more thing:

The API response looks like an array of this, one entry per day:

https://github.com/phiresky/portfolio-bot/blob/0a516a5bc137084ccceb5d03a51e908bc9491150/types.ts#L3-L37

**Comment by buchen** [comment]
Thanks for the code samples.

Looking at the [disclaimer](https://www.onvista.de/disclaimer.html) I am hesitant to implement something against undocumented APIs:

> Eine automatisierte Abfrage der Inhalte des Finanzportals ist ohne ausdrückliche Einwilligung von onvista in jeglicher Form unzulässig. Zuwiderhandlung wird verfolgt.

Did you happen to have contact with onvista folks?

**Comment by phiresky** [comment]
Mh yeah that might make sense. The API has been absolutely solid for me (and given much better results than yahoo which sometimes seems to have gaps etc), with no auth (and no rate limiting that I saw).

I'm not sure about the legality. I don't think there would be much of the problem, since those paragraphs mainly talk about forbidding commercial use etc.

> Ihre zwingenden gesetzlichen Rechte (einschließlich der Vervielfältigung zum privaten und sonstigen eigenen Gebrauch nach § 53 UrhG) bleiben unberührt.

I'm not convinced that fetching the API directly, which is the same thing that happens when you select a time range and click the "show data" button, is somehow legally different than just doing that and copy-pasting a HTML table into portfolio. Except being much less effort and more robust of course.

Portfolio wouldn't be spreading any data or have a commercial interest, it's just a tool to help people make a copy of the data they can see on the website for personal use an an easier way.

**Comment by phiresky** [comment]
I mean maybe it should come with a disclaimer on first use that you're confirming you know you're fetching data tables from onvista and that you're only using it for personal use, though that probably applies to all the other services too.

**Comment by buchen** [comment]
Other providers such as AlphaVantage, Quandl, Finnhub have explicit APIs and allow their usage.

**Comment by phiresky** [comment]
Just as a note in case any one else is looking for this: I wrote a small "proxy" server that allows onvista to be used as an api via the generic JSON provider: https://github.com/phiresky/portfolio-bot/blob/master/portfolio-performance-json-server.ts

The resulting data quality is *much* higher than Yahoo for both ETFs and stocks and doesn't require converting the ISIN to a ticker symbol or similar.
