### ISSUE TITLE
ING-Diba: Import von PDF-Bankdokumenten

### ISSUE THREAD

**Issue by juengling** [buchen/portfolio#1377]
Es erscheint die Fehlermeldung "ING-Diba; Unbekannter oder nicht unterstützter Buchungstyp in 'DATEINAME.pdf'". Dazu zahlreiche Fehlermeldungen zu anderen Banken.

Leider sehe ich keine Möglichkeit, weitere Details zu diesem Fehler abzurufen.

Es handelt sich um den Kontoauszug eines Girokontos bei der ING-Diba.

PP v0.44.0, Ubuntu (64bit) v18.04.4, Java v11.0.6+10-post-Ubuntu-1ubuntu118.04.1

**Comment by buchen** [comment]
Ohne eine Beispiel-Datei (siehe [Post](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#andere-dokumente)) kann ich dazu nichts sagen - die Dokumente ändern sich immer wieder mal.

Bei der ING-Diba werden folgende Dokumente unterstützt:
* Wertpapierabrechnung Kauf
* Wertpapierabrechnung Verkauf
* Ertragsgutschrift
* Zinsgutschrift
* Dividendengutschrift

Der reine Kontoauszug hat gff. nicht ausreichend Informationen

**Comment by Ragas13** [comment]
Kontoauszüge sind aktuell auch nicht möglich, da der Fokus auf den einzelnen PDF von Kauf/Verkauf und Co liegt. PP ist mE keine Buchhaltung für alle Buchungen des Girokontos.

**Comment by juengling** [comment]
Ok, das würde es bereits erklären, danke. Alle Buchungen würde ich auch gar nicht wollen, aber wie handhabt man dann die Schwankungen auf dem Girokonto?

**Comment by cmaoling** [comment]
Ich importiere die ING-Diba Kontoauszüge als CSV mit entsprechender Anpassung. Die basiert auf dem "alten" CSVImporter weshalb ich eine eigene Fork von PP betreibe. https://github.com/cmaoling/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/csv/CSVDibaAccountTransactionExtractor.java

**Comment by r41d** [comment]
Hallo, ich habe mit manchen Dokumenten ein Problem und es kommt die Meldung dass nur 3 von 4 Pattern erkannt wurde.
Beispiel: https://imgur.com/a/1gu4wTi
Ich vermute dass das Problem darin liegt dass der Code auf `Vorabpauschale per St.ck` prüft, im Dokument kommt aber `Vorabpauschale gem. § 18 InvStG` vor.

**Comment by Nirus2000** [comment]
Hallo @r41d 
melde Dich doch bitte im Forum unter https://forum.portfolio-performance.info/ an und erstelle ein PDF-Debug. Wie es funktioniert, können Sie im Video-Tutorial sehen.

Video-Tutorial:
[PDF-Dokumente für die Fehlersuche extrahieren](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

Gruß
Alex
