### ISSUE TITLE
Falsche Sortierung von "Einstandskurs" unter Wertpapier Performance

### ISSUE THREAD

**Issue by IV1T3** [buchen/portfolio#1385]
Die Sortierung der Spalte "Einstandskurs" im Reiter Wertpapier Performance sortiert nicht nach Zahlenwert, sondern nach dem "Stringwert". So ist bspw. absteigend sortiert 99€ vor 100€.

**Comment by inv-trad** [comment]
Fehler behoben mit Pull Request #1389
