### ISSUE TITLE
Läuft nicht auf ARM64

### ISSUE THREAD

**Issue by kontny** [buchen/portfolio#1386]
Ich benötige eine 64-Bit-App (ARM64), 32-Bit-Apps (ARM32) oder 32-Bit-Apps (x86). 
Auf meinem Surface lässt sich die hier zu downloadende x86 Version nicht starten

**Comment by Ragas13** [comment]
@kontny 
Portfolio Performance ist unter ARM nicht lauffähig. Verfügbar ist die 64-bit Variante für Windows, Apple und Linux.

**Comment by buchen** [comment]
Und insbesondere verwendet PP als UI Library [SWT](https://www.eclipse.org/swt/) und ist darum abhängig für welchen Plattformen SWT zur Verfügung steht: Windows, Mac/Cocoa, Linux/GTK (x86 64-bit), Linux/GTK (ppcle 64-bit).
