### ISSUE TITLE
Import Dividende Trade Republic führt zu Fehler MsgCheckUnitForexNotValid in checkGrossValueAndUnitsAgainstSecurity

### ISSUE THREAD

**Issue by olaf-kramer** [buchen/portfolio#1390]
Hallo zusammen,

habe den obigen Fehler beim Import einer Dividende von Trade Republic. 
(s.a. Forum https://forum.portfolio-performance.info/t/pdf-import-von-trade-republic/5107/31)

Ohne diese Section in trade-republic-dividends.json läuft der Import bei mir.

`
{
					"context": "UNIT",
					"isOptional": true,
					"pattern": [
						"Quellensteuer DE für US-Emittent -(?<fxAmount>[\\d.,]+) (?<fxCurrency>\\w{3}+)",
						"Zwischensumme (?<fxRateToBase>[\\d.,]+) \\w{3}+/\\w{3}+ [\\d.,]+ \\w{3}+"
					],
					"attributes": {
						"type": "TAX"
					}
				}
`

Hoffe das hilft bei der Fehlersuche.
Gruß
Olaf.

**Comment by olaf-kramer** [comment]
Noch als Anmerkung: Der Fehler tritt bei mir nur auf wenn das Wertpapier vorher bereits mit Währung EUR angelegt ist. 
Ist das Wertpapier noch nicht vorhanden wird es beim Import der Dividende mit Währung USD angelegt und die Buchung funktioniert.

**Comment by Pnda87** [comment]
ich schaue mir gerade dieses Problem an und versuche es anhand der Test PDFs im Forum nachzuvollziehen...

Habe auf dem Weg dorthin allerdings ein anderes Problem mit den **JSON Tests**.
TradeRepublic Dividenden Buchungen sind ja über den JSON Extractor angelegt (#1195).
Ich habe ein neues Beispiel und den JSON Testcase in Eclipse (Dividende04) abgelegt:

![image](https://user-images.githubusercontent.com/34549632/77821043-3c523c00-70e7-11ea-8bbd-f527acb06b03.png)

Offenbar wird der Testcase aber nicht in Eclipse ausgeführt. 
--> Wie kann ich Infinitest denn dazu bringen, den Test auszuführen? 
Das würde ungemein beim Debuggen des Problems helfen..

**Comment by inv-trad** [comment]
> Wie kann ich Infinitest denn dazu bringen, den Test auszuführen?

Für die JSON Tests muss man die JSONPDFTestCase.java ausführen:

![grafik](https://user-images.githubusercontent.com/59824809/82113665-febd7700-9757-11ea-9201-2e0a22343195.png)

**Comment by inv-trad** [comment]
Das Problem sollte mit PR https://github.com/buchen/portfolio/pull/1570 und anderen darauf folgenden Fixes nun behoben sein.
