### ISSUE TITLE
Add All Transactions view directly to GUI

### ISSUE THREAD

**Issue by cqst** [buchen/portfolio#1395]
Hi again !

Would be nice and usefull in my opinion to have a view of all transactions/event done whatever it is securities, deposit, transfer...

Currently we have to remember which accounts we dealt with to find what we done last month, last year...

So maybe a view with a period criteria where we can get an exhaustive historic ?

What do you think ? No problem if it doesnt seem usefull or dont want to work on it, Im just trying to share my improvements ideas as a user :)

Cheers

**Comment by buchen** [comment]
What about **Views -> All Transactions** via the menu?

You see all transactions regardless of account.

There is no view of "events" (other than dividend transactions that happen to be in the list)

**Comment by cqst** [comment]
Oh sorry I had no idea it was already present in the menu in the shadow ;)
That's perfect ! Thank you

**Comment by cqst** [comment]
fixed by commit d79639d88a249eb9c9eae1921079d4c65c133b99
