### ISSUE TITLE
Idea: Provide possibility to look at debug info with quote providers

### ISSUE THREAD

**Issue by simpsus** [buchen/portfolio#1397]
A lot of questions/problems arise from historic/current quote imports from various sources. For me, this is the #1 thing that breaks from time to time and needs my attention.

If a data retrieval fails, the user does not get any information on what the API/website returned and therefore does not have info to post in a forum or a starting point for investigation.

Idea: Provide a button to show the verbose return from the retrieval operation

**Comment by Ragas13** [comment]
I'm not sure but did you recognize the error log at the menu? Because this function is already available...

**Comment by simpsus** [comment]
I know about that dialog in the global window. I am talking about this dialogue
![image](https://user-images.githubusercontent.com/1447101/75115659-e0684380-5660-11ea-85b8-3ca470153d6f.png)

**Comment by buchen** [comment]
I agree: it would be nice to have - inside the dialog - an option to have a look at the raw response to understand what could go wrong. That is not also relevant for the HTML table, but also others: Quandl can have different column names - one would like to know which ones. The JSON import requires JsonPath expression - one would like to see the data structure to know how to formulate the expressions.

As discussed [here](https://github.com/buchen/portfolio/issues/1387#issuecomment-589985245), the code needs some love - and more debug options is one more thing to add.

**Comment by simpsus** [comment]
@buchen Thanks for considering this. I see this from the users perspective. Reliable data collection is the crucial part to the long term value of PP and with websites is a constant hassle and hit-and-miss. Debug info will not solve that but at least give the average user a starting point.

**Comment by buchen** [comment]
Ich habe eine erste Version gebaut - siehe Screenshot.

Allerdings speichere ich jetzt für jeden Request auch die HTML/JSON response. Ich muss noch überlegen ob das so eine schlaue Idee ist oder ob damit nicht zu viel Speicher verbraucht wird.

<img width="733" alt="Bildschirmfoto 2020-04-10 um 11 39 54" src="https://user-images.githubusercontent.com/587976/78981374-17ff5200-7b20-11ea-8266-1fad2d2cf332.png">

**Comment by simpsus** [comment]
Hmmm … wenn man wirklich viele papiere hat kann das schon in den Arbeitsspeicher gehen. Die meisten User werden von diesem Einsatz an Ressourcen keinen Nutzen haben. Die meisten verstehen diese Art von Debug info nicht.

 

Zwei Ideen: 

a.	Wenn man vor dem speichern testet, ob die Antwort ein Fehler ist oder „richtige“ Daten, dann könnte man nur die fehlerhaften speichern.
b.	Ich denke jeder kann damit leben, wenn diese Antworten die Session nicht überlegen, dann müsste man sie auch nicht im Save File speichern sondern „nur“ im Arbeitsspeicher.

 

Von: Andreas Buchen <notifications@github.com> 
Gesendet: Freitag, 10. April 2020 11:42
An: buchen/portfolio <portfolio@noreply.github.com>
Cc: Bastian Kennel <bastian.kennel@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [buchen/portfolio] Idea: Provide possibility to look at debug info with quote providers (#1397)

 

Ich habe eine erste Version gebaut - siehe Screenshot.

Allerdings speichere ich jetzt für jeden Request auch die HTML/JSON response. Ich muss noch überlegen ob das so eine schlaue Idee ist oder ob damit nicht zu viel Speicher verbraucht wird.

 <https://user-images.githubusercontent.com/587976/78981374-17ff5200-7b20-11ea-8266-1fad2d2cf332.png>

**Comment by Ragas13** [comment]
Es ist nur so eine Überlegung, anstelle die Response per Default zu speichern, diese erneut zu laden wenn man auf Debug geht?

Was bei JSON bzw HTML Response evtl die Lesbarkeit verbessern könnte, so etwas wie pretty Printausgabe?! Beim HTML Feed findet dies ja bereits im Fehlerprotokoll statt. Ginge das nicht hier auch?

**Comment by buchen** [comment]
> Ich denke jeder kann damit leben, wenn diese Antworten die Session nicht überlegen, dann müsste man sie auch nicht im Save File speichern sondern „nur“ im Arbeitsspeicher.

Die sind auch nur im Arbeitsspeicher. Aber ich habe gesehen, dass HTML Seite teilweise 2 MByte verbrauchen. Und viele 200k. Das summiert sich recht schnell.

Ich glaube ich werde das so umbauen, dass die "Debug" Informationen nur vorgehalten werden wenn a) man die Kurslieferanten im Dialog konfiguriert oder b) per Kontextmenü explizit die Debug Informationen sehen will.

**Comment by buchen** [comment]
> Was bei JSON bzw HTML Response evtl die Lesbarkeit verbessern könnte, so etwas wie pretty Printausgabe?!

Ja, macht auf jeden Fall Sinn. Das war der erste Wurf. Der User kann bis dahin den Text ja in seinen Lieblingseditor kopieren und da formatieren.
