### ISSUE TITLE
Text Abstand Bestand wenn mit Komma

### ISSUE THREAD

**Issue by chrisaut** [buchen/portfolio#1401]
Hallo,

Ist es so gewollt dass der Text in der Bestandsspalte unter Vermögensaufstellung wie folgt gerendert wird:

![image](https://user-images.githubusercontent.com/8252355/75426240-8c04e280-5944-11ea-88e8-6e3f29309e44.png)

Es scheint der Text ist rechtsbündig, wenn ohne Komma dann auch mit entsprechendem Abstand. Wenn allerdings Kommabestände vorhanden sind richten sich die Zahlen zwar korrekt aus, der Abstand (margin) rechts zum Spaltenrand fehlt allerdings komplett.

Für mich sieht das sehr unordentlich aus, könnte man den Abstand auch nach der letzten Kommazahl erzwingen? Bin leider nicht so der Javatyp, sonst würde ich selbst mal reinschauen.

Tolles Program übrigens

**Comment by Pnda87** [comment]
Stimmt, das ist unschön. Ich habe eine Lösung als Pull Request (#1404 ) eingereicht
