### ISSUE TITLE
Import von Stornierten Dividenden

### ISSUE THREAD

**Issue by Loader23** [buchen/portfolio#1405]
Hallo,

bei REITs ist es manchmal leider so, dass die Dividende storniert wird und kurz darauf mit neuem Betrag wieder gut geschrieben wird. Nun wäre es schön, wenn man diese Stornos auch importieren könnte und der Betrag entsprechend abgezogen wird. Das Beispiel ist jetzt von Trade Republic aber bei ING hatte ich das auch schon:

```
PDF Author: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
My Name SEITE 1 von 1
My Str. 2 DATUM 26.02.2019
D 12345 Berlin DEPOT XXXXXXXXX
STORNO DIVIDENDE
ÜBERSICHT
Storno der Dividende mit dem Ex-Tag 29.11.2019.
POSITION ANZAHL KURS BETRAG
Realty Income Corp. 200 Stk. 0,227 USD 45,40 USD
Registered Shares DL 1
ISIN: US7561091049
GESAMT 45,40 USD
ABRECHNUNG
POSITION BETRAG
Quellensteuer DE für US-Emittent 6,81 USD
Zwischensumme -38,59 USD
Zwischensumme 1,1105 EUR/USD -34,75 EUR
Kapitalertragssteuer 4,09 EUR
Solidaritätszuschlag 0,220 EUR
Kapitalertragssteuer Optimierung -0,090 EUR
Kirchensteuer Optimierung 0,360 EUR
GESAMT -30,17 EUR
BUCHUNG
VERRECHNUNGSKONTO VALUTA BETRAG
DEXXXXXXXXXXXXXXXXXXX 26.02.2020 -30,17 EUR
Realty Income Corp. Registered Shares DL 1 in Wertpapierrechnung.
Lagerland: USA
Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.
Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie 
Leistung.
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
ABRE / 2020-02-26 / 363XXXXX / XXXX-XXXX
```

**Comment by Ragas13** [comment]
Die Wahrscheinlichkeit ist mE eher gering, denn es ist nahezu unmöglich die ursprüngliche Buchung zu identifizieren und diese quasi zu neutralisieren. Das einzige was passieren würde es würden Dividenden im November 2019 gezahlt und dann im Februar 2020 erfolgt die Gegenbuchung, da das Valuta Datum am 26.02.2020 war. Aber ist das richtig bzw gewünscht? Zumal dann die neue Dividende am gleichen Tag eintrifft und dadurch die vorherige Buchung neutralisiert :thinking:

**Comment by Loader23** [comment]
Also die ursprünglich Buchung brauch und sollte auch nicht neutralisiert werden. Denn es ist ja nicht so, dass es einfach storniert wird und neu gebucht wird, das wäre ja zu einfach dann könnte man das ja einfach alles ignorieren. Die neue Dividende unterscheidet sich ja von der alten.

Daher sollte der Betrag in der Storno einfach abgezogen werden und dann kann man die neuen einfach importieren.

**Comment by cmaoling** [comment]
Hallo, denke das könnte man einfach realisieren.
Ich habe mal angefangen mit der DIVIDEND_CHARGE was zu codieren.
Diese benutze ich um Stückzinsen bei Anleihen zu verwalten.
Wenn mein ein solches Storno als DIVIDEND_CHARGE behandeln würde, wäre es eine negative Dividende... Weiß nicht ob einige Metriken damit Probleme haben, aber das wäre mein Lösungsvorschlag.
Alles andere wäre unverändert. beim Parsen würde er basierend auf dem Header keine DIVIDEND buchen, sondern eine DIVIDEND_CHARGE. Done.

**Comment by buchen** [comment]
Ich frage mich wie häufig sowas vorkommt... lohnt sich das? Oder korrigiert man einfach die Original Dividendenbuchung?


Und dann die Frage was man sehen will: z.B. in der historischen Ansicht ist die Linie erst höher und fällt dann wieder ab. Aber eigentlich hat man fälschlicherweise (?) zunächst zu viel ausbezahlt bekommen. Will ich das in den Auswertungen sehen? Und was würde es mir sagen?

**Comment by oduudo** [comment]
Bei Lynx hab ich das tatsächlich sehr häufig, ich weiß auch nicht warum.
Teilweise habe ich mehr als 5 mal Buchung / Storno bei einer Dividendenzahlung, das ist echt doof händisch zu verfolgen, weil die Buchung ja importiert wird, die Stornos aber nicht. Das ist manuell sehr fehleranfällig.. ich würde die Möglichkeit für Storno bzw. negative Dividende sehr begrüßen..

**Comment by cmaoling** [comment]
@buchen do you support this enhancement?
I have already some code for this, so I can offer to compile an initial pull request.

**Comment by christen90** [comment]
@cmaoling
Habe auch so Buchungen in meinem Trade Republic. Schick doch mal dein Code, dann kann ich mich davon inspirieren lassen.

Beste Grüße
Christian

**Comment by cmaoling** [comment]
@christen90 Schaue Dir mal folgenden Issue in meiner Fork an : https://github.com/cmaoling/portfolio/issues/28
Frohe Inspiration. :)

**Comment by kimmerin** [comment]
> Ich frage mich wie häufig sowas vorkommt... lohnt sich das? Oder korrigiert man einfach die Original Dividendenbuchung?

Der Issue ist etwas älter, aber noch offen und diese Frage unbeantwortet. Bei REITs kommt das vor und es gibt REITs, die monatlich eine Dividende ausschütten. Pro Dividende erhält man dann ein Stornodokument und mindestens eine Korrektur. Eventuell wird die ursprüngliche Dividende aber aufgeteilt, wofür man dann jeweils ein Dokument erhält. Letztes Jahr für, "Realty Income" waren das 44 PDFs innerhalb einer Woche (inkl. einer regulären "neuen" Dividende):

```
16.02.2021  20:34           153.943 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492841.pdf
16.02.2021  20:34           153.949 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492842.pdf
16.02.2021  20:34           153.940 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492843.pdf
16.02.2021  20:34           153.942 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492844.pdf
16.02.2021  20:34           153.940 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492845.pdf
16.02.2021  20:34           153.938 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492846.pdf
16.02.2021  20:34           153.943 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492847.pdf
16.02.2021  20:35           153.938 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492848.pdf
16.02.2021  20:35           153.938 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492849.pdf
16.02.2021  20:35           153.934 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492850.pdf
16.02.2021  20:35           153.934 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id957492851.pdf
16.02.2021  20:35           156.211 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078118.pdf
16.02.2021  20:35           156.173 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078119.pdf
16.02.2021  20:35           155.961 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078120.pdf
16.02.2021  20:35           156.221 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078121.pdf
16.02.2021  20:35           156.181 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078122.pdf
16.02.2021  20:35           155.958 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078123.pdf
16.02.2021  20:35           156.204 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078124.pdf
16.02.2021  20:35           156.175 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078125.pdf
16.02.2021  20:35           155.940 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078126.pdf
16.02.2021  20:35           156.205 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078127.pdf
16.02.2021  20:35           156.172 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078128.pdf
16.02.2021  20:35           155.952 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078129.pdf
16.02.2021  20:35           156.214 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078130.pdf
16.02.2021  20:35           156.168 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078131.pdf
16.02.2021  20:35           155.957 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078132.pdf
16.02.2021  20:35           156.184 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078133.pdf
16.02.2021  20:35           156.132 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078134.pdf
16.02.2021  20:35           155.923 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078135.pdf
16.02.2021  20:35           156.179 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078136.pdf
16.02.2021  20:36           156.141 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078137.pdf
16.02.2021  20:36           155.931 2021-02-15 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210215_id958078138.pdf
16.02.2021  20:38           156.399 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304866.pdf
16.02.2021  20:38           156.148 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304867.pdf
16.02.2021  20:38           155.934 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304868.pdf
16.02.2021  20:38           156.395 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304869.pdf
16.02.2021  20:38           156.143 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304870.pdf
16.02.2021  20:38           155.930 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304871.pdf
16.02.2021  20:38           156.426 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304872.pdf
16.02.2021  20:38           156.147 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304873.pdf
16.02.2021  20:38           155.939 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304874.pdf
16.02.2021  20:38           156.189 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304875.pdf
16.02.2021  20:38           156.149 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304876.pdf
16.02.2021  20:38           155.930 2021-02-16 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210216_id958304877.pdf
19.02.2021  22:18           156.336 2021-02-18 REALTY INCOME CORP. ERTRAGSGUTSCHRIFT_123456789_wkn899744_dat20210218_id959111105.pdf
```

Alle Dokumente werden (hier im Falle von Consors) als "Erträgnisgutschrift" angezeigt, so dass man in das Dokument reinschauen muss, um zu sehen, was Sache ist. Dabei sind die ersten 12 die Storni sämtlicher Dividendenzahlungen des Vorjahres. Dann wurde die Dividende in zwei Teile aufgeteilt (macht 24 PDFs) und Dezember bis Junidividenden bekamen noch eine weitere Aufteilung wegen "Reklassifizierung", die mit ihrem eigenen PDF kamen.

Zwar bleiben die USD-Beträge in Summe die gleichen, da die Storni aber mit dem Wechselkurs des originalen Valutatages ausgebucht und die aufgeteilten Beträge mit den aktuellen Wechselkursen eingebucht werden, können sich Unterschiede in den Beträgen ergeben, was Steuerrückerstattungen oder -nachzahlungen zur Folge hat, d.h. man muss das alles mit relativ viel Aufwand manuell in PP nachpflegen.

Das war jetzt der Aufwand für eine Firma. American Capital zahlt aber auch monatlich und macht diese Reklassifizierungen ebenfalls ganz gerne zu der Zeit. Wer solche Papiere hält sieht dem Frühling daher selten gutgelaunt entgegen, was das angeht ;-)
