### ISSUE TITLE
Kann keine Spalte in SecurityListView hinzufügen

### ISSUE THREAD

**Issue by Flippo24** [buchen/portfolio#1410]
Hi Leute,

ich vesuche gerade eine Spalte zur SecurityListView hinzuzufügen, dazu habe ich die [Quote Spalte ](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/SecurityListView.java#L651-L665) erstmal zum Test kopiert und als dritte spalte gleich hinter den Codeblock eingefügt. Noch vor support.createColumns(). Beim Debuggen kann ich die Spalten dann auch innerhalb von support sehen. Aber leider sehe ich sie nicht in der GUI. Dort sind nur die ursprünglichen (date + quote) zu sehen. Finde leider nicht warum sie dort nicht auftaucht.

**Comment by Ragas13** [comment]
Ursache könnte sein das das alte Layout geladen wird. Ändere einmal ```@prices``` in ```@pricesV2```

https://github.com/buchen/portfolio/blob/b5c738365bb65fb5ac853513aeab3b042902269f/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/SecurityListView.java#L609-L610

**Comment by Flippo24** [comment]
Herzlichen Dank. Das funktioniert. Wo bzw. wie finde ich dieses Layout?

**Comment by Ragas13** [comment]
Gar nicht, so wie ich Andreas verstanden hatte wird unter diesem Namen das Layout der Tabelle in den Eingeweiden der Einstellungen gespeichert. Wenn hier programmseitig Spalten geändert werden, bewirkt diese Änderung das die Spalten in der GUI sichtbar werden.

So war es bspw auch bei mir schon der Fall:
https://github.com/buchen/portfolio/commit/701dba15b7089ffa320040265de33ce2d34ad3d1

**Comment by Flippo24** [comment]
Das verstehe ich nicht ganz. Die Spalten werden ja nach der Konfiguration auf sichbar gesetzt. class.getSimpleName() gibt den Klassennamen zurück und der ändert sich ja nicht. Aber warum funktioniert es auch wenn man den String-Zusatz weg lasse. Wozu den dann überhaupt?

**Comment by Flippo24** [comment]
Ich habe den Klassennamen + Zusatz in der Settings Datei der GUI wiedergefunden. Würden dann z.B. bei Updates schon Sinn machen den drin zu behalten, falls man wieder downgraded.

**Comment by Ragas13** [comment]
Alte Version = alte Spaltenkonfiguration, neue Version = neue Spaltenkonfiguration. Es funktioniert nicht anders.

**Comment by buchen** [comment]
Die Spaltenkonfiguration wird mit diesem Schlüssel in der Hash Map in den Settings gespeichert. Der Key ist meinst Klassenname + "@" + Tabellennamen.

Für Tabellen bei denen der Nutzer die Spalten selber konfigurieren kann ist das dann kein Problem: Das ist eine neue aber ausgeblendete Spalte und kann aber über das Menü hinzugefügt werden. Warum ausgeblendet? Sie taucht nicht in der existierenden Konfiguration auf. Ich will ja existierende Tabellen nicht plötzlich verändern.

Für Tabellen, bei denen der Nutzer die Spalten nicht konfigurieren kann, ist der Workaround: neuen Schlüsselnamen vergeben (als z.B. ein "v2" dranhängen). Dann wird die Default-Konfiguration verwendet und die neue Spalte taucht auf.

**Comment by Flippo24** [comment]
Danke euch beiden. Werde erstmal die v2-Variante benutzen.
