### ISSUE TITLE
Data quality table shows small intervalls of working days per week

### ISSUE THREAD

**Issue by cmaoling** [buchen/portfolio#1418]
If historic quotes are not present over a longer period, the individual weeks are highlighted as missing date. This is corerct but makes the list quite long.
I would propose to bridge holidays and week end in these cases.
Example:
No data present in for one month for 10/1...10/31 and assuming 10/1 is Monday and given 10/3 is a holiday in Germany. Rather than these entries
10/1..10/2
10/4..10/5
10/8..10/12
10/14..10/18
10/21..10/25
10/28....10/31
I propose one intervall of 10/1...10/31 being listed.

**Comment by buchen** [comment]
+1

The list is reduced to weeks in the [QuoteQualityMetrics#conflate](https://github.com/buchen/portfolio/blob/45458c855e4197282ef12d0b58452d2a9f496258/name.abuchen.portfolio/src/name/abuchen/portfolio/snapshot/QuoteQualityMetrics.java#L114-L134) method. Do you want to have a go at it?

**Comment by Ragas13** [comment]
I could remember that we're facing the same problem when the chart was drawn. At the chart we've implemented the following date handling:

https://github.com/buchen/portfolio/blob/45458c855e4197282ef12d0b58452d2a9f496258/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/SecuritiesChart.java#L740-L751

I guess the metric needs to be harmonized :thinking: 
https://github.com/buchen/portfolio/blob/45458c855e4197282ef12d0b58452d2a9f496258/name.abuchen.portfolio/src/name/abuchen/portfolio/snapshot/QuoteQualityMetrics.java#L84-L109
