### ISSUE TITLE
Introduce CSV and PDF importer call in context menu of AccountListView

### ISSUE THREAD

**Issue by cmaoling** [buchen/portfolio#1425]
Introduce CSV and PDF importer call in context menu of AccountListView
Add a way to start the import ODF and CSV files out of the AccountListView window.
The Cash and Security Account is extracted based on the current selection in the ListView.
Similar to the implementation provided with #1424.
Will also rework the ImportCSVHandler to be similar to ImportPDFHandler

**Comment by cmaoling** [comment]
@buchen While working on this I observered that in https://github.com/buchen/portfolio/commit/ce04d7bdec61fae421fe4616e42406a26f960635 two different approaches are taken w.r.t. the client handling: 

>   public void execute(@Named(IServiceConstants.ACTIVE_PART) MPart part,
>                    @Named(IServiceConstants.ACTIVE_SHELL) Shell shell, //
>                   IEclipseContext context, //
>                  CSVConfigManager configManager,
>                  @Optional @Named("name.abuchen.portfolio.ui.param.name") String index)
>                  @org.eclipse.e4.core.di.annotations.Optional @Named("name.abuchen.portfolio.ui.param.name") String index)
>    {
>        Optional<Client> client = MenuHelper.getActiveClient(part);
>        if (!client.isPresent())
>            return;
> 

vs. 

>    /* package */ void doExecute(MPart part, Shell shell)
>    {
>        MenuHelper.getActiveClient(part).ifPresent(client -> runImport(part, shell, client));
>    }
>   Client client = MenuHelper.getActiveClient(part);
>   if (client == null)
>       return;

Which one is preferred or is there a reason to have this different between CSV and PDF import handling?

**Comment by buchen** [comment]
I think it does not matter which one.

Either
```
Optional client = MenuHelper.getActiveClient(part);
if (!client.isPresent())
return;
```
then you do not need a separate method but can continue coding in the given method.

Or
```
MenuHelper.getActiveClient(part).ifPresent(client -> ...);
```
then you have a lambda function (which you do not want to get too long I guess and possibly create a new method).
