### ISSUE TITLE
Limit in Wachtlist aufnehmen

### ISSUE THREAD

**Issue by Marfir** [buchen/portfolio#143]
Man kann zwar Watchlisten anlegen, aber es wäre sehr praktisch wenn man pro Wertpapier noch einen Kurs definieren könnte, bei dessen Unterschreitung die Zeile farbig markiert wird.
Es gibt zwar eine Notizspalte, aber die müsste man jedes mal manuell mit dem Kurs abgleichen.

Szenario:
Man legt sich eine watchlist mit interessanten Aktien an, die aber derzeit noch zu teuer sind. Die farbigen Zeilen zeigen dann an, welche Aktien interessant sein könnten.

**Comment by debegr92** [comment]
Ist das nicht sehr ähnlich zu:
https://github.com/buchen/portfolio/pull/171
Bzw. 
https://github.com/buchen/portfolio/issues/163

Das wäre in der Tat eine sehr feine Sache!

**Comment by debegr92** [comment]
Wird das weiter verfolgt, oder gibt es hier Neuigkeiten?
Zusätzlich zur farblichen Hervorhebung und der Sortierung nach dem Delta könnte auch eine Art Eventlog eingebaut werden. Dort wird mitgeloggt, wann diese Preise unter oder überschritten wurden und man kann ggf. eingreifen.

**Comment by buchen** [comment]
Leider sind die "freien Attribute" etwas unglücklich implementiert (um es mal vorsichtig auszudrücken)...

Was man machen könnte:
* Bei den [AttributeFieldType](https://github.com/buchen/portfolio/blob/78aa9164cd7f101bab9daf9213023b87e405ca48/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/settings/AttributeFieldType.java) einen neuen Typ aufzunehmen, z.B. "Limit"
* Da später man die Attribute nur noch an der Klasse erkennen kann, könnte man als Typ zum Beispiel [Quote](https://github.com/buchen/portfolio/blob/78aa9164cd7f101bab9daf9213023b87e405ca48/name.abuchen.portfolio/src/name/abuchen/portfolio/money/Quote.java) verwenden
* Dazu braucht es dann im [AttributeType](https://github.com/buchen/portfolio/blob/78aa9164cd7f101bab9daf9213023b87e405ca48/name.abuchen.portfolio/src/name/abuchen/portfolio/model/AttributeType.java) passende Converter für Quote
* In der [AttributeColumn](https://github.com/buchen/portfolio/blob/78aa9164cd7f101bab9daf9213023b87e405ca48/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/AttributeColumn.java#L116) kann man dann je nach Type einen anderen LabelProvider angeben. Der LabelProvider kann dann die Hintergrundfarbe ändern.
* Der LabelProvider bekommt ein ```Attributable``` reingereicht - das muss sich dann auf den Type ```Security``` beziehen. So könnte man den aktuellen Kurs nachschauen um zu wissen ob das Limit erreicht ist

**Comment by debegr92** [comment]
Wäre es so dann auch möglich dem Attribut ein >= oder <= zusätzlich zum Preis zu geben?
Eigentlich ist es ja klar zum Zeitpunkt wo man das Attribut "Limit" setzt. Man müsste dann nur durch den aktuellen Preis und der Eingabe dann speichern, ob Unter- oder Überschreitung gemeint ist.

**Comment by buchen** [comment]
Gute Idee. Um das auseinander zu steuern brauchst Du eine eigenen Klasse. Die kann ja das "greater as/smaller as" separat speichern.

**Comment by debegr92** [comment]
> * Bei den [AttributeFieldType](https://github.com/buchen/portfolio/blob/78aa9164cd7f101bab9daf9213023b87e405ca48/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/settings/AttributeFieldType.java) einen neuen Typ aufzunehmen, z.B. "Limit"
> 
> * Da später man die Attribute nur noch an der Klasse erkennen kann, könnte man als Typ zum Beispiel [Quote](https://github.com/buchen/portfolio/blob/78aa9164cd7f101bab9daf9213023b87e405ca48/name.abuchen.portfolio/src/name/abuchen/portfolio/money/Quote.java) verwenden
> 
> * Dazu braucht es dann im [AttributeType](https://github.com/buchen/portfolio/blob/78aa9164cd7f101bab9daf9213023b87e405ca48/name.abuchen.portfolio/src/name/abuchen/portfolio/model/AttributeType.java) passende Converter für Quote
> 
> * In der [AttributeColumn](https://github.com/buchen/portfolio/blob/78aa9164cd7f101bab9daf9213023b87e405ca48/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/columns/AttributeColumn.java#L116) kann man dann je nach Type einen anderen LabelProvider angeben. Der LabelProvider kann dann die Hintergrundfarbe ändern.
> 
> * Der LabelProvider bekommt ein `Attributable` reingereicht - das muss sich dann auf den Type `Security` beziehen. So könnte man den aktuellen Kurs nachschauen um zu wissen ob das Limit erreicht ist

Das klingt erstmal ganz schön viel, aber ich schau mal, ob ich das umsetzen kann.

**Comment by debegr92** [comment]
Pull-Request dazu: https://github.com/buchen/portfolio/pull/1330
