### ISSUE TITLE
Problem mit Importer bei Start aus Eclipse

### ISSUE THREAD

**Issue by Pnda87** [buchen/portfolio#1432]
Hallo zusammen,

ich habe ein Problem mit dem Importer (PDF, CSV & Templates).

Wenn ich PP aus Eclipse heraus starte, lässt sich das Importer Dialog nicht öffnen. Der Code ist in Ordnung. Es tritt sowohl bei meinem lokalen branches auf, als auch beim remote branche buchen/portfolio/master.

Woran könnte das liegen? Mache ich etwas falsch?

![image](https://user-images.githubusercontent.com/34549632/76361913-4838b280-6320-11ea-8bff-93c768fb8891.png)

Im Error Log gibt es keine Einträge dazu
![image](https://user-images.githubusercontent.com/34549632/76361889-38b96980-6320-11ea-908e-ab86c775ef18.png)

**Comment by Ragas13** [comment]
@Pnda87 
Schuld könnte sein:
* alte Dateien im Runtime PP Verzeichnis, welches in Benutzerverzeichnis liegt. Ordner ggf löschen. 
* Target Platform unter Eclipse nicht aktuell 
* Notwendige Addons in der Run Configuration fehlen
* Die Dsteien im Eclipse Workspace sind nicht vollständig. Dateien im Eclipse Package mit F5 aktualisieren

**Comment by Pnda87** [comment]
> @Pnda87
> Schuld könnte sein:
> 
> * alte Dateien im Runtime PP Verzeichnis, welches in Benutzerverzeichnis liegt. Ordner ggf löschen.

Ich habe das Projekt neu importiert. Jetzt funktioniert der Importer. Da scheint irgendwas an den Dateien kaputt gewesen zu sein..
Danke für den Tipp

**Comment by Pnda87** [comment]
Ich habe nun erneut das Problem, dass sich der Importer nicht öffnen lässt, wenn ich PP aus Eclipse heraus starte. Nach dem anfänglichen Neuimport des Projekts hat es funktioniert.

Ich habe vor dem Start die Dateien im Workspace Verzeichnis löschen lassen:
![image](https://user-images.githubusercontent.com/34549632/76568452-291d5a80-64b1-11ea-9d46-c5362b15634e.png)

Sowie auch die Configuration Area
![image](https://user-images.githubusercontent.com/34549632/76568486-3afefd80-64b1-11ea-9b67-8844b08a70e7.png)


Oder ist mit dem Runtime PP Verzeichnis etwas anderes gemeint?

Target Platform habeich reloaded.
Required Plugins sind aktiviert.
Workspace ist aktualisiert.

PP an sich startet ja auch richtig, es tritt kein Fehler auf, das Error Log zeigt keine Fehler

Hat jemand eine Idee was da schief läuft?

**Comment by buchen** [comment]
Von den Screenshots sieht das eigentlich okay aus.

Ich vermute aus irgendeinem Grund ist der Pfad nicht korrekt mit dem der Dialog geöffnet wird.

Debugger doch mal den ImportPDFHandler und versuche mal ob das mit setFilterPath funktioniert. Oder welcher Pfad der voreingestellt ist.

**Comment by buchen** [comment]
Ich habe das Problem gefunden. Durch #1426 ist eine ClassCastException reingekommen. Eclipse merkt sich dann, dass dieser Handler (zum Import von CSV und PDF) "kaputt" ist und führt die gar nicht mehr aus. Darum auch keine Exceptions sogar nach dem Neustart. Jetzt sollte es wieder tun.

**Comment by Pnda87** [comment]
@buchen 
Danke für den Hinweis und den Fix!
