### ISSUE TITLE
0.44.1: Taxonomy double layer

### ISSUE THREAD

**Issue by ronnykrijt** [buchen/portfolio#1435]
When creating the 'Industries (GICS)' taxonomy, some of the records have themselves as first drilldown. This doesnt seem logical. See below screenshot for the ones, where Level2, is identical as Level1.

![image](https://user-images.githubusercontent.com/897441/76451731-2d257b80-63d0-11ea-9a32-5e02828f3a07.png)

**Comment by Ragas13** [comment]
The structure based on the Global Industry Classification Standard which is published at https://www.spglobal.com/marketintelligence/en/documents/112727-gics-mapbook_2018_v3_letter_digitalspreads.pdf

The grouping for GICS is the following:

Sector | Industry Group | Industry | Sub-Industry
-- | -- | -- | --

**Comment by ronnykrijt** [comment]
Thanks for answering. Seemed a bit odd, opening the first ones, and then have to click Energy, to see again Energy (and only one as well). But seems answered, given that this is the standard for GICS.
