### ISSUE TITLE
Importer comdirect - Dividenden Transaktion inkl. aller Steuern

### ISSUE THREAD

**Issue by Pnda87** [buchen/portfolio#1443]
Der PDF Impoter für die comdirect arbeitet aktuell nicht korrekt, siehe Themen im Forum [hier](https://forum.portfolio-performance.info/t/comdirekt-steuern-werden-nicht-uebernommen/2330), [hier](https://forum.portfolio-performance.info/t/import-der-steuerbuchung-von-comdirect-funktioniert-nicht/5156), [hier](https://forum.portfolio-performance.info/t/comdirect-dividenden-steuer/5585), [hier](https://forum.portfolio-performance.info/t/uebernahme-der-quellensteuer-bei-pdf-import-von-comdirect/6405) und [hier](https://forum.portfolio-performance.info/t/comdirect-quellensteuer-import/3134). Es gibt dazu auch schon einen ähnlichen Issue #759 

Das Problem bei der comdirect kommt daher, dass es immer 2 PDF Dokumente für eine Dividendenzahlung gibt:
![image](https://user-images.githubusercontent.com/34549632/76705644-e1c9e080-66e1-11ea-88cf-e71dc770e322.png)
- Die Dividendengutschrift_xxx.pdf enthält, wenn bezahlt, die ausländische Quellensteuer
- Die Steuermitteilung_xxx.pdf enthält alle deutschen Steuern

Status quo:
- Der Importer erkennt die Dividendengutschrift_xxx.pdf als Dividende, erfasst allerdings **keine** Quellensteuer als Steuer ein.
- Der Importer erkennt die Steuermitteilung_xxx.pdf als Steuer, erfasst die abgeführte Steuer allerdings in einer **separaten** Transaktion in PP.
Das Ergebnis sieht also so aus (Quellensteuer fehlt als Steuer!):
![image](https://user-images.githubusercontent.com/34549632/76706357-2146fb80-66e7-11ea-94cc-09c6d2f96e44.png)

Ich schlage deshalb folgende Verbesserung vor:
- Option 1: Theoretisch könnte man den Importer so erweitern, dass eine einzige Transaktion aus beiden PDFs erzeugt wird. Dabei gibt es aber die Schwierigkeit, dass die Zuordnung der Steuer zur Dividendenzahlung richtig funktionieren muss (bspw. zeitgleiche Transaktionen auf mehrere Depots, Reihenfolge des Imports der beiden PDFs). Außerdem müsste man sich überlegen was passiert wenn Benutzer nur eine der beiden PDFs importieren.
- Option 2: **Die Steuermitteilung_xxx.pdf enthält allerdings alle relevanten Informationen um eine korrekte Transaktion in PP zu erstellen (Datum, ISIN, WKN, Name des Wertpapiers, Stücke, Bruttobetrag, Nettobetrag)**
- ich würde deshalb die zweite Option bevorzugen: der Import der Steuermitteilung erzeugt eine komplette Transaktion als Dividende inkl. Steuer. Man kann die Transaktion für die Dividendenzahlung aus PP ausbauen oder auch bestehen lassen (wäre mE aber irreführend)
- Mir ist bewusst, dass das eine Änderung zum aktuellen Workflow darstellt

--> Was ist eure Meinung zu dem Thema?

Ich habe das oben skizzierte Vorgehen für Option 2 auf einem lokalen Branch umgesetzt und mit mehreren Dutzend Dividenden Transaktionen (US, DEU, Europa) der letzten 5 Jahre getestet. Funktioniert für mich soweit korrekt. Pull Request #1444

**Comment by fbartnitzek** [comment]
Sehr gut, das diese Thema mal wieder ausgegraben wird. :-)

Diese Loesung kam mir auch schon in den Sinn, hat aber einen gravierenden Nachteil:
**Wenn man beide Dateien gleichzeitig importiert, wird die Dividende doppelt eingebucht.**

Falls man alle Dokumente der comdirect ueber einen bestimmten Zeitraum herunterlaedt (z.B. [hiermit](https://github.com/fbartnitzek/cddl)) und dann alle neuen Dokumente importiert, hat man "zwangsweise" beide drin...

Mir fallen da spontan 2 Auswege ein:
1) doch ein kompliziertes Mergen 
2) ignorieren von Dividenden-Dateien, evtl. ueber "pdf-import-settings" in portfolio performance

Vielleicht hat ja jemand noch eine gute Idee um das Problem zu umgehen.

**Comment by fbartnitzek** [comment]
Dann schau mal ueber meinen Loesungsvorschlag, fuer meine Beispiele passt es sehr gut. ;-)

**Comment by Pnda87** [comment]
> **Wenn man beide Dateien gleichzeitig importiert, wird die Dividende doppelt eingebucht.**

Das ist richtig. Ich habe auch darüber nachgedacht, mich am Ende aber entschieden den bestehenden Import des Dividenden PDFs ersteinmal nicht zu verändern. 
1. um die bestehenden Beispiele (nur Dividenden PDF, kein Steuer PDF vorhanden) weiter verwenden zu können
2. um den Workflow der User, die den Import so haben möchten, nicht kaputt zu machen.

> Falls man alle Dokumente der comdirect ueber einen bestimmten Zeitraum herunterlaedt (z.B. [hiermit](https://github.com/fbartnitzek/cddl)) und dann alle neuen Dokumente importiert, hat man "zwangsweise" beide drin...
Ich denke es ist kein Problem zukünftig nur noch 1 PDF (Steuermitteilung) zu importieren, die Dateinamen unterscheiden sich ja deutlich. Man muss die Dateien zum Import ja manuell auswählen. 

> 1. doch ein kompliziertes Mergen
> 2. ignorieren von Dividenden-Dateien, evtl. ueber "pdf-import-settings" in portfolio performance
Ich finde deinen Vorschlag, die Transaktion aus der Dividenden PDF nachträglich zu löschen sehr gut! :) Ich werde den PR am Wochenende mit einigen meiner Dividendenbuchungen testen.

**Comment by Pnda87** [comment]
@fbartnitzek
> Dann schau mal ueber meinen Loesungsvorschlag, fuer meine Beispiele passt es sehr gut. ;-)

Habe Dividendenbuchungen der vergangenen Jahre importiert. Funktioniert bei mir ebenfalls sehr gut. :)

Nachdem Andreas den PR auch schon gemerged hat, schließe ich den Issue hier.
