### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by PhKP** [buchen/portfolio#1445]
Hi

Thank you very much for creating Portfolio Performance!

I think there is a translation missing here:
<img width="725" alt="Screenshot 2020-03-15 kl  22 34 06" src="https://user-images.githubusercontent.com/11960377/76711166-cc6aab80-670d-11ea-9d3d-e1ecc1fee284.png">

**Comment by cqst** [comment]
pull request #1446 
should fix it :)

**Comment by buchen** [comment]
fixed. Thanks.
