### ISSUE TITLE
Fehlermeldung "Neustart nicht möglich ..." nach automatischem Update

### ISSUE THREAD

**Issue by juengling** [buchen/portfolio#1452]
Am Ende eines automatischen Updates wird gefragt, ob PP neu gestartet werden soll. Bei Beantwortung mit JA kommt die Meldung

    Fehler
    Neustart nicht möglich da noch einige Dialog geöffnet sind.

(Aus dem Gedächtnis zitiert.)

Abgesehen vom sprachlichen Fehler (Singular und Plural gemischt) ist diese Meldung bei den letzten Updates jedesmal gekommen.

**Workaround**
Manuelles Beenden und Neustarten von PP verläuft ohne Probleme.

Möglicherweise existiert ein Zusammenhang mit #287. Eine derartige Rückfrage wird jedoch nicht angezeigt.

**Version**
Version: 0.45.1 (März 2020)
Platform: linux, x86_64
Java: 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, Ubuntu

**Comment by debegr92** [comment]
Bei einem ganz neuen Portfolio mit wenigen Wertpapieren ist da kein Problem. Aber mein Portfolio hat sehr sehr viele und beim Start werden hier erstmal 200 Operationen gestartet. Da hab ich dieses Problem auch immer.

**Comment by juengling** [comment]
Ich habe etwa 30 Wertpapiere in diversen Watchlists und sehe nun auch die Statuszeile "x verbleibende Operationen" (die ist mir früher nicht aufgefallen). Vielleicht ist das mit "Dialoge" gemeint?

**Comment by Mattizin** [comment]
Ich habe dieses Verhalten auch bei jedem PP Update. Auch bei mir hilft manuelles Neustarten.
Gefühlt kommt das daher, da beim Schließen eigentlich gefragt werden müsste, ob gespeichert werden soll, da beim Starten ja aktuelle Kurse usw. geladen werden und somit die Datei aktualisiert werden muss (Sternchen am Tab ist da). Diese abfrage kommt bei Verfügbarem Update aber nicht in den Vordergrund. Vielleicht ist dies der Dialog der den automatsichen Restart blockiert?

**Comment by buchen** [comment]
Ich habe jetzt den Neustart aus dem Programm selber mal entfernt - aus welchen Gründen auch hat das zu häufig nicht funktioniert. Auch bei mir auf macOS kann ich mich gar nicht erinnern wann die Anwendung problemlos wieder gestartet ist. Jetzt muss der Benutzer das Programm selbstständig beenden und Neustarten. Schauen wir mal ob das weniger Probleme produziert (oder zumindest weniger unerwartetes Verhalten).


> Ich habe etwa 30 Wertpapiere in diversen Watchlists und sehe nun auch die Statuszeile "x verbleibende Operationen" (die ist mir früher nicht aufgefallen). Vielleicht ist das mit "Dialoge" gemeint?

Aus irgendeinem Grund kann das Eclipse Framework nur den Restart machen, wenn keine weitere Dialog offen sind (z.B. Wertpapier editieren). Darum dieser Fehlermeldung. Jetzt muss der Anwender selbstständig die Bearbeitung abschliessen.
