### ISSUE TITLE
[win32] JSON Importer - Testfälle in Eclipse

### ISSUE THREAD

**Issue by Pnda87** [buchen/portfolio#1473]
Ich habe eben den JSON Importer für ebase erweitert und anschließend einen entsprechenden Testcase dazu angelegt.

Soweit ich das verstehe muss das json File und das Text File den gleichen Namen haben:
![image](https://user-images.githubusercontent.com/34549632/78296022-50ee6400-752d-11ea-8003-c79beff932c4.png)

Dennoch scheint Eclipse den Testfall nicht auszuführen. Absichtlich falsche Werte im JSON File führen nicht zu einem Test Fehler.

Habe ich etwas übersehen? Wo/wie muss man die JSON Testfälle aktivieren?

**Comment by buchen** [comment]
Nein, eigentlich sollten die automatisch gefunden werden.

Wie führst Du die Fälle den aus? Per "Run as Plugin-Junit Test"?

Dann sollten die in dem JSONPDFTestCase auftauchen:

<img width="557" alt="Bildschirmfoto 2020-04-11 um 13 08 48" src="https://user-images.githubusercontent.com/587976/79042151-9679f380-7bf5-11ea-97e9-34313c2ffc2a.png">

**Comment by buchen** [comment]
(Sorry für die späte Antwort - lese nur recht sporadisch Emails und Github Notifikationen)

**Comment by Pnda87** [comment]
Danke für den Hinweis, das hat bereits einen Schritt weiter geholfen.

Ich hatte die Tests bisher nie aktiv ausgeführt, da ich dachte, dass sie per Infinitest ausgeführt werden, wie bei den regulären Importern. -> das passiert (bei mir?) offenbar nicht.

Beispielhaft ausgeführt: DKBExtraktorTest per Run as "Junit Plug-in Test" funktioniert
<img width="409" alt="junit_dkb_test" src="https://user-images.githubusercontent.com/34549632/79065384-33996280-7cb0-11ea-9fdb-bd7c03eb913e.png">

JSONExtraktorTest ausgeführt per "Junit Plug-in Test": funktioniert bei mir nicht
<img width="574" alt="junit_json" src="https://user-images.githubusercontent.com/34549632/79065398-46139c00-7cb0-11ea-9958-f6dac0741159.png">

Die Fehlermeldung hilft mir leider nicht weiter. Doppelklick öffnet nur die Java Klasse, der Cursor springt aber nicht an eine Stelle, wo der Fehler auftritt.

Hat das evtl etwas damit zu tun, dass der Pfad nicht korrekt funktioniert?
Mein System ist Windows 10, Eclipse IDE Version: 2020-03 (4.15.0), Build id: 20200313-1211

**Comment by Pnda87** [comment]
Es werden keine JSON Dateien gefunden, die params ist leer:
![image](https://user-images.githubusercontent.com/34549632/79066736-91cb4300-7cba-11ea-9976-dd115b5ff405.png)


testdir ist noch befüllt mit dem Pfad _C:\Users\xxx\git\portfolio\name.abuchen.portfolio.tests_

**Comment by Pnda87** [comment]
Das Problem sind die Strings des Pfands:
![image](https://user-images.githubusercontent.com/34549632/79071576-cc45d780-7cdc-11ea-8b7a-fb29c5a80e7c.png)

Das funktioniert so nur für Linux, nicht für Windows. --> PR #1484

**Comment by buchen** [comment]
Hi @Pnda87 - vielen Dank für den Fix und das Debugging.

Ich habe Deine Änderung leicht abändern müssen. Und zwar habe ich File.separatorChar verwendet.

Warum? Ich benutze das [Infinitest Plugin](https://infinitest.github.io) in Eclipse. Damit werden die Tests automatisch im Hintergrund ausgeführt wenn sich eine Datei ändert. Das kann ich nur empfehlen. Die Konfiguration ist im Projekt eingecheckt. Aber man kann bei diesen Tests nicht davon ausgehen, dass das Eclipse Framework vollständig initialisiert ist. D.h. auch ```Platform.getOS()``` funktioniert nicht.

Außerdem reicht es nicht nur nach Linux und Windows zu gucken, sondern ich entwickele unter macOS. Mit File.separatorChar sollte es aber immer funktionieren. **Kannst Du das mal testen?**

```java
.filter(p -> p.toString().contains(File.separatorChar + "classes" + File.separatorChar))
```

**Comment by Pnda87** [comment]
Hallo @buchen 
deine Lösung funktioniert bei mir. Danke, wieder etwas gelernt! :)
