### ISSUE TITLE
Add Currency Picker on more views

### ISSUE THREAD

**Issue by iwalucas** [buchen/portfolio#1488]
Hello, currently I can only pick the currency on the Statement of Assets, although it reflects in many views. 
Would it be possible to add the currency picker on all the views of the Performance section?

**Comment by buchen** [comment]
Makes sense. I am thinking to add it to the menu instead of adding it to every toolbar. I think this feature is not used very often because usually one looks at the data in the primary currency. And some toolbars are already quite "crowded".

**Comment by iwalucas** [comment]
@buchen sure, It will work too! Tks!

**Comment by buchen** [comment]
Feature will be published with the next version

**Comment by iwalucas** [comment]
Hi @buchen , thanks! new menu looks great. Could you update the poeditor strings, so I can translate this new menu to PT? thanks!

**Comment by buchen** [comment]
@iwalucas - Grrr. 😒 I realize that I have not extracted this label for translation. I'll do so, but the translation requires another release...
