### ISSUE TITLE
LGT Bank PDF Import Kaufen

### ISSUE THREAD

**Issue by BuddelPower** [buchen/portfolio#1491]
```
PDF Autor: 'LGT Bank AG'
PDFBox Version: 1.8.16
-----------------------------------------
LGT Bank AG
Herrengasse 12, FL-9490 Vaduz
Tel. +423 235 11 22
info@lgt.com, www.lgt.li, BIC BLFLLI2X
HR Nr.: 1122356-7, Sitz: 9490 Vaduz, MWST-Nr. 50119
UID: CHE-260.887.880
Securities dealer no. 1023228
Herr
Hans Müller
Musterallee 1
12345 Buxtehude
DEUTSCHLAND 1 / 1
Vaduz, 14. April 2020
 
Abrechnung Kauf Portfolio: 0037156.008
Auftragsnummer: 262697612 Kundenportfolio
Kunde: Hans Müller
Titel A.P. Moeller - Maersk A/S
Namen- und Inhaber-Aktien -B-
ISIN DK0010244508
Valorennummer 906020
Wertpapierkennnummer 861837
Abschlussdatum 14.04.2020 09:00:02
Börsenplatz NASDAQ Copenhagen
Anzahl 12 Stück
Kurs DKK 6'732.00
Kurswert DKK 80'784.00
Eidg. Umsatzabgabe  DKK 121.19
Courtage  DKK 1'534.90
Broker Kommission  DKK 12.12
Belastung DKK Konto 0037156.021 DKK 82'452.21
Valuta 16.04.2020
Wir haben die Titel in das oben genannte Depot eingebucht.
Die Gutschrift im oben erwähnten Depot erfolgt vorbehaltlich der effektiven Lieferung.
0037156 13E T VA I TRD1001 50784613 9:32 14.04.2020 %Media:XML-A4H

```

**Comment by Nirus2000** [comment]
Hallo @BuddelPower 

ich würde gern den Importer bauen, dazu benötige ich aber noch mehr Dokumente wie
Kauf, Verkauf, Dividenden etc.

Könntest du mir diese hier noch zur Verfügung stellen?

Grüße
Alex

**Comment by BuddelPower** [comment]
Hallo Nirus,

wie war nochmal die Anleitung zum Übermitteln der gewünschten Daten? Ich glaube da gab es eine spezielle Form dazu.

**Comment by BuddelPower** [comment]
PDF Autor: 'LGT Bank AG'
PDFBox Version: 1.8.16
-----------------------------------------
LGT Bank AG
Herrengasse 12, FL-9490 Vaduz
Tel. +423 235 11 22
info@lgt.com, www.lgt.li, BIC BLFLLI2X
HR Nr.: 1122356-7, Sitz: 9490 Vaduz, MWST-Nr. 50119
UID: CHE-260.887.880
Securities dealer no. 1023228
Herr
Hans Müller
Musterallee 1
12345 Buxtehude
DEUTSCHLAND 1 / 1
Vaduz, 14. April 2020
 
Abrechnung Kauf Portfolio: 0037156.008
Auftragsnummer: 262697612 Kundenportfolio
Kunde: Hans Müller
Titel Novo Nordisk A/S
Namen- und Inhaber-Aktien -B-
ISIN DK0060534915
Valorennummer 23159222
Wertpapierkennnummer A1XA8R
Abschlussdatum 14.04.2020 09:00:02
Börsenplatz NASDAQ Copenhagen
Anzahl 180 Stück
Kurs DKK 396.00
Kurswert DKK 71'280.00
Eidg. Umsatzabgabe  DKK 106.90
Courtage  DKK 1'414.16
Broker Kommission  DKK 10.69
Belastung DKK Konto 0037156.021 DKK 72'811.75
Valuta 16.04.2020
Wir haben die Titel in das oben genannte Depot eingebucht.
Die Gutschrift im oben erwähnten Depot erfolgt vorbehaltlich der effektiven Lieferung.
0037156 13E T VA I TRD1001 50784613 9:32 14.04.2020 %Media:XML-A4H

**Comment by BuddelPower** [comment]
PDF Autor: 'LGT Bank AG'
PDFBox Version: 1.8.16
-----------------------------------------
LGT Bank AG
Herrengasse 12, FL-9490 Vaduz
Tel. +423 235 11 22
info@lgt.com, www.lgt.li, BIC BLFLLI2X
HR Nr.: 1122356-7, Sitz: 9490 Vaduz, MWST-Nr. 50119
UID: CHE-260.887.880
Herr
Hans Müller
Musterallee 1
12345 Buxtehude
DEUTSCHLAND 1 / 1
Vaduz, 14. April 2020
 
Barausschüttung Portfolio: 0037156.008
Auftragsnummer: 262697612 Kontonummer: PDF Autor: 'LGT Bank AG'
PDFBox Version: 1.8.16
-----------------------------------------
LGT Bank AG
Herrengasse 12, FL-9490 Vaduz
Tel. +423 235 11 22
info@lgt.com, www.lgt.li, BIC BLFLLI2X
HR Nr.: 1122356-7, Sitz: 9490 Vaduz, MWST-Nr. 50119
UID: CHE-260.887.880
Securities dealer no. 1023228
Herr
Hans Müller
Musterallee 1
12345 Buxtehude
DEUTSCHLAND 1 / 1
Vaduz, 14. April 2020
 
Abrechnung Kauf Portfolio: 0037156.008
Auftragsnummer: 262697612 Kundenportfolio
Kunde: Hans Müller
Titel A.P. Moeller - Maersk A/S
Namen- und Inhaber-Aktien -B-
ISIN DK0010244508
Valorennummer 906020
Wertpapierkennnummer 861837
Abschlussdatum 14.04.2020 09:00:02
Börsenplatz NASDAQ Copenhagen
Anzahl 12 Stück
Kurs DKK 6'732.00
Kurswert DKK 80'784.00
Eidg. Umsatzabgabe  DKK 121.19
Courtage  DKK 1'534.90
Broker Kommission  DKK 12.12
Belastung DKK Konto 0037156.021 DKK 82'452.21
Valuta 16.04.2020
Wir haben die Titel in das oben genannte Depot eingebucht.
Die Gutschrift im oben erwähnten Depot erfolgt vorbehaltlich der effektiven Lieferung.
0037156 13E T VA I TRD1001 50784613 9:32 14.04.2020 %Media:XML-A4H
Kunde: Hans Müller
Titel A.P. Moeller - Maersk A/S
Namen- und Inhaber-Aktien -B-
ISIN DK0010244508
Valorennummer 906020
Wertpapierkennnummer 861837
Abschlussdatum 14.04.2020 09:00:02
Börsenplatz NASDAQ Copenhagen
Anzahl 12 Stück
Kurs DKK 6'732.00
Kurswert DKK 80'784.00
Eidg. Umsatzabgabe  DKK 121.19
Courtage  DKK 1'534.90
Broker Kommission  DKK 12.12
Belastung DKK Konto 0037156.021 DKK 82'452.21
Valuta 16.04.2020
Wir haben die Titel in das oben genannte Depot eingebucht.
Die Gutschrift im oben erwähnten Depot erfolgt vorbehaltlich der effektiven Lieferung.
0037156 13E T VA I TRD1001 50784613 9:32 14.04.2020 %Media:XML-A4H

> Hallo @BuddelPower
> 
> ich würde gern den Importer bauen, dazu benötige ich aber noch mehr Dokumente wie
> Kauf, Verkauf, Dividenden etc.
> 
> Könntest du mir diese hier noch zur Verfügung stellen?
> 
> Grüße
> Alex



> Hallo @BuddelPower
> 
> ich würde gern den Importer bauen, dazu benötige ich aber noch mehr Dokumente wie
> Kauf, Verkauf, Dividenden etc.
> 
> Könntest du mir diese hier noch zur Verfügung stellen?
> 
> Grüße
> Alex

Dividendenausschüttung

PDF Autor: 'LGT Bank AG'
PDFBox Version: 1.8.16
-----------------------------------------
LGT Bank AG
Herrengasse 12, FL-9490 Vaduz
Tel. +423 235 11 22
info@lgt.com, www.lgt.li, BIC BLFLLI2X
HR Nr.: 1122356-7, Sitz: 9490 Vaduz, MWST-Nr. 50119
UID: CHE-260.887.880

Herr
Hans Müller
Musterallee 1
12345 Buxtehude
DEUTSCHLAND 1 / 1
Vaduz, 14. April 2020
 
Barausschüttung Portfolio: 0037156.008
Auftragsnummer: 262697612 Kontonummer: 0037156.039
Kunde: Hans Müller IBAN: LI74 0981 0000 0371 5603 9
Stand Ihres Depots am 12. Mai 2020:
551 Veolia Environnement SA
Namen- und Inhaber-Aktien
ISIN: FR0000124141, Valoren-Nr.: 1098758
Wir rechnen folgende Erträgnisse unter Eingangsvorbehalt ab:
Ausschüttung EUR 0.50
Ex-Datum 12. Mai 2020
Ausschüttungsart Ordentliche Dividende

Betrag EUR 275.50
Quellensteuer 28 % EUR -77.14
Netto EUR 198.36

Zu Ihren Gunsten EUR 198.36

Valuta 14. Mai 2020

0037156 13E T VA I TRD1001 50784613 9:32 14.04.2020 %Media:XML-A4H

**Comment by Nirus2000** [comment]
Hallo @BuddelPower 
die Formatierungen sind leider alle weg für den Ausbau des LGT Bank Importers...
Bitte im [Forum](https://forum.portfolio-performance.info/)einen neuen Beitrag erstellen und nach der Anleitung des -->[Video Tutorials](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)<-- posten.
Den Beitragsnamen wiefolgt nennen "PDF-Importer LGT Bank"

**Comment by BuddelPower** [comment]
Alles klar mache morgen. Bis dann und Dank

Nirus2000 <notifications@github.com> schrieb am Di., 9. Feb. 2021, 19:33:

**Comment by BuddelPower** [comment]
Habe ich erledigt in zwei Beiträge. 

PDF-Importer LGT Bank
PDF-Importer LGT Bank - Dividende

Vielen Dank

**Comment by Nirus2000** [comment]
@BuddelPower 
danke... wenn du jetzt auch noch für Verkaufen etc. die Dokumente hast, wären
dann Kauf, Verkauf und Dividenden komplett.... was dann noch kommen soll, überlass ich dir :-)
Sobald jemand Zeit dafür gefunden hat, werden diese eingepflegt.

**Comment by BuddelPower** [comment]
Noch habe ich nichts verkauft, baue mir ein Dividendendepot auf. Aber sobald ich verkaufe Stelle ich das gerne zu Verfügung. Vielen Dank

**Comment by Nirus2000** [comment]
@BuddelPower 
sollte beim nächsten Release mit dabei sein :-)
