### ISSUE TITLE
Stacked charts no longer respect time window

### ISSUE THREAD

**Issue by hintz** [buchen/portfolio#1493]
Until recently (0.46.1) the stacked charts in taxonomies (i.e. the default Asset Classes taxonomy) was respecting the time window selected in other charts. This was a bit cumbersome, but at least it was possible to view at the stacked charts in an arbitrary time window.

This seems now broken, with stacked charts always reporting a window of 1 years.

**Comment by buchen** [comment]
Yes, it always shows the window of the first reporting period (which is very often 1 year).

I fixed it. Will come with the next release.
