### ISSUE TITLE
Performance-Berechnung liefert falsche Werte bei realisierten Kurserfolgen

### ISSUE THREAD

**Issue by holzapfelnet** [buchen/portfolio#1498]
Ich habe 2 Depots mit jeweils 2 dazugehörigen Konten. Ich habe das gleiche Wertpapier in beiden Depots. In einem der beiden Depots habe ich das Wertpapier wieder verkauft.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/11599235/79630942-d12fde80-8155-11ea-841f-2a749986932c.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/11599235/79630948-dab94680-8155-11ea-9233-c06d6155eab4.png">

In der Performance-Berechnung für die jeweiligen Depots sind die Berechungen korrekt. Einmal wird ein realisierter Kurserfolg von 13,40 EUR ausgewiesen und einmal ein realisierter Kurserfolg von 0 EUR. 
Wenn ich allerdings auf die Performance-Berechnung für beide Depots gucke, wird ein Verlust von 263,80 EUR ausgewiesen. 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/11599235/79630895-70a0a180-8155-11ea-9d28-4354efe00032.png">

Ich gehe mal davon aus, das bei der Performance-Berechnung das Ganze auf Wertpapierebene berechnet wird und die unterschiedlichen Depots nicht mehr berücksichtig werden.

**Comment by buchen** [comment]
:thinking: In der Tat wird die FIFO Berechnung über beide Depots hinweg gerechnet, also wenn man erst in Depot 1 kauft, dann in Depot 2 kauft, dann in Depot 2 verkauft, dann werden "virtuell" die Anteile aus Depot 1 verkauft. Bei den Trades beachte ich schon die Grenzen zwischen den Depots, hier nicht. Das muss ich beheben.

Und wenn ich das machen, dann sollte ich noch anpassen, dass beim einem Übertrag von einem in ein anderes Depot das Kaufdatum erhalten bleibt - denn auch Steuerlich werden diese Wertpapiere als erstes verkauft.

Vielen Dank für die ausführliche Fehlerbeschreibung!
