### ISSUE TITLE
PDF Import Trade Republic Quartalsauszug Kontoauszug

### ISSUE THREAD

**Issue by Franz-65** [buchen/portfolio#1509]
Hallo, es wäre toll wenn PP den Quartalsauszug einlesen könnte. Hintergrund ist folgender: Da Trade Republic kein vernünftige Übersicht über Umsätze darstellt wäre dies dann zumindest alle 3 Monate in PP möglich. Anbei der Import vom über den PDF-Debugger vom Kontoauszug. 
[Q1 Kontoauszug.pdf.txt](https://github.com/buchen/portfolio/files/4527264/Q1.Kontoauszug.pdf.txt)

PDF Autor: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
Fritz Meier SEITE 1 von 7
Biertrinkerstr. 1 DATUM 22.04.2020
D 57459 Dortmund DEPOT 123498765
KONTOAUSZUG
zum 2020-03-31
BUCHUNGEN
Aufstellung über die Buchungen in Deinem Verrechnungskonto DE12345678912345678912.
BUCHUNGSTAG / BUCHUNGSTEXT BETRAG IN EUR
WERTSTELLUNG
03.01.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 100,00
02.01.2020
06.01.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 3.500,00
06.01.2020
07.01.2020 Accepted PayIn:DE01234567890987654321 to DE12345678912345678912 1.000,00
07.01.2020
08.01.2020 Ausführung Handel Direktkauf Kauf US0970231058 BOEING CO. DL 5 -1.478,00
10.01.2020 6557410720200108
09.01.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 3.000,00
09.01.2020
10.01.2020 Ausführung Handel Direktkauf Kauf US0970231058 BOEING CO. DL 5 -1.485,00
14.01.2020 4700052920200110
14.01.2020 Accepted PayIn:DE52120300001065099937 to DE12345678912345678912 300,00
14.01.2020
14.01.2020 Accepted PayIn:DE01234567890987654321 to DE12345678912345678912 1.000,00
14.01.2020
16.01.2020 Ausführung Handel Direktkauf Kauf IE00B1FZS574 ISHSII-MSCI TURKEY -200,00
20.01.2020 DLDIS 1749900320200116 KW
16.01.2020 Ausführung Handel Direktkauf Kauf IE00B4K48X80 ISHSIII-C.M.E.U.E.EO -150,00
20.01.2020 ACC 2619421520200116 KW
16.01.2020 Ausführung Handel Direktkauf Kauf IE00B5V87390 ISHSVII-MSCI RU ADR -50,00
20.01.2020 /GDRDA 1480032420200116 KW
16.01.2020 Ausführung Handel Direktkauf Kauf IE00B4L5Y983 ISHSIII-CORE MSCI WLD -600,00
20.01.2020 DLA 7660974820200116 KW
16.01.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -200,00
20.01.2020 DLA 4532709120200116 KW
18.01.2020 Auszahlung an Referenzkonto -2.400,00
18.01.2020
21.01.2020 Ausführung Handel Direktkauf Kauf US0970231058 BOEING CO. DL 5 -865,90
23.01.2020 1511087820200121
21.01.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -550,00
23.01.2020 DLA 6139219220200121
21.01.2020 Ausführung Handel Direktkauf Kauf US0970231058 BOEING CO. DL 5 -836,35
23.01.2020 2055629520200121
22.01.2020 Accepted PayIn:DE01234567890987654321 to DE12345678912345678912 2.000,00
22.01.2020
24.01.2020 Ausführung Handel Direktkauf Kauf DE000BAY0017 BAYER AG NA O.N. -601,00
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
SEITE 2 von 7
DATUM 22.04.2020
DEPOT 123498765
28.01.2020 1222476620200124
24.01.2020 Ausführung Handel Direktkauf Kauf DE000BAY0017 BAYER AG NA O.N. -607,40
28.01.2020 7027366920200124
27.01.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -271,29
29.01.2020 DLA 7363036920200127
27.01.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -395,50
29.01.2020 DLA 4000427920200127
27.01.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 200,00
27.01.2020
28.01.2020 Accepted PayIn:DE12345678900123456789 to DE12345678912345678912 1.500,00
28.01.2020
03.02.2020 Ausführung Handel Direktkauf Kauf IE00B1FZS574 ISHSII-MSCI TURKEY -200,00
05.02.2020 DLDIS 1081050120200203 KW
03.02.2020 Ausführung Handel Direktkauf Kauf IE00B4K48X80 ISHSIII-C.M.E.U.E.EO -150,00
05.02.2020 ACC 4999209220200203 KW
03.02.2020 Ausführung Handel Direktkauf Kauf IE00B5V87390 ISHSVII-MSCI RU ADR -49,99
05.02.2020 /GDRDA 5145463320200203 KW
03.02.2020 Ausführung Handel Direktkauf Kauf IE00B4L5Y983 ISHSIII-CORE MSCI WLD -599,99
05.02.2020 DLA 1904844720200203 KW
03.02.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -200,00
05.02.2020 DLA 6954806320200203 KW
12.02.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 900,00
12.02.2020
17.02.2020 Ausführung Handel Direktkauf Kauf IE00B1FZS574 ISHSII-MSCI TURKEY -200,00
19.02.2020 DLDIS 2321500520200217 KW
17.02.2020 Ausführung Handel Direktkauf Kauf IE00B4K48X80 ISHSIII-C.M.E.U.E.EO -150,00
19.02.2020 ACC 4147393520200217 KW
17.02.2020 Ausführung Handel Direktkauf Kauf IE00B5V87390 ISHSVII-MSCI RU ADR -49,99
19.02.2020 /GDRDA 5941174720200217 KW
17.02.2020 Ausführung Handel Direktkauf Kauf IE00B4L5Y983 ISHSIII-CORE MSCI WLD -600,00
19.02.2020 DLA 5466254420200217 KW
17.02.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -200,00
19.02.2020 DLA 6120616220200217 KW
24.02.2020 Ausführung Handel Direktkauf Kauf DE000TR020H2 HSBC T+B X-TUP DAX -402,52
26.02.2020 7880932820200224
25.02.2020 Ausführung Handel Direktverkauf Verkauf DE000TR020H2 HSBC T+B X- 367,20
27.02.2020 TUP DAX 7694884620200225
26.02.2020 Ausführung Handel Direktkauf Kauf IE00B4L5Y983 ISHSIII-CORE MSCI WLD -336,90
28.02.2020 DLA 1283472520200226
26.02.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 560,00
26.02.2020
26.02.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 800,00
26.02.2020
26.02.2020 Ausführung Handel Direktkauf Kauf DE000TT0Y6T3 HSBC T+B TURBOP20 -569,40
28.02.2020 DAX 1994926720200226
27.02.2020 Ausführung Handel Direktkauf Kauf DE000TT00DA9 HSBC T+B TURBOP -627,50
02.03.2020 DAX 6696720520200227
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
SEITE 3 von 7
DATUM 22.04.2020
DEPOT 123498765
28.02.2020 Ausführung Handel Direktverkauf Verkauf DE000TT00DA9 HSBC T+B 818,30
03.03.2020 TURBOP DAX 3354947420200228
28.02.2020 Ausführung Handel Direktkauf Kauf DE000TT01JR8 HSBC T+B TURBOP -788,50
03.03.2020 DAX 4985691320200228
28.02.2020 Ausführung Handel Direktkauf Kauf DE000TT01EX7 HSBC T+B TURBOP20 -220,80
03.03.2020 DAX 9449343420200228
02.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT01EX7 10,76
02.03.2020 HSBC T+B TURBOP20 DAX 8990207620200302
02.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT01EX7 HSBC T+B 180,00
04.03.2020 TURBOP20 DAX 8504047620200302
02.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT0Y6T3 HSBC T+B 849,32
04.03.2020 TURBOP20 DAX 2435097720200302
02.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT01JR8 64,51
02.03.2020 HSBC T+B TURBOP DAX 1808358020200302
02.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT01JR8 HSBC T+B 543,95
04.03.2020 TURBOP DAX 1045108020200302
02.03.2020 Ausführung Handel Direktkauf Kauf IE00B1FZS574 ISHSII-MSCI TURKEY -200,00
04.03.2020 DLDIS 2337450920200302 KW
02.03.2020 Ausführung Handel Direktkauf Kauf DE000TT0Y7C7 HSBC T+B TURBOP -907,00
04.03.2020 DAX 9421019520200302
02.03.2020 Ausführung Handel Direktkauf Kauf DE000TT01JR8 HSBC T+B TURBOP -348,87
04.03.2020 DAX 8020109520200302
02.03.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 1.000,00
02.03.2020
02.03.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 650,00
02.03.2020
02.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT01JR8 31,15
02.03.2020 HSBC T+B TURBOP DAX 4443884020200302
02.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT01JR8 HSBC T+B 230,77
04.03.2020 TURBOP DAX 3945004020200302
02.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT0Y7C7 25,53
02.03.2020 HSBC T+B TURBOP DAX 7833734520200302
02.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT0Y7C7 HSBC T+B 810,20
04.03.2020 TURBOP DAX 7365724520200302
02.03.2020 Ausführung Handel Direktkauf Kauf IE00B4K48X80 ISHSIII-C.M.E.U.E.EO -150,00
04.03.2020 ACC 9238953620200302 KW
02.03.2020 Ausführung Handel Direktkauf Kauf IE00B5V87390 ISHSVII-MSCI RU ADR -49,99
04.03.2020 /GDRDA 5644151720200302 KW
02.03.2020 Ausführung Handel Direktkauf Kauf IE00B4L5Y983 ISHSIII-CORE MSCI WLD -600,00
04.03.2020 DLA 8660946020200302 KW
03.03.2020 Ausführung Handel Direktkauf Kauf DE000TT00C04 HSBC T+B TURBOP -625,00
05.03.2020 DAX 3555542320200303
03.03.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -200,00
04.03.2020 DLA 4339207020200303 KW
03.03.2020 Ausführung Handel Direktkauf Kauf DE000TT00R72 HSBC T+B TURBOP20 -940,40
05.03.2020 DAX 9076096220200303
03.03.2020 Ausführung Handel Direktkauf Kauf DE000TT00999 HSBC T+B SMARTS -355,80
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
SEITE 4 von 7
DATUM 22.04.2020
DEPOT 123498765
05.03.2020 DAX 1887202520200303
05.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT00C04 HSBC T+B 650,48
09.03.2020 TURBOP DAX 5709502320200305
06.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT00999 HSBC T+B 394,97
10.03.2020 SMARTS DAX 3979720520200306
06.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT00R72 HSBC T+B 1.133,74
10.03.2020 TURBOP20 DAX 2568651720200306
06.03.2020 Ausführung Handel Direktkauf Kauf DE000TT069U0 HSBC T+B TURBOP20 -395,00
10.03.2020 DAX 3858176620200306
06.03.2020 Ausführung Handel Direktkauf Kauf DE000TT069U0 HSBC T+B TURBOP20 -398,00
10.03.2020 DAX 3894972720200306
06.03.2020 Ereignisausführung Ertrag US0970231058 BOEING CO. DL 5 21,91
06.03.2020 2789264220200306
09.03.2020 Ausführung Handel Direktkauf Kauf DE000TT0Y7C7 HSBC T+B TURBOP -1.337,50
11.03.2020 DAX 2442206020200309
09.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT069U0 HSBC T+B 1.313,53
11.03.2020 TURBOP20 DAX 9443960520200309
09.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT0Y7C7 HSBC T+B 1.357,02
11.03.2020 TURBOP DAX 4993902820200309
11.03.2020 Ausführung Handel Direktkauf Kauf IE00B4L5Y983 ISHSIII-CORE MSCI WLD -471,00
13.03.2020 DLA 9869303120200311
13.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1A8G3 HSBC T+B TURBOP -1.495,00
17.03.2020 DAX 5570105920200313
16.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1A8G3 HSBC T+B 2.267,47
18.03.2020 TURBOP DAX 9892282320200316
16.03.2020 Ausführung Handel Direktkauf Kauf IE00B1FZS574 ISHSII-MSCI TURKEY -200,00
18.03.2020 DLDIS 6233925920200316 KW
16.03.2020 Ausführung Handel Direktkauf Kauf IE00B5V87390 ISHSVII-MSCI RU ADR -50,00
18.03.2020 /GDRDA 3309936520200316 KW
16.03.2020 Ausführung Handel Direktkauf Kauf IE00B4K48X80 ISHSIII-C.M.E.U.E.EO -150,00
18.03.2020 ACC 3280760620200316 KW
16.03.2020 Ausführung Handel Direktkauf Kauf IE00B4L5Y983 ISHSIII-CORE MSCI WLD -600,00
18.03.2020 DLA 2345122620200316 KW
16.03.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -200,00
18.03.2020 DLA 6166752920200316 KW
18.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1G929 HSBC T+B X-TUP DAX -1.541,50
20.03.2020 3366408020200318
20.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1FNS7 HSBC T+B TURBOC -305,32
24.03.2020 DAX 1582795620200320
20.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1FNS7 8,55
20.03.2020 HSBC T+B TURBOC DAX 7221575320200320
20.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1FNS7 HSBC T+B 272,92
24.03.2020 TURBOC DAX 6617695320200320
20.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1CXL8 HSBC T+B TURBOP -268,75
24.03.2020 DAX 3617063420200320
24.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1CXL8 25,90
24.03.2020 HSBC T+B TURBOP DAX 1395476020200324
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
SEITE 5 von 7
DATUM 22.04.2020
DEPOT 123498765
24.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1CXL8 HSBC T+B 170,53
26.03.2020 TURBOP DAX 5955260720200324
24.03.2020 Ausführung Handel Direktkauf Kauf IE00BKM4GZ66 IS C.MSCI EMIMI U.ETF -200,54
26.03.2020 DLA 4546671020200324
24.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1LZQ3 HSBC T+B TURBO DAX -28,48
26.03.2020 2977537620200324
24.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1LZQ3 HSBC T+B 34,60
26.03.2020 TURBO DAX 9465045320200324
24.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1ASB3 HSBC T+B TURBOP -32,60
26.03.2020 DAX 5264283120200324
25.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1ASB3 4,32
25.03.2020 HSBC T+B TURBOP DAX 5451430220200325
25.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1ASB3 HSBC T+B 16,25
27.03.2020 TURBOP DAX 4861750220200325
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1MVR8 HSBC T+B TURBOC -16,84
27.03.2020 DAX 8856281520200325
25.03.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 1.600,00
24.03.2020
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1MVR8 HSBC T+B TURBOC -623,30
27.03.2020 DAX 9005881420200325
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1MVR8 HSBC T+B TURBOC -420,00
27.03.2020 DAX 8196372420200325
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1CXM6 HSBC T+B TURBOP -887,20
27.03.2020 DAX 2962122420200325
25.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1MVR8 66,22
25.03.2020 HSBC T+B TURBOC DAX 3179458620200325
25.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1MVR8 HSBC T+B 809,08
27.03.2020 TURBOC DAX 1293788620200325
25.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1CXM6 HSBC T+B 1.071,26
27.03.2020 TURBOP DAX 8150972020200325
25.03.2020 Accepted PayIn:GB12REVO12345678912345 to DE12345678912345678912 1.400,00
25.03.2020
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1NCB0 HSBC T+B X-TU DAX -41,20
27.03.2020 6653875320200325
25.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1NCB0 HSBC T+B X-TU 19,70
27.03.2020 DAX 6108074520200325
25.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1NCB0 5,67
25.03.2020 HSBC T+B X-TU DAX 1552757420200325
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1CV13 HSBC T+B SMARTS -68,60
27.03.2020 DAX 1919407920200325
25.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1CV13 7,65
25.03.2020 HSBC T+B SMARTS DAX 1060551520200325
25.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1CV13 HSBC T+B 39,60
27.03.2020 SMARTS DAX 4826015220200325
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1NBN7 HSBC T+B TURBO20 -62,36
27.03.2020 DAX 7086201820200325
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1NBN7 HSBC T+B TURBO20 -368,20
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
SEITE 6 von 7
DATUM 22.04.2020
DEPOT 123498765
27.03.2020 DAX 8624692320200325
25.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1NBN7 21,21
25.03.2020 HSBC T+B TURBO20 DAX 3382140620200325
25.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1NBN7 HSBC T+B 350,13
27.03.2020 TURBO20 DAX 2838150620200325
25.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1CXQ7 HSBC T+B TURBOP -299,50
27.03.2020 DAX 1825108920200325
25.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1CXQ7 HSBC T+B 301,34
27.03.2020 TURBOP DAX 8827268820200325
26.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1NBR8 HSBC T+B X-TUC20 -451,00
30.03.2020 DAX 4612466720200326
26.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1NBR8 HSBC T+B X- 578,37
30.03.2020 TUC20 DAX 9336953720200326
27.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1QHC0 HSBC T+B TURBOC20 -395,80
31.03.2020 DAX 8642427220200327
27.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1QHC0 32,97
27.03.2020 HSBC T+B TURBOC20 DAX 1129729320200327
27.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1QHC0 HSBC T+B 270,80
31.03.2020 TURBOC20 DAX 3494593620200327
27.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1QGQ2 HSBC T+B X-TUP DAX -245,72
31.03.2020 3776839920200327
27.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1QGQ2 8,29
27.03.2020 HSBC T+B X-TUP DAX 8151816820200327
27.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1QGQ2 HSBC T+B X- 214,28
31.03.2020 TUP DAX 7587586820200327
27.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1QJV6 HSBC T+B X-TUC20 -251,00
31.03.2020 DAX 3387997020200327
27.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1QJV6 HSBC T+B X-TUC20 -308,80
31.03.2020 DAX 9302047920200327
27.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1QJV6 2,25
27.03.2020 HSBC T+B X-TUC20 DAX 9375260520200327
27.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1QJV6 HSBC T+B X- 41,70
31.03.2020 TUC20 DAX 8900750520200327
27.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1R1E4 HSBC T+B TURBO20 -559,00
31.03.2020 DAX 6943140820200327
27.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1QJV6 31,01
27.03.2020 HSBC T+B X-TUC20 DAX 2129111920200327
27.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1QJV6 HSBC T+B X- 392,00
31.03.2020 TUC20 DAX 1647941920200327
30.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1QG73 HSBC T+B TURBOP -552,00
01.04.2020 DAX 1617044720200330
30.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1QG73 HSBC T+B 638,14
01.04.2020 TURBOP DAX 5949663320200330
30.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1R1E4 HSBC T+B 47,50
01.04.2020 TURBOP20 DAX 9859053820200330
30.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1R1E4 2,22
30.03.2020 HSBC T+B TURBOP20 DAX 3812538520200330
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
SEITE 7 von 7
DATUM 22.04.2020
DEPOT 123498765
30.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1MVK3 HSBC T+B TURBOC -630,00
01.04.2020 DAX 6815183220200330
30.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1MVK3 HSBC T+B 684,48
01.04.2020 TURBOC DAX 7112580220200330
30.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1MVN7 HSBC T+B TURBOC -680,00
01.04.2020 DAX 2008155620200330
30.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1R1E4 76,93
30.03.2020 HSBC T+B TURBOP20 DAX 1068279020200330
30.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1R1E4 HSBC T+B 211,40
01.04.2020 TURBOP20 DAX 7661619020200330
30.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1MVN7 HSBC T+B 699,88
01.04.2020 TURBOC DAX 2646383620200330
30.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1RJ12 HSBC T+B X-TUC DAX -1.019,00
01.04.2020 8463876220200330
30.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1RJ12 18,46
30.03.2020 HSBC T+B X-TUC DAX 9372195620200330
30.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1RJ12 HSBC T+B X- 949,00
01.04.2020 TUC DAX 8961875620200330
30.03.2020 Ausführung Handel Direktkauf Kauf DE000TT1MW02 HSBC T+B X-TUC DAX -501,00
01.04.2020 2864401620200330
30.03.2020 Ausführung Handel Direktverkauf Verkauf DE000TT1MW02 HSBC T+B X- 500,00
01.04.2020 TUC DAX 6642729520200330
30.03.2020 Kapitalertragssteueroptimierung Depot Direktverkauf DE000TT1MW02 0,27
30.03.2020 HSBC T+B X-TUC DAX 7087269520200330
30.03.2020 Ereignisausführung Tilgung DE000TT1G929 HSBC T+B X-TUP DAX 0,15
31.03.2020 4142739820200330 KW
30.03.2020 Kapitalertragssteueroptimierung Depot Tilgung DE000TT1G929 HSBC T+B 406,53
30.03.2020 X-TUP DAX 4438559820200330
KONTOSTAND AM 31.03.2020: 3.145,07 EUR
Empowered by solarisBank AG
HINWEIS ZUR EINLAGENSICHERUNG
Guthaben sind als Einlagen nach Maßgabe des Einlagensicherungsgesetzes entschädigungsfähig. Nähere 
Informationen kannst Du dem Informationsbogen für den Einleger der solarisBank entnehmen. Diesen findest 
Du im Dokumenten-Center in der App.
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller

**Comment by Ragas13** [comment]
@Franz-65 
Was würdest du für eine Funktionalität erwarten? Mehr als Einzahlung/Auszahlung ist damit nicht möglich da Stückzahlen, Kaufkurs, Gebühren und Steuern fehlen.

Sinniger wäre es die einzelnen Belege der individuellen Transaktion zu importieren und zu verwalten.
