### ISSUE TITLE
VIAC PDF-Import - "Rückerstattung Quellensteuer"

### ISSUE THREAD

**Issue by C1618A** [buchen/portfolio#1514]
Hello
Thank you very much for the fantastic software. I'm using the PDF-Import for VIAC and when it comes to dividends some PDFs work, others not.
I leave here one PDF that work and one that doesn't.
Working: 
https://www.amazon.com/clouddrive/share/sU3XvlBY4UFj18QMPmDs1d47OqnOLLDEPSJf0stMqzK
Not Working:
https://www.amazon.com/clouddrive/share/d4dwdnTrErUciVW3EcZlPjiZ7AWm2FIW7K0iDfl3B8
The difference is that one says "Rückerstattung Quellensteuer"

**Comment by Mauin** [comment]
As a follow-up issue to this: The "Rückerstattung Quellensteuer" appears to always be in CHF, whereas the underlying security might have a different base currency. But a transaction of type TAX_REFUND seems to require a currency conversion in such a case.

@buchen what would be the best way to handle such a situation?
