### ISSUE TITLE
Feature request: Make it possible to add to a filter

### ISSUE THREAD

**Issue by lsolesen** [buchen/portfolio#1519]
Make it possible to add items to a filter after creation under Earnings & Expenses. Right now when a filter has been created and saved, it seems you can edit the name or delete the filter. However, it would be nice to be able to add to the filter.

I am using the filters for my dashboards, so I can show earnings for different asset types.

**Comment by oduudo** [comment]
I would love this feature too..

**Comment by lsolesen** [comment]
Seems to be a duplicate of #1375
