### ISSUE TITLE
Feature request: Make it possible to give the security accounts a taxonomy also

### ISSUE THREAD

**Issue by lsolesen** [buchen/portfolio#1524]
I want to show the XIRR for a portfolio with one security account and several currency deposit accounts - like this:

Security Account Nordnet
Deposit Account Nordnet USD
Deposit Account Nordnet EUR
Deposit Account Nordnet DKK

I cannot get the XIRR and totals to be correct for this portfolio without having to put in the exact securities I bought in this portofolio. However, many of the securities I have also bought in other portfolios, so that would mean that I had to create multiple versions of the same stock. Having the security account link directly from the taxonomy would PP know exactly which securities are connected?

Or make it possible to add more deposit accounts to the same security account for multicurrency setup.

**Comment by buchen** [comment]
I wonder: if you define a "filter" containing the 4 accounts, then you can select this filter for the XIRR widget on the dashboard.

If it was a "category" with these 4 accounts, where else would you want to see/use that?

**Comment by lsolesen** [comment]
@buchen I did not see that you could use the filters also as data series on the dashboard (must be my beginning blindness). That is brilliant - and worked perfectly. Then filters gets much more helpful especially when #1375 and #1523 are adressed, so it is possible to edit your currently saved filters - and those filters are saved and can be used between computers.

I think this issue and #1530 could be solved by filters, so it can be closed.
