### ISSUE TITLE
comdirect Dividendengutschrift in Fremdwährung

### ISSUE THREAD

**Issue by m-kro** [buchen/portfolio#1526]
Der automatische Import einer comdirect-Dividendengutschrift mit Dividende in CHF auf ein EUR-Konto schlägt mit folgender Meldung fehl:

_**Wechselkurs des Nettowertes fehlt [...]**_

Dieser wird derzeit tatsächlich nicht eingelesen, wenn ich https://github.com/buchen/portfolio/blob/3b3870e12b1da53465711f1210fdbad54a16c739/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/ComdirectPDFExtractor.java#L129 richtig deute. Leider steige ich noch nicht so ganz durch die Datenstruktur von PP durch, kann aber eine Beispieldatei zum Nachvollziehen zur Verfügung stellen (generiert über PP-Textextraktion):
[comdirect_Dividendengutschrift.pdf.txt](https://github.com/buchen/portfolio/files/4576411/comdirect_Dividendengutschrift.pdf.txt)

**Comment by inv-trad** [comment]
Das Thema wurde bereits in der Community diskutiert:

https://forum.portfolio-performance.info/t/import-der-steuerbuchung-von-comdirect-funktioniert-nicht/5156/11

und 

https://forum.portfolio-performance.info/t/comdirekt-steuern-werden-nicht-uebernommen/2330/2

Es gibt scheinbar zwei Dokumente:
    Dividendengutschrift_XXX.pdf
    Steuermitteilung_XXX.pdf

Und wenn ich das Coding richtig verstehe, sollte die Steuermitteilung alle Informationen für die Berechnung der Steuern inkl. Quellensteuer enthalten. Gibt es das Steuerdokument in jedem Fall oder kann es auch vorkommen, dass es nicht zugestellt wird, wenn keine inländische Steuer aber die Quellensteuer anfällt?

**Comment by m-kro** [comment]
Danke für den Hinweis. Ich bin noch recht neu bei PP und habe nur auf Github vorher danach gesucht. 

Zu der Frage: Ich nehme an, dass das Steuerdokument immer erstellt wird. Zum Beispiel wird auch bei wegen des Freistellungsbetrag 0€ einbehaltener Steuer ein Dokument erstellt (Summe vor = Summe nach Steuern).
