### ISSUE TITLE
trade republic PDF Import Sparplan

### ISSUE THREAD

**Issue by hanno-0** [buchen/portfolio#1531]
Hallo,
ich glaube trade republic hat für die Ausführungsabrechnung, genannt 'ABRECHNUNG AUSFÜHRUNG N' des Sparplans die Beschreibung für den Kurs beim Kauf geändert.

Hier die Auszüge aus meinen ABRECHNUNGS AUSFÜHRUNGEN vom 04.05. und vom 16.04.

**ausgeführt am 04.05.**
POSITION ANZAHL DURCHSCHNITTSKURS BETRAG
iShsIII-Core MSCI World U.ETF 5,1038 Stk. 48,98 EUR 250,00 EUR

**ausgeführt am 16.04.**
POSITION ANZAHL KURS BETRAG
iShsIII-Core MSCI World U.ETF 5,1855 Stk. 48,211 EUR 249,9981 EUR

Bei Aktienkäufen ist natürlich weiterhin der 'KURS' im PDF angegeben.

Könnte beim Import zusätzlich zu 'KURS' auch 'DURCHSCHNITTSKURS' erkannt werden? Da sonst der Import einen Fehler ausgibt.

Besten Dank und viele Grüße,
Hanno

**Comment by inv-trad** [comment]
Siehe Pull Request 1533: https://github.com/buchen/portfolio/pull/1533
