### ISSUE TITLE
Trade Republic

### ISSUE THREAD

**Issue by ackount** [buchen/portfolio#1532]
PDF Autor: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
<XXXXXX> SEITE 1 von 1
<XXXX> DATUM 04.05.2020
<XXXX>AUSFÜHRUNG 81XXXXcfa
SPARPLAN bcXXXXf
DEPOT 1XXXXX1
WERTPAPIERABRECHNUNG SPARPLAN
ÜBERSICHT
Sparplanausführung am 04.05.2020 an der Lang & Schwarz Exchange.
Der Kontrahent der Transaktion ist Lang & Schwarz TradeCenter AG & Co. KG.
POSITION ANZAHL DURCHSCHNITTSKURS BETRAG
iShsIII-Core MSCI World U.ETF 1,4290 Stk. 48,98 EUR 70,00 EUR
Registered Shs USD (Acc) o.N.
ISIN: IE00B4L5Y983
GESAMT 70,00 EUR
BUCHUNG
VERRECHNUNGSKONTO VALUTA BETRAG
DEXXXXXXXXXX5 06.05.2020 -70,00 EUR
iShsIII-Core MSCI World U.ETF Registered Shs USD (Acc) o.N. in Wertpapierrechnung.
Lagerland: Republik Irland
Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.
Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie 
Leistung.
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Ingo Hillen
10435 Berlin USt-ID DE307510626 Karsten Müller
ABRE / 2020-05-04 / 61066314 / 2d32-b91a

**Comment by Ragas13** [comment]
Es geht doch nichts über aufschlussreich E
#1531

**Comment by inv-trad** [comment]
Siehe Pull Request 1533: https://github.com/buchen/portfolio/pull/1533
