### ISSUE TITLE
CSV Depotimport verbreitert 1. Spalte auf Fensterbreite

### ISSUE THREAD

**Issue by hupfdule** [buchen/portfolio#1536]
Hallo,

Beim Import einer CSV-Datei werden alle Spalten zuerst korrekt dargestellt.
Nach Änderung des Datentyps oder der Anzahl zu überspringender Zeilen, wird die 1. Spalte auf die Fensterbreite verbreitert. Mein erster Eindruck war, dass die restlichen Spalten verschwunden wären. Tatsächlich waren sie nur nicht mehr sichtbar.
Siehe die folgenden Screenshots direkt nach dem öffnen und nach Umstellung des Datentyps.

![CSV Import nach dem Öffnen](https://user-images.githubusercontent.com/36069345/81689241-645ceb00-945a-11ea-986a-6731af27f5ca.png)

![CSV Import nach Umstellung Datentyp](https://user-images.githubusercontent.com/36069345/81689284-6c1c8f80-945a-11ea-894d-4690c346aa9a.png)

Genutzt habe ich Portfolio Performance 0.46.3.

**Comment by cmaoling** [comment]
@hupfdule I think this is reported again here https://github.com/buchen/portfolio/issues/1723.
I created is a workaround/hack to fix this, the merge of the PR is pending.
FYI @buchen

**Comment by buchen** [comment]
Fixed.
