### ISSUE TITLE
PDF-Import Consorsbank Vorabpauschale schlägt fehl

### ISSUE THREAD

**Issue by Algernon99999** [buchen/portfolio#1548]
Hallo zusammen,

vermutlich wird der PDF-Dokumententyp mit der Vorabpauschale der Consorsbank noch nicht unterstützt, von daher anbei ein Beispiel für eine Belastung des Kontos.

Zu erkennen am Textteil: "Netto zulasten..."

Idealerweise wird dann beim Erzeugen der Buchung beim Feld "Typ" entsprechend auch gleich "Vorabpauschale" eingetragen.

[VORABPAUSCHALE_123456789_wknA12GJD_dat20200127_id836349804.pdf.txt](https://github.com/buchen/portfolio/files/4635057/VORABPAUSCHALE_123456789_wknA12GJD_dat20200127_id836349804.pdf.txt)

Ich würde mich freuen, wenn das jemand bei der Importer-Funktion aufnehmen könnte!

Vielen Dank und viele Grüße
Gunnar

**Comment by inv-trad** [comment]
Ein erster Wurf ist in Pull Request #1549 implementiert, wobei der Typ Steuern verwendet wird.

**Comment by Algernon99999** [comment]
> 
> 
> Ein erster Wurf ist in Pull Request #1549 implementiert, wobei der Typ Steuern verwendet wird.

Das hört sich ja schon mal gut an!  👍 

Besten Dank, auch für das schnelle Kümmern!  :-)

**Comment by buchen** [comment]
@inv-trad - kann dieser Issue damit geschlossen werden?

**Comment by inv-trad** [comment]
@buchen - aus meiner Sicht schon.
