### ISSUE TITLE
Taxonomies : select "security account" in categories

### ISSUE THREAD

**Issue by cqst** [buchen/portfolio#1555]
Hi pp

Here is some improvement / feature request :

In taxonomies, would be usefull to be able to select "security account" in categories (like deposit account).

Use case : I have a taxonomy "by financial institution", some securities are common to several "security account" in different institution, so I can't see real amount in each "financial institution".

Being able to select "security account" in a category would solve these kind of problem.

Cheers and thx again for this awesome app

**Comment by Ragas13** [comment]
@cqst 
Personally I think your taxonomy is just a little bit overdone because this kind of selection is considered at the filter. At the filter you could select the individual security accounts.

**Comment by cqst** [comment]
No worry that’s a point of view :)
Actually I find it very useful to classify financial institution and know exactly which amount you have in each. 
Useful in France because we have some guarantee limit / tax limit, in case of bankruptcy, inheritage...so it gives a quick and accurate overview with a taxonomy by financial institution or contracts. 

I noted there was filtering available but it doesn’t fix this use case fully because it will be wrong with entire portfolio.

An other workaround could be duplicating security and buy or sell for a separate security account...not really clean anyway 

Giving the opportunity to select « security accounts » OR « securities » could satisfy every taxonomies cases in my opinion.

**Comment by buchen** [comment]
duplicate #1524

**Comment by buchen** [comment]
I get that feature request every once in a while. It is not easy to add to the existing structure of taxonomies, because it changes the way to calculate values. This is fairly big change.

What already works: put a number of accounts and securities accounts into a "filter". This filter can also be selected in dashboard widgets and added as data series to charts. So you could create filters, and then add the values to your dashboard. A little cumbersome.

> Useful in France because we have some guarantee limit / tax limit, in case of bankruptcy, inheritage...so it gives a quick and accurate overview with a taxonomy by financial institution or contracts.

Let's explore where you want to see the data. Maybe there are easier solutions. In the "statement of assets" because you can group by "financial institutions"? The pie charts?

**Comment by cqst** [comment]
Hi @buchen 

> What already works: put a number of accounts and securities accounts into a "filter". This filter can also be selected in dashboard widgets and added as data series to charts. So you could create filters, and then add the values to your dashboard. A little cumbersome.

It does the job indeed, creating as many filters as I need "by institution" but it doesnt give a "global view" because we have to switch to each filter or add taxonomy per institution with a specific filter applied to each (not that bad but still no global view)

> Let's explore where you want to see the data. Maybe there are easier solutions. In the "statement of assets" because you can group by "financial institutions"? The pie charts?

Actually I don't really care where to see it, I think in this use case all that matters is having a global view "by institution" or "by contract", that's why I thought taxonomies was the right place.
Statement of assets would be nice too but we still have to use filtering "by institution", impossible to have a global view.

Anyway I can understand if it involves big changes, it would be a "nice to have" but no big deal if you choose to close it ;)

**Comment by chirlu** [comment]
@cqst You can have that “global view” in a dashboard. You just need to add a widget for each institution and assign them different filters.

**Comment by cqst** [comment]
@chirlu thanks ! that's nearly perfect then :)
