### ISSUE TITLE
Project setup in Eclipse 

### ISSUE THREAD

**Issue by bcamel** [buchen/portfolio#1561]
I am using Eclipse Version: 2020-03 (4.15.0) and installed the required / recommended plugins as mentioned in README.MD.

Then set the target platform and am faced with an error in the project setup of `name.abuchen.portfolio.ui`:

> Project has only main sources but depends on project 'name.abuchen.portfolio.tests' which has only test sources.

I am not too familiar with OSGi (try to avoid it TBH), so maybe my guess is totally off. But I thought it might have sth. to do with this configuration in `MANIFEST.MF`:

```
Require-Bundle: com.ibm.icu,
 name.abuchen.portfolio;bundle-version="0.46.4",
 org.eclipse.nebula.cwt,
 org.eclipse.ui.forms
```

Yet it does not look like `name.abuchen.portfolio.tests` is picked up from there, because I would image that a dependency on the test project would need to be explicitly stated there. 

This is the result of Eclipse's plugin dependency view on `name.abuchen.portfolio.ui`

![image](https://user-images.githubusercontent.com/356990/82657742-287a1080-9c26-11ea-9e19-6e12657bba66.png)

**Comment by inv-trad** [comment]
Here is a little lightweight setup guide. Maybe that helps (German, but with a translation tool it should be understandable):
https://forum.portfolio-performance.info/t/verbesserungen-im-source-code-in-github-einbringen/7063/7

**Comment by bcamel** [comment]
Thank you for the link. This is basically what I did as well.

Now, I just switched to Eclipse 4.10 and the setup worked flawlessly. Maybe some issue with 4.15 ... I do not use Eclipse usually. 

Anyway, it works now. Vielen Dank!
