### ISSUE TITLE
PDF Import Consors seit 2001

### ISSUE THREAD

**Issue by thilo20** [buchen/portfolio#1579]
Der PDF-Import für Consorsbank funktioniert bei alten Dokumenten nicht.

Ich habe inzwischen ein PDF von 2001 erfolgreich importiert (inkl. Testcase und UI).

Besonderheit: 
- Bankname 'Consors' ist im extrahierten Pdf-Text nicht enthalten. 
- Pdf-Autor ist korrekt gesetzt (Pdf wurde kürzlich aus dem Consors-Archiv runtergeladen)

Status und Fortschritt hier:
https://github.com/thilo20/portfolio/commits/feature_importConsors2001

**Comment by Ragas13** [comment]
@thilo20 
Der zweite Commit würde die automatische Erkennung von PDF's verfälschen.

Du hast recht damit das die Erkennung via Author und BankIdentifier widersprüchlich ist, ich würde hier ansetzen um ggf. Abwärtskompatibel zu alten PDFs zu erhalten:

https://github.com/thilo20/portfolio/blob/f8cb4670e32215e3a06bdc2cff883adc2876c432/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/AbstractPDFExtractor.java#L145-L156

Ansonsten Pusche bitte deine Änderungen auf den Master von PP.

VG
Marco

**Comment by thilo20** [comment]
Hallo Marco,

 

mit dem PR werde ich noch etwas warten, bis ich passend dazu realisiert habe:

-          Deinen Hinweis

-          Verkäufe

-          Steuern

-          Test mit meinen 340 PDFs (ich vermute zwischen 2001 und 2015 ist viel passiert)

 

Danke für Deine schnelle und erfreuliche Rückmeldung :)

 

Viele Grüße, Thilo

 

Von: Ragas13 [mailto:notifications@github.com] 
Gesendet: Sonntag, 31. Mai 2020 11:39
An: buchen/portfolio <portfolio@noreply.github.com>
Cc: thilo20 <thilo.schaper@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [buchen/portfolio] PDF Import Consors seit 2001 (#1579)

 

@thilo20 <https://github.com/thilo20> 
Der zweite Commit würde die automatische Erkennung von PDF's verfälschen.

Du hast recht damit das die Erkennung via Author und BankIdentifier widersprüchlich ist, ich würde hier ansetzen um ggf. Abwärtskompatibel zu alten PDFs zu erhalten:

https://github.com/thilo20/portfolio/blob/f8cb4670e32215e3a06bdc2cff883adc2876c432/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/AbstractPDFExtractor.java#L145-L156

Ansonsten Pusche bitte deine Änderungen auf den Master von PP.

VG
Marco
