### ISSUE TITLE
TradeRepublic Document Import, Dividenden in USD nicht möglich

### ISSUE THREAD

**Issue by RonnyOs** [buchen/portfolio#1586]
Hallo,

ich habe Dividenden im Trade Republic Depot erhalten, dieses weist anfangs die Kosten in US aus und rechnet diese im Laufe des Dokuments in EURO um. PortfolioPerformance erkennt leider nur USD und bricht somit den Import ab.

Viele Grüße
Ronny

**Comment by inv-trad** [comment]
siehe auch Issue: https://github.com/buchen/portfolio/issues/1532
und Pull Request https://github.com/buchen/portfolio/pull/1570
