### ISSUE TITLE
Enhancement: Add "Tracking Difference" as additional attribute

### ISSUE THREAD

**Issue by programmdesign** [buchen/portfolio#1592]
As a user, I'd like to track the "Tracking Difference" (e.g. available here https://www.trackingdifferences.com/) in addition to the TER in order to track the real cost of my ETFs.

**Comment by Ragas13** [comment]
@programmdesign 
Vielleicht hilft dir das Alternativ:
https://forum.portfolio-performance.info/

**Comment by programmdesign** [comment]
@Ragas13: Danke. Das Feature war mir nicht klar. Ist damit gelöst.

**Comment by siprbaum** [comment]
Kann jmd erklären, wie man mit diesen Attributen das geforderte Feature abdeckt?
Das erschließt sich mir so ad hoc nicht wirklich!
