### ISSUE TITLE
Builds für ARM64 / aarch64

### ISSUE THREAD

**Issue by dtpnk** [buchen/portfolio#1595]
### Hintergrund
ich bin u.a. User eines ChromeOS Tablets / Notebooks mit ARM64 Architektur. Seit einiger Zeit kann man da ja auch Linuxprogramme installieren und ausführen. Natürlich würde ich dort gerne auch PP zum Laufen bringen.
"Paket runterladen -> Auspacken -> `PortfolioPerformance` ausführen" funktioniert da leider nicht, da das Binary scheinbar nur auf x86 Architekturen läuft. Alle Dependencies (openjdk8, libwebkit-3-x-x) sind soweit installiert.

### Frage
* Könntet ihr ein zusätzliches Paket für ARM64 / aarch64 Systeme bereitstellen?
* bzw. könntet ihr eine kurze Anleitung / Hilfestellung geben, wie man PP für solche Plattformen baut? (dann würde ich mich auch mal selbst heranwagen)

**Comment by dtpnk** [comment]
Ich habe direkt mal versucht PP auf dem Gerät selbst zu bauen.
Es scheint so als wenn die Tests fehlschlagen:

```bash
$ cd <PATH-TO>/portfolio/
$ docker run -it --rm --name my-maven-project -e MAVEN_OPTS="-Xmx1g" -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven arm64v8/maven:3.5.2-jdk-8 mvn clean verify -Dtycho.disableP2Mirrors --file portfolio-app/pom.xml

[...]

Tests run: 777, Failures: 0, Errors: 6, Skipped: 0

[INFO] ------------------------------------------------------------------------                                                          
[INFO] Reactor Summary:
[INFO]
[INFO] Portfolio Performance .............................. SUCCESS [  5.797 s]                                                          
[INFO] portfolio-target-definition ........................ SUCCESS [  0.523 s]                                                          
[INFO] name.abuchen.portfolio ............................. SUCCESS [17:30 min]                                                          
[INFO] name.abuchen.portfolio.tests ....................... FAILURE [01:29 min]                                                          
[INFO] name.abuchen.portfolio.ui .......................... SKIPPED
[INFO] name.abuchen.portfolio.ui.tests .................... SKIPPED
[INFO] name.abuchen.portfolio.bootstrap ................... SKIPPED
[INFO] name.abuchen.portfolio.feature ..................... SKIPPED
[INFO] portfolio.product .................................. SKIPPED
[INFO] ------------------------------------------------------------------------                                                          
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------                                                          
[INFO] Total time: 25:41 min
[INFO] Finished at: 2020-06-14T09:23:14Z
[INFO] Final Memory: 74M/513M
[INFO] ------------------------------------------------------------------------                                                          
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:1.5.1:test (default-test) on project name.abuchen.portfolio.tests:
There are test failures.
[ERROR]
[ERROR] Please refer to /usr/src/mymaven/name.abuchen.portfolio.tests/target/surefire-reports for the individual test results.           
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                                      
[ERROR] Re-run Maven using the -X switch to enable full debug logging.                                                                   
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:                                
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException                                                   
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command                                                         
[ERROR]   mvn <goals> -rf :name.abuchen.portfolio.tests
```

Irgend eine Idee, wie ich von hier weiterkomme? (sorry bin nicht so der Java-Crack)

**Comment by Ragas13** [comment]
@dtpnk 
Der Fehler liegt nicht an MAVEN oder Java, sondern entweder an der AARCH64 oder DOCKER Konfiguration. Nur hier bist du auf dich alleine gestellt  vielleicht hilft dir aber das?

https://forum.portfolio-performance.info/t/portfolio-performance-in-docker/6149

**Comment by dtpnk** [comment]
@Ragas13 :
Danke für die schnelle Antwort. 
Der Artikel behandelt eher wie man PP dockerisiert. Ich hab aber Docker für MAVEN - quasi als build environment genommen. Das sind 2 unterschiedliche paar Schuhe.
Braucht man denn eine bestimmte maven version zum Bauen?

**Comment by chrisaut** [comment]
Wenn nur die tests nicht laufen du die ja versuchen mal zu ignorieren, zumindest vorerst. Versuch mal die portfolio.tests aus der pom.xml unter modules raus zu nehmen.

**Comment by dtpnk** [comment]
@chrisaut 
Danke dir. Hat soweit funktioniert.
Ich kann aber keine Buildartefakte finden. Wo sollten die normalerweise sein?

```bash
[...]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Portfolio Performance .............................. SUCCESS [  6.192 s]
[INFO] portfolio-target-definition ........................ SUCCESS [  0.787 s]
[INFO] name.abuchen.portfolio ............................. SUCCESS [02:24 min]
[INFO] name.abuchen.portfolio.ui .......................... SUCCESS [ 40.955 s]
[INFO] name.abuchen.portfolio.bootstrap ................... SUCCESS [  2.362 s]
[INFO] name.abuchen.portfolio.feature ..................... SUCCESS [  0.368 s]
[INFO] portfolio.product .................................. SUCCESS [03:13 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:07 min
[INFO] Finished at: 2020-06-16T09:16:35Z
[INFO] Final Memory: 197M/592M
[INFO] ------------------------------------------------------------------------
```

**Comment by Ragas13** [comment]
@dtpnk 
Der run able part solute dann hier abgespeichert sein:
```[INFO] Installing product name.abuchen.portfolio.product for environment linux/gtk/x86 to /home/runner/work/portfolio/portfolio/portfolio-product/target/products/name.abuchen.portfolio.product/linux/gtk/x86/portfolio```

**Comment by buchen** [comment]
Hi @dtpnk,

PP verwendet Eclipse SWT GUI Bibliotheken die nativen Code nutzen. SWT unterstützt nur (noch) x86_64 (siehe [Target Platformen](https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_15.xml#target_environments)). Auch x86 wird nicht mehr unterstützt und aus diesem Grunde wird es bald auch keinen 32bit Version von PP mehr geben #1209.

Deine beste Chance ist mal nach "Eclipse Java IDE auf Chromebook" zu suchen. Auf [Quora](https://www.quora.com/Is-there-any-way-I-can-run-Java-Eclipse-on-my-Chromebook-so-that-it-s-just-like-the-Eclipse-environment-on-the-Windows-system-we-use-in-my-programming-class?share=1) habe ich ein paar Hinweise gefunden: Stichworte Crouton oder "un Linux applications via a virtual machine instance". Ich hoffe das hilft weiter.

**Comment by dtpnk** [comment]
HI @buchen,
danke für deinen Hinweis. Tatsächlich benutze ich schon die die Lösung von Google namens "Crostini", was unter der Haube auch nur LXC/LXD container in einer VM sind. Aus diesem Grund konnte ich ja auch Docker und maven im Container dort nutzen.
Tatsächlich ist das Problem, dass am Ende kein ARM64-binary "rauspurzelt".

Vielleicht ist es ja auch mal eine Überlegung wert das in Zukunft zu unterstützen? 
(Besonders wenn Apple damit liebäugelt in Zukunft auch CPUs auf ARM-architektur in den MacBooks zu verbauen) ;)

**Comment by buchen** [comment]
> Vielleicht ist es ja auch mal eine Überlegung wert das in Zukunft zu unterstützen?

Eclipse SWT ist ziemlich groß - das nicht zu stemmen. Und ARM auf dem Mac macht mir auch schon Sorgen weil SWT schon heute nicht mehr so aktiv weiterentwickelt wird. Andrerseits müsste ich das ganze GUI neu schreiben wenn ich SWT loswerden wollte...

**Comment by lmb** [comment]
Es scheint so als ob es Plaene gibt SWT auf arm64 macOS zu unterstuetzen: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690 Immerhin kein kompletter rewrite in diesem Fall ;)

**Comment by buchen** [comment]
@lmb zumindest für macOS wird dann Xcode wohl auch binaries für Apple silicon/arm64 produzieren. Ob und inwieweit dann andere OS davon profitieren kann ich nicht beurteilen

**Comment by pinpins** [comment]
Why was it closed actually?

**Comment by Ragas13** [comment]
@dtpnk 
> Why was it closed actually?

Reason was that PP depends on Eclipse and if and how they'll support this architecture.
