### ISSUE TITLE
Einlagen Wiederholungen ermöglichen

### ISSUE THREAD

**Issue by tsohst** [buchen/portfolio#1596]
* Auf mein Konto wird monatlich automatisch eine Summe überwiesen als Einlage
* Diese muss ich manuell jeden Monat verbuchen
* Bitte einen scheduler bereitstellen um automatisch Einlagen zu buchen 
    * täglich/wöchentlich/monatlichen/quartalsweise/jährlich, 
    * auch mit einem Ende versehen, das nach X Eintragungen der scheduler aufhört.
    * Einzelne Eintragungen des Schedulers editierbar machen, sollte sich der Wert in einem Monat ändern

**Comment by Ragas13** [comment]
@tsohst 
Du kannst Sparpläne für monatliche Einzahlungen verwenden. Der Bedarf an weiteren Zeiträumen müsstest du noch beim Investieren erläutern...
