### ISSUE TITLE
IZF Berechnung nach Update auf 0.46.4 defekt

### ISSUE THREAD

**Issue by schrchr** [buchen/portfolio#1606]
Nachdem ich auf 0.46.4 geupdated habe, funktioniert die IZF Berechnung bei mir nicht mehr. Das Widget zeigt einfach nichts an. Scheinbar hat es etwas mit den Dividenden zu tun (siehe Log)?

[pp-error-2020-06-21.log](https://github.com/buchen/portfolio/files/4810176/pp-error-2020-06-21.log)

**Comment by buchen** [comment]
Vielen Dank für das Log, @schrchr.

Ich denke ich habe das Problem gefunden. Welche Version brauchst Du um das zu testen? Windows 64bit?

**Comment by schrchr** [comment]
Ja, Windows 64bit

**Comment by buchen** [comment]
@schrchr - könntest du mal diese Version testen:
https://www.dropbox.com/s/3mx6stnog7jughm/PortfolioPerformance-distro-0.46.5-SNAPSHOT-win32.win32.x86_64.zip?dl=0

**Comment by schrchr** [comment]
Ja, die IZF Berechnung funktioniert wieder, jedoch zeigt er jetzt die folgende Warnung mehrmals an. Die entsprechenden Wertpapiere wurden an dem Datum verkauft.

!ENTRY name.abuchen.portfolio 2 0 2020-06-21 22:37:17.468
!MESSAGE Negativer Bestand während der FIFO Kostenberechnung. Bestand: -40 Wertpapier: Stock Datum: 15.01.2018

**Comment by buchen** [comment]
Könntest Du mir mal Deine Datei an *portfolio dot performance dot help at gmail dot com* schicken? Ggf. auch andere Wertpapiere löschen, aber nur so viel dass die Fehlermeldung weiter kommt. Damit ich mir das mal näher anschauen kann.

**Comment by buchen** [comment]
Hat sich erledigt. Ich kann das Problem auch bei mir sehen.
