### ISSUE TITLE
Anleitungstext nicht korrekt im PDF-Buchungsimport

### ISSUE THREAD

**Issue by fbuchinger** [buchen/portfolio#1608]
Aktuell (nicht korrekt):
_"Die unten stehenden Buchungen werden erstellt.
Entfernen Sie Buchungen mit Hilfe des Kontextmenüs"_

Ich habe vergeblich einen "Entfernen" Befehl im Kontextmenü gesucht. Mir war nicht klar, dass durchgestrichene Buchungen nicht importiert werden.

Korrekt:
_"Die unten stehenden Buchungen werden importiert, sofern sie nicht ~~durchgestrichen~~ sind.
Ändern Sie dies mit Hilfe des Kontextmenüs"_

Dieser Hinweise berücksichtigt, dass durchgestrichene Buchungen nicht importiert werden und Buchungen nicht aus der Liste gelöscht werden können (sind weiterhin sichtbar, wenn auch durchgestrichen).

![image](https://user-images.githubusercontent.com/287434/85234575-8c068200-b40e-11ea-96de-9c1921f80c49.png)

**Comment by inv-trad** [comment]
Wenn man auf eine nicht durchgestrichene Zeile geht, sieht das Kontextmenü anders aus und man erhält die Möglichkeit die Buchung nicht zu importieren.

![grafik](https://user-images.githubusercontent.com/59824809/86752274-87151580-c03f-11ea-9c52-ac4b3417f052.png)

Wie wäre es mit:
"Die unten stehenden Buchungen werden erstellt, sofern sie nicht durchgestrichen sind.
Änderungen können mit Hilfe des Kontextmenüs vorgenommen werden."

**Comment by fbuchinger** [comment]
Perfekt, danke!
