### ISSUE TITLE
Kontextmenü "Nach unten" schiebt Eintrag noch oben

### ISSUE THREAD

**Issue by Githki** [buchen/portfolio#1615]
In der Oberfläche "Einstellungen\Attribute: Wertpapiere" sorgt die Sortiermöglichkeit "Nach unten" via Kontextmenü für die Einträge in der Liste zum entgegengesetzten erwarteten Ergebnis. Die Sortiermöglichkeit "Nach oben" funktioniert wie erwartet. 

Version: 0.46.5 (Juni 2020)
Platform: win32, x86_64
Java: 11.0.4+11-LTS, Azul Systems, Inc.

**Comment by buchen** [comment]
Vielen Dank für die Fehlermeldungen!
