### ISSUE TITLE
Umbenennen einer Watchlist wird nicht ad-hoc angezeigt

### ISSUE THREAD

**Issue by Githki** [buchen/portfolio#1616]
Nach dem Umbenennen einer Watchlist wird der neue Name nicht direkt angezeigt. Bei einem erneuten Versuch die Watchlist umzubenennen wird nach dem ersten Versuch der korrekte Name angezeigt. 
Die Aktualisierung erfolgt erst nach dem Wechsel zu einer anderen Watchlist.

Version: 0.46.5 (Juni 2020)
Platform: win32, x86_64
Java: 11.0.4+11-LTS, Azul Systems, Inc.

**Comment by buchen** [comment]
😒 It works on macOS and Linux, but no on Windows. Not clear what is going wrong...
