### ISSUE TITLE
Feature: Interest CSV Import

### ISSUE THREAD

**Issue by debegr92** [buchen/portfolio#1618]
Topic from forum: https://forum.portfolio-performance.info/t/zinsgutschrift-aus-csv-importieren/2223/5

Basically add drop down entry for interest for CSV import wizard.

**Comment by Ragas13** [comment]
@debegr92 
This issue is obsolet as explained at https://forum.portfolio-performance.info/t/zinsgutschrift-aus-csv-importieren/2223/6. You have to assign the according Type, column header assigning the field values into each transaction per line item.
