### ISSUE TITLE
Watchlist: Zielkurs eingeben + Alert/farbliche Markierung

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#163]
> Ich hätte noch eine Idee für ein cooles Feature in der Watchlist: Ich würde es toll finden, wenn man bei jedem Wertpapier einen Zielkurs angeben könnte (beispielsweise den gewünschten Kauf- oder Verkaufskurs) und dann alle Wertpapiere nach der Differenz zwischen aktuellem Kurs und Zielkurs sortieren könnte, so dass man sofort erkennen kann, bei welchen Wertpapieren Handlungsbedarf besteht. Also ähnlich einer Art Kursalarm, allerdings nicht so, dass nur ein nerviges Popup erscheint, sondern dass man wirklich nur bei Bedarf nachsehen kann, welche Werte langsam interessant werden könnten. 

Aus dem Wertpapier Forum: http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__903411

**Comment by msschl** [comment]
Gibt es Neuigkeiten zu diesem Feature?

**Comment by buchen** [comment]
Siehe #1330
