### ISSUE TITLE
Erträge & Ausgaben -> Buchungen: Manche Filter falsch [bug]

### ISSUE THREAD

**Issue by burkart** [buchen/portfolio#1656]
Unter *Erträge & Ausgaben* wird bei *Buchungen* manchmal zu wenig gefiltert:

- *Steuern* zeigt zusätzlich Buchungen vom Typ *Zinsen* an
- *Gebühren* zeigt zusätzlich Buchungen vom Typ *Kauf* an

**Comment by Ragas13** [comment]
@burkart 
Wenn über Gebühren gesprochen wird, sind auf die angefallenen Gebühren bei Käufen relevant. Gleiches Spiel bei Zinsen, wenn mich nur Steuern interessieren.

Abgesehen von der Diskussion zur Anzeige von Gewinn/Verlust lässt sich hier kein Problem zu erkennen. Aber vielleicht kannst du einen Screenshot nachreichen wo das "Problem" sichtbar wird?

**Comment by burkart** [comment]
Ah, mein Fehler! Durch eine zufällig "passende" Anordnung von Buchungen unterschiedlicher Typen hatte ich fälschlicherweise angenommen, dass z.B. zu jeder Kauf-Buchung eine separate Gebühren-Buchung angelegt wurde. Tatsächlich macht Portfolio Performance hier alles richtig und blendet auch z.B. Kauf-Buchungen mit 0 EUR Steuern in der Steuern-Ansicht aus.

P.S.: Im Prinzip zeigt z.B. die Steuern-Ansicht alle Buchungen an, bei denen der Wert in der Steuern-Spalte ungleich Null ist. Beispielsweise Buchungen des Typs Steuern haben hier eine Null und die Steuerzahlung stattdessen in der Spalte Betrag. Man könnte der Einheitlichkeit halber den Wert stattdessen in der Steuern-Spalte anzeigen; ich kann mir aber vorstellen, dass das größere interne Umbauten an der Datenhaltung für einen kleinen kosmetischen Effekt bedeuten würde. Falls doch gewünscht, kann ich ein separates Issue incl. Screenshot anlegen.
