### ISSUE TITLE
Wertpapier-Sparplan ohne konfigurierten Kurslieferant --> Fantasiebestand

### ISSUE THREAD

**Issue by fbuchinger** [buchen/portfolio#1660]
Der Bug ist wie folgt nachstellbar:
1. Wertpapier anlegen, aber keinen Kurslieferant konfigurieren
2. Sparplan für dieses Wertpapier anlegen und Buchungen erstellen lassen

Erwartetes Verhalten:
Fehlermeldung "Kein Kurslieferant hinterlegt"

Aktuelles Verhalten:
Wertpapier wird mit Kurs 0,00 behandelt, bei einer festen Sparplansumme von 150 EUR ergibt das einen Fantasiebestand von -90290432230924... (irgendeine illusorisch hohe Zahl).

**Comment by cmaoling** [comment]
![image](https://user-images.githubusercontent.com/11899631/92715680-1a2f3c00-f35e-11ea-8e30-a3165449e5c7.png)
Create propsal to raise a WARNING...

**Comment by fbuchinger** [comment]
I like the idea of a warning in the investment plan dialog. But shouldn't
it be rather an error, that also disables the "save" button? Without quote
information, the investment plan won't be able to create correct bookings.

Am Do., 10. Sept. 2020 um 12:18 Uhr schrieb Colinas Maoling <
notifications@github.com>:

**Comment by cmaoling** [comment]
This is a question of definition IMHO.
You can fix the quotes in a different dialog, while the investment plan kind of is completely defined...
I first thought to disable the transaction generation. But this would be a lot of code and might cause confusion down the road...

**Comment by fbuchinger** [comment]
There are indeed multiple approaches how to deal with "quoteless" securities (no quote provider configured):

1) Hide them from the  Securities dropdown in the "New Investment Plan" Dialog

2) Just show a warning for those securities in the same dialog (as suggested by @cmaoling).

3) Show a warning and don't generate investment plan transactions for them

4) Turn the warning of 2) into an error and don't let the user confirm the dialog.

1), 2) and 4)  seem easier to implement, but have some usability flaws: 1) is not very intuitive, people will miss their securities in the dialog and don't know why they are hidden. 2) is a step in the right direction, but it's easy to confirm the dialog and forget about the warning. 4) forces the users to abort and do all the work again because they forgot to configure a provide.

I would prefer solution 3) (warning in dialog + don't generate transactions if the quotes cannot be fetched). This has the benefit that we don't create bogus transactions if quotes cannot be fetched for any reason (no internet, quote provider outage,  quote provider not configured). But the warning proposed by @cmaoling is definitely a step in the right direction.

**Comment by buchen** [comment]
> I would prefer solution 3) (warning in dialog + don't generate transactions if the quotes cannot be fetched).

Yes, that makes totally sense. I have now added code that is displaying a warning if the user explicitly starts the generation of transactions from the UI. If the transaction is auto-generated after opening the file, then the error message is printed to the log only.
