### ISSUE TITLE
Performance calculation

### ISSUE THREAD

**Issue by mestrode** [buchen/portfolio#1681]
I have some problems with the performance calculation: Looks like there is some issue in between the combinations of

Did some testing with a empty bank account
starting on 1.01.2020 with a saldo of [+/-] 100 €
than having 4 quarters each 1 € of [credit interest / borrow rate] (dates: 01.03. 01.06. 01.09. 01.12)

x | 1 | 2 | 3 | 4
--- | --- | --- | --- | ---
Starting | 100€ | -100€ | 100€ | -100€
4x interest | 1€ | 1€ | -1€ | -1€
saldo | 104€ | -96€ | 96 € | -104€
TTWRR | 2% | -2% | -2% | 2%
IZF | 3,47% | -3,47% | -3,47% | 3,47%

doing this again but starting with an additional transaction on 31.12.2019 with [+/-] 1€ doesn't have an effect 

x | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
--- | --- | --- | --- | --- | --- | --- | --- | ---
1st transaction | 1€ | 1€ | 1€ | 1€ | -1€ | -1€ | -1€ | -1€
Starting | 100€ | -100€ | 100€ | -100€ | 100€ | -100€ | 100€ | -100€
4x interest | 1€ | 1€ | -1€ | -1€ | 1€ | 1€ | -1€ | -1€
saldo | 105€ | -95€ | 97€ | -103€ | 103€ | -97€ | 95 € | -105€
TTWRR | 1,98% | -2,02% | -1,98% | 2,02% | 2,02% | -1,98% | -2,02% | 1,98%
IZF | 3,43% | -3,49% | -3,38% | 3,05% | 3,50% | -3,38% | -3,47% | 3,43%

But shouldn't the TTWRR and the IZF be independend of the saldo sign, but have the same sign like the interests?

**Comment by buchen** [comment]
To be honest, I do not fully understand your sample data.
**For what time period do you calculate the IZF / TTWRR?**
Keep in mind that the calculation may not include future values (it is only August 2020).

If you have build a sample XML file, could you can attach it to this issue.

> But shouldn't the TTWRR and the IZF be independend of the salso, but have the same sign like the interests?

If you have no other deposits/removal/inbound or outbound deliveries, I tend to agree.

**Comment by mestrode** [comment]
Ohh, your right! No calculation with data beyond the current date.
For the calculation of IZF / TTWRR I selected the period since 01.01.2020 until today.

BUT, I guess it was to late for me yesterday...

Tried to show the issue in a some more understandable kind.
Now the transaction are done within the period from 01.01.2019 until 01.12.2019.
Report for IZF / TTWRR should be the whole Year 2019 (I saw this seemed to be 31.12.2018 until 31.12.2019 - please double check, if this is by intention if I select a whole year. Shouldn't it start on 01.01.2019?)

Here my prepared example (remind the adjusted file-suffix for upload)
[1.xml.txt](https://github.com/buchen/portfolio/files/5010160/1.xml.txt)
Please take a look on the four accounts. And then review the prepared performance dashboard, please.
The data should represent something equivalent to thy first table, I send in my initial post.

**Comment by mestrode** [comment]
additional hint:
if I add a transaction on 01.06.2019 with a value of 100€
The monthly return shows irregular values.
[2.xml.txt](https://github.com/buchen/portfolio/files/5011353/2.xml.txt)
