### ISSUE TITLE
import justtrade pdf documents does not work

### ISSUE THREAD

**Issue by lliinnaarrtt** [buchen/portfolio#1686]
Import of justtrade pdf documents does not work.
I will added an modified pdf example into the attacthments.
[justrade_example_12.08.2020.PDF](https://github.com/buchen/portfolio/files/5061680/justrade_example_12.08.2020.PDF)

**Comment by Ragas13** [comment]
@lliinnaarrtt 
Dear Artur,

modification of an PDF is destroying the structure who PP is parsing. Please post the content as tollows:


## [Und andere PDF Dokumente?](#andere-dokumente)

Andere Dokumente können im Source Code hinzufügen werden. Wer sich daran versuchen möchte, schaut sich z.B. den [Importer für die Deutsche Bank](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DeutscheBankPDFExtractor.java) an. Ansonsten kann ich - wenn Zeit und Muße vorhanden ist - auch Dokumente hinzufügen. Dazu braucht es den Text:

* Im Menü "Datei" -> "Importieren..." -> "Debug: Text aus PDF extrahieren..." den Text aus der PDF Datei generieren
* Gegebenenfalls private Informationen wie Namen, Anschrift oder genaue Buchungswerte ändern. Dabei aber unbedingt darauf achten, dass man keine neuen Zeilen, keine Zeilenümbrüche, oder Leerzeichen oder ähnliches einfügt.
* Neuen [Github Issue](https://github.com/buchen/portfolio/issues/new) mit dem Text anlegen oder hier im Forum posten. Beim Posten im Forum bitte den Text in drei Backticks (```) einschließen, so dass die Formatierung nicht verändert wird.

**Comment by lliinnaarrtt** [comment]
```PDF Autor: ''
PDFBox Version: 1.8.16
-----------------------------------------
justTRADE
Ein Service der Sutor Bank
JT Technologies GmbH
Kaiserhofstraße 16
Herr 60313 Frankfurt am Main
Max Mustermann Email: service@justtrade.com
Musterstraße 17 Web: www.justtrade.com
12345 Musterstadt
Name des Kunden: Max Mustermann
Kontonummer: 123456789
WERTPAPIERABRECHNUNG
Sehr geehrter Herr Max Mustermann,
dieses Dokument ist eine Bestätigung der Transaktion, die wir in Ihrem Namen durchgeführt haben.
Bei Fragen oder im Falle einer fehlerhaften Abrechnung wenden Sie sich bitte an den justTRADE -
Kundenservice. Sie finden die Kontaktdetails im Briefkopf dieser Abrechnung.
Der Gegenwert der Transaktion wird per Valutatag gebucht.
Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.
Produktbezeichnung - VANGUARD FTSE ALL-WORLD UCITS ET
Wertpapierhändlername: justTRADE
Internationale Wertpapierkennnummer (ISIN): IE00B3RBWM25
Währung: EUR
Handels-/Ausführungsplatz: DUSD
Handelsreferenz: 123456789012345678901234
Orderausführung Datum/Zeit: 1 Jul 2020 16:08:10
Valutatag Datum: 5 Jul 2020
Transaktionsart: Kauf
Kurs: €77,3700
Stück/Nominale: 10,00
Kurswert: €773,70
Ausmachender Betrag: €773,70
MAX HEINR. SUTOR OHG TELEFON 040-8090685-0 GESCHÄFTSLEITUNG FINANZAMT HAMBURG AMTSGERICHT HAMBURG
HERMANNSTRASSE 46 TELEFAX 040-8090685-810 ROBERT FREITAG STNR: 2761000074 HRA 25379
20095 HAMBURG THOMAS MEIER UST-IDNR: DE155617009
POSTFACH 11 33 37 INFO@SUTORBANK.DE BANKLEITZAHL 202 308 00
20433 HAMBURG WWW.SUTORBANK.DE BIC CODE: MHSBDEHBXXX```

**Comment by lliinnaarrtt** [comment]
I am using following Version: 0.47.0 (Juli 2020)

**Comment by lliinnaarrtt** [comment]
Error Message:
![2020-08-12 21_02_23-Buchungen aus PDF-Dateien importieren](https://user-images.githubusercontent.com/59148161/90056439-2aacb200-dcdf-11ea-8ec5-82be29c76fad.png)

**Comment by lliinnaarrtt** [comment]
Based on my understanding new justtrade pdf format was implemented in commit 23465215970fe8af8315d830fd578f71ba94901a (https://github.com/buchen/portfolio/commit/23465215970fe8af8315d830fd578f71ba94901a).
Nevertheless it doesn't work for me.

**Comment by lliinnaarrtt** [comment]
maybe TradeRepublicPDFExtractor is missing in PDFImportAssistant.java?

extractors.add(new TradeRepublicPDFExtractor(client));

**Comment by Ragas13** [comment]
That's not the root cause as the file format is different/not able to parse even w/ TradeRepublic

**Comment by lliinnaarrtt** [comment]
Sorry for the typo:
maybe JustTradePDFExtractor is missing in PDFImportAssistant.java?

**Comment by Ragas13** [comment]
https://github.com/buchen/portfolio/blob/e2d701d10c6a7a2f26b1135681a6f06a5f5778d0/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/PDFImportAssistant.java#L53

**Comment by Ragas13** [comment]
I got it, change proposed 👍

**Comment by lliinnaarrtt** [comment]
Hi,
I was able to validate the fix without issues.
Any idea when it will pushed into master and released?
Kind regards

**Comment by buchen** [comment]
Hi @lliinnaarrtt, I have merged the change now. My rough plan is to release a new version end of August.
