### ISSUE TITLE
JSON API Flexibility (Binance Quotes)

### ISSUE THREAD

**Issue by metal450** [buchen/portfolio#1692]
I’m trying to include some of my crypto holdings, which are supported the Kucoin exchange but not by the software’s two built-in exchanges (Bitfinex & Kraken). I figured I could do this by using PP’s JSON provider option, with Kucoin’s API (https://docs.kucoin.com/#get-24hr-stats). As an example URL:

https://api.kucoin.com/api/v1/market/stats?symbol=OCEAN-ETH 1

However, there are two problems that I don't believe can be solved given PP's current JSON setup:

1. Many of KuCoin’s currencies don’t have a pairing with USD - i.e. OCEAN only pairs ETH, so then this needs to be in turn translated by ETH-USD for the sake of showing holdings as their USD equivalents. Is there any way to handle that in the software currently?  If not via direct UI, by myself coding up a plugin/extension? (Apologies if this is listed - it's a bit difficult to navigate the documentation, as it's all in German).  If this isn't possible - I'd file something like it as a feature request, as I think it's a pretty common scenario in the crypto world.
2. Even for currencies that KuCoin’s API does provide a direct pairing with USD (for instance https://api.kucoin.com/api/v1/market/stats?symbol=BTC-USDT 1), Portfolio Performance seems to require a „date“ (per https://translate.google.de/translate?hl=&sl=de&tl=en&u=https%3A%2F%2Fhelp.portfolio-performance.info%2Fkursdaten_laden%2F%23json ). From the API’s link, you can see that it provides a unix epoch timestamp. I haven’t been able to figure out anything in „path to date“ & „path to close“ that makes this work.

Thanks in advance for any thoughts

**Comment by buchen** [comment]
**About 1: conversion ETH - USD**

At the moment, cryptocurrencies are not true currencies in PP (as EUR or USD are). Plus one cannot add arbitrary new currency labels at the moment. Even if I changed that, PP is currently only working with 2 decimal places for monetary amounts which will not work for cryptocurrencies (security holdings have 6 decimal places). Alas, not easy to fix/improve.

The fastest way probably is to have your own quote provider for kucoin that - internally - knows that to load and apply ```ETH-USDT``` as well. I probably can build something like this. But let me first understand the API. Is there a "historical data series" API. Your samples only show the current snapshot.

**About 2: unix epoch timestamp**

PP will try the "date" property as regular ISO date, but also as unix epoch timestamp.
For me, the server just returns one data set (e.g. the JSON has no array of values), but I am able to retrieve one data point.

<img width="485" alt="Bildschirmfoto 2020-08-20 um 08 48 28" src="https://user-images.githubusercontent.com/587976/90726415-f7ab8500-e2c1-11ea-9818-7901109c890a.png">

**Comment by metal450** [comment]
>> cryptocurrencies are not true currencies in PP

Yeah - I think treating cryptos as securities is the right way to go anyway, as that's more reflective of how they're used & traded.

>> Is there a "historical data series" API. Your samples only show the current snapshot.

I looked through their API docs and wasn't able to find one :/  Still, pulling a current price each time the app runs is much better than nothing :)  https://docs.kucoin.com/#get-24hr-stats

An alternative possibility could be Binance (which is by far the largest - https://coinmarketcap.com/rankings/exchanges/). Here's their API: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#current-average-price.  It'd have the same issues though, where many currencies are only paired against ETH or BTC, rather than USD.

>> unix epoch timestamp

Ah, cool, I guess that one works then! :)  In truth I didn't dig *too* deeply in the date thing, as I knew the pairings issue would preempt everything.

>> security holdings have 6 decimal places

As a related side note - it would be GREAT if the UI could display all 6 places (when working with crypto, I always need to hover over them one at a time to see the full number of shares, as even these small decimals are pretty consequential with things like BTC).  Mentioned in #1459

Thanks! :)

**Comment by metal450** [comment]
Looking into it a bit more, if you would consider adding support for another crypto exchange, I think Binance would have the most benefit.  It definitely seems to have the most trading pairs overall.

**Comment by metal450** [comment]
Is there anything I could do to somehow help get Binance and/or Kucoin working?

**Comment by Drkmstr310** [comment]
I'd also really really like to see Binance support. My holding values are never correct, because most cryptos aren't supported by the current few providers (even some top10 cryptos, like PolkaDot).

Binance would cover most cryptos (+ Kucoin would fill in even more of gaps).

**Comment by metal450** [comment]
So I thought I had a great slution for this - https://nomics.com/docs/ is an API that's free for current quotes (historical quotes aren't, but latest quote is at least sufficient to have accurate current balances).  Using JSON with settings:

URL: https://api.nomics.com/v1/currencies/ticker?key=(yourkey)&convert=USD&interval=1d&ids=OCEAN
Path to date: $.[*].price_date
Path to close: $.[*].price

Manages to pull the latest price (i.e. it shows it there on that dialog):

![2020-12-19 20 56 24](https://user-images.githubusercontent.com/1877409/102705437-c9708e80-423c-11eb-99a6-3873883fca2b.png)

However, it never actually updates the quote.  Even if I explicitly right click the security->quotes->update quote online, it doesn't pull the quote.  What might be wrong - it's definitely showing the correct value in that dialog, so I'd expect it to also be able to download...?

**Comment by metal450** [comment]
I was able to solve this with a different API: CryptoCompare.  The settings I'm using i.e. for OCEAN Protocol are:

Feed URL: https://min-api.cryptocompare.com/data/v2/histoday?fsym=OCEAN&tsym=USD&limit=30
Path to Date: $.Data.Data[*].time
Path to Close: $.Data.Data[*].close

Since they provide quotes for essentially every coin & token, it seems like this pretty much alleviates the need for any exchange-specific settings.  Thus, closing this request :)
