### ISSUE TITLE
macOS Big Sur: list content won't change

### ISSUE THREAD

**Issue by trkit** [buchen/portfolio#1709]
**Describe the bug**
When viewing a list-like element in the main window followed by demanding a similar view by changing the original element you viewed in the list, the content of the list won't change.

**To Reproduce**
1. Go to "Alle Wertpapiere"
2. Click on Stock A
3. View the overview lists, like "Umsätze" of Stock A
4. Click on Stock B

**Expected behavior**
Expected behaviour would be, that when clicking ob Stock B, the list "Umsätze" would change to the list content of Stock B. Though, the former content of Stock A "Umsätze" is still shown.

**Screenshots**
This is a "dynamic" bug. Screenshots won't add more info

**Desktop (please complete the following information):**
 - OS: macOS 11.0 Beta (20A5354i) "Big Sur"
 - Version 0.48

**Comment by buchen** [comment]
I'll have to see how to trouble shoot these issues because I realized that my laptop does not support Big Sur anymore.

**Comment by pat-s** [comment]
> I'll have to see how to trouble shoot these issues because I realized that my laptop does not support Big Sur anymore.

Happy to help with logs / other useful information. Unfortunately I have no idea of Java to issue PRs myself.

I've recognised multiple glitches in Big Sur and would be grateful to help.

**Comment by dbussink** [comment]
As an additional datapoint, resizing the window forces a reflow and results in updated content. So maybe there's something wrong that refreshes are not always properly triggered when changing selections?

**Comment by trkit** [comment]
I can confirm that re-sorting columns also triggers a refresh.

If the new view, however, has N less rows then the last one, there will be N hanging rows which are not removed while the others are updated.

Am 03.11.2020 um 19:35 schrieb Dirkjan Bussink <notifications@github.com>:

﻿

As an additional datapoint, resizing the window forces a reflow and results in updated content. So maybe there's something wrong that refreshes are not always properly triggered when changing selections?

**Comment by buchen** [comment]
It seems to be fixed with the latest Eclipse build. I just tested it on a different Big Sur machine. I plan to provide a special build for Big Sur users soon.

**Comment by trkit** [comment]
Great news!

Am 21.11.2020 um 21:21 schrieb Andreas Buchen <notifications@github.com>:

﻿

It seems to be fixed with the latest Eclipse build. I just tested it on a different Big Sur machine. I plan to provide a special build for Big Sur users soon.

**Comment by buchen** [comment]
Can you give this version a try: https://github.com/buchen/portfolio/releases/download/0.49.2/PortfolioPerformance-0.49.3.bigsur.dmg

**Comment by trkit** [comment]
First, thank you so much Andreas for tackling these Big Sur issues which seemed quite nasty on the dev side, too.

Praising `aria2c -x 16` dowloads for GitHub releases - otherwise you wouldn’t get a feedback tonight.

This build looks very promising so far - will now check out the individual issues and them back individually.

Am 22.11.2020 um 21:11 schrieb Andreas Buchen <notifications@github.com<mailto:notifications@github.com>>:

https://github.com/buchen/portfolio/releases/download/0.49.2/PortfolioPerformance-0.49.3.bigsur.dmg

**Comment by trkit** [comment]
I can confirm, that this issue #1709 is fixed. Tried to reproduce like described in the initial report - Lists of "Wertpapiere" now switch as desired when selecting between different assets.

Expected behaviour with release `*0.49.3.bigsur` is fulfilled: 

- When clicking ob Stock B, the list "Umsätze" changes to the list content of Stock B.

**Comment by trkit** [comment]
@buchen I have reviewed and fed back the Big Sur related bugs and issues. These seem all to be successfully addressed. However, I did not intensively test for new bugs. This might be the case in around one week when reviewing my financials for November.

**Comment by dbussink** [comment]
> As an additional datapoint, resizing the window forces a reflow and results in updated content. So maybe there's something wrong that refreshes are not always properly triggered when changing selections?

Can confirm that the new build doesn't seem the have the refresh problems for me and that content does get properly updated now.

**Comment by trkit** [comment]
Have to report that this issue here as well as #1710 is back for regular version, after reporting in #1779 that it was temporarily fixed - came back with upgrading to 0.49.3.

Please refer to #1710 for more details like Installation Details report.
