### ISSUE TITLE
On Startup: "NoClassDefFoundError: TableTreeItem"

### ISSUE THREAD

**Issue by StegSchreck** [buchen/portfolio#1717]
**Describe the bug**
After starting up, the application shows a dialogue window containing the error and the portfolio data is not visible.

**To Reproduce**
1. Start Portfolio Performance
2. Wait until error is displayed (see screenshot below)
3. No data of the portfolio is displayed

A click in graph sections (e.g. `Berichte > Vermögensaufstellung > Diagramm`) works, but table-like sections (e.g. `Stammdaten > Konten`) does yield the error described above.

**Expected behavior**
Application starting up without errors, displaying the portfolio data.

**Screenshots**
![image](https://user-images.githubusercontent.com/9078002/91887003-77eec480-ec8a-11ea-8186-29556711eb7f.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version 0.47.0 (Jul 2020)
   - Platform: linux, x86_64
   - Java: 25.262-b10, Oracle Corporation

**Comment by Ragas13** [comment]
@StegSchreck 
This might could happen as the basic Eclipse framework were updated. If you're download the latest version from the homepage to replace your local installation, is the problem still available?

**Comment by StegSchreck** [comment]
Reinstalling `portfolio-performance-bin-0.47.0-1` from aur initially solved the issue. the in-app update to 0.48.0 broke everything again. now, nothing shows up, just an empty wnidow

**Comment by StegSchreck** [comment]
> @StegSchreck can you provide the log? It should be at `~/.PortfolioPerformance/workspace/` as a hidden file `.log`.
> 
> I tested PP 0.48.1 on Ubuntu 20.04 LTS. But something is strange.
> 
> Maybe #1727 is connected: Do you have **libgtk-3-0** installed?

I have `extra/gtk3 1:3.24.22-1` and `extra/gtk2 2.24.32-2` installed.

I attached the `.log` and `.bak_0.log` from `~/.PortfolioPerformance/workspace/.metadata`:
[.log](https://github.com/buchen/portfolio/files/5176032/default.log)
[.bak_0.log](https://github.com/buchen/portfolio/files/5176033/default.bak_0.log)

**Comment by buchen** [comment]
@StegSchreck The log file looks inconclusive to me. It contains a lot of "no actual value was found for the argument" messages from the dependency injection framework. It is not really clear to why this is failing.

```
org.eclipse.e4.core.di.InjectionException: Unable to process "CustomStackRenderer.preferences":
no actual value was found for the argument
"IEclipsePreferences[@org.eclipse.e4.core.di.extensions.Preference(nodePath=org.eclipse.e4.ui.workbench.renderers.swt, value=)]".
```

Can you try deleting the workspace fold ```~/.PortfolioPerformance/workspace``` and then starting PP again.

If that is not helping, can you provide the "installation details" (Help -> About Portfolio Performance -> installation Details)

**Comment by StegSchreck** [comment]
What I have already 

tried was to move that folder away and reinstalling PP. This did not help unfortunately.

I cannot access the menu as PP only shows a blank window frame.
![image](https://user-images.githubusercontent.com/9078002/92300947-8e816e00-ef5f-11ea-8e3f-3b4687542e2f.png)

I added the current workspace (after the steps mentioned above) as an archive here:
[workspace.tar.gz](https://github.com/buchen/portfolio/files/5177747/workspace.tar.gz)

**Comment by DonRichie** [comment]
I would also like to contribute my logs. 

On Arch Linux I did the following:
1. removed ~/.PortfolioPerformance completely
2. reinstalled portfolio-performance-bin
3. opened PortfolioPerformance and opened my xml file
4. got errors

This logfile is the result:
[log.txt](https://github.com/buchen/portfolio/files/5177977/log.txt)

**Comment by StegSchreck** [comment]
Today, I got the update to 0.48.1 via `aur` and it seems to work fine again. Therefore, I'm closing this issue.
