### ISSUE TITLE
Version 0.48.0 shows always one caption less than colors present in asset diagramm

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#1718]
**Describe the bug**
Since version 0.48.0 the diagramm for the asset diagram (in the German version: Vermögensaufstellung -> Diagramm) show one caption less than colors are present in the diagram.

**To Reproduce**
1. Start PortfolioPerformance with the main window visible. Do not maximize the window.
2. Open the tab "Welcome"
3. Click on "Open the Kommer example file"
4. Click onto "Statement of Assets" -> "Chart"
5. Count the caption below the diagram (should be four) and also click and hold in the diagram and count the captions there (should also be four).
6. Maximize the window and repeat step 5.

**Expected behavior**
Below the diagram there should be four captions.

**Observed behavior**
Below the diagram are only three captions. When click and hold in the diagram all four captions are shown.
It looks like there is a line break for the captions which makes the fourth invisible.

**Screenshots**
![Portfolio Performance _029](https://user-images.githubusercontent.com/25621029/91906876-2f92cf00-eca9-11ea-9bb5-66899260652a.jpg)

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu 18.04.5 LTS
 - Version: 0.48.0 (Aug 2020)
Platform: linux, x86_64
Java: 25.265-b01, Private Build

**Comment by buchen** [comment]
Thanks you very much for the detailed error description!

Fixed with 44dabdc8acc64a91e3528f8e67e3bb377ff4c144
