### ISSUE TITLE
CSV Import Spalten außerhalb des Fensters nach Wechsel zu Komma

### ISSUE THREAD

**Issue by debegr92** [buchen/portfolio#1723]
Datei -> Importieren -> CSV

Zu Beginn nach Dateiauswahl:
![01](https://user-images.githubusercontent.com/4254744/92010984-bcda3000-ed4a-11ea-93de-67e0c43fa3c5.png)
Nach Wechsel zu Komma:
![02](https://user-images.githubusercontent.com/4254744/92011000-c06db700-ed4a-11ea-8515-571f0bb15337.png)

Warum ist Komma nicht als Standard ausgewählt? Warum landen die Spalten außerhalb, wenn ich das Trennzeichen ändere?

**Auffallend**
Nur die erste Spalte wird extrem breit. Der Rest passt wieder.

**Lösung**
Fenster muss größer gezogen werden und die erste Spalte wieder verkleinert werden.

**Comment by buchen** [comment]
> Warum ist Komma nicht als Standard ausgewählt?

Im Deutschen sind CSV Dateien üblicherweise mit einem Semikolon getrennt (siehe z.B. Excel) weil das Komma für die Beträge benötigt wird. Ich belege das je nach Sprache mit Komma oder Semikolon vor.

> Warum landen die Spalten außerhalb, wenn ich das Trennzeichen ändere?

Das scheint ein Bug unter Linux zu sein.
Unter macOS kann ich das Problem nicht nachstellen.
Ich nehme den "hack" von @cmaoling auf damit sich das unter Linux besser verhält.

**Comment by debegr92** [comment]
Die Spalten werden nun neu skaliert, jedoch kommt das "Update" erst, wenn ich das Fenster skaliere. Da bekommt die Tabelle dann ihr Update und wird korrekt angezeigt.
Ich hoffe das ist verständlich.
