### ISSUE TITLE
Bondora Import bei Einzahlungen über 1.000€

### ISSUE THREAD

**Issue by DominikHolzapfel** [buchen/portfolio#1726]
Im Kontoauszug von Bondora Go&Grow werden Einzahlungen über 1.000€ mit einem Tausender-Punkt dargestellt. Der aktuelle RegEx fängt das nicht ab und erstellt dann eine Einzahlung z.B. über nur 1€

**Comment by gimpfenlord** [comment]
Der Bug tritt bei mir immer noch auf.
Aus 3200€ werden 3,20€

**Comment by DominikHolzapfel** [comment]
Hallo, da ich kein entsprechendes PDF habe und der Fehler bei mir nicht auftritt, vermute ich ein Lokalisationsproblem (Tausender-Trennzeichen deutsch/englisch).
Ich würde mal darauf tippen, dass der Fehler nicht mehr auftritt, wenn der Kontoauszug von Bondora auf deutsch erstellt wird.

**Comment by gimpfenlord** [comment]
Nein der Kontoauszug ist auf deutsch.

Hier mal ein Screenshot aus der Abrechnung
![image](https://user-images.githubusercontent.com/12447074/152873432-b5e146e8-6f94-4c1b-be3f-16c48894aeec.png)

**Comment by DominikHolzapfel** [comment]
Tut mir leid, da kann ich so auf die Schnelle nicht helfen. Der Code hat sich seitdem auch etliche Male geändert.
Am besten das Issue hier wieder öffnen (falls möglich) oder ein neues erstellen und am besten den Debug Text-Auszug aus dem PDF gleich mit anhängen (bereinigt um persönliche Daten).
