### ISSUE TITLE
Import of PDF documents via drag and drop does not work anymore

### ISSUE THREAD

**Issue by gregorko** [buchen/portfolio#1740]
When dragging and dropping a PDF file into Portfolio Performance a import dialog should be displayed. 

Click on "Alle Wertpapiere".
Open a Windows Explorer. Select a PDF and drag and drop it into "Alle Wertpapiere" table.

As far as I remember since 0.46.2 it should display the import dialog. This is not working anymore with 0.48.1.
It only shows a crossed circle symbol. I also tried to drop into other views without success.

 - OS: Windows
 - Version 0.48.1

**Comment by buchen** [comment]
I do not seem to be able to reproduce it - at least on macOS.

For me, the drag and drop import starts when
* dragging into the side navigation, or
* into the table of securities under "all securities" ("Alle Wertpapiere")

I have to check once I get to a Windows machine. If somebody develops on Windows, it would be helpful if you could debug.

**Comment by gregorko** [comment]
I just tried again to make sure... and I have to say I'm sorry... I'm also not able to reproduce the problem. Not sure why it didn't work when I tried the last time... Maybe it had something to do with the update? It was the first start after the update from 0.47
