### ISSUE TITLE
ISINs starting with QS are (sometimes) deemed invalid

### ISSUE THREAD

**Issue by dariottolo** [buchen/portfolio#1761]
**Describe the bug**
My (Italian) pension funds have ISINs starting with QS. I tried to add them to the security and PP does not accept most of them saying they are invalid, except for QS0000003564

**To Reproduce**
1. Go to 'Securities', 'All Securities'
2. Right Click on any security and choose 'Edit'
3. Paste QS0000003562 in the ISIN field
4. Error "Invalid ISIN: ISIN"

**Expected behavior**
If you add the ISIN QS0000003564 it is strangely accepted, QS0000003560, QS0000003561, QS0000003562 and QS0000003563 are considered invalid. I expect to be able to add them as ISINs.

**Screenshots**
![pp](https://user-images.githubusercontent.com/23664193/94037283-7ca82380-fdc5-11ea-96ab-45387b86a366.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 0.48.1

**Comment by buchen** [comment]
Hi @dariottolo,

I pasted the ISIN numbers to https://www.isindb.com/validate-isin/ and indeed they are reported as invalid.

Of course, PP could relax the check and just report a warning instead of an error.
Or we could say: if it is an non-standard country code ("QS") then apply no checks.

However, I wonder why your pension fund as invalid ISINs. Are they using them for internal purposes only? Are those really traded?

**Comment by dariottolo** [comment]
Hi Andreas,

the funds are not traded. I contribute monthly (purchase shares depending on my paycheck) and I will receive the accumulated amount once I retire. 

The ISINs are listed on [their website](https://www.secondapensione.it/SecondaPensione/Ricerca-quote) and on Italian [newspaper](https://finanza.repubblica.it/Fondi/Scheda/FA.100001899/320/). The strange thing is that one (QS0000003564) is considered valid while all the others not.

I thought about adding it in order to facilitate the import of the quotes. There are no sources and I have to do it manually, but they are updated twice a month, so it's not a real big deal.

If I may make a suggestion, the warning might be better, because it would allow me to add the value, that might be invalid, but I am sure it is correct (from the issuer point of view). The second solution would also work for me.

In any case, I am fine if you prefere leaving the things as they already are.

Thanks a gain for your time.

Dario

**Comment by bountin** [comment]
The ISINs are probably considered invalid because their check digit is wrong. 

In addition, QS seems to be an invalid start of an ISIN. I don't have access to the ISO document but the BCL is quoting it as the following:
> the two first digits must correspond toa valid country code (ISO 3166)at the date of  issue of  the security  or  toEU, XA,  XB,  XC,  XD  and XS. In  particular, a  code whosethetwo first digits are DU, EV, HF, HS, QS, QT, QU, QY, TE, XF, XX, ZZ is not considered as a valid ISIN code.

(see http://www.bcl.lu/en/Regulatory-reporting/Vehicules_de_titrisation/Instructions/TPTTBS/TPTTBS_L1_VER_EN.pdf, p. 6)

I have no clue why this Italian financial institution is using them (in public) but to me it looks invalid and some kind of hack.

**Comment by Ragas13** [comment]
Just for the files:

Since June 30, 2003, Euroclear France has been issuing interim dummy ISINs in accordance with ISO 6170, which begin with “QS”.

ISINs that begin with the code "XS" mostly refer to bonds that are held in custody with Clearstream or Euroclear.

**Comment by dariottolo** [comment]
> I have no clue why this Italian financial institution is using them (in public) but to me it looks invalid and some kind of hack.

The firm managing the funds is Amundi, which is a quite known French Asset Manager... I do not think they are invalid, maybe not being traded, there is no need to actually have a "real" ISIN.

> Since June 30, 2003, Euroclear France has been issuing interim dummy ISINs in accordance with ISO 6170, which begin with “QS”.

This might be an explanation, being the Asset Manager French...

**Comment by buchen** [comment]
> I do not think they are invalid

"invalid" in this discussion means the [checksum digit](https://rosettacode.org/wiki/Validate_International_Securities_Identification_Number) is wrong.

We can relax the ISIN check and do not calculate the checksum for ISIN numbers starting with "QS" (and the other non-valid codes as commented by @bountin). Instead we print a warning message.

In the end, PP is not "doing" anything with the ISIN other than matching imported transactions to securities. Therefore I see the argument that it should still be possible to maintain such a ISIN.
