### ISSUE TITLE
MacOS Scrollen in Tabellen total unflüssig

### ISSUE THREAD

**Issue by Fabioni** [buchen/portfolio#1774]
**Describe the bug**
In allen Tabellen die im Programm verkommen, zum Beispiel "Alle Buchungen" ist das Scrollen fürchterlich ruckelnd und dadurch richtig unangenehm. Es schränkt außerdem die usability ein in größeren Listen etwas zu finden oder umzusortieren. Bei Windows funktioniert es. Das Problem ist glaube ich, dass bei Windows einfach Zeile für Zeile gescrollt wird, was zwar ein bisschen altmodisch wirkt aber flüssig geht und bei Mac dieses kontinuierliche Scrollen verwendet wird, was eben überhaupt nicht funktioniert. 

**To Reproduce**
1. Go to Alle Buchung
2. Scroll Down and Up

**Expected behavior**
Flüssiges kontinuierliches Scrollen oder Zeilenweises Scrollen wie bei Windows.

**Screenshots**
Auf Nachfrage kann ich Videos machen

**Desktop:**
 - OS: macOS Catalina 10.15.7
 - Hardware: Mac Book Pro 2019

**Comment by Ragas13** [comment]
@Fabioni 
Was passiert den wenn du A) das [Workspace-Verzeichnis](https://help.portfolio-performance.info/installation/) löschst und B) PP erneut von der Homepage herunter lädst und mit dieser Version arbeitest?

**Comment by Fabioni** [comment]
> @Fabioni
> Was passiert den wenn du A) das [Workspace-Verzeichnis](https://help.portfolio-performance.info/installation/) löschst und B) PP erneut von der Homepage herunter lädst und mit dieser Version arbeitest?

Den Workspace Folder zu löschen hat nichts geändert. Ich hatte bereits die aktuelle Version 0.48.1 (Sep. 2020), daher habe ich nichts neu herunter geladen. Hätte ich es trotzdem machen sollen?

**Comment by Ragas13** [comment]
Support macOS Big Sur (10.16) #1621

**Comment by buchen** [comment]
Ich habe jetzt auch - endlich - Big Sur auf meinem Rechner.
Bei mir scrollt die Tabelle okay. Ich glaube es ist kein *Big Sur* Issue. Es ist ein Issue wenn die Tabelle besonders groß ist. Da könnte eine "lazy data loading" helfen.

**Comment by Fabioni** [comment]
es ginge mir nie um Big Sur, ich habe Catalina gehabt als ich das Problem hatte, wie aus meinem Eröffnungspost zu entnehmen ist.
Ich habe nun gerade Big Sur installiert und siehe da, das Problem ist weg :D
Big Sur war also nicht das Problem, sondern die Lösung bei mir :-)
