### ISSUE TITLE
macOS Big Sur: Can't import csv file

### ISSUE THREAD

**Issue by Plorenzo** [buchen/portfolio#1779]
**Describe the bug**
A gray overaly is displayed after double clicking the imported csv columns to assign a type. After the overlay appears nothing is clickable or editable enymore. The only thing to do to move on is use ESC key. 

**To Reproduce**
1. Go to File -> Import -> CSV Files
2. Choose the desired csv file to import from files system. 
3. Pop up with csv data will appear. 
4. Double click where it says _Double click here_
5. Mapped to Field pop up appear and screen becomes gray. 
6. App becomes unusable.  

**Expected behavior**
I expect to be able to assign a type to each of the columns and finish the csv import without issues. 

**Screenshots**
<img width="1920" alt="Screenshot 2020-10-11 at 10 31 34" src="https://user-images.githubusercontent.com/4695692/95668950-1edd4f00-0bad-11eb-8b5f-ef33f74b09da.png">

<img width="1920" alt="Screenshot 2020-10-10 at 17 13 02" src="https://user-images.githubusercontent.com/4695692/95651465-37058d80-0b1d-11eb-8d44-42a6e456afe9.png">

**Desktop (please complete the following information):**
- MacBook Pro (15-inch, 2016)
 - OS: macOS Big Sur version 11.0 Beta (20A5384c)
 - Version: 0.48.1 (Sep 2020)

**Comment by Ragas13** [comment]
@Plorenzo 
Just a quick question, the drop down input field is not able to choose at the appearing dialog "Mapped to field"?

**Comment by Plorenzo** [comment]
Hi @Ragas13, when the overaly appears, I can't click anything anyome, so the dropdown menu is never displayed.

**Comment by Ragas13** [comment]
@Plorenzo 
Sehr eigenartig, wenn ich es nicht besser wüsste so würde ich ein Fehler in der bei dir lokal eingerichten Workspace-Verzeichnis und/oder dem PP-Programmverzeichnis vermuten.

Was passiert den wenn du A) das [Workspace-Verzeichnis](https://help.portfolio-performance.info/installation/) löschst und B) PP erneut von der Homepage herunter lädst und mit dieser Version arbeitest?

VG
Marco

**Comment by Ragas13** [comment]
@Plorenzo 
I apologise that I've wrote previously in German language.

The gray overlay is not issued by PP themselves so I assume that the used Eclipse Java engine could be the root cause. What happed if you're deleting the golder **~/Library/Application Support/name.abuchen.portfolio.product/workspace** and downloading and using the latest version from the homepage?

**Comment by Plorenzo** [comment]
No worries :) thanks for the suggestion. 

I just tried it, the behaviour is the same.

**Comment by Ragas13** [comment]
#1621

**Comment by Plorenzo** [comment]
Still happening in version 0.49.0

**Comment by Plorenzo** [comment]
Not happening anymore in Version: 0.49.2 (Nov 2020)
Big Sur version 11.0.1

**Comment by buchen** [comment]
Can you give this version a try: https://github.com/buchen/portfolio/releases/download/0.49.2/PortfolioPerformance-0.49.3.bigsur.dmg

**Comment by trkit** [comment]
I can confirm, that this issue #1779 is fixed. Tried to reproduce like described in the initial report, importing a CSV without the described issue.

Expected behaviour with release *0.49.3.bigsur is fulfilled:

- I am able to a type to each of the columns.

**Comment by Plorenzo** [comment]
@buchen tried it, looks like is working correctly. It also looks like it fixes #1710

**Comment by trkit** [comment]
@buchen there's something odd, regular version does now also work on BigSur for me. Either the BigSur build fixed some GUI library in the system, or my latest BigSur build fixed the GUI libraries itself. However, we should check out if this occurs for others, too, so we maybe do not need a specialized build.

**Comment by buchen** [comment]
> regular version does now also work on BigSur for me

Can you share the "installation details" of your regular version? About PP -> Installation Details

**Comment by Plorenzo** [comment]
closing this as it doesn't happen anymore.
