### ISSUE TITLE
Heatmaps are empty on Linux

### ISSUE THREAD

**Issue by bllngr** [buchen/portfolio#1790]
**Describe the bug**
Starting with version 0.49, heatmaps don't show anything anymore on Linux. It worked with earlier versions. No system changes have been done other than updating PP.

See also this topic: https://forum.portfolio-performance.info/t/heatmap-widgets-funktionieren-nicht-mehr/11443

**Screenshots**

![Screenshot_20201025_163747](https://user-images.githubusercontent.com/303458/97111822-26d6dc00-16e1-11eb-9bb1-6e0eb86bf3af.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 32, 64-bit
 - KDE Plasma 5.20.0
 - Version 0.49.0, 64-bit

**Comment by bitwave** [comment]
Can confirm.

**Comment by yetipenguin** [comment]
I can confirm this problem.

**Comment by gerrit8143** [comment]
same problem here

Debian Bullseye
Mate Desktop 1.24.1

**Comment by debegr92** [comment]
MeToo
![Uploading heatmap.png…]()

**Comment by bitwave** [comment]
The white is not white, but old screen/framebuffer contents. 

![2020-10-28_16-38](https://user-images.githubusercontent.com/1345784/97459360-fc348f80-193b-11eb-94ee-330280333089.png)

here you can see my Desktop background...

**Comment by bllngr** [comment]
All right, thanks everyone. I think we have enough confirmations. :) If you are affected, please cast your vote in the report (first comment). Further "me too" comments are probably not required.

**Comment by buchen** [comment]
Fixed. Thanks for your patience!

I will publish an updated version later today
