### ISSUE TITLE
PDF-Import - #Comdirect - Verwahrungsentgeld

### ISSUE THREAD

**Issue by ThBexx** [buchen/portfolio#1791]
Ist es möglich eine Erweiterung des PDF Imports für die Comdirect Bank zu integrieren? Automatisches hinzufügen einer Gebühr/Verwahrungsentgeld für das Wertpapier "Xetra Gold, WKN A0S9GB"

**PDF Autor: ''
PDFBox Version: 1.8.16**
-----------------------------------------
comdirect bank AG, 25449 Quickborn 977 13 010
Herrn Telefon: 04106 - 708 25 00
Telefax: 04106 - 708 25 85
E-Mail: www.comdirect.de/kontakt
(E-Mail über Kontaktformular)
Kundennummer: 
Abrechnung Verwahrentgelt Xetra Gold, WKN A0S9GB 06.01.2020
5DBR0154
Sehr geehrter Herr xy,
für die Verwahrung Ihres Wertpapieres Xetra Gold, WKN A0S9GB, berechnen wir pro Monat ein
Entgelt von 0,0298 % (0,025 % zzgl. 19 % MwSt.) auf Ihren Wert in der Gattung.
Die Buchung von 0,01 Euro für den vorherigen Monat erfolgte über das Abrechnungskonto für
Ihre Wertpapiergeschäfte.
Alle Informationen zu unseren Produkten und Services finden Sie unter www.comdirect.de
Mit freundlichen Grüßen
comdirect bank AG
Henning Ratjen
Leiter Service
comdirect bank AG
Pascalkehre 15
25451 Quickborn Vorstand: Frauke Hegemann (Vorsitzende), Dietmar von Blücher, Matthias Hach
(AG Pinneberg HRB 4889) Vorsitzender des Aufsichtsrates: Dr. Jochen Sutor

**Comment by ThBexx** [comment]
Ich habe das Ticket fälschlicher Weise als bug gekennzeichnet. Leider (oder Gott seid dank) habe ich keine Berechtigung das Label zu ändern. Es ist wohl mehr eine Erweiterung.

Mich schreckt die Einrichtung der Entwicklungsumgebung etwas ab. Um die Entwickler zu unterstützen poste ich meinen Vorschlag für die regular expression.

^.*Verwahrentgelt (?<name>.*),.*WKN (?<wkn>\\S*) (?<date>\\d+.\\d+.\\d{4}).*$
^.*Buchung von (?<fee>\\d.*,\\d+) (?<currency>\\w*) .*$

**Comment by fmms** [comment]
This is a duplicate of #1487 . Thanks for fixing this!
