### ISSUE TITLE
Monthly earnings visualization

### ISSUE THREAD

**Issue by arcataurus** [buchen/portfolio#1793]
With release 0.49 you can no longer read the numbers in the monthly dividend widget with more than three digits

![Image 2](https://user-images.githubusercontent.com/11029966/97273312-79281200-1833-11eb-8581-6d66255537cc.jpg)

**Comment by uok** [comment]
have you tried increasing the column size?

**Comment by arcataurus** [comment]
it works, thanks!!!

**Comment by pfalcon** [comment]
@arcataurus: Perhaps, close this ticket then?
