### ISSUE TITLE
Durchschnitt monatliche Erträge / Average monthly earnings

### ISSUE THREAD

**Issue by uok** [buchen/portfolio#1795]
Bitte beim Widget "Monatliche Erträge" eine Spalte mit "Ø Durchschnitt" (wie Jahressumme) hinzufügen.
Danke!

Please add a column "Ø average" (like yearly sum) to the "monthly earnings" widget.
Thanks!

**Comment by buchen** [comment]
Thanks to @inv-trad  for implementing it. It is merged. Will come with the next version.
