### ISSUE TITLE
Hyperlinks not readable in "About" section with dark mode enabled

### ISSUE THREAD

**Issue by m-terlinde** [buchen/portfolio#1803]
**Describe the bug**
If you go to the PP settings and have the dark mode enabled, hyperlinks in the about section are not readable.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the PP settings, select dark mode and apply
2. Go to "Help" and select "About Portfolio Performance"

**Expected behaviour**
Hyperlinks should be readable, maybe a different white colour than the text?

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10097313/97926021-b5db9800-1d62-11eb-94ef-79b3b897ae37.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.49.1

By the way you have a spelling mistake in the issue template. It should be "behaviour" instead of "behavior".

**Comment by Ragas13** [comment]
> By the way you have a spelling mistake in the issue template. It should be "behaviour" instead of "behavior"
American and British typo is different 😉

**Comment by m-terlinde** [comment]
Oh wow, you are right!
Thanks for enlighten me. Once learned in school, never questioned ;).

Am 3. November 2020 16:02:40 MEZ schrieb Ragas13 <notifications@github.com>:
>> By the way you have a spelling mistake in the issue template. It
>should be "behaviour" instead of "behavior">
>American and British typo is different 😉 >
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/buchen/portfolio/issues/1803#issuecomment-721182768

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by buchen** [comment]
Fixed.
