### ISSUE TITLE
Performance dashboard looses some colour it tabbed out

### ISSUE THREAD

**Issue by m-terlinde** [buchen/portfolio#1805]
**Describe the bug**
When the dark mode is enabled, switching the focus to an other app causes the performance dashboard to loose some colour.

Sorry for all the issues I've opened.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable dark mode
2. Go to the performance dashboard
3. Enable some widgets with red/green colouring (e. g. TTWROR)
4. Open a different app and switch context to it (e. g. ALT + Tab, or in my case have a second display and simply click on it)
5. Switch back to PP
6. Almost all red/green colouring is lost, except for "Trade Count"

**Expected behaviour**
The red/green indicators should stay, even if PP is out of focus.

**Screenshots**
Before:
![grafik](https://user-images.githubusercontent.com/10097313/97927759-e7a22e00-1d65-11eb-9539-f8af9542738b.png)

After:
![grafik](https://user-images.githubusercontent.com/10097313/97927777-f2f55980-1d65-11eb-8cde-14a90cf177b0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.49.1

**Comment by buchen** [comment]
> Sorry for all the issues I've opened.

Don't worry. 😄 What a strange error... it also happens on macOS. Let's go debugging

**Comment by buchen** [comment]
Found it. Strange side effect of CSS styling...

**Comment by m-terlinde** [comment]
Thanks a lot!
