### ISSUE TITLE
unable to import bank pdf Comdirect bank

### ISSUE THREAD

**Issue by RandyStardust** [buchen/portfolio#1810]
**Describe the bug**
Error says the bank pdf document is not a supported file

**To Reproduce**
1. Go to 'File/Import/PDF-Bankdocument'
2. Click on 'PDF-Document'
3. Navigate to PDF-document on local drive

**Expected behavior**
PP will import the file and set the action (purchase or sell) accordingly. 
![Screenshot 2020-11-04 163408](https://user-images.githubusercontent.com/73953202/98131483-97d57b00-1ebb-11eb-903f-1b5b056e3551.png)

**Screenshots**

**Desktop (please complete the following information):**
 - windows 10 pro
 - Version 10.0.18362 Build 18362

**Comment by Ragas13** [comment]
Duplicate with #1807

**Comment by RandyStardust** [comment]
sorry I'm new on here. 

is there a solution jet or does it mean that somebody else has raised the same error and it is not jet resolved?

 

thanks

 
 

Gesendet: Mittwoch, 04. November 2020 um 16:47 Uhr
Von: "Ragas13" <notifications@github.com>
An: "buchen/portfolio" <portfolio@noreply.github.com>
Cc: "RandyStardust" <andreas.defren@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [buchen/portfolio] unable to import bank pdf Comdirect bank (#1810)


 

Duplicate with #1807

**Comment by Ragas13** [comment]
No worries, there was already a bug recently opened belonging to yor topic. Root cause is the recently applied changes of the bank identifier. It will be updated soon.

**Comment by buchen** [comment]
Fixed. I will publish a version later today
