### ISSUE TITLE
Sortierung in Kassifizierungen

### ISSUE THREAD

**Issue by Nirus2000** [buchen/portfolio#1816]
**Describe the bug**
Die Sortierungen der z.b. Klassifizierungen in den Wertpapieren ist unübersichtlich.

**To Reproduce**
1. Alle Wertpapiere
2. Klassifizierungen

**Expected behavior**
Sortierung der Wertparpierart, Branchen, Region etc. absteigend nach _Gewichtung_ .

**Screenshots**
![Wertpapierart](https://user-images.githubusercontent.com/45203494/98463857-d53d4f80-21be-11eb-88ba-b8de0f66c8c4.jpg)
![Branchen](https://user-images.githubusercontent.com/45203494/98463860-d9696d00-21be-11eb-97c7-601d0681ea8a.jpg)
![Regionen](https://user-images.githubusercontent.com/45203494/98463866-e0907b00-21be-11eb-852a-8649cdd597db.jpg)

**Desktop (please complete the following information):**
 - Windows 10 64bit
 - Version 0.49.2

**Comment by buchen** [comment]
Hi @Nirus2000,

Die Sortierung sollte genau der Reihenfolge entsprechen wie sie in den Klassifikationen angelegt ist.

Stimmt das bei Dir nicht?


<img width="827" alt="Bildschirmfoto 2020-11-08 um 13 19 30" src="https://user-images.githubusercontent.com/587976/98464742-1df80700-21c5-11eb-91b2-30b69290903e.png">

**Comment by Nirus2000** [comment]
Das habe ich auch erst gedacht, aber leider nicht. 
Besser wäre jedoch eine Sortierung nach _Gewichtung_ im Wertpapier selber. Die Sortierung in den Klassifizierungen sind i.O.

Anbei als Image meine Sortierung in den Klassifizierungen zu denen im Wertpapier
![Branchen](https://user-images.githubusercontent.com/45203494/98465256-4f260680-21c8-11eb-8d10-0e51431edd30.jpg)
![Regionen](https://user-images.githubusercontent.com/45203494/98465258-51886080-21c8-11eb-8095-a9443c13482e.jpg)

**Comment by Nirus2000** [comment]
Im übrigen ist mir gerade aufgefallen, dass die Codierung mit Sonderzeichen nicht stimmt.
![UTF Problem](https://user-images.githubusercontent.com/45203494/98465338-c196e680-21c8-11eb-83d4-eb204e3aaafb.jpg)

**Comment by buchen** [comment]
Okay, jetzt habe ich es verstanden.

Ich habe von der Sortierung **innerhalb** der Dropbox gesprochen.
Du von der Sortierung wenn ein Wertpapier mehreren Kategorien zugeordnet ist.

Das schaue ich mir an
