### ISSUE TITLE
Wrong and inconsistent performance calculation for part of a portfolio

### ISSUE THREAD

**Issue by chirlu** [buchen/portfolio#1817]
In versions 0.46.4, 0.46.5, and 0.46.6 (at least), tweaks were made to the way transactions are collected into trades (FIFO). Since that time, performance calculations for *parts* of a portfolio have been broken, if there are any securities that were transferred between accounts.

Example:
![performance calculation, for a whole portfolio (correct) and filtered (broken)](https://www.wertpapier-forum.de/uploads/monthly_2020_08/Screenshot_mit_Depotwechsel.png.1d911225bf57ab22569aaafdf95f096f.png)
As you can see, the second calculation in that image (marked red) does not add up; the final value (Endwert) is too high by 1551,00.

This example was provided by user *Birke* at wertpapier-forum.de, who also made available the corresponding portfolio file (dax_mit_depotwechsel.xml) [here](https://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/?do=findComment&comment=1335916).

The bug also got mentioned on the forums repeatedly ([most recent example](https://forum.portfolio-performance.info/t/performance-berechnung-falsch-rendite-berechnung/4718/5)).

In addition to a fix for this particular issue, I think it would be generally useful if the performance calculation always cross-checked itself, by summing up the starting value, gains etc. and comparing the result to the final value, which should match; an error should be displayed whenever there is an inconsistency.

**Comment by buchen** [comment]
Thanks to @inv-trad this one is now fixed. I will create a new release later today.
