### ISSUE TITLE
Delay update popup until after password entry

### ISSUE THREAD

**Issue by danielb42** [buchen/portfolio#1820]
Hi! When a .portfolio is encrypted, the update announcement popup should be delayed until there is no more password entry screen active. What just happened to me is that it popped up while I was entering my password. The popup ...

- steals the focus
- (possibly receives key presses that might uncheck the auto update checkbox?)
- on "Return" key to complete password input: executes the update download/installation

**Comment by buchen** [comment]
It has happened to me as well 😞 
I can certainly decide at that point in time to not open the dialog, but it is not so easy to delay opening the dialog. Let me see if I come up with an idea

**Comment by danielb42** [comment]
Does it really need to be a surprise popup? You could just display "update available!" (bright, blinking, whatever) at the bottom of the left sidebar. There it can sit and wait until the user actively clicks it, then pop up the dialog with changelog, action buttons etc.
