### ISSUE TITLE
Widget Quick-Tips

### ISSUE THREAD

**Issue by Nirus2000** [buchen/portfolio#1821]
**Describe the bug**
Quick-Tip im Widget -> Erträge -> Monatliche Erträge wird zu groß dargestellt und die Währung fehlt.
Quick-Tip im Widget -> Heatmap -> Jahresrenditen -> Mauszeiger über "Xgeom" oder "Gesamtportfolio"
Quick-Tip im Widget -> Heatmap -> Monatsrenditen -> Mauszeiger über "Monate" gehen

**To Reproduce**
1. Performance
2.1. Neues Widget -> Erträge -> Monatliche Erträge
2.2 Neues Widget -> Performance-> Monatsrenditen in einer Heatmap
2.3 Neues Widget -> Performance-> Jahresrenditen in einer Heatmap

**Expected behavior**
Der Quick-Tip sollte "Autosize" sein und der Betrag in einer Währung angezeigt werden.

**Screenshots**
![Widget mtl Quicktip](https://user-images.githubusercontent.com/45203494/98527799-bbae0d80-227b-11eb-9918-1271f54ef41b.jpg)
![Heatmap](https://user-images.githubusercontent.com/45203494/98668441-2fb9e580-2350-11eb-9d0e-008e0609b244.jpg)
![Heatmap2](https://user-images.githubusercontent.com/45203494/98668749-99d28a80-2350-11eb-80c6-1b3ec9d90f90.jpg)
**Desktop (please complete the following information):**
 - Windows 10 64bit
 - Version 0.49.2

**Comment by buchen** [comment]
Thanks. fixed.
