### ISSUE TITLE
Sector/ Industry Allocation Chart

### ISSUE THREAD

**Issue by kerner1000** [buchen/portfolio#1828]
To support proper diversification, it would be nice to be able to generate a chart, that shows a portfolio's allocation by sector and/ or industry.

I imagine a pie chart, displaying the total holdings value of each stock as a percent value.

**Comment by Ragas13** [comment]
@kerner1000 
This feature is already available, please check out the according taxonomy function.

**Comment by kerner1000** [comment]
Awesome! Unfortunately, ABBV and  GILD seem to be in all taxonomies "without classification". Do I need to set those manually somehow?
