### ISSUE TITLE
Exception launching the Eclipse Platform

### ISSUE THREAD

**Issue by nappy** [buchen/portfolio#1829]
I receive an exception during startup:

```
!SESSION Thu Nov 19 14:36:19 CET 2020 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2020-11-19 14:36:19.248
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
```

**To Reproduce**
1. choco uninstall portfolio
2. choco install portfolio
3. Launch application
4. See error dialog

**Expected behavior**
The program should start after clean install without exceptions. If there are certain assumptions about the environment, the error should indicate what the program is missing from the environment it runs in.

**Desktop**
 - OS: Windows
 - Version v0.49.2

**Comment by Ragas13** [comment]
@nappy 
As this error is causing at an independent project please contact the responsible developer:
https://chocolatey.org/packages/portfolio

**Comment by buchen** [comment]
@SebRut Something wrong with the choco package?

**Comment by SebRut** [comment]
The chocolatey package simply downloads the latest zip file from the website and unzips it, so this error message sounds kinda weird as long as nothing changed on Portfolio Performance's side.
Unfortunately I've switched to arch linux for most of my day to day stuff, so I'm not sure when I'll be able to check this out.

**Comment by nappy** [comment]
If I replace everything in the installation folder with the contents of the zip file, I still get the error, so its something about the environment, I am not even sure if its reproducible or whether its related to chocolatey. If I start from the same extracted directory on the desktop though, it works.
