### ISSUE TITLE
macOS dark mode: Comment field is barely visible

### ISSUE THREAD

**Issue by cgolde** [buchen/portfolio#1841]
**Describe the bug**
Comment field for new deposits is bad to see under with Macos with dark mode enabled.

**To Reproduce**
1. Go to 'accounts'
2. Right click on account e.g. 'Tagesgeld' from example portfolio and select add new deposit.
3. See error

**Expected behavior**
Comment (de 'Notiz') field should have a border to be easier visible.

**Screenshots**
<img width="589" alt="Bildschirmfoto 2020-11-24 um 08 29 48" src="https://user-images.githubusercontent.com/9364454/100207452-e2b94000-2f07-11eb-9d28-c94c3af554b4.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 
 - Version Version: 0.49.2 (Nov. 2020)

**Comment by dylan09** [comment]
On my MacBook Pro 16" it look a little bit different. The dark black bars are the scroll bars. If I add text so that scrolling is possible the knob appears. 

macOS 10.15.7
PP 0.49.2
<img width="591" alt="Bildschirmfoto 2020-11-25 um 12 43 29" src="https://user-images.githubusercontent.com/13660768/100223913-667d2780-2f1c-11eb-96d6-c2e06a2a5b08.png">

**Comment by buchen** [comment]
And this is how it looks on my machine - macOs 10.15.7

Strange...

<img width="581" alt="Bildschirmfoto 2020-11-29 um 10 32 17" src="https://user-images.githubusercontent.com/587976/100538148-2c6a9900-322e-11eb-9711-fea6811da9f6.png">

**Comment by dylan09** [comment]
A few more info:
macBook Pro 16" (2019) AMD Radeon Pro 5300M and Intel UHD Graphics
Java version: Java 8-Update 271
The scrollboxes looks also strange when set to Bright. I think it was shown that way before dark mode is available in PP.

<img width="699" alt="bright" src="https://user-images.githubusercontent.com/13660768/100551293-d1619200-327f-11eb-89f1-d7fac21872c1.png">
<img width="699" alt="dark" src="https://user-images.githubusercontent.com/13660768/100551296-d58daf80-327f-11eb-818f-34feaf91e3b1.png">

**Comment by dylan09** [comment]
Forgotten to mention that in System Settings I have activated to show Scrollbars every time (Systemeinstellungen -> Allgemein -> Rollbalken einblenden -> Immer)

**Comment by cgolde** [comment]
Which details of my setup would help you to track down the issue?
I was using dark mode on macOS and dark mode pp.

**Comment by cgolde** [comment]
Was solved with latest update (https://github.com/buchen/portfolio/releases/tag/0.50.0) for me. Thanks.
