### ISSUE TITLE
On viewing a list starts at second entry and needs a scroll upward

### ISSUE THREAD

**Issue by trkit** [buchen/portfolio#1848]
**Describe the bug**
When changing view to a list view, the first entry is not visible in the list. Instead, the viable area list entries start with the second entry.

**To Reproduce**
1. Go to any list view
2. However into the list
3. Scroll up
4. See that the list started with the second entry, and first entry is only visible after scrolling up

**Expected behavior**
Changing to a list view should start with the first entry being visible

**Screenshots**
Not feasible for this bug description.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0.1 (20B29) (this is the case for the specialized Big Sur as well as the regular broken version)
 - Version 0.49.3

**Comment by Ragas13** [comment]
@trkit 
Could you kindly test the following version, if the error disappear?
https://github.com/buchen/portfolio/releases/download/0.49.2/PortfolioPerformance-0.49.3.bigsur.dmg

**Comment by trkit** [comment]
Thanks @Ragas13 for reaching out. I suspect, that this the linked build is the one I am running on

> OS: macOS Big Sur 11.0.1 (20B29) (this is the case for the specialized Big Sur as well as the regular broken version)
> Version 0.49.3

The bug exists for the 0.49.3.bigsur as well as the 0.49.3 for me.

If display / graphics matter: I am running on a MacBook Early 2015 13" machine, Intel Iris Graphics 6100 1536 MB. However, I guess this is either a screen size issue or directly coupled to List View.

**Comment by simphide** [comment]
I also have the same Issue Mac OS BigSur with the newest Portfolio Performance running
