### ISSUE TITLE
New Transactions Default To Current Time

### ISSUE THREAD

**Issue by metal450** [buchen/portfolio#1874]
Suggestion/request: Whenever you enter a new transaction (i.e. buy/sell), the dialog comes up with the date field preset to today's date, which is very handy.  However, the time is always preset to 12:00AM.  It would be much easier to enter transactions if it were preset to the current system time, so that inter-day trades would appear in the correct order (i.e. if I enter a transaction at 15:23, the dialog would come up to reflect that time - rather than coming up showing 12:00AM & then needing to be manually set to the current time for each transaction one enters).

Thanks! :)

**Comment by chrisaut** [comment]
I'd rather it not do that, or at least make it an option.

I usually enter transactions with some delay, eg. on the weekend or something, and if I enter 5 things from last Wednesday I don't want to have to clear the time every time (as it's rather irrelevant when I enter the transactions != time of the transaction). I usually don't bother with the time except to force an order, but that's rare.

**Comment by metal450** [comment]
I've since realized that you can set it to the current time by clicking the little "clock" icon next to the time input field. This makes it quite a bit better, as at least you can set it with one extra click (rather than typing it manually). However, I still think it would be preferable to have it default to the current time, as I do this literally for every transaction I enter.

As it seems some people prefer the opposite though, yeah, perhaps the solution is a program-wide setting for whether this defaults to on (& clicking the clock turns it off) or the opposite :)

**Comment by buchen** [comment]
> However, I still think it would be preferable to have it default to the current time, as I do this literally for every transaction I enter.

This was actually the initial implementation. I changed it to the current behavior because of feedback from the forum. Only a few folks seem to record the time at all, and the current time is almost never the time of the trade. The "clicking the clock" behavior is the compromise.

One could make that behavior configurable. I am hesitating a little bit because it make the code more complex and harder to maintain (and the dialogs are already complex). And if you know PP, you know how long I hesitated to make the decimal places for shares configurable... Having said that, I am willing to review a contribution 😄

**Comment by metal450** [comment]
> the current time is almost never the time of the trade

For me personally it's actually more about just having them sort in the same order as I entered them, rather than them being at the right *actual* time. Even if I enter them later & the times aren't true transaction times, as long as it's ticking forward as I do my inputs, the relative order will be correct. In any tho case, yeah, you can never please everyone.  Except with configurable options :)

(Tho now that I realized that you *can* set the time...this is far, *far* lower a priority, personally, than the crypto precisions :) )

**Comment by metal450** [comment]
Regarding contribution: are u aware of any way this could be developed/built via VS Code?  I spent some time trying to get it working, but came up unsuccessful.  Was hoping to avoid installing the whole Eclipse IDE just for this.  If there were a way to do so in VS Code, I'd love to have a crack at it :)

**Comment by metal450** [comment]
If adding a dialog setting is not ideal, what about allowing the old behavior to be enabled manually via the text config file?

**Comment by metal450** [comment]
As it's really quite agonizing to click that clock over & over & over for each & every trade, in order to get them to appear in chronological order, I finally went ahead & got Eclipse running in hopes of resolving it myself :)

I located the code responsible: name.buchen.portfolio.ui/src/name/abuchen/portfolio/ui/dialogs/transactions/AbstractSecurityTransactionModel.java, line 48 just needs to be `protected LocalTime time = LocalTime.now();`

A PR just to "fix" the default value is simple (https://github.com/metal450/portfolio/tree/fix-default-time). However, per chrisaut's reply, my guess is that for as much as it makes me crazy needing to click that clock a million times just for the txns to appear in order, others who would rather their transactions appear in random/non-chronological order won't want to have to click it to un-set the time (?).

Unfortunately, I couldn't seem to figure out how I might be able to pull in a value from the config file (as a non-java programmer, & entirely unfamiliar with Eclipse & this codebase) - if an option is indeed required.

Any pointers would be appreciated. Seems like it's probably easy to read some global config value, to someone familiar enough with the codebase to know where to look :)

**Comment by tquellenberg** [comment]
I would like to propose a different solution. Currently the transactions with the same date are not sorted randomly, but get a stable order by using 1. date/time, 2. amount and 3. hash-code (`AccountTransaction`).  To the user who enters two or more transactions with the same date this looks like "random order".

My solution: for a stable order in the view we use 1. date/time and 2. updatedAt. Thus, the transactions with the same date appear in the order of creation. The only problem: when a transaction is changed afterwards, it moves to the top position within the list of same date transactions.

**Comment by metal450** [comment]
That's certainly MUCH better than we have now.  In my opinion not quite as ideal though, because 1) there will still be no way to have proper order in i.e. CSV exports, and 2) for those who do actually enter transactions when making trades & who'd prefer having true times, they still have to keep enabling the clock over & over.

If a configurable option is a hassle, maybe the "best" solution is to just have it remember the last state. i.e. if the last transaction was entered with a time, then the next one should be too (and vice-versa). That way there's no extra UI, no hidden option in the xml that needs to be manually enabled, & no need to keep re-setting the same desire a million times. You just tick on the clock once, & it records times until you tick it off. The option just needs to be enabled once, rather than for every single transaction separately.

**Comment by tquellenberg** [comment]
> That's certainly MUCH better than we have now.

I proposed a push request with my solution to the problem.

The changes to the behavior of the clock button (configurable or not) do not convince me completely. Maybe this feature will be added in a second step.

**Comment by metal450** [comment]
> I proposed a push request with my solution to the problem.

Thanks! Certainly a big improvement :)

> The changes to the behavior of the clock button (configurable or not) do not convince me completely.

You don't think it would be better to have the clock remember its last state?

In any event, that was more just an idea of a way to do it without needing a separate "option", in response to buchen's thought that "I am hesitating a little bit because it make the code more complex and harder to maintain (and the dialogs are already complex)." To me, all of these would be equally desirable, as they all achieve the same result: no need to manually click the clock before every transaction in order to have it log the time:
1) Clock remembers its last state; or
2) UI config option to determine the clock's initial state; or
3) XML config option that can be used to directly control the clock's initial state (like #2, but just need to config via xml, to avoid having to add to a dialog)

**Comment by tquellenberg** [comment]
I think, for 90% of the users the time of a transaction is irrelevant. They want a reasonable order of their newly added transaction. And this is achieve by the fix.

Looking at your ideas, the remembering clock button seems the easiest change to me. But I'm not quite sure who uses the clock button anyway. And therefor I feel not confident enough to decide on this. Maybe @buchen can have a look...and than I can implement it.

**Comment by metal450** [comment]
> a reasonable order of their newly added transaction. And this is achieve by the fix.

Somewhat. The problem is if we ever do want a time, then the ordering ends up incorrect unless we use a time for everything - this ordering only works for "all on or all off". Also, if you ever need to go back & edit a transaction, then it loses the ordering, unless you then manually go & edit all subsequent trades made that day, in order. Which is more cumbersome than just clicking the clock every time, to make sure you have a "predictable" order no matter if edits are needed or if you do want a time for another trade made that day.

You might say that people don't go back and edit transactions a lot, but I definitely do. For example, I might do a DeFi trade that costs very high ethereum gas, & thus I submit it, then once it completes later, I come back & add the txn hash to the note. This would break the order. Or, at the end of each month when I reconcile my holdings, often I find a mistake here or there - i.e. I accidentally bought something in the wrong security account for example, so I go back to quickly fix it. Again this would break the order.  So although this change is indisputably a big improvement, to me, just having times provides far, far better usability.

> I think, for 90% of the users the time of a transaction is irrelevant.

Not so sure I'd make that assumption. Long-term investors might not, but day traders might. Or especially anyone who deals with crypto, where price swings are so violent that a transaction logged at 9am could be worth thousands of dollars different than 9pm. Yes, PP does capture the quote at the time you make the trade, but if we're using this program to log a history of actions taken, simply throwing away the context of time of day makes a pretty significant difference. My view is that, just as we wouldn't really round transaction values off to the nearest hundred dollars, rounding times off to the nearest 24 hours is pretty poor data resolution - especially when there's really no reason to be doing so: the full resolution is there & available, it just needs to be manually turned on over & over, for each & every trade.  I can see that throwing out this resolution may not have mattered a much w/ traditional equity markets, where price swings are smaller & trading hours are only during a core period of the day.  But I think this software's use cases are broader than that ;)

**Comment by metal450** [comment]
I'll add a 4th possibility to my list of 3 above:

4) Get rid of the clock entirely, and always log times, for every transaction. Then just have a global option to hide the time from being displayed in that column.  Thus, in all cases, you're storing an accurate "createdAt," without throwing out data - but since some users seem to dislike having to see time of day there, just have it be hidden. Thus from a data perspective, it's consistent, but from a UI perspective, it looks as if the times were thrown out.

**Comment by metal450** [comment]
↑ does that (# 4) look like a reasonable solution @buchen ?

**Comment by tquellenberg** [comment]
Yes, my view is biased. I measure my investments in months and years, not in hours or minutes :-)

Idea 1) and 2) look feasible and okay to me.
3) in my eyes is too complicated and 4) is a far too big change (for me).

**Comment by metal450** [comment]
All 4 are 100% equivalent in my eyes - the only goal is to avoid the discarding of data (aka always record times). The only difference really is just trying to come up with a way to still facilitate those who do prefer to discard the times, or to avoid having them shown :)

**Comment by tquellenberg** [comment]
I looked into the source code and I thinks 
> 2. UI config option to determine the clock's initial state
is the easiest way to go. If there is no veto, i will give it a try. (Something like: "For new transactions the time is preset to: a) start of day b) current time")

**Comment by metal450** [comment]
Awesome! :)

**Comment by metal450** [comment]
@tquellenberg : It seems it remembers the time setting for some types of transactions, but some of them aren't working: i.e. Buy/Sell do indeed work, but not Interest/Dividend/Removal

**Comment by tquellenberg** [comment]
I can't reproduce your problem. 
- In the preference the preset is set to "Current time"? Right?
- When you open the dialog for a new buy, the time is preset to the current time as expected. Right?
- And when you open the dialog for a new dividend the time is preset to "0:00"?? Really?? For me there is also the current time preset to the time field.

**Comment by metal450** [comment]
Nevermind...I'm an idiot.

I'm using this on both Linux & Windows (dual boot, sharing a config), seems like I updated it in on one OS but not the other.  Sorry to bother you, it's actually working fine! 😅 🙏

**Comment by tquellenberg** [comment]
No problem.
