### ISSUE TITLE
CSV import: Add trim option

### ISSUE THREAD

**Issue by RoChess** [buchen/portfolio#1880]
Fidelity.com exports their CSV with a prefixed space on almost every column, and I'm going to log a bug with them to stop doing that, but they might not be that easily convinced to change their end.

It might help others within Portfolio Performance to have an extra checkbox option near "First line contains header" that allows to TRIM() the input to remove unnecessary spaces.

I cannot phantom a situation where somebody would want a pre/post-fixed space, so maybe it doesn't even need to be configurable, but I'll leave that up to the project manager.

**Comment by buchen** [comment]
Implemented with #1895 - by default all whitespace is stripped before attempting to parse the values
