### ISSUE TITLE
Eclipse Manifest error / javax.annotation

### ISSUE THREAD

**Issue by Ragas13** [buchen/portfolio#1903]
In memory of #1071!

@chrisaut @damarvin

scheinbar verwechselt ihr das Ticketsysyem mit einem Forum, erstellt wenn notwendige bitte zukünftig bei bereits geschlossenen Issues ein nrues und nehmt ggf. Bezug auf das alte. Andernfalls fällt dies unter den Tisch.

--------

> Ich versuche gerade PP wieder im Eclipse (neuer PC) zum laufen zu bringen. Leider bekomme ich auch immer dieses
> 
> ```
> PostConstruct cannot be resolved to a type	ClientProgressProvider.java
> ```
> 
> Wenn ich in name.abuchen.portfolio (und .ui) Manifest.MF von
> 
> ```
>  javax.annotation,
> ```
> 
> auf
> 
> ```
> javax.annotation;version="1.2.0",
> ```
> 
> ändere findert er es.
> Kenn mich leider mit dem Eclipsezeug so gar nicht aus, aber kann es sein dass hier wieder irgendwas "rausgeflogen" ist?
> 
> Eclipse 20-12 (4.18.0)

--------

> @chrisaut You saved my day!
> Auf der Suche nach einer Antwort auf Probleme mit "Eclipse vs. Maven" und "Java 8 vs. 11" bin ich auf diesen (eigentlich "Closed") Thread gestoßen und kann bestätigen, dass ich _nur_ durch diese Änderung (;version="1.2.0") PP in der IDE starten kann.
> => **launch**-Dateien im **master** korrigieren?
> 
> #1071 wurde ja vor 2 Jahren behandelt und vor fast 2 Jahren geschlossen: Was ist der aktuelle Stand?
> PP soll
> 
> * in Eclipse für Java 8 (extra installiert) + 11 (Eclipse-intern) JDK laufen?
> * mit Maven bisher nur für Java 8 bauen?

**Comment by damarvin** [comment]
@Ragas13 Danke. Und gut, dass das geklärt ist, hatte mich schon gewundert.
[Frage mich noch, warum Ihr das hier in deutsch macht: Würden nicht auch andere Leute mithelfen wollen?]

Das [_PP-Forum_](https://forum.portfolio-performance.info/) ist für solche Projekt-Fragen wahrscheinlich weniger der richtige Ort und [Diskussionen](https://github.com/vercel/vercel/discussions/3874#discussioncomment-162269) noch kein allgemeines Feature.
Eigentlich habe erst einmal nur Fragen (siehe oben) zu den Java-8/11-Problemen, noch kein Issue – aber auch das Tag "question" schon gesehen.

**Comment by chirlu** [comment]
> Das PP-Forum ist für solche Projekt-Fragen wahrscheinlich weniger der richtige Ort

Warum nicht?

**Comment by chrisaut** [comment]
> In memory of #1071!
> 
> @chrisaut @damarvin
> 
> scheinbar verwechselt ihr das Ticketsysyem mit einem Forum, erstellt wenn notwendige bitte zukünftig bei bereits geschlossenen Issues ein nrues und nehmt ggf. Bezug auf das alte. Andernfalls fällt dies unter den Tisch.
> 

Bei aller Liebe, das hat doch nix mit Forum vs. Ticketsystem zu tun. Ich bin auch auf ein eventuelles Problem gestossen das einem alten commit von @buchen  ähnelt und hatte dazu eine kurze Frage. Das kann man doch mal kurz in einem alten issue posten. Ehrlich gesagt ist der Ton von deinem Post auch sehr....naja. Wenn das nicht so gemeint war dann entschuldige ich mich, aber so wie das hier rüberkommt fördert man keine Community.

> > Das PP-Forum ist für solche Projekt-Fragen wahrscheinlich weniger der richtige Ort
> 
> Warum nicht?

Weil das Forum für Enduseranfragen da ist, github ist der technische Teil.

**Comment by buchen** [comment]
@chrisaut schreibt:
> Kenn mich leider mit dem Eclipsezeug so gar nicht aus, aber kann es sein dass hier wieder irgendwas "rausgeflogen" ist?

In der Tat ist diese Version "rausgeflogen". Zu einem späteren Zeitpunkt haben wir alle Versionen aus dem Manifest rausgeworfen. Es sollte ja eigentlich die Version verwendet werden, die in der Installation vorkommt. Ich füge diese Versions zu dem javax.annotation Bundle wieder hinzu.

Trotzdem verstehe ich das Problem nicht ganz. Wenn ich mir die Target Platform anschaue, dann gibt es das annotation Bundle genau nur einmal. Das sollte doch so auch aufgelöst werden können?!?


@damarvin 
> Frage mich noch, warum Ihr das hier in deutsch macht: Würden nicht auch andere Leute mithelfen wollen?

Neue Tickets versuchen wir in English zu halten. Aber wenn jemand auf Deutsch postet, dann antworte ich trotzdem auf Deutsch. Maybe I still switch to English in order to allow others - non-German speakers - to contribute.

**Comment by buchen** [comment]
@damarvin asks:

> in Eclipse für Java 8 (extra installiert) + 11 (Eclipse-intern) JDK laufen?
> mit Maven bisher nur für Java 8 bauen?

The status quo is:

The 64bit version is distributed with Java 11, the 32bit version is distributed with Java 8. There are no 32bit Java binaries for Java 11.

Therefore I want to keep the *n.a.portfolio* and *n.a.portfolio.bootstrap* bundles Java8 compatible. This is the code I downport to the 32bit branch. With the Eclipse version 2020-12, I plan to adopt the UI bundle to this Eclipse version. And we could also upgrade it to use Java11.
