### ISSUE TITLE
Interner Zinsfuß - NaN%

### ISSUE THREAD

**Issue by CK1-CK** [buchen/portfolio#1904]
https://forum.portfolio-performance.info/t/wertpapier-performance-izf-nan/7919/3

Programmversion 0.49.4
Ansicht Berichte > Performance > Wertpapiere

IFZ als NaN% (Berichtszeitraum 1, 2 oder 3 Jahre)

Zur Verdeutlichung habe ich eine Beispiel XML angehängt. Ich hoffe man kann den Fehler nachvollziehen.
Bug.xml Download:
https://forum.portfolio-performance.info/uploads/short-url/eR5kd7Xh9CTa7AsRumK24QYRHij.xml

Ich kann ausschließen:
- kurze Haltedauer
- Fehlbuchung

Laut Excel müsste ein interner Zinsfuß von -99,x% herauskommen.

**Comment by Highlife1911** [comment]
I can somewhat confirm the Problem as my IRR is too high:
![image](https://user-images.githubusercontent.com/7109398/103768984-c985d200-5023-11eb-80b6-a6f3feecec36.png)

**Comment by CK1-CK** [comment]
> version 0.49.4
> I'm seeing the same issue in Performance => Trades:
> ![imagen](https://user-images.githubusercontent.com/10577978/103685661-e66fc600-4f8d-11eb-8946-2bd022ca019b.png)
> Only 2 trades for that stock, without currency exchange:
> ![imagen](https://user-images.githubusercontent.com/10577978/103685780-1323dd80-4f8e-11eb-8c27-a1b71af403c2.png)

I have the NaN Problem at the following reports

- Ansicht Berichte > Performance > Wertpapiere
- Ansicht Berichte > Performance > Trades

My expectation would be that something with -99.x% would come out. But not NaN

**Comment by bosix** [comment]
I can confirm the bug in the current version. Here a minimum example to reproduce the bug:
![image](https://user-images.githubusercontent.com/26360670/107690732-c9c05f80-6caa-11eb-9b19-f80a1ac5ebc0.png)

The bug also destroys the "Performance-Diagramm" since the overall performance will be -100% forever no matter which trades are done after that.

![image](https://user-images.githubusercontent.com/26360670/107690916-0f7d2800-6cab-11eb-8624-7f7127b4d9a4.png)

**Comment by chirlu** [comment]
@bosix: Your diagram issue is unrelated; the diagram doesn’t even use IRR.

**Comment by CK1-CK** [comment]
> https://forum.portfolio-performance.info/t/wertpapier-performance-izf-nan/7919/3
> 
> Programmversion 0.49.4
> Ansicht Berichte > Performance > Wertpapiere
> 
> IFZ als NaN% (Berichtszeitraum 1, 2 oder 3 Jahre)
> 
> Zur Verdeutlichung habe ich eine Beispiel XML angehängt. Ich hoffe man kann den Fehler nachvollziehen.
> Bug.xml Download:
> https://forum.portfolio-performance.info/uploads/short-url/3AyWoM0XMTvOd3Ms2mPfiA0Jz.xml
> 
> Ich kann ausschließen:
> 
> * kurze Haltedauer
> * Fehlbuchung
> 
> Laut Excel müsste ein interner Zinsfuß von -99,x% herauskommen.


@buchen: Do you need any more information to close the bug?

I don't currently know if the NaN% also triggers errors in overall performance.

In Version 0.52 the Bug is still present.

**Comment by CK1-CK** [comment]
The bug is still present in Portfolio Version 0.54

unfortunatly #1959 didn't fix the problem.

Bug_IZF.xml:
https://forum.portfolio-performance.info/uploads/short-url/3AyWoM0XMTvOd3Ms2mPfiA0Jz.xml

Picture:
[https://forum.portfolio-performance.info/uploads/default/original/2X/9/9aa606712ae9bfbe805fc8d1b097856b591a098e.png](url)

if you change the Time Period to 2 or more years, than the IZF is calculated wrong (NaN%)

https://forum.portfolio-performance.info/t/wertpapier-performance-izf-nan/7919/5

Please Reopen the Bug Ticket here.

**Comment by sennahLessert** [comment]
i look for a bugfix

**Comment by CK1-CK** [comment]
is it possible to reopen the bug-report?
