### ISSUE TITLE
Yahoo Finance: auto-select currency in share creation process

### ISSUE THREAD

**Issue by tsohst** [buchen/portfolio#1924]
**Describe the solution you'd like**
* Select currency automatically to the currency that is returned by the yahoo-finance api, when createing a new share.
* Don't know if the api returns the currency that a share has.

**Additional context**
* I always need to check on yahoo finance what currency a share has. Would save time when creating a new share.

**Comment by chirlu** [comment]
Shares don’t have currencies. Shares are traded in currencies, but those depend on the exchange; e.g., the same share may be traded in USD on NASDAQ, in GBP on the LSE and in EUR on XETRA.

**Comment by tsohst** [comment]
> Shares don’t have currencies. Shares are traded in currencies, but those depend on the exchange; e.g., the same share may be traded in USD on NASDAQ, in GBP on the LSE and in EUR on XETRA.

You right, but when creating a share in PP and select yahoo finace it just returns a number. If that number is the current price for a share in USD and I select EUR while creating the share, I fake the actual price or am I wrong?

**Comment by Ragas13** [comment]
As far as I remember, Yahoo nor other quote providers distribute the currency symbol in their feeds.

**Comment by buchen** [comment]
One probably would have to implement some kind of heuristic - if it is traded in Frankfurt, it is EUR. If it is NYSE, then it is USD. Yahoo does not tell use which one it is - at least in the API to retrieve the historical quotes.
