### ISSUE TITLE
Feature request: Make a "save Template" function on CVS imports

### ISSUE THREAD

**Issue by C1618A** [buchen/portfolio#1926]
**Is your feature request related to a problem? Please describe.**
It's always frustrating when one imports a CVS and have to select the right columns again and again. There is some templates made, but one can not make dozens and dozens of templates for fit for every case. 

**Describe the solution you'd like**
What I would like is a button where after I made the selections for a CVS import, I could save them as a template. This template would save not only the field positions (like Value and so on) and also the options for each field (like the date as DD-MM-YYYY, or the Type field relations, etc) and maybe the account. Next time it would be a lot faster.

**Describe alternatives you've considered**
Save the already existing templates on a separated file where the users could go there and adapt for their own cases. If each template had it's own file, it could be a way of users sharing their own templates on the forum for more specific cases.

**Additional context**
![image](https://user-images.githubusercontent.com/63592783/103439254-87cbe480-4c3b-11eb-86b1-591d388b7d53.png)

**Comment by chrisaut** [comment]
If you click the little gear icon you have options to save a specific config as shorthand, or import/export as many configurations as you like to their own file. Is this not exactly what you are asking for here?

**Comment by C1618A** [comment]
Yes, Thank you, I may need better glasses ;)

One can delete this issue, since it will only make people lose their time.
