### ISSUE TITLE
IZF und TWROR bei taggleichen Käufen und Verkäufen

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#193]
Aus dem [Wertpapier-Forum](http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__920151):

> Kann es sein, das IZF und TWROR im Programm mit taggleichen Käufen und Verkäufen ein Problem haben?

> Ich habe ein Wertpapier intraday gekauft und mit Gewinn verkauft. IZF zeigt mir eine negative unendliche Rendite an "-Infinity%". Unendlich kann ich noch verstehen, wegen das kurzen Zeitraums, aber negativ? TWROR wirft "-100%" aus.
Kurz darauf habe ich das gleiche Papier noch einmal gehandelt. Die Haltedauer war diesmal ein paar Tage und auch hier wurde mit Gewinn verkauft. IZF und TWROR geben für diese Transaktion einzeln betrachtet nachvollziehbare positive Werte aus.
Beide Trades zusammen ergeben beim IZF einen nachvollziehbaren positiven Wert, aber TWROR zeigt "-100%" und das auch noch in grüner Schrift.

> Beim intraday Trade wird der Verkauf optisch auch vor dem Kauf gelistet. Gleiches wird auch auf dem Verrechnungskonto dargestellt, obwohl in der richtigen Reihenfolge erfasst wurde. Kann das etwas damit zu tun haben?

**Comment by clashdreath** [comment]
Könnte man mit Issue #423 kombinieren

**Comment by buchen** [comment]
Ja, ich denke auch das ist das gleiche Problem. Bloß nicht einfach zu lösen...
