### ISSUE TITLE
Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-11

### ISSUE THREAD

**Issue by Janosch** [buchen/portfolio#1930]
With a fresh checkout from master I get this error when executing `mvn clean verify -Dtycho.disableP2Mirrors`

> [INFO] Resolving class path of MavenProject: name.abuchen.portfolio:name.abuchen.portfolio.ui:0.49.5-SNAPSHOT @ /Users/janosch/Dev/portfolio/name.abuchen.portfolio.ui/pom.xml
> [ERROR] Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle name.abuchen.portfolio.ui cannot be resolved
> [ERROR] Resolution errors:
> [ERROR]    Bundle name.abuchen.portfolio.ui - **Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-11**
> [ERROR] -> [Help 1]
> org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle name.abuchen.portfolio.ui cannot be resolved
> Resolution errors:
>    Bundle name.abuchen.portfolio.ui - Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-11
>    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)

I'd like to build PP with maven only, as I am trying to package it for macports. I could make it work by increasing tycho-version to 2.0.0. But I'd like to know what the _proper_ fix is for this. I guess I have to define JavaSE-11 somewhere but I have no idea where.

Any hints? Thanks!

**Comment by buchen** [comment]
Interesting... 🤔 

Which JDK version are you using to build PP - it is a Java11, right?
Which Maven Version

I am building with:
```
> mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/asbn/Tools/apache-maven-3.6.3
Java version: 11.0.9.1, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

> I could make it work by increasing tycho-version to 2.0.0.

I can check if I can update centrally to tyco 2.0.0. I had some installation problems before...

**Comment by Janosch** [comment]
No it's Java 15 but it should work anyway, no?
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/local/share/java/maven3
Java version: 15, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by buchen** [comment]
> No it's Java 15 but it should work anyway, no?

I never tested it with Java 15.

For the fun of it, I started a build with PR #1942. Let's see what that one reports

**Comment by buchen** [comment]
And with Java15 it fails with this error message. 😒  I have no idea. I checked whether I can update to Tycho 2.0.0 but there seemed to be other problems.

The only solution for now: fall back to Java 11. Sorry.
