### ISSUE TITLE
Mehrzeilige Spaltenüberschriften

### ISSUE THREAD

**Issue by Shorty68DE** [buchen/portfolio#1933]
Leider müssen einzelne Spalten (z.B. in der Vermögensübersicht) extrem breit aufgezogen werden, um deren Spaltenköpfe vollständig lesen zu können. Dies führt bei mir z.B. dazu, dass ich PP über die gesamte verfügbare Bildschirmbreite aufziehen muss und der tägliche Umgang mit dem Programm eine negative User experience erzeugt.

Hier könnte Abhilfe geschaffen werden mit mehrzeiligen Spaltenüberschriften.

Eine weitere denkbare Möglichkeit wäre es, den vollständigen Text des Spaltenkopfes zusätzlich im Tooltip-Text mit anzuzeigen.

Mit einer diesen beiden sicherlich einfach zu realisierenden Lösungsvorschlägen ließe sich schon viel erreichen!!

**Comment by chirlu** [comment]
Forum: https://forum.portfolio-performance.info/t/mehrzeilige-spaltenueberschriften-vermoegensaufstellung/4326

**Comment by buchen** [comment]
> Eine weitere denkbare Möglichkeit wäre es, den vollständigen Text des Spaltenkopfes zusätzlich im Tooltip-Text mit anzuzeigen.

Das habe ich jetzt so eingebaut. Kommt mit der nächsten Version.

> Hier könnte Abhilfe geschaffen werden mit mehrzeiligen Spaltenüberschriften.

Das ist leider nicht trivial. Die Widgets unterstützen das nicht von Hause aus. Und es mir nicht klar, ob man custom painter auch für die Spaltenüberschrift nutzen kann.

Da ist es vielleicht fast noch einfacher die Spaltenüberschrift editierter zu machen - dann kann man sich selber einen Kurztitel überlegen.
