### ISSUE TITLE
Linux Version v0.5.0 does not work anymore

### ISSUE THREAD

**Issue by marcusg** [buchen/portfolio#1964]
**Describe the bug**
The updated and the reinstalled fresh version 0.5.0 does not start anymore (see the attached error log). 

**To Reproduce**
1. Download v0.5.0 Linux version
2. Install it 
3. Open PP 

**Expected behavior**
PP should start. 

**Log**
[1610350372093.log](https://github.com/buchen/portfolio/files/5794927/1610350372093.log)

**Desktop (please complete the following information):**
 - OS: Arch Linux (Kernel 5.10.5)
 - Version [e.g. 0.50.0]

**Comment by buchen** [comment]
PP needs Java 11 now, you start with Java 8.

Sorry for not having a better error message.
