### ISSUE TITLE
Verkaufsdialog nicht mehr vorausgefüllt

### ISSUE THREAD

**Issue by MarcDahlem** [buchen/portfolio#1966]
Hallo zusammen,

seit dem neusten Update auf Version: 0.50.0 (Jan. 2021) muss ich beim Verkauf eines Wertpapiers immer ein Depot auswählen und die Anzahl eingeben.. 
Dies war in der vorherigen Installation nicht der Fall und die Daten waren vorausgefüllt. Daher vermute ich, dass es ein Bug ist: "Depots --> Mein Depot --> Rechtklick auf Wertpapier --> Verkauf".

![grafik](https://user-images.githubusercontent.com/2813850/104212912-07c12e00-5436-11eb-8458-63c0713389cc.png)

Viele Grüße & danke für die kontinuierliche Weiterentwicklung!

**Comment by chirlu** [comment]
Bist du sicher, daß das in der vorherigen Version nicht auch so war? Gründe, warum du anderes denken könntest:
* Wenn es nur ein einziges Depot gibt, wird das (auch weiterhin) vorausgefüllt. Bei mehreren Depots nicht. Hast du vielleicht kürzlich ein zweites Depot angelegt?
* Wenn du es nicht aus der Vermögensaufstellung des Depots, sondern aus der Umsatzliste machst, wird (auch weiterhin) das Depot vorausgefüllt. Hast du vielleicht vorher aus der Umsatzliste neue Buchungen erstellt?

**Comment by chrisaut** [comment]
Hab auf meinem Laptop noch 0.49.2. Damit wird wirklich Depot und Konto vorausgewählt, auch wenn es mehrere davon gibt.

Depot - Wertpapier Rechtsklick - Verkaufen

**Comment by buchen** [comment]
Das hat sich geändert. Da ich die Vermögensaufstellung umbauen musste um FIFO Kosten bei Transfers korrekt zu berechnen habe ich aktuell das Depot nicht mehr zur Hand. Und darum ist der Dialog nicht vorbelegt. Ich überlege mir was

**Comment by MarcDahlem** [comment]
Das ging ja schnell mit dem Fix. Danke!
In der Zwischenzeit ist mir aufgefallen, dass die Vorausfüllung nicht nur beim Verkauf leer war, sondern auch beim Eintragen von  Dividenden, beim Starten des Nachkaufs über das Depot etc. Sind all diese Dialoge nun mit dem Commit wieder gefixt?
