### ISSUE TITLE
Portfolio Time Machine (Statement of Assets as of Date) no longer works

### ISSUE THREAD

**Issue by pascalhein** [buchen/portfolio#1969]
**Describe the bug**
In the Statement of Assets view, all info is always as of today (i.e. latest quote, current holdings), no matter what date is selected in the Time Machine (calendar button).

**To Reproduce**
1. Go to 'Reports → Statement of Assets'
2. Choose any date with the calendar button (upper right)
3. Observe that 'Shares', 'Date of Quote', 'Quote', 'Market Value' are for the wrong day

**Expected behavior**
'Quote' should be the most recent one on the selected date. 'Shares' should be holdings as of the selected date.

**Screenshots**
Today: 
![image](https://user-images.githubusercontent.com/5236894/104443901-50dcc380-5597-11eb-9c68-ee5ff88fd5be.png)

Past:
![image](https://user-images.githubusercontent.com/5236894/104443865-44586b00-5597-11eb-895d-d53b2f6298c7.png)

**Desktop:**
 - OS: Linux x86_64 (Ubuntu 20.04 LTS)
 - Java: 14.02+12-Ubuntu-120.04
 - Version 0.50.1 (Jan 2021)

**Log file** (not sure if relevant):
[pp-error-2021-01-13.log](https://github.com/buchen/portfolio/files/5808198/pp-error-2021-01-13.log)

**Comment by chrisaut** [comment]
This has already been fixed: https://github.com/buchen/portfolio/commit/234659592d7593084b2b692b82394ab32258a416

**Comment by pascalhein** [comment]
You're right, I missed that. Closing this.
