### ISSUE TITLE
donations

### ISSUE THREAD

**Issue by Xyz00777** [buchen/portfolio#1973]
Hi zuerst mal cooles Projekt das ihr hier aufgezogen habt!
Ich würde gerne ein wenig Geld spenden, damit weiterhin so gut am Projekt weiter machen könnt.
Da ich leider nichts finden wollte ich fragen, ob ihr das aktuell alles selber bezahlt?
Das finde ich zwar cool aber muss auch nicht sein, da dies bestimmt auch eine gute monatliche Summe ist, die man anders verwenden kann...
Ich habe bereits bei mehrere Projekte gesehen, dass diese opencollective benutzen, dies ist meiner ansicht nach eine super seite, da man hier auch als spender sehen kann für was das geld ausgegeben wurde. zb Lizenzen, server kosten, zertifikat kosten...
https://opencollective.com/
Ich würde mich sehr freuen, wenn ich euch da auch demnächst drauf sehen könnte! :)

**Comment by chirlu** [comment]
https://forum.portfolio-performance.info/t/dickes-lob-und-spende/1041/2

**Comment by buchen** [comment]
Mehr ist das aktuell nicht zu sagen
