### ISSUE TITLE
[Feature request] Chart widgets: make height adjustable

### ISSUE THREAD

**Issue by zr40** [buchen/portfolio#1987]
On a large screen, the chart widgets have a really small height. I would like to be able to adjust the height, so that the chart is more clear and there is less unused space on the dashboard.

Screenshot of current dashboard:

![Screenshot from 2021-01-17 19-14-23](https://user-images.githubusercontent.com/616299/104852080-f0cc8100-58f8-11eb-89cf-5b30bbb5e251.png)

I'd like to increase the height of the charts to about 2 or 2.5 times as they are now.

**Comment by zr40** [comment]
This seems like an easy change, I'd do it myself, however I am totally unfamiliar with Java, SWT, and this codebase. This tiny chart height is so annoying to me I'm even willing to change the hardcoded height in a fork and build it myself. However there is no height specified anywhere in `name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/ChartWidget.java`. Please tell me where I can specify the height so I can make the change.

**Comment by zr40** [comment]
I've now spent the better part of a day searching for the chart height in the codebase and I could not find it. Please solve this annoying paper cut. Dashboard charts shouldn't be restricted to a height of about 180 pixels. We aren't stuck with 640x480 displays anymore.

**Comment by zr40** [comment]
Does anyone even see these requests?

**Comment by zr40** [comment]
This was implemented in 0fc072b33167febfc68a5779ee518fd0ec4f41f5, however "Bigger" results in only a 50% increase and is still comically small. Please add more reasonable height options.

**Comment by buchen** [comment]
More options are coming with the next release
