### ISSUE TITLE
Crash on startup on arch aur install.

### ISSUE THREAD

**Issue by Retkid** [buchen/portfolio#1994]
**Describe the bug**
I installed from the aur and it wont boot.

Heres my log.
https://pastebin.com/yUXLKSBu

Arch, Kernel Version: 5.10.6-zen1-1-zen

**Comment by Ragas13** [comment]
I assume you didn't noted the hint at the AUR package. Please try to delete the Eclipse folder.

https://aur.archlinux.org/packages/portfolio/
