### ISSUE TITLE
PDF Extractor verbessern / Fehler melden: PDF Datei in Text konvertieren

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#200]
Wenn Fehler beim PDF Import gemeldet werden, dann brauchen wir vermutlich meist die eigenltiche PDF Datei um den Fehler zu verstehen und zu beheben. Als Benutzer möchte ich aber nicht das PDF mit meinen sensitiven Daten uns Entwicklern teilen. Auch brauchen wir Beispieldokumente um weitere Buchunen zu ermöglichen.

Warum also nicht Benutzer mit Hilfe der PDFBox eine Textdatei generiere? Die kann er frei editieren (Namen, Adresse, Preise, Menge, ...) und dann an uns senden. Wir können die dann den Fehler im Extractor korrigieren und die Beispieldatei als Testdatei einchecken.

@simpsus was meinst Du?

**Comment by buchen** [comment]
BTW, per Email habe ich Feedback zum Comdirect Import bekommen. Das ist schwer "per Email" zu fixen, aber ein Export als Text würde ich auch helfen.

> > Super ist der comdirect import (wenngleich er auch nicht immer alle Stückzahlen richtig erkennt - spielt comdirect da am Aufbau der pdf rum?).

> Leider lässt sich keine Regelmäßigkeit erkennen, da ich einen Sparplan auf ETF's (in EUR) habe und es von Monat zu Monat unterschiedlich ist, ob es richtig erkannt wird oder nicht. Mal betrifft es den einen ETF, mal den anderen und mal gar keinen.
Wenn es falsch erkannt wird, erscheint -1 als Wert, obwohl ich im ganzen Dokument keine -1 finde.

**Comment by simpsus** [comment]
-1 kommt wenn er die Zahl nicht finden kann, das muss dann nicht im Dokument stehen.
Aber ich muss an dieser debug-export funktion arbeiten.
Leider bin ich immer noch nicht weiter in meinem Problem, dass ich momentan die Entwicklungsversion nicht starten kann. auf ein maven build oder install schlägt mit Äonen von Fehlermeldungen fehl. Ich verstehe momentan nicht was sich da verändert hat...

**Comment by buchen** [comment]
> Leider bin ich immer noch nicht weiter in meinem Problem, dass ich momentan die Entwicklungsversion nicht starten kann.

Du hast das neue Bundle "n.a.portfolio.bootstrap" bei Dir im Workspace jetzt drin, richtig?
Du kompilierst mit Java 8? In meiner Environment habe ich  ```export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/``` definiert.
