### ISSUE TITLE
PDF Import TradeRepublic Quartal

### ISSUE THREAD

**Issue by Nustinua** [buchen/portfolio#2003]
Der PDF Import vom Quartalsabschluss 04/2020 klappt nicht mehr.

TradeRepublic scheint das Format der PDF geändert zu haben.

Hier die ersten Zeilen vom Quartal 3:
01.07.2020 Accepted PayIn:IBANEInzahlungsKonto to IBANDepot 212
01.07.2020
02.07.2020 Ausführung Handel Direktkauf 

Und nun die ersten Zeilen vom Quartal 4:
01.10.2020 Accepted PayIn:IBANEInzahlungsKonto to 212
01.10.2020 IBANDepot

Es findet nun ein Zeilenumbruch aus irgendeinem Grund mitten in der PDF statt.
Zeile 335 der Datei 
[portfolio/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/TradeRepublicPDFExtractor.java 
](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/TradeRepublicPDFExtractor.java#L335)müsste nun wie folgt aussehen:
                        .match("(?<date>\\d+\\.\\d+\\.\\d{4}|\\d{4}-\\d+-\\d+) Accepted PayIn:.* to (?<amount>[\\d+,.]*)")

Wenn ich das richtig sehe.

**Comment by Nirus2000** [comment]
Am besten ein anonymes Beispiel posten... dann sieht man direkt wo es klemmt. PDF2Txt

**Comment by Nustinua** [comment]
Ist doch oben?
Hier dann in ein bisschen länger:

Q3:
`PDF Autor: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
Vorname Nachname SEITE 1 von 5
Straße Hausnummer DATUM 09.10.2020
D PLZ ORT DEPOT 1xxxxxxx1
KONTOAUSZUG
zum 30.09.2020
BUCHUNGEN
Aufstellung über die Buchungen in Deinem Verrechnungskonto DExxxxxxxxxxxxxxxxxxx7.
BUCHUNGSTAG / BUCHUNGSTEXT BETRAG IN EUR
WERTSTELLUNG
01.07.2020 Accepted PayIn:DExxxxxxxxxxxxxxxxx3 to DExxxxxxxxxxxxxxxxxxx7 299,96
01.07.2020
02.07.2020 Ausführung Handel `

Und hier ist Q4:
`PDF Autor: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
Vorname Nachname SEITE 1 von 5
Straße Hausnummer DATUM 09.10.2020
D PLZ ORT DEPOT 1xxxxxxx1
KONTOAUSZUG
zum 31.12.2020
BUCHUNGEN
Aufstellung über die Buchungen in Deinem Verrechnungskonto DExxxxxxxxxxxxxxxxxxx7.
BUCHUNGSTAG / BUCHUNGSTEXT BETRAG IN EUR
WERTSTELLUNG
01.10.2020 Accepted PayIn:DExxxxxxxxxxxxxxxxx3 to 299,96
01.10.2020 DExxxxxxxxxxxxxxxxxxx7
01.10.2020 Accepted`


So besser?
