### ISSUE TITLE
Last Price [currency] - The currency is displayed incorrectly

### ISSUE THREAD

**Issue by CK1-CK** [buchen/portfolio#2021]
Version 0.50.3
OS: Win10

View: "Alle Wertpapiere (All securities)"

The unit of the last price is displayed incorrectly for "All securities".

The last rate/price was 315,65 CHF.

It does not have to be "CHF", but Euro. This is "only" a display error. (see screenshot)

![Bug_Portfolio-Performance](https://user-images.githubusercontent.com/65177756/106136742-00a25b80-616a-11eb-959d-36406d92157c.png)

**Comment by Ragas13** [comment]
@CK1-CK 
Could you kindly post your settings made for historical quotes and latest one, please?

**Comment by CK1-CK** [comment]
I have found the solution.
You have given me the decisive tip.


**Historical Data Source:** 
https://www.ariva.de/roche_genussscheine-aktie/historische_kurse?go=1&boerse_id=123&month=&currency=**CHF**&clean_split=1&clean_bezug=1

**Online Data Source:**
https://www.ariva.de/roche_genussscheine-aktie/historische_kurse?go=1&boerse_id=123&month=&currency=**EUR**&clean_split=1&clean_bezug=1

I don't know why there was a difference in the settings.

Anyway, thanks for your efforts.
