### ISSUE TITLE
Could not resolve module: org.eclipse.e4.core.commands

### ISSUE THREAD

**Issue by tuseto** [buchen/portfolio#2023]
**Describe the bug**
When try to start Portfolio Performance version > 0.49.3-linux.gtk.x86_64.tar.gz 
[1612003416814.log](https://github.com/buchen/portfolio/files/5897779/1612003416814.log)

Could not resolve module: org.eclipse.e4.core.commands

**To Reproduce**
1. Extract Portfolio Performance from tar with version > > 0.49.3-linux.gtk.x86_64.tar.gz
2. Click on extracted executable file PortfolioPerformance
4. See error: An error has occurred see log file...
5. In the log:
eclipse.buildId=unknown
java.version=1.8.0_275
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.e4.ui.bindings 4 0 2021-01-30 12:43:37.349
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.e4.ui.bindings [160]
......
.....

**Expected behavior**
Execute portfolio performance without issues

**Desktop (please complete the following information):**
Distributor ID: Neon
Description:    KDE neon User Edition 5.20
Release:        20.04
Codename:       focal

**Comment by Ragas13** [comment]
@tuseto 
Please ensure that at least Java 11 is enabled at your system. Java 8 wont be supported anymore. Furthermore please delete the eclipse folder if the errer still exist after the update.

**Comment by tuseto** [comment]
Thank you! It worked with just installing jdk 14 without anything else actions needed.
