### ISSUE TITLE
[DKB] Import of dividend PDF does not find amount

### ISSUE THREAD

**Issue by StegSchreck** [buchen/portfolio#2034]
**Describe the bug**
Dividend PDF from DKB does not get parsed properly if the amount is split between tax-free and taxed (see screenshot for clarification) 

**Expected behaviour**
Amount of dividend is imported correctly.

**Screenshots**
Screenshot from corresponding part in the PDF:
![image](https://user-images.githubusercontent.com/9078002/106510442-38ddcd00-64cf-11eb-87cf-ad9f56d4d59a.png)

Screenshot from portfolio after import attempt
![image](https://user-images.githubusercontent.com/9078002/106511011-f668c000-64cf-11eb-9afc-2076f0acad61.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.50.3

**Comment by Ragas13** [comment]
@StegSchreck 
It's looks like that DKB has  adjusted the format. Please provide a full document debug as described at https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#andere-dokumente

**Comment by StegSchreck** [comment]
Hey @Ragas13 
Sure, here is the debug info:
[WKN_A0YEDG_-_Ertragsabrechnung_Fonds_vom_12.01.2021_zu_Depot_XXXXXX_-_Belegnr._YYYYYYYY.pdf.txt](https://github.com/buchen/portfolio/files/5912753/WKN_A0YEDG_-_Ertragsabrechnung_Fonds_vom_12.01.2021_zu_Depot_XXXXXX_-_Belegnr._YYYYYYYY.pdf.txt)

**Comment by Nirus2000** [comment]
Hallo @StegSchreck 
ich habe mir den PDF Export angeschaut und habe festgestellt, das hier keine Kosten etc. anfallen, daher kommt die Fehlermeldung im Importer. Ich kann mich auch irren, aber

`Steuerpflichtige Vorabpauschale 0,93+ EUR` <--- Vorabpauschale
`davon steuerfreier Anteil wg. Teilfreistellung 0,27- EUR` <-- steuerfreie Teilfreistellung 
`Kapitalertragsteuerpfl. Ertrag nach Teilfreistellung 0,66+ EUR`
`Verrechneter Sparer-Pauschbetrag 0,66 - EUR` <-- 0,93€ - 0,27€ = 0,66€
`Berechnungsgrundlage für die Kapitalertragsteuer 0,00+ EUR` <--- keine Kapaitalsteuer
`Pauschbetrag Quellensteuer`
`Vorher 0,00 0,00 791,93 0,00 0,00` <--- das sollten deine 801€ Freistellungsauftrag sein
`Ertrag 0,00 0,00 0,66- 0,00 0,00` <--- Abzug des Sparer-Pauschbetrag
`Nachher 0,00 0,00 791,27 0,00 0,00` <--- noch übrig zur freien Verfügung

Ich hoffe ich konnte etwas Licht ins dunkle geben.
Wenn du damit zufrieden bist, bitte das Issue schließen.

Grüße 
Alex

**Comment by StegSchreck** [comment]
Hallo @Nirus2000
Ich hatte tatsächlich nur versucht ein einzelnes PDF zu importieren. Ich glaube du meisnt hier die im Screenshot verschiedenen Patterns die erfolglos versucht wurden um das Dokument einzulesen. Es ist trotzdem nur ein Dokument.

Außerdem: Das mit den Kosten ist recht spannend, aber dennoch müsste er nach meinem Verständnis dann den erzielten Dividendenertrag eintragen. Das ist nicht passiert. Daher ist die ursprüngliche Frage dieses Tickets noch immer offen.

**Comment by Nirus2000** [comment]
Hallo @StegSchreck 
Okay... das habe ich verstanden.
Ich sehe nur leider auf dem Dokument keinen Betrag der irgendwie "gut" geschrieben wird. Weder Dividenden, Zinsen oder anderweitig. Auf dem Dokument wird lediglich die "Vorabpauschale" bearbeitet. Diese wird von deinem Freistellungsauftrag/Pauschbetrag abgezogen und fertig. Nichts weiter passiert hier.
Ansonsten könntest du dir das Dokument nochmal in die Hand nehmen und schauen, ob du einen Betrag findest, der auf ein Konto oder dem Depot verrechnet wird, ergo also tatsächlich gebucht wird.

Grüße
Alex

**Comment by StegSchreck** [comment]
Ah richtig. Sorry, hatte da was falsch interpretiert. DAnn hat sich das tatsächlich erledigt. Danke für den Hinweis
