### ISSUE TITLE
MacOS ARM version

### ISSUE THREAD

**Issue by fabiodcorreia** [buchen/portfolio#2047]
Any plans on releasing a native version for macOS arm64 instead of using rosseta 2?

**Comment by Ragas13** [comment]
Please check out #1386 and #1595. It's up to Eclipse if it will be supported or not.

**Comment by buchen** [comment]
This seems to be the eclipse bug to track: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690

It looks to me there is some work going on (at least looking at the upstream issues linked), but it is not clear when this will become available.
