### ISSUE TITLE
[Request] Global function to sanitize and escape input vars to PDF-Importer

### ISSUE THREAD

**Issue by Nirus2000** [buchen/portfolio#2069]
**Is your feature request related to a problem? Please describe.**
Es wird eine zentral globale Funktion benötigt in der Zahlen von Währungen und Wechselkursen standardisiert wird. Vielleicht auch für Datumsformatierungen.

**Describe the solution you'd like**
Ich habe mich einige Zeit mit den PDF-Importern beschäftigt und verschiedene Ansätze gefunden,
wie die Zahlen im jeweiligen Importer korrigiert werden um den Standard zu erfüllen für die Weiterverarbeitung.
Stichwört wäre hier [JSR 354](https://jaxenter.de/javamoney-money-money-eine-einfuehrung-in-den-jsr-354-standard-39756) Siehe Währungsformatierung des Degiro-Importers oder [LGT Bank](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/LGTBankPDFExtractor.java#L119).
Beispiele der Währungsformate:
```
DKK 71'280.00
EUR 1.107,68
USD -1,082.50
EUR 8 587 234,45
CHF 23'400.50
USD 5,879,354.45
```
Für die Datumsformatierung wird z.B. bei [TargoBank-Importer](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/TargobankPDFExtractor.java#L338) + [Line 344](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/TargobankPDFExtractor.java#L344) verwendet, aber dann das Datumformat in dd.mm.yyyy benutzt. Beim [LGT Bank-Importer](name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/LGTBankPDFExtractor.java) (PR #2074) Zeile 158 ebenfalls. Alternativ kann man das auch einen Punkt nennen, in dem wir Code-Schnipsel zentral hinterlegen können für die PDF-Imports mit einem Aufrufverfahren.

Am dem [Union Investment PDF-Importer](https://forum.portfolio-performance.info/t/pdf-import-von-unioninvest-volksbank/1686/7) (Nr. 4 und 5) bin ich leider gescheitert, da meiner Meinung nach hier eine Block in Block Funktion fehlt, welche als Schleife laufen könnte bis die nächste ISIN gesetzt wird. Die SecurityVars müssen da irgendwie gespeichert werden. Bei den PDF-Debugs werden Sell/Buy/Dividenden/... gleichzeitig verarbeitet. 

Auch wäre am Importer selbst eine Änderung sehr nütztlich, wenn der Import korrekt eingelesen wurde, aber der Endbetrag 0,00 ist. Derzeit wirf er ja immer eine Exception, was zu fragen im Forum führt

Ebenfalls sind [stripDots](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/CommerzbankPDFExtractor.java#L269), [stripBlanks](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/ComdirectPDFExtractor.java#L906), [stripSlashesAndUnderScore](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/ComdirectPDFExtractor.java#L911), DoubleSlashes, [stripTailling ](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/JustTradePDFExtractor.java#L32)... auch eine gute Erweiterung.
Folgende Funktion o.ä. wäre auch nützlich:
```
public static String replaceLast(String input, String regex, String replacement) 
{
    return input.replaceFirst("(?s)"+regex+"(?!.*?"+regex+")", replacement);
}

private String stripBlanks(String input)
{
    return input.replaceAll("\\s", ""); 
}

private String stripBlanksAndUnderscores(String input)
{
    return input.replaceAll("[\\s_]", "");
}

private String stripDots(String input)
{
    return input.replaceAll("\\.", "");
}

private String stripTrailing(String input)
{
     int right = input.length();
     if (input.endsWith(" "))
     {
         input= input.substring(0, right-1);
     }
     if (right == 0)
     {
         return "";
      }
    return input;
}
```

**Comment by buchen** [comment]
> Ich habe mich einige Zeit mit den PDF-Importern beschäftigt und verschiedene Ansätze gefunden,
wie die Zahlen im jeweiligen Importer korrigiert werden um den Standard zu erfüllen für die Weiterverarbeitung.

Ich habe ehrlich gesagt Deinen Vorschlag noch nicht komplett verstanden.

Geht es Dir im das Zahlenformat, dass Du in dem Text vorfindest?
Da war meine Überlegung bisher immer: man schreibt natürlich häufiger sowas wie ```(<amount>[0-9,.'-])``` aber die Regex würden ziemlich unübersichtlich werden, wenn man die konkateniert. Also sowas sie ```"Betrag: " + AMOUNT```

Oder geht es Dir um die Umwandlung. Dann könnte man doch vielleicht die ```asAmount()``` Methode aufbohren. Vielleicht gibt ein Format mit oder einfach nur die Sprache ```asAmount(v.get("amount"), "ch")```

Die weiteren Hilfsmethoden machen in der Tat Sinn irgendwo zentral zu sammeln. Vielleicht direkt in ```TextUtil```? Das sind schon einige.


> Auch wäre am Importer selbst eine Änderung sehr nütztlich, wenn der Import korrekt eingelesen wurde, aber der Endbetrag 0,00 ist. Derzeit wirf er ja immer eine Exception, was zu fragen im Forum führt

Macht Sinn. Hast Du einen Vorschlag? Mann könnte in ```AbstractPDFExtractor#extract``` die Items prüfen und dann ggf. in ein ```NonImportableItem``` umwandeln.

**Comment by Nirus2000** [comment]
Hallo @buchen

danke das du dir kurz dafür Zeit genommen hast für diese Probleme. Dies könnte man alles nun als "Sonderfälle der jeweiligen Banken und der PDF-Dokumente" betrachten, aber wenn das Wort "aber" nicht wäre...
Ich versuche das wiefolgt zu erläutern. 
Die Ausführungen sind sehr primitiv zu betrachten, erläutern jedoch das Grundproblem.

**_Zahlenformatierung von Währungen oder Wechselkursen_**
Es sollen die jeweiligen Beträg per Importer verarbeitet werden (z.B. der Degiro-Importer)
```
// 1.   DKK 71'280.00
// 2.   EUR 1.107,68
// 3.   USD -1,082.50
// 4.   EUR 8 587 234,45
// 5.   CHF 23'400.50
// 6.   USD 5,879,354.45    
// RegEx = [\d',.-]+[\d',.-]... whatever

// Als primitive Hilfsfunktion dient dies hier
private String ConvertAmountToStandard(String inputAmount)
{
    String amount_Step1 = inputAmount.replace(" ", "");
    String amount_Step2 = amount_Step1.replace("'", "");
    String amount_Step3 = amount_Step2.replace(".", ",");
    return amount_Step3;
}

Ergebnisse:
------------
71'280.00 = 71280,00 --> i.O.
1.107,68 = 1,10768 ≠ 1.107,68 --> n.i.O.
-1,082.50 = -1,08250 ≠ -1,082.50 --> n.i.O.
8 587 234,45 = 8587234,45 --> i.O.
23'400.50 =  23400,50 --> i.O.
5,879,354.45 = 5.879.35445 ≠ 5,879,354.45 --> n.i.O.
```
Vielleicht habe ich hier einen fatalen Denkfehler drin... aber wie wird das gelöst?! 
`/* protected */long asAmount(String value)` oder exchangeRate?

**_Hilfsmethoden_**
Diese sollten aus allen derzeitigen Importer getausch/entnommen/umbenannt werden und zentral gelagert werden. Dafür vorgesehen wurde bereits die "[PDFExtractorUtils](https://github.com/buchen/portfolio/blob/31deffdebfa58fa82b87266072e977483757c569/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/PDFExtractorUtils.java#L10)". Es steht nur die Frage im Raum, wie diese angewendet werden bzw. im OOP-Style. Sollte hier Escape und Sanitize voneinander getrennt werden? Ergo z.B. die [stripBlanks](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/ComdirectPDFExtractor.java#L906) von [checkAndSetTax](https://github.com/buchen/portfolio/blob/31deffdebfa58fa82b87266072e977483757c569/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/PDFExtractorUtils.java#L13)?
Ich würde ja sagen, aber ich bin zu jung in diesem Projekt.

**_Zahlenformatierung von Datumsformaten_**
Die Datumsformatierung könnten dann ggf. mit in die PDFExtractorUtils verschoben werden, analog der [checkAndSetTax](https://github.com/buchen/portfolio/blob/31deffdebfa58fa82b87266072e977483757c569/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/PDFExtractorUtils.java#L13). Das Ausgabeformat wird festgelegt (`dd.MM.yyyy`) für die weitere Verarbeitung und die Input-Var wird z.B. über den DateTimeFormatter eingespeist. Alternativ über eine Options-Var in der Funktion `setDate` oder `setDateTime` verarbeitet werden.

**_Exception "Fehlerhafter/unbekannter Dokumenten-Typ im PDF-Import"_**
Korrekte Dokumente werden verarbeitet und die inkorrekten werden nach dem Importvorgang mit Dateinamen angezeigt (Single-/Massenimport). Nach der Verarbeitung der korrekten Dokumente wäre eine Möglichkeit, hier in den direkten PDF-Debug zu starten. Diese könnten dann direkt per Klick als PDF-Debug extrahiert werden und nicht erst über den separaten Menüpunkt.

**_Exception "Korrekter Verarbeitung im PDF-Import, jedoch mit dem Ergebnis 0,00_**
Ein Hinweis würde hier denke ich ausreichen. Also, grüner Haken, mit dem [Typ](https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/model/PortfolioTransaction.java#L18) und dem Betrag 0,00 buchen. Ein Betrag von 0,00 € sollte theoretisch keine Auswirkung auf PP haben, oder? Alternativ nur Anzeigen mit einem Hinweis-Symbol, jedoch nicht weiter verarbeiten.

**_Union Investment PDF-Importer_**
Am dem [Union Investment PDF-Importer](https://forum.portfolio-performance.info/t/pdf-import-von-unioninvest-volksbank/1686/7) (Nr. 4 und 5) habe ich aufgegeben :-( 
Vielleicht hat ja @inv-trad oder @Ragas13 noch eine zündende Idee.

Ich danke dir nochmals für deine kostbare Zeit und die Geduld deines Contribution-Team und Community.

Grüße und bleib Gesund
Alex

**Comment by buchen** [comment]
Es ist super schwer das Zahlenformat zu raten. Im [HTMLTableQuoteFeed](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/online/impl/HTMLTableQuoteFeed.java#L128-L161) probiere ich das notgedrungen - aber nutze auch die "language" Information die (teilweise) in den Webseiten zur Verfügung steht.

Aber noch mal anders gedacht: Du weißt doch in welchem Format die Zahlen im PDF sind. Es sind doch konkrete Dokumente einer Bank. Dann könnte man doch die ```asAmount``` um einen Parameter erweitern, welche Sprache es für die Umwandung verwenden soll.

Oder meinst Du weiß noch nicht mal in welchen Format die Zahlen im PDF Dokument sind. Könnte man dann nicht an der Sprache des Texts rausfinden, welches Format zu verwenden wäre? Nach dem Motto da steht "Buchungen" also ist des Deutsch, oder die Bank heißt "Degiro CH" also muss es wohl Schweizer Format sein?

**Comment by Nirus2000** [comment]
> Es sind doch konkrete Dokumente einer Bank. Dann könnte man doch die asAmount um einen Parameter erweitern, welche Sprache es für die Umwandung verwenden soll.

Diese Frage ist schwer zu beantworten, welche Banken in welchen Ländern aktiv sind, oder noch aktiv werden. 
[(4 Countries von Degiro)](https://github.com/buchen/portfolio/blob/31deffdebfa58fa82b87266072e977483757c569/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DegiroPDFExtractor.java#L510)
Ein Quergedanke wäre von meiner Seite her, wenn man die Zahlen von rechts nach links betrachtet. Bei Währungen wäre es nur die `123,xx`. Wenn keine Dezimalzahl ist, dann ist es eine Ganzzahl. Die Funktion `asAmount` müsste nur prüfen, welches Symbol an vorhanden ist, und alle nicht digits aus dem restlichen String nach links entfernen. Wenn meine Überlegung nicht verkehrt ist, dann müsste das die Probleme der Formatierungen beheben, egal wie die Währungsformatierung aussieht.
