### ISSUE TITLE
Genauigkeit von Kursen nur 2 Nachkommastellen - ungenügend für z.B. Fremdwährungen und Pennystocks

### ISSUE THREAD

**Issue by smurfer** [buchen/portfolio#207]
Ich würde gerne meine Norwegischen Kronen in Portfolio mit aufnehmen - macht z.Zt. keinen Sinn, da die Kurse ( historisch bei NOK so zwischen 0,10 und 0,12) nur mit 2 Nachkommastellen gespeichert werden. Damit kann man keine Wertentwicklung darstellen. Lösung: Nachkommastellen bei Kursen unter 10 erhöhen, zumindest bis zu einer Genauigkeit von 1/10^5

**Comment by buchen** [comment]
Siehe #10 - Bis zu 4 Nachkommastellen bei Wertpapieren
