### ISSUE TITLE
DKB PDF importer assigns wrong year in an edge case

### ISSUE THREAD

**Issue by fnord23787** [buchen/portfolio#2079]
**Describe the bug**
The recently-added code (030f454751304f8e9660c45c305dcb4d4964598d) for importing DKB "Kontoauszüge" (thanks, @christen90!) assigns the wrong year to transactions that
* (a) are on the first "Kontoauszug" of the year, *and*
* (b) have a February date.

The code contains logic to fix this for January transactions on the first "Kontoauszug", however I did receive one titled "Kontoauszug Nummer 001 / 2021 vom 31.12.2020 bis 01.02.2021", which contained a single transaction on 2021-02-01.

This transaction was incorrectly imported for 2020-02-01 because [the conditions that should trigger the fix](https://github.com/buchen/portfolio/commit/030f454751304f8e9660c45c305dcb4d4964598d#diff-0f0adbcbc36fd112240b57211fa2234537780cde4e960b97570a7f738ec952f9R723) were not met.

The bug is present in both these two lines:

https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DkbPDFExtractor.java#L694
https://github.com/buchen/portfolio/blob/6d96a6044ab46c7824b795f9577e3342de7c5ff1/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/DkbPDFExtractor.java#L723

**To Reproduce**
1. Import a first-of-the year DKB "Kontoauszug" (titled "Nummer 001 …") that contains a February transaction.
2. Observe that the February transaction(s) were imported for a last year’s February date.

**Expected behavior**
The transaction(s) should be imported for this year’s February.

**Desktop (please complete the following information):**
 - OS: Linux, but should occur on any OS.
 - Version 0.50.4

**Comment by christen90** [comment]
Mhh in my case the Nummer 1 just had the first week or so included.
You allready found the malfunctioning line...
Feel free to fix :)

**Comment by Nirus2000** [comment]
@fnord23787
Would it be possible to get a PDF debug?!

**Comment by fnord23787** [comment]
Sure, please see: 
[2021-02-01-Kontoauszug_Nr_2021_001_per_2021_02_01.pdf.txt](https://github.com/buchen/portfolio/files/5974011/2021-02-01-Kontoauszug_Nr_2021_001_per_2021_02_01.pdf.txt)

As for fixing it myself, I'm not very familiar writing Java (reading is easier, sorry), so I'm not sure if I'll produce usable results

**Comment by Nirus2000** [comment]
Okay. Thanks! I think @christen90 will fix the bug in the source code. I'm looking forward to that part too ;-)
Greets...
