### ISSUE TITLE
Portfolio Performance doesn't read tax correctly from Flatex PDF import

### ISSUE THREAD

**Issue by unclejamal3000** [buchen/portfolio#2096]
Tax is not recognized and the price was miscalculated.

![grafik](https://user-images.githubusercontent.com/6795043/108590542-626a7580-7364-11eb-873f-ac9aa853eb0f.png)

- 13,39635294 EUR instead of 14,116 EUR
- 0 EUR KESt instead of 305,85

Portfolio Performance Version: 0.50.4

PDF Debug log is attached.
Thank you
[VerkaufFondsZertifikate.txt](https://github.com/buchen/portfolio/files/6014489/VerkaufFondsZertifikate.txt)

**Comment by Nirus2000** [comment]
Hallo @unclejamal3000
vielen Dank für die Fehlerbeschreibung und damit auch gleich dem passenden PDF-Debug. Super!
Sollte im nächsten Release mit dabei sein...

Grüße Alex

**Comment by unclejamal3000** [comment]
Danke für die schnelle Korrektur @Nirus2000 
Ich sehe gerade die Ausführungszeit wird auch nicht in die Buchung übernommen. Kannst du das noch korrigieren?

**Comment by unclejamal3000** [comment]
Ich habe noch ein zweites kniffligeres Beispiel gefunden. Hier wird eine Steuergutschrift als negativer KESt Betrag ausgewiesen. Das lässt sich auch so über die Oberfläche gar nicht in das Feld eintragen, sondern ich muss eine eigene Buchung für Steuergutschrift machen.

[20201110_VerkaufFondsZertifikate.txt](https://github.com/buchen/portfolio/files/6015883/20201110_VerkaufFondsZertifikate.txt)

**Comment by Nirus2000** [comment]
Hallo @unclejamal3000
die Ausführungszeit habe ich hinzugefügt.
Mit dem Verkauf und negativer KESt., also Steuererstattung, habe ich ein neues Issue #2098 erstellt, da es ja "zwei" Probleme sind.
Ich denke aber, wir finden auch hierfür eine Lösung.

**Comment by Nirus2000** [comment]
Hallo @unclejamal3000 
wenn alles i.O. ist, dann sollte zukünfig auch die eventuelle Steuererstattung bei Verkauf durch den PDF-Importer gebucht werden.
Im Test hat soweit alles funktioniert
![grafik](https://user-images.githubusercontent.com/45203494/108838335-c9da2c80-75d3-11eb-9b3d-64b89ddd6440.png)

**Comment by csegit** [comment]
Vielen Dank für den superschnellen Fix!
Ergänzend eine Frage: Wäre es möglich, den PDF-Importer auch vorhandene Buchungen korrigieren zu lassen, so dass fehlende Steuern automatisch nachgetragen/korrigiert werden? Das wäre eine riesen Hilfe bei sehr vielen Buchungen ggü. einer  manuellen Korrektur.

**Comment by Nirus2000** [comment]
Das ist leider nicht möglich. :-/

**Comment by unclejamal3000** [comment]
Behoben mit Version 0.51.0.
