### ISSUE TITLE
Binance no historical data

### ISSUE THREAD

**Issue by msoldin** [buchen/portfolio#2099]
**Describe the bug**
If i set Binance as course supplier, there is Data displayed in the window for each day.
![image](https://user-images.githubusercontent.com/26545782/108623788-15a89c80-7441-11eb-8e1a-b31411ff3d19.png)

But after accepting it, there is no historical data in the overview.

![image](https://user-images.githubusercontent.com/26545782/108623800-2bb65d00-7441-11eb-9425-838e959aabef.png)

**To Reproduce**
1. Create a crypto asset
2. Use Binance as course supplier
3. Check historical data

**Expected behavior**
Expected is historical data for each day, to see your entry positions and a chart.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.50.4

**Comment by Ragas13** [comment]
@msoldin 
I've proposed a bug fix. For cross check, could you create just one dummy historical quote at 1st/Jan 1970, please? Is this KISS solution working to download the whole history?

**Comment by msoldin** [comment]
@Ragas13 
Yep, it seems now it's working. Thank you!
