### ISSUE TITLE
Please allow "Sell" transactions totaling $0

### ISSUE THREAD

**Issue by metal450** [buchen/portfolio#2103]
There seems to be a check in the software preventing any sale where the amount totals $0 (it shows the error "Input required for 'Total').  In the case of cryptocurrency, it would be much more convenient if this were allowed.  Why?  In PP, fees are always paid out in 'currency,' not in 'securities' - but in crypto, fees are paid in the crypto itself (i.e. ethereum gas).  To document this in PP, it takes 2 transactions each time: a Sell transaction to convert the crypto to USD, followed by a Fees transaction for the same amount.  However, if "Sell" transactions weren't prevented from having a total of $0, this could be documented as just one "Sell" where the amount equals the fees.  i.e. in the Sell dialog, the amount is $10, fees is $10, thus credit total is $0.  The result is the as desired: the crypto 'shares' were removed, you booked $10 in fees, and no change to your USD holdings - but it took half as many transactions.

As my transaction history grows increasingly cluttered with Sell, Fee, Sell, Fee, Sell, Fee, I think it'd be a lot more crypto-friendly to just remove this 'total can't be $0' check :)

**Comment by Ragas13** [comment]
Duplicate of #2094

**Comment by metal450** [comment]
Whoops, sorry - closing :)

**Comment by chirlu** [comment]
This isn’t a duplicate of #2094, but it is a clear “won’t fix”. Use outbound delivery instead of sell.

**Comment by metal450** [comment]
Then perhaps for UI clarity, it would be better to display that info on the dialog - i.e. "Sell with an amount of $0 should be input as Outbound Delivery," vs "Input required for sub-total."
