### ISSUE TITLE
PDF Import JustTrade - Datum Mrz could not be parsed at index 2

### ISSUE THREAD

**Issue by Saturas89** [buchen/portfolio#2116]
JustTrade liefert leider in seinen PDFs das Datum in dem folgenden Format.

Orderausführung Datum/Zeit:2 Mrz 2021 09:50:52
Valutatag Datum:4 Mrz 2021

Fehler
Text '2 Mrz 2021 09:50:52' could not be parse at index 2

Bis sie den Umlautfehler behoben haben, könnte man auch Mrz einlesen bitte?
So lange sind für den kompletten Monat keine Imports mehr möglich.

**Comment by Ragas13** [comment]
#2115
