### ISSUE TITLE
Error on import of ING documents (dividend)

### ISSUE THREAD

**Issue by tomjanke** [buchen/portfolio#2126]
**Describe the bug**
Import error with ING documents
after update to 
Version: 0.51.1 (March 2021) Platform: macosx, x86_64 Java: 11.0.4+11-LTS, Azul Systems, Inc. 
I get the following error message when importing income statements (dividends):
"Taxes and fees may not include currency: ..." 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Version: 0.51.1 (March 2021) 
Platform: macosx,
x86_64 Java: 11.0.4+11-LTS

**Comment by Nirus2000** [comment]
Please send an PDF-Debug:

Video tutorial:
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

**Comment by heldic** [comment]
```
PDF author: 'ING-DiBa'
PDFBox Version: 1.8.16
-----------------------------------------
ING-DiBa AG · 60628 Frankfurt am Main
Depotinhaber: Max Mustermann
Herrn Direkt-Depot Nr.: 1234567899
Max Mustermann Datum: 04.03.2021
Musterstraße 123 Seite: 1 von 2
60628 Frankfurt am Main
Dividendengutschrift
ISIN (WKN) US4581401001 (855681)
Wertpapierbezeichnung Intel Corp.
Registered Shares DL -,001
Nominale 16,00 Stück
Zins-/Dividendensatz 0,3475 USD
Ex-Tag 04.02.2021
Zahltag 01.03.2021
Brutto USD 5,56
QuSt 15,00 % (EUR 0,68) USD 0,83
Zwischensumme USD 4,73
Umg. z. Dev.-Kurs (1,214228) EUR 3,90
Gesamtbetrag zu Ihren Gunsten EUR 3,90
Abrechnungs-IBAN DE21 5001 0517 1234 5678 99
Valuta 01.03.2021
Quellensteuer laut Doppelbesteuerungsabkommen (DBA).
Jahressteuerbescheinigung folgt.
Weitere steuerliche Informationen entnehmen Sie bitte der Rückseite.
ING-DiBa AG · Theodor-Heuss-Allee 2 · 60486 Frankfurt am Main · Vorsitzender des Aufsichtsrates: Dr. Claus Dieter Hoffmann · Vorstand: Nick Jue (Vorsitzender),
Dr. Joachim von Schorlemer (stellv. Vorsitzender), Zeljko Kaurin, Sigrid Kozmiensky, Daniel Llano Manibardo, Norman Tambach · Sitz: Frankfurt am Main · AG Frankfurt am Main
HRB 7727, Steuernummer: 047 220 2800 4 · USt-IdNr.: DE 114 103 475 · Internet: www.ing.de · E-Mail: info@ing.de · BIC: INGDDEFFXXX · Mitglied im Einlagensicherungsfonds
Depotinhaber: Max Mustermann
Direkt-Depot Nr.: 1234567899
Datum: 04.03.2021
Seite: 2 von 2
ISIN (WKN) US4581401001 (855681)
Anrechenbare ausländische Quellensteuer 0,68 EUR
KapSt-pflichtiger Kapitalertrag 4,58 EUR
Mit Sparer-Pauschbetrag verrechnet -0,00 EUR
Sparer-Pauschbetrag vor Ertrag 123,45 EUR
Sparer-Pauschbetrag nach Ertrag 123,45 EUR
Verrechnungstopf ausländ. Quellenst. vor Ertrag 123,45 EUR
Verrechnungstopf ausländ. Quellenst. nach Ertrag 123,45 EUR
Bei Fragen besuchen Sie uns einfach unter www.ing.de/wertpapierwissen - da gibt es viele schnelle
Antworten. Oder senden Sie uns eine E-Mail an info@ing.de .

```

**Comment by tomjanke** [comment]
> Hello @tomjanke
> Please send an PDF-Debug:
`PDF Autor: 'ING-DiBa'
PDFBox Version: 1.8.16
-----------------------------------------
ING-DiBa AG · 60628 Frankfurt am Main
Depotinhaber: Max Mustermann
Herrn Direkt-Depot Nr.: #1234567
Max Mustermann Datum: 04.03.2021
Strasse Seite: 1 von 2
PLZ Ort
Dividendengutschrift
ISIN (WKN) US92826C8394 (A0NC7B)
Wertpapierbezeichnung VISA Inc.
Reg. Shares Class A DL -,0001
Nominale 5,00 Stück
Zins-/Dividendensatz 0,32 USD
Ex-Tag 11.02.2021
Zahltag 01.03.2021
Brutto USD 1,60
QuSt 15,00 % (EUR 0,20) USD 0,24
Zwischensumme USD 1,36
Umg. z. Dev.-Kurs (1,214229) EUR 1,12
Gesamtbetrag zu Ihren Gunsten EUR 1,12
Abrechnungs-IBAN DE_IBAN123456
Valuta 01.03.2021
Quellensteuer laut Doppelbesteuerungsabkommen (DBA).
Jahressteuerbescheinigung folgt.
Weitere steuerliche Informationen entnehmen Sie bitte der Rückseite.
ING-DiBa AG · Theodor-Heuss-Allee 2 · 60486 Frankfurt am Main · Vorsitzender des Aufsichtsrates: Dr. Claus Dieter Hoffmann · Vorstand: Nick Jue (Vorsitzender),
Dr. Joachim von Schorlemer (stellv. Vorsitzender), Zeljko Kaurin, Sigrid Kozmiensky, Daniel Llano Manibardo, Norman Tambach · Sitz: Frankfurt am Main · AG Frankfurt am Main
HRB 7727, Steuernummer: 047 220 2800 4 · USt-IdNr.: DE 114 103 475 · Internet: www.ing.de · E-Mail: info@ing.de · BIC: INGDDEFFXXX · Mitglied im Einlagensicherungsfonds
Depotinhaber: Max Mustermann
Direkt-Depot Nr.:Depotnummer
Datum: 04.03.2021
Seite: 2 von 2
ISIN (WKN) US92826C8394 (A0NC7B)
Anrechenbare ausländische Quellensteuer 0,20 EUR
KapSt-pflichtiger Kapitalertrag 1,32 EUR
Mit Sparer-Pauschbetrag verrechnet -1,32 EUR
Sparer-Pauschbetrag vor Ertrag 999,99 EUR
Sparer-Pauschbetrag nach Ertrag 999,99 EUR
Verrechnungstopf ausländ. Quellenst. vor Ertrag 99,99 EUR
Verrechnungstopf ausländ. Quellenst. nach Ertrag 99,99 EUR
Bei Fragen besuchen Sie uns einfach unter www.ing.de/wertpapierwissen - da gibt es viele schnelle
Antworten. Oder senden Sie uns eine E-Mail an info@ing.de .`

**Comment by sheepherder** [comment]
same here.
"Steuern und Gebühren dürfen keine Währung haben: USD 13.03"
```
PDF Autor: 'ING-DiBa'
PDFBox Version: 1.8.16
-----------------------------------------
ING-DiBa AG · 60628 Frankfurt am Main
Depotinhaber: ###################
###### Direkt-Depot Nr.: ###########
############ Datum: 04.03.2021
########### Seite: 1 von 2
###########
Dividendengutschrift
ISIN (WKN) US4581401001 (855681)
Wertpapierbezeichnung Intel Corp.
Registered Shares DL -,001
Nominale 250,00 Stück
Zins-/Dividendensatz 0,3475 USD
Ex-Tag 04.02.2021
Zahltag 01.03.2021
Brutto USD 86,88
QuSt 15,00 % (EUR 10,73) USD 13,03
Zwischensumme USD 73,85
Umg. z. Dev.-Kurs (1,214228) EUR 60,82
Gesamtbetrag zu Ihren Gunsten EUR 60,82
Abrechnungs-IBAN ###########
Valuta 01.03.2021
Quellensteuer laut Doppelbesteuerungsabkommen (DBA).
Jahressteuerbescheinigung folgt.
Weitere steuerliche Informationen entnehmen Sie bitte der Rückseite.
ING-DiBa AG · Theodor-Heuss-Allee 2 · 60486 Frankfurt am Main · Vorsitzender des Aufsichtsrates: Dr. Claus Dieter Hoffmann · Vorstand: Nick Jue (Vorsitzender),
Dr. Joachim von Schorlemer (stellv. Vorsitzender), Zeljko Kaurin, Sigrid Kozmiensky, Daniel Llano Manibardo, Norman Tambach · Sitz: Frankfurt am Main · AG Frankfurt am Main
HRB 7727, Steuernummer: 047 220 2800 4 · USt-IdNr.: DE 114 103 475 · Internet: www.ing.de · E-Mail: info@ing.de · BIC: INGDDEFFXXX · Mitglied im Einlagensicherungsfonds
Depotinhaber: ###########
Direkt-Depot Nr.: ###########
Datum: 04.03.2021
Seite: 2 von 2
ISIN (WKN) US4581401001 (855681)
Anrechenbare ausländische Quellensteuer ###########
KapSt-pflichtiger Kapitalertrag ###########
Mit Verrechnungstopf ausländ. Quellenst. verrechnet -###########
Bemessungsgrundlage für KapSt vor QuSt ###########
Auf Kapitalertrag angerechn. ausl. QuSt ###########
Verrechnungstopf Allgemein vor Ertrag ###########
Verrechnungstopf Allgemein nach Ertrag ###########
Sparer-Pauschbetrag vor Ertrag ###########
Sparer-Pauschbetrag nach Ertrag ###########
Verrechnungstopf ausländ. Quellenst. vor Ertrag ###########
Verrechnungstopf ausländ. Quellenst. nach Ertrag ###########
Bei Fragen besuchen Sie uns einfach unter www.ing.de/wertpapierwissen - da gibt es viele schnelle
Antworten. Oder senden Sie uns eine E-Mail an info@ing.de .
```
