### ISSUE TITLE
PDF Import Flatex: Wechselkurs bei Kauf wird nicht berücksichtigt

### ISSUE THREAD

**Issue by unclejamal3000** [buchen/portfolio#2127]
In Zeile 25 vom PDF steht der Devisenkurs. Dieser wird aber beim Import scheinbar nicht berücksichtigt und daher folgende Fehlermeldung ausgegeben:

![image](https://user-images.githubusercontent.com/6795043/109983833-7cf90300-7d03-11eb-8a69-5468fde7de7f.png)

Dass die Buchung schon existiert, kann ignoriert werden. Habe es nur zu Demonstrationszwecken neu importiert.

PP Version: 0.51.1
PDF Debug Log hier:
[20210226_Wertpapierabrechnung.txt](https://github.com/buchen/portfolio/files/6084588/20210226_Wertpapierabrechnung.txt)

**Comment by Nirus2000** [comment]
Hallo @unclejamal3000
der Import läuft bei mir Problemlos durch. Ich glaube eher, dass du in deinen Wertpapieren 
das Wertpapier in USD führst anstatt in EUR, wie dein Depot.
![grafik](https://user-images.githubusercontent.com/45203494/110080756-364eeb80-7d8b-11eb-8248-919155d61e66.png)
Wenn ja, bitte Issue schließen.

**Comment by unclejamal3000** [comment]
Ja ich führe das Wertpapier in USD, weil ich die Kurse so bekomme.
Ist es eine falsche Annahme von mir, dass der Kauf so eingebucht wird?

<img width="591" alt="grafik" src="https://user-images.githubusercontent.com/6795043/110083422-f5f16c80-7d8e-11eb-88a8-9e26196c0d97.png">

**Comment by Nirus2000** [comment]
Hallo @unclejamal3000 
Ja, das funktioniert natürlich dann nicht.
Du kannst die historischen Kurse von arivia.de nehmen.
https://www.ariva.de/cm_life_sciences_inc-aktie/historische_kurse?go=1&boerse_id=40&month=&currency=EUR
Hier darauf achten, das **currency=EUR** steht. dann sollte es auch klappen :-)
![grafik](https://user-images.githubusercontent.com/45203494/110089224-2092f380-7d96-11eb-89f4-1a4ff96dbd2f.png)
Die historischen Kurse für einen längeren Zeitraum, kannst als CSV dort ebenfalls downloaden.
![grafik](https://user-images.githubusercontent.com/45203494/110089288-34d6f080-7d96-11eb-842b-490bc77182ac.png)
Wenn alles passt, sollte auch der Import problemlos funktionien und bitte das Issue schließen.

**Comment by unclejamal3000** [comment]
@Nirus2000 danke für die Erläuterung.

**Comment by Nirus2000** [comment]
You're welcome...
