### ISSUE TITLE
Farbige Einfärbung von TWROR Anzeige in Performance Wertpapiere

### ISSUE THREAD

**Issue by simpsus** [buchen/portfolio#213]
Ich hätte erwartet, dass Zahlen <0 rot und >0 grün eingefärbt werden.
BASF zeigt mir für das letzte Jahr: 

https://www.dropbox.com/s/upuwqd1fzy90w61/Screenshot%202014-12-26%2009.53.44.png?dl=0

Der TWROR ist negativ, wird aber in grün angezeigt. Der IZF ist positiv. Wird die Farbe evtl. nur einmal berechnet oder ist das gewollt?

**Comment by buchen** [comment]
Gleiche Meldung:

> Sorry, aber ich habe noch einen lustigen Effekt in meiner Wertpapieransicht entdeckt. Negativer TWROR, positiver IZF, beide in grüner Schrift. Also z. B. TWROR = - 15%, IZF = 4,39%.
