### ISSUE TITLE
Importing dividends in different currency from security (Interactive Brokers Flex Query)

### ISSUE THREAD

**Issue by delianenchev** [buchen/portfolio#2139]
I have the following error when importing a Flex Query: `Exchange rate of gross value is missing (transaction currency USD and security currency EUR)`. Flex Query have [`fxRateToBase`](https://guides.interactivebrokers.com/rg/reportguide/cash_transactionsfq.htm)
![Image](https://user-images.githubusercontent.com/1281108/110248099-1d575d80-7f78-11eb-9956-c769a576e647.png)

First import `Trades.xml`

`
<FlexQueryResponse queryName="Trades" type="AF">
<FlexStatements count="1">
<FlexStatement accountId="UXXXXXX" fromDate="20190826" toDate="20191231" period="LastBusinessDay" whenGenerated="20210307;043303">
<Trades>
<Trade accountId="UXXXXXX" acctAlias="" model="" currency="EUR" fxRateToBase="1" assetCategory="STK" symbol="SGN" description="SURGUTNEFTEGAS-SP ADR" conid="27346611" securityID="US8688612048" securityIDType="ISIN" cusip="" isin="US8688612048" listingExchange="SWB" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" tradeID="2592275115" putCall="" reportDate="20191030" principalAdjustFactor="" dateTime="20191030;091642" tradeDate="20191030" settleDateTarget="20191101" transactionType="ExchTrade" exchange="TGATE" quantity="120" tradePrice="6" tradeMoney="720" proceeds="-720" taxes="0" ibCommission="-6" ibCommissionCurrency="EUR" netCash="-726" closePrice="5.965" openCloseIndicator="O" notes="" cost="726" fifoPnlRealized="0" fxPnl="0" mtmPnl="-4.2" origTradePrice="0" origTradeDate="" origTradeID="" origOrderID="0" clearingFirmID="" transactionID="11501005" buySell="BUY" orderReference="" volatilityOrderLink="" exchOrderId="N/A" orderTime="20191030;080542" openDateTime="" holdingPeriodDateTime="" whenRealized="" whenReopened="" levelOfDetail="EXECUTION" changeInPrice="0" changeInQuantity="0" orderType="LMT" traderID="" isAPIOrder="N" accruedInt="0" />
</Trades>
</FlexStatement>
</FlexStatements>
</FlexQueryResponse>
`

Error is in `Cash Transactions.xml`

`<FlexQueryResponse queryName="Cash Transactions" type="AF">
<FlexStatements count="1">
<FlexStatement accountId="UXXXXXX" fromDate="20200102" toDate="20201231" period="YearToDate" whenGenerated="20210307;045036">
<CashTransactions>
<CashTransaction accountId="UXXXXXX" acctAlias="" model="" currency="USD" fxRateToBase="0.83815" assetCategory="STK" symbol="SGN" description="SGN(US8688612048) CASH DIVIDEND USD 0.088051 PER SHARE - RU TAX" conid="27346611" securityID="US8688612048" securityIDType="ISIN" cusip="" isin="US8688612048" listingExchange="SWB" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" dateTime="20200818;202000" settleDate="20200818" amount="-1.58" type="Withholding Tax" tradeID="" code="" transactionID="13505500801" reportDate="20200818" clientReference="" levelOfDetail="DETAIL" />
<CashTransaction accountId="UXXXXXX" acctAlias="" model="" currency="USD" fxRateToBase="0.83815" assetCategory="STK" symbol="SGN" description="SGN(US8688612048) CASH DIVIDEND USD 0.088051 PER SHARE (Ordinary Dividend)" conid="27346611" securityID="US8688612048" securityIDType="ISIN" cusip="" isin="US8688612048" listingExchange="SWB" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" dateTime="20200818;202000" settleDate="20200818" amount="10.56" type="Dividends" tradeID="" code="" transactionID="13505500800" reportDate="20200818" clientReference="" levelOfDetail="DETAIL" />
<CashTransaction accountId="UXXXXXX" acctAlias="" model="" currency="USD" fxRateToBase="0.83815" assetCategory="STK" symbol="SGN" description="SGN(US8688612048) CASH DIVIDEND USD 0.088051 PER SHARE - FEE" conid="27346611" securityID="US8688612048" securityIDType="ISIN" cusip="" isin="US8688612048" listingExchange="SWB" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" dateTime="20200818;202000" settleDate="20200818" amount="-3.67" type="Other Fees" tradeID="" code="" transactionID="13505500802" reportDate="20200818" clientReference="" levelOfDetail="DETAIL" />
</CashTransactions>
</FlexStatement>
</FlexStatements>
</FlexQueryResponse>`

Note about [`fxRateToBase`](https://guides.interactivebrokers.com/rg/reportguide/cash_transactionsfq.htm): EUR is the main currency of my account.  If I buy a Canadian stock on the US stock exchange, and i get a dividend in CAD. I guess fxRateToBase must be EUR/CAD

 - OS: Windows
 - Version 0.51.1 (Mar 2021

**Comment by Kalypox** [comment]
I have the same problem.

**Comment by ChrisKolan** [comment]
I can confirm this error.

**Comment by Kalypox** [comment]
Yes this issue is still present
