### ISSUE TITLE
comdirect PDF import of dividend statements should include the number of shares

### ISSUE THREAD

**Issue by wsteitz** [buchen/portfolio#214]
when using the comdirect pdf import with a dividend statement, the number of shares is not extracted from the pdf. unfortunately it is also not possible to add this later in the UI.

**Comment by wsteitz** [comment]
Editieren funktioniert in der Tat in der Konto Ansicht, habe ich nicht bemerkt. Ich habe es bei Performance->Wertpapiere und bei "Alle Wertpapiere"->Umsätze versucht. Alle drei Ansichten zeigen eine Liste von Transaktionen, nur in einer kann man editieren.

**Comment by buchen** [comment]
> Alle drei Ansichten zeigen eine Liste von Transaktionen, nur in einer kann man editieren.

Fällt mir selber schon gar nicht mehr auf :-( Bei Gelegenheit sollte ich die da mal editierbar machen. Danke.
