### ISSUE TITLE
US Dividenden von ING können nicht importiert werden

### ISSUE THREAD

**Issue by dnsbtchr** [buchen/portfolio#2143]
Hi,

ich habe heute festgestellt dass der Import von PDF Dividendenabrechnung der ING nicht mehr möglich ist.
Der heutige Import der Fastenal Dividende schlägt mit "Steuern und Dividenden dürfen keine Währung haben" fehl. Der letzte Import der Fastenal Dividende Anfang Januar hat noch ohne Probleme funktioniert.
Bei Bedarf kann ich gerne das PDF bereitstellen.

Gruß
Dennis

**Comment by Ragas13** [comment]
Duplicate of #2126
