### ISSUE TITLE
PDF Import Keytradebank

### ISSUE THREAD

**Issue by berndmr** [buchen/portfolio#2157]
**Describe the solution you'd like**
Extend PDF import to process keytradebank PDFs.

PDF Debug Output attached.

[Keytrade_Kauf.txt](https://github.com/buchen/portfolio/files/6151327/Keytrade_Kauf.txt)

**Comment by Nirus2000** [comment]
Hallo @berndmr
thx... pls send more examples and post it on [PP-Forum](https://forum.portfolio-performance.info/)
Open a new Threat with the name "PDF-Import für Keytrade Bank" and post the PDF-Debugs

Video tutorial:
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)
