### ISSUE TITLE
[Feature request] Ex-Tag/Buchungstag implementieren

### ISSUE THREAD

**Issue by Nirus2000** [buchen/portfolio#2173]
**Is your feature request related to a problem? Please describe.**
Ex-Tag / Buchungstag in PP implementieren

**Describe the solution you'd like**
https://forum.portfolio-performance.info/t/buchung-von-dividenden-am-ex-tag-oder-bei-gutschrift/1718
https://forum.portfolio-performance.info/t/buchungsdatum-vs-valutadatum/292/18

**Comment by Ragas13** [comment]
Hm, I could not see the benefit for having two dates rather than on date. Did you have any plan to enhance the calculations? The demand is at one side, the usage/purpose is on the other side.

**Comment by Nirus2000** [comment]
Hallo @Ragas13 
https://forum.portfolio-performance.info/t/wiederanlage-von-dividenden/1871/53 und folgende Beiträge.
Die Performance ist nun mal unterschiedlich zwischen Wertpapieren, welche im per Ex-Datum tatsächlich eingebucht/gekauft werden und dem Abrechnungsdatum der jeweiligen Broker. In sämtlichen Importern, welche ich bisher bearbeitet habe, wird es mal so und mal so gebucht. Ich habe diese natürlich bisher nicht angefasst, oder verändert, jedoch bei neuen Importern stets drauf geachtet, den Anweisungen vom @buchen zu folgen. ;-)
https://github.com/buchen/portfolio/pull/2074#discussion_r579612397

Die Diskussion steht schon sehr lang im Raum, also warum nicht "_Nägel mit Köpfen machen_" und die beiden Varianten anbieten.
Der EndUser kann dann selber entscheiden. Die Importer anpassen, auch wenn es eine Menge sind, wäre nicht das Problem.

**Comment by Ragas13** [comment]
Hi @Nirus2000 
Fie Diskussionen kenne ich, die Challenge jedoch ist, was soll dann mit dieser neuen Information angefangen werden. So wird ein Datum bei den Buchungen hinzugefügt, ohne das es eine Auswertung auf irgendwelche Berechnung hätte. Oder fällt dir eine Verwendung für das ex-Tag Datum ein?

**Comment by Nirus2000** [comment]
Hallo @Ragas13

### Definiieren wir erstmal die Bedeutungen von Ex-Tag und Valuta:

**Ex-Tag:**
Der Ex-Tag bei deutschen Aktien ist in der Regel ein Tag nach der Hauptversammlung, bei der die Dividende festgelegt worden ist. Anleger, die am Ex-Tag die Unternehmensanteile erworben haben, bekommen keine Dividende ausgeschüttet. Im Gegensatz dazu ist der Dividendenstichtag das Datum, welches darüber entscheidet, welche Aktieninhaber Anspruch auf den Erhalt der Dividende haben. Sie müssen bei Handelsschluss am Dividendenstichtag Inhaber der Aktie sein, um die Dividende ausgezahlt zu bekommen.
Bei Offenen Investmentfonds wird das Anrecht auf die Ausschüttung vom Investmentfondsanteil am Ex-Tag getrennt. 
[Quelle Wikipedia]
Das bedeutet, dass dir die z.B. Dividende schon zusteht, aber noch in der "Pipline" ist um auf dein Konto zu fliesen. Der zeitliche Horizont ist hierbei leider etwas flexibel.

**Valuta:**
Das ist der Tag, an dem das Geld dir auf dem Konto gutgeschrieben wird. Die Bank macht eine Transaktion auf dein Konto.

---------------------------------------------------



> Die Performance wird auf das Buchungsdatum mE gerechnet,da ich vorher nicht im Besitz des Geldes bin. Oder irre ich mich da?

Hier entsteht der Irrtum.

### Wie soll PP nun verfahren?

---------------------------------------------------

Betrachten man Auswertungen/Kennzahlen aus dem Valuta-Datum (primitiv Verrechnungskonto-Sicht), so wird die Performance verzerrt und das meist ins negative. (nicht reell -> "mir steht es zwar zu, aber ich hab's noch nicht auf'n Konto") 

Betrachten man Auswertungen aus dem Ex-Datum (primitiv Depot), so wird die Performance korrekt berechnet.
(reell)

---------------------------------------------------

### EndUser-Entscheidung:
So... und hier scheiden sich nun die Geister. 
Performance und Kennzahlen nach dem Verrechnungskonto oder nach reellen Wertpapierereignissen.
Um genau dieses Problem zu lösen, sollte die Möglichkeit von Ex-Tag/Schlußtag/Stichtag zu Valuta geschaffen werden.

**Comment by chirlu** [comment]
Die korrekteste Vorgehensweise wäre, wenn das Geld zum Ex-Tag aus der Aktie auf ein Pseudokonto flösse und am Zahltag (Wertstellungstag) auf das reale Konto umgebucht würde. Kann man auch von Hand machen, wenn man ein entsprechendes Konto „Noch unterwegs seiende Dividenden“ einrichtet.

Der Buchungstag ist vom Zufall bzw. von der jeweiligen Bank und ihren Prozessen abhängig und daher irrelevant.

Verwandt: #372

**Comment by Pnda87** [comment]
@Nirus2000 und @chirlu stellen den Grundgedanke genau richtig dar.

Am Ex-Tag erfolgt der Dividendenabschlag bei der Aktie. Ab diesem Zeitpunkt hat man eine Dividendenforderung (was oben "Noch unterwegs seiende Dividenden" Konto genannt wurde).
Dividendenforderungen sind Teil des NAVs, d.h. fließen in die Performance ein.
Auf dem Konto gebucht wird am Valuta Tag.

In einer idealen Welt würde das in PP so berücksichtigt werden.

Daher von mir +1 für den Feature request.

**Comment by Nirus2000** [comment]
Durch den PDF Import sind die Daten vorhanden, also wenn die Importer den Ex-Tag nutzen.
Beide könnten korrekt dadurch korrekt abgebildet werden. Ein Valuta-Tag für das Verrechnungskonto und der Ex-Tag für die Performance.
