### ISSUE TITLE
Steuern zu Zinsen und Dividenden erfassen

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#219]
Aus dem Wertpapier-Forum:

> Zinsen und Dividenden
> -Es wäre schön, wenn ich Steuerabzüge direkt in der Maske eingeben könnte Zur Zeit bleibt mir nur die Möglichkeit, meine netto Zinsen/Dividenden einzutragen und einen Kommentar zu setzen, dass x EUR für Steuern bereits abgezogen wurden.

**Comment by Tolzmann** [comment]
Diese Erweiterung würde die Ergonomie der Software bei der Erfassung von Dividenden deutlich verbessern. Da Dividenden auch relativ häufig zu erfassen sind (1 bis 4 mal pro Jahr) wäre diese Anpassung eine wesentliche Arbeitserleichterung.

**Comment by buchen** [comment]
Erste Version:
* [Win 64bit](https://dl.dropboxusercontent.com/u/14269663/PortfolioPerformance-0.23.2-SNAPSHOT-win32.win32.x86_64.zip)
* [Win 32bit](https://dl.dropboxusercontent.com/u/14269663/PortfolioPerformance-0.23.2-SNAPSHOT-win32.win32.x86.zip)

Achtung: ❗ Dateien, die mit dieser Version gespeichert werden, können nicht mehr in Version 0.23.1 geladen werden. Unbedingt mit einer Kopie arbeiten.

Build enthält Änderungen aus #10

**Comment by buchen** [comment]
Bugs per Email:

> 1. Bei einem Verkauf einer Aktie mit Gewinn taucht unter Konten -> Umsätze zwar genau wie jetzt bei den Dividenden keine separate Steuerbuchung auf, aber beim Verkauf werden die Steuern dennoch erfasst (lasse ich mir in Vermögensaufstellung -> Diagramm anzeigen). Die Steuern auf Dividenden werden aber jetzt nicht hinzuaddiert. Das müsste wohl korrigiert werden. Perspektivisch wäre auch nett, einen tabellarischen Überblick über die gezahlten Steuern zu erhalten. In einer Spalte könnte dann "Euro", in einer weiteren "Typ" stehen (Verkauf / Dividende), in noch einer weiteren Spalte das betroffene Wertpapier, in einer letzten das Konto.

> 2. Die Angabe "Stück" beim Erfassen der Dividenden irritiert mich jedes mal. Sie verleitet zu dem Gedanken, dass im folgenden die Dividende pro Aktie abgefragt würde. Trotzdem ist die Abfrage sinnvoll. Zur Klarstellung könnte man hinter den Zeilen Bruttowert bis Gutschrift so etwas wie "für alle Aktien zusammen" oder etwas professioneller "kumuliert" mit einer geschweiften Klammer um die drei Zeilen ergänzen, so dass direkt klar würde, was einzugeben ist.
