### ISSUE TITLE
Automatic and unwanted currency exchange of a security

### ISSUE THREAD

**Issue by simonsilie** [buchen/portfolio#2204]
**Describe the bug**
I have created the "Vanguard FTSE All-World UCITS ETF" as a security. The currency was set as the Swiss franc (CHF). Purchase and sale of the security is exclusively in CHF. This is also how it is to be booked.
The special thing about the ETF is that the dividend is paid in US dollars (USD). As soon as I enter the dividend via PDF import, the currency of the ETF is set to USD and can no longer be changed manually. I have two securities accounts, one in USD and one in CHF, and I enter purchases and divide to the correct account each time.
PDF document is from Swissquote Bank. I do not get any error when importing.

**To Reproduce**
1. Create security in CHF.
2. Buy security in CHF.
3. Enter the corresponding dividend in USD using PDF Import.
4. Error: Currency of the security is changed to USD and can no longer be changed manually.

**Expected behavior**
No automatic currency change of the security type or a manual change of the preservation afterwards.

**Desktop (please complete the following information):**
 - Version: 0.51.3 (Mar 2021)
 - Platform: macosx, x86_64
 - Java: 11.0.4+11-LTS, Azul Systems, Inc.

**Comment by Nirus2000** [comment]
Hello @simonsilie
please create a PDF debug as in the tutorial video and create a post 
in the PP forum named "PDF-Import von Swissquote Bank".

Video tutorial:
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

**Comment by simonsilie** [comment]
Hi @Nirus2000 ,
I've created the PP forum post:

https://forum.portfolio-performance.info/t/pdf-import-von-swissquote-bank/15835

Please let me know if there is any information missing.

**Comment by Nirus2000** [comment]
Hallo @simonsilie
You write that the security is in CHF. In witch currency is your Account?

**Comment by simonsilie** [comment]
Hi @Nirus2000 
do you mean the corresponding deposit account? Of these, I have one in CHF and one in USD.
Or do you mean the global display (top right as drop down menu). Here it says EUR.

**Comment by Nirus2000** [comment]
Hi @simonsilie
in which account were the purchases imported?

**Comment by simonsilie** [comment]
To the CHF deposit account. FYI @Nirus2000

**Comment by Nirus2000** [comment]
Hello @simonsilie
please create a PDF debug of the purchase to this security and post it in the forum.

**Comment by simonsilie** [comment]
Hi @Nirus2000 
I've added the PDF debug of the purchase into the forum post.
https://forum.portfolio-performance.info/t/pdf-import-von-swissquote-bank/15835

**Comment by Nirus2000** [comment]
Hallo @simonsilie,
Ja das habe ich mir fast gedacht. Derzeit gibt es keine Möglichkeit, die Währung des Gegenkontos zu prüfen, weil man ja viele Gegenkontos führen könnte. Daher weiß der Importer ergo auch nicht, welches Gegenkonto er nutzen soll.
Wir können nur prüfen, in welcher Währung das Wertpapier angelegt ist. 
Bei deinem Kauf, wird aber die Option ausgeschlossen, dass das Wertpapier in USD geführt wird. Darauf hatte ich gehofft.

Sprich am besten mit deiner Bank, dass diese Option in den Abrechnugen eingeführt werden muss, so dass die Dividenden in deinem Beispiel aus USD und ebenfalls schon fertig umgerechnet in CHF in der der Abrechnung geführt werden soll (Also in Kontowährung und in Wertpapierwährung). Es hilft auch nicht, das Wertpapier in USD vollständig zu führen, da hier der Umrechnungkurs fehlt. Auch das soll deine Bank in Angriff nehmen.
Sorry, dass ich dir da nicht helfen kann, hätte ich aber gern. Da hilft leider nur manuelle Pflege.

Grüße
Alex
