### ISSUE TITLE
DKB PDF Importer reports unknown booking type

### ISSUE THREAD

**Issue by fnord23787** [buchen/portfolio#2211]
**Describe the bug**
On the attached DKB Kontoauszug, the PDF importer throws an “Unknown booking type” error („Unbekannter oder nicht unterstützter Buchungstyp“) and does not import any data.

[2021-04-01-Kontoauszug_Nr_2021_003_per_2021_04_01.pdf.txt](https://github.com/buchen/portfolio/files/6305007/2021-04-01-Kontoauszug_Nr_2021_003_per_2021_04_01.pdf.txt)

**To Reproduce**
Try importing the attached PDF debug.

**Expected behavior**
The document should be imported without error.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.51.3

**Comment by Ragas13** [comment]
It's not a bug in case of security transactions because the account statement does not provide the necessary information. Please use the single buy/sell transaction pdf.

**Comment by fnord23787** [comment]
That sounds reasonable, thanks!
