### ISSUE TITLE
Flatex Dokumente werden nicht mehr erkannt.

### ISSUE THREAD

**Issue by unclejamal3000** [buchen/portfolio#2212]
Vermutlich wegen der Umbenennung auf Flatex Degiro Bank, werden die Dokumente beim Import nicht mehr erkannt.

PP Version: 0.51.3 (März 2021)

![grafik](https://user-images.githubusercontent.com/6795043/114696566-1660ff00-9d1d-11eb-9223-ff61b061f421.png)

PDF Debug Export:
[20210414_Wertpapierabrechnung_31012381674_197532070.pdf.txt](https://github.com/buchen/portfolio/files/6310171/20210414_Wertpapierabrechnung_31012381674_197532070.pdf.txt)

**Comment by Ragas13** [comment]
#2206

**Comment by eddieddu** [comment]
Genau, Mit dem identifier
        addBankIdentifier("flatexDEGIRO Bank AG"); //$NON-NLS-1$
gehts wieder.

**Comment by unclejamal3000** [comment]
Gelöst mit Version 0.52.0
