### ISSUE TITLE
JSON quote feed: Time in seconds instead of mili seconds or days

### ISSUE THREAD

**Issue by KP7984** [buchen/portfolio#2215]
**Is your feature request related to a problem? Please describe.**
Thank you for making it possible in 0.51.2 / 14. März 2021 to specify the date format when configure the JSON import for historical quotes. Nevertheless, I've got a **JSON response which** isn't defining the time in mili seconds or days since 1970 as **it's defining the time in seconds**. 

This is not possible for now right?

**Describe the solution you'd like**
I would love that to be possible :D.

**Describe alternatives you've considered**
Write in the tooltip that this is not possible :( or explain how it is possible :)

**Additional context**
Example of JSON response for time in seconds:
[onvista.de](https://api.onvista.de/api/v1/instruments/FUND/107918/eod_history?idNotation=120539918&range=M1&startDate=2021-04-01)

Thank you!

**Comment by KP7984** [comment]
I got a little confused since in [this bug](https://github.com/buchen/portfolio/issues/2106#issue-817083824) it seemed to work with seconds.

**Comment by RomanLangrehr** [comment]
That is strange, PP should handle epoch time in seconds as well (the tool tip is bad, I will update it). Can you maybe provide an example where this is not working.

PP treats numbers greater than `7258118400` as “epoch in milliseconds”, numbers smaller than `84.006` as “epoch in days” and everything in between as epoch in seconds.

**Comment by KP7984** [comment]
I'm afraid that I've used your feature in a wrong way? However, [your documentation](https://help.portfolio-performance.info/kursdaten_laden/#json) seems easily understandable...

The epoch is 1617278400 (1.617.278.400) so it should fit in between milliseconds and days.


I've tested all paths with [your recommended tool](http://jsonpath.herokuapp.com/) which found the correct arrays with equal lengths. Again, here is the link for an example JSON response: [onvista.de](https://api.onvista.de/api/v1/instruments/FUND/107918/eod_history?idNotation=120539918&range=M1&startDate=2021-04-01)
![JSON-Quotes_will_not_refresh](https://user-images.githubusercontent.com/48592359/115009442-95387200-9eac-11eb-8ccc-72e23b721737.png)

My paths:
- $.datetimeLast
- $.last
- $.low
- $.high

Could the point of a decimal separator in the quotes be an issue?
Or that the time in the epochs are GMT: 12:00:00 o'clock? 
Probably not :D

In PP I have used the following link with a dynamic date format which should also be correct as I get correct server responses as I can see in PP: https://api.onvista.de/api/v1/instruments/FUND/107918/eod_history?idNotation=120539918&range=M1&startDate={DATE:yyyy-MM-01}

**Comment by RomanLangrehr** [comment]
Just add `.[*]` at the end of each path, then it should work.

**Comment by KP7984** [comment]
It's working like a charm! Thank you very much and sorry for the inconvenience! 

Can I contribute in any way to improve [the documentation](https://help.portfolio-performance.info/kursdaten_laden/#beispiele) as it says "Beide Ausdrücke müssen ein Array zurückgeben." which is quite irritating in combination with the stated tool to test the paths in my case?
