### ISSUE TITLE
Risikomaß eines Portfolios

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#223]
> Ein Risikomaß eines Portfolios z.B. in Form von maximalen Drawdown, Standartabweichung oder Varianz.

**Comment by simpsus** [comment]
Das hatten wir in anderer Form ja schonmal, ich glaube mich an die sharpe ratio zu erinnern.
Das ganze ist damals daran gescheitert (bei mir) dass ich es nicht geschafft habe, auf die <Datum, Wert> Reihen der Securities zuzugreifen

**Comment by simpsus** [comment]
Das ist mit 16.1 live.
