### ISSUE TITLE
Some closed positions show in Securities tab

### ISSUE THREAD

**Issue by ngosang** [buchen/portfolio#2255]
**Describe the bug**
I have around 20 closed positions (different securities) and 5 open positions. Open positions are fine but I have a problem with closed positions. 2 of them show in the Securities tab. The expected behavior should be to hide those stocks in the security tab too.

**To Reproduce**
I don't know how to reproduce.

**Expected behavior**
Securities without shares should be hidden in Securities tab.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10577978/118395445-cee6cf00-b64a-11eb-9861-8341b9af3f15.png)

**Desktop:**
Version: 0.52.0 (Apr 2021)
Platform: win32, x86_64
Java: 11.0.4+11-LTS, Azul Systems, Inc.

**Comment by paurisa** [comment]
The default behavior is to show all securities even if you closed the position and do not currently have any shares in them.

You can apply a filter to hide those securities in which you do not have any shares. You just have to select the funnel icon:

![Screenshot from 2021-05-16 10-04-28](https://user-images.githubusercontent.com/7051536/118400349-3f7ff280-b62f-11eb-944b-886be2c3a8b1.png)

And then select the filtering option "Shares held > 0":

![Screenshot from 2021-05-16 10-07-28](https://user-images.githubusercontent.com/7051536/118400377-5b839400-b62f-11eb-8540-ef0480d08929.png)

Hopefully this helps you. Maybe we should change the default Securities view to only display securities in which a position is open with more than 0 shares?

**Comment by ngosang** [comment]
I see, there is no but. Thank you!
