### ISSUE TITLE
"Statement of Assets" tab missing in 0.53.0

### ISSUE THREAD

**Issue by roshanshariff** [buchen/portfolio#2277]
**Describe the bug**

In version 0.52.0, in the Accounts > Securities Accounts view, clicking on a particular account would show an info pane with two tabs, "Statement of Assets" and "Transactions". In the just-released version 0.53.0, the "Statement of Assets" tab is missing and only a button labelled "Transactions" is visible.

**To Reproduce**
1. In the left navigation bar, click on "Securities Accounts".
2. Choose one of the accounts from the list on the right.
3. Look at the lower info pane.
4. There is a "Transactions" button but no "Statement of Assets".

**Expected behavior**
As in the previous 0.52.0 version, there should be two tabs: "Statement of Assets" and "Transactions".

**Screenshots**

![Screenshot from 2021-06-13 14-16-13](https://user-images.githubusercontent.com/552952/121820815-fd5bc800-cc51-11eb-8933-1d4188924262.png)

Compare to version 0.52.0:

![Screenshot from 2021-06-13 14-17-55](https://user-images.githubusercontent.com/552952/121820866-46ac1780-cc52-11eb-9772-1dc06d49e220.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.53.0

**Comment by chirlu** [comment]
I noticed this, too. In addition, the “data quality” sub-tab is missing from the security view; it used to show the dates for which no quotes are present, as well as the percentage of those days.

**Comment by buchen** [comment]
Linux... it should be there... will try to fix tonight

**Comment by Nirus2000** [comment]
hmm... das Zusatzmenü kann auch in jedem Menüpunkt aktiviert werden...
![grafik](https://user-images.githubusercontent.com/45203494/121907891-c73f4680-cd2c-11eb-88af-e1d375f334d8.png)
![grafik](https://user-images.githubusercontent.com/45203494/121908150-ffdf2000-cd2c-11eb-8020-3f92b3ff3f15.png)

im Performance-Menü sieht das ganze dann so aus...
![grafik](https://user-images.githubusercontent.com/45203494/121908533-65331100-cd2d-11eb-878a-44770d0995d2.png)

In der Vermögensaufstellung wären bei Konten keine Informationen angezeigt und sollte aber den
Kontenverlauf, sowie die Umsätze wie unter Stammdaten -> Konten angezeigt werden.
![grafik](https://user-images.githubusercontent.com/45203494/121909197-fdc99100-cd2d-11eb-92cf-b1ccdaa64eca.png)

**Comment by buchen** [comment]
@roshanshariff  - thanks for reporting.

It looks like the problem is the indentation of toolbar items - that's why I was calculating the wrong size of the toolbar and that's why the last item was hidden away. The problem existed before, but apparently you never noticed the missing button in the top toolbar to add new views...

Can you test if this build works for you?
https://www.dropbox.com/s/xelezkc4clw1qoh/PortfolioPerformance-0.53.1-SNAPSHOT-linux.gtk.x86_64.tar.gz?dl=0

**Comment by roshanshariff** [comment]
Great! I tested that build and I can confirm that both the tabs appear, as well as the buttons on the right to export data to CSV and change columns  :slightly_smiling_face: Here's a screenshot:

![Screenshot from 2021-06-14 17-48-07](https://user-images.githubusercontent.com/552952/121972607-b7c5fa80-cd38-11eb-8cc8-ed54ace230e4.png)

I also checked that the issue reported by @chirlu is fixed; the "Data Quality" tab does appear in the Securities view, along with the options to select time horizon and chart options.

Thanks for your quick response!

P.S. I noticed a separate bug, not new to this version and not that serious: In most of the table views, if you "Reset Columns" then all the text in the table disappears until you go to another view and come back to the table... Perhaps I should file this as a separate bug?

**Comment by buchen** [comment]
> I noticed a separate bug, not new to this version and not that serious: In most of the table views, if you "Reset Columns" then all the text in the table disappears until you go to another view and come back to the table... Perhaps I should file this as a separate bug?

Yes, please.

I am not using Linux myself (I am developing on and using macOS). Most of the time, I am just "hoping" that the SWT Framework sufficiently abstracts the platforms away. But every once in a while there a those glitches and I do not necessarily notice those differences. So thanks for reporting
