### ISSUE TITLE
Kategorie "Realisierte Kurserfolge" in Performance-Berechnung

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#228]
Aus dem Wertpapier-Forum:

> Dann noch eine Frage: Gibt es eine Möglichkeit auf Ebene eines einzelnen Wertes nur die realisierten Erträge (Verkaufsgewinne minus Kosten plus Dividenden/Zinsen) anzuzeigen ? Die Spalte Erträge berechnet ja Kursgewinne, als nicht-realisierte Erträge mit.

Eventuelle passende Spalte auch in die "Performance -> Wertpapiere" Tabelle.

Aber: abhängig von Währungen #14 da ich da einiges umbauen musste

**Comment by buchen** [comment]
Oder auch

> Gibt es schon eine Idee, wie dort auch Verkaufserlöse (z.B. durch Teilverkäufe im Rebalancing) eingehen könnten ?

**Comment by buchen** [comment]
Und wieder

> Mir fehlt eine Anzeige der unrealisierten Kursgewinne zu Ende eines Betrachtungszeitraumes in der Performance (Hier würde es zusätzlich das Problem geben, dass ich entweder teilweise oder vollständig steuerfreie Dividenden erhalten habe, die den Einstiegskurs herabsetzen: Die Herabsetzung des Einstandskurses sollte direkt mit der Dividendeneingabe verknüpft werden) Eine Eingabe des persönlichen Versteuerungssatz (derzeit 26,4%) wäre sinnvoll, um den wahren Wert bei Liquidation zu erfahren. So könnte man sein reales Vermögen besser schätzen und über die Jahre vergleichen, indem große realisierte Gewinne eines Jahres somit keinen entscheidenden Einfluss mehr haben. Die derzeitig angezeigten Endwerte bestehen ja nur virtuell.

**Comment by buchen** [comment]
Und wieder

> Wäre es möglich in der Performance-Berechnung im Reiter "Berechnung" die Kurserfolge noch in "realisierte" (also verkaufte) und "nicht realisierte" zu trennen?

**Comment by lopiuh** [comment]
Hi,

"Die Herabsetzung des Einstandskurses sollte direkt mit der Dividendeneingabe"

Das wären dann aber zwei verschiedene "Einstandskurse" zur Transaktion. 1. Der für die GuV für die  Performanceberechnung und 2. der für die Ermittlung des steuerlich relevanten Gewinnes. Wenn es nur einen  Einstandskurs gibt, dürfte der nicht einfach herabgesetzt werden, da sonst die GUV falsch wird (der tatsächliche Kaufpreis ist ja nicht reduziert und Geld (zusätzlich zur Dividende) erstattet worden. Für die steuerliche Bewertung ja, um die Dividende aus Kapitalrückstellungen nachträglich zu versteuern. (richtig?)

Gruß

lopiuh

**Comment by buchen** [comment]
Hi @lopiuh, das sehe ich ähnlich. Ehrlich gesagt habe ich mir den Kommentar hier gemerkt weil wieder mal jemand nach dem Feature "realisierte vs. nicht-realisierte Kursgewinne" gefragt hat. Es ging mir gar nicht um die steuerliche Betrachtung einer vollständig oder teilweise steuerfrei erhaltenen Dividende. Ehrlich gesagt weiß ich gar nicht wie weit ich bei den Steuern gehen will: das ändert sich ständig, ist in Österreich anders als in Deutschland, etc.

**Comment by buchen** [comment]
<img width="939" alt="Bildschirmfoto 2020-02-23 um 19 17 32" src="https://user-images.githubusercontent.com/587976/75117785-e23c0200-5674-11ea-8088-c11af2ee3927.png">
