### ISSUE TITLE
Ereignisse von Dividendenzahlungen in falscher Währung

### ISSUE THREAD

**Issue by Nirus2000** [buchen/portfolio#2283]
**Describe the bug**
In der Wertpapierübersicht werden die Ereignisse der z.B. für Dividendenzahlungen in der falschen Währung
wiedergegeben. Wertpapier ist in EUR angelegt, jedoch werden diese im Betrag als USD ausgegeben.

**To Reproduce**
1. Hauptmenü -> "Wertpapiere" oder in "Vermögensaufstellung
2. STRG-L für einblenden
3. Wechseln auf TAB "Ereignisse

**Screenshots**
![grafik](https://user-images.githubusercontent.com/45203494/122438536-18ed0880-cf9b-11eb-8a68-09724f75914b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H
 - Version  0.53.1 (Juni 2021)

**Comment by chirlu** [comment]
Der Fonds schüttet in Dollar aus, also wird die Datenquelle (DivvyDiary? Portfolio Report?) das auch so melden.

**Comment by Nirus2000** [comment]
Danke @chirlu,
das macht natürlich Sinn... 😄
