### ISSUE TITLE
CSV Import Portfolio Transaction has Invalid Mapped to Field

### ISSUE THREAD

**Issue by flywire** [buchen/portfolio#2334]
**Describe the bug**
The second field is invalid in English

**To Reproduce**
File, Import, CSV, set to Portfolio Transaction

**Expected behavior**
The second field should not occur in English

**Screenshots**
![image](https://user-images.githubusercontent.com/11288701/125744492-fc71584d-f746-4da4-b2cd-e74dc2de0b95.png)

**Desktop (please complete the following information):**
- Version: 0.53.3 (Jun. 2021)
- Platform: win32, x86_64

**Comment by Nirus2000** [comment]
Thx and done...
