### ISSUE TITLE
Delete "Unnecessary Code" in PDF Importer 

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#2341]
Eclipse reports that a couple of methods in the category of "Unnecessary Code":

<img width="1128" alt="Bildschirmfoto 2021-07-18 um 08 40 13" src="https://user-images.githubusercontent.com/587976/126059551-b21ebfcd-2ab9-4a31-a2b1-6926d14e50a1.png">

@Nirus2000 - Can you delete / refactor the code?

**Comment by Nirus2000** [comment]
Hallo @buchen 
diese Code ist als "Vorbereitung" für die jeweiligen Importer eingefügt. Sobald Gebühren oder Steuern
in den jeweiligen PDF's vorhanden sind, wird dieser durch die regEx-Bedingungen aktiviert.

https://github.com/buchen/portfolio/blob/f7a53a2dbdc938b29f9d2d7cd07b6c743da97139/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/WeberbankPDFExtractor.java#L239

Soll ich diese trotzdem fix entfernen?!

**Comment by buchen** [comment]
> Soll ich diese trotzdem fix entfernen?!

Ich habe sie rausgenommen. Ich versuche nach Möglichkeit keine Meldungen in Eclipse zu haben.

Hier frage ich mich ja, ob die Methode nicht so generisch ist, dass die in die super class gehört. Könnte nicht die Klasse ```PDFExtractorUtils``` auch schon den instanceof check machen?
