### ISSUE TITLE
Menüleiste wird nicht übersetzt

### ISSUE THREAD

**Issue by Beluk** [buchen/portfolio#235]
Sowohl in Deutsch auch in English: 
%menu.file.label
%menu.online.label
%menu.help.label

**Comment by buchen** [comment]
Hi,

Könntest Du mir sagen auf welcher Platform Du läufst? Win, Linux, Mac? 32/64bit?

Dann wäre es super wenn ich die komplette LogDatei haben könnte. Die liegt im Programmverzeichnis unter ```workspace/.metadata/.log```

Ich vermute mal, wenn Du das Programm mit ```PortfolioPerformance --clearPersistedState``` startest, könnte es wieder okay sein.

**Comment by Beluk** [comment]
Läuft bei mir unter Windows 8.1 64 bit. Der Parameter hat einwandfrei funktioniert. Wo soll ich dir die Logdatei hinschicken?

**Comment by buchen** [comment]
andreas dot buchen at gmail dot com

Keine Ahnung warum (manchmal?) der Parameter nicht zieht. Ich setze den eigentlich nach einem Update.... ich hoffe das Log kann mir Aufschluss geben.

**Comment by buchen** [comment]
Ich habe mal "-clearPersistedState" by default gesetzt und mehr Logging eingefügt: 7d5b7154f3d04cdcdbf5141ec59a129e0adfe8fb
