### ISSUE TITLE
ASX feature request

### ISSUE THREAD

**Issue by ismogal12** [buchen/portfolio#2351]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
1. CGT(Tax) discount if the holding period is more than 12 months.
    In ASX you can get a tax discount of 50% for individuals if the holding period is more than 12 months. 
2. Ability to calculate LIFO, I think currently it only does FIFO:
     If frequently trading, you can choose the LIFO method to select the most recent parcel to sell rather than the First one. 

**Describe alternatives you've considered**
I don't think there are considerations done for far under ASX. 

**Additional context**
Refer to CGT: https://www.ato.gov.au/General/Capital-gains-tax/Working-out-your-capital-gain-or-loss/Working-out-your-capital-gain/The-discount-method-of-calculating-your-capital-gain/

Looking forward to these requests, and may be able to contribute if required.

**Comment by flywire** [comment]
Have you tested these issues in Portfolio Performance? What are the results?

I suggest issue would be more meaningfully named as `Calculate Capital Gains`. It is a good suggestion but it is unlikely to be actioned because there are other priorities, and tax is complicated varying significantly between countries.

Consolidation should be removed from this issue and raised separately.

**Comment by Nirus2000** [comment]
Hello and welcome,
Therefore, log in to the forum at [https://forum.portfolio-performance.info/](https://forum.portfolio-performance.info/) and create a thread with the name "PDF-Importer CommSec"

For a PDF-Importer we need examples of buy, sell, dividend and so on.... post it there.
You can see how this works in the video tutorial.

Video tutorial:
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

**Comment by ismogal12** [comment]
These are not issues but feature requests, if 1 and 2 are most likely not going to happen, can we consider Consolidation here or do you want me to raise a new one?

**Comment by flywire** [comment]
This whole area of the repository contains issues (including feature requests). Yes, I'm suggesting put the consolidation point in a new issue then edit [the first post](https://github.com/buchen/portfolio/issues/2351#issue-952073155) and remove it.

btw, I haven't seen your post in the forum. I'm interested in CommSecPDFExtractor. Would you like to email [me](https://github.com/flywire)?

**Comment by ismogal12** [comment]
Thanks, flywire, yes I have raised it on the English forum, but I get the message will be reviewed by the moderator, and I cant find the two posts(see here also [Link](https://github.com/buchen/portfolio/pull/2340#issuecomment-886052620). 

I have also edited the first post and created a new one for Consolidation [#2354].

**Comment by flywire** [comment]
@buchen this issue has nothing to do with #2383

> I suggest issue would be more meaningfully named as `Calculate Capital Gains`.
