### ISSUE TITLE
Expand/Collapse Sidebar/Infopane

### ISSUE THREAD

**Issue by flywire** [buchen/portfolio#2355]
Users must go through the View, Option, ... to expand/collapse sidebar or infopane.

A reversable triange could expand/collapse the panes. eg:

![image](https://user-images.githubusercontent.com/11288701/127467841-7b0e751e-3f21-478d-ba48-a299755453a7.png)

**Comment by chirlu** [comment]
> Users must go through the View, Option, ... to expand/collapse sidebar or infopane.

Or press Ctrl-L or Ctrl-K.

**Comment by flywire** [comment]
It's a pain doing that with a mouse.

**Comment by buchen** [comment]
@flywire 

There are keyboard shortcuts.

Ctrl-K (or on mac Command-K) shows/hides the sidebar
Ctrl L (or on mac Command-L) shows/hides the info area

At least on mac, the menu also includes the shortcuts.
<img width="576" alt="Bildschirmfoto 2023-06-25 um 18 32 15" src="https://github.com/buchen/portfolio/assets/587976/2b0e133c-b7f3-4848-b508-7a563396ea45">

Can you please check?

**Comment by buchen** [comment]
(please reopen this issue if it does not work)

**Comment by flywire** [comment]
Issue title updated to specifically refer to gui (as noted in comments). This functionality is used sufficiently often to provide GUI support.

> (please reopen this issue if it does not work)

I don't have the privileges to reopen the issue but the issue remains.

**Comment by pfalcon** [comment]
> At least on mac, the menu also includes the shortcuts.

Confirming also visible on Linux. (Just mentioning this because appears some complex shortcuts aren't visible on Linux, https://github.com/buchen/portfolio/issues/3308).
