### ISSUE TITLE
Diskussion: Risikokennzahlen

### ISSUE THREAD

**Issue by simpsus** [buchen/portfolio#236]
1) Der Text der Labels ist sehr "denglisch". Ich versuche später mal das ein wenig deutscher zu machen
2) Der Hinweis von Dir, dass sqrt(2) * semi = vola bei gleichverteilter Abweichung gilt ist super. Damit könnten wir doch aus der Vola die semi' vola berechnen, bei der die Schwankungen gleichverteilt wären. Das könnten wir dann mit der semi anzeigen und somit einen Bezug herstellen. So hängt die semi ziemlich in der Luft.
3) Du hast im forum geschrieben, dass in einem nächsten Schritt die Vola einzelner Papiere kommt. Das ist super, aber für einzelne Wertpapiere kann man das simpel auch im Internet nachschauen. Ich denke das killer feature ist wenn das mit klassifizierungen zusammen kommt und man zb schauen kann, wie hoch die vola seiner rentenpapiere ist um zu schauen ob man beim nächsten zukauf etwas forscher sein kann oder doch besser nicht. Die Berechnung der Vola ist denke ich generisch genug. Das Problem ist eher in der gui. Wie bringen wir das wo unter, sodass es hilft, gefunden wird und nicht verwirrt?
4) Es gibt noch einige weitere Risikokennzahlen. Mit der Vola könnten wir aber auch in Richtung Performance Kennzahlen weiter denken (sharpe Ratio). Was ist Deine Position dazu? Ich würde das gerne angehen, aber wenn es für dich nicht wichtig ist, logo nicht.

**Comment by buchen** [comment]
> Der Text der Labels ist sehr "denglisch". Ich versuche später mal das ein wenig deutscher zu machen

Gerne. Ich bin nicht so der große Schreiberling. Wenn Du einen separaten Pull Request machst, kann ich den gerne mergen.

> Damit könnten wir doch aus der Vola die semi' vola berechnen, bei der die Schwankungen gleichverteilt wären. 

Stimmt. Ich denke das könnte man auch in dem Tooltip anzeigen. Genauso wie ich den Interval des Maximum Drawdown im Tooltip anzeige. Dann entsteht auf der Übersichtsseite kein Wirrwarr, und trotzdem kommt man an alle Informationen ran.

> das killer feature ist wenn das mit klassifizierungen zusammen kommt [...]
> Das Problem ist eher in der gui. Wie bringen wir das wo unter, sodass es hilft, gefunden wird und nicht verwirrt?

Man könnte doch Spalten in der Klassifizierungs-View hinzufügen, die der User über den "Config" Knopf oben rechts hinzufügen kann. Dann hat man je eine Zelle pro Kategorie. Später (in einem separaten Change) könnte man auch die Performance selbst hinzufügen.

Meines Erachtens müsste man schauen ob das a) schnell genug berechnet werden kann (es sind ja viele PerformanceIndex Objekte), dann werden b) die Berichtszeiträume momentan nur implizit im Stapeldiagramm genutzt. Das müsste man vielleicht besser exponieren.

Und momentan hat die Berechnung der Volatilität noch ein Problem: wenn man keine Bestände mehr hat, dann bleibt die Delta Performance bei 0 gegen Ende der Datenreihe. Dann ist die Volatilität natürlich viel zu niedrig. Beim Gesamtportfolio tritt das wohl selten aus (wer schaut sich im Programm schon sein aktuelle Portfolio mit 0 Gesamtwert an) aber bei Kategorien kann das aber ja schon der Fall sein.

> Es gibt noch einige weitere Risikokennzahlen. Mit der Vola könnten wir aber auch in Richtung Performance Kennzahlen weiter denken (sharpe Ratio).

Warum nicht? Solange das Programm nicht zu einer Kakophonie von Zahlen verkommt, macht das Sinn.

**Comment by simpsus** [comment]
Ich denke das ist hinreichend besprochen und wir haben ja die pull requests zum diskutieren
