### ISSUE TITLE
Report Combined Security Across Accounts

### ISSUE THREAD

**Issue by flywire** [buchen/portfolio#2361]
I have multiple securities accounts, some of which contain the same securities. Reports (including charts) report each security within each account.

The default should be to report the security once as the total of all accounts. Grouping by security or by security account should be optional.

See https://forum.portfolio-performance.info/t/reporting-across-multiple-security-accounts/17381

**Comment by chirlu** [comment]
The forums are a better place for support questions. Please give more details when asking there;
> Reports (including charts) report each security within each account.
is not enough to understand what your problem is.

**Comment by flywire** [comment]
The feature is supported. The issue is apparently due to security configuration.

**Comment by flywire** [comment]
> The forums are a better place for support questions.

There wouldn't have been a response unless it was raised as an issue.
