### ISSUE TITLE
Fehler bei import von Kursen aus HTML Tabelle

### ISSUE THREAD

**Issue by ms5** [buchen/portfolio#237]
Ich versuche z.B. die Kurse von UBS von der Tabelle aus finanzen.ch [1] zu extrahieren und importieren. Dabei paste ich ausschliesslich den "table" block aus dem HTML source code in das import Feld. Das Datum und Kurse werden danach gelesen und in der Übersicht angezeigt. Das Datum stimmt jeweils, jedoch die Kurse nicht. Diese sind um den Faktor 100 zu gross. Anstatt eines Kurses von 15.60 wird ein Kurs von 1560.00 angezeigt. Ich vermute, dass es etwas mit dem Decimal separator "." anstatt wie sonst in Portfolioperfomance üblich "," zu tun hat. 

[1] http://www.finanzen.ch/kurse/historisch/UBS_Group/SWL/10.1.2014_10.2.2015

nachtrag: bei Finanzen.net wird tatsächlich der Kurs mit einem "," als Dezimalseparator ausgewiesen. Auf Finanzen.ch jedoch mit einem ".". Leider sind auf Finanzen.net und .ch andere Börsenplätze verfügbar. So ist z.B. die Schweizer Börse SIX auf Finanzen.net nicht verfügbar.

**Comment by buchen** [comment]
> Ich vermute, dass es etwas mit dem Decimal separator "." anstatt wie sonst in Portfolioperfomance üblich "," zu tun hat.

Das stimmt. Ich habe jetzt den Code erweitert und unterstütze auch den "." als Dezimaltrennzeichen.

Die URL [1] funktioniert leider trotzdem nicht. Die Kurse sind nicht direkt in der Seite, sondern werden durch eine JavaScript (Code) nachgeladen. Der Code manipuliert dann den DOM-Tree direkt. Wenn man im Browser "Als HTML kopieren" auswählt und das dann nach PP kopiert, dann werden die Kurse korrekt importiert.

![bildschirmfoto 2015-02-22 um 07 37 13](https://cloud.githubusercontent.com/assets/587976/6317723/aad61702-ba65-11e4-81d8-da846057306a.png)
