### ISSUE TITLE
Vorschlag: Hoch und Tief Linien im Performance Chart

### ISSUE THREAD

**Issue by simpsus** [buchen/portfolio#241]
Ich bin skeptisch ob Du das gut findest oder nicht, aber man könnte horizontale Linien bei dem Hoch und dem Tief einziehen. Das würde die Spanne der Schwankungen visualisieren. Man könnte auch besser einschätzen, wie weit ein bestimmter Wert (meistens der aktuelle) vom hoch oder tief entfernt ist.

Thoughts?

**Comment by buchen** [comment]
(Ich hätte schwören können ich habe schon mal geantwortet :-( Sei's drum...)

Könnte man machen. Wenn, dann über das Konfig-Menü an/ausschaltbar.
Vielleicht aber vorher überhaupt mal ausprobieren wie das "aussieht" und welchen Mehrwert das bringt. Mir fällt sowas immer schwer als Trockenübung.

**Comment by simpsus** [comment]
Ich habe mir das mit der lib angeschaut.
Leider geht da garnix mit. 

Ich wollte ungefähr sowas machen:

![image](https://cloud.githubusercontent.com/assets/1447101/6514117/4ea6fbbc-c380-11e4-93d3-860f244c41d6.png)

- Chart von max-akkumuliert bis oben transparent grau
- Chart von min-akkumuliert bis unten transparent grau
- Max Drawdown duration einzeichnen
- Peak (angedeuted) und low (nicht gezeigt) kennzeichnen
- max drawdown kenntlich machen (nicht angezeigt)
- Die area von akkumuliert grün machen wenn > 0 und rot wenn <0

genau nichts davon ist mit der lib möglich.

**Comment by buchen** [comment]
> genau nichts davon ist mit der lib möglich.

Ich habe schon mal überlegt eine JavaScript Bibliothek wie http://d3js.org einzubetten. Man müsste schauen ob man in dem Browser Widget das laufen lassen kann, wie man die Java <-> JavaScript Kommunikation hinbekommt und ob das auf den verschiedenen Plattformen (Linux, Windows, Mac) gut aussieht. Dann hätte man aber alle Optionen... im JavaScript Bereich findet so viel Entwicklung statt.

SWTChart ist gar nicht so schlecht (klein, schnell), aber wenig interaktiv und nicht viele Optionen. Ich habe anfangs BIRT verwendet und dann rausgeschmissen. Und man kann sich immer auch den Canvas schnappen und direkt malen...

**Comment by simpsus** [comment]
Ich habe überhaupt nichts gegen SWTChart. Super klein und schnell. Halt nicht mehr.
Mein Chart Mockup oben macht auch nicht für alle Anwendungsfälle sinn. Hat man nur eine Series oder die akkumulierte Linie nicht, dann bringt das nichts. Auch habe ich keine Ahnung ob andere User die Risiko Werte so visualisiert sehen wollen. Für mich macht es das erst so greifbar.

Leider ist das nicht meine Kernkompetenz, zu schauen wie man in das alles am besten hinbekommt.
Mein erster google versuch hat mich hierhin geführt:

https://github.com/ralfstx/rap-d3charts
http://eclipsesource.com/blogs/2013/07/18/visualizing-data-with-d3/

Ich habe früher mal an einer anderen lib mitgebastelt, und dort war der beste output SVG. D3 kann SVG ausgeben und es gibt ein Canvas (ich glaub von apache) welches SVG darstellen kann. Ob das kompatibel ist keine Ahnung. Für mich klingt ein browser widget auf den ersten blick nicht gerade schlank.

Sag bescheid was ich tun kann und ich versuchs.
