### ISSUE TITLE
Update to 2021-09 once it is available to get nicer close icons

### ISSUE THREAD

**Issue by vogella** [buchen/portfolio#2410]
Looking at your screenshots of https://www.portfolio-performance.info/ reminded me how ugly the Eclipse close icon is. I updated it for the 2021-09 release and hope that your software benefit from it, in case you can build against 2021-09 after its release.

![image](https://user-images.githubusercontent.com/139910/131979873-74c2e6cc-af6c-4ddd-bede-9d250077d41f.png)

**Comment by buchen** [comment]
Thanks @vogella

I do have a branch against 2021-06 in order to build macOS aarch64. I plan to update to 2021-09 before merging that into the master branch.

**Comment by buchen** [comment]
Updated.
