### ISSUE TITLE
"Berechnung"-Tab: Editieren von Wertpapiernamen möglich

### ISSUE THREAD

**Issue by tsohst** [buchen/portfolio#2417]
**Describe the bug**
Im Tab "Berechnung" lassen sich Wertpapiernamen Namen in jedem Feld/Spalte ändern

**To Reproduce**
1. Berechnung-Tab
2. Links-Click z.B. auf den aktuellen Wert (Zahl - siehe Screenshot) -> Irgendetwas reinschreiben
3. "Wertpapiere" Tab -> Hier ist jetzt das Wertpapier den Namen den wir eben geschrieben haben

**Expected behavior**
Editieren sollte im Tab "Berechnung" nicht möglich sein?

**Screenshots**
![image](https://user-images.githubusercontent.com/32710648/132211983-8cda9f7a-5da2-44d0-a8e8-bd4e8349cb43.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - v0.54.3

**Comment by chirlu** [comment]
> Editieren sollte im Tab "Berechnung" nicht möglich sein?

Warum?

**Comment by Nirus2000** [comment]
Duplicate of #2404

**Comment by chirlu** [comment]
Keine Dublette. Hier ist der Wunsch, daß das Bearbeiten (aus dieser Ansicht) überhaupt nicht möglich sein solle.

**Comment by Nirus2000** [comment]
Das Problem wurde mit #2412 schon behoben und sollte beim nächsten Release mit dabei sein.
So... @tsohst bitte dieses Issue schließen. 
Danke

**Comment by chirlu** [comment]
Nee … Behoben wurde, daß ein einfacher Klick statt Doppelklick den Änderungsmodus aktiviert hat. Man kann aber weiterhin Wertpapiernamen aus dem Berechnung-Reiter heraus ändern (eben mit Doppelklick).

**Comment by Nirus2000** [comment]
Hallo @chirlu 
Folgendes wurde behoben im PR #2404 + #2412

1. Reiter "Berechnung"
  Spalte "Wert" kann nicht mehr editiert werden d9ee41e56531347bbd9fee053c6948f8cdb8fc4b
  Spalte "Bezeichnung - einfacher Doppelklick in den Bezeichnungen wurde durch Doppelklick ersetzt 76365379f99bb97cd148bce7d68bcfa2f47db300
  das Berechnungsevent wird neu ausgelöst, wenn die Bezeichnung geändert wird, da sich die Labels der geänderten Bezeichnung
  bei multiplen vorhanden sein nicht mit geändert haben. d9ee41e56531347bbd9fee053c6948f8cdb8fc4b
2. Reiter "Trades"
  Spalte "Name" - einfacher Doppelklick in den Bezeichnungen wurde durch Doppelklick ersetzt 76365379f99bb97cd148bce7d68bcfa2f47db300

Es sollte also alles erledigt sein.

**Comment by tsohst** [comment]
>    Spalte "Wert" kann nicht mehr editiert werden [d9ee41e]

Gilt das auch für die Spalte "davon Fremdwährungsgewinne"? - Kann man nämlich genauso editieren.

**Comment by Nirus2000** [comment]
Ja, es wurde für beide korrigiert 👍🏻

**Comment by tsohst** [comment]
Top 👍 Dann warte ich mal auf das Release -  Issue kann zu :)
