### ISSUE TITLE
Taxonomy Pie Charts Often Don't Appear

### ISSUE THREAD

**Issue by metal450** [buchen/portfolio#2423]
**Describe the bug**
Sometimes, when I visit one of the Taxonomies & view it as "Pie Chart," nothing appears - the screen is just white.  Screenshot is below.

If I quit & re-launch the software, the isue is fixed - the chart will appear. But some time later - i.e. if I switch to Statement of Assets, and then back to Taxonomies, it will again show only white, and to view the charts again, I have to fully quit & re-launch the application.

**To Reproduce**
It's sporadic, but set a Taxonomy on pie chart, & then switch to some other views, and back.  Eventually, when visiting the taxonomy, the chart won't appear.

**Expected behavior**
The pie chart should always appear, not requiring a quit & re-launch of the software

**Screenshots**
![2021-09-16 21 24 42](https://user-images.githubusercontent.com/1877409/133723940-bf262441-6e24-446f-ba47-cd8c466eb430.png)

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu 20.04
 - Version 0.54.3

**Comment by chirlu** [comment]
Duplicate of #2193.

**Comment by metal450** [comment]
K, closed & +1'ed there. Looks like this is a pretty prevalent bug that's experienced by many.
