### ISSUE TITLE
Microsoft Dividend PDF Import Problem from Comdirect

### ISSUE THREAD

**Issue by IIIskiplikIII** [buchen/portfolio#2424]
**Describe the bug**
Hi everyone,
I have an import problem with the dividend pdf from microsoft from my broker comdirect. When I try to import it via "Datei" -> "Importieren" -> "PDF Bankdokument" it is not able to recognize that I already have the stock Microsoft in my depot. Previous dividends work pretty well, it started with the current dividend document from 9th September 2021.

**To Reproduce**
1. Go to 'Datei / Files' -> 'Importieren / Import' -> 'PDF Bankdokumente / PDF Bank Documents'
2. Select the dividend document from Microsoft
3. In the upcoming window 'Buchungen aus PDF-Datei importieren / Import transactions from PDF files' you can see that PP didn't recognize the stock that I already have in my securities account. Instead it tries to add a new stock named 'M  i c ro s  of  t C o  rp  .' See the screenshots
4. ![image](https://user-images.githubusercontent.com/44728263/133748397-04128c19-b194-4447-b169-d2a019bbf07f.png)
5. ![image](https://user-images.githubusercontent.com/44728263/133748257-02dabcff-3766-41ad-b890-b185137179e1.png)
6. Therefore I think there is a problem in reading the correct stock name out of the dividend pdf file. Comdirect probably changed the structure of the pdf files
7. I also attached the pdf file converted (Debug: Text from PDF ...) from the function out of PP: [Dividendengutschrift_WKN_870747(MICROSOFT____DL-00000625)_vom_09.09.2021800222_dummy.pdf.txt](https://github.com/buchen/portfolio/files/7184057/Dividendengutschrift_WKN_870747.MICROSOFT____DL-00000625._vom_09.09.2021800222_dummy.pdf.txt)

**Expected behavior**
I would suggest that the dividend will be booked on the already existing stock from screenshot number 5

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.54.3 (Aug 2021)

**Comment by chirlu** [comment]
You could try adding the WKN to your existing security.

**Comment by IIIskiplikIII** [comment]
> You could try adding the WKN to your existing security.

I thought about that myself, if it works it would be a nice way too but the problem is that it worked before, so something (in the document) must have changed, therefore I wanted to let the developers know.

**Comment by Nirus2000** [comment]
Hallo @IIIskiplikIII 
Is fixes #2425 with next release :-)

**Comment by IIIskiplikIII** [comment]
@Nirus2000 Thanks, great to hear that. Looking forward to the upcoming release
