### ISSUE TITLE
Diagramm zu Volatilität vs Rendite

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#244]
Aus dem Wertpapier Forum (von "Der_Seher")

> Wie ich gerade gelesen habe, sollen in Zukunft auch Volatilitätskennzahlen für jedes einzelne Wertpapier auf Basis der historischen Performance angegeben werden. Das wäre ja echt super. Dann kann man endlich das Verhältnis der Rendite zum Risiko sehen. Ein Vorschlag hierzu von meiner Seite: Zur Darstellung der Kennzahlen wäre es super, wenn man ein oder zwei neue Diagrammen integriert könnte, in dem das gesamte Portfolio nach den Risiko- und Renditekennzahlen darstellt werden. Hierzu habe ich zwei Diagramm-Vorschläge:

> 1. Auf Ebene der Einzelwertpapiere über das gesamte Portfolio:
![post-11634-0-44900800-1423997410_thumb](https://cloud.githubusercontent.com/assets/587976/6204574/96eda8aa-b550-11e4-93a9-d701c28bdc2e.png)

2. Auf Ebene des Portfolios im Vergleich zu Benchmarks (Marktindizes etc.):
![post-11634-0-21607300-1423997469_thumb](https://cloud.githubusercontent.com/assets/587976/6204575/b6a0b50c-b550-11e4-87a7-fd8c179d3a44.png)

Ähnlich zu dem Performance Diagramm sollte man beliebige Datenreihen dem Diagramm hinzufügen können.

**Comment by simpsus** [comment]
Die Charts sind "simple" (x,y) Charts. Die zu zeichnen dürfte das kleinste Problem werden.
Es wird eher der Aufwand sein, die Daten zusammen zu saugen.
Also wir müssen von den Wertpapieren die Performance und die Vola berechnen. Dazu muss im Prinzip eine Art "PerformanceIndex" für jedes der Papiere gemacht werden.

Im jetzigen Performance Diagramm kann man ja schon die einzelnen Securities hinzufügen. 
In welcher Klasse würdest Du sowas ansiedeln?
Willst Du das selbst machen?

**Comment by buchen** [comment]
Ich will mir das am Wochenende mal vornehmen. Ich denke die Auswahl der Wertpapiere (oder Positionen) könnte ähnlich dem Performance Diagramm sein (sprich: ChartConfigurator). Ich werde aber vermutlich einen neuen Eintrag in der Seitennavigation spendieren. Mal sehen.

> Es wird eher der Aufwand sein, die Daten zusammen zu saugen.

Genau. Das wird spannend. Vielleicht muss man es erst als Background Job abfrühstücken.
