### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Bleighhhh** [buchen/portfolio#2441]
I want to install this and i am lost. Extracting the folder doesn to work and I dont know how to install the program.

I'd like to read on the readme file how to install this program on debian-based siystems or having a better way to install this, like finding it in the repo. Any installation method works, I just need guidance.

Please, providing installation guidance on the main github page would a plus.

Moreover, I cast a vote in favour of adding crypto support.

**Comment by chirlu** [comment]
Well, you need to extract the archive and run the program. That’s it.

**Comment by Bleighhhh** [comment]
> Well, you need to extract the archive and run the program. That’s it.

So basically it is never installed on the pc much like on appimage? ok, my bad :)
