### ISSUE TITLE
crash nach aktualisierung der Java Runtime

### ISSUE THREAD

**Issue by gynngr** [buchen/portfolio#247]
habe neulich das aktuelle Java jre1.8.0_31 installiert und dabei die alten Versionen deinstallieren lassen. Nun crasht pp mit
---------------------------
PortfolioPerformance
---------------------------
Java was started but returned exit code=13
C:\ProgramData\Oracle\Java\javapath\javaw.exe
-Xms40m
-Xmx512m
-jar D:\Gynngr\Apps\portfolio\\plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
-os win32
-ws win32
-arch x86_64
-showsplash
-launcher D:\JPlaga\Apps\portfolio\PortfolioPerformance.exe
-name PortfolioPerformance
--launcher.library D:\Gynngr\Apps\portfolio\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.200.v20140603-1326\eclipse_1603.dll
-startup D:\Gynngr\Apps\portfolio\\plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
--launcher.overrideVmargs
-exitdata 1ad4_6c
-nl de_DE
-vm C:\ProgramData\Oracle\Java\javapath\javaw.exe
-vmargs
-Xms40m
-Xmx512m
-jar D:\Gynngr\Apps\portfolio\\plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar 
---------------------------
OK   
---------------------------
Was kann ich tun ?

**Comment by buchen** [comment]
Der Fehler bedeutet normalerweise, dass die 32/64bit Versionen nicht zusammen passen.
In Deinem Fall das Du die 64bit Version von PP mit der 32bit Version von Java starten möchtest.

**Comment by gynngr** [comment]
Danke für den Tip. Frage mich allerdings, wieso Oracle mein 64er-Java einfach mit einem 32er updated....
