### ISSUE TITLE
Allow filters to be changed

### ISSUE THREAD

**Issue by funnym0nk3y** [buchen/portfolio#2491]
**Is your feature request related to a problem? Please describe.**
According to this forum thread [wrong link] some people wish for an option to change filters. Me too. 

**Describe alternatives you've considered**
Editing the xml file is a very technical way and shouldn't be the default way of doing this.

**Comment by OnkelDok** [comment]
I guess your link ist not the correct one.
Do you mean this PP forum thread: https://forum.portfolio-performance.info/t/bestehende-filter-erweitern/7355

Is this a duplicate of #1375?

**Comment by funnym0nk3y** [comment]
This is awkward 🙈
