### ISSUE TITLE
Invalid Error Message

### ISSUE THREAD

**Issue by flywire** [buchen/portfolio#2496]
**Describe the bug**
Import file using SelfWealth PDF Importer

**Screenshots**
![image](https://user-images.githubusercontent.com/11288701/140048075-e4b61777-8e7f-4411-98fe-2801c41a5e3d.png)

**Test**
Assume any of the [test](https://github.com/buchen/portfolio/tree/master/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/selfwealth) files should be able to be printed as a pdf and imported? Not reproducible so give me some more guidance.

**Desktop:**
Version: 0.55.0 (Sep. 2021)
Platform: win32, x86_64

**Comment by Nirus2000** [comment]
Could it be that the month name consists of more than 3 characters? Can you please post a PDF-Debug here?
