### ISSUE TITLE
MaxDrawdown Berechnung wenn Berichtsperiode > aktuelles Datum

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#250]
>Eine weitere Sache die mir aufgefallen ist, sind die Max. Drawdown Duration. Ich nehm immer die Kalenderjahre, hab also als aktuellen Zeitraum 01.01.2015-31.12.2015. In der neuen Version zeigt er mir jetzt als MDD 311 Tage an (Heute bis Ende des Jahres). In der letzten Version hat er noch ca 23 Tage ausgegeben (sprich nur die wirklich angefallenen Tage bisher).
Ist das ein Bug oder working-as-intended?

**Comment by simpsus** [comment]
Das kann doch nur passieren, wenn zwar dates in der Berechnung ankommen, aber keine Werte da sind. Leider kommen da nicht "keine" Werte, sondern einfach der letzte immer wieder, oder?

Damit umzugehen ist nicht ganz einfach, denn wie willst du entscheiden, dass das jetzt einfach keine neuen Daten mehr sind?

Ich bin fast geneigt zu sagen das ist kein Bug in der Berechnung, sondern ein Bug in der Routine die die Daten für die Berechnung erstellt. 
Ich würde sogar fast soweit gehen zu sagen, dass das Diagram hier auch nix anzeigen sollte, also der heutige Tag einfach der letzte Tag ist.

**Comment by buchen** [comment]
> Leider kommen da nicht "keine" Werte, sondern einfach der letzte immer wieder, oder?

Genau. Das Delta bleibt 0 (Problem für die Volatilität) und der akkumulierte Wert bleibt gleich (Problem für den maximalen Drawdown).

Ich denke auch, dass eher die Daten im "PeformanceIndex" begrenzt sein sollten. In allen abgeleiteten Klassen vom PerformanceIndex könnte man das begrenzen. Auf der anderen Seite sollte das Diagramm aber vielleicht die gleiche Auflösung haben damit man zwischen den Jahren einfach wechseln kann.

**Comment by simpsus** [comment]
Auflösung muss ja nicht gleich daten sein. Man kann doch bestimmt ein Diagram machen das nicht für jeden Wert auf der X Achse einen Wert anzeigt.
