### ISSUE TITLE
Wertpapier - Editieren - Klassifizierungen - Regionen: nicht speicherbar nach Änderung

### ISSUE THREAD

**Issue by smurfer** [buchen/portfolio#254]
Wenn ich die prozentuale Allokation eines Papiers nach Regionen ändern will, lassen sich die geänderten Werte nicht speichern (OK button ausgegraut), obwohl die geänderten Werte in Summe wieder 100% ergeben. Geänderte Branchenanteile lassen sich hingegen speichern.

**Comment by buchen** [comment]
@smurfer Hast Du einen Screenshot für mich?

Ich kann das nicht reproduzieren. Die Logik für Branchen und Länder ist zudem eigentlich identisch. Ich habe aber gesehen, dass nicht immer eine Fehlermeldung oben angezeigt wird. D.h. wenn mehrere Kategorisierungen fehlen, dann wird keine Fehlermeldung gezeigt. :frowning:
