### ISSUE TITLE
Feature request - Diagrammauswertung "Zahlungen --> Jahr"

### ISSUE THREAD

**Issue by Nirus2000** [buchen/portfolio#2588]
**Is your feature request related to a problem? Please describe.**
Hallo @chirlu 
du hast ja schon einiges in dem Punkt "Zahlungen" geändert, was ich super finde.
Ich verstehe die Logik hinter dem Diagramm "Zahlungen" nicht. (im Anhang einen Testdatei)
Wenn man "Summe" wählt und sich das Balkendiagramm Monat, Quartal und Jahr anschaut. Sieht erst-mal alles
gleich aus. Jedoch, wenn negative Beträge vorhanden sind, dann wird nur im Reiter "Jahr", das Diagramm grau und ohne Jahreszahlenlegende dargestellt. 
Ist das denn überhaupt noch sinnvoll hier die Farben bei negativen Beträgen zu ändern?
Könnten du das anpassen, dass dies analog den anderen Balkendiagrammen angezeigt wird, oder bin ich hier einen Fehler auf dem Leim gegangen?!

Gruß
Alex

**Screenshot**
![grafik](https://user-images.githubusercontent.com/45203494/146882692-47b9515d-8ef4-4be1-9b47-7add117af727.png)

**Testfile**
[buchen.ods.xml.zip](https://github.com/buchen/portfolio/files/7750086/buchen.ods.xml.zip)

**Comment by Morpheus0815** [comment]
Was already discussed at https://github.com/buchen/portfolio/pull/1760
