### ISSUE TITLE
Deutsche Bank PDF Import: Fees discounts are ignored

### ISSUE THREAD

**Issue by stefangries** [buchen/portfolio#2602]
**Describe the bug**
If I receive a discount on the fee from Deutsche Bank when I buy shares, as is the case with savings plans, for example, this discount is not recognized correctly. 

**To Reproduce**
Simply Import a Deutsche Bank PDF.

**Expected behavior**
When comparing PDF and imported booking, it is noticeable:

- The total value ("Belastung") 250,05 € was correctly transferred.
- The fees ("Provision") of 3.13 € were recognized, but the discounts ("Provisions-Rabatt"/"Auskehrende Zuwendungen") from them were ignored. The correct total charges are 0 € and not 3,13 €.
- The quantity ("ST") 4,9672 was correctly taken over.
- The price per piece ("Kurs") was not correctly taken over. Presumably it was calculated this way: (Total Value - Fees) / Quantity. Because of the wrong fees, the price per unit is also not correct.

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/10342151/147567667-ebf52631-3e48-4f71-be2a-cf5ec77f60c0.png)
![Unbenannt2](https://user-images.githubusercontent.com/10342151/147567789-d1abfc9b-2577-4f27-b91d-38b28e7254b7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.56.2

**Comment by Nirus2000** [comment]
Hallo @stefangries ,
melde dich bitte im Forum unter https://forum.portfolio-performance.info/ an und erstelle einen PDF-Debug zur Bearbeitung
Diesen kannst du dann im Forum [hier ](https://forum.portfolio-performance.info/t/pdf-import-von-deutsche-bank/2973) posten

Wie es funktioniert, können Sie im Video-Tutorial sehen.

Video-Tutorial:
[PDF-Dokumente für die Fehlersuche extrahieren](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

Gruß Alex
