### ISSUE TITLE
Absolute change last date is showing wrong after version update yesterday.

### ISSUE THREAD

**Issue by vipuldamani** [buchen/portfolio#2622]
**Describe the bug**
Last date change in % term show red and Value is green..
![image](https://user-images.githubusercontent.com/57120750/148501047-0756569c-0185-4660-a433-2a552f454853.png)
Here same client statement of asset show negative with same as % in performance report.
both same data series and time series selected.
![image](https://user-images.githubusercontent.com/57120750/148501128-2de6e6ef-65d6-4b9e-b697-8189267cae0e.png)

window-10 64 bit.
version 0.56.2 Dec-21

**Comment by flywire** [comment]
Note that dates are wrong. Shows 6-12 Jan 22 only missing Sat 8 Jan 22 but should have missed Sun 9 Jan. Also price shown 9 Jan is 10 Jan 22 price, 12 Jan is correct but price shown for 10 and 11 Jan is just wrong.

**Comment by flywire** [comment]
This one is different again on same installation created from new later in the day:

![image](https://user-images.githubusercontent.com/11288701/149094149-70130842-f9b9-4c73-ac31-8d728fea30c3.png)

Direct from Yahoo
```
12  44.15
11  43.99
10  43.92
 7  44.18
 6  43.25
 5  45.27
```

Note difference at 7/9. Maybe this is a unix time issue.

Version: 0.56.3 (Jan. 2022)
Platform: win32, x86_64
Java: 11.0.12+7-LTS, Azul Systems, Inc.

**Comment by buchen** [comment]
> This one is different again on same installation created from new later in the day:

Can you post what the "Show server response" shows for that request where you see differences?

**Comment by tquellenberg** [comment]
It's a problem with the timezone. The data from Yahoo contains timestamps for the time zone "AEDT" (Australia/Sydney).  The code in Portfolio Performance didn't take this into account:
`price.setDate(LocalDateTime.ofEpochSecond(ts, 0, ZoneOffset.UTC).toLocalDate());`
For a timestamp of 1641769200 this results in the date 2022-01-09 but it is actually 2022-01-10T10:00 Australian time.
```
Long ts = new Long(1641769200);
		
System.out.println(LocalDateTime.ofEpochSecond(ts, 0, ZoneOffset.UTC).toLocalDate());
// 2022-01-09
System.out.println(LocalDateTime.ofInstant(Instant.ofEpochMilli(ts*1000), ZoneId.of("Australia/Sydney"))); 
// 2022-01-10T10:00
```
[all_ax_quotes.txt](https://github.com/buchen/portfolio/files/7861490/all_ax_quotes.txt)

**Comment by buchen** [comment]
If I see this right, the timezone is included in the request so we can fix this. Thanks.

**Comment by tquellenberg** [comment]
The time zone is included in the JSON response.
`"exchangeTimezoneName": "Australia/Sydney"`
I would parse it from there.

**Comment by flywire** [comment]
[[quote="AndreasB, post:4, topic:19535"]](https://forum.portfolio-performance.info/t/roll-back-latest-pp-upgrade/19535/4)
> (I am not aware of any change in that code in the January 2022 version of PP)


Yes the Historical Quotes in Version: 0.56.2 (Dec. 2021) omit Friday and Saturday for Aus instead of Saturday and Sunday. I can't check much more on a weekend.

The thing I initially noticed was the Performance dashboard Last Day: Absolute change was wrong.
