### ISSUE TITLE
Optional reverse column order for payments matrix tabs

### ISSUE THREAD

**Issue by tquellenberg** [buchen/portfolio#2640]
**Is your feature request related to a problem? Please describe.**
The problem is discusses in the forum: 
https://forum.portfolio-performance.info/t/reihenfolge-der-spalten-in-einnahmen-ausgaben-monat-anlage/17109/30

**Describe the solution you'd like**
I propose an optional reverse column order for payment matrix tabs (month, quarter, year). My solution contains no changed to the model but works with JFace setColumnOrder. The setting is stored in the preference store.
The order can be changed separately for every matrix tab like this:

![menu](https://user-images.githubusercontent.com/528888/149492469-224d4c10-009c-4d08-b7e5-a5b616dcf8d3.png)

**Comment by tquellenberg** [comment]
Sorry, when implementing the feature I only looked at the dividends tab. But there are other tabs too, which are effected by the new functionality (Interest, Earnings, Taxes, ...). The setting for the reverse order is only stored once, this results in some scrambled tables. I will look at this problem today...

**Comment by buchen** [comment]
thanks @tquellenberg
