### ISSUE TITLE
"Current week" uses incorrect start of the week

### ISSUE THREAD

**Issue by tquellenberg** [buchen/portfolio#2666]
**Describe the bug**
On german systems "current week" results in a time range of 22.1. to 29.1. which is a Saturday.

**To Reproduce**
Select "current week" for reporting time range.

**Expected behavior**
Depending on the language setting, the week starts with Monday (germany) or Saturday (US)

See: https://forum.portfolio-performance.info/t/welcher-zeitraum-ist-die-aktuelle-woche/19767

**Comment by buchen** [comment]
Can you post your "configuration details"? Application menu -> About PP -> Installation details

On my machine - with German locale - I see 23.1. to 30.1. as current week

**Comment by tquellenberg** [comment]
The problem is as follows
````
System.out.println(WeekFields.of(Locale.GERMAN).getFirstDayOfWeek());
System.out.println(WeekFields.of(Locale.GERMANY).getFirstDayOfWeek());
````
results in 
````

SUNDAY
MONDAY
`````
There are two ways to run in this problem:
1. Setting "-osg.nl de" on command line (in combination with "Automatisch") or
2. Choosing "German" in the preference of Portfolio Performance.

In both cases `Locale.getDefault()` returns `"de"` and not `"de_DE".`

**Comment by tquellenberg** [comment]
Solution
1. I think the problem with "-osg.nl de" can be ignored
2. Choosing the language in the preference should change the region, too. Of course, there is no direct relation between language and region. But for most users changing the region to the "natural" home of the language will be a better solution than the current situation.

**Comment by Morpheus0815** [comment]
It is a Java behaviour how `Locale` is handled:
* https://www.oracle.com/technical-resources/articles/javase/locale.html
* https://docs.oracle.com/javase/1.5.0/docs/guide/intl/locale.doc.html
* https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html

However, you never just a specific language rathe than assign a county an region which leads the app and the to be used language.

**Comment by tquellenberg** [comment]
The discussion in the forum ended with "it's not a bug". The preference setting in Portfolio Performance is only a language setting. There is no region setting and thus the current behavior is okay.

**Comment by buchen** [comment]
Does it make sense to extend the drop down with "Deutsch (Deutschland)" = de_DE and "Deutsch (Schweiz)" = de_CH, etc? Either the user picks "automatic" and the local is determined from OS, or the user picks a language + country (and hence derived configuration such as "first day of the week").

@tquellenberg what do you think?

**Comment by tquellenberg** [comment]
This would be possible but there are A LOT of combinations. French, english and spanish are spoken in many countries. And omitting some of these countries will lead to bug reports. Who knows if the number format in Argentina is different from the number format in Spain. The [Java documentation](https://www.oracle.com/java/technologies/javase/jdk11-suported-locales.html) contains a list. For PP at least 50 combinations make sense.

And after the discussion in the forum the main question for me is, why should I change the language / region / calendar format in an application at all? The automatic mechanic is fine. I'm not sure if it is helpful to put more effort in this feature.

**Comment by buchen** [comment]
We could use ```Locale.getAvailableLocales()``` to have a secondary dropdown with the country.

The alternative could be to allow entering the full local string directly. Or document how to do this in the ```config.ini``` file because that's all what technically happens.

The reason I am offering the language drop down is allow users of a not fully / not good translated version to fallback to another language. To be honest, I cannot say how good the Dutch translation is (I don't speak Dutch) so maybe as a French user I want to use English instead. But of course I don't want to switch the language of my operating system

**Comment by tquellenberg** [comment]
Okay, I'll give the solution with two dropdowns a try.
