### ISSUE TITLE
Problem of splits

### ISSUE THREAD

**Issue by verng95** [buchen/portfolio#2677]
I parse quotes using JSON and my broker gives prices before the split. I understand that after the split, PP does not update quotes before the split date, right? Because he doesn't touch all prices except January 31. How can I solve this problem?

**Before split:**

![image](https://user-images.githubusercontent.com/17193436/152372197-1fffca23-6e56-4072-b1ec-eef3dc6ac4cd.png)

**After split:**

![image](https://user-images.githubusercontent.com/17193436/152372308-c77d0f44-6a29-4369-bfd5-82d51662cdcf.png)
![image](https://user-images.githubusercontent.com/17193436/152372331-b1ffc075-0790-468d-8018-1152144b6ec7.png)

**After update history:**

![image](https://user-images.githubusercontent.com/17193436/152372480-3cb54eac-1339-4298-8ec9-79fd701777f8.png)

 - OS: Windows
 - Version: 0.56.4

**Comment by tquellenberg** [comment]
>  I understand that after the split, PP does not update quotes before the split date, right?

PP only updates the quotes once. It's a one time operation: all quotes and shares are changed, when you add the split. Thats it. 
When you receive old quotes from your broker afterwards, you have to fix it manually.

**Comment by verng95** [comment]
> > I understand that after the split, PP does not update quotes before the split date, right?
> 
> PP only updates the quotes once. It's a one time operation: all quotes and shares are changed, when you add the split. Thats it. When you receive old quotes from your broker afterwards, you have to fix it manually.

The problem went away when I added a split on February 4th, on February 3rd. After that, the quotes for January 31 stopped being reset.

That is, it turns out that the split does not need to be added on the same day.

But I still didn't understand _"When you receive all quotes from your broker afterwards, you have to fix it manually."_... now the old quotes come to me (before the split), but the prices are not reset.

**Comment by tquellenberg** [comment]
I assume, that your broker sends update only for one or two quotes. Or PP only updates one or two historical quotes, when they are already exist. So probably today, only data for 3. February are updated, but not the value for 31. January.

> So the update takes into account splits?

No, not as far as I know.

> Because the Json API returns prices as if there was no split.

Which value does your broker sent for February 3rd? 1,211 or 12,11. 

May be you should wait some days and see whether the situation will stay okay.

**Comment by verng95** [comment]
> Which value does your broker sent for February 3rd? 1,211 or 12,11.

For Ferruary3rd quote 1,211

![image](https://user-images.githubusercontent.com/17193436/152523818-079348f8-8fcd-4c90-b8d9-e185764cbf23.png)

I hope that PP does not reset the data until February 3rd. 
It would be nice if it were possible to forbid PP to allow the quote to be historical before the split.

**Comment by tquellenberg** [comment]
Your broker sent:
- 1,211 for February 3rd. PP doesn't change this value when it is imported.
- 12,14 for Janauary 31st. PP imported/updated this value unchanged AFTER you made the split in PP. This was the problem. But I don't know if this is really a bug.

**Comment by verng95** [comment]
> Your broker sent:
> 
> * 1,211 for February 3rd. PP doesn't change this value when it is imported.
> * 12,14 for Janauary 31st. PP imported/updated this value unchanged AFTER you made the split in PP. This was the problem. But I don't know if this is really a bug.

I did the tests and concluded that if, for example, the split occurred on February 3, then you need to add it on February 4, then P P does not reset the last historical date.

Thanks for the feedback)

**Comment by tquellenberg** [comment]
I think, the split works fine and you observed a problem with the quote update. 
For the import of quotes PP works as follows:
```
    /**
     * Adds all prices to the list of prices unless a security price for that
     * date already exists. However, the last historical date is overwritten as
     * some quote provider include the latest security price in the list of
     * historical prices.
     */
```

**Comment by verng95** [comment]
Thansk
