### ISSUE TITLE
Make the time field wider when adding a transaction

### ISSUE THREAD

**Issue by verng95** [buchen/portfolio#2680]
If you add a new transaction, then it is problematic to see the time, since the field width is not enough. 

![Screenshot_1](https://user-images.githubusercontent.com/17193436/152529000-ebaab591-c33b-4a42-a988-b6c6ff275e3a.png)

**UPD:**
Operation system: Windows 10
Version PP: 0.56.4
Font settings: By default (9px)

**Comment by tquellenberg** [comment]
Do you have some information about your operating system (Windows? Which version?) and your font settings in the preferences of Portfolio Performance?

**Comment by verng95** [comment]
> Do you have some information about your operating system (Windows? Which version?) and your font settings in the preferences of Portfolio Performance?

Operation system: Windows 10
Version PP:  0.56.4
Font settings: By default (9px)

**Comment by tquellenberg** [comment]
Thanks, for the information. I can reproduce the problem. It seems to correlate with the chosen language. In German and English the input field is okay. In Spanish and Russian the field is too small.

PP uses an external library for this field. I'm not sure if we can fix this problem, but I will try it.

**Comment by tquellenberg** [comment]
I found the problem. The size is derived from the initial value. In Germany this is "00:00". In other languages (eg. Spain, Russia) this is "0:00". This depends on the time format of Java which is sometimes "HH:mm" and sometimes "H:mm". I think we can fix this.

**Comment by verng95** [comment]
> I found the problem. The size is derived from the initial value. In Germany this is "00:00". In other languages (eg. Spain, Russia) this is "0:00". This depends on the time format of Java which is sometimes "HH:mm" and sometimes "H:mm". I think we can fix this.

That's fine, thank you! :)
