### ISSUE TITLE
Problem with Cyrillic encoding when exporting quotes to CVS

### ISSUE THREAD

**Issue by verng95** [buchen/portfolio#2690]
**Describe the bug**
If you try to export quotes of an asset that is named in Cyrillic, then there is a problem with the file name, as well as the encoding in the csv itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/17193436/152678191-cf7b4870-eac4-4820-8b8d-e3d0e4e9ca57.png)
![image](https://user-images.githubusercontent.com/17193436/152678204-91d4f9ad-eeac-4a70-87aa-8b68090c5b64.png)

 - OS: Windows 10
 - Version: 0.56.4

**Comment by verng95** [comment]
Similar problem

![image](https://user-images.githubusercontent.com/17193436/152685388-3ee3513f-9a0b-4f89-a81e-2a4c79a4a2f0.png)

**Comment by tquellenberg** [comment]
I think, that are two problems:
1. Encoding of the **filename**. The name of the file is build using UTF-8. I think, this isn't working at all on windows. Even german 'Umlaute' are broken. I Think this is a bug.
2. Encoding of the **file content**. When opening the file with Excel, you should tell Excel, that the file content is encoded in UTF-8. I think this should work.
