### ISSUE TITLE
Baader Bank / Scalable Capital English PDF import

### ISSUE THREAD

**Issue by cattaneod** [buchen/portfolio#2701]
My scalable capital documents are in English, and Portfolio Performance can't import them, as the importer expect german "keywords".

Is it possible to adapt the importer to support both German and English documents?

**Comment by Nirus2000** [comment]
Hello @cattaneod 
Therefore, log in to the forum at [PDF-Import von Baader Bank/Scalable Capital](https://forum.portfolio-performance.info/t/pdf-import-von-baader-bank-scalable-capital/2057)
For a PDF importer we need examples of purchase, sale, dividend and so on.... please post them here. 
You can see how it works in the video tutorial.

Video tutorial:
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

**Comment by goolpone** [comment]
Hello @Nirus2000 
I have just posted the new english template: [PDF-Import von Baader Bank/Scalable Capital](https://forum.portfolio-performance.info/t/pdf-import-von-baader-bank-scalable-capital/2057/68)

**Comment by Nirus2000** [comment]
Done.
Wenn du mehr Dokumente hast, welche auch Verkauf, Dividenden, Gebühren in 
Englisch enthalten, dann bitte wieder im Forum.

Gruß
Alex
