### ISSUE TITLE
Anzeige "Momentaner Drawdown" 

### ISSUE THREAD

**Issue by simpsus** [buchen/portfolio#271]
bei den Risikokennzahlen die beiden Aussagen:

Wie weit ist die Performance vom letzten Hoch entfernt (% und Zeit)

**Comment by buchen** [comment]
Inwieweit ist das anders als #266?

**Comment by simpsus** [comment]
wenn ich drüber nachdenke ist der einzige unterschied einzelnes Papier vs. ganzes Portfolio.
Also: nicht wirklich ein Unterschied.
