### ISSUE TITLE
Allow negative account values

### ISSUE THREAD

**Issue by funnym0nk3y** [buchen/portfolio#2720]
**Describe the bug**
When creating two balance account with 0,00 in them each and then create a transaction from account A to B with value 100 then in the account overview both accounts still show 0,00 in them. 

**To Reproduce**
1. Create two accounts A,B with 0,00 each in them. 
2. Create a transaction with value x from A to B
3. View account "tab"

**Expected behavior**
I'd expect PP to also support negative account balances. 

**Desktop (please complete the following information):**
 - OS: Win10 21H2
 - Version: 0.56.5

**Comment by tquellenberg** [comment]
<img width="553" alt="screenshot_12" src="https://user-images.githubusercontent.com/528888/156522191-1c927080-828d-4bb2-9559-e400c7a9a401.png">

For me this works fine.

**Comment by funnym0nk3y** [comment]
Well, I restarted PP and now it works just fine for me too. But initially it did not work, I checked it several times...
