### ISSUE TITLE
Respect language settings in time widget

### ISSUE THREAD

**Issue by tquellenberg** [buchen/portfolio#2736]
**Describe the bug**
To enforce enough space for two hour-digits, the time format is hard coded to "HH:mm". This doesn't work for countries with AM/PM time formats. The hard coded pattern was introduced here: #2680

See: 
https://forum.portfolio-performance.info/t/how-to-change-time-format/20223/11

**Solution**
Modify the time pattern dynamically when there is only one digit for the hour expected.

**Comment by flywire** [comment]
Can you look at date too? `Jun. ` is not a valid format for month but `Jun` is.

**Comment by tquellenberg** [comment]
About what date widget are you talking? There are only numeric values here:

<img width="345" alt="screenshot_14" src="https://user-images.githubusercontent.com/528888/157601352-63493306-75eb-4b41-8168-52501d8cd7b4.png">

**Comment by flywire** [comment]
Version: 0.56.6 (Mar. 2022)
Platform: win32, x86_64
Java: 11.0.12+7-LTS, Azul Systems, Inc.

![image](https://user-images.githubusercontent.com/11288701/157613377-ba53536c-8f27-4e3a-a51e-192956f870a5.png)

Used in all reports eg:

![](https://forum.portfolio-performance.info/uploads/default/original/2X/4/4e733e6dd396124bc686e55796b7e1921687b0aa.png)

Win10:

![image](https://user-images.githubusercontent.com/11288701/157613485-3a488542-cde3-4483-af9d-4dba98c70edf.png)

**Comment by tquellenberg** [comment]
Sorry, international date and time can be confusing. I'm not sure whether I understand the problem correctly. In Australia there should no dots when the name of the month is abbreviated; is this your point?

This looks to me as a Java bug which is discussed here: https://bugs.openjdk.java.net/browse/JDK-8208487
I don't see any chance that we fix this in Portfolio Performance.

When I didn't get you right, please create a new issue. I think your problem is not directly connected to the problem of this issue.

**Comment by flywire** [comment]
Yes, my point is as you say about the extra period and also I'd expect it to use Regional format - Short date. Thank you for advising of the Java bug.
