### ISSUE TITLE
Automatische Wechselkurskonversion

### ISSUE THREAD

**Issue by jochenheil** [buchen/portfolio#274]
Wenn Wertpapiere hat, die auf Dollar laufen und die nicht an Börsen in Deutschland gehandelt werden kann man derzeit nur die Dollarkurse verwenden, was dann natürlich alle Berechnungen verfälscht. Man könnte ein zusätzliches Attribut "Währung" einführen und das Programm könnte sich die aktuellen Wechselkurse besorgen und die Historischen Kurse entsprechend umrechnen.

**Comment by buchen** [comment]
Da bin ich dran - siehe #14. Allerdings ist diese Änderung doch grösser als gedacht und ich habe momentan weniger Zeit als gedacht. Es wird wohl noch etwas dauern...

**Comment by jochenheil** [comment]
Die #14 hatte ich dann auch gesehen und wollte das "issue" wieder löschen, habe aber keinen Button gefunden. In jedem Fall vielen Dank, das du dieses tolle Programm der Öffentlichkeit zur Verfügung stellst.
