### ISSUE TITLE
PDF Import: automatisch Einlieferungen aus Käufen generieren

### ISSUE THREAD

**Issue by Necoro** [buchen/portfolio#275]
Beim Import via comdirect PDF gibt es leider keine Möglichkeit als Ursprungskonto "Einlage" zu wählen. Das wäre aber schön zu haben, finde ich doch den Zwang eines Referenzkontos relativ mühsam :)

**Comment by buchen** [comment]
Gibt es bei comdirect keinen Dokumententyp "Einlage"?
Oder möchtest Du einen Kauf einfach als "Einlage" buchen und die Buchung auf Deinem Konto ignorieren?

**Comment by Necoro** [comment]
Letzteres. Hintergrund: Ich wollte Sparpläne einpflegen. Im Sparplan kann man ja wahlweise ein Referenzkonto einbinden, oder es auch sein lassen, also "(Einlage)" verwenden. Da ich aber keine Lust hatte, alle Ausführungen noch einmal anpassen zu müssen (comdirect lässt gerne hier und da mal ein paar Cent weg) wollte ich einfach das Import-Tool auf den Abrechnungen laufen lassen. Das bot mir aber eben nur an, das direkt mit einem Konto zu verrechnen.

(Was mich dann gleich zu #276 brachte, als ich die importierten Buchungen nämlich wieder löschen wollte :)).

**Comment by buchen** [comment]
#276 kann ich bei Gelegenheit machen :smile:

Die Umwandlung als "Einlage" könnte man auch realisieren. Wenn der Importer eine "Kauf-Buchung" erstellt, kann man die ja anschließend recht einfach in eine Einlage umwandeln wenn nur "Einlage" gewählt ist. Ich ändere den Titel mal entsprechend um.

**Comment by Necoro** [comment]
Keine Ahnung wie sinnvoll das für Nicht-Anfänger ist: Evtl kann man das auch gleich generalisieren und für eine Buchung den Wechsel/Wegfall/Hinzufügung eines Referenzkontos erlauben. Und wenn man das intern schlicht als delete+add abbildet.

**Comment by simpsus** [comment]
Lustigerweise würde ich das auch sofort und als standard benutzen...

**Comment by ElRico** [comment]
Ditto, ich habe kürzlich den PDF import entdeckt und würde diesen gerne für meine Sparpläne benutzen, bei dennen ich Einlagen verwende. Super das es bereits auf der Roadmap ist!
