### ISSUE TITLE
Sorting Limit price - working correctly?

### ISSUE THREAD

**Issue by Pnda87** [buchen/portfolio#2772]
Referring to pull req. #2734 a new behavior for sorting limit price columns has been introduced.

I am wondering if this is working correctly? 
For me it seems this is not the case, as it is still sorting by _absolute_ value.
Is my configuration wrong?
![image](https://user-images.githubusercontent.com/34549632/161374575-679d91f5-b3ef-4672-b041-aafb810987fb.png)

**Expected behavior** is as described in the pull req., i.e. sorting by _relative_ values
![image](https://user-images.githubusercontent.com/34549632/161374661-44babb50-8b91-4b5d-8011-6a3da7599882.png)

**Attribute settings:**
![image](https://user-images.githubusercontent.com/34549632/161374682-a0935b36-7151-4ab1-ad66-413fb40fb4c0.png)

**Comment by OnkelDok** [comment]
The merged PR was merged after the release of version 0.56.6.
Release date of 0.56.6 was Mar 5, 2022 (265a5b8).
The PR #2734 was merged on Mar 26, 2022 (6b195cf).

Therefore the new behavior is available with next version.

**Comment by Pnda87** [comment]
oh sorry, my bad. i completely missed that. Thanks for the commit anyway and the quick reply here :)
