### ISSUE TITLE
Support multiple portfolios in divvydiary

### ISSUE THREAD

**Issue by oxisto** [buchen/portfolio#2779]
**Is your feature request related to a problem? Please describe.**

Since recently, it is possible to add more than one portfolio in divvydiary (on the paid plan). I wonder if it is possible to support this in PP, by mapping different portfolio XML files to different portfolio IDs in divvydiary. However, for this to work, probably some setting on the portfolio itself needs to be set, since the existing divvydiary settings are global for all portfolio files.

Alternatively, the multiple portfolios could be used to differentiate different accounts, rather than portfolio files. Not sure what would be best. For me personally, mapping the portfolios to different files would be the best.

**Comment by buchen** [comment]
It is now possible with version 0.57.0
