### ISSUE TITLE
FlatEx PDF-Importer bucht Bruttothesaurierung als Dividende

### ISSUE THREAD

**Issue by uok** [buchen/portfolio#2786]
Achtung, der FlatEx PDF-Importer in Portfolio Performance v0.57.1 speichert die Bruttothesaurierung von einem Fonds (Ertragsmitteilung) als Dividende - das ist falsch! In älteren Versionen war dieses Problem nicht vorhanden, da wurde - richtigerweise - nur die Steuer eingetragen.

Bitte um Fix, Danke!

**Comment by Morpheus1w3** [comment]
> Bitte einen PDF-Debug zur Verfügung stellen.

https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/fintechgroupbank/FlatExDegiroDividende01.txt

**Comment by Nirus2000** [comment]
Hallo @Morpheus1w3 und @uok 
Hier ist mir ein Fehler unterlaufen zwischen 
- Bruttoausschüttung mit negativen Betrag 
und 
- Bruttothesaurierung mit negative Betrag

Ich werde mich schnellstmöglich darum kümmern, dass zu korrigieren.
Vielen Dank für die Meldung. Super von Euch - dadurch mach Ihr den Importer immer besser! 👍🏻 
Gruß
Alex
