### ISSUE TITLE
Umbuchung von Wertpapieren: Unnötige Wertangabe

### ISSUE THREAD

**Issue by Necoro** [buchen/portfolio#282]
Wenn ich Wertpapiere von einem Depot in ein anderes verschiebe, bin ich in der Anwendung gezwungen, einen Wert anzugeben. Das ist ja aber unnötig, da sich durch die Umbuchung am Wert selber nichts ändert. Die Anwendung sollte hier, sofern sie denn unbedingt einen Wert braucht, einfach den internen Wert am Tag der Umbuchung eintragen.

**Comment by buchen** [comment]
Die Bewertung brauche ich. Nicht wenn man das Gesamtportfolio anschaut, sondern wenn man die Performance eines einzelnen Portfolios berechnen will. Dann braucht es die Abgrenzung. Für die Währungen habe ich aber schon angefangen die Dialoge überarbeitet. Da sollte dann ein guter Vorgabewert sein.

**Comment by buchen** [comment]
Im Branch feature_currencies wird der Wert jetzt automatisch anhand des Datums vorbelegt. Es wird allerdings noch etwas dauern bis ich den in master mergen kann.
