### ISSUE TITLE
Quote formating is wrong (point instead of comma)

### ISSUE THREAD

**Issue by ngosang** [buchen/portfolio#2888]
**Describe the bug**
Quote formating is wrong (point instead of comma). The other textboxes in the form are right, Take a look at the screenshot.

**To Reproduce**
Set decimal separator = comma and open the "buy" dialog.

**Expected behavior**
All textboxes should use comma for decimal separator.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10577978/174300846-8ef488fe-ce99-4e5f-895f-89b6de5a5d72.png)
![imagen](https://user-images.githubusercontent.com/10577978/174301192-d74df9b3-dc96-45d9-ae0b-212479e13795.png)

**Desktop (please complete the following information):**
Version: 0.58.4 (Jun 2022)
Platform: win32, x86_64
Java: 11.0.15+10-LTS, Azul Systems, Inc.

**Comment by buchen** [comment]
Thanks for the bug report. That was a tricky one. A dependent library did not know about the en_150 locale and that resulted in mixed formatting.
