### ISSUE TITLE
Some quotes are not updating in last versions

### ISSUE THREAD

**Issue by ngosang** [buchen/portfolio#2889]
**Describe the bug**
Some quotes are not updating in last versions.

1) When I open PP some quotes are updated and other not. I don't have the screenshot but some securities have the "latest date" and "latest historical date" in yellow.

2) If I use the "security" menu to update the quote, it sometimes work and sometimes it only updates the "latest date". The "latest historical date" column remains with the old/yellow value.
![imagen](https://user-images.githubusercontent.com/10577978/174302517-f27365c0-9139-4821-834d-713c038fd8f0.png)

3) If I use the menu in the "historical quotes" tab, all the prices for that security are updated correctly.
![imagen](https://user-images.githubusercontent.com/10577978/174302745-a8567bcf-e0eb-46b6-aa29-218df69eb0e7.png)

**Expected behavior**
1) and 2) should work as 3)

**Desktop (please complete the following information):**
Version: 0.58.4 (Jun 2022)
Platform: win32, x86_64
Java: 11.0.15+10-LTS, Azul Systems, Inc.

**Comment by buchen** [comment]
That is a super hard issue to debug. 1 and 2 and 3 trigger the same piece of code.

It can be a bug, it can also be a provider that is unhappy about a burst of calls (when updating all quotes after opening PP) and returns empty results while being happy about a single call to update the quotes.

Can you post which configuration you use for the securities where it happens regularly?

**Comment by ngosang** [comment]
> That is a super hard issue to debug. 1 and 2 and 3 trigger the same piece of code.

Then the issue must be on my side.

> It can be a bug, it can also be a provider that is unhappy about a burst of calls (when updating all quotes after opening PP) and returns empty results while being happy about a single call to update the quotes.

I guess you are right. I'm using "custom" provider that returns JSON data and I don't know how reliable it's but I can debug it. On your side, maybe you can improve how the errors in quote providers are reported to the user. I see the quotes are yellow/outdated but the reason is not obvious. Of course, this is an enhancement not a bug. I will deal with my issue and I will come back if I found something you can fix.

**Comment by ngosang** [comment]
It could be related to this => #2874
