### ISSUE TITLE
Edit Wertpapiere: Beim der Klassifikation die Summe der Prozente anzeigen

### ISSUE THREAD

**Issue by Tolzmann** [buchen/portfolio#290]
Sofern man beim Anlegen eines ETF als Werpapier den Ehrgeiz hat, die Länder- oder Branchenverteilung anzugeben, gestaltet sich die Erfassung recht mühsam:

Die Daten lassen sich nur dann speichern, wenn für jede Klassifikation das Wertpapier zu 100% auf die Klassen verteilt wurde. Wie viel Prozent bereits verteilt sind, lässt sich jedoch nicht erkennen. Diese Information anzuzeigen wäre jedoch hilfreich.

**Comment by buchen** [comment]
> Wie viel Prozent bereits verteilt sind, lässt sich jedoch nicht erkennen.

Eigentlich sollte das Papier in der Kategorie "Ohne Klassifizierung" mit dem Restanteil auftauchen. Von da kann man es per Drag & Drop einer Kategorie zuordnen. Im Kontextmenü  sollten eigentlich die fehlenden, also freien, Prozente auch angezeigt werden.

![bildschirmfoto 2015-05-23 um 09 05 21](https://cloud.githubusercontent.com/assets/587976/7782822/10c1ed14-012b-11e5-971b-7e72aed7a846.png)

Etwas anders verhält es sich, wenn man in die Asset Allocation Ansicht wechselt. Dann müssen die Unterkategorien auf 100% aufgehen. Die Werte stehen dann in der selben Spalte, aber bei den Kategorien.

> Die Daten lassen sich nur dann speichern, wenn für jede Klassifikation das Wertpapier zu 100% auf die Klassen verteilt wurde.

Wie wirkt sich das aus? Eigentlich sollte man die Datei immer speichern können - selbst wenn die Zuordnung nicht vollständig ist?

**Comment by Tolzmann** [comment]
Mein Hinweis bezog sich den Reiter "Klassifikation" beim Anlegen oder Bearbeiten eines Wertpapiers:

![Uploading 2015-05-26 12_28_45-Portfolio Performance.png…]()

**Comment by buchen** [comment]
> Mein Hinweis bezog sich den Reiter "Klassifikation" beim Anlegen oder Bearbeiten eines Wertpapiers

Jetzt habe ich es verstanden. In der Tat ist es inkonsistent, dass man in der einen Ansicht auch Anteile unklassifiziert lassen kann, in der anderen aber nicht. Das kann ich ändern. Und bei mehreren Anteilen könnte ich auch die Summe ausrechnen. Den "Neue Kategorie" könnte man dazu ja verschieben und so kaum Platz verlieren.

**Comment by buchen** [comment]
![bildschirmfoto 2015-05-26 um 20 31 15](https://cloud.githubusercontent.com/assets/587976/7820116/88afadbc-03e6-11e5-86fa-619316dd3a13.png)

Kommt mit der nächsten Version.
