### ISSUE TITLE
Fonts bei Anzeige "Bestände" zerhackt!

### ISSUE THREAD

**Issue by hmarschall** [buchen/portfolio#291]
Die Schrift wird bei der Anzeige der Bestände vollkommen unleserlich zerhackt.
![screenshot](https://cloud.githubusercontent.com/assets/12566044/7780239/96fde92c-00dc-11e5-9c7a-9a9a98cc16f1.png)

.

**Comment by buchen** [comment]
Ooops. :flushed:

Ich überarbeite gerade das Kuchendiagramm. Ich poste in den nächsten Tagen einen Link auf eine Testversion. Da ich einen andere Bibliothek verwende, hoffe ich mal dass das Problem dann nicht mehr auftritt.

**Comment by buchen** [comment]
@hmarschall 

Wie sieht das mit der Beta aus:
**Beta:** [Windows 32bit](https://s3.amazonaws.com/name.abuchen.portfolio/beta/PortfolioPerformance-0.17.3-SNAPSHOT-win32.win32.x86.zip) | [Windows 64bit](https://s3.amazonaws.com/name.abuchen.portfolio/beta/PortfolioPerformance-0.17.3-SNAPSHOT-win32.win32.x86_64.zip) | [Mac OS X](https://s3.amazonaws.com/name.abuchen.portfolio/beta/PortfolioPerformance-0.17.3-SNAPSHOT-macosx.cocoa.x86_64.tar.gz) | [Linux 32bit](https://s3.amazonaws.com/name.abuchen.portfolio/beta/PortfolioPerformance-0.17.3-SNAPSHOT-linux.gtk.x86.tar.gz) | [Linux 64bit](https://s3.amazonaws.com/name.abuchen.portfolio/beta/PortfolioPerformance-0.17.3-SNAPSHOT-linux.gtk.x86_64.tar.gz)

**Comment by hmarschall** [comment]
Prima! Die Anzeige des Kuchendiagramms funktioniert hier! 

Danke für die schnelle Reaktion und die tolle Software!

**Comment by buchen** [comment]
Fixed with 6b7365c07699ab19618fc46becc10a704237610b
Nächstes Wochenende baue ich eine neue Release.
