### ISSUE TITLE
CSV import, special number series

### ISSUE THREAD

**Issue by MandelK** [buchen/portfolio#2944]
So here one issue I come across:
![image](https://user-images.githubusercontent.com/110846918/183475752-809fb762-2be0-4969-8585-3e5364eacf00.png)

The format of numbers currently only identifies
0.000,00
0,000.00
0’000.00
but 0 000,00 not yet.

This new format would be useful for me at least as it then always just imports 1 if I use 0.000,00, but the value was 1 000.

**Comment by flywire** [comment]
Identical to #2945 which is better described and has a comment. Suggest this one is closed.
