### ISSUE TITLE
CSV import, new number format

### ISSUE THREAD

**Issue by MandelK** [buchen/portfolio#2945]
So here one issue I come across:
![image](https://user-images.githubusercontent.com/110846918/183476049-ff7678aa-3286-4c86-8578-c5a8f1318858.png)

The format of numbers currently only identifies
0.000,00
0,000.00
0’000.00
but 0 000,00 not yet.

This new format would be useful for me at least as it then always just imports 1 if I use 0.000,00, but the value was 1 000.

**Comment by flywire** [comment]
The issue would not exist if data was cleaned properly so numbers have all characters stripped except `0-9` and `decimal separator` (#2359 is a similar issue with dates). The default decimal separator is given in the locale. User interaction would not be required unless the default setting needed to be changed.
