### ISSUE TITLE
Portfolio's holdings chart almost never displays on the canvas

### ISSUE THREAD

**Issue by maxpsq** [buchen/portfolio#2950]
**Describe the bug**
The holdings chart displays only the first time you land on its canvas after opening the application. When you get back to that canvas after a bit of browsing around the other pages, the chart is no longer displaid: the only thing you see is a gray empty canvas.

**To Reproduce**
1. go to "Reports" > "Statements of Assets" > "Holdings": the chart is shown correctly
2. go to any other page of your choice
3. go back to to "Reports" > "Statements of Assets" > "Holdings": the chart is no longer shown

**Expected behavior**
The chart shoud be always visible

**Screenshots**

![image](https://user-images.githubusercontent.com/7106975/184637654-cfa7d057-5e90-4ff7-b1dc-714ebd5f45c1.png)

**Desktop:**

**_OS_:**
Linux, TUXEDO 22.04 LTS (Ubuntu based)

**_Portfolio Performance_:**
Version: 0.59.0 (Jul 2022)
Platform: linux, x86_64
Java: 11.0.14+8, Flathub

**Comment by Morpheus1w3** [comment]
This is a Linux driven issue. Check out the PP settings to influence the chart rendering behaviour of PP.

**Comment by maxpsq** [comment]
Thanks! It solved the issue
