### ISSUE TITLE
Flatex import does not work anymore

### ISSUE THREAD

**Issue by oldgitdaddy** [buchen/portfolio#2951]
**Describe the bug**
Go to: Datei-> Importieren -> PDF Bankdokumente

Error says: 
![image](https://user-images.githubusercontent.com/4282985/185643950-c22bf999-eff2-49bf-9a81-173af117a596.png)

**To Reproduce**

**Expected behavior**
PDF cannot be imported

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.59.0

Updated the issue with a more meaningful screenshot of the errormessage.

**Comment by Morpheus1w3** [comment]
Kindly follow this thread:
https://forum.portfolio-performance.info/t/pdf-import-von-flatex/1752/177

**Comment by oldgitdaddy** [comment]
Sorry for not being that precise. I think this is not related to the thread you pointed out directly. Still of course related. Wondering if anybody is working on the fix already?

Please see error message with more detail. I guess it is a parsing issue of a relatively straight-forward import buy confirmation.
![image](https://user-images.githubusercontent.com/4282985/185643728-196c592d-dcd4-47a3-be71-2b8055082496.png)

**Comment by oldgitdaddy** [comment]
Shoot. I chose the wrong document. I just saw when extracting the text from the pdf. my bad. sorry!
