### ISSUE TITLE
imported gross value and calculated gross value do not match when importing IB Flex Query

### ISSUE THREAD

**Issue by timoll** [buchen/portfolio#2957]
**Describe the bug**
Imported Trades from the Flex Query of Interactive Broker can't be imported. Shown errors says "Imported gross value (CHF XXX) and calculated gross value(CHF XXX) do not match".

The imported gross value includes the commission while the calculated gross value does not.

This is a regression, the flex query can be imported in versions prior to 0.58.0

**To Reproduce**
1. Create a new Portfolio with a deposit and securities account
2. Click on File -> Import -> Interactive Brokers: Activity Flex Query
3. Import [dummy.txt](https://github.com/buchen/portfolio/files/9431890/dummy.txt) (rename it to dummy.xml)
4. See error with the buy transaction

**Expected behavior**
Buy transaction can be imported

**Desktop:**
 - OS: Linux
 - Version 0.59.1

**Comment by Nirus2000** [comment]
Done.
