### ISSUE TITLE
Quellensteuern werden in der Transkationsliste der Wertpapiere nicht angezeigt

### ISSUE THREAD

**Issue by alani1** [buchen/portfolio#298]
Die Transaktionsliste von jedem Wertpapier zeigt die Dividenden. Ich arbeite an einem Importer fuer Interactive Brokers. Da erstelle ich fuer jede Dividendenzahlung auch eine Steuer-Transaktion fuer die Quellensteuer. Diese Quellensteuer Transaktionen sollten ebenfalls in der Transaktionsliste des Wertpapiers angezeigt werden.

Bis jetzt war es im UI gar nicht moeglich eine Steuer Transaktion mit einem zugeordneten Wertpapier zu erstellen.

**Comment by alainschaefer** [comment]
Habe gerade realisiert dass ich ev. die Transkation falsch erstelle. Muessen fuer die AccountTransactions wie Dividenden oder eben Quellensteuern auch Gegenbuchungen im Portfolio erstellt werden ? Bis jetzt habe ich dies nur fuer die Buy/Sell Transactions mit BuySellEntry gemacht.

**Comment by alainschaefer** [comment]
Dasselbe wie fuer die Quellensteuern gilt auch fuer Gebuehren. Mir werden zum Teil Gebuehren fuer das Auszahlen der Dividenen verrrechnet. Diese sind eine separate Transaktion und sollten ebenfalls in der Transaktionsliste angezeigt werden.

**Comment by buchen** [comment]
Steuern und Gebühren kann man momentan noch nicht im Bezug auf ein Wertpapier erfassen, siehe #219. Das Modell bildet das Stand heute noch nicht ab.

Beim [Consorsbank Importer](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/ConsorsbankPDFExctractor.java#L102) erfasse ich die Steuern zwar als separate Buchung, aber eben ohne Wertpapier.

> Muessen fuer die AccountTransactions wie Dividenden oder eben Quellensteuern auch Gegenbuchungen im Portfolio erstellt werden ?

Nein, nur bestandsverändernde Buchungen brauchen Gegenbuchungen.

**Comment by alainschaefer** [comment]
Bist du dir sicher dass das Model das nicht unterstützt ? Der IBFlexStatementExtractor importiert diese als separate Transaktion und setzt bei den Taxes setSecurity() das Model speichert dies korrekt. Ich denke dies wäre das bessere Vorgehen, da so das Model nicht extra angepasst werden muss. in #219, muss dann nur das UI aufgebohrt werden.

**Comment by buchen** [comment]
> Der IBFlexStatementExtractor importiert diese als separate Transaktion und setzt bei den Taxes setSecurity() das Model speichert dies korrekt.

Richtig, da gehört es auf jeden Fall hin. Mit Modell anpassen meinte ich auch eher die Berechnungen (Performance, ...) um separate Steuer und Gebühren Buchungen mit aufzunehmen. Es macht aber absolut Sinn das zu machen.
