### ISSUE TITLE
Connection to IP address 185.5.82.138 on startup

### ISSUE THREAD

**Issue by uok** [buchen/portfolio#2996]
Hello,

Portfolio Performance is connecting to IP address 185.5.82.138 on startup.
DNS resolves to xb905528a.host.myracloud.com
Opening this IP in browser shows dummy website with no content.

Edit: It seems to come from some code connecting to "www.ecb.europa.eu", which resolves to the same IP address

Please inform what this connection is used for and how to disable it. 
Thanks!

**Comment by Morpheus1w3** [comment]
Well, PP require for curreny conversion exchange rates and PP retrieve them at start via https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html . Disabling is no option.

**Comment by uok** [comment]
Where is currencry conversion used? 
If you enter amounts into account, e.g. interest, it is Euro. If you buy a stock and scan PDF from bank / broker there is no conversion necessary.

**Comment by Morpheus1w3** [comment]
In your specific scenario might no conversion is required but it's a standard behaviour of PP that exchange rates are updated at program start. If you don't want it, block the IP at your router.

**Comment by buchen** [comment]
Indeed PP is downloading the reference exchange rates from the European Central Bank - regardless of the current file has any other currencies or not. There is no option to suppress this behavior.
