### ISSUE TITLE
CSV Import of Buy/Sell Securities fails - "Exchange rate of gross value is missing"

### ISSUE THREAD

**Issue by matt-winfield** [buchen/portfolio#3000]
**Bug Description**
When trying to import security transactions from CSV where type is buy or sell, and the transaction currency is different from the security currency (in my case, GBP and GBX), then those rows fail to be imported. The error indicates "Exchange rate of gross value is missing (transaction currency GBP and security currency GBX)"

**To Reproduce**
1. File -> Import -> CSV Files
2. Select CSV file containing transaction with type "Buy"
3. Data type is "Account Transactions"
4. Map the "Date", "Type", "Shares", "Value", "Exchange Rate", "Gross Amount" and "Currency Gross Amount" fields to the correct columns
5. Click next
6. The row is crossed out, right click to see the error

Adding the transaction manually through the UI works fine for this account

Example CSV that doesn't work:
```
Date,Type,Shares,Symbol,Description,Value,Contract Ref,ISIN,Sedol,Exchange Rate,Gross Value,Currency
17-Dec-2018,Buy,12.34,XYZ,EXAMPLE STOCK GBP,500.0,ZYX,GB00123,ABC,100,50000.0,GBX
```

**Expected behavior**
The transactions should be created successfully. It seems there was an update made that allowed this to work for dividend payments: https://forum.portfolio-performance.info/t/dividend-csv-update/15977
But it doesn't seem to work when the type is buy/sell.

This issue is discussed on the forum here: https://forum.portfolio-performance.info/t/exchange-rate-of-gross-value-is-missing-when-importing-csv-transactions-with-currency-conversions/20633/5?u=mattw

**Screenshots**
Screenshot of the error (Ignore “transaction does already exist”, that shouldn’t affect this):
![image](https://user-images.githubusercontent.com/15931560/194054084-107f55f1-4bb8-4490-a5a2-9c050ae6426a.png)

And the field mapping - I’ve tried mapping currency, gross amount, currency gross amount:
![image](https://user-images.githubusercontent.com/15931560/194054110-37702aca-efd1-401d-a9aa-0ab7c2989d11.png)

**Possible solution**
I had a look through the code and identified what may be causing the issue. I don't have local development set up to test the changes, but hopefully this points someone who's worked with this project more in the right direction:

It seems the bug might be caused by missing transaction.addUnit for buy/sell types.
Here is the code that imports Dividends and most other transaction types:
![image](https://user-images.githubusercontent.com/15931560/194054696-2b8d7cec-22ff-403d-94eb-d0c6a90e8884.png)

And here is the equivilant part for buy/sell:
![image](https://user-images.githubusercontent.com/15931560/194054760-94c03d36-4aaf-4e5a-b939-eb1d87629f6c.png)

You can see there is not something like the `t.addUnit(grossAmount.get()` for buy/sell, I would imagine if somehting like `buySellEntry.getPortfolioTransaction().addUnit(grossAmount.get())` was added here it might fix the issue.

Since that unit is not set, when transaction currency does not match security currency, it will try to get that unit and fail:
![image](https://user-images.githubusercontent.com/15931560/194054822-a443f2b0-abc1-44d2-b46b-cd63e1407b41.png)

**Desktop:**
 - OS: Windows
 - Version: 0.59.1 (Aug 2022)

**Comment by matt-winfield** [comment]
> Hello @matt-winfield The same problem exists with IBFlexquery and PDF importers. It is not an exchange rate error in that sense, but a currency error. (GBX <-> GBP | ZAC <-> ZAR | ILA <-> ILS | USD <->AED ... and so on). So one factor...
> 
> That itself results if you put a security in GBP for example and then the quotes are pulled in GPX.
> 
> I have not yet found a solution to the problem. Maybe @buchen has an idea how we could check and process fixed currency pairs with each other.
> 
> Look at -> [here](https://github.com/buchen/portfolio/blob/039ef44eea2481d3a05ce637929012e31f22dd55/name.abuchen.portfolio/src/name/abuchen/portfolio/money/impl/FixedExchangeRateProvider.java) <-
> 
> Greetings Alex

I'm not sure I understand - If my security is in GBX, and the transaction quote is in GBP (mapped to the "Currency Gross Amount" field), I have the "Exchange Rate" field that tells PP how to convert from GBX to GBP, doesn't it have all of the information it needs?

**Comment by matt-winfield** [comment]
Ah thanks @Nirus2000, I've got it working now. I see the issues I was having with my input data, the main one being my exchange rate being the wrong way around.
Thank you for your help!

**Comment by dakkusingh** [comment]
Same issue and the solution doesnt seem to work...
Here is my test file..
[Test.csv](https://github.com/buchen/portfolio/files/10374288/Test.csv)

<img width="716" alt="Screenshot 2023-01-09 at 15 08 58" src="https://user-images.githubusercontent.com/1692872/211340644-3678412f-70c2-4fc3-ac8b-666d8a79de8b.png">
<img width="1548" alt="Screenshot 2023-01-09 at 15 08 39" src="https://user-images.githubusercontent.com/1692872/211340678-57787a59-441c-4efe-92f2-4c25993e7ec8.png">
<img width="1418" alt="Screenshot 2023-01-09 at 15 08 46" src="https://user-images.githubusercontent.com/1692872/211340703-0fc93de0-7e0f-44d7-be2c-33cbce3ebbb0.png">

**Comment by dakkusingh** [comment]
it seems you have to choose:
Type of Data as "PortfolioTransactions" in order for the import to work correctly!

**Comment by Nirus2000** [comment]
Thx, thats the solution...
@dakkusingh

**Comment by jpiaia** [comment]
Hello everyone - I have been struggling with the same bug "Exchange rate of gross value is missing" but when importing Dividends, i.e. when selecting "Account Transactions' as type of data. I am surprised to see this Bug marked Closed, because for Dividends it does not seem to work yet?

**Comment by DrBroker007** [comment]
> it seems you have to choose: Type of Data as "PortfolioTransactions" in order for the import to work correctly!

Perfect! This worked!! Thanks @dakkusingh !!
