### ISSUE TITLE
Datumseingabe beim Kauf/Einzahlung falsch

### ISSUE THREAD

**Issue by mgehre** [buchen/portfolio#301]
Hallo,

wenn ich Wertpapier kaufe, und das Datumsfeld in diesem Dialog auf z.B.
1/18/2015 setzte,
dann steht danach in der Transaktionsliste die Transaktion mit dem Datum 2015-06-18. Der Monat ist falsch!

Dieses Problem ist reproduzierbar.

**Comment by mgehre** [comment]
Jetzt hatte ich das Problem mit 1/ 8/2014. Er machte daraus 2014-06-03 (den heutigen Tag im richtigen Jahr).

**Comment by mgehre** [comment]
Das Problem scheint nicht aufzutreten, wenn ich das Datum mit Pfeil-aufwärts und Pfeil-abwärts einstelle.

**Comment by buchen** [comment]
Du meinst schon diesen Kaufdialog, oder? Auf welcher Platform bist Du unterwegs? Auf meinem Mac kann ich da so ein Datum gar nicht eingeben.

![bildschirmfoto 2015-06-03 um 22 22 02](https://cloud.githubusercontent.com/assets/587976/7970509/01aa78c4-0a3f-11e5-9a55-012bcc380b89.png)

**Comment by mgehre** [comment]
![screen](https://cloud.githubusercontent.com/assets/774286/7970791/bec3d346-0a40-11e5-936d-ab5b281d3a8f.png)
Bei dir kann man das Datum im deutschen Format eingeben, bei mir ist es komischerweise MM-DD-YYYY.
Ich habe die letzte git revision und laufe auf Linux/Ubuntu.

**Comment by buchen** [comment]
Das ist ein "natives" SWT Widget, d.h. es sollte sich die Plattform-Einstellungen ziehen. Aber eine Eingabe von "1/18/2015" entspricht dem Format. Meint er plötzlich, es ist der 18. Monat?!?

**Comment by buchen** [comment]
Das Attribute wird [hier](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/BindingHelper.java#L218) an das Widget gebunden. Die Konvertierung macht meinem Verständnis nach komplett das DateTime Module. Hier findet das Plumbing statt: https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/SimpleDateTimeSelectionProperty.java

**Comment by buchen** [comment]
*DateTime does not support localization*
https://bugs.eclipse.org/bugs/show_bug.cgi?id=248075

**Comment by mgehre** [comment]
Danke, dass du dich darum kümmerst :+1:

**Comment by buchen** [comment]
CDateTime unter Linux funktioniert besser (zumindest bei meinem kurzen Test).
Ist in der nächsten Version drin.
