### ISSUE TITLE
Allow insertion of negative transactions

### ISSUE THREAD

**Issue by maxpsq** [buchen/portfolio#3013]
I'm requesting the possibility to insert negative transactions (in this case, the "save" button is deactivated). I have a quite unusual situation where a sell order of 2000 shares was executed only partially (only 1 single share) and the commissions are higher then the price of the single share sold.

```
Price sold    2,03 EUR
Commissions   4,91 EUR
             -2,88 EUR
```

**Comment by Nirus2000** [comment]
Negativ amounts are not supported.
Create a transaction for sell (2.03) and a fee transaction (4.91)
