### ISSUE TITLE
ImportExtractedItemsWizard zeigt # Shares nicht für Transfer Inbount/Outbound

### ISSUE THREAD

**Issue by alainschaefer** [buchen/portfolio#304]
Mir ist ebenfalls aufgefallen dass bei Transfer Inbount/Outbound im Import Dialog die Anzahl Aktien nicht angezeigt werden, sind aber korrekt im Model weil später in den Portfolio Transactions sichtbar. Bug oder Feature?

Bug. Ich hatte bisher noch keinen Transfer. Und: funktioniert das überhaupt schon? Ich glaube man müsste dafür noch ein Item anlegen... oder das BuySellItem generisch machen.

**Comment by buchen** [comment]
Ich habe den Import Wizards mal um die Umbuchungen erweitert.

Ich habe neue Items angelegt:
```java
    public List<Item> extract(String text, String filename, List<Exception> errors)
    {
        List<Item> results = new ArrayList<Extractor.Item>();

        AccountTransferEntry t = new AccountTransferEntry();
        t.setDate(Dates.today());
        t.setAmount(1_00);
        results.add(new AccountTransferItem(t));

        PortfolioTransferEntry t2 = new PortfolioTransferEntry();
        t2.setDate(Dates.today());
        t2.setAmount(1_00);
        t2.setShares(Values.Share.factorize(1.23));
        t2.setSecurity(allSecurities.get(0));
        results.add(new PortfolioTransferItem(2));

        return results;
    }
```

Ganz konkret fehlt noch etwas Fehlerbehandlung (Umbuchung auf das gleiche Konto).

Für die doppelten Buchungen haben wir ja noch ein anderes Ticket.

In dem [feature_currencies](https://github.com/buchen/portfolio/tree/feature_currencies) Branch habe ich auch Dialoge mit denen man existierende Buchungen editieren kann. Aktuell kann man ja über die Dialog nur neue Buchungen anlegen und dann in der Tabelle in-place editieren. Wenn ich den Branch gemergt habe, dann könnte man auch durch eine Doppelklick die Buchung editieren. Und dann natürlich auch Konten und Portfolios beliebig ändern. Ich lege dazu mal ein separates Ticket an.

**Comment by buchen** [comment]
BTW, ich denke am einfachsten machst Du einen Rebase Deines Branches auf den neue HEAD von master. Meinem Verständnis nach müsste das in den selben Pull Request gepusht werden.

**Comment by alainschaefer** [comment]
Nachdem ich nun auf DELIVERY_INBOUND / OUTBOUND umgestellt habe, kann ich leider nicht mehr überprüfen ob bei TRANSFER_IN / OUT die # shares angezeigt werden. Auf jeden Fall werden diese bei DELIVERY_INBOUND / OUTBOUND korrekt angezeigt.
