### ISSUE TITLE
ImportExtractedItemsWizard zeigt keine Account Transaktionen

### ISSUE THREAD

**Issue by alainschaefer** [buchen/portfolio#305]
Wesshalb werden in dem Import Fenster nur die Securities und die Wertpapier Käufe angezeigt? Account Transaktionen sollten doch auch angezeigt werden, z.b. Einlagen. Bug oder Feature?

Bug. Das entsteht halt nach und nach und aus den PDFs habe ich bisher nur Käufe/Verkäufe und Dividenden extrahiert. Alles andere kann tun, muss aber nicht.

**Comment by buchen** [comment]
Ich habe das gerade mal getestet. Bei mir werden Einlagen im Dialog angezeigt:

```java
    public List<Item> extract(String text, String filename, List<Exception> errors)
    {
        List<Item> results = new ArrayList<Extractor.Item>();

        AccountTransaction t = new AccountTransaction();
        t.setDate(Dates.today());
        t.setAmount(1_00);
        t.setType(AccountTransaction.Type.DEPOSIT);

        results.add(new TransactionItem(t));

        return results;
    }
```

Wichtig: Mit dem ```TransactionItem``` kann man momentan nur "einfache" Buchungen anlegen. Also nicht die Umbuchungen. Dazu braucht es ja auch ein Gegenkonto (oder Gegenportfolio).

Umbuchungen schauen wir uns dann in #304 an.
