### ISSUE TITLE
Icon for Deposit Account

### ISSUE THREAD

**Issue by metal450** [buchen/portfolio#3054]
It's great how we can attach an icon to each security, i.e. to replace the generic "green" icon. Is there some way to also attach an icon to a deposit account, i.e. to replace the generic "orange" icon?

**Comment by OnkelDok** [comment]
Should possible right now: https://forum.portfolio-performance.info/t/logos-fuer-konten-einstellen/10318
I hope link to German forum section is OK.

**Comment by metal450** [comment]
Aha - with google translate, I got it - thanks!
