### ISSUE TITLE
Save the time ranges in the .portfolio file

### ISSUE THREAD

**Issue by ngosang** [buchen/portfolio#3060]
**Is your feature request related to a problem? Please describe.**
I just moved to a new computer and I had to setup a lot of "time ranges".
![imagen](https://user-images.githubusercontent.com/10577978/204988850-d29be49b-5b28-46d2-bab9-00b5a68fa564.png)

**Describe the solution you'd like**
It will be convinient if you can save them  in the .portfolio file, with the prices, dashboards, etc..

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by sebasbaumh** [comment]
This is similar to #2952 .

A workaround is to enable "Store GUI settings next to Portfolio Performance file" in the settings of Portfolio Performance (Settings -> General).

**Comment by ngosang** [comment]
Yeah, that works for me.
Could you tell me where are the "settings files" in Windows if I don't check that option?

**Comment by sebasbaumh** [comment]
It seems to be in the workspace folder, see [here](https://forum.portfolio-performance.info/t/loss-of-custom-settings-after-moving-a-folder/5968) and [here](https://help.portfolio-performance.info/installation/#workspace-verzeichnis).

I usually just store the Portfolio Performance file as compressed XML in my Dropbox and if the option is checked, the settings file ends up there as well.

**Comment by ngosang** [comment]
I can not find any .settings file in `%LOCALAPPDATA%\PortfolioPerformance\workspace`
Anyway, this solves my issue. I will configure PP for the last time :)
