### ISSUE TITLE
Add more space for the portfolio file name

### ISSUE THREAD

**Issue by ngosang** [buchen/portfolio#3061]
**Is your feature request related to a problem? Please describe.**
Add more space for the portfolio file name. I know this is a really minor thing but the UI could be more responsive.
![imagen](https://user-images.githubusercontent.com/10577978/204989065-c96c45bb-2ecd-4a27-99de-98ba5a9a01a0.png)

**Describe the solution you'd like**
Responsive UI.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by buchen** [comment]
Fixed
