### ISSUE TITLE
NewClient Wizard sollte Basiswährung erfragen, und Währungen für Portfolio und Konten

### ISSUE THREAD

**Issue by alainschaefer** [buchen/portfolio#307]
Ich beginne mal für einzelne der in #14 erwähnten Punkte Issues zu erstellen. Ich hoffe das ist so ok.

1. Die Basiswährung sollte diese in einer separaten Page erfragt werden oder auf der gleichen Page wie die Porfolios und Konten erstellt werden ? Ich hätte hier eine seprate Page ähnlich wie im Migration Dialog gemacht.

2. Ich bin für KISS. Meiner Meinung nach wäre es nicht unbedingt notwendig im Wizard die Währung für Portfolios und Konten abzufragen. Der Fall das Portfolios und Konten in einer anderen als der Basiswährung geführt werden ist wohl relativ selten und so ein Benutzer kann nach dem Wizward dann "manuell" im Portfolio/Konto die Währung ändern. Lasse mich aber gerne überzeugen.

**Comment by buchen** [comment]
Hat es in den Fingern gejuckt?!? :wink: Ich gucke dass ich im Laufe des Tages mir den Change angucke.


> Ich bin für KISS. Meiner Meinung nach wäre es nicht unbedingt notwendig im Wizard die Währung für Portfolios und Konten abzufragen.

KISS ist mir auch wichtig. Da ich ab dieser Version zwingend eine Währung brauche (ich möchte nicht an allen Stellen auf eine nicht existierende Währung prüfen) und die ggf. auch verschiedenen Stellen angezeigt wird, sollte der Benutzer eine wählen. Eine kleine Drop-Down irgendwo und EUR vorgelegt, und gut ist.

**Comment by buchen** [comment]
BTW, wenn Du topic branches direkt auf "upstream/feature_currencies" (statt auf "master/feature_currencies") aufsetzt, dann habe ich die zusätzlichen merge commit nicht in der Historie - siehe rote Linie.

![bildschirmfoto 2015-06-07 um 11 43 55](https://cloud.githubusercontent.com/assets/587976/8023418/ebe46ea8-0d0b-11e5-88c3-2a3f671e26b8.png)

Normalerweise versuche ich in den Topic branch nicht zu mergen. Allerdings war feature_currencies jetzt schon so alt und so weit hinterher und dabei noch so weit weg von einem Merge, dass ein Merge nötig war...

**Comment by alainschaefer** [comment]
Ich möchte feature_currencies voranbringen damit ich PP hoffentlich bald
für mich einsetzen kann. Mit so kleinen changes komme ich langsam in deine
schön strukturierte CodeBasis rein.

Leider bin ich mit Git noch etwas verloren. Meinst du ich solle in Zukunft
einen Checkout von upstream/feature_currencies in einen lokalen Branch
machen und diesen auf meinen fork pushen um dann da den Pull request zu
machen ? Sorry für die blöden Fragen.


2015-06-07 18:57 GMT+09:00 Andreas Buchen <notifications@github.com>:

**Comment by buchen** [comment]
Ja, das ist glaube am einfachsten. Du machst einen Branch auf dem letzten Commit von "upstream/feature_currencies" - sagen wir "feature_newclientwizard" - und den pusht Du dann in Dein Repository und machst einen Pull Request auf.

(Ich persönlich nutze ja [Gerrit](https://code.google.com/p/gerrit/) viel lieber für Code Reviews. Github nutzt halt Pull Requests).

**Comment by buchen** [comment]
> Ich möchte feature_currencies voranbringen damit ich PP hoffentlich bald
für mich einsetzen kann.

Du hast mich aktiviert. Ich habe gestern mal angefangen, die fehlenden Dialog auf Währungen umzustellen.
