### ISSUE TITLE
"Open in Browser" konfigurierbar machen

### ISSUE THREAD

**Issue by alani1** [buchen/portfolio#309]
Ich würde gerne zusätzliche Webseiten zum Kontext Menu hinzufügen. Dazu sollten die Webseiten konfigurierbar sein. 

Idee:
 * Neue WebLocationPreferencesPage  mit einer Liste/Tabelle von (Label, Pattern).
 * WebLocationMenu lädt das IniFile und erstellt die WebLocation Objekte
 * default preferences enthalten alle Websites welche heute schon statisch im Menu erzeugt werden

**Comment by buchen** [comment]
:+1: Sehr gute Idee. Ich bin selber nie dazu gekommen, weil... na ja... ich kann sie ja einfach hinzufügen...

Alle Punkte (eins bis drei) sehe ich auch so.

Die einzige Frage für mich: Wo speichern? Als "preference" im "workspace" Verzeichnis? Das gilt dann für alle geöffneten Dateien, aber eben nur in dieser Installation. Oder im "client"? Das ist dann pro Datei, die Datei bei Änderungen als "dirty" markiert, aber wenn man die Datei auf einem anderen Rechner öffnet, sind die Kontenmenüs da. Was meinst Du?


Dann fände es super, wenn man auch einen Separator hinzufügen könnte. Sagen wir mal in dem der Bookmark Name einfach ein "-" dash ist:

| Bookmark | URL |
| ------------- | ------ |
| Yahoo Finance | http://de.finance.yahoo.com/q?s={tickerSymbol} |
|   - |   |
| Nächstes... | |

Momentan werden nur *isin* und *tickerSymbol* unterstützt. Ich würde mindestens noch *wkn* hinzufügen, vielleicht noch *name* (als Suchanfrage).

**Comment by alainschaefer** [comment]
Ich hätte die WebLocations im inifile gespeichert, gleich wie die Spracheinstellung. Aber irgendwie wenn ich so an speichern in der Cloud denke ist die Idee die Bookmarks im Client zu speichern bestechend!

1. Passt dann der Dialog noch zu den Preferences ? Die sind ja unabhängig vom geöffneten File. Falls nicht wohin damit ?
2. Wie speichern im Client ? ein neues private attribute bookmarks vom Typ Map ?

**Comment by buchen** [comment]
> Passt dann der Dialog noch zu den Preferences ? Die sind ja unabhängig vom geöffneten File. Falls nicht wohin damit ?

Guter Punk. Vielleicht könnte man in der Navigationszeile unter "Allgemeine Daten" noch einen Punkt "Einstellungen" einfügen. Da sind dann momentan nur die Bookmarks. Falls mehr kommt, könnte man ja noch mehr Reiter erstellen.

> Wie speichern im Client ? ein neues private attribute bookmarks vom Typ Map ?

Im Client gibt es schon ein Attribut "properties" für generische key-value pairs  - allerdings als Strings. Entweder Du speicherst Die Bookmarks da - in irgendeiner Form - serialisiert. Oder man bohrt das auf und macht eine Map<String, Object>. Ich würde ersteres mal ausprobieren. Wenn das zu umständlich wird, dann eher aufbohren. Mein Hintergedanke: ich möchte eine Proliferation von Attributen im Client vermeiden.


> Ich hätte die WebLocations im inifile gespeichert, gleich wie die Spracheinstellung.

Die Spracheinstellung ist dann spezifisch weil die Local vor dem Start gesetzt werden muss. Darum ist die in dem "inifile". Andere Einstellungen kann man auch separat speichern (die landen dann im Workspace Folder).

**Comment by buchen** [comment]
Ah ja, und die Change kann ruhig gegen master gehen. Dafür brauchen wir nicht auf den *feature_currencies* branch warten.

**Comment by alainschaefer** [comment]
Hi Andreas,

klar geht der gegen Master. Ich habe nun einen ersten Entwurf. Es fehlt
noch das Speichern/Serializing im Client. Habe eine ClientSettings Klasse
erstellt welche die WebLocations in einer ArrayList hält, so musste ich am
Client gar nichts ändern. Das Serializing würde ich gerne erst beim
speichern des Files machen. Wie kann ich eine Klasse beim Client
registrieren so dass diese über einen beforeSave Event informiert wird ?
Lesen vom Client tue ich indem die Klasse als Propertylistener registriert
ist.

Es fehlt mir im TableViewer noch eine möglichkeit die WebLocations
umzuordnen. Ev. lass ich das in einer ersten Version auch weg. Deine
Vorschläge Separator, wkn und name sind implementiert.

2015-06-07 21:20 GMT+09:00 Andreas Buchen <notifications@github.com>:

**Comment by buchen** [comment]
>  Das Serializing würde ich gerne erst beim
speichern des Files machen. Wie kann ich eine Klasse beim Client
registrieren so dass diese über einen beforeSave Event informiert wird ?

So einen Event gibt es nicht. Bisher habe ich bei solchen Fällen bei der Änderung einfach "drüber" serialisiert. In dem Fall der "Bookmarks" ändert sich das ja auch nicht häufig - nur wenn der Benutzer in der Einstellungenansicht tatsächlich eine Änderung vornimmt. Kann man da nicht z.B. die ClientSettings#toString in die Client Properties schreiben? Zu simplistisch?

Ansonsten müsste man einen Event einführen. Und eine - wie auch immer geartete - Registrierung von Listeners.

> Es fehlt mir im TableViewer noch eine möglichkeit die WebLocations
umzuordnen. Ev. lass ich das in einer ersten Version auch weg. 

Genau. Lieber kleine Inkremente.

**Comment by buchen** [comment]
Ich sehe gerade Du hast schon was in Dein Repo gepusht. Mir ist noch die Idee gekommen, dass man die Konfiguration ja auch aus dem Kontextmenü aufrufen könnte. Also ein letzter Menüpunkt "Bookmarks konfigurieren..." oder so ähnlich. Dann ist die Konfiguration auch an der Stelle, an der man sich gerade denkt, Mensch, ich würde doch noch andere Bookmarks haben wollen.

**Comment by alainschaefer** [comment]
gute Idee ! Das kann ich gerne noch hinzufügen. Hast du eine Idee wie man vom WebLocationMenu an eine Referenz auf das PortfolioPart kommt ? Denn da müsste ich wohl activateView(view, parameter) aufrufen.

**Comment by buchen** [comment]
Die ```AbstractFinanceView``` hat eine Methode #getPart. Ein bisschen blöd, aber weiterreichen?

**Comment by buchen** [comment]
Im Prinzip fehlt jetzt eigentlich nur ein "drag & drop" um die Bookmarks in die richtige Reihenfolge zu bringen.
