### ISSUE TITLE
Targobank PDF import no longer working

### ISSUE THREAD

**Issue by Fail-Unsafe** [buchen/portfolio#3092]
Targobank PDF import no longer working correctly.

I try to import both the Steuerbeilage and the Ertragsgutschrift at the same time. But the result is as follows:

![Bildschirmfoto von 2022-12-20 17-19-10](https://user-images.githubusercontent.com/26485846/208716638-5f2cc26c-58f0-46bf-900d-b720367a1785.png)
[Ertragsgutschrift vom 2022-12-14.pdf.txt](https://github.com/buchen/portfolio/files/10270262/Ertragsgutschrift.vom.2022-12-14.pdf.txt)
[Steuerbeilage vom 2022-12-16.pdf.txt](https://github.com/buchen/portfolio/files/10270263/Steuerbeilage.vom.2022-12-16.pdf.txt)

**Comment by buchen** [comment]
@Nirus2000
