### ISSUE TITLE
Payments sum is calculated only for the first year

### ISSUE THREAD

**Issue by dylan09** [buchen/portfolio#3094]
**Describe the bug**
In the Reports → Payments column, only the total for 1 year is calculated.
If I select several years for the evaluation, only the value from the first column is used for the total column. If there is no value in the first year, the sum column also remains empty.

**To Reproduce**
See above. Additional Information see [this thread](https://forum.portfolio-performance.info/t/zahlungen-summe-wird-nur-fur-das-erste-jahr-berechnet/22536) in PP forum.

**Expected behavior**
Sum of all columns.
 
**Screenshots**
See [this thread](https://forum.portfolio-performance.info/t/zahlungen-summe-wird-nur-fur-das-erste-jahr-berechnet/22536) in PP forum

**Desktop (please complete the following information):**
 - OS: macOS
 - 0.59.3 (Nov. 2022)

**Comment by buchen** [comment]
Fixed with ab8b972fc3631d40d8220f883d0e53ee86958160
