### ISSUE TITLE
IBKR: Flex Query import total price of trade

### ISSUE THREAD

**Issue by seg-on** [buchen/portfolio#3095]
I find out that importer (IBKR: Flex Query import) import to total value of stock's price with fee and then to the fee the fee price.
Total price of trade include 2 times fee.

Here is detail from PP
![image](https://user-images.githubusercontent.com/19683952/209153701-9f2e5117-5f80-4f5a-ba2f-40c56634dd8c.png)

In XML is traded price of one share $14,05 total price $140,5 and fee $0,33125725

And one another thing. The conversion rate is different. But it is a separate FX trade automatically make by IBKR. Maybe it is too complicated to use conversion rate of the FX trade. Only note.

[AFQ__PP.xml.txt](https://github.com/buchen/portfolio/files/10288000/AFQ__PP.xml.txt)

OS: Windows
Version 0.60.0

**Comment by seg-on** [comment]
I would like to analyze more older trades. When I will have time.

**Comment by seg-on** [comment]
I analyzed deeper in the history and there is always a fee included 2 times. Once in the price of the shares purchased and the second time in the fees. But in flex it is separate.

**Comment by Nirus2000** [comment]
Hello @seg-on 

> In XML is traded price of one share $14,05 total price $140,5 and fee $0,33125725

Of course, the broker in the XML file has indicated the price of 14.05 per share, but by the fees, which is divided by the number of shares, this is added to the purchase price, which PP gives you here.
So you do not purchase a share for `14.05` but for `14.083`.
`14,05 + (0,33125725 / 10) = 14,083125725`
Okay? I hope this helps you...

Alex
