### ISSUE TITLE
java.lang.NullPointerException while importing "Sparplan Abrechnungen" from TradeRepublic

### ISSUE THREAD

**Issue by Streethawk27** [buchen/portfolio#3113]
**Describe the bug**
While importing my "Sparplan Abrechnungen" (11 pieces) from TradeRepublic a java.lang.NullPointerException occurs

[nullpointer.txt](https://github.com/buchen/portfolio/files/10366218/nullpointer.txt)

**To Reproduce**
1. Go to 'Importieren  - PDF Bankdokumente'

**Expected behavior**
Import works

**Screenshots**
![image](https://user-images.githubusercontent.com/88531074/211150272-4f0ae5ff-791f-4367-8cc0-f907f7ee70a7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.60.1

**Comment by Streethawk27** [comment]
The exact document type from TR is "WERTPAPIERABRECHNUNG SPARPLAN"

The error also occurs, when I only select one instance

**Comment by Streethawk27** [comment]
Now I found the reason: the "Gegenkonto" was deactivated

**Comment by Nirus2000** [comment]
@Streethawk27 
If the error was found, is the please close ticket please?!

**Comment by Streethawk27** [comment]
Ok, i will close the ticket.
Just one question: Is it unconditional necessary, that a "Gegenkonto" is selected? Probably an error message would be helpful rather than a null pointer exception.

**Comment by Nirus2000** [comment]
Done 👍🏻 
Is fixed...
