### ISSUE TITLE
feature_currencies: Import/Export (CSV, PDF, ...) muss Währung erfassen

### ISSUE THREAD

**Issue by alani1** [buchen/portfolio#317]
Hi Andreas,

Mein Projekt fuer naechstes Weekend oder eher fuer die naechsten Wochen :-)

Frage :
Kann ich den merge von feature_interactivebroker auf Master cherrypicken auf meinem feature Branch oder fuehrt das spaeter zu einem Merge conflict ? 

1. Moechte ich den Extractor erweitern so dass auch Currency und Exchange Rate unterstuezt, zusammen mit erweitern des IBExtractors
2. CVS Import erweitern, ev. gleich zusammen mit #295
3. Export

Fuer die einzelnen Schritte wuerde ich dann separate PR auf feature_currencies erstellen, so dass das ganze noch etwas ueberblickbar bleibt.

**Comment by alainschaefer** [comment]
Ist mir gerade noch durch den Kopf gegangen. Ev. kann man den Extractor auch erweitern dass er historische Wechselkurse importieren kann ? In meinen XML Files sind diese jeweils fuer alle Waehrungen des Portfolios enthalten. Ich wuerde es vorziehen die Wechselkurse meines Brokers zu verwenden als diese der ECB. Ev. waere dies aber auch ein separates Feature/Issue.

**Comment by buchen** [comment]
> Ev. kann man den Extractor auch erweitern dass er historische Wechselkurse importieren kann ? 

Irgendwann soll man auch eigene Wechselkurse erfassen können. Momentan fehlt komplett die Infrastruktur die a) im Client zu speichern und b) aus mehreren Serien (€->$) die richtige zu bestimmen. Dann will man das editieren können, vielleicht eine Fallback falls die eine Serie nicht vollständig ist. Der einfachheithalber lasse ich das alles momentan weg. Man kann nur die Kurse der EZB nutzen. Und man kann nur die Währungen der EZB auswählen. Wenn der Rest steht, kann man hier ran.

Zu den Exporten: macht absolut Sinn. Von der Komplexität her würde ich das genau umgekehrt angehen, von leicht nach schwer. Am besten separate kleine Changes, die kann ich schneller anschauen und mergen.

Zu dem ersten Punkt. Ich habe mich noch nicht final entschieden wie ich die base/term currencies speichere. Du siehst die Forex Klasse in den Buchungen.

**Comment by alainschaefer** [comment]
Dank fuer die Rueckmeldung, verstehe dann lassen wir das importieren der Kurse noch weg. Ich bin intrinsisch motiviert und habe desshalb die Reihenfolge so gewaehlt. Du konntest mich jedoch schon das eine oder andere Mal ueberzeugen :-)

Zurueck zu meiner Frage, ist cherry-picking ok, oder warte ich besser bis feature_currencies wieder von master aktualisiert wird ?

**Comment by buchen** [comment]
> Zurueck zu meiner Frage, ist cherry-picking ok, oder warte ich besser bis feature_currencies wieder von master aktualisiert wird ?

Ich merge Dir den lieber rein. #319 Ich habe das bisher nicht über das Web UI gemacht. Mal sehen ob ich das richtig hinbekomme. Nach einem Cherry-pick sehe ich beim Pull Request viel zu viel.

**Comment by buchen** [comment]
Ich kann das nicht automatisch mergen - da ist eine Code Änderung notwendig (die Values Klasse ist umgezogen). Mach das doch lokal, setze dann Deine Changes drauf. Wenn ich dass zentral nachgezogen habe, dann ziehst Du Deine Änderungen auf den neuen tip um.

**Comment by alainschaefer** [comment]
Danke ! Lass dir nur Zeit, zuerst kommt ja jetzt der Export ....

**Comment by buchen** [comment]
FYI: Ich habe master gerade in feature_currencies gemergt und gepusht.

**Comment by buchen** [comment]
Hi @alani1 - Du hast vielleicht schon gesehen, dass ich komplett auf das Java 8 Time API umgestellt habe. Die Änderung ist schlussendlich doch grösser geworden als gedacht. Ich hoffe für Dich - im CSV import / export sind die Änderungen überschaubar. Du solltest aber auf jeden Fall eine rebase Deiner Change auf den feature_currencies Branch machen. Ein Merge in Deinen Branch hinein wird schwieriger auseinander zu nehmen sein.

Eine schöne Sache ist auch, dass (fast) alle Warnungen verschwunden sind. Nur noch das "restricted API" von Eclipse 4. 

<img width="258" alt="bildschirmfoto 2015-07-05 um 08 44 09" src="https://cloud.githubusercontent.com/assets/587976/8510605/81a85f70-22f2-11e5-99c4-1199be148cca.png">
