### ISSUE TITLE
PP 0.61.0 (sometimes) freezes when importing multiple PDF documents

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#3191]
### Observations
* seems to occur only on Windows 10 and Windows 11
* happens after the update to Java 17 and Eclipse 2022-12 (no change in pdfbox version)

### Generated thread dumps
[dump1.txt](https://github.com/buchen/portfolio/files/10776428/dump1.txt)
[dump2.txt](https://github.com/buchen/portfolio/files/10776429/dump2.txt)
[dump3.txt](https://github.com/buchen/portfolio/files/10776430/dump3.txt)

### Some analysis through https://fastthread.io
[ft-report-dump1.pdf](https://github.com/buchen/portfolio/files/10776431/ft-report-dump1.pdf)

**Comment by buchen** [comment]
@Nirus2000 @chirlu @OnkelDok help wanted - not sure what to make out of those dumps

**Comment by Nirus2000** [comment]
@tquellenberg @RomanLangrehr @inv-trad

**Comment by buchen** [comment]
The main thread waits in line 190 of ImportPDFHandler. Which is **after** the files have been converted from PDF to text. I'd say this issue is not related to loading pdfbox.

```
"main" #1 prio=5 os_prio=0 cpu=19296.88ms elapsed=7628.47s tid=0x0000022d59d96050 nid=0xc60 runnable  [0x00000050be8fc000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.win32.OS.WaitMessage(Native Method)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:4752)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:824)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler$1.lambda$0(ImportPDFHandler.java:190)
	at name.abuchen.portfolio.ui.handlers.ImportPDFHandler$1$$Lambda$3768/0x0000000801248c58.run(Unknown Source)
```

The Equinox container is also in Unsafe.park when PP is running normally.

```
"Active Thread: Equinox Container: f35d97b1-b164-4a21-8aaa-6969711f89b1" #16 prio=5 os_prio=0 cpu=0.00ms elapsed=7615.40s tid=0x0000022d7424b6c0 nid=0x3214 waiting on condition  [0x00000050bfdff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.5/Native Method)
	- parking to wait for  <0x00000000c04f7570> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
```

There is no worker thread doing anything?!?

**Comment by buchen** [comment]
Eclipse 2022-12 had a change in the JobManager implementation:
https://www.eclipse.org/eclipse/news/4.26/platform_isv.php#JobManager_Implementation

**Comment by OnkelDok** [comment]
I dont any experience in reading Java dumps, but there is one thing I am wondering about (without big knowledge about threads and jobs in java).

In each of the dumps the following stack entry is always present twice:
```
- locked <0x00000000c09f29d0> (a org.eclipse.core.internal.jobs.WorkerPool)
```
The line above is from ``dump1.txt``. In other files the same stack entry can be found twice (but with different lock ID).
Is the part after the ``-locked `` statement the pointer of the lock? Does that mean that two threads locked the same lock-object? But it is possible that a lock-object is locked twice?

**Comment by buchen** [comment]
> Does that mean that two threads/workers have locked the same lock-object? But it is possible that a lock-object is locked twice?

I also do not know. A thread dump of a regular (not frozen) process looks the same. And: if the there was a job still executing, then I would expect to see on on the stack trace.

My theory: the job completed, but doesn't get into the UI thread to close dialog because the wizard dialog was opened in parallel from another async execution. Maybe both operations - closing a modal dialog and opening a modal dialog - now block each other? The code was anyway unnecessarily complex - I have reordered the statement, build a test version, and shared it with the users that have provided thread dumps.

**Comment by buchen** [comment]
I have one tester reporting that he cannot reproduce the lock anymore. I will create a new release, but it will be Wednesday the earliest
