### ISSUE TITLE
Changes in the PDF structure of Bondora

### ISSUE THREAD

**Issue by MarcMocker** [buchen/portfolio#3205]
**Describe the bug**
Bondora changed the structure of it's generated PDFs from the Go and Grow product.

**To Reproduce**
1. Generate a PDF report for your God and Grow account (doesn't happen with an old report) 
2. Import it into Portfolio Performance 
3. Now the date listed transactions on your go and grow account in pp shows the month as day and the day as month and the cents as euros. E.g. The date in the report was changed from dd/mm/yyyy to mm/dd/yyyy and for example the notation for 12 cents was changed from 0,12 € to 0.12 €

**Expected behavior**
The import function should work with the new file structure. 

**Desktop (please complete the following information):**
 - OS: Debian Sid (unstable) 
 - Linux, x86_64
 - Java 17.0.6
 - Version 0.61.3
But the problem should happen independent from the respective OS

**Comment by Nirus2000** [comment]
Hello @MarcMocker 
 please post them here.
You can see how it works in the video tutorial.

Video tutorial:
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

**Comment by MephistoaD** [comment]
Hello @Nirus2000 

I'm so sorry, but the export from this month had the old shape again.
However I'm not sure if they keep that permanently now.
Is there a way to change this back?

**Comment by Nirus2000** [comment]
Hello @MephistoaD 
Create a new PDF debug and post it, then I'll take a look.

Greetings
Alex
