### ISSUE TITLE
The money weighted rate of return (MWRR)

### ISSUE THREAD

**Issue by DiogoCruz40** [buchen/portfolio#3212]
**Is your feature request related to a problem? Please describe.**
It's very important for me to have a rate that takes into consideration my cash flow in/outs. This rate solves this problem.

**Describe the solution you'd like**
To add as a widget in the Performance tab.

**Comment by RomanLangrehr** [comment]
As far as I know money weighted rate of return is just another name for the internal rate of return, and there already is a widget for that.

**Comment by DiogoCruz40** [comment]
You are right! Thanks!
