### ISSUE TITLE
Fees & Taxes in Transaction Currency

### ISSUE THREAD

**Issue by alani1** [buchen/portfolio#324]
> > Mir ist aufgefallen dass Fees in der Kontowährung sind, bei mir sind die Transaktionskosten aber  in der Währung des Handelsplatzes d.h. in der gleichen Waehrung wie das Securitiy

> Mist. Das ist momentan so: Gebühren sind in Kontowährung. Mit ist auch aufgefallen, dass das zu komischen Effekten führt. Zum Beispiel eine Umbuchung von Wertpapieren braucht keine Währung (ist ja z.B. in EUR notiert). Bei einer Einlieferung braucht ich - für die Gebühren auf dem Konto - aber ggf. einen Wechselkurs. Ersteres führt dazu das in der Liste der Buchungen sich die Währungen mischen (mal EUR, mal $).

> Ich überlege auch schon wie man das flexibilisieren kann...
Eine Möglichkeit ist natürlich aus einem "Vorgang" mehrere Buchungen zu generieren: den Kauf, die Steuern, die Gebühren in $, die Gebühren in EUR, und so weiter. Bisher war mir das zu umständlich weil mir die Klammer für diesen Vorgang fehlt (CrossEntry ist schon umständlich genug). Darum habe ich Gebühren und Steuern an die Buchung angehängt. Diese Entscheidung kann man natürlich jetzt - im Lichte der Währungen - noch mal neu überdenken.
Alternativ könnte ich mir auch die Transaction als "Vorgang" vorstellen. Mit einer Liste von Komponenten (Steuern, Gebühren) die jeweils Ihre eigene Währung haben können. Das hätte den Vorteil, dass Buchungen (Transactions) weiterhin dem entsprechen was man UI in einer Zeile sehen möchte und darum hoffentlich programmatisch einfacher zu handhaben sind.

> Bis es soweit ist, würde ich vorschlagen die Gebühren umzurechnen. Jetzt etwas zu importieren was nicht vom Modell unterstützt wird, bringt nichts. Man muss vielleicht auch noch sicherstellen (warnen), dass der Benutzer keine USD Buchungen mit einem Wechselkurs nach CAD auf ein EUR Konto importiert. Zumindest dann, wenn die Basiswährung der Buchung im CSV steht.

**Comment by buchen** [comment]
Mit
> Mit einer Liste von Komponenten (Steuern, Gebühren) die jeweils Ihre eigene Währung haben können. Das hätte den Vorteil, dass Buchungen (Transactions) weiterhin dem entsprechen was man UI in einer Zeile sehen möchte und darum hoffentlich programmatisch einfacher zu handhaben sind.

meinte ich sowas in die Richtung
```
public class NewTransaction
{
    enum ComponentType
    {
        BRUTTO, FEE, TAX, RETAINED_EARNINGS;
    }

    public static class TransactionComponent
    {
        ComponentType type;
        Money amount;
        ForexData forex;
    }

    List<TransactionComponent> components;
    
    Date date;
    Money amount;

    Security security;
    long shares;
    String note;
}
```

Und dann wäre es auch interessant, wenn der Benutzer eigene Unterkategorien definiert könnte. Also zum Beispiel wenn er die verschiedenen Steuern separat erfassen möchte.

Alles aber erst mal Zukunftsmusik. :smile: :sleeping:

**Comment by buchen** [comment]
@alani1 Ich habe mal etwas rumgespielt - siehe den Branch. Über Überlege ob ich ForexData rauswerfe, stattdessen in einer Buchung weitere Bestandteile ("[Transaktion.Unit](https://github.com/buchen/portfolio/blob/ffc1abb92dc57f2591cab05a9315dfb5d4ada79e/name.abuchen.portfolio/src/name/abuchen/portfolio/model/Transaction.java#L19)") erfasse. Die Units wären für den Nettobetrag, Steuer, Gebühren und ähnliches gedacht. Es könnte prinzipiell mehrere Einträge für eine Kategorie geben - so kann man Gebühren sowohl in der Währung der Transaktion als auch des Wertpapiers erfassen.

In der PortfolioTransaction müssten dann Gebühren [berechnet](https://github.com/buchen/portfolio/blob/ffc1abb92dc57f2591cab05a9315dfb5d4ada79e/name.abuchen.portfolio/src/name/abuchen/portfolio/model/PortfolioTransaction.java#L71) werden. Beim Laden alter Dateien würden das Modell konvertiert - die Felder Gebühren und Steuern würde ich [deprecaten](https://github.com/buchen/portfolio/blob/ffc1abb92dc57f2591cab05a9315dfb5d4ada79e/name.abuchen.portfolio/src/name/abuchen/portfolio/model/PortfolioTransaction.java#L29).

Beim [Nettobetrag](https://github.com/buchen/portfolio/blob/ffc1abb92dc57f2591cab05a9315dfb5d4ada79e/name.abuchen.portfolio/src/name/abuchen/portfolio/model/PortfolioTransaction.java#L107) bin ich mir noch unsicher ob man den immer berechnet, oder immer also Unit speichert. Bei ersterem könnte man sich optional den Nettobetrag "nur" für Buchungen mit Fremdwährungen merken.

Das Ganze heißt nicht, dass man keine Builder braucht. Also Nettobetrag, Betrag der Buchung, Gebühren und Steuern müssen konsistent gesetzt werden. Und zu jeder Unit muss der Betrag auch in der Währung der Buchung vorliegen - also meist der des Kontos.

Sag mal was Du davon hältst. (Mir ist klar, dass da weder die Tests laufen noch das UI kompiliert).

**Comment by alani1** [comment]
Hallo Andreas,

Verstehe ich richtig eine Transaktion besteht aus x Units, jedoch mindestens eine welche der Bruttobetrag wäre? Ein interessanter Ansatz ! Sicher sehr flexible erweiterbar. Ev. könnte man getAmount in Unit so implementieren dass er transparent umrechnet in die Transaktionwährung ?  So wie ich das sehe kann die ExchangeRate nachtraeglich nicht mehr geaendert werden. Ist das so gewollt ?

Nettobetrag koennte man ev. im Modell erst nach Bedarf berechnen und müsste man nicht im XML speichern.

Leider ist die Zeit bei mir momentan etwas knapp. Am Weekend gehts nach Hause! Ich werde jedoch versuchen den CSV Importer darauf basierend anzupassen. Ev. auch den Extractor. Mal sehen in was für Probleme ich dann laufe.

**Comment by buchen** [comment]
> ich werde jedoch versuchen den CSV Importer darauf basierend anzupassen.

Auf den Change zu gehen ist vielleicht noch zu früh. Der kompiliert weder noch laufen die Tests. Es war für mich eher eine Fingerübung um ein Gefühl dafür zu bekommen was es bedeuten würde.

> Ev. könnte man getAmount in Unit so implementieren dass er transparent umrechnet in die Transaktionwährung?

Das ist eine gute Frage. Unit könnte nur die Fremdwährung, also Originalwährung, speichern und die Buchungswährung wird immer errechnet. Weniger Daten, nix dupliziert. Andrerseits brauche ich den Wert für die Buchungswährung vermutlich sehr häufig. Jede der Performance-Berechnungen geht immer wieder über die Buchungen drüber. Und ich habe kein Problem mit Rundungsfehlern. Der umgerechnete Wert ist genau der, den der Benutzer im Dialog eingegeben hat. Deinen Punkt sehe ich auch. Mal überleben.


>  So wie ich das sehe kann die ExchangeRate nachtraeglich nicht mehr geaendert werden. Ist das so gewollt ?

Es wäre ja nicht der Wechselkurs an diesem Tag (der kommt ja von externen Quellen), sondern der Wechselkurs, der genau bei dieser Transaktion angefallen ist. Der sollte sich doch auch später nicht mehr - zumindest separat - ändern. Ein Edit-Dialog müsste halt alle Units löschen und neu anlegen.


> Nettobetrag könnte man ev. im Modell erst nach Bedarf berechnen und müsste man nicht im XML speichern.

Genau bei dem Punkt überlege ich auch noch. :smile: Momentan ist das ja etwas verquer - den Nettobetrag in Buchungswährung errechne ich (#getLumpSum), den Nettobetrag in Fremdwährung speichere ich in dem ForexData Objekt (das ich übrigens in dem Vorschlag oben gelöscht habe). Warum? Weil ich den vom Benutzer eingegebnen Originalbetrag behalten will. Bei den Units will ich den natürlich auch behalten. Mit dem Change oben müsste ich den aber *immer* vorberechnen, auch wenn ich gar keine Fremdwährungen habe. Also eine Frage von Konsistenz ("muss immer in Unit vorliegen") oder weniger Storage/schnellerer Zugriff/einfacheres Modell im Normall ("nur bei Buchungen mit Fremdwährungen").

**Comment by alani1** [comment]
>Auf den Change zu gehen ist vielleicht noch zu früh. Der kompiliert weder noch laufen die Tests. Es war für mich eher eine Fingerübung um ein Gefühl dafür zu bekommen was es bedeuten würde.

Ich meinte das auch eher als Fingeruebung, pressant habe ich es momentan nicht :-)

>Unit könnte nur die Fremdwährung, also Originalwährung. ... Der umgerechnete Wert ist genau der, den der Benutzer im Dialog eingegeben hat.
Der Punkt mit der Performance kann ja einfach mit caching geloest werden, d.h. Umrechnung nur beim ersten Mal. Das mit dem Dialog verstehe ich nicht ganz. Denn wenn ich eine Fremdwaehrungstransaktion habe gebe ich doch den Betrage gerade in der Fremdwaehrung ein und nicht in meiner Kontowaehrung.

>Also eine Frage von Konsistenz ("muss immer in Unit vorliegen") oder weniger Storage/schnellerer Zugriff/einfacheres Modell im Normall ("nur bei Buchungen mit Fremdwährungen").
Ich waere fuer so wenig wie moeglich Speichern  und nur was der Benutzer eingegeben hat. Wenn die Fremdwaehrung gleich Kontowaehrung ist, kann einfach ein Kurs von 1 genommen werden. Performance via caching des kalkulierten Wertes angehen.

**Comment by buchen** [comment]
@alani1 ich habe jetzt mehr oder weniger alles auf die Transaction Units umgestellt. Auch im UI kann man jetzt Gebühren sowohl in Konto- als auch in Fremdwährung erfassen.

Ich habe den CSV Import und den Interaktive Brokers Import minimal angepasst. Da überall eine Währung vorgegeben sein muss, habe ich die einfach mal auf EUR gesetzt. Das muss man natürlich korrekt auslesen. Und der Import Dialog muss checken, dass man keine EUR Buchungen auf ein USD Konto importiert - asking for trouble...
