### ISSUE TITLE
refactoring: using meaningful root package name

### ISSUE THREAD

**Issue by Marfir** [buchen/portfolio#3243]
**current root package name**
name.abuchen.portfolio

**web domain**
portfolio-performance.info

**more meaningful root package name will be**
info.portfolioperformance
or shortly: info.pp
or by convention: info.portfolio_performance

**Comment by buchen** [comment]
Let me add my reply to the conversation on [Wertpapier Forum (in German)](https://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/?do=findComment&comment=1607006):

> Ich habe einfach eine Domain verwendet, die mir gehört - noch bevor ich überhaupt wusste, dass ich PP als Projekt veröffentliche. Die Domain portfolio-performance.info habe ich erst 4 Jahre später registriert.
 
> Du hast auf jeden Fall recht - man könnte die Domain ändern. Leider ist der Name mir an einer Stelle in das XML gerutscht. Außerdem ist das package in den Preferences, d.h. zum Beispiel das Fensterlayout, die Spalten, die View-Einstellungen hängen davon ab. Und auch einige Parameter haben den Package-Namen drin, die zum Beispiel von den Linux Packages genutzt werden. Darum ist die Änderung des Package-Namen eine nicht triviale Änderungen - sicherlich machbar (es ist alles nur Software), aber das bedeutet einigen Aufwand. Und weil danach idealerweise alles wieder so funktioniert wie vorher, habe ich meine Zeit auf andere Features verwendet.

The gist: it is not a trivial change and I do not plan to spend the effort on this for the time being
