### ISSUE TITLE
refactoring: using lombok

### ISSUE THREAD

**Issue by Marfir** [buchen/portfolio#3245]
If the project use lombok then a lot of getter/setter and other boring code can be avoided.
see https://projectlombok.org/

**Comment by buchen** [comment]
I understand the benefits of lombok but I want to avoid yet another compile time dependency to some framework. Plus: wouldn't the latest Java "record" address many of the concerns? And I have no clue to add it to the target platform. I am closing this issue because I do not plan to use lombok.

**Comment by Marfir** [comment]
Yes to use the recent Java versions will be also helped. But then also somebody needs to refactor the old code. Only update the compile version did not make it better. ;-)
