### ISSUE TITLE
feature_currencies: Issues with create/edit Buy Transaction

### ISSUE THREAD

**Issue by alani1** [buchen/portfolio#325]
Das UI scheint irgendwie die 5. Nachkommastelle des Wechselkurses zu vergessen und falsch zu rechnen. Siehe Screenshot unten. Wenn ich diese Transaktion speicher und danach editiere sind nur noch vier Kommastellen da. Ebenfalls sollte Debit Note : 3,033.25 CHF sein und nicht 3,033.16 CHF.

![2015-06-21 09_40_25-createbuytransaction](https://cloud.githubusercontent.com/assets/3892818/8269888/6a1cda96-17fa-11e5-8915-7f6a5c7aead5.png)

**Comment by buchen** [comment]
> Das UI scheint irgendwie die 5. Nachkommastelle des Wechselkurses zu vergessen und falsch zu rechnen. Siehe Screenshot unten. Wenn ich diese Transaktion speicher und danach editiere sind nur noch vier Kommastellen da.

Wechselkurse werden als BigDecimal gespeichert und haben damit genug Nachkommastellen. Bei Umrechnungen des Wechselkurses (zum Beispiel um den inversen Wechselkurs zu errechnen), nutze ich 10 Nachkommastellen (z.B. [InverseExchangeRateTimeSeries](https://github.com/buchen/portfolio/blob/feature_currencies/name.abuchen.portfolio/src/name/abuchen/portfolio/money/impl/InverseExchangeRateTimeSeries.java#L52)).

Bei der Formatierung werden momentan nur 4 Nachkommastellen formatiert, siehe [Values Klasse](https://github.com/buchen/portfolio/blob/feature_currencies/name.abuchen.portfolio/src/name/abuchen/portfolio/money/Values.java#L89). Trotzdem sollte weiterhin mit der BigDecimal gerechnet werden - es sei, denn der Benutzer ändert den Wert im Feld "Wechselkurs" ganz explizit.

Das könnte man ändern. Allerdings hatte ich das Gefühl, das wird sehr unübersichtlich weil die inversen Wechselkurse dann immer 10 Nachkomastellen haben. 

![bildschirmfoto 2015-06-21 um 09 27 14](https://cloud.githubusercontent.com/assets/587976/8270845/dc28cf94-17f7-11e5-9f03-041436b452cd.png)

In dem Screenshot wird als Wechselkurs "nur" 0,8850 angezeigt, aber an dem umgerechneten Wert siehst Du, das noch mehr Nachkommastellen existieren.

> Ebenfalls sollte Debit Note : 3,033.25 CHF sein und nicht 3,033.16 CHF.

Die Rechnung stimmt aber doch, oder?
3240 * 0,93153 = 3018,1572

Wenn Du in das Feld für den Betrag "3033,25" einträgst, dann errechnet mir der Dialog einen Wechselkurs von 0,9362 (wie gesagt - Nachkommastellen nicht angezeigt)

**Comment by alani1** [comment]
Ich verstehe, d.h. man kann zwar z.b. 5 Stellen eingeben, aber danach werden nur 4 angezeigt. Ich hätte erwartet dass mir so viele Stellen angezeigt werden wie ich eingebe. Denn ich gebe Stück + Kurs + Wechselkurs ein und eigentlich nicht die Bruttowerte. Jetzt wo ich es verstehe ist das ok.

> Die Rechnung stimmt aber doch, oder?
3240 * 0,93153 = 3018,1572

Diese schon aber 3018.16 + 15.09 (manuell eingegeben) = 3,033.25 CHF und nicht 3033.16

Ok, jetzt habe ich es .... Das Problem sind die Numberformats. Ich verwende Amerikanisches Format, du Deutsches mit Komma. Bei den Feldern Quote, Fees und Taxes kann man nur Deutsches Format mit Komma eingeben. Nach dem Speichern und wieder editieren werden diese aber mit amerikanischem Format angezeigt. Btw, lustig ist auch der zweite Screenshot. Vergleich mal die Quote in der TransactionList und im Edit Window. Sollten die nicht beide 0.27 sein ? Oder ist der in der Liste in der Kontowaehrung ? Ich weiss ich bin auf einem Feature Branch.... :-)

![2015-06-21 17_49_40-buytransactionnbformat](https://cloud.githubusercontent.com/assets/3892818/8271066/f76fec60-183d-11e5-914e-40f4979fc008.png)

![2015-06-21 17_55_14-portfolio performance](https://cloud.githubusercontent.com/assets/3892818/8271088/e00fa582-183e-11e5-9e36-94600791a263.png)

**Comment by buchen** [comment]
> as Problem sind die Numberformats. Ich verwende Amerikanisches Format, du Deutsches mit Komma.

Das habe ich jetzt mal versucht hier zu beheben: 71c5d41d39f743ccb5a12b93852747ddd15ae424 Teste mal ob tut. Ich dachte immer, da ich "nur" Deutsch wirklich unterstützte, reicht es erst mal hartkodierte Dezimaltrennzeichen.

> Vergleich mal die Quote in der TransactionList und im Edit Window. Sollten die nicht beide 0.27 sein ? Oder ist der in der Liste in der Kontowährung ?

Die Liste ist in Kontowährung. Mit dem letzten Change habe ich das mal wie folgt geändert: wenn es sich um einen Betrag in der List handelt, der *nicht* der Default Währung des "Clients" entspricht, als das, was man momentan in der Vermögensaufstellung oben rechts wählt, dann wird die Währung angezeigt.

Mir fällt jetzt erst auf, dass Du auf Englisch unterwegs bist. Sehr gut. Wenn Dir etwas auffällt in Bezug auf Benennung, Formatierung, etc. - immer her damit.

**Comment by alani1** [comment]
:+1: funktioniert!

 Etwas verwirrend, habe zuerst 0,27 (also deutsches Format eingetippt) und das ergab dann folgende Rechnung : 12,000 x 0,27 = 324,000.00  --> sollte nicht einfach das tausendertrennzeichen ignoriert werden, d.h. 0,27 wuerde als 027 interpretiert?

**Comment by alani1** [comment]
btw, ich arbeite nicht nur auf Englisch sondern mit einer Koreanischen Tastatur, aber wir wollen jetzt mit der Uebersetzung von PP auf KR noch etwas zuwarten :-) Abgesehen davon sind meine Sprachkenntnisse noch nicht soweit.

**Comment by buchen** [comment]
> Etwas verwirrend, habe zuerst 0,27 (also deutsches Format eingetippt) und das ergab dann folgende Rechnung : 12,000 x 0,27 = 324,000.00 --> sollte nicht einfach das tausendertrennzeichen ignoriert werden, d.h. 0,27 würde als 027 interpretiert?

12000 x 27 ist doch 324000, oder?
Dein Tausendertrennzeichen sitzt nicht richtig, interessiert ihn aber auch nicht. Führende Nullen werden natürlich ignoriert.

**Comment by alani1** [comment]
ja, klar ist das richtig, es war wohl etwas spaet gestern....
