### ISSUE TITLE
Transaction View issues when editing transaction date/time (duplicate entries)

### ISSUE THREAD

**Issue by AlexanderLill** [buchen/portfolio#3253]
I have been having issues with the Transaction window (e.g. showing all transaction in deposit and security accounts) when editing transactions.

When I edit a transaction directly in the list of all transactions (for example the date and time), the row I edited ends up in the new location where it should be according to the sort order, but at the same time stays in the current position. This means that a row that existed before is not shown any more, and that my edited row now shows up twice. The problem is resolved once I switch to any other view (e.g. the “Account Balance Chart” graph) and back to the transaction view. This is especially annoying when editing multiple transactions at once, as some transactions will not be shown.

I have added screenshots that show the steps to reproduce, namely 1) have at least 2 transactions (in my example two different dates and a Note “first” and “second” for each of them). 2) Edit the date/time so that the order of the two transactions should change (view is set to order by date). 3) After editing the date of the second transaction, this second transaction is now shown twice, and the first transaction disappeared. 4) After switching to another view, everything is correct and both transactions are shown again.

1
![image](https://user-images.githubusercontent.com/11082297/229154292-c4cf0680-d979-4a73-8202-31c80d77ccfe.png)
2
![image](https://user-images.githubusercontent.com/11082297/229154344-153af17a-a1d6-4c36-94f8-944743672fe7.png)
3
![image](https://user-images.githubusercontent.com/11082297/229154378-d5c26828-d134-481f-b217-7427a40ad764.png)
4
![image](https://user-images.githubusercontent.com/11082297/229154444-78f8502b-deed-4923-96b7-55c7ac06d261.png)

My environment:
Version: 0.61.4 (März 2023)
Platform: macosx, x86_64
Java: 17.0.5+8-LTS, Azul Systems, Inc.

Please let me know if you need any other information!

(Original forum-post here: https://forum.portfolio-performance.info/t/transaction-view-issues-when-editing-transactions-duplicate-entries/22278/1 )

**Comment by buchen** [comment]
Thanks for the detailed error message. It allowed me to reproduce the problem easily. I still do not fully understand why it did not work before, but I applied a change that now ensures that it works.

**Comment by AlexanderLill** [comment]
Oh that was quick, thank you! :)
