### ISSUE TITLE
"TIME_SERIES_DAILY" is a "premium" Alphavantage API, stock quotes don't work by default for mere users

### ISSUE THREAD

**Issue by pfalcon** [buchen/portfolio#3275]
**Describe the bug**

Thanks for your nice application, the more strange it is to see that this issue wasn't reported already. When I add/import any securities, Alphavantage is used as the default quote feed. However, no quotes are being received, price charts are not shown, instead following error is shown in the log:

```
Unexpected header in response: {
    "Information": "Thank you for using Alpha Vantage! This is a premium endpoint. You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly unlock all premium endpoints"
}
```
(Note that the log doesn't show enough context of the error, e.g. which API URL was used to access Alpha Vantage, which is a problem in itself.)

**To Reproduce**
1. Create a new portfolio via File -> New... (I use USD as the base currency if that matters).
2. Make sure that free Alpha Vantage API KEY is set in Preferences.
3. Import some securities
4. Check that Alpha Vantage is used in Edit security -> Historical quotes
5. See error in the log

**Expected behavior**

This corresponds to https://www.alphavantage.co/documentation/#daily , where TIME_SERIES_DAILY is marked as "Premium". Instead, [TIME_SERIES_DAILY_ADJUSTED](https://www.alphavantage.co/documentation/#dailyadj) should be used, which is superset of TIME_SERIES_DAILY.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.62.0

**Comment by chirlu** [comment]
Well, a few months ago, the premium status of those two endpoints was the opposite way around: https://web.archive.org/web/20221001202632/https://www.alphavantage.co/documentation/

> the more strange it is to see that this issue wasn't reported already.

Uh, probably not many people are using Alpha Vantage. That it is first in an alphabetical list doesn’t mean it is “default” in any way.

**Comment by chirlu** [comment]
There was one report in December: https://forum.portfolio-performance.info/t/kurse-von-alpha-vantage-werden-nicht-aktualisiert/22431

**Comment by pfalcon** [comment]
> Uh, probably not many people are using Alpha Vantage. That it is first in an alphabetical list doesn’t mean it is “default” in any way.

Ah, I stand corrected. It appears to be default as set by the IBKR importer, which may give that impression that it's somehow "default" for the app...

**Comment by Morpheus1w3** [comment]
> It appears to be default as set by the IBKR importer, which may give that impression that it's somehow "default" for the app

Unfortunately this pitfall behaviour was implemented with https://github.com/buchen/portfolio/commit/b655b3f79ae10aa08debce23dac88188bb66a794, which isn't the intention at all to default a source for historical quote prices.

**Comment by buchen** [comment]
> Unfortunately this pitfall behaviour was implemented with https://github.com/buchen/portfolio/commit/b655b3f79ae10aa08debce23dac88188bb66a794, which isn't the intention at all to default a source for historical quote prices.

Thanks @Morpheus1w3 for pointing out. We should fix that. I believe the thinking was that Alphavantage is also using the symbols to identify investment vehicles.

**Comment by buchen** [comment]
> Instead, [TIME_SERIES_DAILY_ADJUSTED](https://www.alphavantage.co/documentation/#dailyadj) should be used, which is superset of TIME_SERIES_DAILY.

I have adapted the code accordingly. Thank you very much for point it.

**Comment by pfalcon** [comment]
> Thanks @Morpheus1w3 for pointing out. We should fix that. I believe the thinking was that Alphavantage is also using the symbols to identify investment vehicles.

@buchen, Thanks for changing that in https://github.com/buchen/portfolio/commit/61276578650c23ee6b70f5706dc2db33a967a0ec . Yahoo Finance is of course not ideal, but it's a well-known and free service, so using it makes good sense, to provide a common, known-largely-working baseline for everyone by default. Then interested parties can adjust it as needed from there.
