### ISSUE TITLE
PDF Import Dividendenzahlung bei Consors

### ISSUE THREAD

**Issue by sebfischer83** [buchen/portfolio#329]
Der PDF Import funktioniert nicht bei PDF von Dividendenzahlungen.

**Comment by buchen** [comment]
Könntest Du mit "File" -> "Importieren..." -> "Debug: Text aus PDF extrahieren..." mir einen Textexport zukommen lassen. In der Textdatei solltest Du Kontonummern in 12345 ändern. Aber keine Zeilen einfügen und am besten genauso vielen Stellen bei den Zahlen belassen.

Die beiden Testdateien, die ich auf diesem Wege bekommen habe, können importiert werden. Da ich aber selber nicht bei der Consorsbank bin, weiß ich natürlich nicht wann sich das Format hier und da ändert.

**Comment by sebfischer83** [comment]
Wie kann ich die Dateien am besten schicken?

**Comment by buchen** [comment]
Entweder hier pasten oder als Email portfolio.performance.help AT gmail.com

**Comment by buchen** [comment]
Danke für die Datei. Dividenden in Fremdwährung.
