### ISSUE TITLE
Flatpak crashes on Fedora 38 - Gnome 44

### ISSUE THREAD

**Issue by donvipre** [buchen/portfolio#3304]
**Describe the bug**

After updating to Fedora 38 today from 37 the flatpak from flathub doesn't open anymore.
Immediately after executing Portfolio Performance the program crashes with:
"java quit unexpectedly" report to abrt.

**To Reproduce**
1. Update from Fedora 37 to Fedora 38
2. execute Portfolio Performance flatpak
3. Crash

**Expected behavior**
Normal execution

```bash
flatpak list | grep Portfolio
Portfolio Performance   info.portfolio_performance.PortfolioPerformance 0.62.0  stable  flathub system
cat /etc/os-release 
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by chirlu** [comment]
This flatpak stuff is an external project that we don’t have much to do with. Perhaps you will find help at https://github.com/flathub/info.portfolio_performance.PortfolioPerformance/issues or https://forum.portfolio-performance.info/t/bringing-portfolio-performance-to-flathub/14433

**Comment by donvipre** [comment]
@chirlu: thank you for the hint

I have now created: https://github.com/flathub/info.portfolio_performance.PortfolioPerformance/issues/60

**Comment by l-ray** [comment]
Hi @donvipre - as you're using Fedora anyway, have a look at the Portfolio Performance-Copr at https://copr.fedorainfracloud.org/coprs/lray/PortfolioPerformance/
