### ISSUE TITLE
Steuern&Gebühren auch bei Dividenden-Erfassung

### ISSUE THREAD

**Issue by fuchsst** [buchen/portfolio#333]
analog der Erfassungsmasken für den Kauf/Verkauf, wäre es praktisch auch in der Dividenden-Erfassung die Steuern und Gebühren erfassen zu können

**Comment by buchen** [comment]
Siehe auch #219 

Ich bin da dran - allerdings in der Version mit Währungsunterstützung. Dort habe ich das Modell so erweitert, dass ich auch Steuern und Gebühren an anderen Buchungen erfassen kann. Leider wird es noch etwas dauern, bis ich eine Testversion rausgeben kann.
