### ISSUE TITLE
Stammdaten von Bank importieren

### ISSUE THREAD

**Issue by ahilmer** [buchen/portfolio#335]
Hi,

habt Ihr euch mal überlegt, die kompletten Stammdaten mit einer Bank z.B. comdirect zu synchronisieren?

Das hätte den Vorteil, dass man keine CSV oder PDF's mehr importieren muss und die Stammdaten automatisch auf den aktuellen Stand sind.

Die Banken geben zwar keine Schnittstelle heraus, aber man könnte ja einen Klickbot entwickeln der sich dort durchklickt und die Daten herunterlädt.

Nur mal so eine Idee :)

Was sagt Ihr dazu?

Viele Grüße, 
 Andi

**Comment by buchen** [comment]
> habt Ihr euch mal überlegt, die kompletten Stammdaten mit einer Bank z.B. comdirect zu synchronisieren?

Mit "Stammdaten" meinst Du die Basisdaten der Wertpapiere, oder Kurse, oder auch Umsätze?
Schreib mal was Du konkret im Sinn hast!

CSV hat den Vorteil es ist stabil und maschinenlesbar. PDF kann man leicht in Text konvertieren und ist relativ stabil. Schon die Kurse aus HTML einzulesen ist frickelig und erfordert andauernde Anpassung.

**Comment by ahilmer** [comment]
Also ich hab an sowas gedacht:

- hinterlegen der Anmeldedaten von z.B. Comdirect, DAB-Bank
- synchronisieren der Depot-Umsätze von hinterlegter Bank mit lokalem Portfolio

Das hat den Vorteil, dass das aktualisieren der Portfolios automatisch statt findet. Es ist nicht mehr notwendig die CSV,PDF Dateien zu importieren. 
Außerdem sind "echtes Portfolio" synchron mit "lokalem Portfolio".

Die Banken stellen zwar keine Schnittstelle zur Verfügung, aber ein Klickbot sollte dafür ausreichen. Mit den Anpassungen der Website müsste man rechnen, da hast Du recht.

Ich hab vor geraumer Zeit Versucht die Umsätze auszulesen und bin zu relativ guten Ergebnissen gekommen. Dabei habe ich das Framework [HtmlUnit](http://htmlunit.sourceforge.net/).

Ist aus Deiner Sich solch ein Feature denkbar?

**Comment by buchen** [comment]
Bevor ich mit web scraping anfangen würde, würde ich wohl erst mal schauen was man über HBCI erreichen kann. Da müsste man ja auch Portfolio Informationen laden können.

Aber: momentan möchte ich eigentlich im Programm keine Online Zugangsdaten wissen. Dann kommen so fragen wie: ist das korrekt encrypted? Vertraue ich einem open source Programm meine Zugangsdaten an? Könnte jemand eine Trojaner Version unter meinem Namen bauen um Zugangsdaten abzugreifen? Für alle diese Fragen gibt es Antworten, klar, aber gerade gibt es noch andere Features an denen ich knabbere (Währungen)...

**Comment by buchen** [comment]
Aktuell nicht geplant. Sorry.
