### ISSUE TITLE
Add Cboe Europe Exchange to Yahoo tickers (.XD)

### ISSUE THREAD

**Issue by maxpsq** [buchen/portfolio#3360]
I cannot find Cboe Europe Exchange among the list of symbols I can choose from after selecting Yahoo as a price data provider. As an example "Laboratorios Farmaceuticos Rovi" (ROVIE.XD).
Please add this Exchange

**Comment by Morpheus1w3** [comment]
Tough, this code is not mentioned by Yahoo at http://help.yahoo.com/kb/SLN2310.html

However, you could manually set this for the quote download while adding ROVIE.XD as symbol at the security settings.

**Comment by maxpsq** [comment]
Well, I've just noticed all tickers on .XD exchange do not provide historical data, only real time data and the last closing are provided.
