### ISSUE TITLE
FlatEx PDF-Importer bucht Verlust durch Gebühren als Guthaben

### ISSUE THREAD

**Issue by uok** [buchen/portfolio#3371]
Der FlatEx PDF-Importer in Portfolio Performance v0.62.1 speichert einen Verlust (entstanden durch Gebühren) als Guthaben!

Beispiel: 0,50 Stück zu Kurs 9,00 = Wert 4,50 abzgl. Gebühren 6,00
PDF: -1,50 
Portfolio: 1,50 (und auch der Kurs ist falsch, da hochgerechnet)

Das Problem wurde bereits mal im Forum besprochen
https://forum.portfolio-performance.info/t/verkauf-mit-negativer-gutschrift-gebuehren-hoeher-als-wert/6997

Da eine negative Gutschrift nicht möglich ist, wäre es ideal, wenn der PDF Importer für solche Fälle 2 Einträge erstellt:
1x Verkauf mit Gutschrift/Steuern aber ohne Gebühren - Notiz: `Transaktion-Nr.:  1234 (1/2)`
1x Gebühren (zugeordnet zu Wertpapier) - Notiz: `Transaktion-Nr.:  1234 (2/2)`

Danke!

**Comment by Nirus2000** [comment]
Kannst du dazu mal ein PDF-Debug erstellen?

**Comment by uok** [comment]
```
Herr Auftragsdatum      24.05.2023n
Max Muster Handelstag         25.05.2023
Musterstraße Ausführungszeit    00:00 Uhr
PLZ Musterstadt Valuta             29.05.2023
Musterland Auftragsnummer     111111111/1
Ausf.platz/-art    KAG/außerbörsl.
Wertpapierabrechnung Verkauf Fonds/Zertifikate
Ihre Depotnummer: 22222222222
Depotinhaber:     Muster, Max
Nr.111111111/1     Verkauf     AAAAA (XXXXXXXXXXXX/YYYYYY)
Ausgeführt    :        0,385884 St.     Kurswert      :               3,51 EUR
Kurs          :        9,108000 EUR     Provision     :               5,90 EUR
Devisenkurs   :        1,000000         Eigene Spesen :               0,00 EUR
                                       *Fremde Spesen :               0,00 EUR
Verwahrart    : Wertpapierrechnung
Lagerstelle   : Clearstream Lux.
Lagerland     : Musterland                  Bemessungs-
                                        grundlage     :               0,00 EUR
Gewinn/Verlust:            0,10 EUR   **Einbeh. KESt  :               0,03 EUR
                                        Endbetrag     :              -2,42 EUR
*   Enthalten sind folgende Gebühren Courtage         :               0,00 EUR
                             Tradinggebühr            :               0,00 EUR
                             Regulierung              :               0,00 EUR
                             Schlussnoten             :               0,00 EUR
                             LS-Umlegung              :               0,00 EUR
                             Finanztransaktionssteuer :               0,00 EUR
                             Sonstige                 :               0,00 EUR
**  Einbehaltene Kapitalerstragsteuer. Details dazu finden Sie im Steuerreport
    unter der Transaktion-Nr.: 3333333333.
```

**Comment by Nirus2000** [comment]
Hello @uok 
Can you create more example and provide us here? 
Maybe also with a security with currency exchange?

**Comment by uok** [comment]
Das ist das einzige PDF dieser Art in meinem Portfolio.

**Comment by Nirus2000** [comment]
Fixes with: https://github.com/buchen/portfolio/issues/3371

@buchen 
Can be closed...

**Comment by uok** [comment]
Thanks for the fix @Nirus2000, I tested this with v0.64.1 and two entries are generated.
But the number for the sale is wrong: it should be 3,48 (value 3,51 - tax 0,03) and not 2,42

**Comment by Nirus2000** [comment]
Hello @uok 
Oh damn... I forgot one line. But should work correctly now. Thx!
