### ISSUE TITLE
Separetly stored Import/Export pathes are not applied correctly by external resource (OS: Win)

### ISSUE THREAD

**Issue by OnkelDok** [buchen/portfolio#3376]
### Describe the bug
With ebc2dc615b58bf70dd29a38dc8a704f1c2749818 the pathes for import/export are stored separately for each portfolio XML file.
But unfortunately this is not working on windows. Instead of the stored import/export path of the XML, the global last used path is used (e.g. the path of the import into another portfolio XML).

### To Reproduce
1. Have two separate portfolio XMLs (XML A and XML B) and two separate directories with import files (directory A and directory B)
2. Import file from directory A into XML A and import file from directory B into XML B
3. Now the individual import pathes are stored to the files
4. Start import into XML A. You can see that the open file dialog shows the directory B instead of expected directory A

### Expected behavior
When import/export from different XML files with different import/export pathes, then the filedialog should set the initial directory to the correct one of the XML from which the import/export is startet.

### Some research

I checked the current logic But the implemented logic is correct. It seems the error is located in the ``org.eclipse.swt.widgets.FileDialog``. The issue is also reported in its github project and seems fixed with https://github.com/eclipse-platform/eclipse.platform.swt/pull/556.
@buchen: where can I see which version of the swt-package is currently used? Is it easy to switch to the newest/latest?

### Desktop (please complete the following information):
 - OS: Win10
 - Version: 0.62.1 (Mai 2023)

**Comment by buchen** [comment]
> @buchen: where can I see which version of the swt-package is currently used? Is it easy to switch to the newest/latest?

SWT is pulled in via the target platform definition, currently version 4.26 (December 2022). We could update to 4.27 (March 2023) if required

https://github.com/buchen/portfolio/blob/master/portfolio-target-definition/portfolio-target-definition.target#L5-L12

**Comment by buchen** [comment]
The bug you are linking to was resolved in February.

This is a patch to update the target platform. I wanted to apply it, but let me do this after the current bug fixes from today's release...

```
iff --git a/portfolio-target-definition/portfolio-target-definition.target b/portfolio-target-definition/portfolio-target-definition.target
index cd980760e..c1df2f5fe 100644
--- a/portfolio-target-definition/portfolio-target-definition.target
+++ b/portfolio-target-definition/portfolio-target-definition.target
@@ -2,13 +2,13 @@
 <?pde version="3.8"?>
 <target name="portfolio-target-definition" sequenceNumber="26">
 <locations>
-	<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
-		<repository location="https://download.eclipse.org/eclipse/updates/4.26/R-4.26-202211231800/"/>
-		<unit id="org.eclipse.e4.rcp.feature.group" version="4.26.0.v20221123-2302"/>
-		<unit id="org.eclipse.e4.rcp.source.feature.group" version="4.26.0.v20221123-2302"/>
-		<unit id="org.eclipse.equinox.executable" version="3.8.1900.v20221108-1024"/>
-		<unit id="org.eclipse.equinox.executable.feature.group" version="3.8.1900.v20221108-1024"/>
-		<unit id="org.eclipse.platform.feature.group" version="4.26.0.v20221123-2302"/>
+	<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
+		<repository location="https://download.eclipse.org/eclipse/updates/4.27/R-4.27-202303020300/"/>
+		<unit id="org.eclipse.e4.rcp.feature.group" version="4.27.0.v20230220-1431"/>
+		<unit id="org.eclipse.e4.rcp.source.feature.group" version="4.27.0.v20230220-1431"/>
+		<unit id="org.eclipse.equinox.executable" version="3.8.2000.v20221201-0912"/>
+		<unit id="org.eclipse.equinox.executable.feature.group" version="3.8.2000.v20221201-0912"/>
+		<unit id="org.eclipse.platform.feature.group" version="4.27.0.v20230302-0300"/>
 	</location>
 	<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
 		<repository location="https://download.eclipse.org/tools/orbit/downloads/drops/R20220302172233/repository"/>
```

**Comment by OnkelDok** [comment]
> @OnkelDok - I have update Eclipse - can you check if it is fixed?

Update to Eclipse 4.27 (March 23) (https://github.com/buchen/portfolio/commit/d902d32a47f4bff3da88dccfc4f5bcea9165d5eb) fixed the issue. Thank you.
