### ISSUE TITLE
Proxy configuration doesn't work

### ISSUE THREAD

**Issue by markokocic** [buchen/portfolio#340]
I'm running the latest version of the application on Windows.
I tried configuring proxy by updating the ini file, like explained on the FAQ section in the Wiki, but for some reason I still get connection timeouts when trying to search Yahoo Finance for adding a symbol.

I tried setting http.proxy, https.proxy and socksProxy in various combination, and nothing worked. Those same proxies work correctly when set in browser, so wrong configuration is not an issue here.

**Comment by markokocic** [comment]
To reply to myself.

After deleting the whole installation folder, and updating ini file with socksProxyHost and port settings before starting the application for the first time, I was able to connect to the internet.

**Comment by buchen** [comment]
Thanks for the update. I have another item to add a proper configuration dialog to set/use proxies #198
