### ISSUE TITLE
Security is added to watchlist of other (not active) open file when new security is added/created

### ISSUE THREAD

**Issue by OnkelDok** [buchen/portfolio#3452]
### Describe the bug
Reported here: https://forum.portfolio-performance.info/t/interferenz-zwischen-zwei-gleichzeitig-geoffneten-dateien/24516

### To Reproduce
Steps to reproduce the behaviour:
1. Have two opened files A and B, where B contains a watchlist.
2. Select watchlist in B and switch back to file A.
3. Create new security via main menu or +-Button
4. Security is added to file A (as expected)
5. **But** also in watchlist of file B the security was inserted (not expected)

### Expected behavior
Only new security in file A. 

### Desktop (please complete the following information):
 - OS: Windows
 - Version 0.64.4 (Juli 2023)

**Comment by buchen** [comment]
fixed
