### ISSUE TITLE
Kann Börsenplatz nicht auswählen

### ISSUE THREAD

**Issue by torstenzander** [buchen/portfolio#357]
![bildschirmfoto 2015-10-05 um 10 20 26](https://cloud.githubusercontent.com/assets/980484/10276682/4f6fd11c-6b51-11e5-8d64-5dc43a0be612.png)

Wie im Screenshot zu sehen kann ich den Börsenplatz nicht auswählen die SelectBox ist nicht knickbar bzw. hat keinen Inhalt,
Version ist: 0.20.0 auf MAC 10.11

**Comment by buchen** [comment]
Mann muss erst auf dem Reiter "Stammdaten" eine Ticker Symbol hinterlegen...
Das ist ein bisschen unpraktisch...

**Comment by torstenzander** [comment]
Dank dir, aber wo bekomme ich die her, gerade bei Fonds erscheint das schwer nur bei der Apple Aktie habe ich ihn gefunden.

**Comment by buchen** [comment]
Am einfachst mit ISIN bei Yahoo Finance suchen.
Die Klippe muss ich noch irgendwie entschärfen...

**Comment by torstenzander** [comment]
Yahoo Finance hat leider nicht alles, kann dort einiges auch mit der ISIN nicht finden, ist wahrscheinlich sinnvoll eine Alternative anzubieten, die eine wenig Euro lastiger ist.

**Comment by buchen** [comment]
Wenn Du als Kurslieferant "Yahoo Finance" auswählst, dann brauchst Du einen Ticker Symbol.
Und wenn Du das Ticker Symbol hast, dann kannst Du die Börsenplätze auswählen.

Alternativ kannst Du als Kurslieferant auch einen Webseite auswählen.
Dann kann man von einigen Seiten die Kurse importieren, zum Beispiel On vista oder ähnliches.
Dann braucht es eine URL und kein Ticker Symbol (und dann eben auch keine Börsenplätze).

**Comment by mammuth** [comment]
Hier bin ich ebenfalls drüber gestolpert. Ich habe PP soeben das erste mal ausprobiert und testweise Comdirect Abrechnungen importiert. Wenn bei diesen dann per Rechtsklick die Kurse konfigurieren möchte, so kommt man automatisch in den "Historische Kurse" Tab wie im Screenshot im ersten Kommentar hier.

Hier kam ich absolut nicht von selbst auf die Idee, dass ich erst in anderen Tabs Infos einfügen soll - ich nahm an, dass es sich hier um einen UI Bug handelt 🙈
