### ISSUE TITLE
Beta: Währungen

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#382]
Mit dieser (Beta) Version kann man Konten und Wertpapiere mit einer bestimmten Währung anlegen. Dazu nutze ich die historischen Wechselkurse der [European Central Bank (ECB)](https://www.ecb.europa.eu/stats/exchange/eurofxref/html/index.en.html). In der Vermögensaufstellung legt man oben rechts die Basiswährung fest. In dieser Währung werden die Auswertungen wie Vermögensaufstellung, Performance-Berechnungen oder die Grafiken berechnet. In den Buchungsdialogen kann man die Fremdwährungen erfassen - wenn das Wertpapier in einer anderen Währung als das Konto notiert ist.

Gleichzeitig habe ich das Eclipse Framework auf die aktuellste Version gehoben. Damit kann ich unter dem Mac endlich auch Retina (HiDPI) Icons anzeigen. Aus diesem Grund brauchte ich komplett neue Icons.

Dateien, die mit dieser Version gespeichert wurden, können nicht mehr von älteren Versionen des Programms geladen werden. Bitte unbedingt mit einer Kopie arbeiten!

**Feedback**

Fragen gerne einfach als Kommentar zu diesem Issue. Oder einen [neuen Issue](https://github.com/buchen/portfolio/issues/new) anlegen. Mir geht es primär um Fehler. Ich weiss nach noch einige Features fehlen. Das ist nur der erste Schritt.

**Download**

[Windows 32bit](https://s3.amazonaws.com/name.abuchen.portfolio/0.21.0.beta1/PortfolioPerformance-0.21.0.beta1-win32.win32.x86.zip) | [Windows 64bit](https://s3.amazonaws.com/name.abuchen.portfolio/0.21.0.beta1/PortfolioPerformance-0.21.0.beta1-win32.win32.x86_64.zip) | [Mac OS X](https://s3.amazonaws.com/name.abuchen.portfolio/0.21.0.beta1/PortfolioPerformance-0.21.0.beta1-macosx.cocoa.x86_64.tar.gz) | [Linux 32bit](https://s3.amazonaws.com/name.abuchen.portfolio/0.21.0.beta1/PortfolioPerformance-0.21.0.beta1-linux.gtk.x86.tar.gz) | [Linux 64bit](https://s3.amazonaws.com/name.abuchen.portfolio/0.21.0.beta1/PortfolioPerformance-0.21.0.beta1-linux.gtk.x86_64.tar.gz)

**Online Update**

Mutige können auch ihre existierende Installation mit dieser Update Site aktualisieren (Einstellungen -> Update URL): http://updates.abuchen.name/portfolio-beta

Ein Online Update der Mac OS X Version ist leider nicht möglich. Das Layout ist jetzt OS X-konform und kann leider darum nicht aktualisiert werden.

**Features**

* Währungen #14: historische Wechselkurse der ECB, Währung der Konten und Wertpapiere festlegen
* Eclipse Framework 4.5.1 (Mars) #296 Unter anderem wegen der Retina (HiDPI) Grafiken brauchte ich komplett neue Icons
* CSV/PDF Import: Käufe/Verkäufe in Einlieferungen/Auslieferungen umwandeln #275 
* CSV Import überarbeitet: Währungen #322, Notizfeld importieren #295, Wertpapiere mit Namen anlegen #350, Gegenbuchungen generieren #351
* Klassifizierungen: Kopieren #374, Zustand aufgeklappt/zugeklappt merken #376, Reihenfolge in der Seitennavigation ändern

**Comment by gsthys** [comment]
- auf den ersten Blick: Proxyeinstellungen (uebernommen aus der alten ini) funktionieren nicht mehr. Bisher war es so, dass nur die Updates nicht gingen, jetzt werden auch keine Kurse mehr aktualisiert.

[error.zip](https://github.com/buchen/portfolio/files/73939/error.zip)

**Comment by buchen** [comment]
@gsthys proxies schaue ich mir an. Danke. Die Fehlermeldungen im Log (error.zip) sind aber auch interessant. Hast Du eine existierende (alte) Version aktualisiert oder mit dem Download angefangen?

**Comment by gsthys** [comment]
Hallo Andreas,

ich hab die "Originalversion" in eine Verzeichnis "portfolio.beta"
kopiert und die Beta drueberinstalliert, dann die 
PortfolioPerformance.ini  mit den Parametern fuer den Proxy ergaenzt.
Die Datenhaltung erfolgt in 2 getrennten Verzeichnissen (zu Beginn
natuerlich identisch). Der erste Versuch ging ziemlich schief, dort
hatte ich den Parameter de_DE in der PortfolioPerformance.ini mit
uebernommen. Allerdings wurde in dem Fall auch ein Java 1.7.0_65
benutzt, hab aber keine richtige Vorstellung warum, da der Aufruf
jeweils via Kommandozeile in der gleichen Umgebung erfolgte :-(

Was mir sonst aufgefallen ist:
- lange nicht mehr aktualisierte Kurse waren bisher gelb/hellbraun
hinterlegt mit schwarzer Schrift, jetzt ist das weiss auf schwarz - eher
unangenehm
   fuer die Augen
- bisher waren die Zeilen abwechselnd weiss/grau, so dass man die Zeilen
gut unterscheiden konnte, jetzt haben alle Zeilen den gleichen weissen
Hintergrund.

Ach so, falls das mit EInfluss hat: Debian Jessie als BS.

Gruesse, Gerd


On 12/29/2015 06:41 PM, Andreas Buchen wrote:
>
> @gsthys <https://github.com/gsthys> proxies schaue ich mir an. Danke.
> Die Fehlermeldungen im Log (error.zip) sind aber auch interessant.
> Hast Du eine existierende (alte) Version aktualisiert oder mit dem
> Download angefangen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buchen/portfolio/issues/382#issuecomment-167840574>.
>


-- 
gerd
Key fingerprint = 41A1 BDC9 81E2 BFF6 AA1A  B080 A2E8 5F34 FA0A 2A7A

**Comment by buchen** [comment]
>  die Beta drueberinstalliert

Okay, das erklärt die Meldungen.

> jetzt ist das weiss auf schwarz - eher unangenehm für die Augen

Ich schaue mal was ich machen kann. Eigentlich werden die normale Vorder- und Hintergrundfarbe für Tooltips genommen. Allerdings geht unter Linux die transparenz verloren. Dadurch wird das ein ganz hartes Schwarz/weiß. Bei den Tooltips fällt mir das ebenfalls auf #386 
Die eigentlich Formatierung der Tabelle (abwechselnd weiss/grau bzw. einheitlich) sollte vom Betriebssystem vorgegeben werden.

Vielen Dank für das Feedback!

**Comment by buchen** [comment]
@gsthys Ich habe jetzt die Proxy Konfiguration explizit in die Einstellungen aufgenommen.
Wenn Du Zeit und Lust hast, probier das mal aus.
Eventuell musst Du noch mal neu installieren - das "in ein existierendes Verzeichnis auspacken" muss nicht funktionieren (wegen dem Eclipse Framework drunter).

**Comment by gsthys** [comment]
@buchen Hab grad die Linux 64bit Version neu geholt und in neues Verzeichnis installiert. Ich sehe allerdings nichts in den Einstellungen, was auf Proxy hindeutet ?

**Comment by buchen** [comment]
@gsthys Das Feature gibt es nur als Online Aktualisierung. Wenn Du die aber mangels Proxy Unterstützung nicht machen kannst, hilft Dir das nix... ich lade nachher noch mal eine neue Version hoch.

**Comment by buchen** [comment]
@gsthys hier: https://s3.amazonaws.com/name.abuchen.portfolio/0.21.0.beta1/PortfolioPerformance-0.21.0.beta3-linux.gtk.x86_64.tar.gz

**Comment by gsthys** [comment]
Sieht gut aus:
- Proxy ist ok (theoret. muesste man auch einen Proxy-User /Proxy-PW definieren koennen ;-) )
- Zeilen abwechselnd weiss/grau ist wieder da
- lange nicht aktualisierte Kurse sind wieder schwarz auf gelb
Der UpdateCheck scheint auch zu gehen, der ist der "alten" Version mit dem Proxy nicht klargekommen.
DANKE !

**Comment by buchen** [comment]
> Proxy ist ok (Theorem. muesste man auch einen Proxy-User /Proxy-PW definieren koennen ;-) )

Ich weiss. Und, wenn man es genau nehmen wollte, auch non-proxy hosts.

Ich will bloss das Passwort nicht speichern müssen. Wo. Wie encrypted, etc.
Wenn man user / password angeben muss, kann man das weiterhin per Environment variable machen.

**Comment by buchen** [comment]
veröffentlicht
