### ISSUE TITLE
DAB Bank PDF Import

### ISSUE THREAD

**Issue by mipxx** [buchen/portfolio#384]
Hallo @buchen,

der import eines ETF Verkaufs bei der DAB Bank schlägt mit folgender Meldung fehl:
![bildschirmfoto 2015-12-29 um 11 44 44](https://cloud.githubusercontent.com/assets/13769683/12033277/9b54127e-ae21-11e5-8417-2f71be2b7f04.png)

Der Debug-Textimport ist angehängt.
[dab_bank_verkauf_investmentfonds_etf_abrechnung.txt](https://github.com/buchen/portfolio/files/73871/dab_bank_verkauf_investmentfonds_etf_abrechnung.txt)

Gruß

**Comment by buchen** [comment]
Danke für das Beispiel. Ich hatte bisher kein Beispiel für einen Verkauf, darum wurden ich auch nicht unterstützt: https://github.com/buchen/portfolio/wiki/PDF%20Dokumente
