### ISSUE TITLE
Unter Linux ist die Spalte "Bestand" leer

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#385]
Siehe Screenshot - unter Linux nix zu sehen - #382 

<img width="676" alt="bildschirmfoto 2015-12-29 um 10 09 00" src="https://cloud.githubusercontent.com/assets/587976/12038879/e174d222-ae5b-11e5-922c-29e8c7d80132.png">

**Comment by buchen** [comment]
@wsteitz hast Du dieses Problem eigentlich auch bei Dir unter Linux? Keine Werte in der Spalte "Bestände"?

**Comment by wsteitz** [comment]
Kann ich bestätigen, die Spalte ist auch bei mir leer. Unter Portfolios->Umsätze das gleiche Problem bei der Spalte "Stück". Wenn ich den Wert per doppelklick editiere, sind die Werte da. komisch. 

Ansonsten ist die gesamte Darstellung bei mir etwas komisch. Zb diese grauen Kästen um die Überschrift.

![screenshot from 2015-12-29 21-39-05](https://cloud.githubusercontent.com/assets/78306/12041749/a1a56b98-ae74-11e5-94c2-f5e2ee584c45.png)

**Comment by buchen** [comment]
Das sieht ja extrem unschön aus... :disappointed: 

Komischerweise ist das auf meiner Linux Installation nicht der Fall (Ubuntu in einer VM).

Zu der Titelzeile ("Vermögensaufstellung" + Buttons):

Eigentlich setze ich die Hintergrundfarbe explizit hier:
https://github.com/buchen/portfolio/blob/feature_currencies/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/AbstractFinanceView.java#L127-L128

Es sieht fast so aus als würden die Margins nicht mit der richtige Farbe belegt:
https://github.com/buchen/portfolio/blob/feature_currencies/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/AbstractFinanceView.java#L144

Da ich das nicht reproduzieren kann: vielleicht kannst Du ein bisschen mit rumspielen? Du brauchst auf jeden Fall den Branch "feature_currencies".

**Comment by buchen** [comment]
Zu den "Anteilen":

Die werden als sogenannter OwnerDrawLabelProvider gemalt.

Wenn ich mir diesen Blog anschaue, haben noch andere das Problem. Ich habe jetzt einfach mal auf gtk_version 2 zurückgestellt. Dann sehe ich die Shares wieder. Und ich vermute auch, dass die Hintergrundfarbe wieder okay ist. SWT auf GTK3 scheint noch zu buggy zu sein. :cry: 
http://marian.schedenig.name/2015/09/16/swt-gtk-bug-affecting-grep-console/

**Comment by wsteitz** [comment]
Mit der GTK2 Version sieht es wieder hübscher aus. Die Bestände sind da, die Margins haben die richtige Farbe..

**Comment by snekker77** [comment]
Hallo Bennerich,

du hattest ja gebeten, mal die Ini-Datei zu posten. Hier ist sie:

$cat PortfolioPerformance.ini
-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417
--launcher.GTK_version
2
-vmargs
-Xms256m
-Xmx768m


An der GTK_version habe ich auch schon mal rumgespielt und diese auf 3 gestellt. Keine Verbesserung.

**Comment by snekker77** [comment]
Ich hatte mir dann nur kurz die Spalte Bestand angesehen. Da hatte ich auf jeden Fall keine weiteren Probleme festgestellt. Ich werde am WE etwas intensiver damit spielen und gebe dir Bescheid.

**Comment by snekker77** [comment]
Hatte heute doch etwas mehr Zeit und konnte mal etwas rumspielen.
Ich konnte jetzt so keine zusätzlichen Probleme feststellen, nachdem ich die Variable gesetzt habe. 
Was mir aber noch aufgefallen ist: wenn Zahlen mit mehr als 2 Stellen nach dem Komma dargestellt werden, wird die letzte Stelle fast vom Übergang zur nächsten Spalte verdeckt (siehe Bild). Evtl. kann man da auch noch was tun :-). Ansonsten sieht es dann gut aus.

![bestand_ok](https://cloud.githubusercontent.com/assets/22795407/19362532/5ae94bce-9187-11e6-949b-4c916fb714e7.jpg)
