### ISSUE TITLE
Unzureichende Fehlerbehandlung bei Umbuchung von Wertpapieren

### ISSUE THREAD

**Issue by riedinger** [buchen/portfolio#397]
Versucht man ein Wertpapier von einem Portfolio in ein anderes umzubuchen, und versäumt dabei im PopUp-Fenster das umzubuchende Wertpapier auszuwählen, erhält man die Fehlermeldung "Element can not be mapped to a null key". Bis zum Restart des Programmes ist das von der Umbuchung betroffene Portfolio nicht mehr aufrufbar.

**Comment by buchen** [comment]
Hi @riedinger,

ich versuche gerade diesen Fehler zu reproduzieren.

Wenn ich kein Wertpapier auswähle, dann darf ich den Dialog auch nicht mit "speichern" beenden:
<img width="531" alt="bildschirmfoto 2016-01-13 um 21 50 06" src="https://cloud.githubusercontent.com/assets/587976/12307474/b7476452-ba3f-11e5-963e-d80ec63ac339.png">

Auf welchem Wege kannst Du den Dialog schliessen?
Aus welcher Ansicht bist Du in den Dialog gekommen?

Irgendwo scheint da ein Fehler zu sein, aber ich brauche noch ein bisschen Info um dem auf die Spur zu kommen.

**Comment by riedinger** [comment]
Hi Andreas,

erst einmal herzlichen Dank für das tolle Programm! Zum ersten Mal habe
ich eine Ahnung davon, in wie weit meine Anlagestrategie erfolgreich ist.

Ich kann den Fehler unter Windows 8.1 gut wie folgt reproduzieren.

1. Programm starten
2. Unter dem Menüpunkt "Stammdaten" den Punkt Portfolios selektieren
3. Ein beliebiges Portfolio selektieren
4. Umbuchung aus dem Kontextmenü (rechter Mausklick) für das Portfolio
auswählen
5. Umbuchungsmaske unvollständig ausfüllen, siehe beigefügter Screenshot
6. OK klicken -> Fehlermeldung erscheint, siehe Screenshot

Das Fehlerprotokol enthält entgegen der der Aussage des Popups keinerlei
Einträge.

Sehr schön wäre übrigens ein Feature, das erlaubte, die steuerlichen
Anschaffungsdaten zu hinterlegen und die Umbuchungen nach dem FIFO
Prinzip vornehmen zu können. Damit könnte man dann tracken, ob die
Banken jeweils die richtigen steuerlichen Anschaffungsdaten übertragen,
wenn man zwischen Depots Zwecks Erhalt der Depotübertragungsprämie hin-
und herjongliert. Hierzu habe ich aber bewusst kein Ticket eingestellt,
da ich weiß, dass die Programmierung dieses Features sehr aufwendig sein
dürfte.

Beste Grüße
     Jan



Am 13.01.2016 um 21:51 schrieb Andreas Buchen:
>
> Hi @riedinger <https://github.com/riedinger>,
>
> ich versuche gerade diesen Fehler zu reproduzieren.
>
> Wenn ich kein Wertpapier auswähle, dann darf ich den Dialog auch nicht
> mit "speichern" beenden:
> bildschirmfoto 2016-01-13 um 21 50 06
> <https://cloud.githubusercontent.com/assets/587976/12307474/b7476452-ba3f-11e5-963e-d80ec63ac339.png>
>
> Auf welchem Wege kannst Du den Dialog schliessen?
> Aus welcher Ansicht bist Du in den Dialog gekommen?
>
> Irgendwo scheint da ein Fehler zu sein, aber ich brauche noch ein
> bisschen Info um dem auf die Spur zu kommen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buchen/portfolio/issues/397#issuecomment-171428742>.
>

-- 
Jan Riedinger                           Phone :  +49-30-39 73 19 66
Dipl.-Inf. | Managing Director          Fax   :  +49-30-39 73 19 64
                                        E-Mail:  riedinger@sns.eu
SNS Consult GmbH                        ICQ   :  163-237-041
Südwestkorso 49a                        MSN   :  jan@sns-consult.de
14197 Berlin GERMANY                    Skype :  Jan Riedinger

AG Charlottenburg - HRB 71973

**Comment by buchen** [comment]
> Umbuchungsmaske unvollständig ausfüllen, siehe beigefügter Screenshot

Anscheinend gehen die Attachment verloren, wenn man per Email auf eine Github Notification antwortet.
Auf der Webseite kannst Du den Screenshot per Drag & Drop in das Eingabefeld einfügen.

**Comment by riedinger** [comment]
Anbei die Screenshots
![portfolio performance fehlerhafte umbuchung](https://cloud.githubusercontent.com/assets/6261133/12322970/135660ea-bab8-11e5-843c-d8a9d754e0b9.PNG)
![portfolio performance fehlerhafte umbuchung fehlermeldung](https://cloud.githubusercontent.com/assets/6261133/12322971/135b7076-bab8-11e5-8b3b-98f186b97535.PNG)

**Comment by riedinger** [comment]
Anbei die gewünschten Screenshots
![portfolio performance fehlerhafte umbuchung](https://cloud.githubusercontent.com/assets/6261133/12323130/3c26d882-bab9-11e5-9404-b6f3e1937c23.PNG)
![portfolio performance fehlerhafte umbuchung fehlermeldung](https://cloud.githubusercontent.com/assets/6261133/12323129/3c267cac-bab9-11e5-83e4-199e5ec05b7b.PNG)

**Comment by buchen** [comment]
Hi @riedinger,

vom Screenshot her sehe ich, dass Du noch eine alte Version von dem Programm installiert hast.

Aktualisiere mal per "Hilfe" -> "Nach Aktualisierungen suchen...".

In der aktuellen Version 0.21.3 kann ich das Problem nicht mehr nachvollziehen.

Andreas.
