### ISSUE TITLE
CVS Export von Konten: Fehlendes Vorzeichen bei Beträgen 

### ISSUE THREAD

**Issue by riedinger** [buchen/portfolio#398]
M. E. wäre es sinnvoll, beim CVS von Kontendaten für die gebuchten Beträgen auch die Vorzeichen zu exportieren. Dies würde es z. B. ermöglichen mit Excel für beliebige Buchungen Zwischensummen zu berechnen.

**Comment by clashdreath** [comment]
Habe mich nun endlich mal hier angemeldet und wollte etwas contributen, indem ich mich mal an diesen Bug heranwage.. bin dann auch gleich auf die Funktion "exportAccountTransactions" unter datatransfer/csv/CSVExporter.java gestoßen. Wenn ich das richtig sehe, wird in Zeile 58 der Betrag ausgelesen und für den Export aufbereitet: "printer.print(Values.Amount.format(t.getAmount()));"
Nachdem ich mich dann ewig lange durch den Code geforstet habe, um den Fehler bzw. den Zeitpunkt des Verlierens des Vorzeichens zu finden, bin ich nun etwas ratlos, es scheint eigentlich alles ordentlich übergeben zu werden, oder habt ihr einen Plan, wo hier angesetzt werden sollte? (Währenddessen ist mir übrigens aufgefallen, dass das Problem auch bei den "exportPortfolioTransactions" vorhanden ist.)
Konnte bisher allerdings noch nicht aktiv testen, weil ich noch etwas mit dem Einrichten der Entwicklungsumgebung kämpfe ^^
Möglicherweise ist das aber auch einfach nicht der richtige Bug für den Einstieg :-D

**Comment by buchen** [comment]
Das "Problem" ist, dass PP intern alle Werte als positive Cents speichert. Je nach Buchungstyp werden die Werte dann addiert oder subtrahiert - siehe z.B. [hier](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/snapshot/AccountSnapshot.java#L26-L40). Wenn beim Export jetzt das Minuszeichen "mit exportiert" werden soll, muss das hinzugefügt werden.

Die Frage ist, wie man das am Besten macht. Vielleicht hat man ein EnumSet mit AccountTransaction.Types die negativ sein sollen und fügt entsprechend ein "-" ein. Und Ähnlich müsste man das auch für PortfolioTransactions machen.

Allerdings habe ich dieses "Problem" auch beim [Einfärben der Buchungen in der Liste](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/AccountListView.java#L589-L595) - das könnte dafür sprechen, die Information doch an die Enum selber zu hängen und von beiden Stellen aus zu nutzen.

Ich hoffe das hilft ein bisschen.

> Konnte bisher allerdings noch nicht aktiv testen, weil ich noch etwas mit dem Einrichten der Entwicklungsumgebung kämpfe 

Was ist denn das Problem? Ich nutze die aktuelle Eclipse Neon Installation + PDE (Plugin Development Environment).

**Comment by clashdreath** [comment]
Vielen Dank, mir ist die Sache jetzt etwas klarer und nachdem ich das mit der Entwicklungsumgebung hinbekommen habe, konnte ich die Issue auch recht schnell erledigen :+1: 
Habe mich zwar erst mal nur an der Sache mit den Konten versucht (da die PortfolioTransactions anscheinend nicht ganz analog dazu aufgebaut sind), aber der Teil funktioniert jedenfalls ausgezeichnet bei mir.
Allerdings fehlt mir wie es aussieht noch die Berechtigung, um etwas hochladen zu können?
(Vielleicht auch mein Fehler, habe kaum bzw. schon ewig lang keine Erfahrung mehr mit Git)

**Comment by clashdreath** [comment]
Was ich außerdem noch anmerken wollte: Wäre es code-technisch nicht viel unkomplizierter und auch rechnerisch effizienter, wenn das Vorzeichen direkt mitgespeichert wird, anstatt alle Beträge positiv abzuspeichern und dann überall erst im Nachhinein indirekt über den Typ das Vorzeichen jedes einzelnen Betrags seperat auszuforschen? Welchen Vorteil bietet die aktuelle Vorgehensweise?

**Comment by buchen** [comment]
> Allerdings fehlt mir wie es aussieht noch die Berechtigung, um etwas hochladen zu können?

Das funktioniert auf Github so: Du machst einen Fork, pusht Deine Änderungen in Deinen Fork, und machst dann einen Pull Request auf. Auf die Schnelle habe ich jetzt nur diesen Seite gefunden: https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR

> Wäre es code-technisch nicht viel unkomplizierter und auch rechnerisch effizienter, wenn das Vorzeichen direkt mitgespeichert wird, anstatt alle Beträge positiv abzuspeichern und dann überall erst im Nachhinein indirekt über den Typ das Vorzeichen jedes einzelnen Betrags seperat auszuforschen? Welchen Vorteil bietet die aktuelle Vorgehensweise?

Ich würde das mal als "so ist jetzt halt" kategorisieren. Ich sehe Dein Argument, aber wenn man das jetzt ändern wollte, muss man durch den ganze Code. Und es hängt ja auch von der Rechnung ab: eine Einlage auf dem Konto ist auf dem Konto positiv, aber in der IZF Rechnung ist die selbe Einlage negativ.

**Comment by clashdreath** [comment]
#535 Gepusht

**Comment by clashdreath** [comment]
Habe eine verbesserte Version gepusht, diesmal auch mit PortfolioTransactions, vielleicht könntest du da nochmal kurz drüberschauen ob ich da nichts wichtiges übersehen habe? So ganz den Durchblick habe ich bei den Unmengen an Code noch nicht :-D

**Comment by clashdreath** [comment]
> Ich würde das mal als "so ist jetzt halt" kategorisieren. Ich sehe Dein Argument, aber wenn man das jetzt ändern wollte, muss man durch den ganze Code. Und es hängt ja auch von der Rechnung ab: eine Einlage auf dem Konto ist auf dem Konto positiv, aber in der IZF Rechnung ist die selbe Einlage negativ.

Wenn man nun mittelfristig alle Vorzeichen-Abfragen schrittweise aktualisiert und mit `t.getType().isNegative()`durchführt, könnte der Code langfristig auch leichter so umgeschrieben werden, dass die Vorzeichen von vornherein mitgespeichert werden: isNegative() würde dann vereinheitlicht direkt alle Code-Teile markieren, welche dafür geändert werden müssen.

**Comment by buchen** [comment]
Ich hab's gerade kurz angeschaut - nur im Browser. Ich denke es sollte passen. Ich merge im allgemeinen aus der IDE heraus. Später. 😄 

Ich habe gedacht, vielleicht nennen wir es nicht "isNegative" sondern "isDebit" / "isCredit". Entweder "belastet" dieser Vorgang das Konto oder es wird was gutgeschrieben. Was hältst Du von den Namen?

Ansonsten ist mir die Formatierung noch aufgefallen. Wenn Du in Ellipse bist, sollte der Formatter eigentlich richtig gesetzt sein. Ist nicht groß schlimm, dass kann ich schnell nachziehen. Ich habe bei mir Eclipse so konfiguriert, dass immer beim Speichern der Code formatiert wird.

**Comment by riedinger** [comment]
Ich kenne den Code nicht, daher ist mein Kommentar nur mit bedingt
fundiert. In Anlehnung an die Doppelte Buchführung gefallen mir die
Begriffe Credit/Debit oder isDebit isCredit besser.


Am 14.06.2016 um 19:48 schrieb Andreas Buchen:
>
> Ich hab's gerade kurz angeschaut - nur im Browser. Ich denke es sollte
> passen. Ich merge im allgemeinen aus der IDE heraus. Später. 😄
>
> Ich habe gedacht, vielleicht nennen wir es nicht "isNegative" sondern
> "isDebit" / "isCredit". Entweder "belastet" dieser Vorgang das Konto
> oder es wird was gutgeschrieben. Was hältst Du von den Namen?
>
> Ansonsten ist mir die Formatierung noch aufgefallen. Wenn Du in
> Ellipse bist, sollte der Formatter eigentlich richtig gesetzt sein.
> Ist nicht groß schlimm, dass kann ich schnell nachziehen. Ich habe bei
> mir Eclipse so konfiguriert, dass immer beim Speichern der Code
> formatiert wird.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/buchen/portfolio/issues/398#issuecomment-225960660>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF-JjcGJ9PTAY5_XMDcYDB4fiAiV2zMJks5qLulngaJpZM4HC0iM>.
>

-- 
Jan Riedinger                           Phone :  +49-30-39 73 19 66
Dipl.-Inf. | Managing Director          Fax   :  +49-30-39 73 19 64
                                        E-Mail:  riedinger@sns.eu
SNS Consult GmbH                        ICQ   :  163-237-041
Südwestkorso 49a                        MSN   :  jan@sns-consult.de
14197 Berlin GERMANY                    Skype :  Jan Riedinger

AG Charlottenburg - HRB 71973

**Comment by clashdreath** [comment]
Passt :smile:

"isDebit" / "isCredit" klingt gut :+1: 

Werde schauen, dass die Formatierung beim nächsten Mal in Ordnung ist.

**Comment by buchen** [comment]
Bin jetzt endlich dazugekommen die Change zu mergen.

Ich habe das isNegative in isDebit/isCredit für AccountTransactions umbenannt.
Und bei PortfolioTransactions habe ich es isLiquidation/isPurchase genannt. Dabei habe ich mich von dieser [Liste von Transaction Types](https://admainnew.morningstar.com/webhelp/PAS/Accounts/Transaction_Types.htm#Sell) inspirieren lassen.
