### ISSUE TITLE
Zusätzliche Währung "GBX" (Pence Sterling)

### ISSUE THREAD

**Issue by bgo82** [buchen/portfolio#406]
An der London Stock Exchange werden die Kurse in "GBX" und nicht in GBP notiert.

Yahoo Finance liefert die Kurse dieser Aktien ebenfalls in GBX und somit sind diese im Programm um den Faktor 100 zu hoch wenn GBP als Währung ausgewählt wird.

**Comment by buchen** [comment]
Ich kann nicht einfach neue Quelle für Wechselkurse einbinden, aber ich kann GBX virtuell auf GBP Basis einbinden. Wenn ich das richtig sehen, würde das schon helfen, oder?

**Comment by bgo82** [comment]
Ja das würde helfen :)

**Comment by buchen** [comment]
Veröffentliche ich evtl. noch heute...
