### ISSUE TITLE
Sortierung Wertpapiername

### ISSUE THREAD

**Issue by mbs2016** [buchen/portfolio#407]
die Spalte Wertpapiername wird unter berücksichtigung der Groß- und Kleinschreibung sortiert ("groß sticht klein"). Zum Beispiel zeigt Portfolio Performance die folgende Reihenfolge:

ComStage Commerzbank Commodity ex-Agriculture EW
Deka STOXX® Europe Strong Value 20
RBS Market Access MSCI Frontier Markets
db X-trackers Russell 2000 (DR) 1C
iShares MSCI Emerging Markets Small Cap
iShares eb.rexx® Government Germany 1.5-2.5yr (DE)

Eine logischere Reihenfolge wäre:

ComStage Commerzbank Commodity ex-Agriculture EW
db X-trackers Russell 2000 (DR) 1C
Deka STOXX® Europe Strong Value 20
iShares eb.rexx® Government Germany 1.5-2.5yr (DE)
iShares MSCI Emerging Markets Small Cap

Vielen Dank im Voraus!

**Comment by buchen** [comment]
Veröffentliche ich evtl. noch heute...
