### ISSUE TITLE
(inaktive Wertpapiere) Kontextmenü zu Wertpapier: Name fehlt, ist auch nicht im Drop-Down enthalten

### ISSUE THREAD

**Issue by smurfer** [buchen/portfolio#429]
komischer Fehler: für zwei meiner Papiere (DE000A1W0PN8, LU0378435399) gibt es einen Fehler im Kontextmenü (Rechts-klick auf das Papier): "Wertpapier fehlt" bei der Auswahl von "Dividenden", "Steuerrückerstattung", "Aktiensplit". Das Feld "Wertpapier" bleibt leer, die beiden sind auch nicht im drop-down Menü enthalten.
Für alle anderen menu items (e.g. "Kaufen") und alle anderen Papiere wird das Feld aber richtig bevölkert (sagt man das so im Deutschen?).

Achim

**Comment by buchen** [comment]
Ist das Papier als "inaktiv" markiert?

Wenn ja, dann wäre das ein noch ein Bug.
Wenn nein, dann frage ich ob es vielleicht einen Fehler im Log gibt?

**Comment by smurfer** [comment]
wow - das nenne ich response Zeit.
Das wars. Bei dem einen hatte ich das mit Absicht auf Inaktiv gesetzt, bei dem anderen wohl versehentlich. Danke für das schnelle feedback, Feature request: die Fehlermeldung in der Dialog Box, "Wertpapier fehlt", könnte in so einem Fall angepasst werden.
Achim

**Comment by buchen** [comment]
Kommt mit dem nächsten Update.
