### ISSUE TITLE
Datumseingabe mittels Copy & Paste

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#431]
Die Eingabe des Datums ist aufwendig. Aufgrund des verwendeten DateTimePick Controls muss jeder Wert (Tag, Monat, Jahr) einzeln eingegeben werden, danach muss mit der Maus oder mit der Cursortaste der nächste Wert umständlich ausgewählt werden. 

Da ich viele Daten aus einer Tabelle eingeben möchte, vermisse ich die Möglichkeit ein Datum mittels copy & paste einfügen zu können.

**Comment by buchen** [comment]
Wie in #430 kurz beschrieben liegt das an den (nativen) SWT Widgets.
