### ISSUE TITLE
Kontostand Spalte // Kontostand anstatt Guthaben

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#437]
* ich vermisse eine Kontostand Spalte zur besseren Nachvollziehbarkeit meiner Buchungen, d.h. ich möchte zu jedem Datum gerne den kumulierten Kontostand wissen:

Zur Verdeutlichung:
Datum   |   Typ       |     Betrag     |      Kontostand
2016-01-01	Einlage	50,00 €	50,00 €
2016-01-02	Einlage	50,00 €	100,00 €
2016-01-03	Entnahme 1,00 €	99,00 €	

* "Kontostand" anstatt "Guthaben"
lt. Duden lautet die Definition für Guhaben = positiver Saldo (Buchführung).
oder "zur Verfügung stehendes, gespartes Geld [bei einer Bank]; " 
Meines Wissens nach gibt es kein Antonym für Guthaben.

Ich persönlich denke bei Guthaben nicht unbedingt an meinen Kontostand.
Man könnte den Begriff Saldo verwenden; Ich finde aber Kontostand definitiv besser bzw. treffender.

**Comment by buchen** [comment]
Nur kurz: die Benennung der Spalte macht Sinn. Den laufenden Kontostand anzeigen, allerdings etwas aufwändiger zu implementieren - auch weil Buchungen am selben Tag aktuell keine eindeutige Reihenfolge besitzen.

**Comment by megabugman** [comment]
> Den laufenden Kontostand anzeigen, allerdings etwas aufwändiger zu implementieren

ich hätte da eine andere Idee, siehe https://github.com/buchen/portfolio/issues/453

**Comment by buchen** [comment]
Oder, wie bei #453 erwähnt, ein Diagramm mit dem Verlauf des Kontostandes?

**Comment by buchen** [comment]
Implemented w/ 4e34800b7f290a0294d4037c347194b3b7ff2d7a
