### ISSUE TITLE
Crash: Zusicherung »!_button._widget« nicht erfüllt

### ISSUE THREAD

**Issue by tamueller** [buchen/portfolio#439]
After upgrading to the newest version, I cannot open or create a portfolio. When i try to load an existing one, or create a new one, it always crashes with this message:

I'm on Ubuntu 14.04.3 LTS \n \l and just installed 0.21.5

```
(Portfolio Performance:12578): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

(Portfolio Performance:12578): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

(Portfolio Performance:12578): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
PortfolioPerformance: /build/buildd/gtk2-engines-oxygen-1.4.5/src/animations/oxygencomboboxdata.cpp:87: void Oxygen::ComboBoxData::setButton(GtkWidget*): Zusicherung »!_button._widget« nicht erfüllt.

```

**Comment by tamueller** [comment]
Oh, i just found out, that when i start up, and go to Hilfe, Einstellungen, Sprache it also crashes the second I click on "Sprache" with exactly the same error message.

**Comment by buchen** [comment]
Wie alt ist Deine Linux Installation?

Es gibt im Web [dazu Meldungen](https://bugs.eclipse.org/bugs/show_bug.cgi?id=440660). Die sagen aber auch, der [KDE Bug](https://bugs.kde.org/show_bug.cgi?id=339174) sei gefixt.

Es soll helfen:
```
For oxygen, edit the normally already existing file "/usr/share/themes/oxygen-gtk/gtk-2.0/gtkrc" and change
    GtkComboBox::appears-as-list = 1
into
    GtkComboBox::appears-as-list = 0
```
