### ISSUE TITLE
Datumformat einstellen/ändern auf DD.MM.YYYY

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#441]
bei der Eingabe des Datums im Dialog einer Transaktion (zB Kaufen) 
wird das Datum im Format DD.MM.YYYY eingegeben. Danach taucht es im Format
YYYY-MM-DD in der Tabelle wieder auf. Ich vermisse die Möglichkeit das Datum in 
der Tabelle auf DD.MM.YYYY einzustellen. Hab ich etwas übersehen?

**Comment by buchen** [comment]
Das ist hartkodiert, das kann man momentan nicht ändern.

**Comment by hjbflyer** [comment]
Ich habe spasseshalber mal die Kodierung in Values.java auf dd.mm.yyyy geändert. Danach wird das Datum korrekt angezeigt. In der Buchungsliste funktioniert danach auch die Sortierung. Bei den Kurslisten stimmt sie nach nicht mehr. 
Da ich erst seit 1 Tag in den Code geschaut habe, kann ich nicht beurteilen, an wie vielen Stellen geändert werden muss. (Trennung von internem Modell und Darstellung im UI).

Ich würde mir aber auch eine Umstellung der Datumsanzeige wünschen. Wenn ich helfen kann, sehr gerne.

**Comment by buchen** [comment]
> In der Buchungsliste funktioniert danach auch die Sortierung. Bei den Kurslisten stimmt sie nach nicht mehr. 

Ich habe das Format in Values gerade testhalber auf ```String.format("%1$td.%1$tm.%1$tY", date);```. Unter "Alle Wertpapiere" -> "Historische Kurse" wird auch damit richtig sortiert. @hjbflyer Welche "Kursliste" meinst Du?

Wenn ich das Format ändere, dann direkt so, dass es Locale-dependent ist. Das kann man in Values machen. Dann sollten die Im/Exporte stabil bleiben, z.B. CSVExporter. Das in-place editing des Datums müsste in DateEditingSupport angepasst werden.

Ich denke es braucht keine Preference Page dafür - die Umstellung auf das in Deutschland übliche Datumsformat ist okay so.

**Comment by hjbflyer** [comment]
Ich hatte mich verguckt. In der Portfolioliste werden die Kurs Termine natürlich in der jeweiligen Region sortiert.

Ja, die Umstellung auf das Datumsformat der jeweiligen Lokale reicht nach meiner Meinung auch.

**Comment by buchen** [comment]
Ich habe es umgestellt auf dd.MM.yyyy umgestellt. Ich hoffe ich habe alle Stellen erwischt...
