### ISSUE TITLE
HTTP response code: 400: Wertpapier nicht gefunden

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#442]
Wertpapier hinzufügen von "Deutsche Bank" führt zu 
`Server returned HTTP response code: 400 for URL: https://s.yimg.com/aq/autoc?query=Deutsche Bank&region=DE&lang=de-DE&callback=YAHOO.util.ScriptNodeDataSource.callbacks`
Work

**Comment by flobjective** [comment]
Hallo zusammen, erstmal Danke für das tolle Programm.
Beim Serverrequest wurde der Quertext nicht escapt, somit passt dann die URL nicht.
Ich schlage mal ein Pull Request vor.

**Comment by buchen** [comment]
Fixed. Danke @flobjective!
