### ISSUE TITLE
Java was started but returned exit code= 13

### ISSUE THREAD

**Issue by Trike27** [buchen/portfolio#443]
Ich habe als neuer User Ihr Programm gestern herunter geladen, erhalte nach Entpacken und Doppel-Klick auf PortfolioPerformance.exe aber leider die folgende Fehlermeldung:

![java_error](https://cloud.githubusercontent.com/assets/15910746/13288561/c58a5838-db0c-11e5-99d6-43830b26c46f.png)

**Comment by buchen** [comment]
https://github.com/buchen/portfolio/wiki/FAQ#exit-code13

**Comment by buchen** [comment]
Du scheinst ein 32bit Java Installiert zu haben und brauchst darum auch ein 32bit PP version.

**Comment by Trike27** [comment]
Danke! Der Hinweis beim Herunterladen war einfach nicht deutlich genug ;)
