### ISSUE TITLE
toggle radio button via click on text

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#447]
normalerweise kann man mittels klick auf den Text ein Radio button togglen d.h. mit Klick auf Letzte 
![radio_button](https://cloud.githubusercontent.com/assets/17204819/13364111/58273f8c-dccd-11e5-95d1-aa3f9f3375b3.png)

**Comment by buchen** [comment]
Kann ich fixen.

Ich sehe gerade unter Windows wird da oben auch beim Eingabefeld der Rahmen abgeschnitten. Das sollte ich mir auch anschauen.

Details, Details, Details, ...

**Comment by megabugman** [comment]
> Details, Details, Details, ...

Wenn wir schon dabei sind :-) , ich denke müsste "**Von**" heissen, siehe
von ... bis / lokale + temporale Präposition:
http://longua.org/bis.temporal.php
oder hier:
http://www.knowhow.de/blog/wp-content/uploads/2013/01/taschenrechner_datum-e1359130029931.jpg

**Comment by buchen** [comment]
Mit der nächsten Version behoben
