### ISSUE TITLE
Chart ruckelt beim Aufrufen des Context Menues

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#449]
das Ruckeln irritiert etwas:
![ruckler](https://cloud.githubusercontent.com/assets/17204819/13366484/bd4ffee0-dcdb-11e5-9f94-12e3a4d2762d.gif)

**Comment by buchen** [comment]
Tritt unter Mac OS X nicht auf, kann ich aber unter Win 70 reproduzieren. Linux muss ich noch mal checken.

**Comment by buchen** [comment]
notiz: adjustRange / redraw produziert 2 Events?

**Comment by buchen** [comment]
Mit der nächsten Version behoben
