### ISSUE TITLE
Import von ING-DiBa PDF Dokumenten

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#45]
Import von Wertpapieren + Umsätzen + Gegenbuchungen

Ziel: einfacher Jump-Start

Quelle: PDF Dokumente der ING-DiBa

**Comment by mipxx** [comment]
Hallo,

gibt es zu den PDF Importen der ING-Diba schon was neues?
Habe als Beispiel mal 2 Abrechnungen und eine Ertragsgutschrift als anonymisierten Textreport angehängt.
Gruß

[ing_diba_pdf_abrechnung_order_mit_limit.txt](https://github.com/buchen/portfolio/files/38041/ing_diba_pdf_abrechnung_order_mit_limit.txt)
[ing_diba_pdf_abrechnung_order.txt](https://github.com/buchen/portfolio/files/38042/ing_diba_pdf_abrechnung_order.txt)
[ing_diba_pdf_ertragsgutschrift.txt](https://github.com/buchen/portfolio/files/38043/ing_diba_pdf_ertragsgutschrift.txt)

**Comment by buchen** [comment]
@mipxx  Danke für die Textbeispiele. Mittlerweile hat sich der Ansatz wie ich Daten aus den PDF Dokumenten extrahiere geändert. Mit den Beispiele kann ich das jetzt umsetzen.

**Comment by Beluk** [comment]
Hier nochmal zwei Abrechnung von der ING-Diba, aber diesmal für Anleihen. Einmal Flat Notiz und einmal mit Stückzinsen.

PS: Es wäre auch schön wenn man bei Anleihen die aufgelaufenen Stückzinsen im Program sehen könnte. Hast du da schon irgendwelche Pläne?

[Direkt_Depot_8000000000_Abrechnung_Kauf_XS0968913342_Order_90000000_001_00000000.txt](https://github.com/buchen/portfolio/files/39356/Direkt_Depot_8000000000_Abrechnung_Kauf_XS0968913342_Order_90000000_001_00000000.txt)
[Direkt_Depot_8000000000_Abrechnung_Kauf_XS0138973010_Order_90000000_001_00000000.txt](https://github.com/buchen/portfolio/files/39357/Direkt_Depot_8000000000_Abrechnung_Kauf_XS0138973010_Order_90000000_001_00000000.txt)

**Comment by buchen** [comment]
@Beluk Danke für die Beispiele. ING-DiBa habe ich soweit eingebaut. Allerdings habe ich den Kauf der festverzinslichen Wertpapiere noch weggelassen. Das hängt ganz davon ab wie man das im Programm abbilden - ich unterstütze es ja eigentlich gar nicht wirklich. Die Datei habe ich aber gespeichert damit ich auch in Zukunft ein Beispiel habe. Wenn es nicht tut - einfach ein neues Ticket aufmachen.

**Comment by Beluk** [comment]
Das mit den Anleihen wäre meiner Meinung gar nicht so schwer und würde dem Programm einen Mehrwert bieten. Außerdem könnte man somit auch Tages- und Festgelder abdecken. Ich kann die Tage mal etwas zusammenschreiben…

**Comment by gklimm** [comment]
Hallo in die Runde!

Keine Ahnung, ob das hilft, aber wir haben bei [https://ckonverter.de](https://ckonverter.de) bereits diverse PDF hinterlegt, bei denen wir die Daten aus den lustigen PDFs extrahieren. Unser Primärzeil dabei ist es zwar die Daten für die Buchhaltung aufzubereit, aber evtl. lassen sich die Exportdaten auch hier nutzen.
