### ISSUE TITLE
Einstandspreis anstatt Einstandswert

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#450]
unter Vermögensauftstellung, Einstandswert sollte meiner Meinung nach durch Einstandspreis ersetzt werden.

**Comment by buchen** [comment]
Einstands*preis* wäre für mein Gefühl eher der Kurs (also Einstandskurs) und nicht die Anschaffungskosten. Und das Pärchen "Einstandswert" und "Marktwert" passt für mich auch ganz gut. Ein Google Suche hat auf die Schnelle jetzt aber auch nichts entscheidendes zu Tage gefördert. Hast Du einen passenden Link?

**Comment by megabugman** [comment]
**Einstandspreis**
Der Einstandspreis eines Wertpapiers ist derjenige Betrag, der inklusive aller Nebenkosten zum Kauf einer Wertpapierposition aufgewendet wurde. English: Total purchase price 
Quelle: Deutsche Bank - Bank- & Börsenlexikon
http://www.enzyklo.de/lokal/42012&page=2

Weiterhin:
![duden](https://cloud.githubusercontent.com/assets/17204819/13411710/03c4e790-df3f-11e5-812d-960e3a28685c.PNG)

Außerdem:
![nowikipedia](https://cloud.githubusercontent.com/assets/17204819/13411767/626c2876-df3f-11e5-9c3c-f09fecd7bc13.PNG)

**Comment by buchen** [comment]
Fixed. Mit der nächsten Version.
