### ISSUE TITLE
Diagramm: Berichtszeitraum Vorlage "Gesamt"

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#452]
standardmäßig sind zZ 1-5 Jahre zur Auswahl voreingestellt. 
Mich interessiert der Zeitraum seit der der ersten Buchung bis heute. 
Der Work-around mittels "Von bis" funktioniert nur bedingt da der Endwert (Heute) nicht dynamisch ist.

**Comment by buchen** [comment]
Ist das nicht die Option "Seit X" wobei dan X die erste Buchung sein müsste?

Oder soll der Berichtszeitraum pro Wertpapiere unterschiedlich sein (in der Performance Liste)?


(Die anderen Issues schaue ich mir auch an. Ich habe die nächsten 2 Wochen wenig Zeit - ich weiß nicht zu was ich kommen werde).

**Comment by megabugman** [comment]
> Ist das nicht die Option "Seit X" wobei dan X die erste Buchung sein müsste?

genau diese Option habe ich gesucht. Manchmal sieht man den Wald...
