### ISSUE TITLE
Möglichkeit der Deaktivierung einzelner Transaktionen

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#453]
mittels Deaktivierung einzelner Transaktionen wäre es sehr einfach möglich den Kontostand zu einem bestimmten Zeitpunkt in Erfahrung zu bringen. 

Auf dieser Art und Weise könnte man "was wäre wenn Gedankenspiele" durchzuführen á la wie hoch wäre mein Kontostand wenn ich Aktie xyz nicht verkauft hätte.

Zudem würde dies helfen wenn man viele Transaktionen seines Brokers nachtragen muss um mit dem Kontostand zum Quartalsende vergleichen zu können.

siehe auch https://github.com/buchen/portfolio/issues/437

**Comment by buchen** [comment]
> mittels Deaktivierung einzelner Transaktionen wäre es sehr einfach möglich den Kontostand zu einem bestimmten Zeitpunkt in Erfahrung zu bringen.

Deaktivieren ist für mich relativ aufwändig - ich müsste an vielen Stellen jetzt prüfen ob die Buchung überhaupt gilt. Für ein "was wäre wenn" könnte man die Buchung auch einfach löschen (zumindest wenn man es mal temporär wissen will und die Datei dann nicht speichert). Darum schliesse ich diesen Issue mal.

Für den Kontostand habe ich mir auch überlegt, ob ich nicht ein Diagramm mit dem Kontostand in die Ansicht einbaue. Das ist leichter als ein separates Feld (weil die Sortierung nicht beachtet werden muss) und könnte ebenfalls helfen festzustellen wann der Kontostand auseinander gelaufen ist.

> Zudem würde dies helfen wenn man viele Transaktionen seines Brokers nachtragen muss um mit dem Kontostand zum Quartalsende vergleichen zu können.

Das Problem habe ich auch hin und wieder. Meist rechne ich die Differenz zwischen meinem Kontostand und dem Wert im Programm aus. Und suche dann nach der fehlenden Buchung mit diesem Wert. Vielleicht kann man das intelligent auch im Programm unterstützen...?!? Idee?

**Comment by megabugman** [comment]
> Das Problem habe ich auch hin und wieder. Meist rechne ich die Differenz zwischen meinem Kontostand und dem Wert im Programm aus. Und suche dann nach der fehlenden Buchung mit diesem Wert. Vielleicht kann man das intelligent auch im Programm unterstützen...?!? Idee?

De facto habe ich dieses Problem oft, da ich sehr viele Transaktionen pro Quartal (zB Fondsparpläne, Aktien An- & -Verkäufe, Umbuchungen Referenz- <-> Tagesgeldkonto) habe. Aufgrund der hohen Anzahl der Aktionen im Monat wird es schnell unübersichtlich und entsprechend aufwendig einen Fehler zu finden.

Was helfen könnte ist ein **Quickfilter** (ähnlich wie bei Outlook) damit könnte man in allen Buchungen zB nach einem bestimmtem Jahr oder Wertpapier filtern.

> Für den Kontostand habe ich mir auch überlegt, ob ich nicht ein Diagramm mit dem Kontostand in die Ansicht einbaue.

gute Idee.
