### ISSUE TITLE
NullPointerException bei neuer Kategorie in einer leeren Kategorie - Klassifizierungen

### ISSUE THREAD

**Issue by JosScha** [buchen/portfolio#459]
Hallo Andreas

Fügt man bei einer vorher leeren Kategorie einen neue Subkategorie ein, so tritt ein Nullpointer auf. Dieser Fehler tritt bei verschieden Arten der Klassifizierung gleich auf. Zwar steht bei der Fehlermeldung, dass im Fehlerprotokoll mehr steht, dort findet sich aber kein Hinweis auf den Fehler.
Der Fehler ist in Beispielportfolio Dax und Kommer nachvollziehbar.

Version 0.22.0
![kategoriefehler](https://cloud.githubusercontent.com/assets/17599939/13502192/2dec4630-e16a-11e5-84de-f5a10f899c56.PNG)

**Comment by buchen** [comment]
Danke für die Rückmeldung. Ich habe das Problem gefunden. Fix kommt mit dem nächsten Update.
