### ISSUE TITLE
minor issue: Tooltip ändert sich nach Eingabe von +11 Nachkommastellen

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#461]
beim versehentlichem Eintrag vieler Nachkommastellen ist aufgefallen:
![forinputstring](https://cloud.githubusercontent.com/assets/17204819/13539844/26da762a-e253-11e5-8b92-023e0822465d.png)

**Comment by buchen** [comment]
Fixed. Kommt mit der nächsten Version.

Aber: bei Anteilen werden so oder so nur 6 Nachkommastellen unterstützt.
