### ISSUE TITLE
Benchmark hängt 1 Tag hinterher

### ISSUE THREAD

**Issue by bartho1** [buchen/portfolio#466]
Wenn ich im Performance Diagramm mein Depot gegen einen Benchmark anzeigen lasse hört der Benchmark immer 1 Tag vor dem aktuellen Datum auf

**Comment by buchen** [comment]
Hi @bartho1 

Wenn ich die Vermögensaufstellung z.B. für einen Sonntag berechne (aktuellen Tag), dann nehme ich den aktuellsten verfügbaren Kurs, z.B. von einem Freitag.

Bei einem Benchmark mache ich das nicht, da zeichne ich die Linie nur mit den tatsächlich vorhandenen Kursen, d.h. sie geht dann nur bis Freitag (wenn man an einem Sonntag das Diagramm anschaut).

Ich kann mir also zwei Szenarien vorstellen:
Entweder die Kurse von dem Benchmark sind um einen Tag verzögert (häufig der Fall wenn man die Kurse aus einer HTML Tabelle extrahiert) oder Du schaust auf das Diagramm an einem Wochenende.

Prüfe das doch mal. Wenn es keines der beiden Szenarien ist, dann mach diesen Bug einfach wieder auf. Dann brauche ich ein paar mehr Details - oder eine Beispielsdatei.

**Comment by bartho1** [comment]
Hallo,

Danke für die schnelle Antwort! Ich glaube, dass auch unter der Woche der Benchmark einen Tag hinterherhinkt, werde es morgen nochmal überprüfen.

Ist es denn sinnvoll, dass an einem börsenfreien Tag der Depotwert weiterberechnet und im Chart weitergezeichnet wird? Wobei mich das im Chart noch weniger stört, problematischer finde ich es in der Übersicht der Performanceberechnung, wo mir z.B. heute unter "letzter Tag" nicht die Veränderung des letzten Börsentages, also Freitag, angezeigt wird sondern von heute, einem börsenfreien Tag, somit kann ich die Veränderung des letzten Handelstages nicht mehr nachvollziehen.

**Comment by buchen** [comment]
> Ist es denn sinnvoll, dass an einem börsenfreien Tag der Depotwert weiterberechnet und im Chart weitergezeichnet wird?

Das ist ein berechtigter Einwand. Ich habe bisher immer mit dem "echten" Kalender gearbeitet und dann mit LocalDate.now() für den aktuellen Tag. Und genauso kann man problemlos eine Buchung für einen Sonntag erfassen (mittlerweile kommt dann ein Warnhinweis). Zur Berechnung der Volatilität verwende ich einen "Handelskalender", d.h. Wochenenden und einige Feiertage wie Ostern, Weihnachten, Neujahr und der 1. Mai werden rausgerechnet.

Ich scheue momentan noch den Aufwand das umzustellen. Je mehr Kennzahlen sich auf den "vorherigen Tag" beziehen, desto mehr tut das weh. Die Spalten sind ja relativ neu. Bisher war das alles in Jahren oder Monaten. Ich muss mir das mal durch den Kopf gehen lassen.

**Comment by bartho1** [comment]
Hallo nochmal,

kurz nochmal zu dem "Problem", das der Benchmark im Performance-Diagramm 1 Tag hinterherhinkt. So ist es tatsächlich, wenn man z.B. im Kommer-Bsp-Depot einen Benchmark, z.B. DAX hinzufügt, wird er nur bis zum Vortag angezeigt.
