### ISSUE TITLE
Ersatzhalber Kurse aus Buchungen extrahieren (was: Charts falsch wenn kein Kurs existiert)

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#473]
zur Reproduktion ein Wertpapier DE0005403901 anlegen und kaufen am 1.2.2010 für 20 Euro.
Die Diagramme stimmen nicht.
![cewe01](https://cloud.githubusercontent.com/assets/17204819/13901436/f6c1a328-ee23-11e5-8b5b-0551f66ef69a.png)
Nach historischer Kurseingabe zum 1.1.2010 von 20 Euro, werden Charts erwartungsgemäß gezeichnet.
![cewe02chart3_besser](https://cloud.githubusercontent.com/assets/17204819/13901437/f8d4b290-ee23-11e5-9a87-183a6170d142.png)

**Comment by buchen** [comment]
Im Prinzip ist die Frage, ob man fehlende Kurse auch aus Buchungen oder dem aktuellen Kurs (#36) ersatzhalber berechnen kann.

Das aktuelle Verhalten ist unglücklich, weil der Vermögen auf Null rutscht, und dann aus nichts wieder 110 Euro entstehen...
