### ISSUE TITLE
Beim Beenden von PP werden die Jobs nicht richtig beendet

### ISSUE THREAD

**Issue by hjbflyer** [buchen/portfolio#481]
Sicher nur eine kleine Sache, aber mich machen solche Meldungen immer nervös ;-)

`
!ENTRY org.eclipse.core.jobs 2 2 Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: name.abuchen.portfolio.ui.UpdateQuotesJob
2016-03-25 12:14:26.357
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: name.abuchen.portfolio.ui.UpdateQuotesJob
`

**Comment by buchen** [comment]
Ist in der Tat unkritisch. Die Meldung sehe ich auch ab und an im Log. Bisher habe ich einfach nicht die Zeit investiert um zu schauen wie ich die abstellen kann. Das ist in der Tat nicht so schwierig. Die Meldung kann trotzdem wieder auftreten wenn der Job nicht schnell genug reagiert (weil er z.B. auf die Antwort der externen Webseite wartet).
