### ISSUE TITLE
Fehler beim Parsen eines Datum Attributes

### ISSUE THREAD

**Issue by hjbflyer** [buchen/portfolio#488]
Ich habe heute ein Datums-Attribut zu meinen Ansichten hinzugefügt. Die Eingabe wurde nur im ISO-Format akzeptiert. Die Anzeige war ebenfalls in diesem Format.

Ich habe als Änderungsvorschlag 2 Patches beigefügt.

**Comment by hjbflyer** [comment]
[patch.zip](https://github.com/buchen/portfolio/files/206358/patch.zip)

**Comment by buchen** [comment]
Bist Du auf dem aktuellen HEAD?
Mit dd4dc31b2861f02e36c6fb1eb9b3d4b4d32aa8f3 habe ich eigentlich das
Datumsformat von ISO auf ein localized medium format (also für Deutschland
dd.MM.yyyy) umgestellt.

**Comment by buchen** [comment]
Ah, verstanden, es geht um frei definierbare Attribute.
Danke. Nehme ich mit auf.

**Comment by buchen** [comment]
Danke für den Patch.

Ich habe den ```LocalDateConverter``` nicht angefasst weil der für die Konvertierung von Java -> XML verwendet wird. Und im XML soll weiterhin das ISO Format verwendet werden.

Die Idee mit den mehreren DateTimeFormatter patterns ist super! Die habe ich auch für das Editieren eines Datums in einer Spalte übernommen.

**Comment by hjbflyer** [comment]
Schade dass Du meine Änderungen am LocalDateConverter nicht übernommen hast. Als Ergebnis kann ich meine Portfolios nicht mehr öffnen, da sie jetzt lauter DateTimeParseExceptions werfen.

**Comment by buchen** [comment]
> Schade dass Du meine Änderungen am LocalDateConverter nicht übernommen hast. Als Ergebnis kann ich meine Portfolios nicht mehr öffnen, da sie jetzt lauter DateTimeParseExceptions werfen.

Ah, Du hattest Deine Datei schon einmal gespeichert. Ändert doch die #fromString Methode temporär um die Daten einmal einzulesen.

**Comment by buchen** [comment]
Im XML Format möchte ich nur das Datum nur in ISO Format stehen haben. Ansonsten würde es von der Local abhängen ob die Datei eingelesen werden kann oder nicht.

**Comment by hjbflyer** [comment]
Verstehe, ich werde fromString kurzzeitig anpassen.
