### ISSUE TITLE
Diagrammüberschrift für Kunten - Chart Title

### ISSUE THREAD

**Issue by JosScha** [buchen/portfolio#501]
Beim der neuen Funktion (Chart mit Saldenverlauf eines Kontos #453) wird eine Überschrift "Chart Title" angeführt.
Ich habe es nicht geschafft diese Überschrift zu ändern. War das so vorgesehen? Bei den anderen Diagrammen gibt es auch keine Überschrift.

**Comment by buchen** [comment]
Das ist ein Bug. Ist mir 5 Minuten nachdem ich alles veröffentlicht hatte auch aufgefallen. Bloß hatte ich keine Zeit eine komplette neue Version nachzuschieben. Kommt beim nächsten Mal mit.
