### ISSUE TITLE
Menü - Nach Aktualisierungen suchen ... - scheint nichts zu finden

### ISSUE THREAD

**Issue by JosScha** [buchen/portfolio#502]
Ich nutze die Funktion regelmäßig, weil immer am Stand sein möchte :-) Vorallem weil ihr regelmäßig interessante und hilfreiche Funktionen bereitstellt. Noch mal vielen Dank!
Normalerweise starte ich Applikation selten neu und mit dem Menüpunkt (Hilfe -> Nach Aktualisierungen suchen ...) prüfe ich auf Aktualisierungen. Ich habe das auch die letzten Tage durchgeführt. Nach dem Version 0.23 am 24-4 bereitgestellt wurde, hätte ich doch zumindest gestern eine Aktualisierung finden müssen.

Ich bin mir bei dem Thema nicht ganz sicher. Ich klicke zwar regelmäßig drauf. Aber traue niemals einen User.

**Comment by buchen** [comment]
Hi @JosScha - schau doch mal nach was in den Einstellungen als URL für die Aktualisierungen steht. Das sollte so aussehen:
<img width="637" alt="bildschirmfoto 2016-04-28 um 06 27 01" src="https://cloud.githubusercontent.com/assets/587976/14875346/3d7ec534-0d0a-11e6-8bc0-03feba2eee99.png">

Während der Beta stand da mal eine andere URL (im Januar). Aber eigentlich sollte die automatisch aktualisiert worden sein. Das könnte schief gegangen sein. Ansonsten bräuchte ich mal das Fehlerprotokoll.

**Comment by JosScha** [comment]
Hallo, der Url sollte passen, ich habe auch keine Fehler gefunden.
Ich werde das einfach weiter beobachten.
