### ISSUE TITLE
Bestand wird in der Vermögensaufstellung nicht dargestellt

### ISSUE THREAD

**Issue by fuchsst** [buchen/portfolio#504]
siehe Bild:
![unbenannt](https://cloud.githubusercontent.com/assets/8582765/14934542/76820012-0eb3-11e6-8d4f-ae64a6b71762.png)

statt dessen, wird der Bestand als Tooltip angezeigt.

**Comment by fuchsst** [comment]
das Problem tritt unter Ubuntu 16.04. auf.
Unter Windows passt die Darstellung:
![unbenannt](https://cloud.githubusercontent.com/assets/8582765/14936931/e610f182-0ef8-11e6-94e2-b314c8a781b9.png)

**Comment by buchen** [comment]
Ich habe gerade mal ein frisches Ubuntu 16.04 als VMWare image aufgesetzt. Da tut es.

<img width="723" alt="bildschirmfoto 2016-05-01 um 17 14 46" src="https://cloud.githubusercontent.com/assets/587976/14942570/bfaa3bde-0fc0-11e6-82d3-7f47165aaa76.png">

Allerdings habe ich gesehen, dass es verschiedene Bugs bei Eclipse zu GTK3 und (teilweise) auch zu "owner draw labels" gibt (die ich für diese Spalte verwende).

Das Log sagt gar nix?

Wenn Du das Log öffnest (Fehlerprotokoll -> oben rechts Datei Symbol), könntest Du mir die Start Parameter posten? Bei mir steht:
```
ava.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

**Comment by fuchsst** [comment]
```
eclipse.buildId=unknown
java.version=1.8.0_03-Ubuntu
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_AT
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

mh, der Java Build ist ein anderer (was mich wundert, hätte gedacht das ein Update auf 16.04 hier zur selben Version führt wie eine Installation from scratch) und Locale ist de_AT anstatt en_US

**Comment by buchen** [comment]
Hi @fuchsst, könntest Du mal probieren, ob folgende zwei Zeilen im PortfolioPerformance.ini helfen:
```
--launcher.GTK_version
2
```

Interessant auch dieser [Bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=492371) auf Eclipse. GTK3 Support auf Ubuntu 16.04 ist nicht gut.

**Comment by fuchsst** [comment]
die stehen da quasi schon. so schaut die komplette PortfolioPerformance.ini aus:
```
-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417
--launcher.GTK_version
2
-vmargs
-Xms256m
-Xmx768m
```

**Comment by buchen** [comment]
Mmmhhh. Mit meinem Kurzzeitgedächtnis habe ich schon wieder vergessen, dass ich genau wegen der leeren Bestandsspalte dieses Flag eingetragen habe: 13435387e6bd569acc31ff6be57b2a1bbc579dfa

Themes scheint keine Unterschied zu machen... Ich kann das Problem noch nicht nachvollziehen. 😠

**Comment by jenald55** [comment]
Hallo, bei mir tritt unter Ubuntu dasselbe Problem auf. Gibt es mittlerweile eine Lösung oder einen Workaround dazu?

**Comment by buchen** [comment]
Es gibt einen Fix mit ec8b24892c4bd1240dfd4db1b08e209320cbc506 der das Problem beheben soll (bei mir selber tritt es nicht auf, aber @andrewisplinghoff  konnte es reproduzieren und fixen). Kommt mit der nächsten Version (morgen oder nächstes Wochenende).
