### ISSUE TITLE
Portfolio nimmt falschen Kurs

### ISSUE THREAD

**Issue by Necoro** [buchen/portfolio#506]
Hallo,

meine Orderabrechnung sagt mir: 3,08642 St à 38,88 EUR, ergeben 120 EUR. Portfolio übernimmt das auch -- und reduziert den Kurs auf 38,87 EUR. Selbst wenn ich die Order-Daten ändern möchte, behauptet er weiterhin 38,87 sei der richtige Kurs und ergäbe auch 120 EUR:

![2016-05-08-121122_553x388_scrot](https://cloud.githubusercontent.com/assets/68708/15097290/0121dbac-1517-11e6-9b56-ccb30d4b7c03.png)

Änder ich das wieder manuell auf 38,88 EUR, wird weiterhin nur 38,87 EUR angezeigt. Änder ich es manuell auf ,86 und dann wieder auf ,87 bleiben die ,87 stehen mit den dann richtigen Kosten. Setze ich es (hoffnungsvoll) auf ,88 bleibt er bei ,87 aktualisiert aber die Kosten.

Muss bei Gelegenheit mal schauen, ob er auch rückwirkende Kurse ändert -- wäre unschön :(

**Comment by Necoro** [comment]
Ok, ein Blick in die XML zeigt, dass der Kurs eh nicht gespeichert wird. Insofern sollten keine rückwirkenden Daten kaputt sein. Also ist das wohl vorrangig ein Anzeigebug (und wahrscheinlich ist auch die Performanceberechnung betroffen, oder?)

**Comment by buchen** [comment]
Der Kurs wird auf jeden Fall immer errechnet, nicht gespeichert.

120 / 3,08642 ergibt 38,87999688960025 was man wohl auch auf 38,88 runden dürfte (und nicht auf 38,87 abschneiden). Das schaue ich mir an.

**Comment by buchen** [comment]
Mmmmh. Ich versuche das gerade mal nachzuvollziehen. Wenn ich im Dialog die Stückzahl eingebe und dann den Wert von 120, dann werden die 38,88 korrekt errechnet.

<img width="502" alt="bildschirmfoto 2016-05-08 um 15 39 52" src="https://cloud.githubusercontent.com/assets/587976/15098088/21cad766-1533-11e6-9129-f1efd591842f.png">

Welche Version hast Du? (Hilfe -> Über Portfolio Performance)
Und: in welcher Reihenfolge erfasst Du die Daten?

**Comment by Necoro** [comment]
Hab die Software leider gerade nicht vor mir, aber erst heute morgen geupdated gehabt, müsste also die Version 0.23.0 sein. Ich werde es morgen mal mit der gerade erschienenen 0.23.1 probieren.

Ansonsten: Angelegt habe ich den Eintrag via Sparplan -- und dabei war mir schon aufgefallen, dass der Kurs um 1ct von dem auf dem Bescheid abwich.

Was die Rundung angeht: Aus meiner Erfahrung (programmiere beruflich Bankensoftware) wird eigentlich immer kaufmännisch gerundet und nur bei wenigen Themen (Steuern u.U.) abgeschnitten/aufgerundet.

**Comment by buchen** [comment]
> Was die Rundung angeht: Aus meiner Erfahrung (programmiere beruflich Bankensoftware) wird eigentlich immer kaufmännisch gerundet und nur bei wenigen Themen (Steuern u.U.) abgeschnitten/aufgerundet.

Ich denke auch das kaufmännisch gerundet werden sollte. Ich glaube es passiert wenn man die Buchung im Edit Dialog das erste mal öffnet. Im Dialog selber wird korrekt gerundet. Ich denke das sollte relativ einfach zu beheben sein.

**Comment by Necoro** [comment]
Hallo,

habe es jetzt endlich wieder geschafft, mir das anzuschauen:

1. Es tritt auch weiterhin mit der aktuellen Version auf.
2. Ja, im Dialog berechnet er das u.U. richtig -- übernimmt es aber dann in die Umsatzliste nicht korrekt. Wenn man dann den Umsatz editiert, steht auch der falsche Wert im Umsatz.

**Comment by beilch** [comment]
Gibt es eine Möglichkeit, historische Kurse mit mehr als 2 Nachkommastellen angezeigt zu bekommen? Bei vielen italienischen Aktien hat man sonst ein Problem

**Comment by buchen** [comment]
@beilch da bin ich dran, siehe #10 - gerne auch Feedback geben, aber Achtung, das Dateiformat ändert sich und man kann dann diese Datei mit alten Versionen nicht mehr öffnen.

**Comment by buchen** [comment]
Behoben. Mit mehr Nachkommastellen bei Kursen tritt auch die falsche Rundung nicht mehr auf. Kommt mit der nächsten Version 0.24.
