### ISSUE TITLE
Spalte für laufenden Saldo

### ISSUE THREAD

**Issue by hjbflyer** [buchen/portfolio#508]
Bei den Umsätzen zu einem Konto wäre es hilfreich eine Spalte zu haben, die immer den laufenden Saldo anzeigt.Dies ist besonders hilfreich, wenn man auf der Suche nach einer Diskrepanz im Konto ist.

**Comment by buchen** [comment]
Ist in #437 auch schon angefragt. Ich machen diesen Issue mal als Duplicate zu.

Das Problem: die Reihenfolge ist nicht eindeutig wenn mehrere Buchungen am selben Tag sind. Und da man beliebige "sortierte" Sichten auf die Buchungen haben, ist der Kontostand nicht so einfach zu rechnen. Vielleicht hast Du einen Idee.

**Comment by hjbflyer** [comment]
Mein Vorschlag:

Unabhängig davon was für eine Sicht man auf eine Buchung hat, gehört für mich ein Saldo zu einer Buchung.

Deshalb würde ich alle Buchungen intern immer in eine definierte Reihenfolge bringen:
	1. nach Datum und
        2. bei Datums-Gleichheit auf- oder absteigend nach Betrag.
	3. bei Gleichheit des Betrages könnte noch ein weiteres Attribut zur Sortierung
	   herangezogen werden (notfalls eine UID)

Die Salden müssen nicht gespeichert werden, sondern müssen nach dem Einlesen der
Buchungen oder nach dem Editieren einer Buchung neu berechnet werden.

Wenn der Saldo zur Buchung gehört, ist die Sortierung für die Anzeige kein Problem mehr.
Die Sortierung nach Datum müsste für die Anzeige nur noch so angepasst werden,
dass bei Gleichheit wie oben sortiert wird. Bei Sortierung der Anzeige nach anderen Attributen,
bleibt der Saldo unverändert.

**Comment by buchen** [comment]
done. 4e34800b7f290a0294d4037c347194b3b7ff2d7a
