### ISSUE TITLE
Inkative Wertpapiere kennzeichen

### ISSUE THREAD

**Issue by Beluk** [buchen/portfolio#519]
Es wäre schön, wenn man inaktive Wertpapiere besser erkennen könnte.
Beispielimplementierung:
![inaktiv](https://cloud.githubusercontent.com/assets/10911904/15515758/fdb152a0-21ef-11e6-91b8-945dc4db3e40.jpg)

**Comment by buchen** [comment]
Nehme ich mit auf.

**Comment by buchen** [comment]
Hi @Beluk,

gute Idee - ich werde das was machen. Aktuell kann man sich die Spalte "inaktiv" einblenden lassen. Kein ganz so prominenter visueller Hinweis, aber hilft vielleicht erst mal.

<img width="324" alt="bildschirmfoto 2016-05-28 um 08 07 55" src="https://cloud.githubusercontent.com/assets/587976/15625566/4e1e3fd8-24ab-11e6-8ad6-32083da784b1.png">

**Comment by Tolzmann** [comment]
Wünschenswert wäre außerdem, wenn es einen Filter geben würde , mit dem inaktive Wertpapiere ausgeblendet werden.
Typischer Anwendungsfall: Ein ETF wird eingestellt. Kursdaten werden nicht mehr geliefert. Da sich das Wertpapier jedem einmal im Depot befand, sollte es nicht aus der Liste der Werpapiere gelöscht werden.
