### ISSUE TITLE
Frage: Buchung editieren: Kurs zeigt nur 2. Nachkommastellen ein

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#529]
wo kann ich man Nachkommastellen einstellen? die dritte Stelle wird nicht angezeigt.
![nachkommastellen](https://cloud.githubusercontent.com/assets/17204819/15837757/e34d7ed4-2c3a-11e6-89e4-55183ed35640.png)

**Comment by buchen** [comment]
Die Nachkommastellen sind erst mit #10 implementiert. Du brauchst genau diese Testversion. (Aber Achtung, das Format hat sich geändert - nur mit einer Kopie Deiner Datei arbeiten).

Ansonsten sollte das automatisch angezeigt werden, wenn der Kurs mehr Nachkommastellen hat. Checke doch mal in der Liste der historischen Kurse:
<img width="230" alt="bildschirmfoto 2016-06-07 um 07 15 55" src="https://cloud.githubusercontent.com/assets/587976/15846682/d75e8402-2c7f-11e6-870c-e34399115d97.png">
