### ISSUE TITLE
Kurs-Import wenn nicht alle Spalten in der Kurs Tabelle belegt sind

### ISSUE THREAD

**Issue by ZfT2** [buchen/portfolio#533]
Der Import von Kursen funktioniert momentan nicht, wenn nicht in allen erkannten Spalten "parse"-bare Beträge stehen:

z.B. http://www.onvista.de/fonds/snapshotHistoryPrint?idNotation=36756863&kag=true&datetimeTzStartRange=26.05.2011&timeSpan=5Y&codeResolution=1D

Ich versuche gerade, eine Lösung dafür zu schreiben.

EDIT: hab mal einen PR dazu erstellt:
https://github.com/buchen/portfolio/pull/534

**Comment by buchen** [comment]
👍 Schaue ich mir an - allerdings wird das ein paar Tage dauern...
