### ISSUE TITLE
Xetra Market Identifier Code falsch

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#543]
der MIC Code für Xetra is XETR. [https://de.wikipedia.org/wiki/Xetra](url)
PP zeigt GER an:
![xetra](https://cloud.githubusercontent.com/assets/17204819/16284698/b3617b9a-38d2-11e6-89fa-61720b35249f.PNG)

**Comment by buchen** [comment]
Die Werte in der Spalte "Börse" übernehme ich aktuell 1:1 von Yahoo Finance. Und die scheinen für Xetra den Identifier "GER" zu nehmen. Aus dem Ticker Symbol könnte ich das ebenfalls extrahieren (".DE"  = Xetra). Mal sehen.

Der Wert wird allerdings nirgendwo gespeichert - er dient eher dazu die Währung zu identifizieren. Denn leider bekomme ich von Yahoo keine Information um welche Währung es sich denn bei dem "Letzten Handel" handelt...

**Comment by stephanmunich** [comment]
Ich denke, das Problem ist gelöst und man könnte das Issue schließen. Zumindest zeigt PP bei mir die Information wie gewünscht an, wenn ich nach "daimler" suche:

![image](https://user-images.githubusercontent.com/16959462/29615261-8165ce9e-880d-11e7-8af9-12431eb8ec03.png)
