### ISSUE TITLE
Gebühren und Steuern werden bei Einlieferung in der Berechnung nicht angezeigt

### ISSUE THREAD

**Issue by Beluk** [buchen/portfolio#547]
![gebuhren](https://cloud.githubusercontent.com/assets/10911904/16355940/da426250-3ac7-11e6-850b-e01300fe08d9.png)

**Comment by buchen** [comment]
Die Rechnung stimmt ja überhaupt nicht: +880 Euro ergibt 760 Euro. Das muss ich fixen. Vielen Dank dass Du den eigentlichen Fehler schon so herausgearbeitet hast!
