### ISSUE TITLE
Interactive Brokers Importer

### ISSUE THREAD

**Issue by TommyknockerT** [buchen/portfolio#548]
Hallo, 
ich bin erst vor kurzem auf deine tolle Software gestoßen. Danke schonmal hierfür. Ich hab mich daher etwas gespielt und gesehen, dass es bereits seit 0.19 einen Importer für IB gibt. 

Leider konnte ich den mit der aktuellen Version 0.23.1 nicht zum Laufen kriegen. Also weder mein eigener Statement noch der ibstatement_test.xml in deiner Testsuite lässt sich importieren: 
Das 'Laden' des xml funktioniert ohne Fehlermeldung, jedoch wird im nachfolgenden Übersichtsfenster nichts angezeigt:

![ib_import_state](https://cloud.githubusercontent.com/assets/20150997/16361871/8962ddb0-3b9e-11e6-8262-0ebe77b35e6f.png)

Könntest du das mit dem aktuellen master testen und falls es wirklich ein Fehler ist, evtl. eine Fehlerkorrektur durchführen.

Danke

**Comment by buchen** [comment]
> Also weder mein eigener Statement noch der ibstatement_test.xml in deiner Testsuite lässt sich importieren

Mmh. Das werde ich mal testen. Die Änderung stammt nicht selbst von mir sondern die hat jemand dazu beitragen. Es kann sein, dass das mittlerweile nicht mehr tut. Es wird allerdings noch ein paar Tage dauern...

**Comment by TommyknockerT** [comment]
Ja kein Problem. Da es dazu ja einen Testcase gibt, gehe ich mal davon aus, dass der Importer funktioniert und das vielleicht es nur eine Änderung in der Darstellung gab wodurch die Daten nicht mehr angezeigt werden?

**Comment by buchen** [comment]
Der Test war auf jeden Fall mal nicht gut genug. Ich habe die NPE gefunden und gefixt. Zumindest die Testdatei kann ich jetzt importieren. Der Fix kommt mit der nächsten Version.

Wenn Deine Datei dann immer noch nicht tut, dann wäre ein anonymisiertes Beispiel XML Hilfreich.
