### ISSUE TITLE
PDF Import ING Diba

### ISSUE THREAD

**Issue by waltapeka** [buchen/portfolio#549]
Eine auf den ersten Blick sehr vielversprechende Software :) Danke dafür.

Leider wird der Großteil der PDFs der ING-DIBA noch nicht erkannt. Anbei sind die Beispiele:

[verkauf1.txt](https://github.com/buchen/portfolio/files/334939/verkauf1.txt)
[kauf3.txt](https://github.com/buchen/portfolio/files/334938/kauf3.txt)
[kauf2.txt](https://github.com/buchen/portfolio/files/334941/kauf2.txt)
[kauf1.txt](https://github.com/buchen/portfolio/files/334940/kauf1.txt)

Vielen Dank und Grüße aus Braunschweig!

**Comment by buchen** [comment]
Schaue ich mir an. Es wird allerdings etwas dauern. Habe gerade nicht viel Zeit.

**Comment by buchen** [comment]
Kommt mit der nächsten Version.

**Comment by waltapeka** [comment]
Super. Daumen hoch und Danke!
