### ISSUE TITLE
Bug SecurtityCache lookup bei Wertpapier mit nicht eindeutigem Namen

### ISSUE THREAD

**Issue by ZfT2** [buchen/portfolio#550]
Bei bestimmten Wertpapieren, z.B. Optionsscheinen ist der Name nicht immer eindeutig, z.B. gab/gibt es von der Commerzbank welche mit der Bezeichnung "COMMERZBANK CALL10 EO/DL". In der ISIN unterscheiden sie sich aber, sind daran also eindeutig zu identifizieren. Momentan guckt PP bei der Prüfung ob ein Wertpapier schon existiert, aber nur nach einem beliebigen Kriterium des Wertpapiers.
(name.abuchen.portfolio.datatransfer.SecurityCache -> Methode lookup)

Ich versuche mal, die Implementierung an dieser Stelle anzupassen... Denke es würde Sinn machen, zusätzlich die ISIN mit abzugleichen and der Stelle, sofern eine existiert. Oder spricht da was dagegen?

**Comment by buchen** [comment]
Du meinst den SecurityCache der beim PDF / CSV Import verwendet wird? Der sollte eigentlich zuerst nach ISIN, Ticker, WKN und erst dann nach Namen der Wertpapier suchen. Und wenn es zwei Wertpapiere mit identischen Namen geben sollte, dann wird ein DUPLICATE_SECURITY_MARKER gefunden und damit die Buchung keinem Wertpapier direkt zugeordnet werden.

Aber klar, wenn da ein Bug drin ist oder man das verbessern kann, immer her damit 😄

**Comment by ZfT2** [comment]
ja genau dort. Also ich habs mal schnell durchdebuggt, und er liefert mir aus dem Cache ein Wertpapier zurück, das aber nicht dem reingegebenem entspricht, aufgrund der unterschiedlichen ISIN.
Ich comitte es später, dann kannst Du es Dir mal ansehen :)

**Comment by buchen** [comment]
Fixed with #552
