### ISSUE TITLE
Keine Warnung bei inaktiven Wertpapieren

### ISSUE THREAD

**Issue by Beluk** [buchen/portfolio#559]
Wird eine Anleihe zurückbezahlt oder geht die Aktie Konkurs gibt es keine neuen Kurse mehr. Dann setzte ich dieses Papier inaktiv. Folglich sollte auch keine Warnung mehr angezeigt werden.
![2016-07-07 15_15_05-portfolio performance](https://cloud.githubusercontent.com/assets/10911904/16654346/a38655ea-4455-11e6-87eb-f0ecad5287d2.png)

**Comment by etzelc** [comment]
Man könnte auch die Hintergrundfarbe der kompletten Zeile eines inaktiven Wertpapieres leicht grau hinterlegen. Der Nutzer würde sich dann (je nach persönlicher Vorliebe) die konfigurierbare Spalte 'inaktiv' sparen.
Allerdings habe ich auf die schnelle im Code keine elegante Lösung gefunden.

**Comment by buchen** [comment]
:+1: Merged

> Man könnte auch die Hintergrundfarbe der kompletten Zeile eines inaktiven Wertpapieres leicht grau hinterlegen.

Inaktive Wertapiere kennzeichnen steht auch hier #519

Bei den Tabelle muss man etwas vorsichtig sein, weil die native Widgets je nach Platform verwenden. Unter Mac OS X werden die Zeilen z.B. abwechselnd mit weissen und hellblauen Hintergrund gezeichnet. Hier kann man auch eingreifen und die Zeile grau machen - das sieht dann aber selbstgebastelt aus.

Ich könnte mir vorstellen die inaktiven Wertpapiere mit einem grauen Icon zu versehen. Eventuell Text grau machen (aber Kontrast beachten).
