### ISSUE TITLE
Kurse werden aktualisiert obwohl inaktiv gesetzt

### ISSUE THREAD

**Issue by Beluk** [buchen/portfolio#563]
Hat man sehr viele Wertpapiere, welche momentan nicht mehr im Bestand sind, würde es Sinn machen, dass diese bei inaktiv auch nicht mehr abgefragt werden. Damit würde die Performance je nach Umfang inaktiver Wertpapiere deutlich besser werden.
Zusätzlich wäre eine Kontext-Menü praktisch:  (z.B. Rechtsklick -> Kurs für Wertpapier aktualisieren). Somit könnte man Kurse dennoch für einen eventuellen Wiedereinstieg abfragen ohne es zuerst aktiv und dann wieder inaktiv setzen zu müssen.

**Comment by buchen** [comment]
Wenn man die Kurse nicht automatisch aktualisieren möchte, kann  man das im Wertpapier hinterlegen:

<img width="426" alt="bildschirmfoto 2016-07-09 um 09 36 29" src="https://cloud.githubusercontent.com/assets/587976/16706758/a4202c2e-45b8-11e6-937e-0138f2859346.png">

Ich möchte das nicht an das "inaktiv" Flag binden (oder zumindest nicht so einfach). Ich habe z.B. den "MSCI World" als inaktiv markiert weil ich den nur als Benchmark brauche, nicht aber im Kaufen Dialog auftauchen soll. Trotzdem möchte ich für den automatisiert Kurse aktualisieren.

**Comment by Beluk** [comment]
Das ist natürlich ein gutes Gegenargument. Dann habe ich das Inaktiv falsch interpretiert. Ein Info Button mit den Auswirkungen, wenn das Flag gesetzt ist wäre eine tolle Sache.

**Comment by Beluk** [comment]
Kann es sein das die Umsetzung in #560 dann auch nicht korrekt ist, da man dann nicht auf das Flag Inaktiv gehen sollte, sondern ob eine Kurslieferant hinterlegt ist oder nicht?

**Comment by buchen** [comment]
Das habe ich mir auch gerade überlegt... 😕 @etzelc 

Ich denke
a) wir könnten eine Beschreibung in den Dialog mitzunehmen
b) und die Quote Information an QuoteFeed.MANUAL festmachen

Schaue ich mir an.

**Comment by buchen** [comment]
Ich habe einen Hilfetext hinzugefügt und die Markierung der veralteten Kurse geändert.

<img width="717" alt="bildschirmfoto 2016-07-09 um 10 46 25" src="https://cloud.githubusercontent.com/assets/587976/16707035/926129c0-45c2-11e6-8a39-8548cfaf6359.png">
