### ISSUE TITLE
Anzeigefehler des Menüpunkt "Plausibilitätsprüfung"

### ISSUE THREAD

**Issue by etzelc** [buchen/portfolio#569]
Der Menüpunkt "Plausibilitätsprüfung" wird in Windows 10 mit allen weichen Trennstrichen angezeigt.

![plausibilitaetspruefung](https://cloud.githubusercontent.com/assets/20241180/16735047/e6e34872-4787-11e6-8a47-b1d4c4656cf9.png)

**Comment by buchen** [comment]
Das tritt unter Windows 10 auf... ich bin vor ein paar Wochen nicht drauf gekommen, warum nur da und nicht wo anders. [Jetzt sehe ich es](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.bootstrap/OSGI-INF/l10n/bundle_de.properties#L10):
```
Plau\u00ADsi\u00ADbi\u00ADli\u00ADt\u00E4ts\u00ADpr\u00FC\u00ADfung...
```

Im Resource Bundle Editor sieht das gut aus - im Code sehe ich die Sonderzeichen. Vermutlich habe ich es aus dem Duden oder so kopiert. Arrrgh.
