### ISSUE TITLE
Performance / Absolute Veränderung seit Update auf 0.24.0 nicht mehr korrekt

### ISSUE THREAD

**Issue by markusb68** [buchen/portfolio#570]
Der Wert "Performance / Absolute Veränderung" ist seit dem Update auf 0.24.0 nicht mehr korrekt.
Er ist mehr als doppelt so hoch. Ich vergleiche es mit meinem Online Portfolio auf de.finance.yahoo.com.
Hier steht zur Zeit: 
Veränderung (heute) Up 1.247,18 Up 1,50%
und im Portfolio Performance steht 3216,88

**Comment by Beluk** [comment]
Bei mir ist das auch so, dass PP einen mehr als doppelt so hohen Wert seit dieser Version anzeigt.

**Comment by buchen** [comment]
Bezieht sich das auf das Dashboard und "Letzter Tag"?

Da ist ein Fehler in der Zeitberechnung. Es werden immer zwei Tage (bzw. ein Tag zu viel genommen). Wenn man sich den Tooltip von der Überschrift anzeigen lässt, solltet Ihr den genauen Zeitraum sehen.

Der Fehler ist wohl im Berichtszeitraum "Handelstage". Wenn Ihr das auf "Tage" wieder ändert ist es wie vorher.

**Comment by Beluk** [comment]
Das mit zwei Handelstagen dürfte von den Werten sehr gut hingehen. Bei mir wird aber nur ein Handelstag angezeigt.

![2016-07-12 20_51_34-portfolio performance](https://cloud.githubusercontent.com/assets/10911904/16779479/b82ba074-4872-11e6-843e-eaa7811f792b.png)
![2016-07-12 20_52_13-portfolio performance](https://cloud.githubusercontent.com/assets/10911904/16779480/b82e2ba0-4872-11e6-980d-36a7bc816382.png)

Was bedeutet eigentlich Handelstag? Bzw. wie weiß das Programm wann ein Handelstag ist oder nicht? Hängt das davon ab ob ein Kurs vorhanden ist oder nicht?
Meine ETFs zum Beispiel sind über Tradegate auch Samstag und Sonntag handelbar, meine Anleihen dagegen nicht.

**Comment by buchen** [comment]
Mach mal den Tooltip auf dem "True-Time Weighted Rate of Return" Überschrift.

Aber ich denke das ist das Problem. Habe ich schon gefixt. Wenn ich eine Version raushaue, dann vermutlich nur als Online Aktualisierung.

**Comment by Beluk** [comment]
PS: Wenn ich einen Tag auswähle scheint es wieder zu passen :-)

![2016-07-12 20_57_12-portfolio performance](https://cloud.githubusercontent.com/assets/10911904/16779623/5f678e3e-4873-11e6-8040-b3fac03217a6.png)

**Comment by Beluk** [comment]
Hier verstecken sich die zwei Tage...

![2016-07-12 21_01_34-portfolio performance](https://cloud.githubusercontent.com/assets/10911904/16779765/e48b1f7c-4873-11e6-9d47-51ed0739319e.png)

**Comment by buchen** [comment]
okay, das Problem habe ich behoben. Ich schiebe eine Bugfix version nach.
