### ISSUE TITLE
Anzahl der Operationen stimmen nicht falls Wertpapiere keinen Kurslieferant haben.

### ISSUE THREAD

**Issue by Beluk** [buchen/portfolio#575]
![2016-07-14 17_59_24-program manager](https://cloud.githubusercontent.com/assets/10911904/16846458/dd9836ee-49ec-11e6-8229-c572cd9cbf46.png)

PS: Habe Deutsch eingestellt wird aber in Englisch angezeigt.

**Comment by buchen** [comment]
Die Übersetzung habe ich noch nicht hinbekommen (ich habe nicht gefunden wo das Framework das Label setzt). Ich hoffe mit der nächsten Eclipse Version ist das übersetzt.

Und die Anzahl der Operationen meist nicht mit dem Wertpapieren zusammen. Das liegt daran, dass ich nicht für jedes Wertpapier genau eine Operation anlege sondern z.B. Yahoo zusammenfassen kann.

Eigentlich dachte ich, dass ist nicht so schlimm. Aber sehr aufmerksamen Benutzern fällt das auf 😄 

Ich habe gerade mal kurz drüber geschaut - keine Ahnung wie ich das ändern könnte (und ob es überhaupt geht). Ehrlich gesagt ist mir aktuell nicht Wert da viel Zeit reinzustecken. Ich belasse es jetzt mal so - vielleicht geht ja mehr wenn ich auf Neon aktualisieren #522 .

**Comment by Beluk** [comment]
Kein Ding, ich find das auch überhaupt nicht schlimm. Ich war nur das erste Mal irritiert, da ich von 30 bis 15 schön zu schauen konnte und auf einmal dann fertig war. Dachte zuerst das irgendwelche Seiten nicht geparst werden konnten aber das Fehlerprotokoll war in Ordnung.
