### ISSUE TITLE
Problem Tausendertrennzeichen für historische Kurse in 0.24.0/0.24.1

### ISSUE THREAD

**Issue by msitms** [buchen/portfolio#577]
Seit 0.24.0 (keine Veränderung mit 0.24.1) werden bei mir die historischen Kurse um den Faktor 100 zu niedrig eingelesen, die aktuellen Kurse jedoch nicht. Kurslieferant für alles ist bei mir Yahoo. Auf dem Screenshot sieht man das Problem ganz gut:

![image](https://cloud.githubusercontent.com/assets/635950/16893597/1bf5b5aa-4b3d-11e6-883c-d492fa8de9b5.png)

Dadurch werden natürlich auch sämtliche Performance-Berechnungen und Charts komplett umbrauchbar. Vor ein paar Tagen fällt quasi alles auf 0, um dann, unter Verwendung des jeweils aktuellen Kurses, der richtig geparst wird, eine "Performance letzter Tag" von +10000% hinzulegen...

Ich habe die historischen Kurse der betroffenen Tage auch schon versucht zu löschen und neu zu laden, das hilft aber nicht. Es wird dann die Historie interessanterweise noch jeweils ein Tag weiter zurück "versaut" als vorher.

OS: Win10 x64
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

Ich nutze die 32-Bit-Version des Programms.

**Comment by msitms** [comment]
Ach ja, Sprach- und Uhrzeiteinstellungen des OS sind alle deutsch, obwohl das OS evtl. ursprünglich mal englisch installiert wurde, sollte aber keine Rolle spielen.

**Comment by buchen** [comment]
Ist das eine Aktualisierung der Kurse per HTML Seite, oder Yahoo?
Welche URL / welches Ticker Symbole genau?

**Comment by msitms** [comment]
Danke für die schnelle Reaktion!
Als Lieferant ist für historisch wie aktuell eingestellt: "Yahoo Finance (Adjusted Close)"
Betroffene Ticker: EXSA.DE, C007.DE, UIMI.DE, LYYA.DE

Wenn ich es über einen Proxy schicke, wird für die **aktuellen Kurse** zuerst folgende URL abgerufen:
http://finance.yahoo.com/d/quotes.csv?s=C007.DE+EXSA.DE+LYYA.DE+UIMI.DE&f=sl1d1hgpv

Da gibt es dann einen 301 auf http://download.finance.yahoo.com/d/quotes.csv?s=C007.DE+EXSA.DE+LYYA.DE+UIMI.DE&f=sl1d1hgpv

Da kommt dann mit `Content-Type: application/octet-stream` zurück:
```
"C007.DE",20.30,"7/15/2016",20.34,20.13,20.31,9310
"EXSA.DE",34.11,"7/15/2016",34.19,33.92,34.19,496380
"LYYA.DE",152.24,"7/15/2016",152.35,150.96,151.95,7680
"UIMI.DE",78.20,"7/15/2016",78.20,77.79,78.18,1411
```

Abruf der **historischen** Kurse sieht offenbar so aus (hier nur ein einzelnes Instrument):

http://ichart.finance.yahoo.com/table.csv?ignore=.csv&s=EXSA.DE&a=6&b=15&c=2016&d=6&e=16&f=2016&g=d

Content-Type: text/csv

```
Date,Open,High,Low,Close,Volume,Adj Close
2016-07-15,34.02,34.19,33.92,34.11,496300,34.11
```

Sieht also von den Quellen her erst mal alles normal und konsistent aus.

**Comment by buchen** [comment]
Fixed.

Das war ein Bug der durch die 2 weiteren Nachkommastellen bei Kursen reingerutscht ist. Ich denke ich werde im Laufe des Tages eine kleine Hoffix Version veröffentlichen.
