### ISSUE TITLE
Application crashes instantly on Mac Os X 10.11.5

### ISSUE THREAD

**Issue by heilbad** [buchen/portfolio#580]
When I open PortfolioPerformance, the application crashes instantly. Mac Os shows me the crash dialog and asks whether to send a report to Apple.

I installed the current Oracle JDK (java -version gives " java version "1.8.0_92" Java(TM) SE Runtime Environment (build 1.8.0_92-b14) Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode). ").

Here is a part of the report:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000003c
Exception Note:        EXC_CORPSE_NOTIFY

How can I fix this? Or is it a general Mac Os Problem?

**Comment by buchen** [comment]
I run on the same OS version, but a little older JDK. So I do not think it is a general problem.

```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

Searching for the issue, it shows [this](http://stackoverflow.com/questions/24096281/eclipse-crashes-on-launch) and [this](http://stackoverflow.com/questions/12360304/problems-running-eclipse-juno-64-bit-on-mac-lion) and [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=390071).

Not sure what to make out of it. It seems to indicate that the installation is corrupt (?) or incomplete (?) and that one native call goes into the void.

Maybe try another archiving program?

One comment was:
> found the problem... I used Unarchiver to unpack the pack... It seems to have a bug... When I used another program to unpack it it worked :-)

**Comment by heilbad** [comment]
Thanks a lot for the hint to Unarchiver. That was the issue.
