### ISSUE TITLE
Wertpapier nicht gefunden

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#590]
liegt vermutlich am Leerzeichen:
![national_bank_of_canada](https://cloud.githubusercontent.com/assets/17204819/17194567/eb962fdc-5458-11e6-8063-bf278d2669bd.png)

das Wertpapier existiert:
![national_bank_of_canada2](https://cloud.githubusercontent.com/assets/17204819/17194585/04b8d438-5459-11e6-8929-838d0c97b0c6.png)

**Comment by flobjective** [comment]
Ja, genau daran liegts. Gleicher Fehler wie #442 .

**Comment by buchen** [comment]
fixed
