### ISSUE TITLE
Inkorrekte Meldung bei Falscheingabe Passwort

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#591]
Mit 128 Bit verschlüsseln, beim Öffnen falsches PW eingeben.
Es kommt die Meldung: "Diese Datei wurde mit einer neueren Version von PP erstellt. (Datei Format Version 1.170.817.497) anstatt "falsches PW eingegeben".

**Comment by megabugman** [comment]
nach weiteren falscheingaben variert die angebliche datei format version. dann kommt mal die Meldung XML kann nicht geparst werden: : input contained no data

**Comment by buchen** [comment]
Wenn PP die Datei entschlüsselt, bekommt ich keine Rückmeldung ob das erfolgreich war. Ich laufe dann weiter und in den nächstbesten Fehler rein - meist ist die Versionsnummer verdammt hoch... Die Fehlermeldung kann ich aber besser machen.
