### ISSUE TITLE
Alle Speichern Menueintrag nicht ausgegraut

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#592]
Menu Datei\Alle Speichern bzw. Speichern unter ist nicht ausgegraut, z.B. wenn beim Öffnen ein falsches PW eingegeben wurde.
Dies macht wenig Sinn denn die Datei sollte erst speicherbar sein nachdem sie entschlüsselt wurde.
Die Menueinträge sind zudem verfügbar auch wenn keine Datei offen ist.

**Comment by buchen** [comment]
Die "Speichern" Einträge sind bei mir nur aktiv wenn die Datei tatsächlich entschlüsselt ist.

Der Menüeintrag "Speichern" ist ein Submenü. Die kann ich nicht einzeln aktivieren oder reaktiveren. Ich könnte es verstecken. Allerdings würde das Menü manchmal "Speichern" enthalten und manchmal nicht. Ich denke das belasse ich jetzt mal so.

<img width="576" alt="bildschirmfoto 2016-11-06 um 08 52 51" src="https://cloud.githubusercontent.com/assets/587976/20036124/6e4110ec-a3fe-11e6-9458-594b691827f4.png">

"Alle Speichern" ist jetzt nur noch aktiv wenn es Dateien gibt, die gespeichert werden müssten.
