### ISSUE TITLE
PP Korruption

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#593]
in v. 0.24.2 alle tabs schließen dann programm zumachen und restarten.
danach tauchen die tabs nicht wieder auf, selbst nachdem eine neue datei erstellt wurde.
ich hoffe das problem ist reproduzierbar.

update: über Hilfe Willkomen wählen dann tauchen alle tabs wieder auf

**Comment by buchen** [comment]
Danke - insbesondere der Hinweis mit dem "Willkommen" Tab war hilfreich!
