### ISSUE TITLE
Enhancement Lokalisierung: Benutzte Dokumente

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#595]
Benutzte Dokumente hört sich imo etwas komisch an. 
Unter Windows wird standardmäßig "Zuletzt verwendet" genommen:
![zuletzt](https://cloud.githubusercontent.com/assets/17204819/17340075/fc0f836e-58ee-11e6-9c0d-768443a452f7.png)

**Comment by buchen** [comment]
Stimmt, das klingt besser. Habe ich angepasst.
