### ISSUE TITLE
Sortierreihenfolge in Vermögensaufstellung nicht gespeichert

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#596]
nach Hinzufügen eines neunen Wertpapiers fiel mir auf dass unter Vermögensaufstellung
die Sortierung nicht gespeichert wird. in meinem Fall landet mal der Eintrag Verrechnungkonto mal an dritter mal an vierte Stelle. Zum Reproduzieren mal nach Bestand mal nach Name sortieren, Programm zumachen und wieder starten. die Sortierung wird nicht gespeichert. 
Dieser Umstand ist ziemlich verwirrend. Evtl. sollte immer alphabetisch sortiert werden?
-> evtl. betrifft das auch andere Programmbereiche.

**Comment by buchen** [comment]
Tricky... Danke.

Die Sortierreihenfolge wird gespeichert, aber erst wenn man die Ansicht wechselt bevor man die Datei schliesst. Also z.B. Sortierreihenfolge ändern, dann Diagramm anzeigen lassen, dann speichern.

D.h. Ich speichere die Konfiguration erst wenn die Ansicht geschlossen wird. Ich muss schauen wie ich da an den richtigen Event rankomme.
