### ISSUE TITLE
Neue Währungen hinzufügen bzw mit bestehenden über Formel verlinken

### ISSUE THREAD

**Issue by jphdxb** [buchen/portfolio#599]
Die Default Währungen werden ja von der EZB gezogen. Leider fehlt dort die Währung AED. Es wäre prima wenn man diese manuell in PP hinzufügen könnte, und durch eine Formel zum USD intern verlinken könnte (USD = AED/3,673). Dadurch bräuchte man auch keinen externen data feed. Noch besser wäre es, wenn man irgendwann neue Währungen von anderen Quellen als der EYB hinzügen könnte. 

Referenz
http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__1042363

**Comment by buchen** [comment]
Laut [Wikipedia](https://en.wikipedia.org/wiki/United_Arab_Emirates_dirham) ist AED seit November 1997 an den USD gebunden:

> On January 28, 1978, the dirham was officially pegged to the IMF's special drawing rights (SDRs). In practice, it is pegged to the U.S. dollar for most of the time. Since November 1997, the dirham has been pegged to the 1 U.S. dollar = 3.6725 dirhams, which translates to approximately 1 dirham = 0.272294 dollar.

Es wäre recht aufwändig in PP die generische Eingabe einer Formel zu programmieren. Ich könnte mit relativ wenig Aufwand das für AED direkt machen. Für die Umrechnung von "British Penne" in "British Pound" habe ich das schon gemacht. Bei Pfund und Penne wird sich das nie ändern (immer 1:100), aber eine Bindung zum Dollar muss nicht auf Dauer sein (Argentinien...).

Die beste Möglichkeit wäre auch Wechselkurse von Yahoo Finance zu erlauben. Das habe ich erst mal hinten angestellt, weil ich mit der EZB gut historische Kurse bekomme. Ich schaue mir mal an was das technisch bedeuten würde.

**Comment by jphdxb** [comment]
Ein schneller Fix würde mir schon langen! Den USD peg gibts ja schon lange und wird auch nicht so schnell abgeschafft, wenn du AED also hard-coded hinzufügen könntest wäre das super. Habe einige Konten in AED, wo ich momentan jede einzelne Transaktion in USD umrechnen und eingeben muss. Danke Dir!

Am 16. Aug. 2016, 17:24 +0400 schrieb Andreas Buchen <notifications@github.com>:

**Comment by jphdxb** [comment]
Hi buchen, ich weiss die Liste ist endlos lang, aber koennte dieses enhancement nochmals in Augenschein treten? Wuerde mir dolle helfen, da ich alle Kontobewegungen momentan manuell und einzeln von AED auf USD kovertieren und eingeben muss. Danke.

**Comment by buchen** [comment]
Hi @jphdxb,

ich habe jetzt AED mal als Währung hinzugefügt. Auf welcher Platform (macOS, Windows, Linux) arbeitest Du? Dann kann ich Dir eine Testversion bauen.

Andreas

**Comment by jphdxb** [comment]
Super. Auf Windows.


Am 18. Dez. 2016, 12:29 +0400 schrieb Andreas Buchen <notifications@github.com>:

Hi @jphdxb<https://github.com/jphdxb>,

ich habe jetzt AED mal als Währung hinzugefügt. Auf welcher Platform (macOS, Windows, Linux) arbeitest Du? Dann kann ich Dir eine Testversion bauen.

Andreas

**Comment by buchen** [comment]
Hier die [64bit](https://dl.dropboxusercontent.com/u/14269663/PortfolioPerformance-0.25.4-SNAPSHOT-win32.win32.x86_64.zip) und [32bit](https://dl.dropboxusercontent.com/u/14269663/PortfolioPerformance-0.25.4-SNAPSHOT-win32.win32.x86.zip) Version für Windows. Wie gesagt - es ist eine Testversion. Dateien, die mit dieser Version gespeichert wurden, können mit älteren Versionen nicht mehr geladen. Ich denke zwischen den Jahren werde ich eine Version veröffentlichen.

**Comment by michaelkress** [comment]
Wäre es auch denkbar, Kryptowährungen hinzuzufügen?
