### ISSUE TITLE
"Ohne Klassifizierung" als Top Level Knoten in Rebalancing Ansicht

### ISSUE THREAD

**Issue by th23x** [buchen/portfolio#601]
Um die tolle Rebalancing Ansicht voll nutzen zu können, wäre es gut eine Option zu haben Einträge "ohne Klassifizierung" von der Berechnung ausschließen zu können.

Damit wäre es möglich zB Cash unberücksichtigt zu lassen.

![ohne-klassifizierung](https://cloud.githubusercontent.com/assets/13735303/17605039/c3ea65a4-6018-11e6-895a-e5337af7712a.jpg)

**Comment by th23x** [comment]
Ich habe gerade mal noch etwas "rumprobiert" und bin über [diesen Eintrag in den FAQ](https://github.com/buchen/portfolio/wiki/Rebalancing) gestolpert.

Nach der Beschreibung dort würde ich auf folgendem Beispiel erwarten, dass # 3 unberücksichtigt bleibt und daher # 4 (IST Wert / SOLL Gesamt = IST %) gerechnet wird - das wäre im Beispiel 61,3%

Aktuell wird aber # 1 und # 2 (IST Wert / IST Gesamt = IST %) gerechnet - und daher # 3 (ohne Klassifizierung) gerade doch berücksichtigt.

![erwartet](https://cloud.githubusercontent.com/assets/13735303/17616488/5539e1b8-6075-11e6-8403-2d303a28aa0f.jpg)

**Comment by buchen** [comment]
Hi @th23x,

Du hast Recht -  die IST % von "ETFs World" bezieht sich auf den IST Wert (also 60,78 statt 131037,78 / 213.815,76 = 61,285%).

Die SOLL-Werte werden aber mMn ohne die Werte in "Ohne Klassifizierung" gerechnet.

Das Ganze irritiert auf jeden Fall. Ich habe mir vorgenommen den Knoten "Ohne Klassifizierung" eine Eben hochzuziehen und neben die Klassifizierung zu packen (hier: "Asset Classes"). Dann sollten die Zahlen logischer sein. Das Feature "Ohne Klassifizierung nicht einbeziehen" habe ich auch erst später eingebaucht - man merkt das.

**Comment by buchen** [comment]
Hi @th23x,

ich habe den Knoten "Ohne Klassifizierung" eine Ebene nach oben verschoben. Das hatte doch einige Auswirkungen auch auf die anderen Grafiken. Könntest Du das mal testen? Welche OS Version brauchst Du? Dann würde ich Dir eine Version bauen.

Andreas.

**Comment by th23x** [comment]
Hallo Andreas,

kann ich morgen gerne mal antesten...ich nutze Windows 7 mit 64bit Java.

Viele Grüße
Thorsten

**Comment by buchen** [comment]
[Hier](https://dl.dropboxusercontent.com/u/14269663/PortfolioPerformance-0.24.3-SNAPSHOT-win32.win32.x86_64.zip) ist eine Win7 64bit Version. Aber Vorsicht: durch andere Änderungen hat sich auch das Dateiformat geändert. Ältere Versionen von PP können die Datei nicht mehr einlesen. Also auf jeden Fall mit einer Kopie arbeiten (es dauert sicherlich noch ein bisschen bis ich die Version veröffentliche).

**Comment by th23x** [comment]
Sieht gut aus - die Anzeigen stimmen jetzt wie oben gewünscht und ich kann beim Durchschauen keine "negativen" / ungewünschten Auswirkungen feststellen!

Willst Du Screenshots von den Anzeigen nach der Änderung?

Ich "spiele" mit dem Snapshot gerne noch etwas weiter rum, wenn ich am nächsten Wochenende mehr Zeit habe...

**Comment by buchen** [comment]
Passt schon. Ich plane noch zwei weitere Änderungen: #606 zur Mehrfach Selektion und eine Filtern der Werte auf ein Depot/Konto. Wenn ich die habe, baue ich noch mal eine Testversion.

**Comment by buchen** [comment]
Unter dem Link oben ist jetzt eine neue Version verfügbar: jetzt kann man mehrere Wertpapiere gleichzeitig per Drag & Drop in Kategorien verschieben. Und man kann die Zahlenwerte filtern, z.B. nur die Werte für ein bestimmtes Depot anzeigen lassen.

Wenn Dir irgendwas beim Test auffällt bin ich über jede Rückmeldung dankbar.

**Comment by th23x** [comment]
Sorry, hab es endlich geschafft das zu testen...also Mehrfachselektion und Drag&Drop klappt.

Ich verstehe nicht ganz was "Zahlenwerte filtern" ist?

**Comment by buchen** [comment]
Das war auf die Schnelle unglücklich formuliert. Ich meinte die neue Filterfunktion oben rechts um die Berechnung auf bestimmte Depots einzuschränken:

<img width="260" alt="bildschirmfoto 2016-09-02 um 07 15 13" src="https://cloud.githubusercontent.com/assets/587976/18193377/1b6b1a6a-70dd-11e6-9529-95ac902a0d1c.png">

**Comment by th23x** [comment]
Danke für die Erklärung...hab es endlich geschafft mir nochmal Zeit zum Testen zu nehmen:

Funktioniert für mich, wie erwartet - ermöglicht jetzt zB das Cash-Konto von der Rebalancing-Berechnung auszuschließen oder nur ein bestimmtes (von mehreren) Portfolios anzuschauen.

Danke, tolles Enhancement!
