### ISSUE TITLE
Keine Dividendenbuchungen bei "inaktiven" Wertpapieren möglich

### ISSUE THREAD

**Issue by th23x** [buchen/portfolio#603]
Die Idee von "inaktiven" Wertpapieren finde ich gut, ich hätte aber erwartet, dass dies WP sind, die ich zwar im Depot noch habe (entsprechend "buy-and-hold"), die ich aber nicht mehr kaufen kann/will.

Wenn dies die Intention ist, dann sollte es aber noch möglich sein, Dividenden für diese einzubuchen, denn im Depot können die WP ja noch sein. Aktuell geht dies aber bei "inaktiv" gesetzten Wertpapieren nicht.

Sollte dies nicht die Intention von "inaktiv" sein, dann würde ich anregen noch einen anderen Status "keine neuen Käufe" einzuführen, der das Wertpapier von der "Kaufen" Eingabemaske ausschließt - und evtl. farblich kennzeichnet (ebenfalls grau?).

**Comment by buchen** [comment]
Inaktiv heißt, dass die Wertpapiere in den Buchungsdialogen nicht angezeigt werden. Die Liste kann sonst verdammt lang werden. Ich habe das versucht in dem Dialog zu beschreiben:

<img width="715" alt="bildschirmfoto 2016-08-16 um 14 44 40" src="https://cloud.githubusercontent.com/assets/587976/17699282/17a932ba-63c0-11e6-9146-9adbd1dc9810.png">

Dividenden kannst Du schon noch erfassen - indem Du einen Rechtsklick auf das Wertpapier selber machst und die Buchung erfasst. Dann (und nur dann) taucht das Wertpapier auch im Dialog wieder auf.

<img width="341" alt="bildschirmfoto 2016-08-16 um 14 43 55" src="https://cloud.githubusercontent.com/assets/587976/17699227/e47e74fe-63bf-11e6-9d42-a6b3900de645.png">

Das geht auch in der Vermögensaufstellung oder in der Liste der Buchungen (wenn man z.B. eine Kaufbuchung mit dem Wertpapiere auswählt).

Genauso verhält es sich mit Käufen. Wenn man das Wertpapier explizit anklickt, dann kann man es weiterhin kaufen.

Ehrlich gesagt möchte ich jetzt nicht einen weiteren Status einführen - das könnte beliebig komplex werden (nicht mehr kaufen, nur verkaufen wenn noch im Bestand, ...)

**Comment by th23x** [comment]
Ah, danke für die Erklärung - darauf bin ich nicht gekommen...dann geht das ja unproblematisch und bedarf keines neuen Status (wäre eh nur ein Backup-Vorschlag gewesen).
