### ISSUE TITLE
Mehrfach-Selektion von Wertpapieren zur Klassifizierung

### ISSUE THREAD

**Issue by jphdxb** [buchen/portfolio#606]
Wenn man vielen Werten noch keine Klassifikation zugeordnet hat, waere es hilfreich einzelne Werte mit STR+Click auszuwaehlen und per drag&drop oder Rechtsklick schnell zu klassifizieren.

**Comment by buchen** [comment]
Macht absolut Sinn. Wenn ich mich an #601 mache, will ich hier auch reinschauen.
