### ISSUE TITLE
IE00B7RBYS07.IR hat auf Yahoo historische Kurse, werden aber nicht geladen

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#609]
http://finance.yahoo.com/quote/IE00B7RBYS07.IR?ltr=1

**Comment by buchen** [comment]
Der identische Link "Download Data" funktioniert auch auf der Yahoo Seite nicht.
Obwohl die historischen Kurse auf der Webseite angezeigt werden.

<img width="826" alt="bildschirmfoto 2016-08-20 um 11 03 15" src="https://cloud.githubusercontent.com/assets/587976/17830206/bac7b7b6-66c5-11e6-9d1f-1880463912a0.png">

**Comment by buchen** [comment]
Die Seite selbst kann auch nicht zum "HTML Import" genutzt werden. Die Kurse werden dynamisch per JavaScript nachgeladen:

https://query2.finance.yahoo.com/v8/finance/chart/BAS.DE?formatted=true&crumb=9FTlydvolVf&lang=en-US&region=US&interval=1d&events=div%7Csplit&range=1y&corsDomain=finance.yahoo.com

**Comment by stephanmunich** [comment]
Ich habe den Eindruck, dieses Issue könnte geschlossen werden. Denn Portfolio Performance lädt sowohl von der HTML-Seite https://finance.yahoo.com/quote/IE00B7RBYS07.IR/history?p=IE00B7RBYS07.IR als auch von https://finance.yahoo.com/quote/IE00B7RBYS07.IR/history?period1=1471953816&period2=1503489816&interval=1d&filter=history&frequency=1d Daten erfolgreich ein. Und wenn man auf den Download Data button klickt, bekommt man eine CSV. Oder habe ich etwas übersehen?
