### ISSUE TITLE
(macOS, Mac OS X) Menüeintrag für FENSTER SCHLIESSEN hinzufügen

### ISSUE THREAD

**Issue by Lanhydrock** [buchen/portfolio#614]
Wunsch: Einen Menüeintrag für aktuelles FENSTER SCHLIESSEN hinzufügen.

Hintergrund:
Wir automatisieren unter macOS das Zusenden der aktuellen Performance und des Vermögensstatus per Screenshot per Applescript.
Wir haben mehrere Portfolios in verschiedenen Dateien abgelegt.
Zur Zeit simulieren wir den Wechsel der Fenster per einer Reihe von KEYSTROKE -Befehlen (ctrl+tab, cursor right etc.).
Dies setzt allerdings voraus, dass die richtigen Dateien in der richtigen Reihenfolge und mit dem richtigen Fokus geöffnet sind.
Ein Befehl FENSTER SCHLIESSEN würde das Handling sehr erleichtern. - Vielen Dank.

**Comment by buchen** [comment]
Hi @Lanhydrock,

ich habe Dir hier mal einen Testversion mit dieser Änderungen hingelegt:
https://dl.dropboxusercontent.com/u/14269663/PortfolioPerformance-0.24.3-SNAPSHOT-macosx.cocoa.x86_64.tar.gz

Dabei geht es mir weniger um den Menüeintrag. Diese Version erlaubt es die Werte in der Klassifizierung auf ein Portfolio einzuschränken. Wie [hier im Wertpapier Forum](http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__1045231) diskutiert.

<img width="815" alt="bildschirmfoto 2016-08-28 um 09 53 30" src="https://cloud.githubusercontent.com/assets/587976/18032447/510b3924-6d05-11e6-9a52-a6d1dd4946f7.png">

Es wäre cool wenn Du das mal ausführlich testen könntest.

⚠️ Diese Version kommt mit einer neueren Version des Dateiformats. Die Dateien können dann nicht mehr mit der alten PP Version geöffnet werden. Also **unbedingt mit eine Kopie arbeiten** ⚠️

**Comment by Lanhydrock** [comment]
zuerst einmal und erneut: vielen, vielen Dank! 

Anmerkungen @ Version 0.24.3.201608280750:

die Spalten mit den Istwerten, mit den errechneten Soll- und Deltawerten sind im momentanen Modell für unsere Daten korrekt

beim Anwenden des Filters werden in der Übersicht alle Konten gelistet, selbst wenn sie inhaltlich nicht zu dem Portfolio gehören; allerdings richtigerweise mit Nullwerten; Abhilfe ggfs. via Kennzeichen beim Konto, zu welchem Portfolio ein Konto gehört bzw. ob es überhaupt eine Zuordnung/Beziehung gibt

es wäre hilfreich, nicht nur Portfolio oder Portfolio-plus-Konto als Filter-Auswahlen zuzulassen, sondern eine beliebige Summe an Portfolios und Konten; wir haben bspw. ein Portfolio (aka Depot) mit einem entsprechenden Konto und dann noch mehrere Konten, die alle zum selben Portfolio gehören

es wäre sehr schön, wenn eine Einstellung hinzugefügt werden kann, ob PP die Werte in "ohne Klassifizierung" einbezieht oder nicht; (was mit der erweiterten Filterung [s.o.] natürlich obsolet, allerdings auch unkomfortabler wäre); momentan berechnet PP die Istwerte inkl. der "ohne Klassifizierung", was aber beim Rebalancing unerwünscht sein kann (vor allem beim Vergleich vom Ist-% und Soll-%)

in den Performance-Diagrammen kann man den Filter via Zahnrad erreichen, in der Klassifizierung über das Filtersymbol

Zustand des Portfolio-Filters wird nicht behalten, wenn man einen anderen Bericht aufruft, dann wieder zurückkommt

Anmerkung für die Zukunft evtl., da bestimmt mit deutlich mehr Aufwand verbunden: unsere Sollallokation variiert pro Portfolio; daher müssen wir die Werte bei jeder Änderung des Filters entsprechend manuell anpassen, was aber natürlich machbar ist

bzgl. Menüeintrag FENSTER SCHLIESSEN auf dem Mac: evtl. noch den Hotkey CMD+W hinzufügen, der ist bei manchen Menüeinträgen von PP bei Mac OS X El Capitan entsprechend vorbelegt, obwohl wir da nichts eingestellt haben; "Datei schliessen" heisst beim Mac oft "Fenster schließen" (Fenster und sz)

**Comment by buchen** [comment]
> beim Anwenden des Filters werden in der Übersicht alle Konten gelistet, selbst wenn sie inhaltlich nicht zu dem Portfolio gehören; allerdings richtigerweise mit Nullwerten; Abhilfe ggfs. via Kennzeichen beim Konto, zu welchem Portfolio ein Konto gehört bzw. ob es überhaupt eine Zuordnung/Beziehung gibt

Korrekt. Obwohl für das Konto keine Werte errechnet werden, bleibt das Konto bestehen. Das ist bei den Wertpapieren ebenfalls. Auch wenn man die Wertpapiere nicht hält, bleiben die in der Liste. Aktuell ist mir der Aufwand zu groß - wenn ich zusätzlich die Zeilen filtere, muss ich die Logik zum Zuordnen/Drag&Drop ändern.

> es wäre hilfreich, nicht nur Portfolio oder Portfolio-plus-Konto als Filter-Auswahlen zuzulassen, sondern eine beliebige Summe an Portfolios und Konten

Ist jetzt drin 😄 Die oben verlinkte Beta-Version ist aktualisiert.

 > es wäre sehr schön, wenn eine Einstellung hinzugefügt werden kann, ob PP die Werte in "ohne Klassifizierung" einbezieht oder nicht; (was mit der erweiterten Filterung [s.o.] natürlich obsolet, allerdings auch umkomfortabler wäre); momentan berechnet PP die Istwerte inkl. der "ohne Klassifizierung", was aber beim Rebalancing unerwünscht sein kann (vor allem beim Vergleich vom Ist-% und Soll-%)

Das kann ich gerade nicht nachvollziehen. Die Werte in "ohne Klassifizierung" werden *nicht* für das Rebalancing verwendet. Die SOLL Werte werden auf Basis der IST der klassifizierten Wertpapiere berechnet.

Vielleicht ist da aber noch ein Bug... Hast Du eine Beispielsrechnung /Screenshot?

> in den Performance-Diagrammen kann man den Filter via Zahnrad erreichen, in der Klassifizierung über das Filtersymbol

Ja, eine Datenreihe zum Diagramm hinzufügen habe ich als "Konfiguration" gesehen. Die Werte zu reduzieren machen ich mit dem "Filter" Symbol. Vielleicht nicht ganz konsistent, andrerseits war das "Konfiguration" Symbol in der Ansicht schon genutzt... 😉 

> Zustand des Portfolio-Filters wird nicht behalten, wenn man einen anderen Bericht aufruft, dann wieder zurückkommt

Kommt. Erst mal will ich mit der Funktion experimentieren. Ich haben den gleichen Filter jetzt in die Vermögensaufstellung eingebaut. Vielleicht "merke" ich mir das dann für die ganze Datei (ähnlich wie ich das mit dem Berichtszeitraum mache). Mal sehen. Ich arbeite mich immer in kleinen Schritten weiter.

> Anmerkung für die Zukunft evtl., da bestimmt mit deutlich mehr Aufwand verbunden: unsere Sollallokation variiert pro Portfolio; daher müssen wir die Werte bei jeder Änderung des Filters entsprechend manuell anpassen, was aber natürlich machbar ist

Hier müsste man wohl eine weitere Klassifikation anlegen - mit der Sollaktion für dieses Konto.

Den Filter sollte man sich dann wohl eher pro Klassifikation merken... (siehe Anmerkungen oben).

> bzgl. Menüeintrag FENSTER SCHLIESSEN auf dem Mac: evtl. noch den Hotkey CMD+W hinzufügen, der ist bei manchen Menüeinträgen von PP bei Mac OS X El Capitan entsprechend vorgelegt, obwohl wir da nichts eingestellt haben; "Datei schliessen" heisst beim Mac oft "Fenster schließen" (Fenster und sz)

Ich habe es mal "Datei schliessen" genannt, weil es ja nur der Reiter ist. Man kann durch das "Herausziehen" des Reiters auch ein weiteres Fenster aufmachen.

**Comment by Lanhydrock** [comment]
> Ist jetzt drin 😄 Die oben verlinkte Beta-Version ist aktualisiert.

Sauber, so soll es sein; sieht sehr gut aus. (Nur noch das Zwischenspeichern der selbst neu gebastelten Filter über Neustart der Anwendung hinaus; aber das hast Du ja bestimmt auf der Liste...)

> [ohne Klassifizierung berücksichtigt] 
> Das kann ich gerade nicht nachvollziehen. 

Ich auch nicht mehr; wir hatten uns von den Ist-% auf der obersten Kategorie ablenken lassen. Die Ist-% sind dort natürlich richtig. Die auf den Unterkategorien werden eben basierend auf dem Ist-Wert der Oberkategorie berechnet und sie sind damit korrekt. - Pardon für die Verwirrung.

> Hier müsste man wohl eine weitere Klassifikation anlegen

Gute Idee; damit und mit der neuen Filterung ist auch das Problem beseitigt. Sehr mächtig, Dein Programm mittlerweile! Danke sehr!

Kurze Zwischenfrage: Können wir mit unserer Beta-Datei mit dem neuen Format weiterarbeiten, weil das bald so freigegeben wird? Oder könnte/ wird sich das nochmals ändern und wir sollten nochmals zu den drei separaten Dateien zurückkehren?

**Comment by Lanhydrock** [comment]
Ach ja, `<Quengelmodus AN>`und bitte die Filter auch beim PERFORMANCE-Bericht einführen und den gewählten Filter dort und bei VERMÖGENSAUFSTELLUNG jeweils auch in die Unterberichte vererben`<Quengelmodus AUS>`

Danke schön!

**Comment by buchen** [comment]
> Kurze Zwischenfrage: Können wir mit unserer Beta-Datei mit dem neuen Format weiterarbeiten, weil das bald so freigegeben wird? Oder könnte/ wird sich das nochmals ändern und wir sollten nochmals zu den drei separaten Dateien zurückkehren?

Die Beta-Datei könnt Ihr weiterführen. Ich hatte überlegt dieses Wochenende ein Update zu veröffentlich, komme jetzt aber nicht mehr dazu. Hoffentlich nächstes Wochenende. Das Format wird sich aber nicht mehr ändern.

**Comment by Lanhydrock** [comment]
Klasse, danke für Version 0.25.0, die heute beim Update heruntergeladen wurde! 

Wir möchten freundlich darum bitten, dass  Du noch die Thematik aus [dem obigen Comment](https://github.com/buchen/portfolio/issues/614#issuecomment-244613091) auf die Liste nimmst. Stichworte: Filter bei Ansichtswechsel beibehalten und vor allem: Filter bei PERFORMANCE und dort sowie bei VERMÖGENSAUFSTELLUNG in die Kinder vererben; denn jetzt sehen wir bei VERMÖGENSAUFSTELLUNG>BESTÄNDE immer nur das Gesamtportfolio und nicht die Einzelportfolios, die wir nunmehr ja alle in einer Datei verwalten. (Anm.: Migration via Export und Import der Kinderdepot- und -kontenhistorie funktionierte einwandfrei.) - Danke sehr.
