### ISSUE TITLE
Spaltenbreite wird nicht gespeichert wenn man Vermögensaufstellung direkt schliesst

### ISSUE THREAD

**Issue by Integer11** [buchen/portfolio#619]
Wenn ich in der Standardansicht (Alle Wertpapiere) oder in der Ansicht (Berichte->Wertpapier Performance) etwas verändere, werden die Änderungen nicht dauerhaft übernommen.

Wenn ich eine neue Spalte hinzufüge, die Spaltenreihenfolge oder die Sortierung ändere, sind alle Änderungen nach einem Neustart wieder verschwunden.

Anders verhält es sich wenn ich  z.B. Änderungen am Dashboard vornehme oder in einem Diagramm eine Datenreihe hinzufüge oder entferne. Wenn ich danach das Programm beende, erscheint dort eine Abfrage: "Sollen die Änderungen gespeichert werden?". Und danach sind die Änderungen auch dauerhaft gespeichert.

Sieht so aus als würde das Programm nicht überall registrieren, dass Änderungen an den Ansichten vorgenommen wurden.

**Comment by buchen** [comment]
Ist das jetzt mit Version 0.25.0 immer noch der Fall?
Ich hatte einen ähnlichen Fehler mit #596.

**Comment by Lanhydrock** [comment]
Die Spaltenänderungen werden in der 0.25.0 bei uns richtig abgespeichert und nach Neustart beibehalten.

Jedoch überstehen die Filter einen Neustart leider nicht. Ich wiederhole daher mal in diesem Issue hier unsere [Anmerkungen](https://github.com/buchen/portfolio/issues/614#issuecomment-246203048) aus #614 und schließe den dortigen mit den verfänglichen Namen:

Stichworte: Filter bei Ansichtswechsel beibehalten und vor allem: Filter bei PERFORMANCE und dort sowie bei VERMÖGENSAUFSTELLUNG in die Kinder vererben; denn jetzt sehen wir bei VERMÖGENSAUFSTELLUNG>BESTÄNDE immer nur das Gesamtportfolio und nicht die Einzelportfolios, die wir nunmehr ja alle in einer Datei verwalten. - Danke sehr.

**Comment by Integer11** [comment]
In der Version 0.25.0 werden die Änderungen nun einwandfrei gespeichert.

**Comment by buchen** [comment]
> Jedoch überstehen die Filter einen Neustart leider nicht.

Die Filter sollten den Neustart überstehen, allein sie sind aktuell nicht "vorausgewählt". D.h. wenn Du 1 Depot + 3 Konten als Filter auswählst, dann sollte diese Auswahl auch nach dem Neustart zur Verfügung stehen.

@Integer11 Danke für den Nachtest!

**Comment by Lanhydrock** [comment]
Hallo, ja, genau, wir haben uns unklar ausgedrückt; die Filter sind nach Neustart da, aber gerade die Bebeihaltung der Auswahl wäre sehr hilfreich.

Noch viel wichtiger wäre aber der Wunsch, dass die Filter auch in den Unterberichten vorhanden sind. Können wir aus der Tatsache, dass das Issue nun geschlossen ist, ableiten, dass Du zustimmst und das in einer der nächsten Versionen kommen wird? - Danke sehr.

**Comment by buchen** [comment]
> Können wir aus der Tatsache, dass das Issue nun geschlossen ist, ableiten, dass Du zustimmst und das in einer der nächsten Versionen kommen wird?

Ich habe übersehen, dass Du #614 geschlossen hast. Diesen Issue habe ich geschlossen, weil das ursprüngliche Problem "Spalten werden nicht gespeichert" nicht mehr existiert - Integer11 hat das bestätigt.

Ich habe #621 für die Filter angelegt.

**Comment by Integer11** [comment]
Eine Sache ist mir gerade noch aufgefallen. Wenn man in einer Tabelle nur die Spaltenbreite ändert, dann wird das beim Neustart nicht übernommen.

**Comment by buchen** [comment]
@Integer11 Danke. Das konnte ich reproduzieren. Wenn man die Ansicht vor dem Schliessen noch ändert, dann ist alles okay. Wenn man aber das Programm direkt schliesst, dann tut es nicht.

Ich muss mal schauen ob ich einen "Resizing end" Event mitbekomme.

**Comment by Integer11** [comment]
Zusätzlich zur Spaltenbreite wird auch eine Änderung der Spalten-Reihenfolge nicht übernommen.
