### ISSUE TITLE
Wertpapier Performance wird bei einigen Wertpapieren nicht richtig dargestellt

### ISSUE THREAD

**Issue by Integer11** [buchen/portfolio#627]
In meinem Portfolio wird bei 2 Wertpapieren die Performance anscheinend nicht korrekt dargestellt, die Werte stimmen nicht.

Dabei ist mir aufgefallen, wenn ich unter "Berichte->Wertpapier Performance" auf die Umsätze schaue, so ist der Kauf als Buchung überhaupt nicht enthalten. Der erste Eintrag der Buchungen lautet dort immer "Kursnotierung". Obwohl das Kaufdatum immer vor dem der Kursnotierung lag wird der Kauf nicht angezeigt. Bei allen anderen Wertpapieren lautet der erste Eintrag immer "Kauf".

Da der Betrag der Kursnotierung nicht mit dem Kaufpreis identisch ist, wird vermutlich auch die Performance falsch berechnet?

Den Kauf hatte ich unter "Alle Wertpapiere" erfasst und wird dort unter Umsatz auch angezeigt.

Ich habe mal ein bisschen experimentiert und dabei festgestellt, dass auch alle nachträglichen Buchungen von Käufen mit dem Datum vor dem der Kursnotierung nicht als Kauf dargestellt werden. Es wird nur die Stückzahl der Kursnotierung erhöht.

**Comment by buchen** [comment]
Unter *Berichte->Wertpapiere* wird die Performance immer in Bezug auf den ausgewählten Berichtszeitraum angezeigt. Wenn der Kauf *vor* dem Anfang des Berichtszeitraumes liegt, dann wird die Kursnotierung als Einstand verwendet.

Ändere mal den Berichtszeitraum. Dann solltest Du auch den Kauf sehen.

**Comment by Integer11** [comment]
Hab ich übersehen, genau das war's.

Vielen Dank.
