### ISSUE TITLE
Ing-Diba Dividendengutschrift pdf wird nicht importiert

### ISSUE THREAD

**Issue by kobotschick** [buchen/portfolio#629]
Ing-Diba pdfs mit "Ertragsgutschrift" im Dateinamen und  "Dividendengutschrift" im Betreff werden nicht importiert.
Ist  "Ertragsgutschrift" der Betreff wird alles korrekt importiert.
Die Dokumente unterscheiden sich nur in der Betreffzeile.

**Comment by buchen** [comment]
Könntest Du eine Textversion generieren ([siehe hier](https://github.com/buchen/portfolio/wiki/PDF%20Dokumente#und-andere-pdf-dokumente)) und mir schicken?

Der Dateiname sollte egal sein. Aber im Text wird in der Tat nur nach "Ertragsgutschrift" gesucht. Meist ist das aber nicht die einzige Änderungen in den PDF Dokumenten.

**Comment by stephanmunich** [comment]
Mir scheint, diese Diskussion könnte geschlossen werden, da der INGDiBa-PDF-Extractor mittlerweile einen Abschnitt zum Erkennen der "Dividendengutschrift" enthält, oder bist Du anderer Meinung, @buchen bzw. @kobotschick ?

**Comment by buchen** [comment]
Ich denke auch - ich war in den letzten Monaten nicht besonders sorgfältig bei der Pflege der Github Issues. Und der ist ja schon aus dem Oktober.
