### ISSUE TITLE
Volatilität sollte annualisiert werden

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#631]
> Also ich hab mal ein bisschen gesucht. In PP wird die tägliche Volatitlität berechnet (richtig?). I.d.R. wird in der "Finanzwelt" die Volatitlität aber annularisiert angegeben. D.h folgendes (ich zitiere ):
> "...Gleichviel indes, ob der Rechnung ursprünglich Tages-, Wochen-, Monats- oder Quartalsschlusskurse und entsprechende Renditen zugrunde liegen, lassen diese sich auf mit Leichtigkeit in die intendierte Jahresvolatilität umgestalten. Dazu wird schlicht und einfach die vorliegende Standardabweichung σ malgenommen mit der Quadratwurzel aus der Zahl des sich in einem Jahr wiederholenden Referenzzeitraums.
> 
> Der Ausdruck für die annualisierte Standardabweichung (= Volatilität) lässt sich somit auf eine klare Formel bringen:
> σann = σ · √n ..."
> 
> D.h. (wenn richtig verstanden) dass man die in PP berechnete Volatilität nur mit der Quadratwurzel von 250 (*) mal nehmen müsste und man hat die annularisiert Volatilität σann = σt · √250

---

> Quelle1: https://www.zmp.de/f...atilitaet-excel
> Quelle 2: http://www.deifin.de/thema002.htm (Hier habe ich das obige Zitat her: Schritt 3)
> - "...Da das Kalenderjahr aufgrund von Handelspausen an Wochenenden und Feiertagen je nach Land lediglich über rund 250 Börsenhandelstage verfügt und empirische Befunde überdies darauf hindeuten, dass eher Börsenhandelstage denn Kalendertage für eine angemessene Bestimmung der Volatilität einer Aktie maßgeblich sind, multipliziert man zur Annualisierung der Standardabweichung im Falle vorliegender Tagesrenditen mit der Wurzel aus 250, statt aus 365, d. h. σann = σt · √250."
>   (Ebenfalls zitiert aus Quelle 2)

**Comment by es86de** [comment]
Die Volatilität sollte nicht _grundsätzlich_ annualisiert werden.

Die Volatilität ist wie die Rendite abhängig vom betrachteten Zeitraum. Beide Kennzahlen sollten immer gemeinsam betrachtet und daher auch für den gleichen Zeitraum berechnet werden. Eine annualisierte Volatilität ist daher nur dann sinnvoll, wenn Sie gemeinsam mit der Rendite über ein Jahr betrachtet wird.

Ich schlage daher vor, in Portfolio Performance nicht die tagesbezogene (aktueller Stand) oder annualisierte (oben vorgeschlagene) Volatilität, sondern die auf jeweiligen Betrachtungszeitraum bezogene Volatilität zu verwenden. Damit wäre auch die Berechnung des Sharpe-Ratio für verschiedene Zeiträume problemlos möglich.

Der nachfolgende Pull-Request verweist auf einen Commit, in dem ich die Volatilitätsberechnung entsprechend angepasst habe. Die Berechnung basiert nun auf logarithmierten Renditen. Dies führt zu genaueren Ergebnissen und passt besser ins Konzept, da bei dieser Berechnungsmethode die TTWROR dem Erwartungswert entspricht.

Ich habe die nach meinen Änderungen in Portfolien Performance berechneten Volatilitäten für den ARERO ETF und die TESLA Aktie mit den auf comdirect angegebenen Volatilitäten für verschiedene Zeiträume verglichen und die Werte stimmen sehr gut überein.

Neben der Risk.java habe ich auch die RiskTest.java und die PerformanceIndexTest.java angepasst. Lediglich die VolatilityTestCase.java muss noch auf die neue Berechnung angepasst werden. Dies konnte ich leider nicht selbst durchführen, da ich das dort referenzierte Excelsheet nicht habe. Das kann ich aber gerne nachholen, wenn du mir die Datei zur Verfügung stellst.

**Comment by doncristobal** [comment]
Ich möchte diese Issue nochmal aufbringen und zur Diskussion stellen, ob es nicht doch sinnvoller wäre, generell auf annualisierte Volatilität umzusteigen. (Als Referenz sei zusätzlich auch noch dieser Forumsthread genannt: https://forum.portfolio-performance.info/t/rendite-volatilitaet-grafik/412/9)

Aktuell ist es ja so, dass die Volatilität aus den täglichen Renditen errechnet wird, und dann auf den gerade ausgewählten Berichtszeitraum mittels *sqrt(Anz. Tage Berichtszeitraum) skaliert wird. 

Im folgenden einige Argumente, warum mir die Verwendung annualisierter Volatilität sinnvoller erscheint:
1. Optische Vergleichbarkeit: Praktisch alle Referenzquellen verwenden annualisierte Volatilität (anbei einige Beispiele). Mental hat man meist die Vorstellung von „MSCI World hat ca. 12%-20% Volatilität, der DAX etwas mehr (da er nur aus 30 Aktien besteht),  Anleihen ca. 4-6%. Und ein z.B. 60:40-Portfolio liegt dann irgendwo zwischen diesen Werten.“ Auch wenn „3 Jahres-Volatilität“ wie im 1. und 2. Beispiel unten (Quelle: justetf.com bzw. MSCI World-Factsheet) ausgegeben wird, ist dies eine annualisierte Volatilität, die dann aber eben aus den Tages- (oder Monats-)daten von 3 Jahren berechnet wurde.
![image](https://user-images.githubusercontent.com/5220023/59967548-dddea880-952b-11e9-96cb-d44d8058501b.png)

2. Aussagekraft für Benutzer: Grundsätzlich erscheint es zwar auf den ersten Blick flexibel, dass der User selber den Berichtszeitraum auswählen kann, für den die Volatilität berechnet wird.  Ich glaube aber, dass dies für Berichtszeiträumen anders als 1 Jahr nur wenig Aussagewert für den Benutzer hat: was sagt es mir z.B. aktuell, dass ich in den letzten 3 Monaten 1,99% Volatilität hatte? Mit den o.g. publizierten Werten kann ich es nicht vergleichen, da es sich auf einen anderen Zeitraum bezieht und ich mir das erstmal mit sqrt(N) multiplizieren müsste, um vergleichbar zu sein.  Man könnte höchstens argumentieren, dass die Aussage „1,99% Volatilität in 3 Monaten“ mir sagt, dass ich mit 68% Wahrscheinlichkeit (eine Standardabweichung der Normalverteilung) innerhalb von 3 Monaten die durchschnittliche Rendite +- 1,99% erwirtschaften werde, aber ich vermute, dass User eher selten so denken. Vielmehr wollen sie wissen, wie sich die Volatilität ihres Portfolios in den letzten x Monaten mit den typischen Volatilitäten (s. Punkt 1) vergleicht, um ein Gefühl für die mögliche „Riskantheit“ des Portfolios zu bekommen. Eine Vergleichbarkeit ist grundsätzlich mit der jetzigen Berechnung nicht gegeben, denn die jetzt angegebene Volatilitätsangabe bezieht sich immer auf einen bestimmten Zeitraum, da sie aber mit sqrt(Anz. Perioden) skaliert, hat die Volatilität immer nur im Kontext des Zeitraums eine Aussagekraft.   (Diese Verwirrung klingt ja in dem o.g. Forumsbeitrag anfangs auch an.)

3. Ja, man kann auch heute theoretisch immer „1 Jahr“ als Berichtszeitraum einstellen und hat dann auch annualisierte Volatilität. Aber das hat meinem Eindruck nach folgende Probleme:
    1. Ich habe ein PP-Depot, in dem ich alle Papiere ab 29.3.2019 (fiktiv) eingeliefert habe, da ich erst ab dann die Verwaltung begonnen habe und erst ab dann die Performanceberechnung in PP  vornehmen will. Ich habe nun überhaupt keine Möglichkeit, mir eine annualisierte Volatilität anzusehen, denn wenn ich jetzt auf 1 Jahr Berichtszeitraum umstelle, liegen für 3/4 des Berichtszeitraums keine Daten/Papiere vorliegen und ich bekomme einen Wert, der keinen Sinn macht. Gerade für neue User ist das ziemlich verwirrend (auch wenn das vielleicht nicht jeder mit einer Einlieferung macht).  Annualisierte Volatilität würde dagegen einfach die Daten ab 29.3. bis jetzt nehmen und auf eine annualisierte Volatilität hochrechnen.   
    2. Ich könnte mir vorstellen, dass für viele Benutzer auf der Performance-Dashboard-Seite der interessanteste Berichtszeitraum nicht  „1 Jahr“, sondern lieber  „YTD“ (Year-to-date, also ab 1.1. des aktuellen Jahres) wäre, da man sich oft für die Performance des aktuellen Jahres interessiert. (Für mich wäre es jedenfalls so.). Dadurch (durch die Einstellung des Berichtszeitraum ab 1.1.) habe ich aber dann automatisch auch keine annualisierte Volatilität mehr (und auch keine Möglichkeit dies einzustellen).

Das Argument von es86de oben ("Die Volatilität ist wie die Rendite abhängig vom betrachteten Zeitraum. Beide Kennzahlen sollten immer gemeinsam betrachtet und daher auch für den gleichen Zeitraum berechnet werden. Eine annualisierte Volatilität ist daher nur dann sinnvoll, wenn sie gemeinsam mit der Rendite über ein Jahr betrachtet wird.") überzeugt mich bisher noch nicht so ganz, man sieht ja z.B. auch an den o.g. Fact sheets, dass große Indexanbieter wie MSCI sehr wohl z.B. eine annualisierte Volatilität aus den Returns der letzten 3 Jahre berechnen (d.h. es besteht kein Widerspruch zwischen einem Berichtszeitraum von 3 Jahren und einer annualisierten Volatilität). 
Ich habe aber selbstverständlich nichts dagegen, ebenfalls eine Volatilität für einen Berichtszeitraum optional zusätzlich anzubieten (auch wenn ich sie persönlich nicht nötig finde, aber vielleicht sieht das mancher anders). Meiner Meinung nach sollte die annualisierte Volatilität aber der Defaultwert beim Start sein. 

Code-Veränderungen:

Der Kern der Codeänderung ist (wie an anderer Stelle schon diskutiert) sehr einfach, ich habe bei mir in Risk.java einfach die folgenden Zeilen mit Math.sqrt(252) statt mit vorher Math.sqrt(count) multipliziert. Das funktioniert bisher auch recht zuverlässig (soweit ich das übersehen kann).

                //stdDeviation = Math.sqrt(tempStandard / (count - 1) * count);
                //semiDeviation = Math.sqrt(tempSemi / (count - 1) * count);
                // Das folgende entspricht annualisierter Volatilität: 
                stdDeviation = Math.sqrt(tempStandard / (count - 1)) * Math.sqrt(252);
                semiDeviation = Math.sqrt(tempSemi / (count - 1)) * Math.sqrt(252);


Fragen:
1. Wie seht ihr das Thema? 
2. Falls Zustimmung zu annualisierter Volatilität, wie seht ihr die Notwendigkeit einer zusätzlichen Funktion, Volatilität für beliebige Zeiträume (wie bisher) zu berechnen? 
3. Was müsste noch geändert werden außer der o.g. Kernfunktionalität in Risk.java?

Falls gewünscht kann ich gerne einen entsprechenden PR einbringen.
