### ISSUE TITLE
Fehler beim Importieren von Dividendendokument mit Fremdwährung von Consors

### ISSUE THREAD

**Issue by akoch** [buchen/portfolio#633]
Reproduzierbar mit "ConsorsbankErtragsgutschrift6_USD_Freibetrag_ausgeschoepft.pdf" aus dem Testprojekt. Die CheckCurrenciesAction schlägt mit der Meldung "Währung des Nettowertes (USD) passt nicht zur Währung EUR des Wertpapiers" an.

Kleine Zusatzfrage: Ist nicht ganz die richtige Stelle, aber warum werden beim Import für Consors die Steuern als extra Buchung erfasst und nicht direkt in der Dividendenbuchung aufgeführt?

**Comment by buchen** [comment]
> Kleine Zusatzfrage: Ist nicht ganz die richtige Stelle, aber warum werden beim Import für Consors die Steuern als extra Buchung erfasst und nicht direkt in der Dividendenbuchung aufgeführt?

Ich denke das ist einfach historisch gewachsen. Man kann erst seit kurzem die Steuern direkt in der Buchung erfassen. Und ich habe nicht alle PDF Importe geändert (wie Du merkst habe ich selber kein Consors Depot). Wenn das in Deiner Change noch nicht drin ist (ich habe sie mir noch nicht angeschaut), wäre es cool wenn Du das ändern könntest.

**Comment by akoch** [comment]
Ziehe ich nach. 

Den obigen Fehler habe ich in dem change auch noch nicht behoben. Ich kenne mich in dem Projekt noch nicht gut genug aus, um die sinnvollste Lösung hierfür zu finden.

**Comment by buchen** [comment]
> Reproduzierbar mit "ConsorsbankErtragsgutschrift6_USD_Freibetrag_ausgeschoepft.pdf" aus dem Testprojekt. Die CheckCurrenciesAction schlägt mit der Meldung "Währung des Nettowertes (USD) passt nicht zur Währung EUR des Wertpapiers" an.

Bei einer Dividendenzahlung prüfe ich, dass a) die Währung des Nettowertes in der Währung des Wertpapiers ist und b) der Bruttowert dann zu der Währung des Kontos passt.

Also Wertpapier in USD und Konto in EUR muss sich auch in der Dividendenzahlung reflektieren. Wenn das Wertpapier aber in EUR notiert (vielleicht weil man genau einen solchen Kursprovider gefunden hat), dann kann man die Dividende nicht in USD erfassen (obwohl das vielleicht die Bank tatsächlich so meldet). Das könnte oben zu dem Mismatch führen.

**Comment by akoch** [comment]
Verstehe, aber was macht man da am Besten? Meine spontane Idee wäre, dass man beim Import schaut, welche Währung das Wertpapier hat und dann entsprechend die Buchung anlegt, je nachdem ob sie der Währung der Buchung im PDF entspricht oder nicht.

**Comment by akoch** [comment]
Also ich hab grad mal bisschen rumgespielt und mir ist noch nicht ganz klar, was ich wie buchen müsste, damit das passt. Der folgende Ausschnitt zeigt die PDF-Abrechnung
![div1](https://cloud.githubusercontent.com/assets/1712469/19353174/cb3a45e2-9162-11e6-9366-0204247ca2fc.PNG)
Mit nem kleinen Fix, dass er die Abbrechnung überhaupt einließt, sieht der Dialog zum Editieren wie folgt aus, Da passt ja schon die Gutschrift nicht.
![div3](https://cloud.githubusercontent.com/assets/1712469/19353560/0a703180-9164-11e6-8ec5-9c88df6a672f.PNG)
Davon ab, dass ich nicht weiß, wo ich "Fremde Spesen" verrechne, sieht der Dialog nach ein bisschen rumspielen nun so aus. Die 55,76 machen da jetzt aber nicht so richtig Sinn, aber wenn ich den Wert ändere, schlägt wieder eine Validierung fehl.
![div2](https://cloud.githubusercontent.com/assets/1712469/19353176/ccdb6138-9162-11e6-987b-a6b619714e59.PNG)
Daher erstmal meine grundsätzliche Frage. Intepretiere ich die Felder falsch oder sind die Werte auf dem richtigen Weg?

**Comment by buchen** [comment]
Ich hätte was in diese Richtung erwartet:

<img width="499" alt="bildschirmfoto 2016-10-13 um 21 24 11" src="https://cloud.githubusercontent.com/assets/587976/19363653/9c9a8890-918b-11e6-9dfd-017c623f79a3.png">

Also den Bruttowert wie aus dem PDF.
Alle Steuern in Fremdwährung, alle Steuern in Buchungswährung.
(Fremde Spesen hier halt mal als Steuern - Gebühren kann man da noch nicht erfassen).

Problem in diesem Beispiel: weil die USD Beträge jetzt einzeln umgerechnet werden, kommt es zu einem Rundungsfehler 😠 Da müsste ich aktuell das ganze Modell ändern (was wohl Sinn machen könnte, aber eine grössere Baustelle wäre). Dann beim Import doch lieber erst mal den Bruttowert um einen 1 Cent reduzieren:

<img width="497" alt="bildschirmfoto 2016-10-13 um 21 29 02" src="https://cloud.githubusercontent.com/assets/587976/19363864/1bd63028-918c-11e6-8ea5-1af768ec7719.png">
