### ISSUE TITLE
Day Trading: Vorgehensweise um Derivate zu verbuchen

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#636]
Wie können Derivate am besten verbucht werden, damit sie korrekt in die Performanceberechnung einfließen?

Gerade bei Knock Outs mit einer Haltedauer von wenigen Minuten/Stunden, macht es keinen Sinn sie als Wertpapier hinzufügen. Zum einen leidet schnell die Übersicht und zum anderen werden oft die Papiere nicht gefunden so dass manuelle Kurseingaben nötig wären.

**Comment by buchen** [comment]
Ich kenne mich mit Knock Outs gar nicht aus. Wenn Du die als Wertpapier erfassen würdest, würde es dann funktionieren? Ich versuche zu verstehen, ob Du vermeiden möchtest ein Wertpapiere anzulegen (klar, das werden viele wenn die nur ein paar Stunden gültig sind) oder ob die Berechnung an sich noch unvollständig ist.

Ohne ein Wertpapier in der Liste "Alle Wertpapiere" kann PP momentan nicht. Aber vielleicht könnte man die auch im Kaufdialog direkt anlegen. Und besser verstecken als mit "inaktiv" zu bezeichnen.

BTW, Buchungen werden "nur" mit Datum erfasst - nicht mit Uhrzeit. Ich sortiere die zwar (erst Kaufbuchungen, dann Verkaufbuchungen), aber ich könnte mir vorstellen dass da auch eine Unschärfe entsteht.

**Comment by megabugman** [comment]
Ich habe mal ein paar Tests durchgeführt. Die Kennzahlen (Kurserfolg, TWROR, etc) im Dashboard stimmen generell nicht (mit Wirklichkeit) übereinstimmen, solange keine Kurse geladen oder manuell eingegeben werden. Ist ja auch logisch da von einem aktuellen Marktwert von Null ausgegangen wird.

Das ist aber aufgrund der kurzen Haltedauer kein großes Problem, denn nachdem ein Verkauf korrekt mit Gebühren eingegebe wurde, stimmen die Kennzahlen wieder.

Dann komme ich um die Eingabe aller Wertpapiere wohl nicht umhin... Danke.
