### ISSUE TITLE
Klassifizierung: Einstellung des Zeitraums für Flächendiagramm

### ISSUE THREAD

**Issue by martvan** [buchen/portfolio#643]
Das Flächendiagramm für die Klassifizierungen zeigt den Zeitverlauf der einzelnen Kategorien an. In 0.25.1 wird hier das gesamte Jahr 2016 angezeigt. Dies hat den Nachteil, dass ab dem jeweils aktuellen Datum aus gesehen die Verlaufskurven gerade verlaufen - da die Daten in der Zukunft liegen, kann hier auch keine Veränderung vorliegen. 

Wenn mich meine Erinnerung nicht täuscht, wurde in alten Versionen nur der Zeitraum bis "heute" dargestellt, was ich als intuitiver empfinde. Ein nettes Feature wäre die freie Wahl des Zeitraums (ähnlich der Konfigurierbarkeit bei den Berichten, z.B. dem Performance-Diagramm).

![flaechendiagramm](https://cloud.githubusercontent.com/assets/23138901/19830426/4d6c359c-9df8-11e6-9e6a-3e9384bc5920.PNG)

**Comment by buchen** [comment]
> Wenn mich meine Erinnerung nicht täuscht, wurde in alten Versionen nur der Zeitraum bis "heute" dargestellt, was ich als intuitiver empfinde.

Ja und Nein. In älteren Versionen könnte man zur Auswahl des Berichtszeitraums immer "nur" das Startdatum festlegen - das Enddatum war immer der aktuelle Tag. Jetzt geht mehr. Aber in diesem Chart macht eine Projektion in die Zukunft überhaupt keinen Sinn (ich will eigentlich nirgendwo in die Zukunft projizieren....).

Das behebe ich. Danke für den Hinweis!
