### ISSUE TITLE
Saldo Sortierung inkorrekt

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#652]
wenn eine Aktie 2x am gleichen Tag gekauft wird, stimmt die Sortierung des Saldo nicht.
![saldo](https://cloud.githubusercontent.com/assets/17204819/20231833/d0ba3af4-a864-11e6-91d0-45db09265bf5.png)
Erwartungsgemäß sollte 70,90 oben sein, da nach Datum sortiert wurde.
Dh wenn vom 3t letzten Saldo (100,40) der Kaufbetrag abgezogen wird (14,75) dann sollte **nicht** 70,90 rauskommen.

**Comment by buchen** [comment]
Danke. Habe ich behoben. Das Problem ist, dass ich tatsächlich nur das Datum habe. Für die Berechnung des Saldos brauche ich aber eine stabile Sortierreihenfolge. Dafür habe ich noch Betrag und Typ hinzugenommen. Die sind aber in diesem Fall identisch. Jetzt habe ich noch den Hashcode hinzugenommen. Damit sollte es jetzt wirklich stabil sein.
