### ISSUE TITLE
UI: Übernehmen anstatt Fertigstellen

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#654]
ich bin der Meinung der Knopf müsste Übernehmen bzw. OK heißen. Mit Fertigstellen assoziere ich dass der Dialog komplett geschlossen wird.
![dialog](https://cloud.githubusercontent.com/assets/17204819/20328583/ced066b4-ab93-11e6-9313-91ad6c4ee16a.png)

**Comment by buchen** [comment]
Geändert
