### ISSUE TITLE
Flatex PDF Dokumente: Steuerrückerstattung bei Verlustgeschäften

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#657]
Hi @ZfT2, 

im [Wertpapier Forum](http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__1059107) gab es eine Rückmeldung zu dem Flatex PDF Importer. Ich habe jetzt noch nicht näher reingeschaut - hättest Du Zeit?

> Wohl noch ein Bug: Beim PDF-Einlesen eines Verkaufs bei Flatex errechnet PP einen komplett falschen Verkaufskurs, wenn es aufgrund eines Verlustgeschäftes eine Steuerrückerstattung gibt (als negativer Steuerbetrag von Flatex ausgewiesen, wird von PP aber ohne das Minus erfasst). In der Folge ist dann auch die ganze Renditeberechnung falsch.

**Comment by ZfT2** [comment]
Hallo Andreas,

ja gucke ich mir an, schaffe es aber wohl erst kommendes Wochenende. Gibt es den Import als Text-Extrakt?

**Comment by buchen** [comment]
Ich habe den Import nicht als Text. Ich habe nur den Kommentar aus dem Wertpapier Forum. Hast Du einen Account im WPF? Ansonsten kann ich mal nachfragen.

**Comment by ZfT2** [comment]
OK, ich frage da mal nach...

**Comment by ZfT2** [comment]
hab leider noch nicht richtig Zeit gefunden, aber mal kurz reingeguckt: Kann den Bug so bestätigen, es wird momentan der negative Betrag als Steuer und nicht als Steuererstattung interpretiert. Muss da noch ein wenig umbauen im Flatex Importer, um in so einem Fall den zum Wertpapier gehörigen Ertrag/Verlust zu reduzieren und eine zusätzliche Buchung mit der Steuererstattung anzulegen...

**Comment by buchen** [comment]
Kein Problem - ich bin auch total unter Wasser. Keine Ahnung wie häufig sowas auftritt.

**Comment by ZfT2** [comment]
Ich hab den Importer jetzt mal so erweitert, daß in so einem Fall eine zusätzliche Buchung vom Typ "Steuererstattung" erzeugt wird. (und der Ertrag am Wertpapier-Verkauf entsprechend reduziert wird, damit es unterm Strich passt.)
Generelle Frage hierzu: Steuern und Gebühren können ja auch direkt am Wertpapier-Verkauf erfasst werden, könnte man dies bei Steuererstattungen auch ermöglichen? Oder übersehe ich da jetzt gerade was?

Der PR folgt in Kürze :)

**Comment by buchen** [comment]
Cool. Der Weg ist auf jeden Fall eine separate Buchung vom Typ "Steuerrückerstattung" zu erstellen. Ich habe eine ähnliche Diskussion gerade wegen dem comdirect Importer.

> Generelle Frage hierzu: Steuern und Gebühren können ja auch direkt am Wertpapier-Verkauf erfasst werden, könnte man dies bei Steuererstattungen auch ermöglichen? Oder übersehe ich da jetzt gerade was?

Das könnte man natürlich ermöglichen. Das "Problem" ist nur, dass ich aktuell nur mit positiven Werten rechne. Die Steuerrückerstattung in der Verkaufsbuchung wäre dann ja ein negativer Wert. Und an keiner Stelle im Code wird das erwartet. Ich kann nicht sagen ob das irgendwo zu Seiteneffekten führt. Darum bin ich da etwas vorsichtig.

**Comment by cmaoling** [comment]
Für mich geht das in eine ähnliche Richtung wie die #666.
@buchen: Verstehe ich deine Sorge richtig, in den Datenstrukturen negative Zahlen zu verarbeiten?
Wir wäre es im Dialog die Möglichkeit zu geben per checkbox zwischen positiver und negativer Steuer bzw. Gebühr zu wählen. Dann würde mit ApplyChanges immer ein positiver Wert in die jeweilige Kategorie gebucht...

**Comment by ZfT2** [comment]
> Das "Problem" ist nur, dass ich aktuell nur mit positiven Werten rechne. Die Steuerrückerstattung in der Verkaufsbuchung wäre dann ja ein negativer Wert. 

Die Steuererstattung kann ja genauso gut als positiver Wert gespeichert und dargestellt werden, um einheitlich bei positiven Werten zu bleiben. Nur der Logik "innendrin" müsste dann beigebracht werden, das Einträge vom Typ Steuererstattung demVerkaufserlös hinzuaddiert werden (und nicht abgezogen wie Steuern und Gebühren.) Ich hab mir das aber zugegebenermaßen nicht näher angeschaut, es ist nur eine Überlegung, die mir beim Erweitern des Importers so kam...

> Wir wäre es im Dialog die Möglichkeit zu geben per checkbox zwischen positiver und negativer Steuer bzw. Gebühr zu wählen.

Ich denke, es wäre schon sinnvoll, den Typ "Steuer" und "Steuererstattung" speparat beizubehalten. Ich bin mir nicht sicher, ob sich Steuern und Erstattungen immer und überall bis aufs Vorzeichen gleich verhalten/verarbeiten lassen.

**Comment by ZfT2** [comment]
So, der PR wäre fertig :)
Ich habe noch in der bestehenden Datei
> name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/FlatexKauf.txt 
den Endbetrag angepasst, da diese Testdaten auch eine Steuererstattung enthalten. Dieses Beispiel ist nicht von mir gewesen, deshalb hab ich leider auch kein Original PDF dazu, aber das kann der Logik nach eigentlich nicht richtig gewesen sein... Es sei denn, Flatex hat da im Laufe der Zeit was geändert...
