### ISSUE TITLE
Minor UI Inconsistencies

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#658]
unter Konten taucht eine Dividende als Typ "Dividende" auf während bei Wertpapiere vom Typ "Dividenden" die Rede ist. Weiterhin sollte imho im Rechte-Maus-Kontextmenü "Dividende..." stehen, da eine einzelne Buchung eingetragen wird.
Der Dialog Kaufen & Verkaufen sollte ebenfalls entsprechend angepasst werden.
![benamung](https://cloud.githubusercontent.com/assets/17204819/20497616/1ac1a2f0-b02a-11e6-84f5-8d7bb6837bf6.png)

**Comment by buchen** [comment]
Fixed.
