### ISSUE TITLE
missing chart redraw nach Kauf

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#667]
beim Kauf über Performance / Wertpapiere wird der Chart **nicht** neu berechnet, beim Kauf über  Wertpapiere / Alle Wertpapiere schon.
![redraw](https://cloud.githubusercontent.com/assets/17204819/20862820/cadeeb7c-b9b5-11e6-8df7-11a7d69be42e.gif)
Ebenfalls könnte man sich überlegen ob nach dem Löschen eines Wertpapiers unter Alle Wertpapiere, das "nächstbeste" Wertpapier den Fokus erhält und dessen Chart angezeigt werden sollte; zZ passiert das nicht.

**Comment by buchen** [comment]
Fixed.
