### ISSUE TITLE
Klassifizierungen -> Asset Classes -> Filter

### ISSUE THREAD

**Issue by Beluk** [buchen/portfolio#669]
![image](https://cloud.githubusercontent.com/assets/10911904/20865710/19890596-ba1a-11e6-9c12-428a281fa748.png)

**Comment by buchen** [comment]
Grrr... Da ist was in der Datei kaputt.

Könntest Du die mir per Email (portfolio DOT Performance DOT help AT gmail DOT com) zukommen lassen? Ggf. alle Buchungen rauslöschen?

Das Problem tritt auf wenn Du das Menü "Filter" anklickst? Oder erst wenn man einen auswählt?
