### ISSUE TITLE
Kursgewinn % seit ...=infinity nach der Umbuchung von Wertpapieren aus Depot A nach Depot B

### ISSUE THREAD

**Issue by norgoe** [buchen/portfolio#672]
Das Problem betrifft Version 0.25.3 (mit anderen Versionen habe ich es nicht getestet).
Nach dem Umbuchen der Wertpapiere aus Depot A nach Depot B zeigt die Spalte "Kursgewinn % seit 30.5.2016" infinity.
Vor der Umbuchung zeigten die ETFs in Depot A noch normale Prozentzahlen in der Spalte.

In der Vermögensaufstellung funktioniert die Berechnung der Kursgewinne in Prozent auch nach der Umbuchung.

**Comment by buchen** [comment]
Hi @norgoe,

ich versuche das Problem gerade nachzuvollziehen.

Es geht um den Bericht "Performance" -> "Wertpapiere" und dann um die Spalte "Kursgewinn %". In der Beispieldatei habe ich eine Umbuchung von einem Depot in ein anderes vorgenommen, die Spalte Kursgewinn bleibt aber gleich. Das ist bei Dir aber anders?

<img width="487" alt="bildschirmfoto 2016-12-11 um 07 48 05" src="https://cloud.githubusercontent.com/assets/587976/21078629/357b0040-bf76-11e6-927b-3a34f6b63f46.png">

Vielleicht könntest Du mir einen Beispieldatei an *portfolio dot Performance dot help at gmail dot com* schicken? Einfach alle anderen Buchungen raus löschen bis auf dieses eine Wertpapiere.

**Comment by norgoe** [comment]
Hi @buchen,

deine Nachfrage zeigt mir, dass ich in meiner Fehlerbeschreibung zu ungenau war.
Nicht richtig angzeigt werden die Daten der übertragenen Wertpapiere bei mir in der Ansicht Stammdaten/Depots/Vermögensaustellung für das Depot in das die Papiere transferiert wurden. 
![portfolio-beispiel](https://cloud.githubusercontent.com/assets/6221132/21081081/4e92c966-bfbf-11e6-9113-2798fe2e21ff.png)

Richtig angezeigt werden die prozentualen Gewinne aber in Berichte/Vermögensaufstellung.

Ich schicke dir gleich meine komplette xml (einmal als Version vor dem Depotumzug und einmal die aktuelle Version mit den Anzeigefehlern). Ich vertraue einfach darauf das du die Daten nicht veröffentlichst, aber selbst wenn wäre das vermutlich nur ein Lehrbeispiel dafür wie man einige Investitionen lieber nicht tätigt ;)

**Comment by buchen** [comment]
Danke. Gefunden. 😄 

Im Code habe ich natürlich den passenden Kommentar gefunden... 😒 
```
        // FIXME create pseudo client --> transferals must add up
```
