### ISSUE TITLE
Rechtsklick-/Popup-Menü in KLASSIFIZIERUNG>...>REBALANCING um KAUFEN, VERKAUFEN etc. ergänzen

### ISSUE THREAD

**Issue by Lanhydrock** [buchen/portfolio#674]
Im Rechtsklick-/Popup-Menü auf ein Wertpapier in der Rebalancing-Ansicht (KLASSIFIZIERUNG>...>REBALANCING) würden uns die Einträge für KAUFEN, VERKAUFEN etc. sehr helfen (wie bspw. in der Ansicht WERTPAPIERE>ALLE WERTPAPIERE).

Momentan gibt es dort nur ENTFERNEN oder IM BROWSER ÖFFNEN.

Vielen Dank.

**Comment by buchen** [comment]
Guter Punkt. Das sollte überschaubar einfach sein.
