### ISSUE TITLE
DATEN EXPORTIEREN ermöglichen in KLASSIFIZIERUNG>...>REBALANCING

### ISSUE THREAD

**Issue by Lanhydrock** [buchen/portfolio#675]
Es wäre sehr hilfreich, wenn man die Rebalancing-Ansicht (entsprechend des gewählten Filters, bitte) in CSV exportieren könnte; so wie es bereits für BERICHTE>VERMÖGENSAUFSTELLUNG realisiert ist (das Symbol: Pfeil nach oben).

Dann könnte man in der Übergangszeit - bis #600 vielleicht einmal realisiert ist ;-) sich das ganze in Numbers/Excel/Open Office selbst nachbilden.

Vielen Dank.

**Comment by buchen** [comment]
Implementiert. Kommt mit der nächsten Version.
