### ISSUE TITLE
import from cvs / historical quotes table on web site

### ISSUE THREAD

**Issue by dlebrecht** [buchen/portfolio#676]
currrent support is for values on the format 0.000,00 and 0,000.00

could u add support for values on the format 0'000.00, such as here:

http://iyourmoney.shark2.rolotec.ch/yourmoney/hiku.html?listing=11262043%2C245%2C333&date_from=14.12.2011&date_to=

**Comment by buchen** [comment]
Sorry for the delay @dlebrecht.

I have added support for format. Come with the next version - I want to publish one early next year.
