### ISSUE TITLE
Graphische Kennzeichnung gehaltener Wertpapiere unter Berechnung

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#677]
Derzeit tauchen alle Positionen unter Berechnung/Kurserfolge alphabetisch sortiert auf.
Dabei wird nicht unterschieden zwischen gehalten und bereits verkauft.
Gerade für Vieltrader wäre sinnvoll wenn gehaltene Wertpapiere graphisch aufgewertet wären z.B. könnte die Farbe des Icons vor dem Asset-Name anders eingefärbt sein, für ein besseres visuelles feed-back.

**Comment by th23x** [comment]
Gute Idee, vielleicht könnte man das mit einer Unterscheidung zw. realisierten (verkauft) und rechnerischen (noch gehalten) Kurserfolgen in der Übersicht kombinieren?

(ich meine dazu mal ein "Issue" gesehen zu haben, finde es aber gerade nicht...)

**Comment by buchen** [comment]
> Farbe des Icons vor dem Asset-Name anders eingefärbt sein

Das ist eine gute (weil auch recht einfach umzusetzende) Idee. Klar, ich will eigentlich die Rechnung komplett umbauen und in realisierte und nicht-realsiebte Kurserfolge trennen (siehe #228). Aber an die Information welche Wertpapiere gehalten werden und welche nicht sollte ich recht einfach dran kommen können.

**Comment by buchen** [comment]
Ich habe das mal implementiert. Kommt mit der nächsten Version.

<img width="459" alt="bildschirmfoto 2016-12-17 um 07 26 50" src="https://cloud.githubusercontent.com/assets/587976/21284930/62fafe90-c42a-11e6-8514-3b694945fd61.png">

Es ist klar, dass das etwas rudimentär ist. Wenn man nur eine Teilposition verkauft hat, dann kann das natürlich eine Kombination von realisierten und nicht-realisierten Erfolgen sein, trotzdem wird das Wertpapier als "gehalten" angezeigt.
