### ISSUE TITLE
Bestand Filter Verbesserung via logical NOT

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#678]
Derzeit kann Bestand > 0 und Bestand = 0 angehackt werden, was zurfolge hat, dass nichts angezeigt wird.
Normalerweise sind _entweder_ die gehaltenen _oder_ die verkaufen Papiere interessant, _oder beide_ (nichts angehackt), die Anzeige einer leerer Tabelle ist wohl in den seltensten Fällen gewünscht.
![bestand](https://cloud.githubusercontent.com/assets/17204819/21368139/82e4d288-c701-11e6-80f9-6fa88ce8bb75.png)
Beides gleichzeitig sollte denke ich nicht angehackt werden können.

**Comment by buchen** [comment]
Das stimmt. Das ist unlogisch. Meine Überlegung war in Zukunft noch weitere Filtermöglichkeiten hinzuzufügen. Und darum wollte ich die Logik hinreichend einfach halten. Wenn ich da jetzt einen Radio Button einbaue, dann gilt das beim nächsten Filter nicht mehr. Und trotzdem kann ich mehrere Filter aktivieren und nachher bleibt die Liste leer.

Ganz kurzfristig werde ich da jetzt nichts ändern - mir ist es der Aufwand gerade nicht wert. Wenn ich neue Filter hinzufüge, dann muss ich mir das aber wieder neu überlegen.
