### ISSUE TITLE
PDF-Import Dividendenzahlungen ING-Diba

### ISSUE THREAD

**Issue by sheepherder** [buchen/portfolio#679]
Hallo,

grossartiges Programm. Leider funktioniert der Import von PDF-Dateien der ING-Diba bei mir zwar für Ertragsgutschriften von ETFs, nicht aber bei Dividendenzahlungen von Einzelaktien. An den Code habe ich mich zwar herangetraut, bin aber gescheitert. Ich würde mich super freuen, wenn die PDFs der ING-Diba alle funktionieren würden - anbei ein Debug-Text einer aktuellen Dividendenzahlung, die nicht erkannt wird.
[Dividende McD.txt](https://github.com/buchen/portfolio/files/667256/Dividende.McD.txt)

**Comment by buchen** [comment]
Danke @sheepherder für das Beispiel. Ich habe jetzt Support für die Dividendengutschrift hinzugefügt.  Ich denke ich werde direkt Anfang nächsten Jahres eine neue Version veröffentlichen. Oder Du startest die Version lokal

**Comment by sheepherder** [comment]
Wow, das ging schnell! Anbei noch zwei Beispiele für den Kauf bzw. Verkauf von Einzelaktien. Damit sollten 90% der Fälle bei ING-Diba abgedeckt sein (ETF geht ja schon länger).
[Abrechnung Verkauf.txt](https://github.com/buchen/portfolio/files/688801/Abrechnung.Verkauf.txt)
[Abrechnung Kauf.txt](https://github.com/buchen/portfolio/files/688802/Abrechnung.Kauf.txt)
