### ISSUE TITLE
PDF-Import Flatex Kauf Zertifikat/Fond Änderung

### ISSUE THREAD

**Issue by CannyDuck** [buchen/portfolio#680]
So wie es aussieht, hat sich das Format der PDFs für den Kauf von Zertifikaten/Fonds im Dezember geändert. Die Dokumente aus dem November funktionieren ohne Probleme.

![Screen](https://cloud.githubusercontent.com/assets/1655493/21437129/6ec34ff0-c882-11e6-827d-037a70cadeb1.png)

**Comment by buchen** [comment]
Hi @CannyDuck - da ich selber nicht Kunde von Flatex bin, brauche ich ein Beispiel für das PDF Dokument. Das Beispiel kann man über *Datei -> Importieren -> Debug: Text aus PDF extrahieren...* generieren, die persönlichen Daten löschen und dann per Email an *portfolio dot Performance dot help at gmail dot com* schicken.

**Comment by buchen** [comment]
Danke für das Beispiel. Sollte jetzt tun. Anfang des Jahres werde ich eine neue Version veröffentlichen.

Wenn Du vorher einen Build brauchst, muss ich wissen welches OS und Bit.
