### ISSUE TITLE
Tests are failing when trying to build in a docker container

### ISSUE THREAD

**Issue by cmaoling** [buchen/portfolio#682]
Hi,

very interesting project.
I am trying to get a development environment up and running.
(FYI: I am doing his w/in a docker container for convenience but suspect, that this is the issue)
Unfortunally I get the following errors when running "mvn clean install" or "mvn clean install -Dgenerate-target-platform=true".

Results :

Tests in error: 
  OnvistaPDFExtractorTest.testErtragsgutschriftErtr?gnisgutschrift2:453->access$0:1254->from:1256 ? NullPointer
  OnvistaPDFExtractorTest.testErtragsgutschriftErtr?gnisgutschrift:418->access$0:1254->from:1256 ? NullPointer
  OnvistaPDFExtractorTest.testWertpapier?bertrag:643->access$0:1254->from:1256 ? NullPointer
  OnvistaPDFExtractorTest.testKapitalerh?hung:795->access$0:1254->from:1256 ? NullPointer

Tests run: 320, Failures: 0, Errors: 4, Skipped: 0

My supposition would be, that the "Umlauts" are causing the issue.
Any advise or previous knowledge.

Thanks
cmaoling

**Comment by buchen** [comment]
Ich vermute das hat sich jetzt erledigt, oder?

**Comment by cmaoling** [comment]
Yep, given that you pulled my change into masters, I am fine to have it closed...
