### ISSUE TITLE
Erfassung von Dividenden vereinfachen

### ISSUE THREAD

**Issue by buchen** [buchen/portfolio#691]
* Nach Eingabe einer Dividendenbuchung wird die Zeile in "Performance" -> "Wertpapiere" deselektiert, darum wird die Liste der Umsätze leer. Man sieht nicht mehr was man eingegeben hat.

* Wenn man nur ein Konto hat, sollte das auch im Dividendendialog torselektiert sein (wenn man aus Performance -> Wertpapiere die Dividende anlegt).

**Comment by cmaoling** [comment]
Meines Erachtens ist der erste Punkt verwandt mit dem in #667 beschriebenen Verhalten.
Es erfolgt nach meiner Recherche immer  eine Deselektion in der SecurityPerformanceView das ist im SecurityListView anders.
Deshalb wird nach der Eingabe eines Kaufs, Verkaufs oder einer Dividende die Chart auch nicht aktualisiert. Die "Security" geht verloren...
Zu Beachten ist hier auch, daß im Dialog das Wertpapier geändert werden kann. Ich würde davon ausgehen, daß dann das gewählte im Anschluß ausgewählt sein sollte...

FYI: Der zweite Punkt ist mir auch aufgefallen und wollte ich mir bei Gelegenheit mal anschauen.

**Comment by buchen** [comment]
Vielen Dank für den Hinweis auf #667 - das ist in der Tat das selbe Problem.

In dem TableViewer "leben" SecurityPerformanceRecord Objekte. Bei jeder Änderung werden die neu berechnet. Und darum fällt auch die Selektion wieder weg. Ich merke mir jetzt die selektierten Wertpapiere und such anschließend die SecurityPerformanceRecord Objekte für diese Wertpapiere wieder raus.
