### ISSUE TITLE
Historische Kurse in Fremdwährung nach manchen Programmstarts fehlerhaft

### ISSUE THREAD

**Issue by michaellass** [buchen/portfolio#701]
Nach manchen Programmstarts stimmen die historischen EUR-Kurse von Wertpapieren nicht, deren Daten in USD vorliegen. Statt dem tatsächlichen Wechselkurs an dem entsprechenden Tag wird stattdessen scheinbar der aktuelle Wechselkurs genutzt um den historischen EUR-Kurs zu berechnen. Dies hat natürlich Auswirkungen auf die Berechnung von Performance und Volatilität.

Ein Beispiel: Das Portfolio enthält 1oz Gold. Am 9.5.2016 war diese 1264,09 USD wert. Der entsprechende EUR-Kurs für den Tag lautet im Programm nun manchmal 1109,34 EUR (korrekt, da der Wechselkurs an dem Tag 1,139 betrug) und manchmal 1203,55 (offensichtlich nach einem deutlich aktuelleren Wechselkurs in der Gegend um 1,05).

Das Problem tritt manchmal beinahe nach jedem Programmstart auf, und manchmal lässt es sich nur schwer reproduzieren. Vielleicht gibt es hier zeitweise Probleme beim Abruf der Daten?

**Comment by michaellass** [comment]
Ich habe doch noch etwas gefunden, das das Problem beeinflusst: Schließt man die Datei vorm Beenden des Programms, sodass das Programm beim nächsten mal ohne geöffnetes Portfolio startet, tritt das Problem nicht auf, sondern nur, wenn direkt mit dem Programmstart auch das Portfolio geöffnet wird.

**Comment by buchen** [comment]
Das ist ein guter Hinweis. Die Logik ist momentan so: erstens gibt es hartkodierte Wechselkurse, damit PP immer einen hat. Dann werden die Kurse von der Platte geladen. Dann wird nach neue Wechselkursen geschaut. Vielleicht fehlt der "Event" wenn die Wechselkurse geladen sind, dann auch die Berechnung noch mal zu aktualisieren?!?

**Comment by michaellass** [comment]
Der Fehler scheint in Version 0.26.1 behoben zu sein. Danke! :+1:
Falls er noch einmal auftreten sollte, melde ich mich wieder.
