### ISSUE TITLE
Import ING Diba - Erweiterung

### ISSUE THREAD

**Issue by waltapeka** [buchen/portfolio#706]
Hallo Andreas,

am Ende und Anfang eines Jahres erscheinen immer mehr Anfragen hattest du ja im Finanzrocker Interview erzählt. Von daher noch eine kleine Bitte um Ergänzung des PDF Imports der ING-Diba. Einige Dividendenimporte funktionieren noch nicht. Das Beispiel ist anbei.

Ansonsten einfach nur Daumen hoch für dieses Stück Software!
[dividendeFonds.txt](https://github.com/buchen/portfolio/files/709091/dividendeFonds.txt)

Viele Grüße,
Dennis

**Comment by buchen** [comment]
Hallo @waltapeka, das ist eine Ertragsthesausrierung. Das wird von PP nicht unterstützt. Die ausgeschüttete Dividende wird ja direkt wieder angelegt. Meines Wissens ändern sich dadurch ja nicht die gehaltenen Anteile, sondern es erhöht sich entsprechend der Kurs. Damit ist das auch in der Performance drin.
