### ISSUE TITLE
Regionaleinstellungen Schweiz

### ISSUE THREAD

**Issue by songohan** [buchen/portfolio#711]
Sehr schönes Produkt, ich nutze es täglich, vielen Dank dafür.

Was mich aber sehr stört ist, dass das Dezimaltrennzeichen und das Tausendertrennzeichen wohl hardcoded ist. Dies sollte sich aber an den Regionaleinstellungen vom Windows orientieren.
Ich möchte nämlich gerne wie bei uns üblich den Punkt als Dezimaltrennzeichen, und das einfache Hochkomma als Tausendertrennzeichen.
Schliesslich habe ich den Punkt auch auf dem Ziffernblock (CH-Layout). Dies würde die Eingabe massiv erleichtern.

Besten Dank
Grüsse
jensni

**Comment by buchen** [comment]
Eigentlich sollte es nicht hartkodiert sein. Ich habe PP gerade mal mit der Locale de_CH gestartet. Da sieht es erst mal wie erwartet aus:

<img width="670" alt="bildschirmfoto 2017-01-27 um 23 01 43" src="https://cloud.githubusercontent.com/assets/587976/22389205/a365a5b8-e4e4-11e6-9db8-84469f43364e.png">

Du könntest mal versuchen, in die configration/config.ini Datei die Lokale explizit zu setzen:
```
osgi.nl=de_CH
```

**Comment by songohan** [comment]
Super vielen Dank, so funktionierts!
Bei mir ist vielleicht speziell, dass ich das Windows auf Englisch installiert habe, die Regionaleinstellungen aber auf "Deutsch (Schweiz)" sind.

Viele Grüsse
Jensni
