### ISSUE TITLE
Zu wenige Nachkommastellen bei der Stückzahl

### ISSUE THREAD

**Issue by uranobody** [buchen/portfolio#712]
Hallo leider kann ich nur 3 Nachkommastellen bei der Stückzahl eingeben.

Bei Onvista werden ETF Sparpläne aber mit 4 Nachkommastellen ausgeführt also z.B.
Kauf von 2,3781 Stück zum Kurs von 42,0500

Es wäre schön wenn man dies ändern könnte :)

Gruß Uranobody

**Comment by buchen** [comment]
Angezeigt werden in den Spalten nur drei Nachkommastellen, aber man kann bis zu 5 erfassen.

<img width="245" alt="bildschirmfoto 2017-02-04 um 08 03 42" src="https://cloud.githubusercontent.com/assets/587976/22616615/7bb272b8-eab0-11e6-9b55-51ad0765757b.png">
