### ISSUE TITLE
Fehler bei Währungen?

### ISSUE THREAD

**Issue by Garve** [buchen/portfolio#714]
Hi!

Ich habe Intel in Euro eingestellt, zu 33,5€ gekauft. Nun zeigt PP an, dass es schon bei 36,5€ ist, jedoch ist es im Moment bei 34€, was aber ca. 36,5$ entspricht. Gibt es da einen Umrechnungsfehler?

**Comment by buchen** [comment]
Unter "Eintsellungen" -> "Währungen" siehst Du die Wechselkurse, die angewandt werden.

Ansonsten würde mir eine Beispieldatei helfen um nachrechnen zu können.

**Comment by Garve** [comment]
Ah, ich war nur dumm, sorry. Hatte nicht "Intel Corp", sondern nur "Intel", was anscheinend etwas anderes ist.
