### ISSUE TITLE
Maven dependency kann nicht aufgelöst werden

### ISSUE THREAD

**Issue by mcfly83** [buchen/portfolio#715]
Wenn ich versuche, das (frisch geforkte und unveränderte) Projekt lokal zu bauen, bricht der Vorgang mit folgender Meldung ab:
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: name.abuchen.portfolio 0.26.3.qualifier
[ERROR]   Missing requirement: name.abuchen.portfolio 0.26.3.qualifier requires 'package org.apache.pdfbox.pdmodel 1.8.7' but it could not be found

In portfolio-app wird Version 1.8.8 der Library als Dependency angegeben. Ich bin aber leider kein Maven-Experte, daher weiß ich nicht, wie ich den Fehler behebe. Da der CI-Build durchläuft, muss das Problem ja irgendwo bei mir liegen...

**Comment by buchen** [comment]
In portfolio-app wird 1.8.8 angegeben und im OSGI Manifest steht, dass mindestens Version 1.8.7 gebraucht wird. Das ist an sich noch nicht problematisch.

Mit welcher Maven Version baust Du? Ich nutze lokal 3.3.9

**Comment by mcfly83** [comment]
Ich verwende ebenfalls Version 3.3.9.

**Comment by buchen** [comment]
Füge doch mal ein Attachment des ganzen Logs ein. Mir scheint da geht vorher schon was schief.

**Comment by mcfly83** [comment]
Jetzt funktioniert es... sehr komisch. Ich habe das lokale Maven-Repository noch mal komplett geleert und nun läuft der Build auch durch. 
Trotzdem danke für die Hilfe!
