### ISSUE TITLE
0.26.2 - Asset Allocation wird nicht gerendert

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#716]
Version 0.26.2
Kubuntu 14.04.2 LTS
WindowMaker 0.95.5
Gestartet mit
"--launcher.GTK_version
2" da GTK 3 zu Abstürzen führt.
(GTK 1 oder 3 ändern für das hier beschriebene Problem nichts.)

Die Asset Allocation rendert die Einträge nicht mehr und zeigt nur noch die Spalte "IST Wert" an. Allerdings sehe ich nun in der Vermögensaufstellung auf einmal wieder die Zahlen in der Spalte "Bestand", die vorher nicht zu sehen waren.
Im Fehlerprotokoll ist dazu nichts zu sehen. Die Plausibilitätsprüfung zeigt auch keine Probleme.
![portfolio performance _048](https://cloud.githubusercontent.com/assets/25621029/22709845/919e58b2-ed7b-11e6-9f18-b41799487ea5.png)

![portfolio performance _049](https://cloud.githubusercontent.com/assets/25621029/22709760/3c80d1ac-ed7b-11e6-97fe-fe510959aa05.png)

**Comment by buchen** [comment]
Ich schaue mir das mal in meiner Linux VM an - allerdings habe ich da Ubuntu 16.04

> Allerdings sehe ich nun in der Vermögensaufstellung auf einmal wieder die Zahlen in der Spalte "Bestand", die vorher nicht zu sehen waren.

Die Spalte "Bestand" ist besonders, weil extra gerendert wird (ich will nicht alle Nachkommastellen anzeigen und ich will überhaupt keine Nachkommastellen sehen wenn es keine Bruchstücke gibt, trotzdem muss der Wert korrekt eingerückt sein). Da scheint es unter Linux wohl mal wieder Probleme zu gegeben 😒

**Comment by yetipenguin** [comment]
Ich konnte mir nun dadurch behelfen, dass ich die Asset Allocation gelöscht und wieder angelegt hab. 

Jetzt kann ich das Problem nochmal genauer eingrenzen:
Es wird nur die Rebalancing-Ansicht nicht gerendert und zwar für die Asset Classes und für die Asset Allocation. Auch hier wieder kein Unterschied ob mit GTK 2 oder 3.

**Comment by buchen** [comment]
Zumindest auf Ubuntu 16.04 sieht es erst mal nicht so schlecht aus.

<img width="981" alt="bildschirmfoto 2017-02-11 um 14 44 11" src="https://cloud.githubusercontent.com/assets/587976/22854180/9900188a-f068-11e6-9602-417b1c908cb7.png">

**Comment by yetipenguin** [comment]
Kann das Problem mit 0.28.1 nicht mehr reproduzieren, daher schließe ich den Bug.
