### ISSUE TITLE
Performancegraf fehlerhaft?

### ISSUE THREAD

**Issue by Garve** [buchen/portfolio#718]
Hi nochmal!

Ich glaube, irgendwas stimmt mit dem Grafen nicht. Mein Depot geht seit 2 Tagen nach oben laut meinem Broker, der Graf in PortfolioPerformance geht jedoch seit 2 Tagen runter, obwohl alle Aktien richtig erfasst sind. Kann das jemand bestätigen?

**Comment by yetipenguin** [comment]
Welcher Datenlieferant ist denn ausgewählt? Stimmt denn der Wert "Kursgewinn" in Zahlen unter "Perfomance"? Mir ist so ein Verhalten noch nicht untergekommen ...

**Comment by Garve** [comment]
Vielleicht liegt es daran, dass die täglichen Schwankungen in PP stark von denen auf den Börsenseiten abweichen kann. Hier mal ein Beispiel: 
![pp](https://cloud.githubusercontent.com/assets/932327/22843952/2623959e-efdc-11e6-8818-f61e8ce8e290.png)

Eigentlich ist Target um 1% gefallen, PP denkt aber, es sei um 2% gestiegen. Wie kommt das?

**Comment by buchen** [comment]
> Eigentlich ist Target um 1% gefallen, PP denkt aber, es sei um 3% gestiegen. Wie kommt das? Können das Währungseffekte sein, oder etwas anderes?

Um das beantworten zu können, braucht es mehr Informationen.

Die aktuellen Kurse kann PP nicht aus einer Webseite extrahieren. Wenn man eine URL angibt, dann wird nach einer Tabelle gesucht die mindestens die Spalten "Kurs" und "Datum" hat.

Schaue mal unter "Alle Wertpapiere" -> "Wertpapier" -> Tab "Historische Kurse". Dort siehst Du mit welchen Kursen gerechnet wird.

**Comment by Garve** [comment]
Ok, es liegt wohl daran, dass jeweils der aktuelle Tag falsch berechnet oder angezeigt wird. Mein Depot ging gestern zum Beispiel wieder nach oben laut meinem Broker. In PP fiel der Graph aber. Als ich heute geschaut habe, war der Graph dann aber doch korrekt, d.h. der Gewinn gestern war höher als vor 2 Tagen. Im Moment wieder das gleiche Spiel: eigentlich ging es nach oben, der Graph in PP geht nach unten. Mal schauen, ob das dann morgen wieder richtig ist, sofern mein Kapital nicht gerade wirklich fällt.

**Comment by buchen** [comment]
Wenn Du keinen aktuellen Kurse von Yahoo hast, dann stehen PP nur die historischen Kurse zur Verfügung. Dadurch könnte die Verzögerung von einem Tag entstehen.
