### ISSUE TITLE
Import von Verkaufsorder Deutsche Bank hat falsche Gebühren

### ISSUE THREAD

**Issue by hjbflyer** [buchen/portfolio#723]
Im Gegensatz zum Kauf werden beim Verkauf die Provision und die fremden Gebühren nicht
berücksichtigt. Durch einen falschen Stückpreis wird die Buchung zwar betragsmäßig richtig angelegt, die Gebühren sind aber total falsch.

**Comment by buchen** [comment]
Kann ich mir anschauen. Mir würde aber trotzdem ein Beispiel helfen. Könntest Du eines hier posten? Ansonsten bin ich gerade zwei Wochen beruflich in Indien - da komme ich zu nicht viel...

**Comment by hjbflyer** [comment]
Ich habe eine Datei angefügt.

Viel Spaß in Indien.

[VerkaufDB.txt](https://github.com/buchen/portfolio/files/792903/VerkaufDB.txt)

**Comment by hjbflyer** [comment]
Ich glaube ich habe die Fehler gefunden.
    1. Die Provisionsangabe enthält einen Prozentsatz. Deshalb muss noch ein Pattern zwischen Provision und Currency eingefügt werden. Man kann einfach ein .* verwenden oder detailliertes Pattern für '(x,xx %)'. Was ist Dir lieber?
   2. Es fehlt ein Pattern für "Fremde Spesen und Auslagen"

**Comment by hjbflyer** [comment]
Habe die Fehler beseitigt und werde einen Pull-Request Incl. Test einstellen.

**Comment by buchen** [comment]
merket. Danke!
