### ISSUE TITLE
Historische Kurse über Yahoo funktionieren nicht mehr

### ISSUE THREAD

**Issue by bgo82** [buchen/portfolio#734]
Der HTTP-Request zum Laden der historischen Kurse aus dem Programm führt zu einer  "HTTP/1.1 301 Moved Permanently" Response.

Yahoo hat anscheinend für die historischen Daten auf https umgestellt. 

### Request:

> Hypertext Transfer Protocol
>     GET /table.csv?ignore=.csv&s=EMR&a=3&b=13&c=2017&d=3&e=20&f=2017&g=d HTTP/1.1\r\n
>     User-Agent: Java/1.8.0_71\r\n
>     Host: ichart.finance.yahoo.com\r\n
>     Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\n
>     Connection: keep-alive\r\n
>     \r\n
>     [Full request URI: http://ichart.finance.yahoo.com/table.csv?ignore=.csv&s=EMR&a=3&b=13&c=2017&d=3&e=20&f=2017&g=d]
>     [HTTP request 1/1]
>     [Response in frame: 3037]

### Response

> Hypertext Transfer Protocol
>     HTTP/1.1 301 Moved Permanently\r\n
>         [Expert Info (Chat/Sequence): HTTP/1.1 301 Moved Permanently\r\n]
>             [HTTP/1.1 301 Moved Permanently\r\n]
>             [Severity level: Chat]
>             [Group: Sequence]
>         Request Version: HTTP/1.1
>         Status Code: 301
>         Response Phrase: Moved Permanently
>     Date: Thu, 20 Apr 2017 15:37:29 GMT\r\n
>     Via: http/1.1 media-router31.prod.media.ir2.yahoo.com (ApacheTrafficServer [c s f ]), http/1.1 e22.ycpi.amb.yahoo.com (ApacheTrafficServer [cMsSfW])\r\n
>     Server: ATS\r\n
>     Location: https://ichart.finance.yahoo.com/table.csv?ignore=.csv&s=EMR&a=3&b=13&c=2017&d=3&e=20&f=2017&g=d\r\n
>     Content-Length: 0\r\n
>         [Content length: 0]
>     Age: 0\r\n
>     Connection: keep-alive\r\n
>     \r\n
>     [HTTP response 1/1]
>     [Time since request: 0.097806000 seconds]
>     [Request in frame: 3008]

**Comment by 3mg4** [comment]
Angeblich liegt es nicht nur an https, im WPF gibt es den User Santander, der berichtet es geht mit seinem Crawler auch über http 

[LINK ZUM BEITRAG ](https://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/?page=105#comment-1085319)

**Comment by buchen** [comment]
Wenn es nur um HTTPS geht, dann kann ich das schnell ändern. Ich denke ich komme da heute Abend oder morgen früh dazu.

**Comment by DominikHolzapfel** [comment]
Mit dem neusten Release geht das bei mir wieder. Kann dann vermutlich geschlossen werden?
