### ISSUE TITLE
mehr als 5 GLOBALE FILTER erlauben

### ISSUE THREAD

**Issue by Lanhydrock** [buchen/portfolio#738]
Eben - leider ;-) festgestellt, dass momentan nur 5 globale Filter in den Ansichten erlaubt werden. Existieren schon fünf, wird bei Neuanlage einer der alten Filter gelöscht.

Das ist unschön, wir brauchen leider mehr als fünf, da wir mittlerweile für vier Personen aus unserer Familie getrennte Portfolios (in *einer* Datei) verwalten und wir so mehr als fünf individuelle Konto/Depot-Kombinationen benötigen.

Es wäre daher sehr schön, wenn die Begrenzung aufgehoben werden könnte. -

Vielen Dank fürs In-Betracht-Ziehen und vielen Dank für PortfolioPerformance überhaupt.

**Comment by buchen** [comment]
Die maximale Anzahl der Filter kann ich leicht ändern - sagen wir auf 10. Kommt mit der nächsten Version.

Eine unbegrenzte Anzahl setzt voraus, dass man die irgendwie auch wieder löschen kann. Dazu habe ich momentan keine Zeit.

**Comment by Lanhydrock** [comment]
Ich traue mich ja kaum es zu sagen, aber meine Frau hat nun auch ihr eigenes Depot eröffnet. Auch dieses wollen wir mit PortfolioPerformance in einer einzigen Datei verwalten; damit sind wir bei fünf Personen. 

Daher reichen die 10 möglichen globalen Filter leider nunmehr auch nicht mehr aus. Wir bräuchten aktuell (wegen der verschiedenen Kombinationen Festgeld, Tagesgeld, Depot mit mehreren entsprechenden Konten sowie für mehrere Personen und einzeln, und jeweils angewendet/benutzt im Dashboard) mindestens 12...

Wir möchten uns daher leise und freundlich erkundigen, 
- ob Du die Begrenzung nochmals ein wenig hoch setzen könntest (20), oder gar
- ob Du die Begrenzung ganz rausnehmen könntest.

@buchen Deinem Argument oben:

> Eine unbegrenzte Anzahl setzt voraus, dass man die irgendwie auch wieder löschen kann. Dazu habe ich momentan keine Zeit.

möchten wir konstruktiv entgegensetzen, dass es doch auch jetzt schon die ALLE FILTER LÖSCHEN Funktion gibt. 

Vielen Dank fürs In-Betracht-Ziehen und vielen Dank für PortfolioPerformance überhaupt.

**Comment by buchen** [comment]
> möchten wir konstruktiv entgegensetzen, dass es doch auch jetzt schon die ALLE FILTER LÖSCHEN Funktion gibt.

Das ist natürlich ein Argument... 😄

**Comment by buchen** [comment]
Ich komme vor meinem Urlaub nicht mehr dazu eine Version zu veröffentlichen. Hier eine mit 30 Filtern: https://www.dropbox.com/s/9210w2bt2kus4zg/PortfolioPerformance-0.27.4-SNAPSHOT-macosx.cocoa.x86_64.tar.gz?dl=0

**Comment by Lanhydrock** [comment]
Hallo Andreas, 

(offtopic:) Wünsche Dir einen supererholsamen schönen Urlaub!

Vielen Dank für die rasante Realisierung! Und vielen Dank für PortfolioPerformance überhaupt!
