### ISSUE TITLE
Export überschreibt existierende Datei ohne Rückfrage

### ISSUE THREAD

**Issue by Lanhydrock** [buchen/portfolio#739]
Export einer Klassifikation via DATEN EXPORTIEREN überschreibt ungefragt eine existierende Datei gleichen Namens auf der Festplatte.

Es wäre schön (und sicherer), gäbe es hier vorher eine Rückfrage.

Vielen Dank fürs In-Betracht-Ziehen und vielen Dank für PortfolioPerformance überhaupt.

**Comment by Lanhydrock** [comment]
v 0.27.1
Anm.: Der Export der Rebalancing-Ansicht einer Klassifikation überschreibt mit diesem Commit aber weiterhin ohne Rückfrage.

Vielen Dank für PortfolioPerformance überhaupt.

**Comment by DominikHolzapfel** [comment]
Die Änderung wurde in den Code eingebaut, ist aber im letzten Release noch nicht vorhanden.
Mit der nächsten Version sollte das dann drin sein.
Siehe https://github.com/buchen/portfolio/pull/748#issuecomment-302960099
