### ISSUE TITLE
Kurse für UBSG.VX werden falsch von Yahoo geladen

### ISSUE THREAD

**Issue by ms5** [buchen/portfolio#741]
Hi

Mir ist heute aufgefallen, dass beim versuche die Kurse der UBS Group via Yahoo zu laden, falsche werte ins PP importiert werden. 

Wie habe ich getestet:
Im PP Wertpapier erfasst:
> symbol: UBSG.VX
> Historische Kurse: 
>> Provider: Yahoo Finance
>> Exchange: VX (UBSG.VX)

Ich erhalte immer den Kurs 17.35 (für jeden Tag)

Zum Vergleich auf Yahoo Finance (Webseite) erhalte ich die korrekten Kurse mit der folgenden URL: 
https://de.finance.yahoo.com/quote/UBSG.VX?ltr=1

**Comment by sunnylars** [comment]
Hallo,
ich habe mir das mal angeschaut, das ist aber an der Stelle ein Fehler von Yahoo.

Die Url passt, aber das csv beinhaltet tatsächlich nur den Kurs 17.35 für jeden Tag.

https://ichart.finance.yahoo.com/table.csv?ignore=.csv&s=UBSG.VX&a=2&b=11&c=2017&d=4&e=11&f=2017&g=d

**Comment by buchen** [comment]
@sunnylars  - Vielen Dank!
