### ISSUE TITLE
xml is marked as changed right after opening

### ISSUE THREAD

**Issue by Yky** [buchen/portfolio#744]
When opening an xml the tab has a * next to it immediately as though it were changed, even though no changes have been made. 

Expected: * only appears when actual changes have been made and thus there is no prompt for saving when only opening and closing the xml

macOS 10.12.4, portfolio performance Version 0.26.5

Possibly related with #717 ?

**Comment by cmaoling** [comment]
Na assumtpion for thus behavior is zur Update of Quotes. Do You see a * indication when the uodat of Quotes has been disabled?

**Comment by buchen** [comment]
Der Stern kann verschiedene Gründe haben:
* Kurse wurden aktualisiert
* eine Ansicht hat Einstellungen (Spaltenbreiten, etc.) die gespeichert werden

Wenn brauche ich mehr Informationen:
* passiert das auch wenn man die Kurse vollständig aktualisiert, dann speichert, und schließt und sofort wieder öffnet?
* Welche Ansicht ist aktive und wird beim Öffnen angezeigt?

**Comment by Yky** [comment]
> 
    passiert das auch wenn man die Kurse vollständig aktualisiert, dann speichert, und schließt und sofort wieder öffnet?

nein

>     Welche Ansicht ist aktive und wird beim Öffnen angezeigt?
Vermögensaufstellung

**Comment by buchen** [comment]
Das liest sich für mich aber so, als wird der "*" angezeigt weil direkt nach dem Öffnen die Kurse aktualisiert werden (und es neue Kurse gibt).
