### ISSUE TITLE
0.27.0 (OSX) - Dividentenzahlung kann nicht gespeichert werden

### ISSUE THREAD

**Issue by hellomarb** [buchen/portfolio#749]
Seit dem Update 0.27.0 kann ich unter OSX keine neue Dividentenzahlung mehr speichern.
Ein Klick auf "Speichern" löst leider keine Aktion aus, das Fenster bleibt unverändert.

**Comment by buchen** [comment]
Grrrr..... fixe ich.

**Comment by buchen** [comment]
Ist jetzt gefixt.
