### ISSUE TITLE
Bug? 0.27.1 berücksichtigt bei FILTER kein KONTO mehr in der Ansicht Rebalancing einer KLASSIFIZIERUNG

### ISSUE THREAD

**Issue by Lanhydrock** [buchen/portfolio#750]
Hallo,

in unserer Datei werden seit Update auf 0.27.1 keine Bestände aus Konten mehr in der Rebalancing Ansicht einer Klassifizierung berücksichtigt, sobald ein Filter eingesetzt wird. Istbestand ist immer 0, obwohl Geld auf dem Konto vorhanden ist und auch im Bericht VERMÖGENSAUFSTELLUNG (derselbe Filter) angezeigt wird.

Die Bestände aus Depots sind korrekt.
 
Dies passiert bei Standardfiltern (Depot + Konto) und selbstdefinierten globalen Filtern.

Liegt das an unserer Datei? Oder habt Ihr das auch?

Vielen Dank fürs Kontrollieren und vielen Dank für PortfolioPerformance überhaupt.

**Comment by buchen** [comment]
Ja Bug 😒 

Habe ich behoben - welche OS Version brauchst? Dann baue ich ein schnelles Update.

**Comment by Lanhydrock** [comment]
Hier werkelt 10.12.5... aber nur wenn's Dir zeitlich passt. Nächstes Rebalancing ist nämlich für Dienstag geplant... ;-)

Vielen Dank fürs Korrigieren und vielen Dank für PortfolioPerformance überhaupt.

**Comment by Lanhydrock** [comment]
@buchen Könnt Ihr schon absehen, wann Ihr eine neue Version pusht? Ich hätte Termine für Rebalancing in vier Portfolios am nächsten Dienstag und würde mir sonst am Wochenende eine Übergangslösung überlegen/programmieren... ;-) Danke.

Vielen Dank fürs Korrigieren und vielen Dank für PortfolioPerformance überhaupt.

**Comment by buchen** [comment]
Du brauchst die Mac Version, oder?

**Comment by buchen** [comment]
https://www.dropbox.com/s/j12fm2eki29y0ne/PortfolioPerformance-0.27.2-SNAPSHOT-macosx.cocoa.x86_64.tar.gz?dl=0

**Comment by Lanhydrock** [comment]
@buchen Guten Morgen und VIELEN Dank! macOS ist richtig.

**Comment by Lanhydrock** [comment]
@buchen Aaaaarggghh, ahem, Dad vergessen, der hats aus Sicherheitsgründen in der 64bit *nix Version unter Virtualbox laufen. Hättest Du das auch im Angebot? Merci....

**Comment by buchen** [comment]
64bit unix https://www.dropbox.com/s/m6vvoegoon0sncr/PortfolioPerformance-0.27.2-SNAPSHOT-linux.gtk.x86_64.tar.gz?dl=0

**Comment by Lanhydrock** [comment]
@buchen Merci auch dafür...
