### ISSUE TITLE
Die Version 0.27.1 startet nicht auf dem Mac.

### ISSUE THREAD

**Issue by mirkoebert** [buchen/portfolio#754]
Es gibt von OS die Fehlermeldung, dass die Datei beschädigt sein und es wird gefragt, ob sie in den Papierkorb gelegt werden soll. Auch ein Start in der Console ergibt keine anderen Informationen. 

In der Console (system.log) habe ich folgendes gefunden:
`Jun  1 08:45:09 MacBook-Pro-3 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x100000f7.PortfolioPerformance[75485]): Service exited due to signal: Killed: 9 sent by CoreServicesUIAgent[75486]`

System Informationen:
```
mirkoebert@MacBook-Pro-3:~> java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
``

```
mirkoebert@MacBook-Pro-3:~> sw_vers -productVersion
10.12.5
```

**Comment by buchen** [comment]
Das kann ich nicht wirklich nachvollziehen. Auf meinem Mac läuft die Version einwandfrei. Bei der Fehlermeldung bin ich etwas ratlos.

Wie hast Du die ausgepackt? Hier gibt es einen Fehler, weil das ZIP nicht richtig ausgepackt wurde: https://bugs.eclipse.org/bugs/show_bug.cgi?id=398450#c17

Vielleicht liegt es daran?

**Comment by mirkoebert** [comment]
Der "Fehler" lag im aktuellen Mac OS X. Abhilfe schafft, wenn man folgendes im Terminal eingibt: `sudo spctl --master-disable`

Siehe auch:
[http://www.macgadget.de/News/2016/09/23/Tipp-Installation-von-unsignierter-Software-unter-macOS-Sierra](http://www.macgadget.de/News/2016/09/23/Tipp-Installation-von-unsignierter-Software-unter-macOS-Sierra)

Das Problem ist gelöst.
