### ISSUE TITLE
Import historischer Kurse von boerse.ard.de und Financial Times schlagen fehl

### ISSUE THREAD

**Issue by sunsided** [buchen/portfolio#771]
Die Tabelle der historischen Kurse von ARD und der financial times lassen sich nicht importieren, z.B. von diesen Links:
http://kurse.boerse.ard.de/ard/kurse_einzelkurs_history.htn?i=15443154
https://markets.ft.com/data/funds/tearsheet/historical?s=LU1597246385:GBP&mhq5j=e2

Version: 0.27.2, Windows 10 (x64)

**Comment by buchen** [comment]
Danke an @stephanmunich
