### ISSUE TITLE
Automatische Anpassung in Feld Umrechnungskurs nicht Kauf/Verkauf Kurs (ER / Bug)

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#784]
derzeit wenn ich amerikanische Aktien kaufe/verkaufe, gebe ich Stück x Kurs und Gebühren ein. 
Der Umrechnungskurs wird dabei automatisch eingetragen.

Die gesamte Gutschrift/Belastung stimmt aber oft geringfügig nicht (vermutlich weil der Umrechnungskurs Tagesendkurs genommen wird und nicht der tatsächsliche Umrechnungskurs bei Kauf/Verkauf).

Beim manuellen Ändern der gesammten Gutschrift/Belastung ändert sich der Kurs (Kauf/Verkaufspreis) und nicht wie erwartet der Wechselkurs.

Ich bin der Meinung der Wechselkurs sollte sich ändern nicht der Kurs.

**Comment by buchen** [comment]
Nur damit ich das richtig verstanden habe: Du änderst den EUR Betrag. Darum wird der USD Betrag angepasst (weil Du amerikanische Aktien gekauft hast), aber es besser der Wechselkurs angepasst werden?

Ich muss das mal durchspielen. Meine Überlegung war sowieso mir zu merken, welche Felder der Benutzer explizit eingegeben hat. Und die dann eben nicht zu ändern (oder nur im Notfall, falls die Rechnung sonst komplett Schrott ist). In diesem Fall würde das auch klappen: Du gibst den USD Betrag ein, dann korrigierst Du den EUR Betrag. Es bleibt also als automatischer Wert nur der Wechselkurs der sich anpassen muss.

**Comment by megabugman** [comment]
So, ich habe zwischenzeitlich herausgefunden warum die Gutschrift/Belastung geringfügig nicht gestimmt hat. Der Wechselkurst ist i.O. jedoch hat mir mein lieber Broker eine kleine (versteckte) Gebühr für den Währungswechsel berechnet und dies nicht explizit ausgewiesen; das hat mich irritiert.

Mein Problem wäre damit erledigt, könnte also geschlossen werden.

**Comment by megabugman** [comment]
Ich versuche nochmal einen Erklärungsanlauf:
Im Beispiel kaufe ich 10 IBM Aktien zu je 153,42 zu einem bestimmten Umrechnungskurs.
![kauf](https://user-images.githubusercontent.com/17204819/34448268-0cc3c9bc-ecec-11e7-8b6a-16ab24e23226.PNG)
Da mein Broker für den Wechsen (USD/EUR) eine versteckte Gebühr verlangt, muss ich die tatsächlich erfolgte "Belastung" manuell im Beispiel auf 1290 Euro ändern.
![kauf2](https://user-images.githubusercontent.com/17204819/34448533-a51501fc-ecee-11e7-92ce-9644a99600f5.PNG)
dabei ändert sich der Kaufkurs auf 153,51. 
Erwartet hätte ich dass sich der Umrechnungskurs ändert nicht der Kaufkurs.
Grund: der Kaufkurs ist fix (zb bei einer Limitorder) während man den genauen Wechselkurs eben nicht kennt.

**Comment by megabugman** [comment]
schließe Ticket, Problem nicht mehr relevant.
