### ISSUE TITLE
YTD Periode

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#789]
die meisten Chart Tools bieten eine YTD Periode (laufendes jahr), evtl. wäre dies auch sinnvoll einzuführen?
![ytd](https://user-images.githubusercontent.com/17204819/28292710-905f7cbc-6b50-11e7-8a92-95e6aa267d88.png)

**Comment by 3mg4** [comment]
Ja wäre schön, schließe mich dem an!

**Comment by Ragas13** [comment]
Ich bin überlege gerade, aber das ist doch bereits möglich wenn ihr die Zeitachse auf das laufende  Jahr beschränkt. Oder verstehe ich die Anforderung falsch?

**Comment by megabugman** [comment]
@Ragas13: gemeint ist der Chart einer Aktie:
![bmw](https://user-images.githubusercontent.com/17204819/28438668-341a843c-6d9f-11e7-96af-0e70981fafdc.PNG)

**Comment by Ragas13** [comment]
Verstanden, danke für die Erklärung (ich Hornochse).

Ich habe hierzu einmal den Pull #790 erstellt.
https://github.com/buchen/portfolio/pull/790

Gruß
Ragas

**Comment by megabugman** [comment]
Danke Ragas.

**Comment by buchen** [comment]
Ich habe den Vorschlag von @Ragas13 gemergt. Kommt mit der nächsten Version.
