### ISSUE TITLE
Forum Anmeldung via Github funktioniert nicht

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#791]
ich möchte mich gerne im PP Forum mit meinem Github Account anmelden, dabei erhalte ich wiederholt die Meldung: 
![github](https://user-images.githubusercontent.com/17204819/28594035-cc2831c8-718e-11e7-97cf-1aefc780f096.PNG)

**Comment by Ragas13** [comment]
Die Anmeldung via github funktioniert, 
du musst dich aber dennoch im Forum
vorher mit deinen github Daten registrieren ^^

**Comment by megabugman** [comment]
die Registrierung funktioniert nicht, ich erhalte obige Meldung. Der Github Login funktionert aber natürlich.
![forum](https://user-images.githubusercontent.com/17204819/28727875-af84be3a-73c6-11e7-9719-a4cf46263881.gif)

**Comment by Ragas13** [comment]
Hast du es bereits mit dem eMail Addy von GITHUB probiert?
Das Forum braucht bei der Registrierung eine eMail-Adresse und die wird von GITHUB in diesem Abschnitt nicht mitgeteilt. Danach funktioniert der Login auch anhand des Benutzernamens.

**Comment by megabugman** [comment]
Danke für den Hint Ragas. Habe eine neue Wegwerfaddresse genommen und jetzt geht es endlich.
Cheers
