### ISSUE TITLE
PDF Import von biw AG bzw. FinTech Group Bank AG identisch zu flatex

### ISSUE THREAD

**Issue by stephanmunich** [buchen/portfolio#793]
Hallo Coding-Profis,

die Bank, welche hinter Flatex steht, war bisher die “biw AG”, welche sich jetzt in “FinTech Group Bank AG” umbenannt hat. Auch andere Anbieter wie z.B. Whitebox benutzen diese Whitelabel-Bank. Die erzeugten PDFs sehen identisch aus, nur leider kann man die Importfunktion in Portfolio Performance nicht nutzen, da im PDF-Dokument nach dem String “flatex” gesucht wird.

Wäre es möglich, das File FlatexPDFExtractor.java in biwPDFExtractor.java zu kopieren und dabei die allerletzte Zeile in “return “biw AG”” zu ändern, um die historischen PDFs von biw/flatex/Whitebox/etc. zu importieren

und

wäre es möglich, eine weitere Kopie desselben Files mit dem Namen fintechgroupbankPDFExtractor.java zu erzeugen und dabei die allerletzte Zeile in “return “FinTech Group Bank AG”” zu ändern, um die aktuellen PDFs von biw/flatex/Whitebox/etc. zu importieren?

Vielen Dank und gebt Bescheid, falls ihr weitere Informationen benötigt.

**Comment by Ragas13** [comment]
Wurde schon gemeldet, siehe https://github.com/buchen/portfolio/issues/783

Ich habe Andreas Buchen bereits einen Pull vorgeschlagen...

Gruß Ragas

**Comment by stephanmunich** [comment]
Damit man jedoch auch PDFs von anderen Banken, welche über die FinTech Group Bank AG laufen, importieren kann, muss der Check nach dem String "flatex" entfernt werden. Ich konnte nicht erkennen, ob dieser Check tatsächlich entfernt wurde. Ich würde vorschlagen, dass man den Import überhaupt nicht mehr Flatex nennt sondern einfach direkt "biw AG" und "FinTech Group Bank AG" oder man den Check vollständig entfernt. Ansonsten wird es für Whitebox nicht funktionieren.

**Comment by Ragas13** [comment]
Aktuell sucht PP nach "biw AG" und soll gem. Poll https://github.com/buchen/portfolio/pull/788 um "FinTech Group Bank AG" erweitert werden.

Als Nebeneffekt, für bspw. Whitebox sollte der Import eigentlich auxh funktionieren, daher wäre es doch überlegenswert das PP Menü anzupassen, aber das muß @buchen entscheiden.

**Comment by buchen** [comment]
Das ist ja unsere Diskussion aus dem [Forum](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38/15) (ich habe zunächst mit der Beantwortung im Forum begonnen :-)

Das Flatex nehmen ich wie besprochen raus. Und den Menüeintrag ändere ich ebenfalls.

**Comment by stephanmunich** [comment]
Vielen Dank, ich denke, die vorliegenden Commits and Pull Requests haben das Problem gelöst.
