### ISSUE TITLE
PDF import für Baader Bank

### ISSUE THREAD

**Issue by stephanmunich** [buchen/portfolio#794]
Hallo Coding-Profis,

die Baader Bank ist die Bank, welche die Wertpapiere für den Robo Advisor Scalable Capital handelt. Es wäre toll, wenn man für diese Bank auch Käufe und Verkäufe importieren könnte. Ich habe daher mit Portfolio Performance den Text aus den entsprechenden PDFs extrahiert:

[Wertpapierabrechnung Baader Bank Kauf.txt](https://github.com/buchen/portfolio/files/1198229/Wertpapierabrechnung.Kauf.txt)
[Wertpapierabrechnung Baader Bank Verkauf mit Steuer.txt](https://github.com/buchen/portfolio/files/1198227/Wertpapierabrechnung.Verkauf.mit.Steuer.txt)
[Wertpapierabrechnung Baader Bank Verkauf.txt](https://github.com/buchen/portfolio/files/1198228/Wertpapierabrechnung.Verkauf.txt)

Der Text scheint eigentlich recht sauber extrahiert zu sein und die Struktur auch nicht besonders kompliziert. Private Daten habe ich mit XXX überschrieben. Leider habe ich selber kein Eclipse etc. installiert, um einen der bestehenden PDF-Importer anzupassen. Gibt es jemanden, der das könnte?

Gebt Bescheid, falls ihr weitere Informationen benötigt oder ob ich sonst noch wie helfen kann.

Vielen Dank und viele Grüße
Stephan

**Comment by buchen** [comment]
Danke für die Beispiele. Es kann ein bisschen dauern, da ich momentan nicht allzu viel Zeit habe. :-(

**Comment by stephanmunich** [comment]
Ich habe mir gestern Eclipse heruntergeladen und eine Kopie des FlatexPDFimporters angelegt. Die Importer für Verkauf und Verkauf (auch mit Steuern) sind bereits so umgeschrieben, dass sie mit der Baader Bank funktionieren. Ich würden Quelltext des Java-Files dann am Ende einfach hier posten, da ich mit SVN nicht betraut bind, ist das in Ordnung?

Außerdem hätte ich noch eine konzeptionelle Frage: Bei der Baader Bank sind ISIN, WKN und Name des Wertpapiers nicht in einer PDF-Zeile, so dass der Suchalgorithmus nicht alle drei Angaben gleichzeitig finden kann. Kann ich, nachdem ich mit 


    .section("isin", "wkn")
    .match(".*Nominale *ISIN: *(?<isin>[^ ]*) *WKN: *(?<wkn>[^ ]*) .*")
    .assign((t, v) -> t.setSecurity(getOrCreateSecurity(v)))

das Wertpapier angelegt habe, nachträglich noch den Namen des Wertpapiers angeben?

Danke und Grüße
Stephan

**Comment by stephanmunich** [comment]
Danke, meine Frage hat sich erledigt, ich habe gesehen, dass man einfach zwei .match-Aufrufe hintereinandersetzen kann um in der nächsten Zeile weiterzusuchen.

**Comment by buchen** [comment]
> Ich würden Quelltext des Java-Files dann am Ende einfach hier posten, da ich mit SVN nicht betraut bind, ist das in Ordnung?

Ja, klar. Ich übertrage die Dateien dann in mein lokale Version. Alternativ ist auf Github das Mittel der Wahl sogenannte [Pull Requets](https://yangsu.github.io/pull-request-tutorial/). Ich erinnere mich aber an meine ersten Tage mit Git - da muss man etwas umdenken. :-)

**Comment by stephanmunich** [comment]
Vielen Dank für den Link, das hat mir schon sehr bei meinem Git-Verständnis weitergeholfen. Wie Du auf [Stackoverflow](https://stackoverflow.com/questions/45560748/letters-from-two-lines-are-interchanged-adobe-reader-can-do-the-job/) nachlesen kannst, hatte ich ein Problem beim Lesen eines bestimmten PDFs.

Das Problem kann gelöst werden, indem der Konverter von PDF zu Text nicht mit der `sort`-Option aufgerufen wird, welche in den beiden Dateien `/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/handlers/CreateTextFromPDFHandler.java` und `/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/AbstractPDFExtractor.java` mit dem Befehl `textStripper.setSortByPosition(true);` gesetzt wird.

Gibt es einen Grund, warum diese Option verwendet wird? Für meine Dateien hat diese Option negative Auswirkungen. Im Zuge dessen habe ich außerdem entdeckt, dass die neue Version pdfbox-2.0.7 sogar noch bessere Ergebnisse liefert (siehe den Link oben). Ich habe daher getestet, ob das Programm auch mit dieser Version funktioniert. Dies ist tatsächlich der Fall.

Folgende Änderungen musste ich vornehmen um von 1.8.8 auf 2.0.7 zu aktualisieren.

Code:

    - replace import org.apache.pdfbox.util.PDFTextStripper
      with    import org.apache.pdfbox.text.PDFTextStripper
      in      name.abuchen.portfolio\src\name\abuchen\portfolio\datatransfer\pdf\AbstractPDFExtractor.java
      and     name.abuchen.portfolio.ui\src\name\abuchen\portfolio\ui\handlers\CreateTextFromPDFHandler.java

Abhängigkeiten:

    - update version of pdfbox in pom.xml from 1.8.8 to 2.0.7
    - remove all dependencies from org.apache.pdfbox.jempbox

    - replace org.apache.pdfbox.util;version="1.8.7"
      with    org.apache.pdfbox.text;version="2.0.7"
      in      name.abuchen.portfolio/META-INF/MANIFEST.MF
      and     name.abuchen.portfolio.ui/META-INF/MANIFEST.MF
    - update version number to 2.0.7 of org.apache.pdfbox.io;version="2.0.7" and org.apache.pdfbox.pdmodel;version="2.0.7"
      in  name.abuchen.portfolio/META-INF/MANIFEST.MF
      and name.abuchen.portfolio.ui/META-INF/MANIFEST.MF
      and name.abuchen.portfolio.ui/target/META-INF/MANIFEST.MF

Wenn ich anschließend mit Maven kompiliere, läuft alles ohne Fehler durch und ich kann die exe-Datei ausführen. Wenn ich allerdings direkt aus eclipse das Programm starte, bekomme ich einen eigenartigen Fehler:

    !ENTRY name.abuchen.portfolio.ui 4 0 2017-08-09 19:18:27.992
    !MESSAGE FrameworkEvent ERROR
    !STACK 0
    org.osgi.framework.BundleException: Could not resolve module: name.abuchen.portfolio.ui [262]
      Unresolved requirement: Import-Package: org.apache.pdfbox.pdmodel; version="2.0.7"
    -> Export-Package: org.apache.pdfbox.pdmodel; bundle-symbolic-name="org.apache.pdfbox"; bundle-version="2.0.7"; version="2.0.7"; uses:="org.apache.pdfbox.contentstream,org.apache.pdfbox.cos,org.apache.pdfbox.io,org.apache.pdfbox.pdmodel.common,org.apache.pdfbox.pdmodel.common.filespecification,org.apache.pdfbox.pdmodel.documentinterchange.logicalstructure,org.apache.pdfbox.pdmodel.documentinterchange.markedcontent,org.apache.pdfbox.pdmodel.encryption,org.apache.pdfbox.pdmodel.font,org.apache.pdfbox.pdmodel.graphics,org.apache.pdfbox.pdmodel.graphics.color,org.apache.pdfbox.pdmodel.graphics.form,org.apache.pdfbox.pdmodel.graphics.image,org.apache.pdfbox.pdmodel.graphics.optionalcontent,org.apache.pdfbox.pdmodel.graphics.pattern,org.apache.pdfbox.pdmodel.graphics.shading,org.apache.pdfbox.pdmodel.graphics.state,org.apache.pdfbox.pdmodel.interactive.action,org.apache.pdfbox.pdmodel.interactive.annotation,org.apache.pdfbox.pdmodel.interactive.digitalsignature,org.apache.pdfbox.pdmodel.interactive.documentnavigation.destination,org.apache.pdfbox.pdmodel.interactive.documentnavigation.outline,org.apache.pdfbox.pdmodel.interactive.form,org.apache.pdfbox.pdmodel.interactive.pagenavigation,org.apache.pdfbox.pdmodel.interactive.viewerpreferences,org.apache.pdfbox.util"
       org.apache.pdfbox [260]
             Unresolved requirement: Import-Package: org.apache.fontbox; version="[2.0.0,3.0.0)"
      Unresolved requirement: Import-Package: org.apache.pdfbox.io; version="2.0.7"
    -> Export-Package: org.apache.pdfbox.io; bundle-symbolic-name="org.apache.pdfbox"; bundle-version="2.0.7"; version="2.0.7"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

Daher meine beiden Fragen:
1. Spricht etwas dagegen, die `sort`-Option für den PDF-Import zu deaktivieren bzw. würde es sich lohnen, für verschiedene PDFs verschiedene Optionen zuzulassen?
2. Weißt Du, was ich tun muss, damit Eclipse auch mit der neuen `pdfbox-2.0.7` das Programm direkt starten kann?

Vielen Dank und viele Grüße, habe schon einiges gelernt bei diesem Projekt!

**Comment by buchen** [comment]
> Das Problem kann gelöst werden, indem der Konverter von PDF zu Text nicht mit der sort-Option aufgerufen wird, welche in den beiden Dateien

Die Sort Option habe ich auf true gesetzt weil ich bei meinen Dokumenten damit bessere Ergebnisse erzielt habe.

Das scheint aber wohl nicht für alle PDF Dokumente zu gelten ... 😒 

Die Option kann man auf jeden Fall nicht (mehr einfach) global ändern. Das Problem ist, dass ich von den meisten Dateien die Original PDF Dokumente gar nicht habe. Aus Datenschützgründen habe mir die Verwender mir nur den schon mit dieser Option umgewandelten Text geschickt (und da einfach Kontonummern und ähnliches editiert). Wenn man jetzt die die sort Option deaktiviert und der Text anders generiert wird, dann werden vermutlich die meisten Importer brechen. So stabil sind die regulären Ausdrücke leider nicht.

Wenn, dann nur pro Importer. Da der "Bank Idenifier" schon auf dem konvertieren Text basiert, müsste man vermutlich beide Versionen generieren - je nachdem welche der Importer braucht.

@Ragas13 baut gerade die Erkennung so um, dass man nicht mehr explizit die Bank angeben muss. In dieser Logik könnte man in einem zweiten Schritt unterschiedliche Sort Optionen einbauen oder auch eine andere pdfbox Version.

> Im Zuge dessen habe ich außerdem entdeckt, dass die neue Version pdfbox-2.0.7 sogar noch bessere Ergebnisse liefert (siehe den Link oben). Ich habe daher getestet, ob das Programm auch mit dieser Version funktioniert. Dies ist tatsächlich der Fall.

Das selbe Problem wie bei der "sort Option" - schwer zu ändern ohne alte Importer "kaputt" zu machen.

Ich habe schon überlegt ob ich beide pdfbox Versionen gleichzeitig nutzen kann. Ein PDF Importer könnte dann bestimmen, welche pdfbox Version zu verwenden sei. Mit ein bisschen Klimmzügen beim Class Loading bekommt man das bestimmt hin. Ich hatte bisher noch nicht die Zeit / den Anlass mir das im Detail anzuschauen.

> Wenn ich allerdings direkt aus eclipse das Programm starte, bekomme ich einen eigenartigen Fehler

Hast Du die Launch Configuration auch angepasst? Vielleicht ist da noch das alte Bundle angewählt?

**Comment by stephanmunich** [comment]
Kannst Du mir einen Tipp, wo ich die Launch Configuration anpasse bzw. was
ein Bundle ist bzw. wo ich das nachlesen kann? Ich kann auch mit der sort
Option leben und mit 1.8.13, nur kann man dann eben nicht den Namen der
Bank extrahieren, aber das scheint ja nicht so wichtig zu sein. Um
langfristig einen Übergang zu schaffen könnte man für neue Texte mit und
ohne sort-Option extrahieren und mit 1.8.13 und 2.0.7. Am Besten wäre es,
die PDFs selber zu anonymisieren, aber das ist mir sonst noch nicht
gelungen, selbst Adobe Acrobat kann das oft nicht.

Andreas Buchen <notifications@github.com> schrieb am Sa., 12. Aug. 2017,
18:09:

**Comment by buchen** [comment]
Wenn Du im Menü "Run" -> "Run Configurations..." auswählst, dann könnten ist vielleicht noch nicht das richtige Bundle ausgewählt:

<img width="626" alt="bildschirmfoto 2017-08-12 um 19 07 19" src="https://user-images.githubusercontent.com/587976/29242692-a5ba1a72-7f91-11e7-8814-65fcbe69d6ba.png">

Oder Du müsstest Die Target Configuration noch aktualisieren - also https://github.com/buchen/portfolio#set-target-platform


> Um langfristig einen Übergang zu schaffen könnte man für neue Texte mit und
> ohne sort-Option extrahieren und mit 1.8.13 und 2.0.7. 

Ja. Ich hatte auch schon gedacht, ob man nicht einen Wizard bauen könnte mit dem Verwender Beispielhaften teilen können. Da würde man ein PDF auswählen, dann verschiedene Versionen generieren, dem Benutzer per search&replace einen Anonymisierung erlauben (also Kontonummer, Name, etc.). Und man würde direkt die Buchung auswählen so wie sie importiert werden sollte. Dann hat man alles für einen schönen Test Case. Kommt. Irgendwann ;-)

An dem Import für die Baader Bank bist Du aber jetzt selber dran, richtig?

**Comment by stephanmunich** [comment]
Die Baader Bank ist fertig

Andreas Buchen <notifications@github.com> schrieb am Sa., 12. Aug. 2017,
19:12:

**Comment by Ragas13** [comment]
Bzgl. der Plug-in Version habe ich einmal versucht mit den MAVEN Einstellungen zu spielen, jedoch schein ECLIPSE an den bereits eingebundenen Add-In's zu hängen^^

Eclipse bzw. MAVEN greift hier die Info aus **.\portfolio-app\pom.xml** ab:
```
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>1.8.8</version>
		</dependency>
```

Anscheinend ist die Änderung in der pom.xml die einzige Möglichkeit, reibungslos die Version des Add-In zu ändern wenn man die Probleme in ECLIPS vermeiden will.

Ich habe gestern einmal hier auf 1.8.13 ausprobiert (entspricht PDFBox 2.0.7) und siehe da, weder MAVEN. ECLIPSE noch PP selbst beanstanden dies.

Ich nehme es mal in meinen Pull auf, wenn meine arbeiten fertig ist.

**Comment by buchen** [comment]
> Ich nehme es mal in meinen Pull auf, wenn meine arbeiten fertig ist.

Generiert denn 1.8.13 noch den identischen Output?

Wie gesagt, ich hatte auch in den Release Notes gelesen, dass pdfbox 2.x "bessere" Ergebnisse liefert - die aber leider alten Output invalidieren.

**Comment by Ragas13** [comment]
Du meinst die Test-Reihen? Ja, alle Tests laufen erfolgreich durch und auch über das Importieren und parsen von PDFs funtioniert problemlos.

Die "Release Notes" zur pdfbox habe ich zwar gefunden, jedoch hatte ich es so verstanden das dies nur den erstellten PDF Content betrifft (erstellen von PDFs), nicht das auslesen von Inhalten. 

Dann gehe ich mal ans lesen der Notes ab 2.0.x *smile*

**Comment by buchen** [comment]
> Du meinst die Test-Reihen? Ja, alle Tests laufen erfolgreich durch und auch über das Importieren und parsen von PDFs funtioniert problemlos.

Die Tests in PP laufen natürlich durch. Die liegen ja schon als Text vor. Nur habe ich keine PDF Dokumente von Onvista, DKB, Bank SLM, etc. um zu checken, ob deren PDF Dokumente immer noch den selben Text produzieren.

> Die "Release Notes" zur pdfbox habe ich zwar gefunden, jedoch hatte ich es so verstanden das dies nur den erstellten PDF Content betrifft (erstellen von PDFs), nicht das auslesen von Inhalten.

Dann könnte man zumindest problemlos auf die letzte 1.8 aktualisieren.

Am liebsten als separaten Pull Request - dann sind Deine anderen Änderungen kleiner uns somit einfacher für mich zu verstehen und zu mergen.

**Comment by Ragas13** [comment]
Ah jetzt ja, habe Verstanden.

Ja, mit den vorhandenen PDF-Beispielen (Consors, DKB, ING) funktioniert das einlesen von PDFs (nicht die geparsten) ohne Probleme. Aber ich lese mich dennoch in die release notes ein.

Was meine pull-requests betrifft, versprochen, diese werden kleiner ;-)

Schönen Sonntag und Gruß
Marco

**Comment by stephanmunich** [comment]
Lieber @buchen, ich brauche noch mal Deine Hilfe. Ich habe erfolgreich einen Menüpunkt für die Baader Bank / Scalable Capital erstellt und den BaaderBankPDFExtractor geschrieben. Ich hatte gehofft, das ganze auch gleich mit Git hochladen zu können und dann einen Pull Request aufmachen zu können. Dafür habe ich einen neuen Workspace erstellt und mit File-Import-Projects from Git-Clone URI und der Adresse https://github.com/buchen/portfolio.git eine lokale Kopie Deines Projekts erstellt, dort die Änderungen eingetragen und mit Add und Commit gespeichert.

Allerdings war wahrscheinlich schon der Ansatz falsch, hätte ich erst online einen Fork und/oder eine Branch erstellen müssen oder wie kann ich aus meinen lokal committeten Daten jetzt ein Pull Request für Dich erstellen? Ich benutze das Git-Plut-In von Eclipse selber! Vielen Dank für Deine Hilfe!

**Comment by stephanmunich** [comment]
Also ich denke, es ist ein rechts Klick auf meinen lokalen Master, dann "Push Branch...", soll ich dann alls destination branch einen neuen branch "baaderbank" eingeben oder wie möchtest Du das bzw. habe ich da überhaupt ein Schreibrecht drauf oder muss ich Dein Projekt forken? Ich glaube, langsam habe ich es raus! Danke!

**Comment by stephanmunich** [comment]
Und was für eine "when pulling" Strategie soll ich auswählen (siehe Anhang)? Vielen Dank!

![image](https://user-images.githubusercontent.com/16959462/29251614-2b187260-8058-11e7-82d3-0f191deac3da.png)

**Comment by Ragas13** [comment]
Ich kenne zwar die ECLIPSE Erweiterung für GITHUB nicht (ich verwende den Windows Client von GITHUB), jedoch sollte der Ablauf für beide ähnlich sein. 

Bei mir war es wie folgt :
1. Du forkst das Projekt von PP
2. Synchronisierst dein persönliches PP offline 
3. Du nimmst die Änderungen offline vor
4. Du comittest deine Änderungen offline an dein GITHUB Projekt 
5. Im online GITHUB Projekt erstellst du einen Pull Request auf das Projekt von @buchen

Einen direkten Merge kannst du so nicht vornehmen, da der Weg erst über dein eigenes Repository gehen musst.

**Comment by stephanmunich** [comment]
Vielen Dank für eure Hilfe, ihr beiden, ich habe es so gemacht, wie von Dir beschrieben und einen Pull Request erstellt. Bitte gebt mir Bescheid, falls ich bei meinen nächsten Beiträgen etwas anders machen soll. Als nächstes würde ich versuchen, die Testcases für die Baader Bank einzubauen. Einen schönen Abend euch.

**Comment by buchen** [comment]
Ich mach den Issue mal zu. Und freue mich auf den nächsten PR.

**Comment by stephanmunich** [comment]
Hier noch zur Dokumentation die Einstellung, die in Eclipse notwendig war, um die Version 2.0.7 auch direkt aus Eclipse starten zu können: portfolio-product/name.abuchen.portfolio.product --> Dependencies --> name.abuchen.portfolio.feature --> Plug-ins --> Add... --> org.apache.pdfbox.fontbox --> OK.

Alle Tests laufen auch mit Version 2.0.7 durch, falls die sort-Option deaktiviert ist. Ich weiß, dass die meisten Tests als Texte und nicht als PDF vorliegen, aber zumindest die wenigen PDFs werden auch mit Version 2.0.7 korrekt geparst.

Die Dokumentation (https://pdfbox.apache.org/2.0/migration.html) sagt: "Breaking Changes to the Library --> General Behaviour: PDFBox 2.0.0 is now parsing PDF files following the Xref information in the PDF. This is similar to the functionality using PDDocument.loadNonSeq with PDFBox 1.8.x. Users still using PDDocument.load with PDFBox 1.8.x might experience different results when switching to PDFBox 2.0.0."

In several places, it is highly recommended to use the new 2.0-parser (equivalent ot the old 1.8-loadnonseq parser): https://stackoverflow.com/questions/33033789/how-to-use-pddocument-loadnonseq-large-pdf-stripper-parsing-text-technique

Ich habe den Eindruck, dass der neue Parser bei bereits ordentlichen Dokumenten keinen Unterschied macht, aber weniger "gibberisch" erzeugt, wozu der alte Parser ja sowieso nicht benutzt werden konnte. Ich denke, er könnte möglicherweise auch issue #428 lösen. Auch für (siehe oben) https://stackoverflow.com/questions/45560748/letters-from-two-lines-are-interchanged-adobe-reader-can-do-the-job/ (Vergleiche dort die Ergebnisse von 1.8.3 mit sort und 2.0.7 mit sort) würde der neue Parser bessere Ergebnisse liefern.

**Comment by toblan** [comment]
Hallo,

man kann sich die Dokumente für Scalable auch direkt von der Baader Bank herunterladen. Allerdings fehlt dann das Wort 'KOPIE'. Anbei ein Beispiel für Verkauf:
```
PDF Author: '' 
PDFBox Version: 1.8.13
-----------------------------------------
Seite 1/2
Unterschleißheim, 05.04.2018
T 00800 00 222 337*
Herrn
F +49 89 5150 2442
xxx xxx service@baaderbank.de
xxxxxxxxx
90491 Nürnberg Stamm-Nr.: xxxxx    Portfolio: 1
Depot-Nr.: xxxx
Vorgangs-Nr.: xxxxx
Referenz-Nr.: xxxxx
Wertpapierabrechnung: Verkauf
Auftragsdatum: 04.04.2018 Beauftragter Ausführungsplatz: XETRA
Auftragszeit: 12:51:14:07
Nominale ISIN: LU0136240974 WKN: 794361 Kurs 
STK 8    UBS-ETF-UBS-ETF MSCI Jap.U.ETF EUR 38,18
Inhaber-Anteile (JPY) A-dis oN
Auftraggeber: ext.Vermögensverw.
Art der Auftragserteilung: Orderroutingssystem
Kundenwunsch: Nicht empfohlener Zielmarkt
Kurswert EUR xxx,xx
Zu Gunsten Konto xxxxxxxx Valuta: 06.04.2018 EUR xxx,xx
Die Wertpapiere buchen wir zu Lasten Ihres Depots.
Details zur Ausführung:
Handelsdatum Handelsuhrzeit
04.04.2018 13:16:18:85
Verwahrart: Girosammelverwahrung
Lagerstelle: 100
Lagerland: Deutschland
Für die Ausführung dieses Auftrags gelten die Usancen des jeweiligen Ausführungsplatzes.
Bitte prüfen Sie diese Auftragsbestätigung/Abrechnung auf Richtigkeit und Vollständigkeit. Etwaige Einwendungen gegen diese 
Auftragsbestätigung/Abrechnung müssen nach Zugang unverzüglich bei der Baader Bank AG erhoben werden.
Dieser Auftrag erfolgte ohne Empfehlung der Bank. Es wurde keine Anlageberatung und keine individuelle Aufklärung durch die Bank 
erbracht.
Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich um eine umsatzsteuerbefreite Finanzdienstleistung.
Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.
Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.
Baader Bank Aktiengesellschaft T 00800 00 222 337* Vorstand: Nico Baader (Vorsitzender), Amtsgericht München HRB 121537
Weihenstephaner Straße 4 F +49 89 5150 2442 Dieter Brichmann (stv. Vorsitzender), Sitz der Gesellschaft: Unterschleißheim
85716 Unterschleißheim service@baaderbank.de Christian Bacherl, Oliver Riedel StNr. 143/107/04009
Deutschland www.baaderbank.de Vorsitzender des Aufsichtsrates: USt-IdNr. DE114123893
Dr. Horst Schiessl LEI: 529900JFOPPEDUR61H13
* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen. WPABRECHNUNG-034.006
Wertpapierabrechnung: Verkauf
Fortsetzung: Seite 2/2
Darstellung der steuerlichen Berechnungsgrundlagen:
Merkposten / Steuertöpfe vorher Erhöhung/Reduktion nachher
Allgemeiner Verlustverrechnungstopf EUR 5,62 EUR 12,20 EUR 17,82
Allgemeiner Verlustverrechnungstopf EUR 17,82 EUR 3,66 - EUR 14,16
Allgemeiner Verlustverrechnungstopf EUR 14,16 EUR 3,47 - EUR 10,69
Allgemeiner Verlustverrechnungstopf EUR 10,69 EUR 10,48 - EUR 0,21
Bemessungsgrundlagen Steuerpflicht brutto Steuerpflicht netto
Veräusserungserg. brutto Aktienf. EUR 12,20 - EUR 0,00
Veräusserungserg. Aktienf. Teilf. EUR 3,66 EUR 0,00
Verkauf R1: AGE + Mehrbetrag EUR 3,47 EUR 0,00
Fonds Verkauf R3: Veräuß.erg. allg. EUR 10,48 EUR 0,00
Kapitalertragsteuer auf allgemeine Gewinne EUR 5,41 EUR 0,00
Berücksichtigte Anschaffungsgeschäfte (alle ermittelten Beträge in EUR)
Geschäfts-
Geschäft Nr. Datum Whg./St. Nominal/Stück Anschaff.-kosten ant. Veräußer.-erlös ant. Ergebnis
WP Kauf fikt.Veräuß. 823645 14.12.2016 STK 8,00 317,64 305,44 12,20 -
Rucksack 1: AGE + Mehrbetrag 3,47 0,00 3,47
Rucksack 3: GuV 2009-2017 Verkaufsformel 10,48 0,00 10,48
Baader Bank Aktiengesellschaft T 00800 00 222 337* Vorstand: Nico Baader (Vorsitzender), Amtsgericht München HRB 121537
Weihenstephaner Straße 4 F +49 89 5150 2442 Dieter Brichmann (stv. Vorsitzender), Sitz der Gesellschaft: Unterschleißheim
85716 Unterschleißheim service@baaderbank.de Christian Bacherl, Oliver Riedel StNr. 143/107/04009
Deutschland www.baaderbank.de Vorsitzender des Aufsichtsrates: USt-IdNr. DE114123893
Dr. Horst Schiessl LEI: 529900JFOPPEDUR61H13
* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen. WPABRECHNUNG-034.006
```
Könnte man das anpassen, da die Dokumente der Baader Bank vollständig und früher verfügbar sind ?
