### ISSUE TITLE
Startet nicht unter MacOS 10.13 Beta

### ISSUE THREAD

**Issue by pikespeak** [buchen/portfolio#795]
Fehlermeldung beim Starten:
Informationen hierzu enthält die Protokolldatei
/Applications/PortfolioPerformance.app/Contents/Eclipse/configuration/1501870682073.log

Ich habe die Protokolldatei angehangen. 

[1501870682073.txt](https://github.com/buchen/portfolio/files/1201273/1501870682073.txt)

**Comment by Ragas13** [comment]
Hat PP schon einmal auf deinem Mac funktioniert oder triit dieser Fehler seit dem letzten Update auf?

Laut dem anhängen Protokoll wird die Java Version 1.7.0_55 von 2014 verwendet.

Kannst du bitte einmal auf https://www.java.com/de/download/ nachsehen, ob eine neue Version installiert werden kann? 

Gruß
Ragas

**Comment by pikespeak** [comment]
Ich installiere es das erste mal.
Seltsam das ich Java 7 habe, ich installiere grad die neue Version und versuche es nochmal.

**Comment by pikespeak** [comment]
Also ich habe die neueste Java 8 installiert. Der Browser meldet mir dies auch. Ebenso das Mac Controlpanel. Java 8, Version 144
Der Terminal liefert weiterhin Java 7 24.55-b03

**Comment by Ragas13** [comment]
Seltsam aber liegt sicher daran das ich Windows User bin...

Im Forum habe ich diesen Beitrag gefunden:
https://forum.portfolio-performance.info/t/fehler-aufgetreten-beim-ersten-start-macbook-pro/270/5

Zusammengefasst geht es darum das MacOS woht das Java JDK und nicht die JRE aktuell sein muss.

Andreas Buchen hat hier auf http://www.oracle.com/technetwork/java/javase/downloads/index.html verwiesen.

Sollte das auch nicht funktionieren, bin ich ratlos.

**Comment by pikespeak** [comment]
Im Java Control Panel steht: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java als Java Pfad drin. Da befindet sich die Version 8.
Im Terminal unter java werde ich auf /usr/bin/java verwiesen, welches dann zur Version 7 führt, das ist wohl seit dem Update auf die Beta Version von Mac OS 10.13 so.
Eine Idee wie ich PP dazu bringe nach der richtigen Java Version zu gucken?

**Comment by pikespeak** [comment]
Danke, es hat geklappt

**Comment by pikespeak** [comment]
JDK von Java 8 installiert
