### ISSUE TITLE
Verbesserung: automatische Auswahl des Extractors auf Basis von PDF Autor und Bank Identifier

### ISSUE THREAD

**Issue by Ragas13** [buchen/portfolio#797]
Ich versuche gerade den Import von PDFs auf einen einzigen Menüpunkt zusammen zu dampfen. Dabei bin ich auf den **ImportPDFHandler** gestoßen:
https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/handlers/ImportPDFHandler.java

Ich bin nur nicht sicher ob ich die Funktionsweise des Handlers richtig verstehe. 

Kann ich von folgender Annahme ausgehen? 
> 1. Über das PP Navigationsmenü wird festgelegt, welcher Import Handler (ING, DKB, usw)
> 2. Im Dateidialog werden die PDF's selektiert /ausgewählt
> 3. In einer Schleife werden die PDF's einzeln durch den Konverter geschickt und vorbereitet
> 4. Der Import Assistent zeigt die geparsten Buchungen an

Wenn ich jetzt eine einzelne Schnittstelle für alle Banken erreichen wollte,
könnte ich doch **innerhalb der Schleife** mE folgende Ergänzung vornehmen:
> 1. Erkennung des Verfassers / Autors des PDF''s (ING, DKB, Consorsbank)
> 2. Im Fehlerfall nach Stichwort innerhalb des PDF's suchen (FinTech Group Bank AG)
> 3. Wenn dann ein **Extractor** gefunden werden konnte, dieses einzelne Dokument auslesen

Lange Rede kurzer Sinn, kann es funktionieren jedes einzelne PDF fallweise durch die verschiedenen Konverter zu schicken? 

Danke, Gruß und schönes Wochenende. 
Ragas

**Comment by Ragas13** [comment]
In diesem Zusammenhang, welche Erweiterung von Eclipse brauche ich um das Menü von PP zu bearbeiten? Ich finde zwar vereinzelt Hinweise aux die XML Dateien, aber das Menü selbst kann ich leider nicht modifizieren.

**Comment by buchen** [comment]
> In diesem Zusammenhang, welche Erweiterung von Eclipse brauche ich um das Menü von PP zu bearbeiten?

Das Menü ist in dem "bootstrap" Plug-in in der Datei "application.e4xmi" definiert. Es gibt dazu auch einen Editor. Ich glaube man muss die "Eclipse e4 Tools" installieren (über die Update Site von oxygen)


> Lange Rede kurzer Sinn, kann es funktionieren jedes einzelne PDF fallweise durch die verschiedenen Konverter zu schicken?

Dein Annahmen (Schritt 1 bis 4) passen so.

Jetzt ist die Frage wie man den richtigen Extractor erkennt.

Der Autor ist ein guter Ansatz. Damit sollte man zumindest einige Dokumente gut identifizieren können.

Die zweite Möglichkeit sind die Schlüsselwörter. Die werden als "bank identifier" gespeichert. Die meisten Dokumente haben solche Schlüsselwörter. Hier müsste man wohl die Logik leicht ändern - momentan wird ja sofort ein Fehler geworfen, wenn der Schlüsselwort nicht gefunden wird.

Ich meine es gibt aber auch Dokumente, die noch gar keine Schlüsselwörter haben. Zum Beispiel der von der DKB. Oder von Onvista. Ich habe damals nix passendes gefunden, aber man könnte ja schaue ob es sowas wie BLZ oder andere Merkmale gibt. Wenn nicht, müsste man das in einer Art "trial and error" machen.

**Comment by Ragas13** [comment]
Danke für deine Informationen, dass hilft mir schon sehr viel weiter.

Eben habe ich auch gelernt das der PDF Import Wizzard alle konvertierbaren PDFs in PP einließt. Wenn ich in der Funktion **performFinish()** der Klasse **ImportExtractedItemsWizard** in Erfahrung bringen kann, welche PDFs er in diesem Durchgang erkannt hat, dann kann ich diese bspw. in einem Unterordner aussortieren und der **ImportPDFHandler** erkennt im nächsten Durchgang weitere Banken.

Was den "bank identifier" betrifft, einen Tot muss man sicherlich sterben sprich das nicht alle Banken über die automatische Erkennung laufen können. Im Falle von DKB oder Onvista wäre dies nicht schön, jedoch wären aktuell 9 von 11 Konverter für diese Lösung prädestiniert.

Aber jetzt erst einen Schritt nach dem anderen, erweitert werden kann es allemal.

Ich versuche dann jetzt einmal folgende Vorgehensweise zu implementieren:
> 1. Öffnen des File Dialogs zur Auswahl der PDF Dateien
> 2. Erkennung des PDF Verfassers
> 3. Im Fehlerfall die Erkennung mittels Schlüsselwörter aka "bank identifier"
> 4. Übergabe des Konverters an den **wizwardDialog** für den gefundenen Extractor
> 5. Im Erfolgsfall (Übernahme bestätigt mittels afterPage @ ImportExtractedItemsWizard) werden Dateien verschoben
> 6. Sollten weitere PDF Dateien anderer Banken ausgewählt worden seinen, beginne bei Schritt 2

**Comment by buchen** [comment]
> Eben habe ich auch gelernt das der PDF Import Wizzard alle konvertierbaren PDFs in PP einließt. Wenn ich in der Funktion performFinish() der Klasse ImportExtractedItemsWizard in Erfahrung bringen kann, welche PDFs er in diesem Durchgang erkannt hat, dann kann ich diese bspw. in einem Unterordner aussortieren und der ImportPDFHandler erkennt im nächsten Durchgang weitere Banken.

Was ich nicht machen würde ist die Dateien auf dem Dateisystem zu verändern (oder zu verschieben). Zumindest nicht wenn der Benutzer nicht explizit danach fragt.

Es gab mal einen Feature Request erfolgreich importierte Dokumente (optional) in einen Ordner zu verschieben. Aber es ist gar nicht so einfach zu sagen, wann das eigentlich erfolgreich importiert wurde. Nur wenn es erkannt wurde? Wenn man tatsächlich auch auf "Importieren..." gedrückt hat? Aber die Buchung manuell nicht vom Import ausgeschlossen hat? Und es hörte sich einfach als eine zu spezielle Anforderung an...

Ich glaube mit den drei (oder vier) Schritten (Autor, Bank Idendifier, dann probieren, dann auswählen) kommt man schon gut weiter.

Ich könnte mir das wie folgt vorstellen:;

1. Öffnen des File Dialogs zur Auswahl der PDF Dateien - Benutzer wählt eines oder mehrere PDF Dokumente aus
2. Für jedes Dokument:
a) Erkennung des PDF Verfassers
b) Wenn nicht gefunden, dann schauen ob ein "Bank identifier" passt
c) Jeden importer (oder die ohne Bank identifizier) ausprobieren --> wenn eine Buchung erkannt wurde, dann übernehmen.

Schritt 2c ist glaube ich okay. Ich würde sagen, es ist ziemlich unwahrscheinlich, dass zwei Extratouren aus dem selben Dokument gültige Buchungen extrahieren können.


Dafür müsstest Du wahrscheinlich die Logik deutlich umbauen. Der Extractor kann jetzt nicht mehr einfach an den Dialog gegeben werden, sondern der Dialog muss in der Lage sein über eine Liste aller Extractoren zu iterieren.

**Comment by buchen** [comment]
(Ich mach den Issue mal wieder auf. Dann finde ich die Diskussion einfacher wieder. In der Commit Message kannst du dann "Issue: #797" reinschreiben - dann wird dafür ein Link generiert)

**Comment by Ragas13** [comment]
Nach dem die Umfrage zumindest teilweise ergiebig war, werde ich mich einmal damit beschäftigen einen den relevanten Teil vom ImportPDFHandler in den ImportExtractedItemsWizard zu verlagern. Der Vorteil, jede Bank bekommt eine eigene Seite im Wizzard (bspw. ING > Seite 1; Comdirekt > Seite 2) usw. 

Auch der original Handler bleibt unverändert, da ich im ImportExtractedItemsWizard auf übergeordnete Vorgaben reagieren kann.

Einzige Sorgenfalte die gerade im Zusammenhang mit der Suche nach dem Bank Identifier habe, was wäre wenn jemand sein Depot bei bspw. der ING-DiBa hat und Aktien der BNP Paribas? Ich glaube da hilft nur der Ausschluss von gewissen ISINs, die dann manuell zugewiesen werden müssen.

**Comment by Ragas13** [comment]
Ich habe jetzt einmal einen ersten Versuch als Pull vorgeschlagen,  jedoch scheitere ich genau an der Stelle wo der Anwender auswählen muss welcher PDFExtractor verwendet werden soll.

Den Assistenten anzupassen, so das dieser Dokumente erkennt, zuordnet, jede Bank sein eigenes Depot/Verrechnungskonto verwendet und alles in einem rutsch importiert wird ist kein Thema. Selbst der Extractor könnte zur Laufzeit geändert werden (Dropdown) **wäre da nicht das Problem das ich den Dropdown nicht abfragen kann und kein refresh() ausgelöst wird**

Wenn du mir etwas Hilfestellung geben könntest, ist mir sehr geholfen.

Gruß 
Marco

**Comment by buchen** [comment]
Ich mache diesen Issue mal zu und wir diskutieren in Pull Request #819 weiter.
