### ISSUE TITLE
Userinterface wird nicht ausreichend neu gezeichnet 

### ISSUE THREAD

**Issue by cgerum** [buchen/portfolio#800]
In der neuesten Version 0.27.4 werden unter Windows 7 GUI updates nich mehr vollständig durchgeführt.
So dass sich wie im folgenden Bild mehrere Views überlagern, oder teile des User  Interfaces gar nicht mehr angezeigt werden.

![missing_ui_updates](https://user-images.githubusercontent.com/65497/29387346-f9067ba2-82df-11e7-92b0-4824dfb2871e.png)

Viele Grüße, Christoph Gerum

**Comment by buchen** [comment]
😮 

Du hast den Issue wieder geschlossen? Hat sich das erledigt?!?

**Comment by cgerum** [comment]
Komplette Neuinstallation hat das Problem behoben. Sorry für die Störung.
