### ISSUE TITLE
INGDiBa Übertrag Ausgang

### ISSUE THREAD

**Issue by stephanmunich** [buchen/portfolio#809]
Ich habe den untenstehenden PDF Text, er stellt eine Entnahme/Ausbuchung/Umbuchung/Übertrag (was ist der richtige Begriff?) eines Wertpapieres aus meinem Depot dar. Das Wertpapier soll dann später auf einem anderen Depot erscheinen (Übertrag Eingang bei Consors).

- Leider ist mir nicht klar, welchen Typ ich für diese beiden Transaktionen verwenden soll: `TRANSFER_IN`, `TRANSFER_OUT`, `DELIVERY_INBOUND` und/oder `DELIVERY_OUTBOUND`?

- Außerdem frage ich mich, wie ich erkennen kann, welche Angaben für jeden dieser Typen notwendig ist. Wo kann ich das sehen?

Folgende Probleme treten auf (die Angaben werden korrekt erkannt und extrahiert):

- Wenn ich das PDF als Umbuchung (Ausgang) importiere (also `TRANSFER_OUT`), funktioniert der Import ohne Fehlermeldung, aber wenn ich danach die Buchung editieren möchte, bekomme ich eine java.lang.IllegalArgumentException.

- Wenn ich beim Importieren den Haken bei Käufe/Verkäufe in Ein-/Auslieferungen umwandeln setze, funktioniert der Import ebenfalls ohne Fehlermeldung, aber wenn ich danach die Buchung editiere, sehe ich, dass ein Betrag, Steuern, etc. gewünscht sind, was ja keinen Sinn macht.

- Wenn ich den Typ auf `DELIVERY_OUTBOUND` setze, bekomme ich beim Importieren die Fehlermeldung `No enum constant name.abuchen.portfolio.model.AccountTransaction.Type.DELIVERY_OUTBOUND`

Was mache ich falsch? Hier mein Code:

```
private void addTransferOutTransaction()
    {
        DocumentType type = new DocumentType("Übertrag Ausgang");
        this.addDocumentTyp(type);

        Block block = new Block("Übertrag Ausgang");
        type.addBlock(block);
        block.set(new Transaction<BuySellEntry>()

                        .subject(() -> {
                            BuySellEntry entry = new BuySellEntry();
                            entry.setType(PortfolioTransaction.Type.TRANSFER_OUT);
                            return entry;
                        })

                        .section("shares", "name", "date", "isin", "wkn")
                        .find("Nominale / Stück Wertpapier-Informationen Schlusstag Auftragsnummer")
                        .match("^(?<shares>[,\\d\\.]+?) Stück (?<name>.*) (?<date>\\d+.\\d+.\\d{4}) \\d+$")
                        .match("^ISIN \\(WKN\\): (?<isin>.*) \\((?<wkn>.*)\\)$")
                        .assign((t, v) -> {
                            t.setSecurity(getOrCreateSecurity(v));
                            t.setDate(asDate(v.get("date")));
                            t.setCurrencyCode(asCurrencyCode(t.getPortfolioTransaction().getSecurity().getCurrencyCode()));
                            t.setShares(asShares(v.get("shares")));
                            
                        })

                        .wrap(BuySellEntryItem::new));
    }
```

Hier der zugehörige Text:
> ING-DiBa AG   60628 Frankfurt am Main
> Depotinhaber: Vorname Nachname
> Herrn Direkt-Depot Nr.: XXXXXXXXX
> Vorname Nachname Datum: 28.04.2016
> Meine Str. 99 Seite: 1 von 1
> 99999 Ort
> Übertrag Ausgang
> Sehr geehrter Herr Nachname,
> nachstehende Wertpapiere haben wir Ihrem Depot entnommen:
> Nominale / Stück Wertpapier-Informationen Schlusstag Auftragsnummer
> 999,00 Stück iShsIII-Cor.MSCI Wld UCITS ETF 28.04.2016 9999999999
> Registered Shs Acc. USD o.N.
> ISIN (WKN): IE00B4L5Y983 (A0RPWH)
> Girosammelverwahrung
> Taxbox-ID: 9999999999999999
> Empfänger: Vorname Nachname
> Depot Nr. XXXXXXXXX, BNPP ehem. Cortal Co
> Vorhandene Einstandskurse werden an inländische Banken automatisch übermittelt.
> Sollten Sie Fragen zu den gelieferten Anschaffungsdaten haben, wenden Sie sich bitte mit der jeweiligen
> Taxbox-ID direkt an die Empfängerbank.
> Mit freundlichen Grüßen
> ING-DiBa
> Gabriele Neitzke Matthias Bayer
> Leiterin Kundendialog Leiter Wertpapier
> ING-DiBa AG Vorsitzender des Aufsichtsrates: Ben Tellings Sitz: Frankfurt am Main Internet www.ing-diba.de
> Theodor-Heuss-Allee 2 Vorstand: Roland Boekhout (Vorsitzender), AG Frankfurt am Main HRB 7727 E-Mail info@ing-diba.de
> 60486 Frankfurt am Main Bernd Geilen, Katharina Herrmann, Zeljko Kaurin, Steuernummer 047 220 2800 4 BIC: INGDDEFFXXX
> Remco Nieland, Dr. Joachim von Schorlemer USt-IdNr. DE 114 103 475 Mitglied im Einlagensicherungsfonds

**Comment by Ragas13** [comment]
Wenn ich im Konverter zu Flatex nachsehe, würde ich als copy&paste Laienprogrammierer dies mittels **PortfolioTransaction.Type.SELL** versuchen. Die Zuordnung ob TRANSFER oder DELIVERY wird an übergeordneter Stelle (ImportExtractedItemsWizard.java & Co.) festgelegt. 

Vielleicht kannst du die Antwort im Flatex Konverter und dessen Funktion addTransferOutTransaction() erkennen, ich schaffe es nicht :-(
https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/pdf/FinTechGroupBankPDFExtractor.java#L471

Das konnte ich zumindest beim umschreiben des Import Handlers erkennen, jedoch fehlen mir auf dem letzten Meter vor dem Ziel eine einzelne Abfrage im JFac Wizard *heul*

Gruß 
Marco

**Comment by buchen** [comment]
> Leider ist mir nicht klar, welchen Typ ich für diese beiden Transaktionen verwenden soll: TRANSFER_IN, TRANSFER_OUT, DELIVERY_INBOUND und/oder DELIVERY_OUTBOUND?

Die TRANSFER_* Typen sind für Wertpapier-Umbuchungen zwischen Depots gedacht. Da braucht es wieder ein "Pärchen" von Buchungen - und das wird über einen CrossEntry angelegt/verwaltet: Also ProtfolioTransferEntry:

<img width="207" alt="bildschirmfoto 2017-09-02 um 07 11 58" src="https://user-images.githubusercontent.com/587976/29993121-0f3b3478-8fae-11e7-831f-df83e389f0f7.png">

Die DELIVERY_* Typen sind für Einlieferungen bzw. Auslieferungen gedacht. Also wenn ein Wertpapier eingeliefert wird und es eben keine Kaufbuchung gibt.

> Außerdem frage ich mich, wie ich erkennen kann, welche Angaben für jeden dieser Typen notwendig ist. Wo kann ich das sehen?

Das ist eine gute Frage... natürlich nirgendwo dokumentiert. Am einfachsten ist es vielleicht sich das im GUI Modell abzuschauen. Da gibt es eine Klasse "AbstractModel" und dann für die verschiedenen Buchungen Sub-Klassen. Schau da auf die Methode *applyChanges* wenn das Modell in die Account/PortfolioTransaction/Entry kopiert wird.

<img width="531" alt="bildschirmfoto 2017-09-02 um 07 14 37" src="https://user-images.githubusercontent.com/587976/29993136-6cc5babe-8fae-11e7-82c8-d89cba73c708.png">

> Wenn ich das PDF als Umbuchung (Ausgang) importiere (also TRANSFER_OUT), funktioniert der Import ohne Fehlermeldung, aber wenn ich danach die Buchung editieren möchte, bekomme ich eine java.lang.IllegalArgumentException.

Ich vermute mal das liegt daran, dass es kein *BuySellEntry* sondern ein *PortfolioTransferEntry* sein muss. Ansonsten -> StackTrace?
