### ISSUE TITLE
Compression for XML file

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#818]
The XML file used by portfolio grows in size over time, e.g. mine is currently about 6 MB large.
To be able to easily sync it using a cloud service like Dropbox or Google Drive, the size should not be too large.
I just tried GZIP compression (which is easily available in the JDK) on it, which turned the 6 MB XML file into a 600 KB GZIP file.

So finally I would like to consider adding an additional option for saving and loading gzipped XML files.
As far as I went through the code there is already a parameter `method` used in [`ClientFactory.buildPersister`](https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/model/ClientFactory.java#L394).
Currently it just describes the key length to be used for AES encryption.
Maybe we can use it or something similar to support a compression.

For the compression to make sense it should be wrapped inside of the encryption as compressing encrypted data will not result in a large size reduction.

**Comment by buchen** [comment]
When encrypting, the XML is compressed - using a regular ZipOutputStream: 
https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/model/ClientFactory.java#L289-L293 - Maybe this can be improved / better compressed?

One could also add a compressed, but unencrypted storage format.

**Comment by sebasbaumh** [comment]
Thanks @buchen, I did not see that one.

I think `ZipOutputStream` should have even better compression - I just chose `GzipOutputStream` as it can be transparently wrapped around any other output stream without having to create a `ZipEntry`.
But in that case using a `ZipOutputStream` is more consistent here.

_BTW: I just did a quick test with my file and zip/gzip (with standard compression settings) - the filesize did not differ much. Some more analysis showed me that both went with the deflate algorithm underneath and the zip file was just a bit larger because of the larger header including the ZIP entry and a larger tail block at the file end ;-)
In contrast maximum settings for ZIP do make a large difference: then I'm down to 480 KB compared to 600 KB (ZIP standard) and 6 MB (uncompressed)._

**Comment by buchen** [comment]
What do you think? Should I add a non-encrypted (e.g. not password protected) but compressed file type?

**Comment by sebasbaumh** [comment]
Sounds great!
Unfortunately I did not have time yet to dig through all of the load/save code - so that would be very welcome :-)

**Comment by sebasbaumh** [comment]
Thanks @Ragas13 and @buchen !
