### ISSUE TITLE
Bug: Dividend Transaction exchange rate label incorrect

### ISSUE THREAD

**Issue by stephanmunich** [buchen/portfolio#823]
Wie man im unten angehängten Bild erkennen kann, ist die Beschriftung des Wechselkurses falsch. Es müsste meiner Meinung nach USD/EUR heißen, falls in der Gleichung am Ende die richtige Währung rauskommen soll. Ich habe schon mal selber kurz in `/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/dialogs/transactions/AccountTransactionDialog.java` geschaut, bin mir aber nicht sicher, woran es jetzt liegt, dass die Anzeige nicht passt.

![bug_pp_dividend_exchangeratelabel](https://user-images.githubusercontent.com/16959462/30026435-31de1e02-917d-11e7-8f16-97ecc827e3d2.png)

**Comment by buchen** [comment]
An der Darstellung der Wechselkurse habe ich lange rumgemacht. Und überlasse es jetzt in den Einstellungen dem Benutzer ob der eine Mengen- oder Preisnotierung nutzen will. Mit dem Nachteil, dass man das nicht immer als mathematische Formel lesen kann (was früher ging - aber dann die Währungsexperten irritiert hat).

<img width="456" alt="bildschirmfoto 2017-09-04 um 21 54 04" src="https://user-images.githubusercontent.com/587976/30037498-9c0f88a4-91bb-11e7-990a-39eb97be3c62.png">

**Comment by stephanmunich** [comment]
Vielen Dank, da habe ich wieder etwas gelernt!
