### ISSUE TITLE
javax.crypto.BadPaddingException: Given final block not properly padded

### ISSUE THREAD

**Issue by hmarschall** [buchen/portfolio#844]
Hallo,

leider öffnet seit heute meine Portfolio-Datei nicht. Auch das Backup öffnet nicht. Ich erhalte folgenden Stack-Trace der Fehlermeldung. Kann mir jemand bitte weiterhelfen??

Grüße,
Holger.

> Mon Oct 02 20:47:57 CEST 2017
> javax.crypto.BadPaddingException: Given final block not properly padded
> 
> java.io.IOException: javax.crypto.BadPaddingException: Given final block not properly padded
> 
> 	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:121)
> 
> 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:239)
> 
> 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:215)
> 
> 	at name.abuchen.portfolio.model.ClientFactory$Decryptor.readStreamUntilEnd(ClientFactory.java:217)
> 
> 	at name.abuchen.portfolio.model.ClientFactory$Decryptor.load(ClientFactory.java:278)
> 
> 	at name.abuchen.portfolio.model.ClientFactory.load(ClientFactory.java:400)
> 
> 	at name.abuchen.portfolio.ui.LoadClientThread.run(LoadClientThread.java:42)
> 
> Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
> 
> 	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:989)
> 
> 	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:845)
> 
> 	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
> 
> 	at javax.crypto.Cipher.doFinal(Cipher.java:2048)
> 
> 	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:118)
> 
> 	... 6 more

**Comment by buchen** [comment]
Ich habe vor ein paar Sekunden eine Version 0.27.8 hochgeladen die das Problem beheben sollte.

https://forum.portfolio-performance.info/t/fehler-nach-passworteingabe/1520

Könntest Du noch mal probieren?

**Comment by hmarschall** [comment]
Hallo,

wo kann ich die neue Version runterladen. Auf http://www.portfolio-performance.info/portfolio/ ist sie noch nicht...

Grüße,
Holger

**Comment by buchen** [comment]
Bekommst Du die nicht durch "Hilfe" -> "Nach Aktualisierungen suchen..." angezeigt?

(Auf dem Mac im Application Menü).

Der Download braucht noch was - der ist noch mit dem Upload beschäftigt :-)

**Comment by hmarschall** [comment]
Da steht bei mir "Keine Aktualisierungen vorhanden."

**Comment by buchen** [comment]
Mmmmh. Bei mir dauert das auch manchmal - oder erkennt das erst nach einem Neustart. Wie auch immer: Jetzt ist die neue Version auch auf der Homepage.

**Comment by hmarschall** [comment]
Prima. In der Version 0.27.8 klappt es wieder. Danke, insbesondere für das schnelle Feedback!

Grüße,
Holger
