### ISSUE TITLE
https://www.portfolio-performance.info doesn't work

### ISSUE THREAD

**Issue by Al2Klimov** [buchen/portfolio#846]
www.portfolio-performance.info verwendet ein ungültiges Sicherheitszertifikat. Das Zertifikat gilt nur für folgende Namen: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

**Comment by buchen** [comment]
Yep, Github User pages mit einer custom domain erlauben aktuell nur HTTP...

Aber das ist ein guter Hinweis. Ich muss mich mal schlau machen. Es scheint doch Wege zu geben:
https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html
https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by Al2Klimov** [comment]
Wenn alle Stricke reissen, gibt's zum Glueck immer noch Let's Encrypt.

**Comment by do3meli** [comment]
Seit Mai 2018 sollte das Github mit der Hilfe von Let's Encrypt von Hause aus können:
https://github.blog/2018-05-01-github-pages-custom-domains-https/

Mein Safari meldet unter https://www.portfolio-performance.info auch ein gültiges Zertifikat:
<img width="579" alt="Screenshot 2020-01-11 at 00 30 07" src="https://user-images.githubusercontent.com/1478176/72193400-9c4f1580-3409-11ea-85cd-9881bf967b16.png">

Der Issue kann damit wohl geschlossen werden.
