### ISSUE TITLE
Unterstützung für Georgische Lari (GEL)

### ISSUE THREAD

**Issue by ei8ht187** [buchen/portfolio#847]
Hallo, 
gerne möchte ich auch meine Investitionen in GEL tracken. Ist es möglich, diese Währung zu unterstützen?
Zumindest von der Nationalbank Georgiens gibt es historische Kurse als Excel: https://www.nbg.gov.ge/index.php?m=582&lng=eng

Freundliche Grüsse

ei8ht187

**Comment by lxffm** [comment]
Ich habe das selbe Bedürfnis! Gerade mit Kontext P2P kommt man ganz flux zu Fremdwährungskonten. Das beste wäre natürlich wenn man Währungen einfach selbst konfigurieren könnte.

**Comment by buchen** [comment]
@sebasbaumh hat in PR #980 schon eingebaut wie man weitere Fremdwährungen hinzufügen kann. Das werden wir jetzt noch etwas polieren und dann kommt das mit einer der nächsten Versionen.
