### ISSUE TITLE
Kompilierungsprobleme mit Neon 3 unter Linux

### ISSUE THREAD

**Issue by yetipenguin** [buchen/portfolio#855]
Wenn ich die Anleitung aus der Readme mit Neon 3 unter Kubuntu 14.04.5 LTS umsetze erhalte ich 941 Kompilierungsprobleme.

Meine Schritte:
Verwendete Eclipse-Version:
eclipse-rcp-neon-3-linux-gtk-x86_64.tar.gz

git clone https://github.com/buchen/portfolio.git portfolio-neon
cd portfolio-neon
export MAVEN_OPTS="-Xmx1g"
cd portfolio-app
mvn clean install
cd ../../eclipse-neon-3-rcp
./eclipse

......
Import wie unter "Developing with Eclipse" beschrieben:
choosing "File" > "Import..." > "Existing Projects into Workspace" from the menu
......

cd portfolio-neon/portfolio-app
mvn clean install -Dgenerate-target-platform=true
......
In Eclipse weiter wie unter "Set Target Platform" beschrieben
Anscheinend wird die Target Platform nicht akzeptiert, da der Button weiterhin "Set as Target Platform" und nicht "Reload Target Platform" heißt".
......
941 Errors

Alles aktualisieren und Build->Clean all hat nicht geholfen

Oxygen zeigt fast das gleiche Verhalten mit dem feature_oxygen-Branch.
Bezüglich der Eclipse-Version war ich mir nicht sicher. Eine reine PDE-Version wird nicht angeboten, da müsste RCP und RAP doch am nächsten kommen oder benötige ich Eclipse IDE for Java und muss dann PDE als Plugin nachinstallieren?

java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by buchen** [comment]
> Eine reine PDE-Version wird nicht angeboten, da müsste RCP und RAP doch am nächsten kommen

Ich denke auch.

> Anscheinend wird die Target Platform nicht akzeptiert, da der Button weiterhin "Set as Target Platform" und nicht "Reload Target Platform" heißt".

War das nicht nur eine Umbenennung im Target Editor zwischen Neon und Oxygen?


Was sind denn die 941 errors? Was kann er denn nicht auflösen?
Und: Du hast die Targert Platform unter "porfolio-app/ide-target-platform/portfolio-ide.target" gesetzt, richtig?

**Comment by yetipenguin** [comment]
> War das nicht nur eine Umbenennung des Links/Buttons im Target Editor zwischen Neon und Oxygen? Ich glaube das ist egal.
Das kann gut sein. Der Button hat sich in Oxygen in "Reload Target Platform" umbenannt. Ich ignoriere es.

> Und: Du hast die Targert Platform unter "porfolio-app/ide-target-platform/portfolio-ide.target" gesetzt, richtig?
Aua. Ich hab "porfolio-app/template/portfolio-ide.target" erwischt.
Danke für die schnelle Hilfe! Jetzt funktioniert es auch mit Oxygen.
