### ISSUE TITLE
Consorsbank Ausgabegebühr wird nicht erfasst

### ISSUE THREAD

**Issue by JB862** [buchen/portfolio#856]
Siehe https://forum.portfolio-performance.info/t/consorsbank-ausgabegebuehr/1638

Hier noch einmal die Datei 
[Consors Ausgabegebühr.txt](https://github.com/buchen/portfolio/files/1424049/Consors.Ausgabegebuhr.txt)

**Comment by buchen** [comment]
Schaue ich mir an
