### ISSUE TITLE
Windows Dateinamenskonvention nicht berücksichtigt

### ISSUE THREAD

**Issue by JB862** [buchen/portfolio#857]
Beim Exportieren (Datei-> Exportieren) erfolgt kein Hinweis, wenn der z.B. aus dem Depotnamen abgeleitete Dateinamen nicht der Windows-Namneskonvention entspricht. In meinem Fall enthielt der Depotname ein *. Beim Klicken auf speichern passiert einfach gar nichts.

Viele Grüße

**Comment by buchen** [comment]
Danke für die Info. Unter macOS werden einfach alle Buchstaben als gültige Dateinamen akzeptiert, darum ist mir das nicht aufgefallen.
