### ISSUE TITLE
PDF Import UnionInvestment Depot > Volksbank

### ISSUE THREAD

**Issue by Kenji242** [buchen/portfolio#860]
Hallo es wäre schön den PDF Import für UnionInvestment zu haben.

[Umsatzübersicht_82339409_6f0e479d36b34c35b41e7f7f2489e87a (1).pdf](https://github.com/buchen/portfolio/files/1427769/Umsatzubersicht_82339409_6f0e479d36b34c35b41e7f7f2489e87a.1.pdf)

Das ist die PDF dazu :)

Danke.

**Comment by buchen** [comment]
Hi @Kenji242,

Dank für das PDF. Das Problem: PP wandelt das PDF in Text um und wertet dann den Text mit regulären Ausdrücken aus. Wenn Du das Original PDF änderst (also z.B. schwärzst), dann ändert sich auch die Textproduktion. Und dann sehen die regulären Ausdrücke ganz anders aus - alles schon ausprobiert... das bringt nix.

Deswegen die Idee: erst den Text generieren, dann im Text Namen und Kontonummer ändern. Den Text kannst Du über das Menü "Datei -> importieren -> Debug: Text aus PDF generieren" erstellen. Dann die Textdatei hier posten.


Andreas.

**Comment by Kenji242** [comment]
So hier habe ich eine Seite generiert. Hoffe sie hilft. Und los gehts.

lg.



PDF Author: '' 
-----------------------------------------
Seite 1 von 1 EBF, Version: 1.0 [51a3410], Erstellt am 31.10.2017, 10:43

Umsatzübersicht

UnionDepot: 8xxxxxxxx-01 Depotinhaber: Pxxxxx xxxxz

Produkt: UniProfiRente Verfügungsberechtigung: Einzeldepot

Zeitraum 01.09.2017 - 06.10.2017

Buchungsdatum Buchungsart Gegenwert

06.10.2017 Kauf 33,00 EUR

1. UniGlobal Vorsorge

Dxxxxxxxxxxxx1, Kapitalverwaltungsgesellschaft: Union Investment Privatfonds GmbH, IBAN: Dxxxxxxxxxxxxxxxxxxxxxxx6, Bank: Volksbank in der

Ortenau eG

Anlagebetrag Preisdatum Ausgabepreis Rücknahme- Abrechnungs- Ausgabeauf- Gebühren Kurswert Anteile

in EUR in EUR preis in EUR preis in EUR schlag in EUR in EUR in EUR

33,00 05.10.2017 207,24 197,37 207,24 -1,57 0,00 33,00 0,159

Buchungsdatum Buchungsart Gegenwert

02.10.2017 Kauf 40,00 EUR

1. UniGlobal Vorsorge

Dxxxxxxxxxxxx1, Kapitalverwaltungsgesellschaft: Union Investment Privatfonds GmbH

Anlagebetrag Preisdatum Ausgabepreis Rücknahme- Abrechnungs- Ausgabeauf- Gebühren Kurswert Anteile

in EUR in EUR preis in EUR preis in EUR schlag in EUR in EUR in EUR

40,00 29.09.2017 204,37 194,64 204,37 -1,90 0,00 40,00 0,196

Buchungsdatum Buchungsart Gegenwert

06.09.2017 Kauf 33,00 EUR

1. UniGlobal Vorsorge

Dxxxxxxxxxxxx1, Kapitalverwaltungsgesellschaft: Union Investment Privatfonds GmbH, IBAN: Dxxxxxxxxxxxxxxxxxxxxxxx6, Bank: Volksbank in der

Ortenau eG

Anlagebetrag Preisdatum Ausgabepreis Rücknahme- Abrechnungs- Ausgabeauf- Gebühren Kurswert Anteile

in EUR in EUR preis in EUR preis in EUR schlag in EUR in EUR in EUR

33,00 05.09.2017 199,28 189,79 199,28 -1,57 0,00 33,00 0,166

Buchungsdatum Buchungsart Gegenwert

01.09.2017 Kauf 40,00 EUR

1. UniGlobal Vorsorge

Dxxxxxxxxxxxx1, Kapitalverwaltungsgesellschaft: Union Investment Privatfonds GmbH

Anlagebetrag Preisdatum Ausgabepreis Rücknahme- Abrechnungs- Ausgabeauf- Gebühren Kurswert Anteile

in EUR in EUR preis in EUR preis in EUR schlag in EUR in EUR in EUR

40,00 31.08.2017 199,73 190,22 199,73 -1,90 0,00 40,00 0,200

Bei Fragen hierzu wenden Sie sich bitte an Ihre Bank.

Union Investment Service Bank AG, 60621 Frankfurt am Main, Gläubiger-Identifikation Dxxxxxxxxxxxxxxxxxxx0

**Comment by Nirus2000** [comment]
Hallo @Kenji242 
sorry, dass ich erst jetzt auf dein Issue reagiere.
Ich bin am Aufarbeiten der PDF-Importer und über deinen PDF-Debug gestolpert.
Kannst du uns einen vollständigen PDF-Debug zur Verfügung stellen? Leider ist hier
nur Seite 1 von 5 vorhanden.

Loggen Sie sich dazu im Forum unter https://forum.portfolio-performance.info/ ein und erstelle einen Beitrag im PDF-Importer von [PDF-Import von UnionInvest/Volksbank/DZ Bank](https://forum.portfolio-performance.info/t/pdf-import-von-unioninvest-volksbank-dz-bank/1686)

Wie es funktioniert, können Sie im Video-Tutorial sehen.

Video-Tutorial:
[PDF-Dokumente für die Fehlersuche extrahieren](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

Gruß
Alex
