### ISSUE TITLE
OnVista Dokumente werden nicht richtig verarbeitet

### ISSUE THREAD

**Issue by uupascal** [buchen/portfolio#861]
Beim importieren einer OnVista Wertpapierabrechnung mit einer Transaktion über die Baader Bank, erkennt der Importer das Dokument als eines der Baader Bank, was dazu führt das der Import fehlschlägt.

**Comment by Ragas13** [comment]
Kannst du evtl. die entsprechende Abrechnung als Textdatei hier posten?

Der Importassistent sucht derzeit nach Schlüsselwörtern(bank identifier) um den passenden Konverter auszuwählen, jedoch können in Sonderfällen Wertpapiere ebenfalls zu Treffern führen. Hier muss sicherlich nachgearbeitet werden.

**Comment by uupascal** [comment]
Ich würde wirklich ungern das Dokument hier öffentlich posten. Falls es garnicht anders geht, würde ich relevante Informationen entfernen und es anonymisiert hier Posten. Da ich dabei aber sichergehen müsste nichts am Layout zu ändern könnte das wohl einen Moment Dauern. 

Ein Workaround wäre es erstmal vielleicht die Option hinzuzufügen den Importer manuell zu wählen.

Ein Ansatz könnte sein nach dem String 
"Dieser Beleg wird maschinell erstellt und daher nicht unterschrieben. Wir bitten Sie, diese Abrechnung auf ihre Richtigkeit und Vollständigkeit zu überprüfen und etwaige Einwendungen unverzüglich zu erheben."

zu suchen. Auch wenn das eine reine Vermutung ist, haben andere Banken wohl einen leicht anderen Wortlaut für diese Bemerkung.

**Comment by Ragas13** [comment]
Der Schnelle workaround wäre die Tastenkombination Alt+X.

Ein anonymisierter Auszug würde helfen hier zukünftig eine Änderung anzustreben. Bei der Änderung des PDF Assistenten war mit  solchen Verstrickungen nicht zu rechnen.

**Comment by sunnylars** [comment]
[pdf.txt](https://github.com/buchen/portfolio/files/1463834/pdf.txt)

Ich hatte das Problem jetzt auch. Mehrere Buchungen in einem PDF, die letzte Buchung von der Baader Bank.

**Comment by Ragas13** [comment]
@sunnylars
Danke für den Auszug, dass hilft zumindest das Problem einzugrenzen. 
Ich schicke den Assistenten morgen zur Nachschulung.

> Börse außerbörslich **Baader Bank**

@Ragas13
Was zumindest einen Versuch Wert ist, im PDFImportAssistant nach " Börse außerbörslich" + bank identifier zu suchen und dann bei Fund das Dokument von der automatischen Erkennung auszuschließen.

https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/wizards/datatransfer/PDFImportAssistant.java#L51-L62

Gruß 
Marco

**Comment by buchen** [comment]
@uupascal @sunnylars 

> Ein Workaround wäre es erstmal vielleicht die Option hinzuzufügen den Importer manuell zu wählen.

Der aktuelle Workaround ist: **Strg-X** -> Dokument(e) auswählen -> Importer auswählen. (Ich sehe gerade @Ragas13 hat das schon oben geschrieben).

Wie weitermachen? Klar - wir könnten die "bank identifier" weiter ausbauen (inklusive Ausschlusskriterien, etc.). Keine Ahnung wie gut man damit wird. Ich würde gerne mal bei Gelegenheit ausprobieren ob man nicht den Text einfach durch alle Extractors schiebt. Und der erste der erfolgreich Buchungen erstellt, muss wohl der richtige sein. Jetzt wo die Umwandlung von PDF in Text nicht mehr im Extractor ist, sollte das deutlich schneller sein. Etwas muss man schauen wie man mit dem SecurityCache umgeht.

**Comment by sunnylars** [comment]
Eine Mögliche Lösung für das Onvista Problem, die den "bank identifier" weiter ausbauen würde.

Mir ist beim analysieren der Onvista Extracte aufgefallen, das in allen Files folgende Kombination vorkommt.

BELEGDRUCK=
ORIGINAL=
FAXVERSAND=
EMAILVERSAND=
DEPOTNUMMER=

Mit einem Vergleich, ob diese 5 Strings in 5 aufeinander folgenden Zeilen irgendwo in dem Dokument vorkommen, könnte erkannt werden, ob es ein Onvista Dokument ist. 

Aktuell würden diese beiden Dokumente nicht mehr erkannt ( sind beide von 2010 ) 
OnvistaDepotauszug.txt / OnvistaKontoauszugEinzelneBuchung.txt

In den beiden Dokumenten findet sich keines dieser Wörter, die haben aber auch eine etwas andere Struktur, wobei ich denke, da wurden nach dem Extrahieren persönliche, aber auch uninteressante Zeilen bearbeitet.
OnvistaKontoauszugMehrereBuchungen.txt / OnvistaKontoauszugMehrereBuchungen2017.txt

In diesen älteren Dokumenten kommt aber der String "onvista" noch vor, insofern könnte das als Fallback implementiert werden.

Ich versuche das mal testweise zu implementieren, aber ich bin kein Eclipse Programmierer und weiß noch gar nicht, wo und wie ich das einbauen würde.

**Comment by ZfT2** [comment]
> Aktuell würden diese beiden Dokumente nicht mehr erkannt ( sind beide von 2010 )
OnvistaDepotauszug.txt / OnvistaKontoauszugEinzelneBuchung.txt

In den beiden Dokumenten findet sich keines dieser Wörter, die haben aber auch eine etwas andere Struktur, wobei ich denke, da wurden nach dem Extrahieren persönliche, aber auch uninteressante Zeilen bearbeitet.
OnvistaKontoauszugMehrereBuchungen.txt / OnvistaKontoauszugMehrereBuchungen2017.txt

In diesen älteren Dokumenten kommt aber der String "onvista" noch vor, insofern könnte das als Fallback implementiert werden.

Diese Beispiele dürften von mir sein, und ich hab eigentlich immer nur meine persönlichen Daten wie Name, Anschrift und Konto/Depotnummern anonymisiert, aber nichts rausgenommen...
Denke es wäre daher schon gut, wenn der Importer "abwärtskompatibel" bleibt auch zu älteren Dokumenten.
