### ISSUE TITLE
Erkennung Comdirect Ertragsgutschrift funktioniert nach Update nicht mehr

### ISSUE THREAD

**Issue by lunareactor** [buchen/portfolio#864]
Seit der automatischen Bankerkennung der Importe scheint die Dokumentart "Ertragsgutschrift" (Dividenen/Erträge) von comdirect nicht mehr korrekt zugeordnet zu werden und kann daher nicht eingelesen werden (siehe Screenshot). Die Dokumentart "Wertpapierabrechnung" für Kauf/Verkauf von Wertpapieren funktioniert weiterhin problemlos.

![screenshot_pp](https://user-images.githubusercontent.com/33316409/32321441-6f24a214-bfc1-11e7-94ad-9a9358a21ee8.JPG)

Falls benötigt, habe ich unten nochmals den anonymisierten Text eines Ertragsabrechungs-PDFs angehängt.

---

31.10.2017
Herrn
xxx xxx
Musterstr. 1
12345 Musterstadt

Depotnr.: xxxxxxxxx
BLZ: xxx xxx xx
G u t s c h ri f t fä ll ig e r W e r t p a p i e r -E r tr ä g e
Ertragsgutschrift
Depotbestand Wertpapier-Bezeichnung WKN/ISIN
p e r 1 1 . 1 0 . 2 0 1 7 i S h s V I - J P M D L E M B d E O H U . E T F D A 1 W 0 M Q
S T K 4 2 , 0 0 0 R e g i s t e r e d S h a r e s o . N . I E 0 0 B 9 M 6 R S 5 6
Emissionsland: IRLAND
EUR x,xxxx Ausschüttung pro Stück für Geschäftsjahr 01.04.17 bis 31.12.17
zahlbar ab 01.11.2017
Abrechnung Ertragsgutschrift
Bruttobetrag: EUR x,xx
Verrechnung über Konto (IBAN) Valuta Zu Ihren Gunsten vor Steuern
DExx xxxx xxxx xxxx xxxx xx EUR 31.10.2017 EUR 8,54
Information zur steuerlichen Behandlung dieses Geschäftsvorganges und den auf
Ihrem Konto gebuchten Endbetrag finden Sie auf der separaten Steuermitteilung
(Referenz-Nr. xxx).
comdirect bank
Aktiengesellschaft
*Diese Abrechnung wird von der Bank nicht unterschrieben

25449 Quickborn

**Comment by Ragas13** [comment]
Kannst du bitte den Inhalt als Textdatei zum download hier einstellen?
Gerade beim Comdirect Import kommt es auf jedes Leerzeichen an.

**Comment by lunareactor** [comment]
Gerne, siehe Textdatei anbei.
Ich habe den Text einfach aus dem PDF herauskopiert, die Formatierung ist da natürlich verloren gegangen, aber Text/Leerzeichen sollten übereinstimmen.

[Ertragsgutschrift.txt](https://github.com/buchen/portfolio/files/1440917/Ertragsgutschrift.txt)

**Comment by Ragas13** [comment]
Danke für die Datei, jedoch hilft es leider nicht wenn du den Text aus dem PDF kopierst. 

PP bietet hier eine hilfreiche Funktion die den Text genauso extrahiert wie der Konverter den Text lesen wird.  Kannst du es bitte noch einmal probieren? Kurzanleitung ist wie folgt:
> Extrahieren geht wie folgt:
> Über das Menü Datei -> Importieren -> Debug: Text aus PDF extrahieren...

Wenn es funktioniert hat, sollte das Ergebnis wie folgt aussehen:
https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/comdirect/comdirectGutschrift3.txt

Eine Bitte noch zum anonymisieren, könntest du Bitte die Stückzahlen und Beträge stehen lassen?
Adresse, IBAN, Kontonummer und Co. können bzw sollten entfernt werden.

Danke dir
Marco

**Comment by lunareactor** [comment]
Ah, diese Funktion von PP war mir noch nicht bekannt. 
Anbei der entsprechende Auszug.

[Ertragsgutschrift2.txt](https://github.com/buchen/portfolio/files/1441134/Ertragsgutschrift2.txt)

**Comment by Ragas13** [comment]
Perfekt 👍 
Ich schaue es mir nachher gleich genau an, warum er dieses Format nicht akzeptiert. 

VG
Marco

**Comment by Ragas13** [comment]
Es ist verwirrend, ich dachte zwar das Problem wäre mit pull #854 erledigt
aber jetzt zeigt sich das wieder eine weitere geringe Änderung vorliegt.

However, ich habe jetzt einmal den Teil des Importers für die Gutschrift fälliger Wertpapier-Erträge soweit angepasst. Es sollte beim nächsten Update funktionieren.

**Comment by fbartnitzek** [comment]
Während ich mich an #759 versucht habe, hatte ein Dividenden-Dokument von mir wieder eine kleine Abweichung - Pull Request folgt.
