### ISSUE TITLE
Yahoo API für Tagesaktuelle Kurse eingestellt

### ISSUE THREAD

**Issue by MattesGroeger** [buchen/portfolio#867]
Wie bereits im Forum diskutiert funktioniert der tagesaktuelle Zugriff auf die Kursdaten seit dem 2. November 2017 nicht mehr. Dies betrifft auch viele andere Programme und Services.

Hier werden verschiedene Alternativen diskutiert, vielleicht ist ja etwas dabei was zu einer Lösung führt:
https://news.ycombinator.com/item?id=15616880

**Comment by buchen** [comment]
@MattesGroeger - Danke für den Link mit möglichen Alternativen

Ich habe als erste Alternative den QuoteProvider so umgebaut, das die Kurse aus der Webseite herausgelesen werden. Siehe 4a00235d339508ce303ba43877ddbcfce3929993. Das ist deutlich langsamer, aber zumindest bekomme ich mit der selben Konfiguration wieder aktuelle Kurse. Es geht um Wertpapiere, die als "Aktuellen Kurse Provider" "Yahoo Finance" eingetragen haben.

@sebasbaumh @akoch @Ragas13 @stephanmunich Wenn Ihr Zeit habt, wäre es cool wenn Ihr mal ausprobieren könntet, ob das bei Eurem Portfolio auch funktioniert.

**Comment by sunnylars** [comment]
Servus,
ich habe das gleich mal getestet und bei mir klappt es prima.

**Comment by sebasbaumh** [comment]
Ja, funktioniert auch bei mir wieder.

**Comment by Ragas13** [comment]
Da war doch was, ganz vergessen  

Läuft unter Win10 :)

**Comment by akoch** [comment]
Sieht bei mir auch gut aus
