### ISSUE TITLE
Inactive - Erweitern, das nur active Wertpapiere neue Kurse holen.

### ISSUE THREAD

**Issue by sunnylars** [buchen/portfolio#871]
Bedingt dadurch, das ich viele Inaktive Zertifikate habe, zu denen keine Informationen mehr abrufbar sind, würde ich vorschlagen, die Updates nur bei den Papieren zu machen, die nicht inaktiv sind.

Gerne auch konfigurierbar, so dass inactive updated oder nicht.

**Comment by sunnylars** [comment]
Mittlerweile habe ich herausgefunden, das ich einfach unter dem Wertpapier auf "Nicht download" stellen kann.

Wäre vielleicht trotzdem eine Überlegung wert, diese Funktionalität ein zu bauen. Wenn Interesse besteht, baue ich das gerne ein.

**Comment by buchen** [comment]
Hi @sunnylars,

ich würde die Funktionalität gerne getrennt halten: man kann ein Wertpapier deaktivieren, dann taucht es nicht mehr in den Dialogen für die Buchungen auf. Trotzdem will man vielleicht noch aktuelle Kurse laden um zu sehen wie sich das Papier so entwickelt hat.

Da die Frage aber immer wieder mal kommt, könnte man es vielleicht intuitiver gestaltet, wenn man zwei Checkboxen hat: eine für die deaktivieren, eine für den Download. Irgendwas muss ich mir bei Gelegenheit mal überlegen.

Andreas.
