### ISSUE TITLE
PDF Import - Augsburger Aktienbank - Bankhaus August Lenz

### ISSUE THREAD

**Issue by RoSchw** [buchen/portfolio#882]
Hi Marco, hier die Dateien.

[Bankenprofile PP.docx](https://github.com/buchen/portfolio/files/1463700/Bankenprofile.PP.docx)

Danke im Voraus.

**Comment by Nirus2000** [comment]
Hallo @RoSchw 

ich würde gern den Importer bauen, dazu benötige ich aber noch mehr Dokumente wie
Kauf, Verkauf, Dividenden etc.

Könntest du mir diese hier noch zur Verfügung stellen?

Tutorial:
[Buchungen aus PDF Dateien importieren](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

Grüße
Alex

**Comment by RoSchw** [comment]
Hallo Nirius2000

beide Banken haben ihr Depotgeschäft aufgegeben. Danke für die Bereitschaft, die Mühe wäre nun leider umsonst.

LG RoSchw
