### ISSUE TITLE
Dividenden drop-down Bennenung

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#886]
um konsistent mit Performance/Wertpapiere Tab zu sein, nehme ich an es müsste Seit heißen:
![seit](https://user-images.githubusercontent.com/17204819/32709171-ac6128ee-c82e-11e7-82b3-36329b819408.PNG)

**Comment by buchen** [comment]
@christian-wehrheim hat den Zusatz "Seit..." hinzugefügt.
