### ISSUE TITLE
Historische Kurse laden: Downloadfehler bei Versuch 1 für Ticker H4ZF.SG

### ISSUE THREAD

**Issue by StefanByom** [buchen/portfolio#888]
Hi,

PP hat beim Lesen der historischen Kurse für den ETF HSBC S&P 500 ETF (DE) (ISIN DE000A1C22M3 / WKN A1C22M) ein Problem. Die gebildete Yahoo URL führt zu einer fehlerhaften Seite. Egal welchen Handelsplatz ich für den Ticker einstelle. Aktueller Kurs wird jedoch wunderbar geladen.

PP Version 0.28.2 (macosx, x86_64)
Log des Fehlers anbei.

URL führt zur Ausgabe im Browser von 

"{
    "finance": {
        "error": {
            "code": "Unauthorized",
            "description": "Invalid cookie"
        }
    }
}"

VG Stefan

[2017-11-14 PP Log URL error.txt](https://github.com/buchen/portfolio/files/1468262/2017-11-14.PP.Log.URL.error.txt)

**Comment by buchen** [comment]
Für den Ticker scheint Yahoo keine Daten zu haben.

Wenn Du auf die Seite gehst:
https://de.finance.yahoo.com/quote/H4ZF.SG/history?p=H4ZF.SG
Und dann "Daten herunterladen" wählst, bekommst Du ebenfalls eine Fehlermeldung (es wird zwar eine Datei heruntergeladen, da steht aber nur eine Fehlermeldung drin).


Also bleibt nur die Such nach einer andere Kursquelle - also z.B. eine Tabelle mit den Kursen.
Siehe auch hier:
https://forum.portfolio-performance.info/t/quellen-fuer-historische-kurse/46

**Comment by cmaoling** [comment]
Hallo,
Ich habe in solchen Fällen gute Erfahrung mit der Funktion von PP gemacht, Kurse aus der Tabelle einer Webseite zu laden.
 Versuche mal folgende URL:http://www.ariva.de/s%26p_500_ucits_etf-fonds/historische_kurse
