### ISSUE TITLE
Eine neuere Version von libwebkitgtk nutzen

### ISSUE THREAD

**Issue by phobeus81** [buchen/portfolio#897]
In Fedora 27 wurde libwebkitgtk-1.0-0 als obsolete markiert und vollständig aus dem System entfernt. Es ist somit auch nicht mehr einfach möglich eine ältere Version von F26 zu nutzen. Hintergrund dafür ist, dass die alte Version zahlreiche bekannte Sicherheitslücken hat und diese nicht mehr in der alten Version gefixt werden.

Bei anderen Distributionen wie Ubuntu hat auch bereits eine Diskussion begonnen, die Pakete aus dem gleichen Grund zu entfernen und andere werden sicherlich auch bald folgen. Dies würde dazu führen, dass einige Funktionen von PP nicht mehr unter Linux zur Verfügung stehen würden.

Es wäre daher super, wenn man auf eine neuere Version aktualisieren könnte. Aktuell im System installiert ist z.B. libwebkit2gtk-4.0.so.37. Der Versuch über das Ini-File eine neuere GTK version zu nutzen führt dazu, dass bei den Beständen nur eine weiße Seite angezeigt wird. In der Konsole gibt es folgender Fehlermeldung:
(Portfolio Performance:4274): Gtk-CRITICAL **: gtk_cell_renderer_set_fixed_size: assertion 'width >= -1 && height >= -1' failed

**Comment by buchen** [comment]
Ich plane auf Eclipse Oxygen zu wechseln und hoffe damit eine aktuellere Version zu bekommen.
PP selber nutzt libwebkitgtk nur indirekt.

**Comment by buchen** [comment]
Ich mache diesen Issue mal zu. Ist gleiche Thema wie #769.
