### ISSUE TITLE
Popup bei Charts enthält nur den Kurs

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#903]
Klickt man auf einen Chart, dann erscheint ein Popup mit dem Kurs an der aktuellen Position.
In der kompakten Ansicht erscheinen jetzt sogar Käufe und Verkäufe.
Allerdings fehlen noch die Dividenden, so dass man immer zur Umsatzansicht umschalten muss.
Diese sollten auch auftauchen und im besten Fall auch noch angeschrieben werden - dann sieht man das sogar in der Übersicht.

Eventuell könnte man auch die Stückzahl beim Kauf anschreiben und beide Texte ausblenden, wenn der Platz nicht ausreicht.
@Ragas13/@buchen was meint Ihr, könnte man die Texte je nach Platz dynamisch ausblenden?

**Comment by Ragas13** [comment]
Ich bin bzgl. der Anzeige der Dividenden auf die Funktion ```paintMarkerLines``` gestoßen. Hier wird anscheinend durch  einen CustomPainter?! der markerLines inkl. Text gezeichnet.

Der sicherlich einfachste Weg wäre direkt hier die Änderungen vorzunehmen, jedoch verbaut man sich an anderen Stellen den Marker.

Je nach Umfang der MarkerLine in PP ķönnte hier mE am ehesten angesetzt werden, wobei zwei Formen der MarkerLines entstehen. 1x vollständig und 1x kurze Linie von unten bis zum Text

https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/util/chart/TimelineChart.java

**Comment by sebasbaumh** [comment]
Ist jetzt wieder drin - danke @buchen  :smile:
