### ISSUE TITLE
PDF Import 1822direkt

### ISSUE THREAD

**Issue by lunareactor** [buchen/portfolio#910]
Wäre es möglich, auch die Bank 1822direkt in den PDF-Importer aufzunehmen?
Ich schätze, dass im Rahmen der Comdirect-Sparplanpassungen bzgl.  der Comstage-ETFs doch einige Nutzer zu 1822direkt gewechselt sind.

Anbei der PDF-Auszug einer meiner Sparplanausführung (Kauf) aus dem Import debugger. 
Ich hoffe, das Format passt.

Vielen Dank!

[1822direkt.txt](https://github.com/buchen/portfolio/files/1539479/1822direkt.txt)

**Comment by Ragas13** [comment]
Hast du evtl noch weitere Buchungsarten wir Verkäufe, Erträge oder Dividenden? Ansonsten kann nämlich nur diese Buchungsart verarbeitet werden...

**Comment by lunareactor** [comment]
Im Moment leider noch nicht. Erträge sollten zum Ende des Monats dazukommen, dann könnte ich ein weiteres PDF liefern. Ich frage in der Zwischenzeit einmal im Wertpapier-Forum nach, ob jemand dort weitere anonymisierte Dokumente liefern könnte.

**Comment by Thiruvananthapuram** [comment]
Ich kann auch noch einen Kauf beisteuern.

[Kauf1.txt](https://github.com/buchen/portfolio/files/1608210/Kauf1.txt)

Wäre super, wenn der Import auch für die 1822direkt funktionieren würde.

**Comment by lunareactor** [comment]
Wie angekündigt, ein weiteres Dokument zu 1822direkt. Diesmal der PDF-Extract für Dividenden/Erträgen:

Bitte beachten: Die Bruttoausschüttung bezieht sich auf 93,56 EUR, Die Nettoausschüttung nach Steuern auf 68,87 EUR. Der Zinsanteil/die Steuergrundlage (93,63 EUR) ist aufgrund einer minimalen Thesaurierung etwas höher als die Bruttoausschüttung. Diese Steuergrundlage sollte aber für Portfolio Performance irrelevant sein.

[Ausschuettung_1822direkt.txt](https://github.com/buchen/portfolio/files/1613047/Ausschuettung_1822direkt.txt)
