### ISSUE TITLE
tycho-maven-plugin nicht verfügbar

### ISSUE THREAD

**Issue by hilbert-ralf** [buchen/portfolio#911]
Hallo,

es scheint als wenn das Maven-Plugin tycho-maven-plugin welches zum Buld benötigt wird unter http://buchen.github.io/maven-repo/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom nicht (mehr) verfügbar ist.
 Folgende Maven-Fehlermeldung erhalte ich:
```
λ mvn clean isntall -Dmaven.test.skip=true
[INFO] Scanning for projects...
Downloading: http://buchen.github.io/maven-repo/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:1.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:1.0.0 @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project name.abuchen.portfolio:portfolio-app:0.28.5-SNAPSHOT (C:\Users\...\git\portfolio\portfolio-app\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:1.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:1.0.0: Could not transfer artifact org.eclipse.tycho:tycho-maven-plugin:pom:1.0.0 from/to portfolio-non-maven-dependencies (http://buchen.github.io/maven-repo): buchen.github.io: Unknown host buchen.github.io -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
```

**Comment by Ragas13** [comment]
Hallo Ralf,

ich habe gerade einmal eine neue Installation geladen und dann vor der dem jeweiligen Maven Befehl den Maven Cache lokal gelöscht. Bei keinem der folgenden Befehle trat dein Fehler auf:
* mvn clean install
* mvn clean install -Dgenerate-target-platform=true
* mvn clean install -Dmaven.test.skip=true

Ich vermute das es ein temporäres Problem beim download gab.

**Comment by hilbert-ralf** [comment]
Hallo Ragas13,

danke für die schnelle Antwort. Leider glaube ich ist es kein temporärer Fehler. Ich kann den Fehler reproduzieren. Habe jetzt auch noch mal auf einem anderen Rechner versucht http://buchen.github.io/maven-repo/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom im Browser aufzurufen. Leider wurde ich dabei auf http://www.portfolio-performance.info/maven-repo/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom redirected und erhielt dort einen 404. Kann es sein das du in deiner lokalen Maven-Konfiguration Einstellungen getätigt hast um das downloaden zu können?

Gruß ralf

**Comment by Ragas13** [comment]
Hallo Ralf,

ich habe allenfalls die unter https://github.com/buchen/portfolio/blob/master/README.md genannten Änderungen vorgenommen?!

> Configure
> **Mac OS X / Linux**
> export MAVEN_OPTS="-Xmx1g"
>
> **Windows**
> set MAVEN_OPTS="-Xmx1g"

Und dann ```mvn clean install``` bzw. ```mvn clean install -Dgenerate-target-platform=true```.

Ich habe gerade noch einmal ein Log erstellt und dieses nach dem Addon durchsucht.
Folgende Einträge kann ich finden:
```
Downloading: http://buchen.github.io/maven-repo/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/tycho/tycho-core/1.0.0/tycho-core-1.0.0.jar
```

Es scheint demnach richtig das Maven erstauf http://buchen.github.io sucht, aber dann ausweicht auf https://repo.maven.apache.org ?!

Gruß
Marco

**Comment by hilbert-ralf** [comment]
Danke, das war der entscheidende Hinweis. bei apache ist es dann auch verfügbar. Es muss also an meiner Maven-Konfiguration liegen das diese Quelle nicht angefragt wurde, damit kann ich arbeiten. Danke nochmal für deine Hilfe.
