### ISSUE TITLE
Umsatz Sortierung nach Eingabe/Datum/Uhrzeit

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#912]
beim Versuch PP als Daytrading Profit Calculator zu verwenden stört die fehlende Sortierung der Umsätze:
![20171214101300](https://user-images.githubusercontent.com/17204819/33985514-1dabdb26-e0bb-11e7-9ad5-2a7bf960f61b.PNG)

die fehlerhafte Sortierung könnte behoben werden indem man Möglichkeit hätte die Uhrzeit mit eingeben zu können.

**Comment by buchen** [comment]
Mit #913 kann man die Uhrzeit erfassen. Kommt. Allerdings werde ich eine Version wohl erst Anfang Januar veröffentlichen.
