### ISSUE TITLE
Hilfe bei Projektsetup

### ISSUE THREAD

**Issue by hilbert-ralf** [buchen/portfolio#918]
Hallo zusammen,
ich würde gerne einen PDF-Importer für die Postbank entwickeln weil ich den persönlich bräuchte. Leider fällt mir das Projektsetup schwer. Erst probierte ich es mit IntelliJ Idea, leider aufgrund der starken kopplun zum Eclipse Ökosystem vergebens. Mit eclipse bin ich weniger vertraut und vielleicht stoße ich deswegen auf viele Probleme. Die Setupanweisungen habe ich soweit befolgt und das `mvn clean install -Dgenerate-target-platform=true` läuft auch mittlerweile ohne Probleme durch. Allerdings bekomme ich noch immer viele Compilierungsfehler angezeigt. Ich vermute dessen Grund darin das mir in der "Target Definition" Ansicht ebenso Fehler angezeigt werden:

> The target definition did not update successfully
> Problems loading repositories
> No repository found at http://archive.eclipse.org/nebula/Q22016/release/.
> 
> The target definition did not update successfully
> Problems loading repositories
> No repository found at http://archive.eclipse.org/technology/babel/update-site/R0.14.1/mars.
> 
> The target definition did not update successfully
> Problems loading repositories
> No repository found at http://download.eclipse.org/eclipse/updates/4.6/R-4.6.3-201703010400/.
> 
> The target definition did not update successfully
> Problems loading repositories
> No repository found at http://download.eclipse.org/tools/orbit/downloads/drops/R20170307180635/repository.
> 

Muss ich vielleicht noch inrgend welche Schritte befolgen die nicht in der README.md beschrieben sind? Über hilfe wäre ich sehr dankbar.

Gruß Ralf

**Comment by yetipenguin** [comment]
Welche Eclipse-Version setzt du denn ein? Der master funktioniert aktuell (nur?) mit Eclipse Neon.

**Comment by hilbert-ralf** [comment]
Das ist ein guter Hinweis, ich habe mir natürlich Eclipse Oxygen geladen. Ich probier mal Neon ...

**Comment by hilbert-ralf** [comment]
Klasse das war es. Also nicht nur, ich hatte auch noch ein Problem weil ich hinter einem Proxy war. In einer Proxylosen-Umgebung mit Eclipse Neon funktioniert es nun endlich, vielen dank! =)

Ticket kann entsprechend zu.

Gruß und frohes Fest Ralf
