### ISSUE TITLE
minor UI issue: buttons misalignment

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#923]
![buttons_misalignment](https://user-images.githubusercontent.com/17204819/34440670-01728c86-ecb7-11e7-8d4f-8864ecae4716.png)
the buttons are cropped; sollten imo nebeneinander stehen &. vollständig sichtbar sein.

**Comment by sebasbaumh** [comment]
Das passiert, wenn das Chartfenster nicht hoch genug ist. Wenn man es vergrößert, tauchen sie dann unter den anderen auf.
Sie sollten also einfach nach links rücken, wenn sie nicht in eine Spalte passen statt nach rechts.
