### ISSUE TITLE
Fehler in der Bestandsberechnung

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#930]
unter Wertpapier Performance wird ein Bestand von 25 angezeigt:
![sshot-0](https://user-images.githubusercontent.com/17204819/34591018-c4d484e2-f1ba-11e7-91a8-f411b82ad9e4.png)
unter Vermögen taucht kein Bestand auf:
![sshot-2](https://user-images.githubusercontent.com/17204819/34591050-f2d571e4-f1ba-11e7-8154-e66ab6b077a8.png)
die Plausibilitätsprüfung erkennt kein Problem:
![sshot-1](https://user-images.githubusercontent.com/17204819/34591046-ec25e388-f1ba-11e7-8fdf-d51811eb627b.png)
LEIDER unterstützt das Programm bis dato keine Leerverkäufe, ergo sollte eine Prüfung durchlaufen werden und eine entsprechende Meldung erscheinen.

**Comment by tomcastro89** [comment]
Das Verrechnungskonto hat keinen Bestand, weil der Bestand sich auf Anteile bezieht. zB. 5 Coca-Cola Aktien, 3 US-Anleihen etc. In englischer Spache steht dort statt Bestand "Shares", also "Anteile". Die deutsche Übersetzung kann ich kurz anpassen.
