### ISSUE TITLE
Flatex PDF import 2018

### ISSUE THREAD

**Issue by up2go-sschwarz** [buchen/portfolio#932]
Auf den ersten Blick sehen 2017 und 2018 Dokumente gleich aus, aber nach dem (vermeintlich erfolgreichen) import werden die Käufe von 2018 leider nicht registriert.

**Comment by Ragas13** [comment]
Ok, aber ohne entsprechende Muster lässt sich der Konverter nicht anpassen. 

Siehe "Und andere PDF Dokumente?" @ https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38

**Comment by Tom0803** [comment]
Hallo,

ich habe unter folgendem Eintrag ein Beispiel gespostet:

https://forum.portfolio-performance.info/t/fehler-bei-pdf-import-flatex/2094/3

Ist das ausreichend oder kann ich noch etwas tun, um bei der Fehlersuche behilflich zu sein?

Viele Grüße
Tom

**Comment by Ragas13** [comment]
Hallo Tom,

jup, sollte ausreichend sein. :+1:

Gruß 
Marco

**Comment by Tom0803** [comment]
Das ist super! Würde der Fix dann in der nächsten Version enthalten sein?

**Comment by mega90** [comment]
Habe auch das selbe Problem beim Import.

Diese Zeile funktioniert:
Nr.99997489/1 Kauf ISHSIII-CORE MSCI WLD DLA (IE00B4L5Y983/A0RPWH

Diese Zeile funktioniert nicht:
Nr.106014935/1 Kauf IS C.MSCI EMIMI U.ETF DLA (IE00BKM4GZ66/A111X9)

Würde mich auch über einen schnellen Fix freuen, Danke.

**Comment by rhagspiel** [comment]
Wäre auch froh um eine baldige Lösung, denn das Programm ist wirklich der Hammer und ich möchte es gerne auch 2018 nutzen. Vielen Dank

**Comment by Tom0803** [comment]
Hallo!

Dem kann ich mich nur anschließen! PP ist echt ein Supertool und es macht richtig Spaß mit ihm zu arbeiten! Ich finde es richtig klasse, dass es hier als open source entwickelt wird. Für Leute, die sich selbst um ihre Finanzen kümmern wollen ist das echt das Beste, was es gibt!

**Comment by rhagspiel** [comment]
Absolut Weltklasse, vielen herzlichen Dank.

 

Grüsse

René

 

Von: Andreas Buchen [mailto:notifications@github.com] 
Gesendet: Montag, 22. Januar 2018 12:45
An: buchen/portfolio <portfolio@noreply.github.com>
Cc: rhagspiel <rhagspiel@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [buchen/portfolio] Flatex PDF import 2018 (#932)

 

Ich habe den Flatex Importer schon angepasst. Ich hoffe heute oder morgen Abend eine Version veröffentlichen zu können.

**Comment by buchen** [comment]
Komme jetzt nicht mehr dazu... :-(


Zum testen:

*win64* https://www.dropbox.com/s/9zej5r0cius90cw/PortfolioPerformance-0.28.5-SNAPSHOT-win32.win32.x86_64.zip?dl=0

*win32* https://www.dropbox.com/s/a51c9c7b52sr7u7/PortfolioPerformance-0.28.5-SNAPSHOT-win32.win32.x86.zip?dl=0

*macOS* https://www.dropbox.com/s/0shxurfv8wmwcv3/PortfolioPerformance-0.28.5-SNAPSHOT-macosx.cocoa.x86_64.tar.gz?dl=0

Fangt erst mal mit einer Kopie an. Das Format hat sich geändert, weil man Buchungen (Kauf, Verkauf) auch mit Uhrzeit erfassen kann.

**Comment by Tom0803** [comment]
Hi Andreas,

ich habe einige Importe getestet und bei mir hat alles wunderbar funktioniert! Echt klasse, vielen Dank!!

**Comment by rhagspiel** [comment]
Super vielen Dank, hat funktioniert.

 

Grüsse

René

 

Von: Andreas Buchen [mailto:notifications@github.com] 
Gesendet: Montag, 22. Januar 2018 22:40
An: buchen/portfolio <portfolio@noreply.github.com>
Cc: rhagspiel <rhagspiel@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [buchen/portfolio] Flatex PDF import 2018 (#932)

 

Komme jetzt nicht mehr dazu... :-(

Zum testen:

win64 https://www.dropbox.com/s/9zej5r0cius90cw/PortfolioPerformance-0.28.5-SNAPSHOT-win32.win32.x86_64.zip?dl=0

win32 https://www.dropbox.com/s/a51c9c7b52sr7u7/PortfolioPerformance-0.28.5-SNAPSHOT-win32.win32.x86.zip?dl=0

macOS https://www.dropbox.com/s/0shxurfv8wmwcv3/PortfolioPerformance-0.28.5-SNAPSHOT-macosx.cocoa.x86_64.tar.gz?dl=0

Fangt erst mal mit einer Kopie an. Das Format hat sich geändert, weil man Buchungen (Kauf, Verkauf) auch mit Uhrzeit erfassen kann.

**Comment by buchen** [comment]
Die gerade veröffentlichte Version 0.29.0 ist genau diese Testversion.

**Comment by psinger** [comment]
Neue Flatex Dokumente funktionieren, aber bei mir funktionieren alte nicht mehr. Alles vor Juli 2017 geht nicht.

**Comment by buchen** [comment]
Mmmhhh. Das muss daran liegen, dass wir nicht genug Beispiele für alte Dokumente haben. Denn eigentlich sollten die alten weiterhin importiert werden können.

Könntest Du ein Beispiel generieren und hier posten? (Oder ein neuen Issue aufmachen)
