### ISSUE TITLE
Falsche Berechnung einer einfachen Buchung

### ISSUE THREAD

**Issue by turborierer** [buchen/portfolio#938]
Ich habe eine Entnahme von meinem Konto gebucht und musste feststellen, dass der Endbetrag leider nicht kleiner, sondern um genau 999,24€ größer wurde. Lustiger weise genau der Betrag den ich zuvor als Einlage gebucht habe. Es scheint als hätte die identische Entnahme dazu geführt, dass die vorherigen 999,24€ erneut mit einberechnet wurden.

![bildschirmfoto 2018-01-31 um 22 22 00](https://user-images.githubusercontent.com/12324180/35648660-b91b5550-06d6-11e8-88d3-32dbe1c6e9c2.png)

**Comment by buchen** [comment]
Ich befürchte das ist ein Sortierungsproblem.

Am 12.1.**2017** hast Du 4.904,95 auf dem Konto.
Am 31.1.**2018** entnimmst du 278,04. Das macht dann einen Kontostand von 4.626,91.

Das Problem ist, dass die Buchungen vom 12.01. nicht richtig sortiert sind. Ist mir wohl bisher nicht aufgefallen, weil ich die neuste Buchung immer oben habe. Also umgekehrt sortiere.

Ist die Ansicht nach Datum sortiert?

**Comment by turborierer** [comment]
Tatsächlich, als ich neu sortiert habe stimmte die Rechnung wieder. Es war mir nicht aufgefallen, dass alle Gutschriften am gleichen Tag statt gefunden haben. 

Vielen Dank für den Tipp.
