### ISSUE TITLE
Historische Kurse Sortierung falsch/inkosistent bzw. geht nicht

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#942]
ich weiß nicht ob das jmd liest/interessiert, mir ist jdnfalls aufgefallen dass die Sortierung unterschiedlich/inkonsistent ist und nicht funktioniert wenn man auf den Tabellenkopf drückt.
![sort](https://user-images.githubusercontent.com/17204819/36647603-7311f3dc-1a88-11e8-9e29-553bde65e0c7.gif)

**Comment by buchen** [comment]
Das sollte ich beheben. Die Kurse werden momentan genauso angezeigt wie der Provider sie anliefert. Und manchen sortieren den aktuellsten Kurs zu erst, andere den ältesten Kurs. Das sollte aber in der Darstellung keinen Unterschied machen. Und sortieren sollte man auch können.

**Comment by buchen** [comment]
Wird jetzt immer absteigend sortiert.
