### ISSUE TITLE
Packaging for Gentoo

### ISSUE THREAD

**Issue by Anth0rx** [buchen/portfolio#947]
Hey there,
I am currently trying to provide a package of PP for Gentoo. However for their package manager portage they don't provide maven support. They preferably need an Ant build.xml to build Java packages with all their dependencies.
Would it be possible to provide such a build.xml file?

**Comment by buchen** [comment]
> Would it be possible to provide such a build.xml file?

No. Eclipse RCP applications are most easily build with Maven Tycho. All the dependency resolution is identical to what is done in the Eclipse IDE.

Can you run Maven within Ant?

**Comment by Anth0rx** [comment]
I don't think running Maven within Ant is encouraged in any way from reading the respective [Gentoo Java Packaging Policy](https://wiki.gentoo.org/wiki/Gentoo_Java_Packing_Policy#Java_Build_Systems).

**Comment by Anth0rx** [comment]
Can I tell Maven to not download the dependencies in form of binaries and instead build them all from source?
