### ISSUE TITLE
Feature Request: Ulcer Index als Risikomass

### ISSUE THREAD

**Issue by unclezero** [buchen/portfolio#948]
Hallo zusammen

Als Feature-Request würde ich gerne die Implementierung des Ulcer Index als Risikomass beliebt machen (http://www.tangotools.com/ui/ui.htm).

Der Ulcer Index zeigt im Gegensatz zur bekannten Volatilität den Drawdown an, als das Risiko, was den privaten Investor wirklich interressiert.

"Ulcer Index (UI) is a method for measuring investment risk that addresses the real concerns of investors, unlike the widely used standard deviation of return (SD). UI is a measure of the depth and duration of drawdowns in prices from earlier highs."

Wäre toll, wenn sich ein Programmier-Kundiger dem annehmen möchte.

Viele Grüsse

**Comment by Ragas13** [comment]
Im Dashboard kann man sich doch Daten zum Drawdown anzeigen lassen?

**Comment by unclezero** [comment]
Wenn es das Gleiche ist, schliesse ich diesen Issue.
Danke für die Info.
