### ISSUE TITLE
Fehler bei Zuweisung der Target Platform (Eclipse Oxygen 3)

### ISSUE THREAD

**Issue by Ragas13** [buchen/portfolio#950]
Mit dem Umstieg auf Eclipse Oxygen 3 erhalte ich bei der Zuweisung der Zielplattform Download Fehler: 
![eclipse - unable to locate installable unit](https://user-images.githubusercontent.com/29358155/38191486-761178f0-3658-11e8-93dc-19e701edb22d.jpg)

Ich habe Eclipse bereits komplett neu aufgesetzt und auch die Mylyn Plug-In Erweiterung nachinstalliert 😢 

Wo liegt der Fehler...

**Comment by buchen** [comment]
Sehr komisch. Die Meldungen sagen ja gar nix aus. Ich aktualisiere jetzt auch mal auf Oxygen 3.

**Comment by buchen** [comment]
Ich habe meine Eclipse Installation aktualisiert und damit kein Problem (also keine Neuinstallation, sondern eine Aktualisierung).

Vielleicht liegt es daran, dass man auf der Kommandozeile aktuell ```-Dtycho.disableP2Mirrors``` sagen muss. Ich weiß allerdings nicht was der analoge Parameter in der IDE ist.

Gibt es andere Fehler im Fehlerprotokoll? (Über *Window -> show View -> Error Log)

**Comment by Ragas13** [comment]
Hier einmal das Fehlerprotokoll von Eclipse Oxygen 3:
[Oxygen 3 - New Install - Error log.log](https://github.com/buchen/portfolio/files/1869076/Oxygen.3.-.New.Install.-.Error.log.log)

Nach dem ich einmalig unter Eclipse Neon die Platform zugewiesen habe, funktioniert es auch unter Oxygen. Anscheinend zieht Oxygen nicht das Plug-in "org.eclipse.pde.core", aber dank Neon läuft alles wieder 👍
