### ISSUE TITLE
ClientFactory.java uses a static salt

### ISSUE THREAD

**Issue by vraychev** [buchen/portfolio#952]
We were researching static analysis of code and came up to your usage of ciphers in ClientFactory.java . A static constant is salt is used, which may affect the security of the cipher. We believe it should be an easy fix to get it secured by generating salt with SecureRandom instead of using a constant one.

**Comment by buchen** [comment]
Thanks! Need to check.

This is a desktop application that (optionally) saves the data in an encrypted file. I was under the impression that I need the same salt the next time the program starts and I want to decrypt the file: "On decryption, the SecretKey is regenerated in exactly the same way, using using the password with the same salt and iteration parameters." ([StackOverflow](https://stackoverflow.com/a/992413))

**Comment by vraychev** [comment]
I have read a bit on the topic and there seem to be a few issues here.

First, the used salt for some crypto implementations is always zeros. e.g.
https://doridori.github.io/Android-Security-Beware-of-the-default-IV/#sthash.xfRKy62X.dpbs
http://www.win.tue.nl/pinpasjc/docs/apis/jc222/javacardx/crypto/Cipher.html#init%28javacard.security.Key,%20byte%29
https://stackoverflow.com/questions/20888851/does-aes-cbc-really-requires-iv-parameter

so the IV that is saved in the beginning of each file may be zeros defeting the purpose of IV.

Then, the salt. The idea of the salt is that if two passwords are the same, they get different keys. This avoid a dictionary attack - somebody guessing a password to decrypt. To solve this, the salt should be randomly generated should also be saved in the file.

**Comment by sebasbaumh** [comment]
@buchen : Yes you need the same salt to decrypt the file as you were using while encrypting it. But using a different/random salt will reduce the chance to execute a dictionary attack on the data (you would have to build one dictionary per salt, which is quite expensive compared to using one for all files).

After all I would not consider the same salt a big risk for the Portfolio application.
I mostly use random salts for hashing passwords to make it impossible to tell from two encrypted passwords for two different users if the passwords are equal. In that case you can just add the salt to the hashed password (and usually you also include the username to make the hash unique even for the same salt).

**Comment by Ragas13** [comment]
It's just an idea but is the so called "salt and pepper" method an option to solve this matter?

I've found the articleAES Encryption and Decryption Using a Password in Java](http://www.novixys.com/blog/aes-encryption-decryption-password-java/#4_Generate_the_Initialization_Vector_IV) which store at the file the random IV plus 8-byte salt. Concatenated with the user password used for the encryption / decryption process.

**Comment by buchen** [comment]
I tend to agree with @sebasbaumh. I do not think the same salt is a big problem, because it is unlikely that two users have exactly the same file. And what dictionary would you want to build for PP files? If I wanted to store the salt, then @Ragas13 proposal would be the way to go. For now, I will not change the binary file format and will close the ticket.

**Comment by vraychev** [comment]
The same salt would have been less of a problem if there IV were not zeros which is the case now. At least initializing the IV correctly can be done without change of the format.
