### ISSUE TITLE
PP does not update current prices via alpha vantage on Linux, Mac with same file works fine

### ISSUE THREAD

**Issue by mknudsen** [buchen/portfolio#953]
I have a mac and two linux machines. The latter fail to update the current prices via alpha vantage when opening the same portfolio xml. The file itself works fine on mac os.

I tried switching from OpenJDK to Oracel Java to no avail. PP just shows the numeber of remaining operations.

**Comment by buchen** [comment]
What is the error message in the error log (open via help menu)?

Did you configure the "AlphaVantage API key" on all machines? That key is not stored in the file.

**Comment by mknudsen** [comment]
It works after entering the alpha vantage API key.
