### ISSUE TITLE
Dividende: Tolltip oder Wert falsch

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#957]
angezeigt wird der Wert nach Steuern. Lt. Tooltip sollte der Bruttowert (3,65) angezeigt werden. Ergo stimmt der Tooltip oder der Wert nicht.
![dividende_tooltip_oder_wert_falsch](https://user-images.githubusercontent.com/17204819/38747053-e0cbade2-3f49-11e8-84cf-01e1636b2519.png)

**Comment by buchen** [comment]
Sehr komisch.

Ich habe testhalber die selbe Buchung erfasst und bei mir werden 3,65 angezeigt:

<img width="707" alt="bildschirmfoto 2018-04-22 um 15 01 34" src="https://user-images.githubusercontent.com/587976/39095274-19370f28-463e-11e8-86eb-11bb183f8e86.png">

Mir ist momentan nicht klar wo der Unterschied her kommen könnte... 🤔 
Welche PP version verwendest Du?
Könntest Du mir die Datei - nur mit diesem Wertpapier und dieser Buchung -zukommen lassen?

**Comment by megabugman** [comment]
das Problem ist repo in 0.30.1. Wie kann ich die Buchung (XML) zukommen lassen? Ich finde keine E-Mail Addresse? Die Buchung ist recht einfach:
![20180423235957](https://user-images.githubusercontent.com/17204819/39155487-86ee471a-4752-11e8-9e97-251a05ac1e51.PNG)

Im weiteren Tests dazu fielen weitere Probleme auf zB dass beim CSV Export die Stückzahl beim kauf unterschalgen wird (wurde von mir schon mal gemeldet wenn ich mich nicht irre) zudem stimmen die Umlaute nicht zB bei Stück (auch schon vermutlich von mir gemeldet):
![20180423234745](https://user-images.githubusercontent.com/17204819/39155600-eafe1578-4752-11e8-8fcb-67a50b16f427.PNG)

**Comment by buchen** [comment]
Die Buchung habe ich ja nachgestellt. Schicke die XML an *portfolio dot performance dot help at gmail dot com*

**Comment by megabugman** [comment]
Email sent. Cheers.

**Comment by buchen** [comment]
Behoben. Ich habe einfach an der falschen Stelle geschaut.
