### ISSUE TITLE
Kontosaldenverlauf nicht aktualisiert

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#962]
Nachdem alle Umsätze gelöscht wurden bleibt der Kontosaldenverlauf weiterhin sichtbar:
![aktualisieren2](https://user-images.githubusercontent.com/17204819/39157772-afa751b0-475c-11e8-8559-86c9622258d3.gif)

Zudem fällt auf dass die Grafik nicht genau ist. 
die gestrichelte Linie verläuft bei 2000, die Einzahlung war 2000, der Saldenverlauf verläuft jedoch tiefer.

**Comment by tomcastro89** [comment]
#1045

**Comment by buchen** [comment]
Fixed by @tomcastro89
