### ISSUE TITLE
Unterstützung von mehreren JDK-Versionen

### ISSUE THREAD

**Issue by obfischer** [buchen/portfolio#964]
Durch meine Arbeit als Softwareenwickler bedingt habe ich mehrere JDK-Versionen, auch EA-Releases, auf meinem Mac installiert. Leider kann PP so nicht starten, da derzeit JDK 8 vorausgesetzt wird. 

Ich habe `JAVA_HOME` explizit gesetzt und PP von der Befehlszeile ausgestartet. Dennoch startete PP mit JDK 11 EA.

Es wäre wünschenswert, wenn PP solche Konstellationen unterstützen würde und es einen expliziten Weg gäbe das JDK manuelle festzulegen.

**Comment by buchen** [comment]
Das kann man in der PortfolioPerformance.ini konfigurieren:

https://forum.portfolio-performance.info/t/beim-starten-bekomme-ich-den-fehler-exit-code-13-was-nun/15/5
