### ISSUE TITLE
Text auschneiden in Notiz via Ctrl+x öffnet PDF Import Assi

### ISSUE THREAD

**Issue by megabugman** [buchen/portfolio#970]
Erwartung: anstatt dem Assi sollte der Text ausgeschnitten werden... dies passiert übrigens nicht nur im Notiz Feld.
![ctrlx](https://user-images.githubusercontent.com/17204819/39836744-b2949962-53d4-11e8-808b-9d0ac847806a.gif)

**Comment by buchen** [comment]
Arrrgh. Ich glaube wir haben auf "Ctrl-X" den PDF Import gelegt. Das ist natürlich Quatsch. Schaue ich mir an.
