### ISSUE TITLE
Cannot enter TER for ETF

### ISSUE THREAD

**Issue by konfri** [buchen/portfolio#982]
Hey Guys :)

thanks for the effort and the nice tool 👍 

While trying to set the TER, I'm getting and parsing exception.

![screen shot 2018-05-18 at 08 55 53](https://user-images.githubusercontent.com/16843990/40220534-c002f9e4-5a79-11e8-91ed-b83c8ca50396.jpg)

Is this expected? I also tried 0,19% but same effect. 

Thank you! :)

**Comment by buchen** [comment]
Ich bin noch ratlos... 🤔 

Siehe auch hier: https://forum.portfolio-performance.info/t/java-text-parseexception-bei-eingabe-der-gesamtkostenquote-ter/2631/19

**Comment by buchen** [comment]
Scheint wohl an Java 9 zu liegen. Ich habe es jetzt behoben.
