### ISSUE TITLE
DKB Dividenden PDF-Import "Ausschüttung Investmentfonds"

### ISSUE THREAD

**Issue by razza-guhl** [buchen/portfolio#988]
Der Import von einen PDF-Dokument "WKN_xxx_Ertragsabrechnung_Fonds_vom_xx.xx.xxxx_zu_Depot_xxx" mit dem Titel "Ausschüttung Investmentfonds" schlägt mit folgender Meldung fehl:

```
Mon Jun 04 15:48:24 CEST 2018
Unbekannter oder nicht unterstützter Buchungstyp in Datei 'WKN_xxx_Ertragsabrechnung_Fonds_vom_xx.xx.xxxx_zu_Depot_xxx_-_Belegnr._xxx.pdf'

java.lang.UnsupportedOperationException: Unbekannter oder nicht unterstützter Buchungstyp in Datei 'WKN_xxx_Ertragsabrechnung_Fonds_vom_xx.xx.xxxx_zu_Depot_xxx_-_Belegnr._xxx.pdf'

	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:106)

	at name.abuchen.portfolio.datatransfer.pdf.AbstractPDFExtractor.extract(AbstractPDFExtractor.java:85)

	at name.abuchen.portfolio.ui.wizards.datatransfer.ReviewExtractedItemsPage$11.run(ReviewExtractedItemsPage.java:579)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)


```

Die manuelle Auswahl vom Broker/Bank auf "DKB" hat nicht geholfen.

Text aus PDF (anonymisiert):

```
PDF Author: '' 
PDFBox Version: 1.8.13
-----------------------------------------
10919 Berlin
Depotnummer 123456789
Kundennummer 0987654321
Max Mustermann
Herrn Abrechnungsnr. 12345678901Datum 31.05.2018
Max Mustermann
Hollander Strasse 71
65558 Hirschberg
Ausschüttung Investmentfonds
Nominale Wertpapierbezeichnung ISIN (WKN)
Stück 10 iShares Core MSCI World UCITS ETF USD IE00B4L5Y983 (A0RPWH)
REGISTERED SHARES O.N.
Zahlbarkeitstag 01.06.2018 Ausschüttung pro St. 0,395700000 EUR
Bestandsstichtag 11.05.2018 Herkunftsland Irland
Ex-Tag 12.05.2018
Geschäftsjahr 01.01.2018 - 31.10.2018
Ausschüttung 4,10+ EUR
Kapitalertragsteuerpflichtiger Ertrag 4,10 EUR
Berechnungsgrundlage für die Kapitalertragsteuer 4,10 EUR
Kapitalertragsteuer 25 % auf 4,10 EUR 1,03- EUR
Solidaritätszuschlag 5,5 % auf 1,03 EUR 0,05- EUR
Ausmachender Betrag 3,02+ EUR
Lagerstelle Clearstream Banking Lux (849133 / 64003)
Den Betrag buchen wir mit Wertstellung 01.06.2018 zu Gunsten des Kontos 1234567890 (IBAN DE28 1234 4536 7890
1234 56), BLZ 120 300 00 (BIC BYLADEM1001).
Keine Steuerbescheinigung.
Nachrichtlich die Übersicht Ihrer Verrechnungs- und Steuertopfsalden zum Zeitpunkt der Erstellung der Abrechnung.
Verrechnungstöpfe 2018 Berechnungsgrundlage
der gezahlten Steuern
Euro Aktien Sonstige Sparer- anrechenbare Aktien und Sonstige
Pauschbetrag Quellensteuer
Ertrag 0,00 0,00 0,00 0,00 4,10
Vorher 0,00 0,00 0,00 0,00 0,00
Nachher 0,00 0,00 0,00 0,00 4,10
Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.
Bitte ggf. Rückseite beachten.
0883.04250100.0000725ER03
```
Getestet wurde mit der Version 0.31.2.

Vielen Dank für diese tolle Software!

**Comment by ZfT2** [comment]
Ich schau mir das mal an, dauert aber ein bisschen...

**Comment by razza-guhl** [comment]
Klasse, vielen Dank.

**Comment by ZfT2** [comment]
der referenzierte PR sollte es dann beheben :)

**Comment by razza-guhl** [comment]
Herzlichen Dank, es funktioniert jetzt

**Comment by Frameset91** [comment]
Hallo,
ich habe mir diesen Thread, sowie die referenzierten Threads angeschaut, leider habe ich in der aktuellen Version 0.38.0 (win32, x86_64) immernoch das Problem, dass ich eine Dividendenzahlung nicht importieren kann. Problem hierbei ist, dass der ETF auf EUR lautet und der Import in USD angegeben wird.

Die Fehlermeldung sagt:
![image](https://user-images.githubusercontent.com/2315756/52400430-66016b80-2abf-11e9-94cc-0dbbc236ed11.png)

Der Textimport sieht so aus:
 
PDF author: ''
PDFBox Version: 1.8.16
-----------------------------------------
10919 Berlin Seite 1
Depotnummer 123456789
Kundennummer 0101010101
Max Mustermann
Abrechnungsnr. 8127381273
Herrn Datum 19.02.2015
Max Mustermann
Muster Str. 1
12345 Musterstadt
Gutschrift von Investmenterträgen
Nominale Wertpapierbezeichnung ISIN (WKN)
Stück 53 IS.II-DEV.MARK.PR.YLD. UC. ETF DE000A0LGQL5 (A0LGQL)
BEARER SHARES (DT. ZERT.) O.N.
Zahlbarkeitstag 19.02.2015 Ertrag pro St. 0,167900000 USD
Bestandsstichtag 28.01.2015 Zinsanteil pro St. 0,012194300 USD
Ex-Tag 29.01.2015 Ausländischer Dividenden- und Veräußerungs-
Geschäftsjahr 01.11.2014 - 31.10.2015 gewinnanteil pro St. 0,190620200 USD
Devisenkurs EUR / USD 1,1426 Herkunftsland Irland
Ausschüttung 8,90 USD 7,79+ EUR
Anrechenbare Quellensteuer pro Stück 0,015993 USD 0,85 USD
Kapitalertragsteuerpflichtiger Zinsanteil gesamt 0,65 USD
Umrechnung in EUR 0,57 EUR
Eingebuchte sonstige negative Kapitalerträge 0,57 - EUR
Berechnungsgrundlage für die Kapitalertragsteuer 0,00 EUR
Kapitalertragsteuerpflichtiger ausländischer Dividenden-
und Veräußerungsgewinnanteil gesamt 10,10 USD
Umrechnung in EUR 8,84 EUR
Eingebuchte sonstige negative Kapitalerträge 8,84 - EUR
Berechnungsgrundlage für die Kapitalertragsteuer 0,00 EUR
Ausmachender Betrag 7,79+ EUR
Lagerstelle Clearstream Banking FFM (849000 / 4003)
Den Betrag buchen wir mit Wertstellung 23.02.2015 zu Gunsten des Kontos 1234567890 (IBAN DE52 1203 0000 1234
5678 90), BLZ 120 300 00 (BIC BYLADEM1001).
Keine Steuerbescheinigung.
Bitte ggf. Rückseite beachten.
1234.12345678.1234567AB12

Seite 2
Depotnummer 123456789
Kundennummer 0101010101
Abrechnungsnr. 8127381273
Datum 19.02.2015
Nachrichtlich die Übersicht Ihrer Verrechnungs- und Steuertopfsalden zum Zeitpunkt der Erstellung der Abrechnung.
Verrechnungstöpfe 2015 Berechnungsgrundlage
der gezahlten Steuern
Euro Aktien Sonstige Sparer- anrechenbare Aktien und Sonstige
Pauschbetrag Quellensteuer
Vorher 0,00 731,52 300,00 0,00 0,00
Ertrag 0,00 9,41- 0,00 0,74 0,00
Nachher 0,00 722,11 300,00 0,74 0,00
Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.
1234.12345678.1234567AB12

**Comment by ZfT2** [comment]
Hab eine Kleinigkeit angepasst damit der Umrechnungskurs auch in Deinem Fall erkannt wird.

PR dazu ist hier: 
https://github.com/buchen/portfolio/pull/1111
