### ISSUE TITLE
Periodizität immer aus gesamter Datenbasis ermitteln

### ISSUE THREAD

**Issue by sebasbaumh** [buchen/portfolio#994]
Damit es nicht verloren geht, aus dem [Forum](https://forum.portfolio-performance.info/t/dividenden-quartal/2882/15):

_Die Zahlungen erfolgen doch jedes Jahr in der gleichen Periodizität, warum zieht er sich dann nicht einfach die Periodizität aus allen Daten. Ist halt schade, wenn man sich die Ansicht nur auf “1 Jahr” ansehen möchte und dann überall “unbekannt” oder “keine” steht._

Die Periodizität sollte immer aus der gesamten Datenbasis ermittelt werden, auch wenn ein kürzerer Zeitraum im Filter ist
Eigentlich ist sie auch eine "Stammeigenschaft", die unabhängig vom Filter sein sollte?

**Comment by sebasbaumh** [comment]
>Aber im Prinzip ist man dann auch immer noch davon abhängig, dass tatsächlich Wertpapiere gehalten werden. 

Ja, das ist auch ein Thema. Theoretisch müsste man Dividenden getrennt von den Wertpapieren erfassen können - analog zu den Kursen. Ich denke nur, dass es schwierig wird, das automatisiert einzutragen.
Eventuell aus eine Webseite wie [hier](https://www.finanzen.net/dividende/Daimler).

**Comment by buchen** [comment]
Yahoo Finance hat auch Dividendenereignisse - mal mehr und mal weniger gut gepflegt.

Unabhängig davon ist der erste Schritt die Berechnung auf _alle_ Buchungen auszudehnen.

**Comment by buchen** [comment]
Merged.
