### ISSUE TITLE
„PortfolioPerformance.app“ ist beschädigt und kann nicht geöffnet werden

### ISSUE THREAD

**Issue by IV1T3** [buchen/portfolio#999]
> „PortfolioPerformance.app“ ist beschädigt und kann nicht geöffnet werden. Es empfiehlt sich, das Objekt in den Papierkorb zu bewegen.

Diese Nachricht bekomme ich, wenn ich die App nach dem Download (https://bintray.com/buchen/downloads/download_file?file_path=0.32.0%2FPortfolioPerformance-distro-0.32.0-macosx.cocoa.x86_64.tar.gz) zum ersten Mal öffnen möchte.

**Comment by Ragas13** [comment]
Der Fehler wird durch einen fehlerhaften Download hervor gerufen. Wenn du die Datei erneut lädst, sollte es funktionieren. Andernfalls stört etwas den reibungslosen Download.

**Comment by IV1TR0** [comment]
Der Fehler ist nun schon in verschiedenen Netzwerken, durch verschiedene Browser und an unterschiedlichen Tagen sogar Moaten aufgetreten. Außerdem habe ich es mit zwei unterschiedlichen Archivierungsprogrammen entpackt, trotzdem tritt der Fehler immer noch auf.

**Comment by IV1T3** [comment]
Dieses Problem taucht ab Release 0.33.1 nicht mehr auf.

**Comment by buchen** [comment]
Grund ist meines Wissens der Gatekeeper. Da ich PP nicht signiere meckert je nach Einstellung.
